var new_lang = {
   lt0: 'Hypertension et les sauts de tension qu’elle déclenche - dans les 89% des cas mène le patient à la mort de l"infarctus ou l"attaque cérébrale!',
    lt1: 'Ministère de la santé de France',
    lt4: 'Santé',
    lt5: 'Activité',
    lt6: 'Documents',
    lt7: 'Centre de presse',
    lt8: 'Concours',
    lt9: 'Principale',
    lt10: 'Centre de presse',
    lt11: 'Actualités',
    lt12: 'L’hypertension et les sauts tension qu’elle déclenche - dans 89% des cas mène tuent le patient à la mort de l"infarctus ou l"attaque cérébrale!',
    lt13:  'L’hypertension et les sauts tension provoqués – resteront dans le passé!',
    lt14: 'l’infarctus et les attaques cérébrales – dans 70% sont causes de tous les décès.  Les 7 personnes sur 10 meurent pour cause de thrombose des artères du cœur et du cerveau. Pratiquement dans tout les cas la cause d’une fin si terrible est seule – les sauts de tension d’hypertension. "Tueur doux", comme les cardiologue l’ont nommé, tous les ans emporte des millions de vies. ',
    lt15: 'Véranda Martin Olivier',
    lt16: 'Docteur-cardiochirurgien, inventeur, organisateur de la science médicale, pédagogue, professeur, académicien.',
    lt17: 'Expérience de travail - 48 ans ',
    lt18: 'Sur le problème:',
    lt19: 'Ceci n’est pas un secret, que les maladies cardio-vasculaires – sont parmi celles qui emportent le plus grand nombre de vies. De cette façon l’hypertension se présente en tant que cause d’infarctus et des attaques cérébrales essentielle. Certain, les autres maladies se manifestent dans l’organisme également, c’est surtout l’hypertension et les sauts de tension qu’elle provoque est le déclencheur, qui fait partir dans le grand voyage.',
    lt20: 'Si l’on parlait des paramètres signifiants, alors environ <strong> 77-78% de décès "naturels", ont pour cause justement l’hypertension. </strong> Aux chiffres absolus, c’est environ 1,54 millions de morts en 2015 et 1,49 millions en 2014. C’est à dire les chiffres sont réellement colossales et effrayants. Jusqu’à ce dernier temps personne ne réalisait les dimensions de la catastrophe, car une statistique détaillée ou une analyse n’avaient pas eu lieu. Pendant la période entre 2011 et 2015 nous avons recueilli une géante archive de données, qui ont permis de faire des conclusions assez décevantes.',
    lt21: 'Les sauts de tension chaque fois provoquent les surcharges colossales du muscle du cœur, qui mènent à un moment à l’arrêt cardial. En gros, dans tout les cas la tension cardiale mène à la surcharge du cœur de 10-20 fois. Si l’on parlait de la fin du développement de la maladie, alors,',
    lt22: 'l’hypertension mène toujours au même résultat – à la mort',
    lt23: 'Bien que, si on la pointait comme cause clé de décès, cela a lieu dans 89% des cas. C’est à dire que dans 89% des cas d’hypertension se termine par infarctus ou attaque et le décès de la personne. En outre, si il y a 20-30 ans les patients avec un tel diagnostique n’avait que 10-20 ans de l’espérance de vie, actuellement environ deux tiers s’en vont pendant les 5 premières années de développement de la maladie.',
    lt24: '2/3 (deux tiers) des patients décède pendant les 5 premières années de développement de la maladie. ',
    lt25: 'Sur le fait, c’est surtout terrifiant, qu’une masse de personnes ne sont même pas conscientes d’avoir de l’hypertension. Et ils perdent la possibilité de corriger une chose, se condamnant au décès simplement.',
    lt26: 'C’est avec ces symptômes que vous pourrez définir si vous avez de l’hypetension:',
    lt27: 'Maux de tête',
    lt28: 'Rythme cardiaque accéléré ',
    lt29: 'Taches noire dans les yeux  (moucherons)',
    lt30: 'Apathie, irritabilité, somnolence',
    lt31: 'Vision brouillée',
    lt32: 'Sudation',
    lt33: 'Fatigue chronique',
    lt34: 'Enflements de visage',
    lt35: 'Torpidité et rigor des doigts',
    lt36: 'Sauts de tension',
    lt37: 'Un seul des deux symptômes devrait vous mettre en garde. Et si  ',
    lt38: 'il y a deux, n’ayez pas de doute – vous avez de l’hypertension',
    lt39: 'Par ailleurs, selon les statistiques, ',
    lt40: '67% des hypertoniques ne savent pas d’être malades.',
    lt41: 'Comment est ce qu’on peut se protéger et vaincre la maladie?',
    lt42: 'Avant tout il faut comprendre, qu’il faut abandonner un grand nombre de vos mauvaises habitudes, surtout le tabagisme et l’alcool. Cela altèrent encore plus la situation avec la tension artérielle. Fait suivant – rabattre de force la tension est possible et nécessaire, impossible autrement. Mais cela ne soigne pas la maladie même. En outre, si l’on abuse des médicaments et obtient une baisse de tension brusque, cela peut provoquer une réaction extrêmement négative de l’organisme allant jusqu’à l’infarctus même. Et cela sans parler de ce que les médicaments créent une charge élevée sur le foie.',
    lt43: 'Proprement dit, en ce moment, le seul remède, promu officiellement des médecins pour le traitement de l’hypertension est le même qu’emploient les cardiologues dans leur travail – c’est<a href=""><strong>le XX</strong></a>. Son élaboration, commencée encore quelques années auparavant, est terminée récemment. Une équipe des spécialistes s’est occupé de sa création, en collaboration étroite avec les cardiologues pratiquants. Finalement un remède unique de ses paramètres, « suppressant » avec certitude l’hypertension et éliminant sa cause, comparable à tout autre produit.',
    lt44: 'En 2016, dans le centre Scientifico-pratique de cardiologie et cardiochirurgie, faisant parti du centre de recherche scientifique sur la médecine prophylactique d’Etat sont mènes à leur fin avec succès les essaies cliniques du produit de la nouvelle génération - <a href=""><strong>le XX</strong></a>, créé pour lutter contre l’hypertension. Le service de presse de l’institut a rendu publique ce qui suit:',
    lt45: '1.Efficacité de XX, calculée selon la méthode de standard (nombre des guéris par rapport au nombre total du groupe de 100 personnes, ayant suivi la cure) a constitué:',
    lt46: ' –	Normalisation de tension – 97%',
    lt47: ' –	Elimination de la thrombose de vaines – 80%.',
    lt48: ' –	Elimination des palpitations fortes – 99%',
    lt49: ' –	Elimination de maux de tête – 100%',
    lt50: ' –	Hausse de vigueur la journée, amélioration de sommeil la nuit – 97%.',
    lt51: '*On entend dans ce cas que la guérison inclut la suppression de tous les symptômes et l’absence de récidive pendant 6 mois.',
    lt52: '2.	Les effets secondaires indésirables, y compris les réactions allergéniques n’ont pas été détectés.',
    lt53: '3.	Le XX est reconnu comme principal produit luttant contre l’hypertension.',
    lt54: 'Brigadier Jean-Philippe',
    lt55: 'Directeur du Scientifico-pratique centre de cardiologie et cardiochirurgie. Professeur.',
    lt56: 'Expérience de travail - 29 ans',
    lt57: 'Les collaborateurs de notre institut ont établi, que le produit agit sur la cause de la maladie, grâce à quoi s’ouvre une perspective de guérison définitive de l’hypertension. La symptomatique est éliminée entièrement dans les six premières heures après l’application grâce à sa composante active. Cela offre la possibilité de respirer profondément immédiatement après le commencement de la cure, comme l’on dit.',
    lt58: 'Le tonus des vaisseaux se restaure entièrement à la suite d’une cure. De plus le XX est efficace à tout stade de l’hypertension. Le remède a naturellement subi des essais cliniques. Je veux noter, que l’efficacité manifestée dans le processus d’épreuve vaincra tout produit étranger. Le meilleur résultat chez les médicaments occidentaux – 20-21% de soignés. Dans notre cas il s’agit des 75-77% de soignés. Les autres obtiennent une simple stabilisation. L’hypertension se conserve dans son état germinal (le problème de tonus des vaisseaux). Bien qu’avec ça vous n’avez pas de sauts de tension et vous vous sentez simplement merveilleux.',
    lt59: 'Outre la Russie, le XX a passé des épreuves cliniques en Suisse et en Allemagne, qui ont aussi confirmé son efficacité. Actuellement il y a une demande colossale sur ce produit. Or, selon un ordre spécial, il est uniquement vendu à l’intérieur de notre pays, ce qui est lié aux quantités modestes de production, n’étant pas prêt à un niveau de demande pareil.',
    lt60: 'A présent le médicament est produit en petites parties, bien que le producteur est déjà en train de construire des nouvelles puissances qui permettront de multiplier de plusieurs fois. ',
    lt61: 'En ce moment le produit original<strong>le XX</strong>est possible de commander<a href=""><strong>au travers du site du producteur</strong></a>.',
    lt62: '194 commentaires',
    lt63: 'Claire Débord',
    lt64: 'La première fois j’ai entendu parler du produit il y a trois mois et l’ai commandé de suite. J’avais les problèmes très graves liés à la tension. Et, dés le premier jour de prise – pas une fois je n’ai plus eu de sursauts. Je profite simplement de la vie.',
    lt65: 'il y a 12 minutes',
    lt66: 'Bruno Lachapelle',
    lt67: 'Aussi je l’achetais pour ma grand-mère – elle a toujours eu des problèmes de tension. Elle-même, je doute qu’elle puisse arriver à commander quelque choses sur internet, même par téléphone. Alors, je fais pour lui. Je peux vous assurer qu’elle est guérie à 100%, bien que les problèmes étaient anciens et généraux – elle fonctionnait grâce aux médicaments pendant plusieurs années.',
    lt68: 'il y a 17 minutes',
    lt69: 'Missis Smit',
    lt70: 'J’ai lu dans un magazine de médecine sur ce produit. Il y a eu un article d’expert, si je ne me trompe pas, et le voilà...',
    lt71: 'il y a 19 minutes',
    lt72: 'Christine',
    lt73: 'J’ai aussi entendu quelque part vaguement. Quelqu’un de mes connaissances commandait pour soi, il me semble. Moi-même j’ai les problèmes de tension cela fait 2-ème année, je viens de lire maintenant – j’ai failli m’évanouir. Vais remplir la commande de suite, autant de l’essayer. ',
    lt74: 'il y a 21 minutes',
    lt75: 'Simon',
    lt76: 'A commandé aussi. Il ont garanti de livrer au bout d’une semaine (à Narbonne), on va patienter donc ',
    lt77: 'il y 25 minutes',
    lt78: 'Gaëlle',
    lt79: 'Je viens de passer une commande pour 2 cures à la fois. Dans ma famille sur la ligne féminine toutes ont les problèmes de tension. Le plus souvent les décès ont l’infarctus pour cause.',
    lt80: 'il y a 27 minutes',
    lt81: 'Adeline  Poirrier',
    lt82: 'Tout juste hier j’ai regardé un reportage à la télé sur cela. On disait que nos médecins ont créé un bon remède contre l’hypertonie.',
    lt83: 'il y a 30 minutes',
    lt84: 'Alex',
    lt85: 'Dans ma famille presque toutes les femmes sont décédées suite à l’infarctus. Toutes elles avaient des problèmes de tension. Même sur la ligne masculine, nombreux alors étaient à avoir cela. Vais laisser une demande aussi.',
    lt86: 'il y a 34 minutes',
    lt87: 'Men',
    lt88: 'j’espère, que le médicament restera au même prix, et pas de 30 000 roubles par cure.',
    lt89: 'il y a 39 minutes',
    lt90: 'Sabine',
    lt91: 'J’ai fait la commande pour ma sœur il y a deux mois encore. Elle a souffert pendant longtemps de l’hypertension. Si vous saviez qu’est-ce qu’elle m’était reconnaissante d’avoir pris le risque et d’avoir commandé le médicament.',
    lt92: 'il y a 42 minutes',
    lt93: 'Irène Chignon',
    lt94: 'J’ai tout en norme au niveau de la tension, mais ma mère en souffre tout le temps. Vais en commander pour elle – j’espère que ça aide.',
    lt95: 'il y a 1 heure',
    lt96: 'Aurèlie Pépère ',
    lt97: 'Je me sens beaucoup mieux à la suite de l’usage, comme si j’été rajeunie. Tout cela a eu de l’impacte sur l’apparence. Mon corps est devenu revigoré et plus sain.',
    lt98: 'il y a 1 heure',
    lt99: 'Jérémie',
    lt100: 'C’est simplement un miracle, oui. J’ai commandé le XX dès que j’en ai entendu. C’est dommage juste, que je n’en savais rien il y a 5 ans, de longues années j’ai souffert des douleurs, mais en ce moment je suis sauf et sain ! Ouvert au monde ! Un grand merci.',
    lt101: 'il y a 1 heure',
    lt102: 'Christian Corbin',
    lt103: 'J’ai vu un grand nombre de retours sur le XX lorsque je passais devant. Et là un ami est venu se plaindre d’un problème similaire. Alors, je pense, qu’il faut le lui conseiller peut-être aussi?',
    lt104: 'il y a 1 heure',
    lt105: 'Natalie Mignon',
    lt106: 'Cela a aidé mon mari ! La tension s’est stabilisée ! Seulement 3  fioles ont suffit. Désormais je le commanderai pour soi ! Il soigne parfaitement.',
    lt107: 'il y a 1 heure',
    lt108: 'C’est génial! Il faut le commander, car j’en ai assez de souffrir de la tension!',
    lt109: 'il y a 2 heures',
    lt110: 'anaïs816',
    lt111: 'Vous n’allez pas me croire, moi aussi j’ai eu pareil problème, le manque de l’énergie permanent, j’ai complètement perdu la joie de vivre, étais désespérée et là le XX, ce produit miracle, je le conseille à tous.',
    lt112: 'il y a 2 heures',
    lt113: 'Serge',
    lt114: 'Le radin paye 2 fois. J’ai trouvé l’information sur le XX, mais n’ai pas commandé. J’ai décidé de m’en procurer sur les larges d’internet, moins cher. J’ai trouvé une partie de faux. Finalement, après m’avoir secoué les puces je l’ai commandé sur le site officiel. Etrangement, mais il a été livré instantanément, ce qui est inhabituel pour notre poste. Merci à Vous.',
    lt115: 'il y a 3 heures',


};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};