var new_lang =   {
"lt00": "Kates Grēviņas blogs. Kā pagarināt seksa laiku!",
"lt0": "SEKSS ar vīru tagad ilgst līdz pat 2 stundām! 3 minūšu vietā!!!",
"lt1": "<a href=\"\" style=\"font-weight: normal; text-decoration: none; color: rgb(0, 0, 0); cursor: pointer;\" target=\"_top\">Publicēts</a><span class=\"startdate\">11.03.2014, 19:51</span>| Autors:<a class=\"yelpay-target\" href=\"\" style=\"cursor: pointer;\" target=\"_top\">kate</a>",
"lt2": "Sveiki, draugi! Vai atcerējāties, ka pirms pusgada es sūdzējos, ka mans vīrs<strong>ļoti</strong><strong>ātri beidz</strong>seksa laikā? Pat vienkāršas masturbācijas laikā viņš<strong>ātri beidz</strong>, pat<strong>pēc 1-4 minūtēm!</strong>",
"lt3": "Vēl es cepos par to, ka viņam<strong>slikti ceļas</strong>un viņa izmērs<strong>nav īpaši liels</strong>. Ja ieskatīties porno filmas, tad tur tādi agregāti vīriešiem – gari un spēcīgie.",
"lt4": "Ieklausījos jūsu padomus, vīrs izmēģinājis visu iespējamo: sakot no viagras un citām tabletēm līdz jogas praksēm un tantriskiem rituāliem. Pilnīgs sviests! Sekss kā bija<strong>1-3 minūtes</strong>, tā arī palicis. Loceklis kā iepriekš bijis maziņš un slikti stāvošs!",
"lt5": "Es nomierinājos ar to, un <a href=\"\" style=\"font-weight: normal; text-decoration: none; color: rgb(0, 0, 0); cursor: pointer;\" target=\"_top\">’’norakstīju’’</a>to visu uz vīra ģenētiku un <b>veselības stāvokli</b>. Laikam, tas viss iet no mūsu gēniem. Pamanīju, ka vīram pat komplekss uzsācis veidoties...",
"lt6": "Glābšana nonāca nav gaidīta…",
"lt7": "Pagājis apmēram pusgads, un nejausi es ‘’uzduros’’ uz porno aktiera <b>Pjera Vudmāna (noteikti esat dzirdējuši par viņu)<b> interviju vienā slavenā žurnālā. Viņš stāstījis, ka cilvēks spējīgs<strong> nodarboties ar seksu līdz 2 stundām</strong>, tāda gadījumā arī loceklis stāvēs labi! Papildus tam, ir iespējami<strong>palielināt izmēru par 5 cm</strong>. Tieši tas, kas man bijis vajadzīgs.",
"lt8": 'Pēc viņa teikta, tik ilgām dzimumaktam cilvēka ķermenim nepieciešams <b> \"Muira Puamas\ekstrakts"</b>. (koks, kuru Dienvidamerikā dzīvojoši indiāni izmantojuši potences uzlabošanai), nonākot saskarsmē ar cilvēka ķermeni – tas pastiprina dzimumhormonu izdali simtos reizēs. Pateicoties tam, jūsu orgasmi būs tādi, kā porno filmās. Papildus tam, šis krēms<strong>palielina locekli 1 nedēļas laikā par 3-5 cm</strong>(spriežot pēc viņa vārdiem)!',
"lt9": " Pjers Vudmāns ieteicis lietot specialo krēmu ar šo ekstraktu-<b>\"XX\"</b>. Pēc viņa teikta, tikai šī zīmola krēms satur šo koka dabisko ekstraktu, viss pārējais – no ķīmijas izgatavoti nestrādājoši viltojumi.",
"lt10": "Izlasot šo rakstu, uzreiz skrienu pasūtīt krēmu. Latvijas teritorijā eksistē tikai viens sertificēts  uzņēmums, kas tirgo šo krēmu\"XX\" -<a href=\"\" style=\"cursor: pointer;\" target=\"_top\"><b>lūk ir links uz viņu mājas lapu</b></a>.",
"lt11": "Noformēju pasūtījumu, sūtījumu saņemu pastā ar pēcapmaksu pēc dažām dienām. Viss ir droši.",
"lt12": "Kāds ir rezultāts?",
"lt13": "Izņemu no iepakojuma, iedevu vīram un nolēmu pārbaudīt krēma efektivitāti.",
"lt14": "Kopā notestējam rezultātu: mīļojāmies <strong>1 stundu 47 minūtes</strong>, un orgasma brīdis ir klāt…nu….<b>KLIEZĀM KOPĀ PA VISU MĀJU, NEREĀLA BAUDA</b>!!!! Nekad savā dzīvē neesmu jutusi neko tādu! Protams ticēju, ka rezultāts būs, bet to, ka tas būs<b>TIK</b>spēcīgs - pat<a href=\"\" style=\"font-weight: normal; text-decoration: none; color: rgb(0, 0, 0); cursor: pointer;\" target=\"_top\">iedomāties</a>nevarēju.",
"lt15": "Pēc krēma divām lietošanas nedēļām, esam  pamanījuši, ka<strong>vīra dzimumloceklis palielinājās par 5 cm</strong>! Mēs bijam šokā, tas bija<strong>pārsteidzošs rezultāts</strong>!",
"lt16": "Tā lūk arī notiek. Nekad pat nevarēju iedomāties, ka kaut kāds augu ekstrakts spējīgs tik spēcīgi ietekmēt uz mūsu ķermeni. Krēma cena līdzīga 2 kino biļetēm. Domājiet paši – vai tas ir daudz vai maz, ņemot vērā kino pilnīgu bezjēdzību.<b>NETAUPIET BAUDAS RĒĶINĀ</b>.",
"lt17": "Lūk, draugi, visiem ieteicu izmēģināt šo <a href=\"\" style=\"cursor: pointer;\" target=\"_top\"><b>XX</b></a>! Novēlu veiksmi! Ja kāds jau lieto šo krēmu, rakstiet savas atsauksmes.",
"lt18": "Pasūtīt krēmu!",
"lt19": "194 komentāri",
"lt20": "Aleks Zariņš",
"lt21": "Paldies, Kate)) neesmu gaidījis tādu ierakstu blogā)) runājot par tēmu – pirms gada neko par šo krēmu neesmu zinājis. Baigi apmierināts. Orgasmi -  pilnīgs kosmoss!)) Loceklis bijis 14 cm, kļuvis 18 cm!<br><img src=\"photo-4.jpg\">",
"lt22": "pirms 4 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt23": "Edža Ed",
"lt24": "Paldies Katei, vakar izņēmu no pasta savu sūtījumu, viss labi))",
"lt25": "pirms 6 minūtēm|<span class=\"vk-comment-answer\">Komentēt</span>",
"lt26": "Andžejs Riekstiņš",
"lt27": "Brālis dzīvo Amerikā, stāsta, ka tur šis krēms ir ĻOTI populārs…It ka visi sajūsmā… nu nezinu",
"lt28": "pirms 7 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt29": "Olga Piliņa",
"lt30": "Čau, Kate! Iespaidīgi! Malacīte! Tūlīt arī savam vīram pasūtīšu).",
"lt31": "pirms 9 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt32": "Gints Pavārs",
"lt33": "Lietoju jau otru dienu. Godīgi – neesmu gaidījis TĀDU efektu. Trūks vārdu. Mana draudziņa foto ;)))))))<br><img src=\"review-1.jpg\">",
"lt34": "pirms 11 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt35": "Aija Paija",
"lt36": "Sveika, Kate! Pasūtīju uzreiz divus, tagad nevaru sagaidīt sūtījumu :)",
"lt37": "pirms 12 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt38": "Valerijs Lazdiņš",
"lt39": "Satriecoši, Kate! Arī tā gribu))",
"lt40": "pirms 15 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt41": "Princesīte",
"lt42": "Sveika, Kate! Es iesmērēju šo krēmu makstī 5 dienu laikā. Lieliski! Superīgi! Uzsākusi piedzīvot orgasmus, iepriekš tikai simulēju) Ieteicu visiem.",
"lt43": "pirms 16 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt44": "Madara Jakovele",
"lt45": "Čiu! Pasūtīju gan vīram, gan sev! Vienkārši trūkst vārdu! Paldies tev! Orgasmi satriecoši!!!!!",
"lt46": "pirms 21 minūtes |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt47": "Princis",
"lt48": "Lietoju vienu nedēļu, pagaidām izaudzis par vienu centimetru, bet jau apnicis tīrīt paklāju no spermas)))",
"lt49": "pirms 22 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt50": "Vitālijs Bunte",
"lt51": "Iepērku, patīk! Iepriekš trūka spēki gultā, orgasmi bija ne īpaši izteikti. Tagad viss izmainījās labākā pusē. Katiņ, paldies tev)",
"lt52": "pirms 25 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt53": "Raitis Ošis",
"lt54": "Es arī zinu par šo XX. Tikai esmu to pircis Ukrainā, vēl pasen. Strādā. Ieteicu.",
"lt55": "pirms 34 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt56": "Sandis Seiko",
"lt57": "Mana sieva no laimes ir uz septītās debesis. Prasa, kas ar mani noticis? Tagad seksa ilgums ir 5 stundas, loceklis izaudzis par 3 cm)))",
"lt58": "pirms 39 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt59": "Māris Tārs",
"lt60": "Arī esmu lietojis šo krēmu. Strādā. Arī pasūtīju caur šo vietni, bez priekšapmaksas, sūtījumu saņemu pēc 6 dienām. Arī nopublicēšu savas draudzenes foto, viņa piedzīvoja vaginālu orgasmu))<br><img src=\"review-2.jpg\">",
"lt61": "pirms 41 minūtes |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt62": "Valdis Maksimovs",
"lt63": "Apsveiciet manu, esmu arī kļuvis par šī štellas laimīgu īpašnieku!",
"lt64": "pirms 44 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt65": "Pauls Liniņš",
"lt66": "Puiši, ceru, ka arī jums palaimēsies tapāt, ka man. Orgasmi kļuvuši izteiktāki laikam nevis 10, bet 100 reizēs! Loceklis izaudzis par 5 cm, esmu šokā. Kate, paldies tev par publikāciju!",
"lt67": "pirms 49 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt68": "Lola Neimane",
"lt69": "Arī zinu par šo krēmu. Mans vīrs tagad tikai ar viņu, beidz, kā zirgs… jau apnicis.",
"lt70": "pirms 50 minūtēm |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt71": "Vilis Mikāns",
"lt72": "Čiu! Krēms superīgs, tik vienkārši – iesmērējis, nomazgājis – un mīļojies cik vien vēlies. Lai sasniegtu locekļa pieaugumu, labāk nenomazgāt krēmu kādas 10 minūtes!",
"lt73": "pirms 51 minūtes |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt74": "Gatis Lubāns",
"lt75": "Sveika. Mana sieva arī nopirkusi šo krēmu, protams, kritizēju viņu, domājot, kas tas ir kārtējais reklāmas triks, net pēc 2 nedēļām biju spiests paņemt savus vārdus atpakaļ un pirkt vēl vienu))",
"lt76": "pirms stundas |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt77": "Reāls Boss",
"lt78": "Tas nav nekāds jaunums. Visi jau zina par šo krēmu. Tie kurš nezina, laikam, negrib pastiprināt savas sajūtas. XX reāli darbojas. Ieteicu.",
"lt79": "pirms stundas |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt80": "Sofija Meirāne",
"lt81": "Tieši tas, kas vajadzīgs! Starp citu, jau sen esmu lasījusi šo rakstu, bet nepievērsu uzmanību… tagad vīrs daru TĀĀĀĀDAS lietas)))",
"lt82": "pirms divām stundām|<span class=\"vk-comment-answer\">Komentēt</span>",
"lt83": "Aivars Subāts",
"lt84": "Rietumos visus šos krēmus lieto jau sen. Visas porni studijas arī. Kā vienmēr, līdz mums viss aiziet ar kavējumu...",
"lt85": "pirms divām stundām |<span class=\"vk-comment-answer\">Komentēt</span>",
"lt86": "Blogeri onlainā",
"lt87": "Un vēl 279 bez avatāriem ...",
"lt88": "Kates Grēviņas blogs.<span class=\"nowyear\">2017</span>©",
};
function Translater () {
               for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                 for (key in elements) {
                  elements[key].innerHTML = new_lang[class_name];
                 }
              }
            }
          };