var new_lang = {
	lt1: 'Mājas',
	lt2: 'Emuārs',
	lt3: 'Atjaunošanos',
	lt4: 'Komentāri: 15',
	lt5: 'Teksts: <a href="" rel="author"> Parkhomenko </a> ',
	lt6: 'Bez jebkāda botox - -15 gadi garantēta',
	lt7: '<strong> Ksenija Bondareva pārskats Uzvarētājs: </ strong>« Stāsti no dzīves par to, kā kļūt par skaistu.',
	lt8: 'Sveiki, mani dārgie lasītāji. Es gribētu pastāstīt savu stāstu, kā jūs varat meklēt skaistumu trīs jūru, un galu galā atrast viņu mājās. ',
	lt9: 'Iepazīsimies. Es Ksenija Bondareva, es esmu 47 gadus vecs, dzīvo Džakartā . ',
	lt10: 'Un tagad, patiesībā, vēsture',
	lt11: 'Vienu dienu, kādā jaukā rītā, es paskatījos uz sevi spogulī un raudāt. Dziļi grumbas uz pieres, tikai milzīgs nasolabial krokās, maisiņi zem acīm, daži izciļņiem uz ādas - viss auksts pelēkā rudens nāk, un vēl joprojām tā vēlas siltumu un gaismu. Kaut kā uzreiz es atcerējos stāstu par vienu sievieti, par to, kā viņa ir lieliska persona atdzimšanu spa Tunisijā. Kas ir tur bijušajā kolonijā Franciju, Francijas darba daudziem pieredzējušiem kosmetologu pie Francijas preparātiem. Izrādās, ne sliktāk kā Francijā, bet ik pēc divām vai trīs lētāk. Tāpēc, spa ceļojumi uz Tunisiju ir ļoti populārs visā pasaulē un Francijā, ieskaitot :-) ',
	lt12: ' «Jā, man nav pelnījuši būt skaista sevi?! - Es nolēmu, lai uzzinātu par un kļūt par biļeti uz Tunisa. Un ķērējs, kā ir labi zināms, un dzīvnieku iet. Pirmajā ceļojumu aģentūrā man piedāvāja 50% atlaidi pēdējā brīža! Īsāk sakot, divas dienas vēlāk es biju kūrorta Hammamet, lielākā Bio Azur Spa. Un vietējie burvji tūlīt paņēma manu seju un ķermeni. Par visu veidu aļģu un dubļu ietīšanas un karstā toveri nevaru pateikt.Ne pa tēmu. Es jums pastāstīt, kā viņi manu seju. ',
	lt13: 'Kurss bija paredzēta 12 dienas. Sākumā ir foto seja, tad pacientam var skaidri redzēt atšķirību. Tad es gaidīju kosmētikas greznu krēslu. Sēdēt un iegremdē svētlaime. Klusa mūzika spēlē, gaiss ir tīkams patīkams aromāts, un sieviete ar mīkstām masāžas kustībām aplicē uz sejas patīkamu smakojošu krēmu. Visa procedūra aizņem aptuveni 15-20 minūtes. Un tā, uz 12 dienām. Beigās fotografēt vēlreiz. Šeit jūs varat redzēt rezultātu par sevi. ',
	lt14: 'Maisiņi zem acīm, grumbas, nasolabial krokās vienkārši pazuda! Un nevis risinājuma 15 gadus ar viņiem! Es biju satriekts un saviļņots! Mans kosmetologs, pieradusi gadu gaitā uz pacilātība par saviem pacientiem, gudrs es smaidīju. Un es atcerējos nosaukumu krējuma-maska sejas, kas bija tik efektīva. <a href=""> COLLAMASK </a> - tas, ko tas sauc !',
	lt15: 'Protams, kad es saņēmu uz manu Samara pie maniem draugiem draudzenes sāka oohs un aahs. Es burtiski bombardē ar jautājumiem! Es esmu visu godīgi teikt visu, un viņa devās ... skumji. Ņemot vērā pacilātība par savu jauno seju, es pēkšņi ieraudzīja manu māti skumji.Un uzreiz es sapratu. Sieviete joprojām ir sieviete jebkurā vecumā. Un jebkurā vecumā viņa vēlas būt skaista. Bet sūtīt 71 gadus veca sieviete Tunisijā - tas bija nereāls. Es jautāju ap maskas veikalos - neviens pat dzirdējuši par to ... ',
	lt16: 'Izrādās, ka šis krēms-maska var pasūtīt, un mēs',
	lt17: 'Seši mēneši. Un pēkšņi, brīnums! I ilga pāri internetā iepazinušies nosaukumu - COLLAMASK! Es izlasīju, man patīk viss konverģē. Tikai iepakojums nav, ka tas, ko es esmu redzējis Tunisijā. Un cena ir daudz pieejamākas. Vai Tunisijā, ir tik daudz ņem par pakalpojumu? Īsāk sakot, lai arī svārstības bija, bet es joprojām pēc pasūtījuma! Nav visiem cilvēkiem, bet es zinu, kā maska izskatās un darbojas! Ja tā ir taisnība <a href=""> COLLAMASK </a>, tad es esmu milzīgs uzvarēt! ',
	lt18: 'nosūtītāja nāca pēc 5 dienām. Un es uzreiz sāku par viņas māti. Turklāt, es skaidri zinu, ko darīt. Protams, nav kosmētikas krēsli, mūzika un aromterapija. Bet COLLAMASK slodze un tā. 12 dienu mana māte ir 15 gadus jaunāka. Diena - par gadu !! ',
	lt19: 'Lūk, es prezentēt sava darba rezultātus:',
	lt20: 'Es uzreiz lika vēl 6 caurules - Me, mana māte un viņas draugs. Lai tā būtu! jo nekas labāks par sejas man vēl nebija izpildīts. Un ātrs rezultāts. Skaistums! ',
	lt21: 'Tas ir viss stāsts. Es ceru, ka mana pieredze būs noderīga daudziem. Galu galā, sieviete jebkurā vecumā vajadzētu būt skaista! ',
	lt22: 'COLLAMASK',
	lt23: 'Iet uz mājas COLLAMASK',
	lt24: 'Ar cieņu, Ksenia Bondareva',
	lt25: 'Atstāj savu balsi',
	lt26: 'Interesanti no partneri',
	lt27: 'Netradicionālās metodes zaudēt svaru',
	lt28: 'Volochkova paziņoja izbraukšanas uz klosteri',
	lt29: 'Reklāma un vitamīni - kur patiesība',
	lt30: 'Kakao uzlabo atmiņu',
	lt31: 'D vitamīns glābt mūs no senils demenci',
	lt32: 'Kopā komentāri: 15',
	lt33: 'Komentāru',
	lt34: 'Lai atstātu komentāru, jums ir izveidot <a href=""> </a>',
	lt35: 'Alika Apet`yan',
	lt36: '71 gadi? Es nespēju noticēt,)) Bet masochku`ll kārtībā. Vai jūs redzat to struktūra uz vietas? Vienkārši super))) ',
	lt37: 'Trina_Paris ',
	lt38: 'COLLAMASK blastu! Tā kļuva populāra pēdējā pusgada gadā. ',
	lt39: 'Elena Medvetskaya',
	lt40: 'Vai kaut kas saprātīgs izgudrots? Apnicis naudas bezjēdzīgi tērēt naudu. Ja jūs tiešām strādā, pārliecinieties pasūtīt to. ',
	lt41: 'Galina Zorina',
	lt42: 'Satveriet! Tas ir efektīvs veids, kā atjaunot!Labi grumbas pazūd pilnīgi bez pēdām. ',
	lt43: 'Ksenija Bondareva',
	lt44: 'Paldies par foto! Lielisks rezultāts! Meitenes rakstīt vairāk par saviem rezultātiem! Tas ir ļoti interesanti. ',
	lt45: 'Luba Kimpel',
	lt46: 'Un es neesmu redzējis šo veikalu ... .Redzams, piemēram, tikai <a href=""> <strong> šajā vietā </ strong> </a> lai cik vien iespējams.',
	lt47: 'Veronica Strel`cova ',
	lt48: 'Attiecībā uz 3. gadu man ir pilnīgi vaļā no grumbām, pat dziļākais. Šī ir pasaka! Kā radās laiku es atbraucu uz jūsu emuāru.Paldies! ',
	lt49: 'Ksenia Bondareva',
	lt50: 'Vienkārši brīnišķīgi! ) Es pats par šo masku, patiesībā, nejauši. Šādas lietas noteikti jāpasaka atpūtu! ',
	lt51: 'Polina Cezareva ',
	lt52: 'Šiks sieviete! Es esmu mans 30 izskatīties sliktāk: ((Viss, ko es būs veikt .',
	lt53: 'Galechka Butramenko',
	lt54: 'Ir nepieciešams pasūtīt līdz tas tika demontēts. Un tad, kas zina) ',
	lt55: 'Marina Veremeichik',
	lt56: 'COLLAMASK, meitenes ne tikai atņemt grumbas, bet arī tūsku. Man ir šādi briesmīgi loki zem acīm bija - un tagad tur. Es nevaru saņemt pietiekami daudz. ',
	lt57: 'Ksenija Bondareva',
	lt58: 'Ļoti ievērojams efekts! Lielisks rezultāts! Paldies par atsauksmes))) ',
	lt59: 'Olga Tarasova',
	lt60: 'Esmu dzirdējis jau par COLLAMASK, bet nezināja, kur pasūtīt. Paldies par palīdzību! ',
	lt61: 'Liza Gladkaya',
	lt62: 'Jau kartīti! Rah-Rah ... ',
	lt63: 'Lolita Malysheva',
	lt64: 'Un mans vīrs deva dzimšanas diena)) teica, ka tagad jums būs mans skaistākā)) Un ko jūs domājat? Un tā izrādījās :) ',
	lt65: 'Evgeniya Razumovskaya',
	lt66: 'Es nopirku, kā masku! Es to izmantot 2 mēnešus. Patiešām jaunības sejas maska, kas nav citādi !!! Rezultāts pievienot ',
	lt67: 'Mēģiniet COLLAMASK <br> tagad',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};