var new_lang = {
lt1:  ' Die Behandlung der Gelenke im Monatsdurchschnitt –ist es real?', 
lt2:  ' Der Schmerzen in den Gelenken lässt nicht ruhig leben?  ', 
lt3:  ' Sie bemerken ständig, dass Ihre Gelenke «knacken»? ', 
lt4:  ' Auszehrender Schmerzen quält Ihnen den ganzen Tag,<br> lässt nicht sin auf den Sachen zu konzentrieren?   ', 
lt5:  ' Sie lassen unberücksichtigt diese beängstigenden<br>Symptome? ', 
lt6:  ' Schade! Denn laut unserer Untersuchungen,<br>In 78% der Fälle beendet sich die verschleppte Arthrose der Gelenke<br> mit schweren Operationen, die<br>den Menschen für viele Monaten bewegungsunfähig machen...   ', 
lt7:  ' GIBT ES DIE HOFFNUNG AUF DIE RETTUNG?  ', 
lt8:  ' Die deutschen Gelehrten konnten die geheime Formel des Elixiers für Behandlung der Gelenke, die seit langer Zeit und erfolgreich die Hollywood-Stars verwenden. In Deutschland ist es die Creme XX!  ', 
lt9:  ' Wollen Sie wirklich  ein tatsächlich<br> glücklicher und gesunder Mensch zu werden? ', 
lt10:  ' Bestellen Sie die Körpercreme «XX» und befreien Sie sich<br> vom Schmerzen in den Gelenken <b>FÜR IMMER!  ', 
lt11:  ' BESTELLEN  ', 
lt12:  ' Tägliche Verwendung  ', 
lt13:  ' Gesunde Gelenke  ', 
lt14:  ' Warum schmerzen die Gelenke? ', 
lt15:  ' In Ihrem Fall die Grund dazu kann sein: ', 
lt16:  ' bewegungsarme Lebensweise ', 
lt17:  ' falsche Ernährung  ', 
lt18:  ' Übergewicht ', 
lt19:  ' Fehlhaltung ', 
lt20:  ' ökologischen Einwirkung', 
lt21:  ' Erblichkeit  ', 
lt22:  ' aktive Sportbeschäftigung', 
lt23:  ' Schwangerschaft ', 
lt24:  ' Falls einer der genannten Punkte Sie betrifft, sollen Sie ernst über Ihre Gesundheit und Zukunft denken! ', 
lt25:  ' Verzehrendes Brennen in den Gelenken erlöscht alle Lebensfarben: dabei interessiert man nicht für Arbeit, eigenes Äußeres, Familie, Erholung…  ', 
lt26:  ' Womit  hilft Ihnen XX und wie bewirkt diese die verletzten Gelenke?  ', 
lt27:  ' Präventiert die Salzablagerungen;< ', 
lt28:  ' Regeneriert die verletzten Gewebe  ', 
lt29:  ' Befreit vom Schmerzen und Ödeme ', 
lt30:  ' Übt eine Reihe der nützlichen<br>prophylaktischen Wirkungen aus ', 
lt31:  ' Pflegt Ihre Gelenke sogar<br>nach dem Abwaschen der Creme ', 
lt32:  ' Dank  einzigartiger Formel dringt die Creme tief in die Struktur der Gewebe und heilt.  ', 
lt33:  ' Minimaler Kurs der Einreibungen lässt leicht und schnell das trockene aufgesprungene Gewebe der Gelenke heilen, und die leichte, fettarme Textur und unaufdringliches Aroma dieser Creme mache die Pflege noch angenehmer und wirksamer!  ', 
lt34:  ' Warum ist die Creme XX<br>so wirksam? ', 
lt35:  ' Trägt aktiver Heilung der Gewebe bei, aktivisiert die Stoffwechselvorgänge ', 
lt36:  ' Glukosamin ', 
lt37:  ' Regeneriert und befestigt die Gelenke bei der Arthritis und Arthrosen  ', 
lt38:  ' Chondroitin ', 
lt39:  ' Stimuliert die Ausarbeitung der Hyaluronsäure, die für Gesundheit der Knorpel verantwortlich ist ', 
lt40:  ' Kampfer ', 
lt41:  ' Beseitigt die Entzündungen und Schmerzen in den Akutzuständen der Erkrankungen der Gelenke, der Knorpel und der Bands  ', 
lt42:  ' Was gibt Ihnen die Verwendung der Creme "XX"?  ', 
lt43:  ' Die Wirkung dieses Elixiers ist auf den biochemischen Vorgängen des Körpers begründet, deswegen passt dieses den Männern und den Frauen von Jung und Alt und mit beliebiger Bewegungsaktivität. Stellen Sie sich vor: jetzt wird es leicht und fröhlich, Sie möchten arbeiten und ein aktives Leben führen! Schlaflichkeit, Schmerzmedikamente und tägliche Qualen bleiben in der Vergangenheit  und kehren nie wieder zurück.  ', 
lt44:  ' Sie werden einen neuen Menschen anziehen! ', 
lt45:  ' Wollen Sie wirklich  Ihr Leben besser gestalten?<br>Dann handeln Sie! ', 
lt46:  ' Und hilft mir "XX" wirklich? ', 
lt47:  ' Ja! Geheimnisformel dieser Creme half vielen Hollywood-Stars sich für immer von den Problemen mit den Gelenken zu befreien, und die Laboruntersuchungen der deutschen Gelehrten haben nur diese Tatsache bestätigt: XX ist weltweit ohnegleichen!  ', 
lt48:  ' In jedem Fall, wenn Ihnen das Ergebnis nicht gefällt, sind wir bereit das Geld zurückzukehren. ', 
lt49:  'Bewertungen  ', 
lt50:  ' Was sagen die Leute, die die Gelenke mir der Creme "XX" schon geheilt haben?  ', 
lt51:  ' Martina, 28 Jahre  ', 
lt52:  ' Moskau  ', 
lt53:  ' Wann meine Finger begannen zu schmerzen und zu knacken, empfiehl mein Arzt  mir die Creme «XX». Ich habe gekauft und bin sehr froh darüber, dass ich diese berufliche Empfehlung gefolgt habe! Erstens hat die Creme mich vom Schmerzen und Reißen in den Händen befreit, und dann auch der Knack verschwand. Ich kann normal arbeiten und mich mit meinen Haushaltsangelegenheiten beschäftigen ich erinnere mich an die Krankheit fast nicht. Ich bestelle jetzt auch für meine Mutti, der Effekt  gefällt ihr auch. ', 
lt54:  ' Dirk-Julius, 44 Jahre  ', 
lt55:  ' Bremen', 
lt56:  ' «XX» ist ausgezeichnetes Mittel! ich arbeite als Uhrmacher, deswegen sind meine Hände mein Hauptarbeitswerkzeug, mein Brot... und wie groß war meine Verzweiflung, wenn man bei mir Fingerarthritis diagnostiert hat. Im Internet fand ich viele Empfehlungen in Bezug auf «XX»... und wissen Sie, dieses Wunder-Mittel, das allen half, half mir auch! Jetzt beschäftige ich mich wieder mit meiner Lieblingsarbeit, und kein Hauch vom Schmerzen blieb übrig! ', 
lt57:  ' Nicole, 56 Jahre  ', 
lt58:  ' Koblenz', 
lt59:  ' Im Frühling vergangenen Jahres habe ich meine Schulter geschädigt... Zuerst ließ ich den Kopf hängen, ich dachte, jetzt würde ich immer die Spritzen brauchen, aber meine Nachbarin empfiehl mir XX zu bestellen. Ich habe bestellt, man rief mich sofort zurück, man hat die Creme sehr schnell geliefert, aber das wichtigste ist — ich habe meine Schulter gesalbt und erstmals nach langer Zeit konnte ich normal, ohne Schmerzen einschlafen. Ich verwende es schon eine Woche und bin ausser mich vor Freude — also, es ist so leicht sich vom Schmerzen zu befreien! ', 
lt60:  ' Vorangehende Bewertung ', 
lt61:  'Nächste Bewertung  ', 
lt62:  ' Vorsicht Fälschung! ', 
lt63:  ' Wie beliebige wirksame und populäre Mittel, versuchen die Betrüger  auch «XX» zu verfälschen. Tappen Sie nicht in eine Falle! Echte Creme XX gegen Erkrankungen der Gelenke können Sie  nur in unserem Shop kaufen. Wir sind offizieller Lieferant auf dem Territorium Deutschlands und garantieren die Qualität unserer Produktion. ', 
lt64:  ' Mit echter Creme "XX" sind gesunde Gelenke sehr einfach, babyleicht.  ', 
lt65:  ' BLEIBEN SIE GESUND! ', 
lt66:  ' Bei der Bestellung bei uns bekommen Sie: ', 
lt67:  ' Echte Creme<br>«XX»<br>für die Gelenke  ', 
lt68:  ' Günstiger<br>Preis ', 
lt69:  ' Schnelle<br>Lieferung  ', 
lt70:  ' BESTELLEN  ', 


};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};