var new_lang = {
lt1:  '- 100% sigur și eficient',
lt2:  'Pe noi <spanclass="blue">DEJA</span> ne-au apelat 4 672 persoane pentru a ne spune<spanclass="blue">MULȚUMESC!</span>',
lt3:  'Comandați o consultație gratuită',
lt4:  '<spanclass="big">Bioretin:</span> principalul aliat<spanclass="blue">în lupta contra vârstei</span>',
lt5:  '<span class="blue">Reduce</span> ridurile',
lt6:  '<span class="blue">Restabilește</span> elasticitatea',
lt7:  '',
lt8:  '<span class="blue">Reface</span>conturul',
lt9:  '<span class="violet">Înnoirea</span> celulelor "adormite"',
lt10: '<span class="violet">Restabilirea</span> celulelor deteriorate',
lt11: '<span class="violet">Regenerarea</span> celulelor sănătoase',
lt12: 'prețul<br><span class="bold">1 EURO*</span>',
lt13: 'Prețul la promoție:<br><span class="big">1 EURO*</span>',
lt14: 'Prețul vechi:',
lt15: 'până lasfârșitul promoției au rămas:',
lt16: 'zile',
lt17: 'ore',
lt18: 'minute',
lt19: 'secunde',
lt20: 'ATENȚIE! Cantitatea de unități la promoție este limitată.',
lt21: 'Au rămas: ',
lt22: ' buc.',
lt23: '* - la comanda întregului curs',
lt24: 'Câți ani are pielea Dvs?',
lt25: 'Se consideră că îmbătrânirea are un singur indiciu – ridurile. Dar Dvs știți că ridurile sunt doar o parte a problemei. <spanclass="red">FIECARE NOUĂ PROBLEMĂ NE ADAUGĂ ANI!</span>',
lt26: 'Pliurile nasolabiale',
lt27: '+6 ani',
lt28: 'Ovalul lăsat',
lt29: '+5 ani',
lt30: 'Riduri ”laba gâștei”',
lt31: '+4 ani',
lt32: 'Riduri între sprâncene',
lt33: '+7 ani',
lt34: 'Pungi sub ochi',
lt35: '<spanclass="violet">Pielea are propria vârstă.</span> Diferită de a noastră.Deoarece pielea este foarte vulnerabilă, este supusă distrugerii de către vreme, spre deosebire de alte organe. După 35 de ani pielea înbătrâneste brusc. Din cauza gravitației, eredității, ecologiei proaste, razelor ultraviolete, radiației, stresului și alimentației incorecte. <spanclass="red">Calculați, câți ani are pierea Dvs acum.</span><spanclass="underline"> Notați punctele, cu care sunteți de acord.</span>',
lt36: 'Introduceți vârsta Dvs reală:',
lt37: 'Am pliuri nasolabiale:',
lt38: 'Pielea și-a pierdut elasticitatea:',
lt39: 'Ridurile mimetice sunt pronunțate:',
lt40: 'Am câteva riduri adânci:',
lt41: 'Indicați vârsta Dvs',
lt42: 'Sunt recomandate: 17 unități de toxină botulinică, 2 cure de mezoterapie, 28 de fire bio<br><spanclass="white">SAU 1 curs de cremă Bioretin</span>',
lt43: 'Sunt recomandate: 37 unități de toxină botulinică, 3 cure de mezoterapie, 38 de fire bio, 1 curs de  filere <spanclass="white">SAU 2 cursuri de cremă Bioretin</span>',
lt44: 'Sunt recomandate: 47 unități de toxină botulinică, 4 cure de mezoterapie, 48 de fire bio, 1 curs de filere <spanclass="white">SAU 3 cursuri de cremă Bioretin</span>',
lt45: 'Sunt recomandate: 57 unități de toxină botulinică, 5 cure de mezoterapie, corecție chirurgicală a ovalului feței <spanclass="white">SAU 3 cursuri de cremă Bioretin</span>',
lt46: 'de ce să arătați mai în vârstă decât sunteți dacă ',
lt47: 'puteți arăta mai tânără?',
lt48: 'MULT MAI TÂNĂRĂ, FĂRĂ DURERE ȘI RISC!',
lt49: 'femeile regretă, că au acceptat injecțiile și intevențiile chirurgicale',
lt50: 'eficacitatea și siguranța dovedite',
lt51: 'ALE CELEI MAI NOI FORMULE Bioretin',
lt52: 'împotriva îmbătrânirii',
lt53: 'RECĂPĂTAȚI CEI MAI FRUMOSI ANI DIN VIAȚĂ ȘI TINEREȚEA',
lt54: 'Bioretin – INOVAȚII și REZULTAT',
lt55: 'Bioretin – este o cremă inovativă, care conține ulei  tămăduitor de argan și avocado, vitamine și acid hialuronic, hrănește și întinerește straturile adânci ale pielii, stimulează creșterea  țesutului epitelial',
lt56: 'Crema stimulează activ producerea de colagen și regenerarea ”matricei” intercelulare. Aceasta ajută la <spanclass="violet">reducerea remarcabilă a ridurilor mimetice de pe frunte, din regiunea gurii și ochilor (riduri ”laba gâștei”). </span><br><spanclass="orange">Bioretin – rste un ”coctail” impresionant pentru corecția pliurilor nosolabiale și ridurilor dintre sprâncene.</span>',
lt57: 'Conține componente care sunt create pentru a ”mări volumul” în locul unde acționează, ceea ce <spanclass="violet">unple ridurile și pliurile din interior,</span> "împingând" pielea înapoi. Deasemenea, ajută la ”relaxarea” micro-contracțiilor musculare, pentru a împiedica increțirea pielii între sprâncene.',
lt58: 'Bioretin – conține unul dintre cei mai puternici antioxidanți, care neutralizează radicalii liberi, ce sut principala pricină a înbătrânirii.',
lt59: 'Inhibă dezintegrarea colagenului , adică, luptă cu îmbătrânirea prin protejarea celulelor de distrugere. Stimulează circuitul limfei pentru eliminarea umflăturilor și micșorarea urmelor vineții de sub ochi. Consolidează structura pielii <spanclass="violet">reface relieful, ovalul feței,</span> datorită producerii naturale de golagen și elastină .',
lt60: 'Acid hialuronic',
lt61: 'Ulei de Argan',
lt62: 'Ulei de Avocado',
lt63: 'Glicerină',
lt64: '',
lt65: 'Efectul senzațional Bioretin.',
lt66: '89% au începutsă arate acea vârstă, pe care o simt!',
lt67: 'După 40 de ani regenerarea celulelor începe sa încetinească.',
lt68: 'Apar tot mai multe riduri, pielea își pierde elasticitatea, iar conturul feței devine mai puțin pronunțat. Îngrijirea revoluționară împotriva îmbătrânirii Bioretin a fost creat anume pentru îngrijirea pielii în ofilire.',
lt69: 'Acțiunea triplă a Bioretin este confirmată de testările clinice la scară largă:',
lt70: '1183 de femei',
lt71: 'Au remarcat<spanclass="violet">o reducere considerabilă</span> a ridurilor și liniilor date de privirea încruntată (de 77%), la colțul ochilor (de 56%) și pe frunte (de 76%)',
lt72: '927 de femei',
lt73: 'S-a umplut volumul în pliurile nosolabiale,',
lt74: 'volumul în regiunea  pomeților a fost restabilit (+41%).<br>Ovalul feței este vizibil mai pronunțat, pielea netedă și umplută cu volum.',
lt75: '1321 de femei',
lt76: 'Rezultate vizibile<br><spanclass="violet">Elasticiatea pielii a crescut (+65%),</span> pielea este mai densă (+54%) și hidratată pentru 48 de ore.',
lt77: '<spanclass="red">UN SONDAJ LA SCARĂ LARGĂ A ARĂTAT CĂ -</span> DE PERSOANELE ÎMBĂTRÂNITE NU SE ȚINE CONT',
lt78: 'LOR NU LI SE ACORDĂ ATENȚIE',
lt79: '74% de bărbați au recunoscut sincer, că femeile cu riduri și cu semne de îmbâtrânire a feței nu pot fi atractive sexual.',
lt80: 'AU O LIMITĂ DE CARIERĂ',
lt81: '67% dintre angajatori nu vor angaja și nu vor propune o avansare unei femei, ce arată mai în vârstă de 45 de ani',
lt82: 'SOȚII LE  ÎNȘEALĂ',
lt83: '96% dintre soți și-au părăsit soțiile pentru o amantă mai tânără și pentru că soțiile au încetat să se mai îngrijească.',
lt84: 'Cercetările au confirmat: 87% de bărbați afirmă că <spanclass="red">vârstafemeii nu contează,</span> e important ca femeia să arate <spanclass="red">îngrijită și atrăgătoare.</span> Aceasta o face în ochii bărbatului <spanclass="red"> atractivă sexual și îi arată că ea se respectă.</span>',
lt85: 'Luați în mâini propria vârstă',
lt86: 'DEVENIȚI <spanclass="red">CU 10 ANI MAI TÂNĂRĂ</span> DUPĂ 2,5 CURSURI',
lt87: 'Pliurile nosolabiale<spanclass="orange">AU DISPĂRUT</span> după 2 cursuri',
lt88: 'Ridurile ”laba gâștii”<spanclass="orange">AU DISPĂRUT</span> după 2 cursuri',
lt89: 'Ridul dintre sprâncene<spanclass="orange">A DISPĂRUT</span> după 2 cursuri',
lt90: 'Conturul lăsat<spanclass="orange">A DISPĂRUT</span> după 1 curs',
lt91: 'Pungile de sub ochi<spanclass="orange">AU DISPĂRUT</span> după 1 curs',
lt92: 'OPINIA INDEPENDENTĂ A COSMETOLOGILOR',
lt93: 'Tatiana Miculescu<br>Medic cosmetolog-dermatolog<br>Stagiul de practică 18 ani',
lt94: 'Dacă aș fi fost în locul cosmetologului Dvs, atunci, desigur, m-aș fi străduit să vă ofer maximum din ceea ce pot și din ce este accesibil prin tehnologiile de frumusețe: <spanclass="violet">botox, plasmolifting, filere ș.a.</span> Dar, ca persoană și ca femeie, înțeleg că cu ajutorul <spanclass="violet">Bioretin toate aceste proceduri pot fi amânate încă vreo 6 ani.</span>',
lt95: 'Și lasă-i pe toți să creadă că am făcut operație estetică...',
lt96: 'Doriana Livădaru<br>Asistent superior al chirurgului plastician<br>Stagiul de practică 7 ani',
lt97: 'Eu recomand să nu vă grăbiți cu injecțiile, operațiile și alte intervenții traumatizante. Amânați aceste îdei pentru înce 20 de ani. Doar<spanclass="violet">încercați Bioretin și peste 1 lună veți înțelege că în medicina estetică s-a produs o revoluție.</span> Cosmeteutica (medicina cosmetică) este viitorul în domeniul frumuseții și tinereții, de rezultatele căruia putem să ne folosim deja acum, și să ne delectăm cu rezultatele.',
lt98: 'Permiteți pielii Dvs să devină mai tânără!',
lt99: 'În toate saloanele bucureștene de prestigiu  <spanclass="blue">deja demult se foloseste Bioretin.</span> O Procedură din exfoliere, masaj facial și aplicare a cremei costă aproximativ 400 lei',
lt100:'Opinii sincere',
lt101:'Recomandat de femei reale.',
lt102:'În anul 2016 au fost vândute mai mult de 3 000 000 .',
lt103:'Dvs ați comandat deja Bioretin?',
lt104:'Ana, Sibiu',
lt105:'Victoria, Timișoara',
lt106:'Sorina,Iași',
lt107:'12 000 000 $ au fost investite pentru crearea Bioretin',
lt108:'ani pentru desfășurarea testărilor',
lt109:'ani pentru crearea formulei',
lt110:'specialiști activi',
lt111:'procente  eficacitate',
lt112:'procente femei fericite',
lt113:'certificat de calitate UE, RTS, ISO',
lt114:'procente componente naturale',
lt115:'ATENȚIE!',
lt116:'În legătură cu popularitatea în România, țările UE și CSI s-au înmulțit cazurile de produse contrafăcute la preț de nimic!<br>Fiți atenți! Pe ambalajul original obligatoriu este plasat un cod de bare cu numărul de autenticitate. Dacă lipsește codul de bare, expediați o plângere pe adresa noastră indicată ân josul paginii. Vă vom compensa pierderile și îi vom trage la răspundere pe excroci.',
lt117:'Cum lucrăm?',
lt118:'PASUL  1',
lt119:'Faceți comanda instant la <spanclass="red">preț promoțional</span>',
lt120:'PASUL 2',
lt121:'Așteptați apelul consultantului pentru a  concretiza detaliile',
lt122:'PASUL 3',
lt123:'Nu achitați nimic până la momentul livrării coletului',	
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};