var new_lang = {
lt1: 'Az alkoholfüggőség legyőzhető! Mentse meg rokonait és barátait!',
lt2: 'Hírek',
lt3: 'Csevegés',
lt4: 'Feliratkozás',
lt5: 'MED-info újság',
lt6: 'Tanácsadás',
lt7: 'Gyógyszer- és intézménytájékoztató',
lt8: 'Rovatok',
lt9: 'Tájékoztató',
lt10: 'Tanácsadás',
lt11: 'Kapcsolat',
lt12: 'Szórakozás',
lt13: 'MED-info <br> újság',
lt14: '<span> gyógyszer- </span><br> és intézménytájékoztató',
lt15: '<span> tanácsadás </span><br> tegye fel kérdését orvosunknak',
lt16: 'Mobilalkalmazások <br></span>',
lt17: 'Rovatok',
lt18: 'Témák',
lt19: 'Elemzés',
lt20: 'Interaktív',
lt21: 'Sztárinterjú',
lt22: 'Infografika',
lt23: 'Előzőleg olvasott cikkek',
lt24: 'Kerekasztal',
lt25: 'Forró téma',
lt26: 'Riport',
lt27: 'Cikkek',
lt28: 'Aktuális hírek',
lt29: 'tegnap, 13:26',
lt30: 'Kész a legjobb fogászatok top-100-as listája',
lt31: 'tegnap, 21:56',
lt32: 'Decemberben lesz megrendezve a Hungarian Pharm Connect Awards díjátadó',
lt33: 'tegnap, 14:24',
lt34: 'Felmérés: milyen káros hatásokkal találkozunk a munkahelyen &nbsp;',
lt35: 'Egy tudóscsoportnak sikerült kitenyésztenie a boldogsághormont termelő neuronokat',
lt36: 'Legérdekesebb cikkek',
lt37: 'Interjú szakemberekkel',
lt38: 'Schmidt Borbála: «Lézeres műtét a fogászatban – a jövő gyógymódja',
lt39: 'Cikkek',
lt40: 'Hogyan válasszunk jól fogkefét &nbsp;&nbsp;',
lt41: 'Alkoholfüggőség',
lt42: 'Interjú szakemberekkel',
lt43: 'Az alkoholfüggőséget le lehet győzni! Mentse meg rokonait és ismerőseit! <br> Dr. László Róbert, orvostudományok doktora, budapesti főorvos',
lt44: 'A szerkesztőségtől: A hivatalos statisztikai adatok szerint, az alkoholisták száma Magyarországon már a 800.000 fős lécet is túllépte, ami a népesség 12,4 %-át teszi ki. Évente 30 ezren halnak meg alkohollal kapcsolatos betegség miatt, emellett az úgynevezett nagyivók száma körülbelül 2,5 millióra tehető, így Magyarországon szinte minden családot érint az alkoholizmus problémája. Ezek sokkoló számok! Ennyi ember nem hal meg autóbalesetben és más szerencsétlenségek következtében együttvéve. A mértéktelen alkoholfogyasztással közvetlenül vagy közvetett módon összeköthető: az öngyilkosságok 62.1%-a, a gyilkosságok 72.2%-a, a hasnyálmirigy-gyulladás miatti halálok 60%-a, a májzsugorodásos esetek 67.7%-a és a szív- és érrendszeri betegségek 23.3%-a. Évente 15 ezer rossz minőségű alkohol miatti alkoholmérgezéses eset van regisztrálva, melyek egy része halálos kimenetellel végződik. Arról, hogy hogyan lehet kigyógyulni ebből a betegségből és újra egészséges emberré válni, Dr. Lendvai Ferencet, az orvostudományok doktorát kérdeztük',
lt45: 'Szörnyű az, amikor az alkohol iránti vonzalom tönkreteszi az ember életét, miatta esnek szét családok, gyermekek vesztik el apjukat, feleségek férjeiket. Sajnos a mi időnkben, az alkoholfüggőség nagyon elterjedt a fiatal generációk körében is. Nagyon gyakori eset, amikor fiatalok teszik tönkre az életüket ivással, szétrombolva a jövőjüket és helyrehozhatatlan kárt okozva az egészségüknek. Kétségkívül igaz, hogy legtöbbször a nők feladatává válik az iszákos férfi – fiú, férj, apa megmentése. Bebizonyosodott, hogy lehetséges az iszákos családtag megmentése, ráadásul úgy, hogy a beteg nem is szerez tudomást róla.  Ma egy új természetes szerről, a <a target="_top" href="">AlcoBarrier-ről </a>, fogunk beszélni, ami rendkívül hatásosnak bizonyult.',
lt46: 'Bizonyára tudják, hogy egészen a közelmúltig az egyedüli hatásos módszer az alkohol elleni harcban, a páciens kódolása volt. Ennek a módszernek egy nagy hátulütője van – a betegnek bele kell egyeznie az orvosi kezelésbe és tudatosan mennie a kódolásra és az alkoholról való teljes lemondásra. Örökre. Mégis, a legtöbb esetben az iszákos emberek nem tarták magukat alkoholfüggőnek és biztosak abban, hogy bármikor képesek letenni a poharat. Így csak a közeli rokonaik, barátaik tudják, hogy külső segítség nélkül képtelenek lennének leszokni az alkoholról. Mit lehet itt csinálni? Rávenni, vitatkozni, veszekedni és kérni az embert, hogy szokjon le, teljesen felesleges, hisz már rég az alkohol irányítása alatt van. Így egyetlen lehetőség marad: titokban meggyógyítani a beteget. Ezt teszi lehetővé az orvosok és tudósok legújabb fejlesztése – az AlcoBarrier szer, mely 2 hét alatt (14 nap) képes kialakítani tartós alkohol iránti undort, még a krónikus alkoholistáknál is. Így, az ember minden alkoholos ital iránt utálatot fog érezni, és már az alkoholszag is undort fog kelteni.',
lt47: 'Hogyan működik az AlcoBarrier?',
lt48: 'Az AlcoBarrier – egy teljesen természetes komponensekből álló készítmény, ami azt jelenti, hogy nincs, és nem is lehet ellenjavallata a készítménynek, teljesen ártalmatlan és bárki használhatja. Emellett, az <a target="_top" href=""><b>"AlcoBarrier"</b></a> készítménynek komplex hatása van, fő funkcióján – az alkohol iránti vonzalom megszüntetése és a undorodás kialakításán kívül, a szer regenerálódási folyamatokat indít meg az összes alkohol által károsodott szervben. Regenerálódási folyamatok mennek végbe sejtszinten a májban, a szívben, a vesékben és az idegrendszer munkája is normalizálódik. Az AlcoBarrier pszichés szinten szünteti meg az alkohol iránti vonzalmat, az alkoholivás szokása teljesen eltűnik, helyére pedig a saját egészség fontosságának belátása kerül. A beteg élénknek és erejének teljében fogja magát érezni az újabb adag ital nélkül is, nem érzékeli a szokásos elvonási tüneteket."',
lt49: 'És hogyan is működik ez? – fogja ön kérdezni. Elmagyarázom. Az AlcoBarrier hatóanyagai és antioxidánsai adott sejtreceptorokra hatnak, melyek a sejt regenerálódásáért és munkaképességéért felelősek. Az információ átkódolása megy rajtuk végbe, így a beteg sejtek lecserélődnek egészségesekre. Végeredményben, a szervezetben megkezdődnek a gyógyulási folyamatok, pontosabban – ahogy mi szoktuk mondani -, a szervezet visszaáll a korábbi „egészséges állapotba”.',
lt50: 'Jelenleg egyetlen hivatalos oldal létezik, amelyen az AlcoBarrier terméket lehet megrendelni, nem pedig olcsó utánzatát. Az AlcoBarrier-et nem árusítják gyógyszertárban, ha mégis látta a városának a gyógyszertárában, az csak hamisítvány lehetett! Most nagyon sokan beszélnek erről a termékről rajtunk kívül is. Nem is hiába azt kell, hogy mondjam! Az AlcoBarrier egy összetett és egyedülálló keverék ritka és erőteljes természetes gyógyhatású anyagokból. Ez a szer nem csak a páciensek előtt, de a tudomány előtt is bizonyította hatásosságát, amely így elismerte az AlcoBarrier-et mint hatásos szert az alkoholfüggőség elleni harcban. A lenyűgöző hatás már 10-15 nap használat után megfigyelhető, ahogy a kutatások is bizonyították – az AlcoBarrier tényleg működik!',
lt51: 'Kutatás',
lt52: 'Laboratóriumi tesztek eredménye <a target="_top" href="">"AlcoBarrierа"</a> в НИИ Наркологии:',
lt53: '85 különböző korú önkéntes választottunk ki, akik könnyű, közepes és súlyos stádiumú alkoholfüggőségtől szenvedtek. A 30 napos kísérlet eredményeként a <b> következő eredményeket kaptuk:</b> ',
lt54: '1. A kísérleti csoport 18-68 éves kor közötti tagjainak javult a közérzete.',
lt55: '2. A betegek 96%-nál teljes mértékben megszűnt az alkohol iránti vonzalom.',
lt56: '3. Már a szer használatának 10. napján a páciensek nagy része jelentette, hogy undort érzett bármilyen alkoholszagtól és íztől.',
lt57: '4. A 30 nap letelte után a páciensek 97%-a végleg nemet mondott az alkoholnak, az orvosi vizsgálatok a szív-, máj- és veseműködés javulását mutatták.',
lt58: '<strong> Figyelem! </strong> Egyre gyakrabban fordul elő az AlcoBarrier szer hamisítványának eladása! Ezért, speciálisan az olvasóink számára elhelyezzük itt az AlcoBarrier termék megrendeléséhez való gombot, az egyetlen hivatalos gyártótól! Erről az oldalról rendelve ön garantáltan minőségi terméket fog kapni a legjobb áron!<br><br> A <strong>honlapunkon vásárlók számára további </strong> kedvezmény <strong> van biztosítva </strong>. Ahhoz, hogy megkaphassa a kedvezményt nyomja meg lejjebb a „Megrendelem” gombot. Ez át fogja irányítani a hivatalos oldalra, ahol leadhatja a rendelését. A kedvezményes csomagok korlátozott számban kaphatók!',
lt59: 'Hozzászólások',
lt60: 'Szilágyi Enikő (Veszprém)',
lt61: 'Csak nem tudom elhinni ezt a mesét! Nem hiszem, hogy segítene… Már annyi mindent kipróbáltunk, hogy egyszerűen a reményemet is elvesztettem…',
lt62: 'Bettina (Budapest, 23.07.2016)',
lt63: 'Enikő, nagy kár, hogy nem hisz, legalább próbálja ki, a helyzeten rontani úgysem tud! Mi is használtuk ezt a szert, nagyon jól segített. Férjem kigyógyult a dipszomániából, most már csak nagy ritkán iszik, ünnepek alkalmával. Kézben tudja magát tartani, és én többé nem féltem őt. Mindenkinek sok sikert kívánok! A termék valóban működik!',
lt64: 'Erdőssy Katalin, 46 éves (Szeged, 23.07.2016)',
lt65: 'Mit csak ki nem próbáltam, hogy leszoktassam a fiamat a sörről, de rádöbbentem, hogy ez már söralkoholizmus. Eleinte minden nap munka után vett egy üveg sört, később egyet már útközben is megivott, majd egy harmadikat is vett estére… Amikor az italnormája eljutott a napi 1,5 literig, úgy döntöttem, hogy tennem kell valamit! Nem elsőre találtam meg az AlcoBarrier-et, előtte sok más módszert is kipróbáltam – mind hatástalanul. Az AlcoBarrier-et teához keverve adtam neki, ő észre sem vette. Már a harmadik napra sör nélkül jött haza! Nem hittem a szememnek, de semmit sem mondtam vagy kérdeztem. Csak figyeltem az események további fejlődését, ő pedig teljesen elfelejtkezett a sörről! Nagyon remélem, hogy örökre! Hálás köszönet!',
lt66: 'Dr. László Róbert (Budapest, 24.07.2016)',
lt67: '> Nem tudtam szó nélkül hagyni ezt a hozzászólást… Katalin, igazán nincs mit! El sem tudja képzelni, mennyire örülök önnek és Bettinának, biztos vagyok benne, hogy jobb irányba változtatták rokonaik életét! <br><br> Üdvözlettel, Róbert',
lt68: 'Nemes Viki (Pécs, 24.07.2016)',
lt69: 'Enikő, hogyha kétségbe esik és elveszti a reményét persze hogy semmi sem fog segíteni! De ez a készítmény tényleg működik ráadásul elfogadható áron ajánlják most. Ajánlom, hogy vegye meg és saját maga bizonyosodjon meg a készítmény hatásosságáról!',
lt70: 'Piroska (Kiskunfélegyháza, 24.07.2016)',
lt71: 'Nekem a rokonaim (férj és feleség) ittak végig egy kúrát. Úgy alakult az életük, hogy párban kezdtek el keményen inni… Már azt hittem, hogy el fogom őket veszíteni, mert már teljesen elvesztették az érdeklődésüket az élet iránt, minden gondolatuk csak az üvegek körül forogtak. Szerencséjük, hogy tudták egymást támogatni és mindketten elhatározták, hogy abbahagyják az ivást. Kérdeztem is őket, ők mondták, tényleg elment minden kedvük az ivástól, attól pedig, hogy elképzelik ahogy megisznak egy kupica pálinkát – hányingerük lesz.',
lt72: 'K. Dóra (Visegrád, 25.07.2016))',
lt73: 'Az AlcoBarrier-el sikerült megmentenem a férjemet, neki mind az apja, mind a két nagyapja delíriumos állapotig itták le magukat és haltak meg, és ő maga is úgy gondolta, őt is ilyen jövő várja, de nem! Titokban minden nap adagoltam neki az AlcoBarrier-et, néha igazán nehezemre esett, de sikerült megoldanom. Ő semmit sem sejtett, mostanáig azt hiszi, hogy magától sikerült kézbe vennie magát. Először el akartam neki mondani az igazat, de inkább meghagyom őt a képzelményeiben. Ha úgy gondolja, hogy magától sikerült – had örüljön és legyen büszke magára. Nekem a legfontosabb, hogy józan és egészséges legyen!',
lt74: 'Viktor (Sárospatak, 25.07.2016)',
lt75: 'Dóra, nagyon helyes, ne is mondjon neki semmit, jobb a férfinak, ha azt hiheti saját maga győzte le szenvedélyét. Én a szüleimnek vettem AlcoBarrier-et, anyám észrevétlenül adagolta apámnak, aki sikeresen le is tette a poharat. Nagy kár, hogy korábban nem létezett ez a szer, annyi évet vesztegetett el az apám a pálinkára.. <br><br> nagyon remélem, hogy a pálinka iránti vonzalom nem fog visszatérni apámhoz, de ha mégis, akkor még egy kúra fog rá várni, anyámnál maradt még tartalék az AlcoBarrier-ből.',
lt76: 'Diószegi Anna (Debrecen, 26.07.2016)',
lt77: 'Nagyon remélem, hogy az AlcoBarrier megmenti anyumat apám iszákos napjaitól-heteitől. Mi mindent csináltunk már.. egyszer egy jóst is felkerestünk, de ő neki sem sikerült apámat elhúznia pohártól. Az AlcoBarrier kúra óta, egy hónapja nem ivott alkoholt, remélem a továbbiakban is így marad…',
lt78: 'Liza (Vác, 27.07.2016)',
lt79: 'Na akkor én is megosztom veletek az örömömet. Sikerült a férjemet kihúznom a krónikus ivászatból, eddig néhányszor próbáltam elhagyni, de mindig visszamentem hozzá, hisz mégiscsak szeretem. Ezután találtam rá az AlcoBarrier-re, egyből több adagot vettem, hogy mindenesetre tartalékon is legyen és elkezdtem itatni vele a férjecskémet. ÉS SEGÍTETT!! 3 héten át minden nap itattam a szerrel és már EGY ÉVE nem iszik!!!!!! <br> Óriási köszönetet szeretnék mondani a szer létrehozóinak, és itt van egy kép, hogy is néz ki az AlcoBarrier csomagolása.',
lt80: 'Zoltán, 37 éves (Киров, 27.07.2016)',
lt81: 'Emberek, kérlek mondjátok meg h hol vettétek? Nem láttam még gyógyszertárban.. Jó lenne nem hamisítványt venni, mer ahogy értettem az semmi hasznot nem fog hozni.',
lt82: 'Dr. László Róbert (Budapest, 27.07.2016)',
lt83: 'Még egyszer megismétlem, az „AlcoBarrier-et” CSAK ÉS KIZÁRÓLAG <a target="_top" href=""> a hivatalos oldalon</a> lehet megvenni, ahhoz, hogy biztos mindent helyesen csináljon, nyomja meg egyszerűen kicsit lejjebb a “Megrendelem” gombot! Speciálisan, az olvasóinknak különleges akciót tudunk ajánlani, a gyártóval való megegyezés eredményeképpen, de a kedvezmény rövid ideig fog tartani, úgyhogy siessen a rendeléssel! <br> És vigyázzon kérem a hamisítványokkal.<br><br>Üdvözlettel, Róbert',
lt84: 'Hozzászólok:',
lt85: 'Neve:',
lt86: 'Városa:',
lt87: 'Az üzenete:',
lt88: 'Hírek',
lt89: 'Üzlet',
lt90: 'Állam és orvostudomány',
lt91: 'Sztárok',
lt92: 'Tudomány',
lt93: 'Közösség',
lt94: 'Események',
lt95: 'Statisztika',
lt96: 'Фармация',
lt97: 'MED-info hírek',
lt98: 'Eseménynaptár',
lt99: 'Rovatok',
lt100: 'Riport',
lt101: 'Elemzés',
lt102: 'Kerekasztal',
lt103: 'Videó',
lt104: 'Infografika',
lt105: 'Interaktív',
lt106: 'Előzőleg olvasott cikkek',
lt107: 'Sztárinterjú',
lt108: 'Interjú szakemberekkel',
lt109: 'Cikkek',
lt110: 'Tájékoztató',
lt111: 'Gyógyszerek',
lt112: 'Intézmények',
lt113: 'Tanácsadás',
lt114: 'Rovatok',
lt115: 'Orvosaink',
lt116: 'Csevegés',
lt117: 'Blogok',
lt118: 'Csoportok',
lt119: 'Állásajánlatok',
lt120: 'Szórakozás',
lt121: 'Versenyek',
lt122: 'Orvosi horoszkóp',
lt123: 'Tesztek',
lt124: 'Alkalmazások',
lt125: 'MED-info',
lt126: 'Orvosi hírek',
lt127: 'Orvosi horoszkóp',
lt128: 'MED-info újság',
lt129: 'A projektről',
lt130: 'Partnerek',
lt131: 'Kapcsolat',
lt132: 'Tesztek',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};