var new_lang = {
lt1: 'l`Alcoolisme, vous pouvez le surmonter! Sauvez vos proches!',
lt2: 'Les actualités',
lt3: 'Communication',
lt4: 'S`abonner',
lt5: 'Journal de MED-info',
lt6: 'Consultation',
lt7: 'Manuel de médicaments et institutions',
lt8: 'Rubriques',
lt9: 'Manuel',
lt10: 'Consultations',
lt11: 'Communication',
lt12: 'Divertissement',
lt13: 'le journal<br>MED-info',
lt14: '<span>Manuel</span><br>des médicaments et des institutions',
lt15: '<strong>Consultations</span><br>Posez la question à votre médecin',
lt16: 'Application<br><span>mobiles</span>',
lt17: 'Rubriques',
lt18: 'Thèmes',
lt19: 'Analyse',
lt20: 'L’interactif',
lt21: 'Interview avec la star',
lt22: 'Infographie',
lt23: 'Histoire le lecteur',
lt24: 'La table ronde',
lt25: 'Sujet piquant',
lt26: 'Reportage',
lt27: 'Articles',
lt28: 'Actualités',
lt29: 'Hier à 13:26',
lt30: 'TOP 100 des meilleurs stomatologies',
lt31: 'Hier à 21:56',
lt32: 'En décembre, le début de French Pharma Awards',
lt33: 'Hier à 14:24',
lt34: 'Sondage: qui est nuisible à la santé &nbsp;au travail',
lt35: 'Les savants ont soulevé des neurones produisant l`hormone du bonheur',
lt36: 'Le plus intéressant',
lt37: 'Interview avec un expert',
lt38: 'Svetlana Tarasenko: «Laser de chirurgie dentaire — une méthode de traitement de l`avenir»',
lt39: 'Articles',
lt40: 'Comment ne pas se tromper dans&nbsp;le choix de la brosse à dents',
lt41: 'Alcoolisme',
lt42: 'Interview avec un expert',
lt43: 'L`alcoolisme, vous pouvez le surmonter! Sauvez vos proches!<br>Le médecin chef de Lille, le docteur des sciences médicales, professeur Michel Bertrand',
lt44: 'Note de la rédaction: Selon les derniers recherches de FRM, le nombre d`alcooliques en France a dépassé la barre des 5 000 000 de personnes ou de 3.4 % de la population. Sur le compte de la peine on a trouvé 1,7% des patients alcooliques. L`alcoolisme est la cause de la mort de 1/3 de tous les hommes et 15 % de femmes. Autrement dire environ 500 000 personnes meurent de l`alcool par an. Les détails choquants! Si on l’additionne tous ensemble, Le nombre de personnes qui meurent des guerres, des épidémies et des catastrophes naturelle est beaucoup plus petit! L’alcool en France, directement ou indirectement, provoque: 62.1% des suicides, 72.2% des meurtres, 60% des décès de pancréatite, 67.7% de la cirrhose et 23.3% de maladies cardio-vasculaires. Chaque année, on enregistre plus de 40 millions de cas d`intoxication insatisfaisant de l`alcool, on y compris mortelles. Nous avons demandé un docteur en sciences médicales, Michel Bertrand de la façon de se débarrasser de cette maladie et de devenir une personne en bonne santé',
lt45: 'C’est effrayant, quand l`addition à l`alcool détruit la vie d`un homme, à cause de l`alcool la famille s`écroulent, les enfants perdent des pères, et la femme du mari. Mais à notre époque, l`alcoolisme est une maladie très jeune. Souvent ce sont les jeunes qui détruisent leur avenir et leur santé. Il faut reconnaître que le plus souvent ce sont sur des femmes qui sauvent leurs fils, leurs maris, leurs pères de l’alcool. Il est possible de sauver un buveur de la famille, et de le faire dans le secret de lui-même. Aujourd`hui, nous allons parler d’un nouvel outil naturel <a target="_top" href="">XX</a>, qui semblit être incroyablement efficace.',
lt46: 'Peut-être que vous saviez que Presque pour le moment le seul remède efficace pour lutter contre la dépendance à l`alcool a été le codage du patient. Cette méthode a un désavantage très sérieux - le patient doit consentir au traitement et aller au codage avec son propre envie puis renoncer complètement de l`alcool. Pour toujours. Mais le plus souvent les buveurs ne considèrent pas eux-mêmes les dépendants de l`alcool. Ils sont sûres qu`ils peuvent à tout moment "se débarrasser". Seulement leur famille comprend que "se débarrasser" de l`alcool c’est pas si facile en tout cas, ils ne pourront jamais sans le faire sans l`aide de personne. Quoi faire? Convaincre, argumenter, supplier c’est tout à fait inutile, l`alcool a déjà un pouvoir sur lui. Reste une seule résolution - traiter un proche de la personne en secret pour le sauver. Un développement récent de médecins et de scientifiques l`outil XX permet de le faire. Dans de 2 semaines (14 jours) Il est capable de former un sentiment persistant de dégoût à l`alcool, même chez l`alcoolique chronique. Tout l`alcool devient dégoûté, même l`odeur de l`alcool provoque le dégoût.',
lt47: 'Comment XX fonctionne-t-il?',
lt48: 'XX est un remède entièrement constitué de composants naturels, ça signifie qu`il n`a pas de contre-indication, il est sans danger, il peut être pris par tout le monde. En outre, <a target="_top" href=""><b>"XX"</b></a> c`est un médicament avec des effets intégrés, en plus de la fonction de verrouillage de l’addition à l`alcool et de la formation de dégoût à l`alcool, il exécute également les processus de rétablissement de tous les organes, qui l`alcool a détruit. La régénération au niveau cellulaire se produit dans le foie, le coeur, les reins, la normalisation des fonctions du système nerveux. XX soulage des besoins psychologiques de prendre l’alcool, l`habitude de boire de l`alcool disparaît complètement et se remplace par la prise de conscience de l`importance de leur propre santé. Le patient se sent revigoré et plein d`énergie, sans la nouvelle portion de l`alcool. Il ne se sent plus familier de "casser".',
lt49: 'Comment ça fonctionne? – vous demanderez-vous. Je vais vous expliquer. À l`aide de substances spécifiques et des antioxydants XX affecte sur les récepteurs spécifiques des cellules qui sont responsables de la régénération et de l`efficacité. On se produit "l`écrasement" de l`information sur les patients des cellules saines. Finalement, le corps commence des processus de guérison, et c`est renvoie, comme nous le disons, un "point santé".',
lt50: 'En ce moment, il existe un unique site officiel commercialisant le médicament XX, pas les imitations. XX n`est pas vendu en pharmacie, si vous l`avons vu dans la chaîne de pharmacies de votre ville, sachez que c`est faux! On en parle beaucoup sur notre chaîne ainsi que sur les autres. Et c’est vrai, je vous dis! XX, c`est un mélange complexe et unique des substances naturels médicales des plus rares et des plus puissants. Cet outil a prouvé son efficacité non seulement aux patients, mais aussi à la science, qui est reconnue pour son efficace du médicament. De superbes effets sont observés après 10-15 jours de la réception, comme l`ont montré les études, XX fonctionne bien!',
lt51: 'Les recherches',
lt52: ', `Les résultats des tests de laboratoire <a target="_top" href="">"ХХа</a> à l`institut de Toxicologie:',
lt53: 'On a retenu 85 volontaires de différents âges souffrant de lourd, léger et moyen à sévère de l’addition à l`alcool. À la suite de 30 minutes de la journée d`étude on a obtenu <b>les résultats suivants:</b> ',
lt54: '1. On a fixé le bien-être amélioré de l`ensemble du groupe des personnes de 18 à 68 ans.',
lt55: '2. Il a été fixé un retrait total de l`alcool chez 96% des patients.',
lt56: '3. Déjà au bout de 10 jours d`une grande partie des patients ont déclaré la fondation de l`aversion de l`odeur et du goût des boissons alcoolisées.',
lt57: '4. Au bout de 30 jours, 97% des patients ont refusé de boire de l`alcool, on a fixé les indicateurs de l’amélioration de la santé du cœur, du foie et des reins.',
lt58: '<strong>Attention! </strong>, les cas de vente d`un faux médicament XX! C`est pourquoi nous plaçons spécialement pour nos lecteurs sur le bouton de commande de l`outil XX, le seul officiel du fabricant! En faisant la commande ici vous êtes assuré d`obtenir un produit de qualité au meilleur prix!<br><br> <p>notre site </strong> il <strong> prix</strong>. Pour l`obtenir, cliquez sur le bouton "Commander" ci-dessous. Vous trouverez sur le site officiel où vous pouvez passer une commande. Nombre de colis avec une décote limitée!',
lt59: 'Commentaires',
lt60: 'Margot Duran (Toulouse)',
lt61: 'Je ne peux pas croire. On a déjà essayé tellement de moyens! J’ai perdu la ',
lt62: 'Marie (Paris, 23.07.2016)',
lt63: 'Margot, C’est dommage que vous ne puissiez pas croire. Je vous recommande de l’essayer quand même, ça ne va pas aller pire! Nous aussi avons été traités par l`outil. Très bien. Mon mari s’est arrêté dans l`ivresse de partir. Maintenant il boit très rarement sur les jours fériés. Le contrôle de lui-même, et je n`ai pas peur pour lui. Bonne chance à tous! L`outil fonctionne!',
lt64: 'Valérie Leroy, 46 ans (Cannes, 23.07.2016)',
lt65: 'Il a essayé de sevrer le fils de la bière, mais j`ai ensuite réalisé que c`est déjà de la brasserie de l`alcoolisme. Tout d`abord, il prenait une bière chaque jour, allant de pair du travail, puis encore une bouteille sur la route, et un autre prenait pour lui le soir... Quand sa "norme" est parvenue jusqu`à 1,5 litre de bière chaque jour, j’ai compris qu`il fallait faire quelque chose! J’essayais d’abord d`autres méthodes qui n`avaient pas aidé. Je lui donnait aussi XX, mixé au thé, il n`a rien senti. Le troisième jour, il est venu à la maison sans la bière! J`ai été choqué, mais rien n`a commencé à parler et demander. Je regardait que sera plus loin, et il a absolument oublié de la bière! J`espère que pour jamais!',
lt66: ' Michel Bertrand, professeur (Lille, 24.07.2016)',
lt67: '> Ne pouvais pas laisser passer cette commentaire... Michel! Vous n`imaginez pas comme je suis heureux de vous, je suis sûr que vous avez changé la vie des personnes proches de mieux! <br><br>cordialement ',
lt68: 'Sophie Robert(Bordeaux, 24.07.2016)',
lt69: 'Margot, si on se désespère et perd tout l’espoir, alors bien sûr rien n`aidera! Mais c`est l`outil fonctionne vraiment, à un coût très abordable. Recommande tout de même de commander et de s`assurer personnellement de l`efficacité d`un médicament!',
lt70: 'Nathalie (Nantes, 24.07.2016)',
lt71: 'Mes proches sont mariés et ils ont aussi utilisé XX. Ainsi, c’est le cas qu’ils ont commencé à ivrogner tous les deux... J`ai cru que je le perdais, parce que ils ont perdu eux-mêmes tout intérêt pour la vie. Ils avaient encore de la chance qu’ ils soutenaient les uns les autres et tous deux ont décidé de s’arrêter définitivement. Je les ai bcp interrogé! ils disent qu’il n’ ont vraiment acunne envie de boire! De plus en imaginant une verre de l’alcool - tout de suite mal est fait. ',
lt72: ' Jacqueline D. (Marseille, 25.07.2016))',
lt73: 'J’ai sauvé mon mari avec ХХ, lui et son père et les deux grand-pères buvaient très fort, il se trouvait qu`à suivre leur exemple, mais non! Je lui donnait XX chaque jour, il était parfois difficile, mais j`ai pu. Il n’est pas deviné, Il estime qu’ il est descendu à l`esprit lui-même. J`ai d`abord voulu lui dire la vérité, mais puis j’ai décidé de ne pas tenter le sort. Laissez-le heureux et fier de lui. Pour moi, l`essentiel c’est qu’ il est sobre et en bonne santé!',
lt74: 'Claude (Paris, 25.07.2016)',
lt75: ' Jacqueline, correctement, ne dites pas mieux de rien, les gens pensent que c`est fait face à la mauvaise habitude. J`ai acheté XX pour mes parents, maman l’a donné au papa et il a pu sortir de l’addition à l’alcool. Très dommage qu`auparavant, ce fonds n`a pas éxisté, le père a perdu tant d`années à cause de l’alcool...<br><br> j`espère que l’addition à l’alcool ne reviendra jamais au père, mais si encore une fois de la queue – on prendra sûrement encore le cours! La mère a reservé encore un stock de ХХа.',
lt76: 'Polina Lasina (Nice, 26.07.2016)',
lt77: ' J`espère que le XX va soulager ma maman de l`enfer de l’alcoolisme de papa, nous avons déjà fait tellement do choses mais rien n`a aidé. Après un mois de XX, Il n’ a pas pris du tout de l’alcool, j`espère que ça continuera...',
lt78: ' Patricia (Nancy, 27.07.2016)',
lt79: 'Je vais aussi partager ma joie. Plusieurs fois je me suis déjà éloigné de mon petit ami, mais je me suis toujours revenue, tout de même destin. Ensuite, j`ai attrapé ce XX, j` en ai acheté beaucoup, avec le stock et le début de l`abreuver de son mari a été parti. Et ça nous a vraiment aidé! Il l’a mangé 3 semaines de chaque jour et un an dans la complication. <br> je veux dire merci aux créateurs de ce remède, et voici à quoi ressemble l`emballage de ХХ.',
lt80: ' Pascal, 37 ans (Marseille, 27.07.2016)',
lt81: ' Les gens, dites-moi où l’avez-vous acheté? Dans les pharmacies un tel outil n`est pas vendu. Je voudrais ne pas tomber dans un faux, mais comment je ne comprends pas, rien ne va.',
lt82: 'Michel Bertrand, professeur (Lille, 27.07.2016)',
lt83: 'Je vous rappelle que vous pouvez commander "XX" seulement par <a target="_top" href="">le site officiel</a>, pour ne pas vous tromper cliquez sur «Commander» si-deccous! Spécialement pour nos abonnés il y a un rabais fantastique! Mais ça peut pas durer toujours – dépêchez-vous!<br> Et Méfiez-vous des imitations! br><br> Michel Bertrand.',
lt84: 'Ajouter un commentaire:',
lt85: 'Votre prénom:',
lt86: 'Ville:',
lt87: 'Votre commentaire',
lt88: 'Les actualités',
lt89: 'Business',
lt90: 'Gouvernement et médecine',
lt91: 'Stars',
lt92: 'Science',
lt93: 'Société',
lt94: 'Évenement',
lt95: 'Statistique',
lt96: 'Pharmacie',
lt97: 'Actualité MED-info',
lt98: 'Calendaire des évenements',
lt99: 'Rubriques',
lt100: 'Reportage',
lt101: 'Analyse',
lt102: 'La table ronde',
lt103: 'Vidéo',				
lt104: 'Infographie ',
lt105: 'Intérractif',
lt106: 'Histoire',
lt107: 'Interview avec la star',
lt108: 'Interview avec un expert',
lt109: 'Articles',
lt110: 'Manuel',
lt111: 'Médicaments',
lt112: 'Institutions',
lt113: 'Consultations',
lt114: 'Rubriques',
lt115: 'Nos médecins',
lt116: 'Communication',
lt117: 'Blogs',
lt118: 'Groupes',
lt119: 'Offres d`emploi ',
lt120: 'Distractions',
lt121: 'Concours',
lt122: 'Horoscope médical ',
lt123: 'Tests',
lt124: 'Applications',
lt125: 'Med-info',
lt126: 'Actualité médicales',
lt127: 'Horoscope médical ',
lt128: 'Journal MED-info',
lt129: 'Sur le projet',
lt130: 'Partenaires',
lt131: 'Contacts',
lt132: 'Tests',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};