var new_lang = {
lt0: 'Erofertil',
lt1: 'Producto natural',
lt2: '26.000 aumentarón la potencia',
lt3: 'Comentarios de los clientes',
lt4: 'Pedir una llamada',
lt5: '<span>“Erofertil”</span>pondrá de manifesto todo tu potencial sexual',
lt6: 'Complejo de hierbas para la intensificación de la fuerza masculina',
lt7: 'Erección dura y estable',
lt8: 'Deseo sexual fuerte',
lt9: 'Resistencia y control de eyaculación',
lt10: 'Descuento<span>-50%</span>',
lt11: 'Precio nuevo',
lt13: 'Precio viejo',
lt14: 'Comprar Erofertil no caro. Precios, comentarios. ¡Pida Erofertil ahora!',
lt15: '¡Pedir con un descuento!',
lt16: 'Sus datos bajo la protección de SecureTECH',
lt17: '<span>¡IMPORTANTE!</span> ¡Con ciertos problemas en la esfera sexual se tropieza absolutamente cada hombre! El menosprecio de los síntomas preocupantes puede llevar a la impotencia sexual total y problemas serios psicológicos: inseguridad en sí mismo, miedo de desepcionar o no complacer a la pareja etc.',
lt18: '<span>26.000</span>nuestros clientes <br>estaban descontentos del sexo',
lt19: 'Han perdido la pasión como en la juventud',
lt20: 'A veces han sufrido por los fallos',
lt21: 'No podían satisfacer<br>a sus mujeres',
lt22: 'Han comenzdo a tener fobias y han perdido<br> la seguridad en sí  mismo',
lt23: 'Y no tienen culpa de eso: por la ecología y el estrés durante últimos 20 años la cantidad de los hombres menores de 35 años que tienen trastornos de erección se ha duplicado!',
lt24: 'Pero todos nuestros clientes han dejado sus problemas en el pasado con<span>“Erofertil”</span>',
lt25: '<span>Fórmula única</span> da fuerza masculina y seguridad',
lt26: '<span> Tribulus terrestris </span> Afrodisíaco fuerte, aumenta el nivel de testosterona, aumenta la potencia y energía sexual.',
lt27: '<span> La Damiana (turnera diffusa) </span> Afrodisíaco potente, intensifica la excitación sexual, elimina la tensión psícoemocional.',
lt28: '<span>La Maca peruana (Lepidium meyenii) </span>Afrodisíaco sudamericano popular, intensifisa la circulación sanguínea, mejora la calidad de esperma.',
lt29: '<span> Rhodiola rosea </span> Previene los problemas con la erección del caracter psicogénico, aumenta la sensibilidad y el tono del organismo en general.',
lt30: '<span> Bisglicinato de zinc </span>Mejora las funciones del sistema reproductivo, contribuye al aumento de la cantidad de espermatozoides producidos.',
lt31: '<span> Semillas de guaraná </span> Estimulador, provoca la libido elevada, intensifica la potencia, prolonga el acto sexual.',
lt32: '<span> Ginkgo biloba </span>Intensifica la micro-circulación, que influye positivamente en la erección.',
lt33: '<span> Goji </span> Se considera “la viagra natural”, mejora la calidad de relaciones sexuales, aumenta la libido.',
lt34: '<span> Levadura, enriquecida con selenio</span>Recupera la erección estable y fuerte, mejora la espermatogénesis.',
lt35: '<span>Niacina (ácido nicotínico, vtamina B3) - 20 mg (111% NRV)</span>Estimula la micro-circulación sanguínea, contribuye a la erección fuerte.',
lt36: '¡Todos los componentes de<span>“Erofertil”</span> complementan mutuamente el efecto uno del otro y estimulan la excitación sexual!',
lt37: '¡Muéstrale<br><span>cómo puedes!</span>',
lt42: '<span class="paced">unidades</span>están disponibles<br>en oferta',
lt49: 'El sexopatólogo recomienda <br><span>“Erofertil”</span><i class="icon-first-aid"></i>',
lt50: 'para la recuperación o intensificación de la erección y prolongación del acto sexual',
lt51: 'Para la recuperación e intensificación<span>de la erección recomiendo el preparado“Erofertil”</span>.',
lt52: 'Activa el proceso de la excitación sexual, que comienza en el cerebro y médula espinal.',
lt53: '<span>El preparado</span>acelera la transmisión de los impulsos nerviosos, que sintetizan el oxido nitrico en el organismo.',
lt54: 'Como resultado, la sangre  llena momentáneamente los cuerpos cavernosos del pene y sucede la erección.',
lt55: '<span>“Erofertil”</span> arregla el proceso de excitación en caso de la disfunción erectil y ayuda a prolongar el acto sexual en caso de la erección precoz.',
lt56: 'Antonio Barreda del Rio',
lt57: 'médico sexapatólogo, doctor<br>en ciencias médicas, profesor.',
lt58: 'Los resultados de las pruebas de Erofertil<br>entre<span>26.000 hombres</span> a la edad de 18-60 años',
lt59: 'según las investigaciones del Instituto de Sexología Clínica en el año 2017',
lt60: 'Se aumenta la producción de testosterona. Se aumenta la libido. Se recupera la elasticidad de los vasos sanguíneos y flujo sanguíneo. Se intensifican las sensaciones durante el coito.',
lt61: 'Se aumenta la actividad de los espermatozoides y cantidad del semen. El deseo sexual se intensifica, la erección se vuelve más fuerte.',
lt62: 'Los cuerpos cavernosos son capaces de llenarse de sangre por completo. La erección es duradera y estable. Se aumenta la sensibilidad e intensidad del coito.',
lt63: 'El control total de la erección. Se aumenta el tono del organismo, resistencia y sensibilidad. La fortaleza de la erección alcanza su máximo fisiológico y se mantene en adelante.',
lt64: 'Se aumenta el nivel de testosterona y la libido. Se intensifican las sensaciones durante el acto sexual.',
lt65: 'El organismo se adapta poco a poco al preparado. La erección se debilita, a veces surge incontroladamente.',
lt66: 'La sensibilidad durante el coito baja. La erección surge solamente durante la estimulación directa del pene. Hasta si hay una erección puede faltar la eyaculación.',
lt67: 'Se produce la insensibilidad del organismo al preparado. Se recuperan los problemas con la erección y eyaculación precoz. Son posibles efectos secundarios: enfermedades del corazón, del tracto gastrointestinal, erupción en la piel.',
lt68: '¿Por qué más de <span>26.000</span>hombres han elegido<span> “Erofertil”?</span>',
lt69: '<i class="icon-white-tick"></i>Erofertil',
lt70: 'La composición única recupera tu fuerza masculina para mucho tiempo',
lt71: 'Los ingredientes naturales contribuyen a la producción de testosterona',
lt72: 'Gracias a la intoxidad se puede combinarlo con el alcohol y medicamentos',
lt73: 'Sintetiza el oxido nitrico – elémento principal en la aparición de la erección',
lt74: '¡El efecto garantizado en 2 semanas ya!',
lt75: '<i class="icon-white-cross"></i>Otros preparados',
lt76: 'Tienen un efecto temporal',
lt77: 'Aumentan la presión arterial',
lt78: 'Está prohibido tomar con el alcohol y medicamentos',
lt79: 'La composicón sintética, peligrosa para la salud',
lt80: '¡Una eficiencia baja, costo alto, y tratamiento duradero!',
lt82: 'Comentarios sobre<span>“Erofertil”</span>',
lt83: 'Clientes <span>contentos</span>',
lt84: '<span>Víktor</span>estoy casado 6 años. Tengo 31, mi esposa tiene 26. Es sexy, alta, los pechos de la talla 2,5, firmes… En general, vivía y me alegraba, hasta que en el sexto año del matrimonio han aparecido los fallos. Y ella es caliente, es la envidia de todo el mundo, y seguro que en cuanto muestro alguna debilidad ya, la van a raptar… Por suerte, el problema hubo una vez, pero he decidido no correr riesgos más. He comenzado a buscar un medicamento en forma de aditivo-intensificador. He comenzado a leer de las astas y arvense y del cómo curarme con eso, luego he comenzado a buscar un prepardo adecuado, sin falsificaciones ni sustitutos. He encontrado Erofertil y lo he pedido. El problema no ha surgido más y no surge, y si vuelve a surgir – volveré a comprar el preparado.',
lt85: '<span>Andrés</span> Lo peor que puede pasar con un hombre es cuando se vuelve débil en la cama. Es poco que aparecen complejos de inseguridad, más la relación deja de funcionar. La chica puede no decir nada, pero entre ustedes va a crecer el frio y la distancia. Así era en mi caso: hemos comenzado a conversar menos, hemos empezado a reñir, ella se ha vuelto más tensa y mala. Y estoy agradecido  a “Erofertil” por haberme ayudado y salvado mi relación.',
lt86: '<span>Iván</span>He empezado a tener problemas con la potencia. Primero he perdido el interés hacia el sexo, lo hacía no más que un par de veces al mes. En aquel tiempo no tenía pareja, por eso no habían muchas problemas con eso. Pués, no se me erectó de una vez. Pués, se me cayó durante el proceso. No siempre sale todo bien, además con el condón. Pero luego he encontrado la pareja. Y he comenzado a solucionar mi problema activamente, y si antes culpaba de eso el cansancio y condón, y ahora me he dado cuenta de que no era eso. Hasta iba a inscribirme en la consulta del psicólogo, pero he visto en la red la publicidad de Erofertil. He pensado: al carajo todo, he seguido el enlace, he leido, he hecho el pedido, lo he comprado y lo he tomado. Ahora lo tengo como piedra)',
lt87: '<span>Pablo</span>¡Adoro el sexo! Y lo recomiendo a otros)) Tengo 24 años, curro en 2 trabajos y estoy emprendiendo mi negocio. Ya que trabajo duro, descanso igual. Muchas chicas, clubes, fiestas, discotecas… Ha comenzado a erectarse con dificultad después de que estuve trabajando todo el día y tomé mucho en la fiesta. La Viagra y otras nunca me han agradado, y he decidio ir por otro camino y fortalecer mi potencia. Por eso he pedido Erofertil, ya que intensifica, y se puede tomarlo con alcohol también. Ahora entre amigos me llaman Pablo el Percutor)',
lt88: '¡Siente un placer con<br><span>“Erofertil”!</span>',



};

function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
};