var new_lang = {
    lt0: 'A magas vérnyomás és az általa okozott nyomásesések - az esetek 89% -ában szívrohamot vagy stroke-ot okoznak!',
    lt1: 'Egészségügyi Minisztérium',
    lt4: 'Egészség',
    lt5: 'Tevékenység',
    lt6: 'Dokumentumok',
    lt7: 'Sajtóközpont',
    lt8: 'Versenyek',
    lt9: 'Fő oldal',
    lt10: 'Sajtóközpont',
    lt11: 'Hírek',
    lt12: 'A magas vérnyomás és az általa okozott nyomásesések - az esetek 89% -ában szívrohamot vagy stroke-ot okoznak!',
    lt13: 'A magas vérnyomás és a nyomás ugrások - maradnak a múltban!',
    lt14: 'Szívroham és stroke - halálesetek közel 70% -át okozza a világon. Tíz ember közül hét meghal, a szív vagy az agy artériák elzáródása miatt. Gyakorlatilag minden esetben az ilyen szörnyű végzet oka - magas vérnyomás okozta egynyomású ugrások. Csendes gyilkos ahogy elnevezték a kardiológusok, évente több millió ember életét veszi el.',
    lt15: 'Király Kinga',
    lt16: 'Szívsebész, feltaláló, tanár, professzor, orvostudomány akadémikusa.',
    lt17: 'Munkatapasztalat - 48 év',
    lt18: 'A témáról:',
    lt19: 'Nem titok, hogy a szív- és érrendszeri megbetegedések - a világvezető betegségek az általuk elvett életek száma alapján. A magas vérnyomás a cardiovascularis megbetegedések számláján rögzített szívrohamok és strokeok fő oka. Természetesen más betegségek is nyomást gyakorolnak a testre, de a hipertónia és az általa okozott nyomáskülönbségek szolgálnak arra a kiváltó tényezőre, amely egy embert küld el a túlvilágba. ', 
    lt20: 'A konkrét értékekről szólva a hipertónia a végzetes "természetes" kimenetek mintegy <strong>77-78% -áért felelős. </strong>Abszolút értelemben - ez körülbelül 1,54 millió haláleset 2015-ban, és 1,49 millió 2014-ben. Vagyis a számok valóban óriásiak és félelmetesek. Egészen a közelmúltig senki sem gyanította a katasztrófa méretét, mert nem volt részletes statisztika és elemzés. A 2011 és 2015 közötti időszakra nagy mennyiségű adatot gyűjtöttünk össze, ami meglehetősen kiábrándító következtetésekhez vezetett. ',
    lt21: 'A nyomás minden esetben óriási túlterhelést okoz a szívizomnak, amely előbb-utóbb szívmegállással végződik. Nagyjából mondható, hogy minden alkalommal,  a megnövekedett nyomás 10-20-szoros túlterhelést okoz a szívben. Ha a betegség végső kifejlődéséről beszélünk',
    lt22: 'a magas vérnyomás mindig ugyanarra az eredményre vezet - halálra',
    lt23: 'Ha azonban az emberi halálozás legfontosabb okaként pontosan megemlítjük, akkor ez az esetek 89% -ában történik meg. Ez azt jelenti, hogy a helyzetek 89% -ában a magas vérnyomás szívrohammal vagy strokkal  és halállal végződik. Ugyanakkor, ha még 20-30 évvel ezelõtt is, a diagnózisban szenvedõ betegeknek jó esélyük volt 10-20 évig élni, most a betegek elsõ öt évében körülbelül <strong> 2/3 (kétharmada) meghalnak. ',
    lt24: 'A betegek 2/3-a (kétharmada) a betegség első öt évében hal meg.',
    lt25: 'Különösen szörnyű az a tény, hogy sok ember nem is gyanítja, hogy magas vérnyomásuk van. És kihagyják a lehetőséget arra, hogy valamit kijavítsanak, és csak halált várnak. ',
    lt26: 'Ezek a tünetek alapján megállapíthatja, hogy magas vérnyomása van: ',
    lt27: 'Fejfájás',
    lt28: ' Szívverés gyorsulása ',
    lt29: 'Fekete pontok a szemek előtt (légy)',
    lt30: 'Apátia, ingerlékenység, álmosság',
    lt31: 'Homályos látás',
    lt32: 'Izzadás', 
    lt33: 'Krónikus fáradtság',
    lt34: 'Arc duzzanat',
    lt35: 'Az ujjak zsibbadása és hidegrázása',
    lt36: ' Nyomás ugrások ',
    lt37: 'Még a tünetek egyikénél is el kell gondolkodnia. És ',
    lt38: 'ha kettő van, akkor ne habozzon: magas vérnyomása van',
    lt39: 'Egyébként a statisztikák szerint ',
    lt40: '67% - a hipertóniás betegek nem veszik észre, hogy beteg.',
    lt41: 'Hogyan védhetjük meg magunkat és leküzdhetjük a betegséget?',
    lt42: 'Mindenekelőtt meg kell értenünk, hogy érdemes felhagyni a rossz szokásaid, különösen a dohányzást és az alkoholt. Ez csak súlyosbítja a helyzetet az artériás nyomással. A következő tény - hogy leüsse a nyomást, maskép sehogy. De ez nem gyógyítja meg a betegséget. Sőt, ha túlozni a gyógyszerekkel és éles nyomást kap, ez a test rendkívül negatív reakcióját eredményezheti még a szívrohamig is. Ez nem beszélve arrol, hogy a tabletták rendkívül nagy terhet rónak a májra. ',
    lt43: 'Valójában jelenleg az egyetlen gyógyszer, amelyet az orvosok hivatalosan a magas vérnyomás kezelésére ajánlanak fel, és amelyet a kardiológusok a munkájuk során használnak - az <a href=""><strong>ReCardio</strong></a>. Fejlesztése néhány évvel ezelőtt kezdődött, és a közelmúltban fejeződött be. A termék létrehozása olyan szakembercsapatot érintett, akik szorosan együttműködtek a kardiológusokkal. Ennek eredményeképpen egyedülálló eszköz volt, amely megbízhatóan "oltja" a magas vérnyomást és megszünteti annak okát, szemben az összes többi gyógyszerrel. ',
    lt44: '2016-ban a Preventív Orvoslás Állami Kutatóközpontja részeként a Kardiológiai és Szívsebészeti Kutatóközpont tudományos és gyakorlati központja sikeresen befejezte a  <a href=""><strong>ReCardio</strong></a> magas vérnyomás elleni küzdelemre irányuló új generációs gyógyszerek klinikai vizsgálatát. Az Intézet Sajtószolgálata kihirdette a következőket: ',
    lt45: '1. A standard módszerrel kiszámított ReCardio hatékonysága (azoknak a betegeknek a száma, akik 100-nál több betegnél részesültek, akik kezelés alatt álltak) a következő volt:',
    lt46: ' –	A nyomás normalizálása - 97% ',
    lt47: ' –	Vénás trombózis megszüntetése - 80%. ',
    lt48: ' –	Az erőteljes palpitáció megszüntetése - 99% ',
    lt49: ' –	A fejfájás megszűnése - 100% ',
    lt50: ' –	Napközbe életerő növelése, éjszakai alvás javítása - 97%. ',
    lt51: '* A helyreállítás ebben az esetben azt jelenti, hogy megszabadulunk az összes tünettől, és nem jelentkeznek 6 hónapon belül. ',
    lt52: '2.	Nemkívánatos mellékhatások, beleértve az allergiás reakciókat, nem mutatnak ki. ',
    lt53: '3.	A ReCardio-t a hipertónia elleni küzdelem egyik vezető gyógyszereiként ismerik el. ',
    lt54: 'Barna Ádám',
    lt55: 'A Kardiológiai és Szívsebészeti Tudományos és Gyakorlati Központ igazgatója. Professzor.',
    lt56: 'Munkatapasztalat - 29 év',
    lt57: 'Intézményünk munkatársai azt találták, hogy a gyógyszer befolyásolja a betegség okait, ami lehetővé teszi a magas vérnyomás megszabadulását. A tüneteket a felhasználás utáni első hat órában eltávolít, az aktív komponenseknek köszönhetően. Ez lehetővé teszi a kúra kezdete után azonnal, amit úgy nevezünk, mélyen lélegezni. ',
    lt58: 'Az érrendszeri tónus teljesen helyreállt egy k]ra után. Ezenkívül a ReCardio hatékony a magas vérnyomás bármely szakaszában. A gyógyszer természetesen átment a klinikai vizsgálatokban. Szeretném megjegyezni, hogy a tesztelési folyamat hatékonysága bizonyult, és nem ad esélyt semmiféle külföldi eszköznek ellene. A nyugati gyógyszerek legjobb eredményei 20-21% -ban gyógyulnak. Esetünkben a gyógyult 75-77% -áról beszélünk. Minden más  helyzetben egyszerűen stabilizálódik. Vagyis maga a magas vérnyomás a kezdetleges állapotban megmaradt (a vaszkuláris tónus problémája). De ugyanakkor nem ugrál a nyomás, és nagyszerűen érzi magát. ',
    lt59: 'Magyarországon kívül a ReCardio-et Svájcban és Németországban  klinikai vizsgálatoknak vetették alá, ami szintén megerősítette hatékonyságát. Most nagy a kereslet erre a gyógyszerre. De egy különleges megrendelés szerint csak hazánkban értékesítik, ami olyan kis mennyiségű termelésnek köszönhető, amely nem áll készen erre a keresletre. ',
    lt60: 'Jelen pillanatban a gyógyszert kis tételekben állítják elő, bár a gyártó már új kapacitást épített fel, amely többször növeli a mennyiséget. ',
    lt61: 'Jelenleg az eredeti <strong> ReCardio </ strong> termék rendelhető a <a href=""> gyártó hivatalos weboldalán </ strong> </a>.',
    lt62: '194 megjegyzés',
    lt63: 'Varga Judit',
    lt64: 'Először hallottam a termekről három hónappal ezelőtt és azonnal megrendeltem. A nyomással nagy problémák voltak. És az első nap után - semmit sem ugrott a nyomás. Élvezem az életet egyszerűen. ',
    lt65: '12 perce',
    lt66: 'Király Kata',
    lt67: 'Én is vásároltam a nagymamának - neki mindig a nyomás a probléma. Ő maga valószínűleg nem fog valamit az interneten megrendelni, még akkor sem, ha telefonon. Így én magam. Segített 100% -ot, bár a problémák régóta és globálisak voltak - már évek óta sok gyógyszert szedd.',
    lt68: '17 perce',
    lt69: 'Missis Smit',
    lt70: 'Valami orvosi folyóiratban olvastam erről a termékről. Egy szakértői cikk volt, itt van ... .',
    lt71: '19 perce',
    lt72: 'Katalin',
    lt73: 'Hallottam valahol én is. Valaki a barátaim közül rendelt magának. Magamnak problémák vannak már második éve, most ahogy elolvastam - eldöntöttem. Megrendelem én is, megpróbálom.',
    lt74: '21 perce',
    lt75: 'Bandi',
    lt76: 'Én is rendeltem. Megígértek, hogy két napon belül szállítanak, várom.',
    lt77: '25 perce',
    lt78: 'Ilona',
    lt79: 'Én is megrendeltem, 2 kúrára. Nálunk a családban mindenkinek problémája van a nyomással. És leggyakrabban szívrohamtól halnak meg. ',
    lt80: '27 perce',
    lt81: 'Kiss Enikő',
    lt82: 'Csak tegnap láttam erröl a ReCardio a tévében. Ott mesélték arról, hogy milyen jó gyógyszert az orvosok létrehozták magas vérnyomás ellen. ',
    lt83: '30 perce',
    lt84: 'Alex',
    lt85: 'A családban szinte minden nő halt meg szívrohamtól. Mindenkinek volt problémája a magas vérnyomsással. Igen, és a férfiaknak talán túl sokan voltak ilyenek. Én is hagyok alkalmazást . ',
    lt86: '34 perce',
    lt87: 'Men',
    lt88: 'Remélem, hogy a gyógyszer továbbra is annyit fog érni, és nem 0000 рубль.',
    lt89: '39 perce',
    lt90: 'Szabina',
    lt91: 'Megrendeltem a nővéremnek két hónapja. Hosszú ideig szenvedett a nyomástól. Nem is tudja elképzelni mennyire hálás volt hogy megrendeltem a gyógyszert.',
    lt92: '42 perce',
    lt93: 'Bogdán Balázs',
    lt94: 'Nekem úgy tűnik hogy minden rendben van nyomással, de az anyám folyamatosan szenved. Neki megrendelem - remélem segít.',
    lt95: 'egy órával ezelőtt',
    lt96: 'Vash Márta',
    lt97: 'Sokkal jobban érzem magam, mintha még fiatalabb volnék. De a  külsőt nagyon érintet. Minden fiatalabb lett és egészségesebb.',
    lt98: 'egy órával ezelőtt',
    lt99: 'András',
    lt100: 'Ez egy csoda, Igen. Az ReCardio-t azonnal elrendeltem, ahogy hallottam róla. Kár, hogy 5 évvel ezelőtt nem tudtam róla, évek óta fájdalomtól szenvedtem, de most már életben vagyok és jól vagyok! Nyissa meg a világ! Köszönöm szépen.',
    lt101: 'egy órával ezelőtt',
    lt102: 'Tóth Ákos',
    lt103: 'Sok véleményе láttam erröl az ReCardio-röl. Aztán egy barátomnál hasonló probléma merült fel. Azt hiszem tanácsolni fogok neki, hogy megrendelje!',
    lt104: 'egy órával ezelőtt',
    lt105: 'Pintér Judit',
    lt106: 'A férjem sokat segített! A nyomás stabilizálódott! Csak 3 darab elég volt. Most én rendeltem magamnak! Segít tökéletesen.',
    lt107: 'egy órával ezelőtt',
    lt108: 'Ez nagyszerű! Kell rendelni, mert már belefáradtam ebbe a magas nyomásba!',
    lt109: 'két órája',
    lt110: 'Anna816',
    lt111: 'Nem fogszjátok elhinni, ugyanaz a probléma,volt nekem az erő folyamatos csökkenése, teljesen elvesztettem az érdeklődést az életben, már kétségbeesett, és itt ez a ReCardio, ez csak egy csoda jelenti, mindenkinek ajánlom',
    lt112: 'két órája',
    lt113: 'Zoli',
    lt114: 'A fösvény kétszer fizet. Információt találtam a ReCardio-ról, de nem rendeltem meg. Úgy döntöttem, hogy az interneten vásárolok, olcsóbban. Valami másra bukkantam. Ennek eredményeként szidtam magam és megrendeltem a hivatalos honlapon. Érdekes, de <a href="">ReCardio</a> jött azonnal, ami nagyon jó. Köszönöm.',
    lt115: '3 órája',
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};