var new_lang = {

    "lt0": "Zum Inhalt",
    "lt1": "Wir verwenden cookies, um sicherzustellen, dass Sie ein bestmögliches Nutzungserlebnis  auf der Website des Rates erzielen können. Bestimmte cookies werden verwendet, um Sammelstatistiken über Website-Besuche zu erhalten, die uns helfen, die Website  ständig zu verbessern und Ihre Bedürfnisse besser zu erfüllen. Andere cookies werden verwendet, um die Leistung zu steigern und die Sicherheit der Website zu gewährleisten.",
    "lt2": "Mit Ihrer Zustimmung verwenden wir AT Internet cookies, um aggregierte, anonyme Daten über unsere Besucher und deren Nutzung unserer Website zu erstellen. Wir verwenden diese Daten, um Ihre Erfahrung auf unserer Website zu verbessern.",
    "lt3": "Weitere Informationen zu diesen Cookies, wie und warum wir sie verwenden und wie Sie Ihre Einstellungen ändern können, finden Sie auf unserer<a href=\"{url}\">Cookie-Richtlinienseite</a>.",
    "lt4": "<span class=\"icon-plus\"></span>mehr lesen",
    "lt5": "Ich akzeptiere Cookies",
    "lt6": "Ich lehne Cookies ab",
    "lt7": "Folgen Sie uns",
    "lt8": "<span class=\"icon-22 icon-left icon-envelope-open\"></span>E-Mail-Abonnement",
    "lt9": "Der Europäische Rat",
    "lt10": "Der Rat der Europäischen Union",
    "lt11": "BG",
    "lt12": "български",
    "lt13": "ES",
    "lt14": "español",
    "lt15": "CS",
    "lt16": "čeština",
    "lt17": "DA",
    "lt18": "dansk",
    "lt19": "DE",
    "lt20": "Deutsch",
    "lt21": "ET",
    "lt22": "eesti",
    "lt23": "EL",
    "lt24": "Ελληνικά",
    "lt25": "EN",
    "lt26": "Englisch",
    "lt27": "FR",
    "lt28": "français",
    "lt29": "GA",
    "lt30": "Gaeilge",
    "lt31": "HR",
    "lt32": "hrvatski",
    "lt33": "ES",
    "lt34": "italiano",
    "lt35": "LV",
    "lt36": "latviešu",
    "lt37": "LT",
    "lt38": "lietuvių",
    "lt39": "HU",
    "lt40": "magyar",
    "lt41": "MT",
    "lt42": "Malti",
    "lt43": "NL",
    "lt44": "Nederlands",
    "lt45": "PL",
    "lt46": "polski",
    "lt47": "PT",
    "lt48": "português",
    "lt49": "RO",
    "lt50": "română",
    "lt51": "SK",
    "lt52": "slovenčina",
    "lt53": "SL",
    "lt54": "slovenščina",
    "lt55": "FI",
    "lt56": "suomi",
    "lt57": "SV",
    "lt58": "svenska",
    "lt59": "Menu",
    "lt60": "Der Europäische Rat",
    "lt61": "Der Europäische Rat",
    "lt62": "Der Europäische Rat ist die EU-Institution, die die Allgemeine politische Richtung und Prioritäten der europäischen Union definiert. Sie besteht aus den<strong>Staats-oder Regierungschefs der Mitgliedstaaten</strong>, zusammen mit Ihrem Präsidenten und dem Präsidenten der Kommission.&nbsp;",
    "lt63": "Lesen Sie mehr über die Rolle des Europäischen Rates",
    "lt64": "Festlegung der politischen Agenda der EU",
    "lt65": "Rolle bei Nominierungen und Ernennungen",
    "lt66": "Schlussfolgerungen des Europäischen Rates",
    "lt67": "Geschichte des Europäischen Rates",
    "lt68": "Charles Michel, Präsident des Europäischen Rates",
    "lt69": "Rolle",
    "lt70": "Biographie von Charles Michel",
    "lt71": "Kabinett",
    "lt72": "Ehemalige Präsidenten des Europäischen Rates",
    "lt73": "Euro-Gipfel",
    "lt74": "Geschichte des Euro-Gipfels",
    "lt75": "Der Rat der EU",
    "lt76": "Der Rat der Europäischen Union",
    "lt77": "Der Rat der EU ist die Institution, die die Regierungen der Mitgliedstaaten vertritt. Informell&nbsp;auch EU-Rat genannt, hier treffen sich&nbsp;<strong>nationale Minister aus jedem EU-Land</strong>&nbsp;um Gesetze zu verabschieden und Politiken zu koordinieren.",
    "lt78": "Entscheidungsprozess",
    "lt79": "Abstimmungssystem",
    "lt80": "Rolle in internationalen Abkommen",
    "lt81": "Schlussfolgerungen und Beschlüsse",
    "lt82": "Ratsformationen",
    "lt83": "Vorbereitungsgremien",
    "lt84": "Vorsitz des Rates",
    "lt85": "Geschichte des Rates der EU",
    "lt86": "Eurogruppe",
    "lt87": "Präsident der Eurogruppe",
    "lt88": "Wie die Eurogruppe funktioniert",
    "lt89": "Arbeitsprogramm",
    "lt90": "Arbeitsgruppe der Eurogruppe",
    "lt91": "Politik",
    "lt92": "Richtlinien",
    "lt93": "Der Rat der EU und der Europäische Rat arbeiten an einer Vielzahl von Fragen, die die Interessen der EU und ihrer Bürger betreffen.",
    "lt94": "Verfolgen Sie die neuesten Entwicklungen zu<strong>Politikgestaltung</strong>und zu<strong>Gesetzgebung</strong>, die derzeit verhandelt wird.",
    "lt95": "Alle Richtlinien anzeigen",
    "lt96": "Eine digitale Zukunft für Europa",
    "lt97": "EU-UK Verhandlungen über die künftige Beziehungen",
    "lt98": "COVID-19 Corona-Virus-Pandemie",
    "lt99": "Ein Wiederauffüllungsplan für Europa",
    "lt100": "Alle Richtlinien anzeigen",
    "lt101": "Terminkalender",
    "lt102": "Die Treffen",
    "lt103": "Der<strong>Europäische Rat </strong>bringt mindestens viermal im Jahr EU-Staats-und Regierungschefs zusammen.",
    "lt104": "Der<strong>Rat der EU - </strong>trifft sich&nbsp;in verschiedenen Konfigurationen je nach Thema.",
    "lt105": "<strong>Ausschüsse und Arbeitsgruppen </strong>übernehmen die Vorbereitung der Akten, bevor sie in Ratssitzungen besprochen werden.",
    "lt106": "Alle Treffen anzeigen",
    "lt107": "Gipfel -und Ministertreffen",
    "lt108": "Vorbereitungsgremien",
    "lt109": "Dokumente & amp; Publikationen",
    "lt110": "Dokumente & amp; Publikationen",
    "lt111": "Dokumente des Rates und des Europäischen Rates werden im<strong>öffentlichen Register</strong> gemäß den<strong>EU-Transparenzregeln</strong>zur Verfügung gestellt.",
    "lt112": "Sie können sich auch Veröffentlichungen des Rates ansehen, auf die Archive zugreifen und nach Rechtsvorschriften suchen, die der Rat zusammen mit dem Europäischen Parlament aushandelt.",
    "lt113": "Erfahren Sie mehr über Dokumente und Publikationen",
    "lt114": "Dokumentenregister",
    "lt115": "Archive",
    "lt116": "Publikationen",
    "lt117": "PRADO (Öffentliches Register echter Identitäts- und Reisedokumente )",
    "lt118": "Suche nach Rechtsakten unter \"Mitentscheidung\"",
    "lt119": "Regierungskonferenzen",
    "lt120": "Bibliothek",
    "lt121": "Datenbank der Verträge und Vereinbarungen durchsuchen",
    "lt122": "Presse",
    "lt123": "Pressestelle",
    "lt124": "Die Pressestelle ist&nbsp;<strong>die erste Anlaufstelle</strong>für alle Medienanfragen. Pressesprecher sprechen inoffiziell über die Aktivitäten des Rates.",
    "lt125": "Die Pressestelle hält&nbsp;<strong>Presseveranstaltungen</strong>, bietet&nbsp;<strong>audiovisuelle Berichterstattung</strong>&nbsp;von Großveranstaltungen und bietet&nbsp;<strong>Einrichtungen für Journalisten</strong>. &nbsp; &nbsp;&nbsp;",
    "lt126": "Erfahren Sie mehr über PRESSEDIENSTE",
    "lt127": "Pressemitteilungen",
    "lt128": "Press Kalender",
    "lt129": "Pressezentrum",
    "lt130": "Pressekontakte",
    "lt131": "Medienakkreditierung",
    "lt132": "Rat live",
    "lt133": "Videos und Fotos",
    "lt134": "Infografiken",
    "lt135": "E-Mail-und sms-Abonnements",
    "lt136": "TV-und Radio-Studios",
    "lt137": "Wenden Sie sich",
    "lt138": "Wenden Sie sich",
    "lt139": "Der Sitz des Rates der EU und des Europäischen Rates befindet sich in<strong>Brüssel</strong>(Belgien).",
    "lt140": "Sie können Kontakt aufnehmen, um einen<strong>Besuch</strong> zu arrangieren,<strong>Fragen</strong>zur Arbeit beider Institutionen zu stellen und unter anderen Dienstleistungen ein&nbsp;<strong>Dokument anzufordern</strong>.",
    "lt141": "Alle Kontaktinformationen anzeigen",
    "lt142": "Wie komme ich zum Rat",
    "lt143": "Stellen Sie eine Frage",
    "lt144": "Besuchen Sie den Rat",
    "lt145": "Soziale Medien",
    "lt146": "Startseite",
    "lt147": "Die Treffen",
    "lt148": "Der Europäische Rat",
    "lt149": "Eine Krankheit, die unterschätzt wurde: Fußpilz tötet die Immunität und erhöht das Risiko einer Virusinfektion!",
    "lt150": "<script type=\"text/javascript\">var appendNull = function (num) {return num< 10 ? 0 + num.toString() : num;};d = new Date();p = new Date(d....getTime() - 4 * 86400000 ein);monthb = 'Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember'.split(',');Dokument.write (appendNull (P. getDate ()) + \" + monthb[P.getMonth()] + \" + P. getFullYear ());</script>02. Oktober 2020 fand die jährliche medizinische Konferenz der Europäischen Gesellschaft für Gastrointestinal Endoscopy (ESGE) statt, wo artikulierten sensationelle Aussage präsentiert wurde. Jüngste Studien haben eine höhere Anfälligkeit für Virusinfektionen bei Menschen mit Pilzinfektionen gezeigt.",
    "lt151": "<b>Laut der weltweiten Statistik leidet jeder fünfte Bewohner des Planeten an Onychomykose (Fuß-und Nagelpilz).</b>Die Krankheit wird durch Pilze verursacht-Dermatophyten Trichophyton rubrum, Trichophyton interdigitale, Trichophyton tonsurans, seltener Epidermophyton floccosum und mikrosporie (Microsporum canis) und andere. Es ist nicht einfach, eine Pilzinfektion loszuwerden, und angesichts der jüngsten Forschung kann diese Krankheit zu schwerwiegenderen Folgen führen als unangenehmer Geruch, Juckreiz oder Nagelschäden.",
    "lt152": "Der Pilz verschlingt Sie von innen!",
    "lt153": "Dr. Louis-Philippe DOMBARD",
    "lt154": "Louis-Philippe Dombard. Es war eine Überraschung für alle.<b>Während der Forschung wurde festgestellt, dass Menschen, die an einer Pilzläsion der Füße und Nägel leiden, leiden auch an Virusinfektionen, einschließlich die neue, 20! mal öfter als die gesunde.</b>Diese Beziehung alarmierte Wissenschaftler und nach sorgfältiger Forschung wurde es festgestellt, dass der Pilz zu einer Abnahme der Immunität führt, wodurch der geschwächte Körper zu einer günstigen Umgebung für die Entwicklung der Infektion wird.",
    "lt155": "Heutzutage leiden Millionen von Menschen an verschiedenen Arten von Pilzerkrankungen der Haut der Füße und Nägel. Manchmal ist die Krankheit fast asymptomatisch, aber meistens ist eine Pilzinfektion durch die folgenden Symptome gekennzeichnet:",
    "lt156": "Verdickung, Zerbrechlichkeit, Farbwechsel der Nagelplatte,",
    "lt157": "Risse zwischen den Fingern,",
    "lt158": "Rötung, Juckreiz, Brennen,",
    "lt159": "Verdickung der Haut an den Fußsohlen, Risse,",
    "lt160": "unangenehmer Geruch,",
    "lt161": "Schwitzen,",
    "lt162": "In schweren Fällen sind allgemeine Schwäche, manchmal eine Erhöhung der Körpertemperatur eingetreten.",
    "lt163": "Die Krankheit hat verschiedene Stadien und je früher die richtige Behandlung begonnen wird, desto höher ist die Chance, die Infektion loszuwerden.",
    "lt164": "<b>Stadium 1</b>Krankheit wird durch eine Veränderung der Nagelfarbe und Verdickung der Nagelplatte gekennzeichnet. Juckreiz oder Rötung der Haut kann vorhanden sein, wenn der Pilz die Haut betrifft.",
    "lt165": "<b>Stadium 2</b>Veränderungen sind sichtbarer, Hyperkeratose beginnt (Verdickung der Haut an den Füßen), Nagelbrösel, Risse zwischen den Fingern oder an den Fersen erscheinen. Juckreiz und Brennen werden stärker, unangenehmer Geruch erscheint. Häufiges waschen hilft nicht und die Umgebung fühlen den Geruch.",
    "lt166": "<b>Stadium 3</b>Die Krankheit schreitet voran, was zur Zerstörung der Nägel, zur Bildung einer festen Schicht abgestorbener Zellen auf der Hautoberfläche führt. Risse sind tief, bringen quälende Schmerzen beim gehen, können bluten. Der Geruch wird stark, unangenehm und ständig vorhanden. Risse können zu einem Tor für eine bakterielle Infektion werden, was oft zu Blutbefall, Gangrän und anderen schrecklichen Folgen führt. In diesem Stadium ist es viel schwieriger  Pilz zu behandeln als in den vorherigen. Chirurgische Techniken wie das entfernen von Nägeln und das abschneiden der rauhen Haut werden aufgewendet.",
    "lt167": "\"Wenn der Pilz die Füße getroffen hat, wird er sich weiter ausbreiten, neues Gewebe einfangen und neue Bereiche treffen. Er ernährt sich von ihren Geweben, der Pilz verschlingt Sie buchstäblich von innen!\"",
    "lt168": "Onychomykose",
    "lt169": "In den heutigen schweren Bedingungen, in denen neue Virusinfektionen entstanden sind, ist es äußerst wichtig, den Einwohnern der europäischen Länder bei der Bewältigung der damit verbundenen Infektionen zu helfen, die den Verlauf chronischer Krankheiten verschlimmern und die Anfälligkeit für neue Viren erhöhen können.",
    "lt170": "Leider sind viele Menschen nicht verantwortlich genug, um eine Pilzinfektion zu behandeln, eine Krankheit auszulösen, falsche und ineffiziente Methoden zu verwenden. Der Pilz wird lange behandelt und der Erfolg der Behandlung hängt weitgehend von der Regelmäßigkeit der Verwendung von Antimykotika und der Durchführung der vom Arzt verordneten Verfahren ab.",
    "lt171": "\"Viele Menschen vertrauen der traditionellen Medizin nicht und versuchen, den Pilz mit Hilfe von Volksheilmitteln und fragwürdigen Rezepten wie Essig oder Zwiebeln selbst zu behandeln. Wir empfehlen eindringlich, dies nicht zu tun, da es nicht nur nutzlos ist, sondern manchmal auch gefährlich sein kann!\"",
    "lt172": "Radikale Methoden, wie die chirurgische Entfernung der betroffenen Nägel, haben auch viele negative Seiten. Erstens entfernt es den Pilz nicht, sondern hemmt nur leicht seine Ausbreitung, und zweitens ist es die Zeit, solche \"barbarischen\" Methoden im 21. Jahrhundert aufzugeben, weil Rehabilitation nach der Operation ist ziemlich lang und die Möglichkeit der bakteriellen Infektion kann nicht ausgeschlossen werden.",
    "lt173": "Glücklicherweise steht die Medizin nicht still, und Wissenschaftler, angeführt von Dermatologen, entwickeln neue Medikamente, die in der Lage sind, eine Pilzinfektion schnell und effektiv zu bewältigen. \"Das ist eine tolle Sache\", sagt er.",
    "lt174": "Die Einzigartigkeit dieses Mittels besteht in der absolut innovativen Formel, die von einem internationalen Team von Dermatologen entwickelt wurde. Sie  ermöglicht die Entwicklung des Pilzes zu stoppen und  seine Sporen in den tiefsten Schichten der Haut und der Nagelplatte zu zerstören.",
    "lt175": "Sarkophag-Effekt-Wie<b><a href=\"{url}\"><span class="productName"></span></a></b>heilt den am meisten vernachlässigten Pilz",
    "lt176": "Die hohe Wirksamkeit des Mittels ist durch die aktiven Bestandteile verursacht. Die Zusammensetzung des Produkts ist absolut natürlich-das ist ein weiteres unbestreitbares Plus von<b><a href=\"{url}\"><span class="productName"></span></a></b>.",
    "lt177": "Wissenschaftler haben herausgefunden, dass die Sporen des Pilzes nur unter bestimmten Bedingungen zerstört werden können. Solche Bedingungen ist nicht einfach zu schaffen, aber es ist möglich. Die Forschungen Schweizer Wissenschaftler haben die Basis für die Entwicklung einer natürlichen Droge gesetzt, die in die tiefen Schichten der Dermis und der Nagelplatte dringt und einen dünnen Film von Wirkstoffen schafft, die die Sporen des Pilzes blockieren und zerstören. <span class="productName"></span>.",
    "lt178": "<b><em>“Wir empfehlen Ihnen, die Pilz mit modernen Mitteln loszuwerden, wie<b><a href=\"{url}\"><span class="productName"></span></a></b>. Diese Entwicklung ist sehr praktisch angesichts der hohen Inzidenz von Virusinfektionen\" </em></b> - sagt Dr.Louis - Philippe DOMBARD.",
    "lt179": "Die hohe Wirksamkeit des antimykotischen Medikaments der neuen Generation ist das Verdienst der stärksten natürlichen Wirkstoffe. Darunter gibt es:",
    "lt180": "<b>Osagi Moor-Saft + Kakao-Öl</b>- sie dringen in die Zellmembran des Pilzes, und zerschmetterte ihn auf zellulärer Ebene. Desinfizieren, lindern Hautentzündungen.",
    "lt181": "<b>Hanföl + Teebaumöl</b>- sie bilden einen Schutzfilm, verhindern die Ausbreitung der Infektion.",
    "lt182": "<b>Chaga Extrakt + Lopacho Extrakt</b>- sie stoppen das Wachstum der pathogenen Mikroflora, haben heilende und desinfizierende Eigenschaften.",
    "lt183": "<b>Cordyceps + Betulin</b>- sie stärken die Immunität auf zellulärer Ebene, fördern die schnelle Wiederherstellung des betroffenen Gewebes.",
    "lt184": "Also, bei regelmäßiger Anwendung bewältigt<b><a href=\"{url}\"><span class="productName"></span></a></b>den Pilz und kann die Gefahr von ernsten Komplikationen loswerden.",
    "lt185": "Angesichts der heutigen ernsten Situation mit der Ausbreitung der Virus-Infektion haben die Hersteller der Creme<b><a href=\"{url}\"><span class="productName"></span></a></b>das Angebot angekündigt, indem jeder bei der Bestellung auf der offiziellen Website einen Rabatt von 50% erhalten kann. Achtung! Die Warenmenge zum Angebot ist begrenzt!",
    "lt186": "Bestellen",
    "lt187": "Kommentare",
    "lt188": "<b>Anna:</b>Ich leide an Fußpilz, ich weiß nicht, wie ich es heilen kann! Ich habe viele Mittel ausprobiert, nichts hilft mir. Ich bestellte<b><a href=\"{url}\"><span class="productName"></span></a></b>auf der Website mit Rabatte, ich hoffe sehr, dass ich diesmal diese Pest bewältige!",
    "lt189": "<b>Peter:</b>ich habe viele Ärzte kontaktiert und mir eine Vielzahl von Salben und Tropfen verschrieben wurden. Aber nichts half. Die Nägel waren geschichtet, die Haut war rot und bekam Risse. Ich hatte Angst, dass die Infektion durchdringen wird und mir die Beine abgeschnitten werden würden! Und dann ein bekannter Arzt erzählte mir über diese<b><a href=\"{url}\">Creme</a></b>. Ich kaufte sie und bereute es nicht! In zwei Monaten hat sie meinen vernachlässigten Fußpilz geheilt und ich bin jetzt gesund! Ich habe keinen schrecklichen Geruch mehr von meinen Füßen, beschädigte Nägel schneide ich ab und bemerke wie gesunde wachsen.",
    "lt190": "<b>Arnd Schmidt:</b>Nur<b><a href=\"{url}\"><span class="productName"></span></a></b>konnte meinen Fußpilz heilen ! Es war einfach schrecklich! Meine Nägel wurden hässlich, sie brachen einfach zusammen, auf der Haut bildeten sich Wucherungen, es gab einen unangenehmen Geruch und einen unerträglichen Juckreiz. Zuerst hat meine Frau mir Bäder und Kompressen gemacht, aber es hat nicht geholfen. Und dann gingen wir zum Arzt. Der Arzt schlug die Entfernung der Nägel vor, aber ich lehnte ab. Ich glaubte, dass es einen humaneren Weg gibt, die Krankheit zu besiegen, und ich fand ihn. Über dieses Medikament habe ich zum ersten mal in einem Forum gelesen, in dem die Leute wie ich nach Hilfe suchten. Und jemand hat mir von der Creme<b><a href=\"{url}\"><span class="productName"></span></a></b>erzählt. Ich bestellte es über das Internet und begann gemäß den Anweisungen zu gebrauchen. Jeden Tag zog sich die Krankheit zurück und nach 6 Wochen sahen meine Füße viel besser aus! Ich setze die Behandlung fort. Vielen Dank an alle, die an der Erfindung dieses wunderbaren Werkes beteiligt sind!<br><br><img alt=\"\" src=\"src/feed1.jpg \"style = \"max-width:100%\">",
    "lt191": "<b>Oliver:</b> Ich kämpfe seit vielen Jahren gegen den Fußpilz und konnte ihn nicht vollständig loswerden. Manchmal die von Arzt gewählte Medikamente geben eine kleine Erleichterung, aber nach einer Weile geht alles zurück. Ich habe schon sehr viel Geld verschwendet. Aber ich vertraue ihrer Website und habe deshalb <b> <a href =\"{url}\"><span class="productName"></span></a></b>mit einen Rabatt bestellt, ich hoffe sehr, dass es mir hilft.",
    "lt192": "<b>Miranda:</b> Vielen Dank an diejenigen, die diese Creme erfunden haben! Es ist eine echte Rettung! Ich stieß auf Fußpilz vor etwa 5 Jahren. Ich glaube, ich habe mich mit ihm im Pool im Urlaub angesteckt. Und danach wurde mein Leben zur Hölle. Die Füße juckten, Risse erschienen, Fingernägel sahen schrecklich aus. Ich wurde lange mit verschiedenen Salben behandelt, schmierte meine Nägel mit einem speziellen Lack, trank einen Kurs von Tabletten, die mir den Magen verdorben haben, aber der Pilz ist nicht verschwunden. \"Das ist eine tolle Sache\", sagt er. Diese Creme wurde meine Rettung! Ich benutzte sie nur etwa zwei Monate und während dieser Zeit wurden meine Beine fast perfekt! Ein wunderbares Mitttel!",
    "lt193": "<b>Vincent:</b> Ja, diese Creme ist wirklich wirksam. Sie hat mir auch geholfen, den Fußpilz zu entfernen.",
    "lt194": "<b>Leon:</b> Vielen Dank, dass Sie uns von dieser Creme erzählt haben. Ich bin schon verzweifelt, ich weiß nicht, wie ich den Pilz loswerden soll. Und jetzt habe ich erfahren, dass er solche ernsten Konsequenzen verursachen kann! Ich habe jetzt Angst, dass er Komplikationen geben kann, weil ich das dritte Stadium habe! Aber ich habe bereits diese Creme mit einem Rabatt von 50% bestellt und jetzt denke ich, alles wird gut sein.",
    "lt195": "<b>Phillipe:</b>Dies ist ein sehr gutes Mittel gegen Fußpilze. Ich habe mit ihm Nagelpilz erfolgreich geheilt. Ich habe sogar speziell ein Foto gefunden, das ich für meinen Arzt gemacht habe. Schaut zu, wie meine Beine vor nach der Behandlung aussehen. Creme<b> < a href = \"{url}\"><span class="productName"></span></a></b>ist wirklich sehr effektiv, ich kann es empfehlen.<br><br><img alt=\"\" src=\"src/feed2.jpg\"style= \"max-width:100%\">",
    "lt196": "<b>Mia:</b> Ein wunderbares Mittel, ich auch kenne es gut. Es hat meinem Mann geholfen, den Fußpilz an den Beinen zu heilen. Sie sind sehr glücklich, dass das Angebot stattfindet, ich kaufte für den vollständigen Betrag, aber ich bereue es nicht, da die Creme perfekt mit ihrer Aufgabe fertig war!",
    "lt197": "<b>Richard:</b>Dank der Creme<b> < a href = \"{url}\"><span class="productName"></span></a></b>konnte ich den Fußpilz loswerden, er quälte mich mehr als 5 Jahre. Ich hatte mich mit ihm in der Duschkabine Fitnessstudios angesteckt und konnte seitdem nicht mehr behandelt werden. Ich ging zu den Ärzten, trank Tabletten, schmierte mit Salben, aber alles ist nutzlos. Und nur diese Creme hat mir wirklich geholfen und die Gesundheit zurückgebracht.",
    "lt198": "<b>Emma:</b>Vielen Dank an alle für euer Feedback, jetzt weiß ich, wie ich meinem Mann helfen kann, diese Infektion zu heilen! Danke an die Wissenschaftler, dass sie so ein gutes Mittel entwickelt haben, und vor allem natürliches! Dies ist sehr wichtig, besonders für ältere Menschen!",
    "lt199": "<b>Sophia:</b> Ich möchte auch eine Rezension über dieses Mittel schreiben. Das ist die einzige Droge, die mir geholfen hat. Schon am nächsten Tag wurde es mir besser, Juckreiz und Rötung verschwanden. Jetzt, nach zwei Wochen, bin ich mit dem Ergebnis sehr zufrieden.",
    "lt200": "Navigation Umschalten",
    "lt201": "Audiovisuelles Material",
    "lt202": "Fotos und Videos",
    "lt203": "Video abspielen",
    "lt204": "Grußbotschaft von Charles Michel",
    "lt205": "Video abspielen",
    "lt206": "Grußbotschaft von Angela Merkel",
    "lt207": "Video abspielen",
    "lt208": "Grußbotschaft von Kyriakos Mitsotakis",
    "lt209": "Video abspielen",
    "lt210": "Grußbotschaft von Ursula von der Leyen",
    "lt211": "Video abspielen",
    "lt212": "Ankünfte (Tag 1)",
    "lt213": "Video abspielen",
    "lt214": "Pressekonferenz (Tag 2)",
    "lt215": "Video abspielen",
    "lt216": "Präsident Charles Michel zum Brexit",
    "lt217": "Video abspielen",
    "lt218": "Rundtischkonferenz (Tag 2)",
    "lt218": "Video abspielen",
    "lt220": "Ankünfte (Tag 2)",
    "lt221": "Video abspielen",
    "lt222": "Pressekonferenz (Tag 1)",
    "lt223": "Video abspielen",
    "lt224": "Präsident Charles Michel über Belarus",
    "lt225": "Video abspielen",
    "lt226": "Rundtischkonferenz(Tag 1)",
    "lt227": "Video abspielen",
    "lt228": "Grußbotschaft von Charles Michel",
    "lt229": "Video abspielen",
    "lt230": "Grußbotschaft von Angela Merkel",
    "lt231": "Video abspielen",
    "lt232": "Grußbotschaft von Kyriakos Mitsotakis",
    "lt233": "Video abspielen",
    "lt234": "Grußbotschaft von Ursula von der Leyen",
    "lt235": "Video abspielen",
    "lt236": "Ankunft (Tag 1)",
    "lt237": "Video abspielen",
    "lt238": "Pressekonferenz (Tag 2)",
    "lt239": "Video abspielen",
    "lt240": "Präsident Charles Michel über Brexit",
    "lt241": "Video abspielen",
    "lt242": "Roundtable (Tag 2)",
    "lt243": "Video abspielen",
    "lt244": "Ankünfte (Tag 2)",
    "lt245": "Video abspielen",
    "lt246": "Pressekonferenz (Tag 1)",
    "lt247": "Video abspielen",
    "lt248": "Präsident Charles Michel über Belarus",
    "lt249": "Video abspielen",
    "lt250": "Roundtable (Tag 1)",
    "lt251": "Video abspielen",
    "lt252": "Grußbotschaft von Charles Michel",
    "lt253": "Video abspielen",
    "lt254": "Grußbotschaft von Angela Merkel",
    "lt255": "Video abspielen",
    "lt256": "Grußbotschaft von Kyriakos Mitsotakis",
    "lt257": "Video abspielen",
    "lt258": "Grußbotschaft von Ursula von der Leyen",
    "lt259": "Video abspielen",
    "lt260": "Ankünfte (Tag 1)",
    "lt261": "mehr anzeigen",
    "lt262": "Themen:",

    "lt263": "Auswärtige Angelegenheiten & amp; internationale Beziehungen",
    "lt264": "Wirtschaft & Finanzen",
    "lt265": "EU-Sanierungsplan",
    "lt266": "Forschung & amp; technologische Entwicklung",
    "lt267": "Binnenmarkt",
    "lt268": "Digitales Europa",
    "lt269": "Navigation Umschalten",
    "lt270": "Andere Sitzungen",
    "lt271": "Europäischer Rat: Weitere Tagungen",
    "lt272": "Zurück",
    "lt273": "-",
    "lt274": "21. Juli 2020",
    "lt275": "19 August 2020",
    "lt276": "-",
    "lt277": "2. Oktober 2020",
    "lt278": "-",
    "lt279": "16 Oktober 2020",
    "lt280": "-",
    "lt281": "11 Dezember 2020",
    "lt282": "Weiter",
    "lt283": "Teilen",
    "lt284": "Zuletzt überprüft am<time datetime=\"2020-10-06T09:20:05.000\">6. Oktober 2020 < /time>",
    "lt285": "Europäischer Rat<br>Rat der Europäischen Union",
    "lt286": "Schließen",
    "lt287": "Nein, danke",
    "lt288": "Umfragen teilzunehmen<span>(öffnet sich in einem neuen Fenster)</span>",
    "lt289": "Das&nbsp;<strong>Generalsekretariat des Rates</strong>&nbsp;ist ein Organ, das für die Unterstützung des europäischen Rates und des Rates der EU zuständig ist. Es hilft bei der Organisation und Sicherstellung der Kohärenz der Arbeit des Rates und der Durchführung seines 18-Monats-Programms.",
    "lt290": "Generalsekretariat des Rates",
    "lt291": "Öffentliche Aufträge",
    "lt292": "Jobs",
    "lt293": "Traineeships",
    "lt294": "Unternehmenspolitik",
    "lt295": "Datenschutz",
    "lt296": "Transparenz",
    "lt297": "Visuelle Identität",
    "lt298": "Wenden Sie sich",
    "lt299": "Wie Sie uns erreichen können",
    "lt300": "Ratsgebäude",
    "lt301": "Allgemeine Anfragen",
    "lt302": "Besuchen Sie den Rat",
    "lt303": "Europäische Union",
    "lt304": "Europäisches Parlament",
    "lt305": "Europäische Kommission",
    "lt306": "Sitemap",
    "lt307": "Über diese Webseite",
    "lt308": "Datenschutz- und Rechtshinweise",
    "lt309": "Sprachpolitik",
    "lt310": "Richtlinien zur Barrierefreiheit",
    "lt311": "Copyright",
    "lt312": "Cookies"
};
function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
}
;


