var new_lang = {
lt1: '- 100% droši un efektīvi',
lt2: 'Mums <span class="blue">JAU</span> ir piezvanījuši 4 672 cilvēki, lai pateikt <span class="blue">PALDIES!</span>',
lt3: 'Pieteikties bezmaksas konsultācijai',
lt4: '<span class="big">Bioretin:</span> galvenais palīgs <span class="blue">cīņā ar vecumu</span>',
lt5: '<span class="blue">Samazina</span> grumbas',
lt6: 'Elasticitātes <span class="blue">atjaunošana</span>',
lt7: '',
lt8: '<span class="blue">Savelc</span> sejas kontūrus',
lt9: '«Aizmigušu» šūnu <span class="violet">atjaunošana</span>',
lt10: 'Bojātu šūnu <span class="violet">atjaunošana</span> ',
lt11: 'Veselu šūnu <span class="violet">reģenerācija</span>',
lt12: 'Cena<br><span class="bold">1 ЕIRO*</span>',
lt13: 'Akcijas cena:<br><span class="big">1 ЕIRO*</span>',
lt14: 'Vecā cena:',
lt15: 'līdz akcijas beigām:',
lt16: 'dienas',
lt17: 'stundas',
lt18: 'minūtes',
lt19: 'sekundes',
lt20: 'UZMANĪBU! Akcijas preču daudzums ir ierobežots.',
lt21: 'Palika: ',
lt22: ' gb.',
lt23: '* - pasūtot pilnu kursu',
lt24: 'Cik veca jūsu āda?',
lt25: 'Pieņemts uzskatīt, ka vecuma pazīme viena – grumbas. Bet, vai jūs zinājāt, ka grumbas ir tikai viena no pazīmēm? <span class="red">KATRA JAUNA PROBLĒMA PALIELINA JŪSU VECUMU!</span>',
lt26: 'Smieklu rieviņas',
lt27: '+6 gadi',
lt28: 'Noslīdējušais sejas ovāls',
lt29: '+5 gadi',
lt30: ' «Vārnu kājiņas» - grumbas acu kaktiņos',
lt31: '+4 gadi',
lt32: 'Vertikālas grumbas starp uzacīm',
lt33: '+7 gadi',
lt34: 'Maisiņi zem acīm',
lt35: '<span class="violet">Ādai ir savs vecums.</span> Tas atšķirās no mūsējā. Tomēr āda ir ļoti neaizsargāta, maksimāli ietekmīga pret laika iedarbību, atšķirībā no citiem orgāniem.Pēc 35 gadiem āda noveco ļoti strauji! Par vainu tam: gravitācija, iedzimtība, slikta ekoloģija, ultravioletie stari, radiācija, stresi un nepareizs uzturs. <span class="red">Parēķiniet, cik veca tagad jūsu āda. </span> <span class="underline">Atzīmējiet punktus, kuriem jūs piekrītat. </span>',
lt36: 'Ievadiet jūsu pašreizējo vecumu:',
lt37: 'Man ir smieklu rieviņas. :',
lt38: 'Āda kļuva neelastīga:',
lt39: 'Redzamās mīmikas grumbas:',
lt40: 'Ir vairākas dziļas grumbiņas:',
lt41: 'Norādiet jūsu vecumu',
lt42: 'Ieteicams: 17 gb. botulotoksīna, 2 mezoterapijas kursi, 28 mezodiegu<br><span class="white">VAI 1 krēma Bioretin kurss </span>',
lt43: 'Ieteicams: 37 gb. botulotoksīna, 3 mezoterapijas kursi, 38 mezodiegu, 1 filleru kurss <span class="white">VAI 2 krēma Bioretin kursi </span>',
lt44: 'Ieteicams: 47 gb. botulotoksīna, 4 mezoterapijas kursi, 48 mezodiegu, filleru kurss <span class="white">VAI 3 krēma Bioretin kursi </span>',
lt45: 'Ieteicams: 57 gb. botulotoksīna, 5 mezoterapijas kursi, ķirurģiska sejas stiepšana <span class="white">VAI 3 krēma Bioretin kursi </span>',
lt46: 'kādēļ jāizskatās vecākam par savu īsto vecumu, ja ',
lt47: 'jūs varat izskaīties jaunāks?',
lt48: 'DAUDZ JAUNĀKS, BEZ SĀPĒM UN RISKA!',
lt49: 'sievietes nozēlo, ka piekrita injekcijām un ķirurģisku iejaukšanos',
lt50: 'parbaudīta drošība un efektivitāte',
lt51: 'JAUNĀKĀS Bioretin FORMULAS',
lt52: 'pret novecošanu',
lt53: 'ATGRIEZT ATPAKAĻ JŪSU JAUNĪBU',
lt54: 'Bioretin - INNOVĀCIJA un REZULTĀTS',
lt55: 'Bioretin — ir innovācijas krēms, kas satur arganas un avokado ārstnieciskās eļļas, vitamīnus un hialuronskābi, baro un atjauno dzīļo ādas slāni, stimulē epitēlija audu augšanu.',
lt56: 'Citādiem vardiem sakot, krems aktīvi stimulē kolagēna veidošanos un starpšūnu "matricas" reģenerācīju. Dēļ tā ir spējīgi <span class="violet">ievērojami samazināties mimīkas grumbas uz pieres, mutes un acu apvidū (“vārnu kājiņas”). </span><br><span class="orange">Bioretin - ir iespaidīgs “koktēlis" smieklu rieviņu un vertikālu grumbu starp uzacīm korekcijai.</span>',
lt57: 'Tajā ietilpst komponenti, kas radīti lai palielinātu apjomu iedarbības vietā, kas<span class="violet">piepildīs grumbas un krokas no iekšienes,</span> "izspiedot" ādu. Ka arī “atslabināt" muskuļu mikro-saīsinājumus, lai traucētu muskuļiem sarauties un izveidot grumbas starp uzacīm.',
lt58: 'Bioretin - iekļauj sevī vienu no stiprākiem antioksidantiem, kas neitralizē brīvus radikāļus - galveno novecošanas pazīmi.',
lt59: 'Mazina kolagēna sadalījumu, vienkaši sakot, cīnās pret novecošanu aizsargājot šūnas no sabrukuma. Stimulē asinsriti limfā, lai mazinātu pietūkumu, “maisiņus” un melnus plankumus zem acīm. Stiprina ādas struktūru, <span class="violet">izlīdzina sejas ādu, sejas ovālu,</span> ar kolagēna un elastāna dabīgas izstrādes palīdzību.',
lt60: 'Hiuluronskābe',
lt61: 'Argana eļļa',
lt62: 'Avokado eļļa',
lt63: 'Glicerīns',
lt64: '',
lt65: 'Sensacionāls efekts Bioretin.',
lt66: '89% sieviešu sāka izskatīties uz to vecumu, uz kuru jūtās!',
lt67: 'Pēc 40 gadiem šūnu reģenerācija sāk samazināties.',
lt68: 'Parādās vairāk grumbju, āda kļūst neelastīgāka un sejas konturs paliek mazāk skaidrs. Revocionala kopšana pret novecošanos Bioretin radīts tieši nobriedušas ādas kopšanai.',
lt69: 'Trījskāršo Bioretin iedarbību apliecina vērienīgi pētniecīskie izmeklējumi:',
lt70: '1183 sieviešu',
lt71: 'Pamanija <span class="violet">ietekmīgu grumbju samazināšanu</span> un drūma skatiena līniju samazināšanu (uz 77%), acu kaktiņos (uz 56%) un uz pieres (uz 76%)',
lt72: '927 sieviešu',
lt73: 'Aizpildijās smieklu rieviņu apjoms,',
lt74: 'apjoms vaigu kaulu apvidū atjaunots (+41%).<br>Sejas ovāls ievērojami skaidrāks, āda izstiepta un apjomīga.',
lt75: '1321 sieviete',
lt76: 'Redzamās izmaiņas<br><span class="violet">Ādas tonuss palielinās (+65%),</span> tā kļūst blīvāka (+54%) un mitrināta uz 48 stundām.',
lt77: '<span class="red">VĒRIENĪGA APTAUJA PARĀDĪJA -</span> VISI DOD PRIEKŠROKU JAUNĪBAI',
lt78: 'NEPIEVĒRŠ UZMANĪBU',
lt79: '74% vīriešu godīgi atbildējuši, ka sievietes ar grumbām un novītuma pazīmēm uz sejas nevar būt seksuāli pievilcīgi.',
lt80: 'KARJERA',
lt81: '67% darbadevēju nepieņems darbā un nepiedavās amata paaugstināšanu sievietei, kas izskatās vecāka par 45 gadiem',
lt82: 'VĪRA KRĀPŠANĀS',
lt83: '96% vīru pametuši savas sievas jaunāku mīļotu dēļ un dēļ tā, ka sieva pārstāja rūpēties par sevi.',
lt84: 'Pētījumi pierāda, ka 87% vīriešu saka, ka <span class="red">sievietes vecumam nav nozīmes, </span> ir svarīgi, lai sieviete izskatītos<span class="red">kopta un pievilcīga.</span> Tas padara viņu <span class="red">seksīgu un izraisa cieņu</span> vīrieša acīs.',
lt85: 'Kontrolējiet savu laiku',
lt86: 'KĻŪSTIET <span class="red">10 GADUS JAUNĀKA </span> 2,5 KURSU LAIKĀ',
lt87: 'Smieklu rieviņas<span class="orange">PAZŪD</span> 2 kursu laikā',
lt88: '«Vārnu kājiņas» <span class="orange">PAZŪD</span> 3 kursu laikā',
lt89: 'Vertikālas grumbas starp uzacīm<span class="orange">PAZŪD</span> 2 kursu laikā',
lt90: 'Noslīdējušais sejas ovāls<span class="orange">PAZŪD</span> 1 kursa laikā',
lt91: 'Maisiņi zem acīm<span class="orange">PAZŪD</span> 1 kursa laikā',
lt92: 'NEATKARĪGS KOSMETOLOGU VĒRTĒJUMS',
lt93: 'Inga Bičele <br>Kosmetologs-dermatologs<br>Prakses ilgums - 18 gadi',
lt94: 'Ja es būtu Jūsu kosmetologa vietā, tad protams mēģinātu Jums piedavāt visvairāk, no tā, ko protu un tā, kas ir iespējams ar skaistuma tehnoloģijām: <span class="violet">botokss, plazmoliftings, filleri u.c.</span> Bet, kā cilvēks, kā sieviete, es saprotu ka ar <span class="violet">Bioretin palīdzību visas šīs procedūras var atlikt vēl uz 6 gadiem.</span>',
lt95: 'Lai domā, ka tā ir plastika...',
lt96: 'Inete Alksne <br>Plastiskā ķirurga vecākais asistents <br>Prakses ilgums - 7 gadi',
lt97: 'Es ieteiktu nesteigties ar injekcijām, operācijām un citiem ķirurģiskas iejaukšanas traumatiskiem veidiem. Atstājiet šo domu uz gadiem 20. Vienkārši <span class="violet">pamēģiniet Bioretin un pēc 1 mēneša jūs sapratīsiet, ka estetiskās medicīnas revolūcija jau notika.</span> Medicīnas kosmētika - tas ir skaistuma un jaunības nākotne, kuru es varam izmantot jau tagad un izbaudīt rezultātus.',
lt98: 'Ļaujiet Jūsu ādai kļūt jaunākai!',
lt99: 'Visos labākajos Rīgas skaistumkopšanas salonos <span class="blue">jau sen tiek izantots Bioretin.</span> Viens seanss, kas sastāv no skrubja, sejas masāžas un krēma uzlikšanas maksā ap 75 eiro',
lt100:'ATKLĀTAS ATSAUKSMES',
lt101:'Reālu sieviešu ieteicams.',
lt102:'2016. gada laikā ir pārdoti vairāk, kā 3 000 000.',
lt103:'Vai Jūs jau pasūtījāt savu Bioretin?',
lt104:'Laiga, Liepāja',
lt105:'Anna, Rīga',
lt106:'Mairita, Cēsis',
lt107:'12 000 000 $ tika ieguldīti Bioretin izveidei',
lt108:'gadi pētījumiem',
lt109:'gadi formulas izveidei',
lt110:'speciālisti',
lt111:'procentu efektivitāte',
lt112:'laimīgu sieviešu skaits',
lt113:'kvalititātes sertifikāti ЕС, РТС, ISO',
lt114:'dabīgu komponentu procenti',
lt115:'UZMANĪBU!',
lt116:'Sakarā ar popularitāti Latvijā un ES ir bijuši vairāki gadījumi ar viltus produkcijas pārdošanu par zemām cenām!<br>Esiet uzmanīgi! Uz oriģināla iepakojuma obligāti būs norādīts svītrkods ar oriģinālu numuru! Ja svītrkoda nav, rakstiet sūdzību mums uz e-pastu, kas norādīta lappuses lejasdaļā. Mēs atlīdzīnāsim jums zaudējumus un piesaistīsim krāpniekus pie atbildības saskaņā ar likumu.',
lt117:'Kā mēs strādājam?',
lt118:'1. SOLIS',
lt119:'Veiciet pasūtījumu par <span class="red">akcijas cenu</span>',
lt120:'2. SOLIS',
lt121:'Sagaigiet konsultanta zvanu detaļu saskaņošanai',
lt122:'3. SOLIS',
lt123:'Jūs neko nemaksājiet, līdz pasūtījuma saņemšanas brīdim',
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};