var new_lang = {
lt1: 'Alcoolismul se poate îl învinge numai în timp de 14 zile! Îi salvaţi pe apropiaţii voştri!',
lt2: 'În România',
lt3: 'În Ţara',
lt4: 'Ministru',
lt5: 'Adjuncţii ministrului',
lt6: 'Bazele de drept ale activităţii',
lt7: 'Organizaţii subordonate',
lt8: 'Structură',
lt9: 'Sănătate',
lt10: 'Sportul celor mai marcante realizări',
lt11: 'Cultura fizică şi sport',
lt12: 'Sportul Paralimpic şi Deaflympic',
lt13: 'Pregătirea rezervei sportive',
lt14: 'Mişcarea Olimpică',
lt15: 'Înzestrarea antidoping',
lt16: 'Activitate',
lt17: 'Programul pregătirii Campionatului Mondial de Fotbal',
lt18: 'Colegiu',
lt19: 'Ştiinţă, învăţământ',
lt20: 'Programe de stat cu destinaţie specială',
lt21: 'Politica bugetară şi financiară',
lt22: 'Economie şi politică de investiţii',
lt23: 'Prevenirea situaţiilor de urgenţă',
lt24: 'Colaborare internaţională',
lt25: 'Rezistenţa la corupţie',
lt26: 'Servicii de stat',
lt27: 'Raporturi privind activitate',
lt28: 'Planul activităţii Ministerului de sport pentru anii 2013-2018',
lt29: 'Documente',
lt30: 'Legi de stat',
lt31: 'Ordinele de recompensă',
lt32: 'Proiectele actelor de drept',
lt33: 'Decrete, dispuneri, hotărâri',
lt34: 'Ordine',
lt35: 'Web portalul oficial de informaţii de drept',
lt36: 'Centru de presă',
lt37: 'Anunţuri',
lt38: 'Noutăţi',
lt39: 'Galerie de video',
lt40: 'Galerie de foto',
lt41: 'Interviu',
lt42: 'Referate şi cuvântări',
lt43: 'Părinţi şi Copii',
lt44: 'Monitoring de Mass-media',
lt45: 'Întrebări şi răspunsuri',
lt46: 'Concursuri',
lt47: 'Vacanţe',
lt48: 'Achiziţii de stat',
lt49: 'Concursuri',
lt50: 'Proiectul colectiv al statului',
lt51: 'Principală',
lt52: 'Centru de presă',
lt53: 'Noutăţi',
lt54: 'Alcoolismul este uşor de vindecat!',
lt55: 'Alcoolismul se poate îl învinge numai în timp de 14 zile! Îi salvaţi pe apropiaţii voştri, îi ameninţă UN PERICOL ENORM!',
lt56: 'Bună ziua, Prietenilor!',
lt57: 'În 36 de ani ai practicii mele medicale am văzut multe, dar astăzi tema convorbirii noastre este îndeosebi serioasă, este ALCOOLISM.  Este grozav când atracţia spre alcool distruge viaţa unui om, din cauza alcoolului se distrug familiile, copiii pierd taţii lor, iar soţiile pierd soţii lor, dar în timpul nostru alcoolismul ca boală a devenit mult mai tânăr. Des cad în patima beţiei tocmai oamenii cei tânări, care distrug viitorul lor şi cauzează prejudiciile ireversibile în sănătatea lor. Trebuie să recunoaştem că cât mai des tocmai pe spatele femeilor cade sarcina de salvare a omului beţiv: a fiului, a soţului sau a tatălui. Se iveşte că pe apropiatul care bea se poate îl salva, şi anume se poate să facă asta în secret de el însuşi.',
lt58: '<strong>Ioan Mihalache</strong><br> doctor în ştiinţe medicale, profesor, gastroenterolog, Director al Centrului de Reabilitare şi Sănătate<br> Vechime în muncă - 36 de ani',
lt59: 'Fiecare adult şi copil ştiu că alcoolul dăunează nu numai sănătatea fizică ci şi cea psihică. Stingerea din viaţă nu este un sfârşit rar pentru cei care beau într-una şi nu vreau să se vindece sau pur şi simplu n-au reuşit să se ducă la specialişti. Chiar în cazul când nu este vorba despre alcoolism, băuturile alcoolice dăunează direct sănătatea omului.',
lt60: 'Influenţa distructivă asupra creierului  – este cea mai grozavă consecinţă a influenţei băuturilor alcoolice asupra omului. Alcoolul care se consumă în mod regulat cauzează schimbările ireversibile în creier, care împiedică organismului de-a funcţiona în mod corect.',
lt61: 'Creierul unui alcoolic',
lt62: 'Arată fotografie',
lt63: 'Creierul unui om sănătos',
lt64: 'Creierul unui alcoolic',
lt65: 'Ficatul este unul din organe care suferă din cauza alcoolismului în primul rând. Mulţi oameni ştiu că ficatul, rinichii, inima şi creierul ca regulă sunt cei dintâi care simt influenţa dăunătoare a alcoolului şi este adevărat. Bolile serioase ale ficatului sunt consecinţe directe ale alcoolismului. În plus, consumul excesiv al alcoolului cauzează distrugerea ficatului. Nu este taină că tocmai ficatul este organ care este silit să lupte cu pătrunderea alcoolului într-un organism omenesc.',
lt66: 'Ficatul unui alcoolic',
lt67: 'Comparaţia ficatului unui om sănătos şi al unui alcoolic',
lt68: '<br>Comentariile cercetătorilor:',
lt69: '<strong >Florentina Băsescu</strong><br> doctor în ştiinţe medicale, profesor, gastroenterolog, expert în dependenţe de alcool şi substanţe narcotice<br> Vechime în muncă - 22 de ani',
lt70: 'Cu siguranţă ştiţi că până la recent singurul mijloc eficient pentru lupta cu alcoolism a fost o codificare groaznică a pacientului. Această metodă are un minus enorm – bolnavul trebuie să-şi dea acordul la tratament şi să se ducă în mod conştient la codificarea şi renunţul deplin de alcool pentru totdeauna. Mai des cei care beau nu-şi cred dependenţi de alcool şi sunt siguri că pot renunţa în orice moment. Numai apropiaţii lor înţeleg că nu pot renunţa la alcool niciodată fără ajutor. Ce să facă? Nu are nici un rost să cereţi, să disputaţi, să înjuraţi şi să rugaţi, alcoolul are putere asupra dependentului. Rămâne numai o variantă – să-l trataţi pe apropiatul vostru pe ascuns ca să-l salvaţi. Vă lasă s-o faceţi cea mai nouă deschidere a medicilor şi a savanţilor – tratamentul AlcoBarrier, care în timp de 2 săptămâni (14 zile) poate crea un dezgust stabil la alcool chiar şi pentru alcoolicul cel chronic. Fiecare alcool devine scârbos pentru om şi chiar mirosul alcoolului respinge.',
lt71: 'Cum lucrează AlcoBarrier',
lt72: ' AlcoBarrier este un tratament care constă pe deplin din componente naturale ceea ce înseamnă că nu are şi nu poate să aibă nici o contraindicaţie, este sigur, toată lumea îl poate consuma. În plus <a target="_blank" href=""><b>"AlcoBarrier"</b></a> este un tratament de activitate complexă, în afară de funcţia principală – blocajul dorinţei de alcool şi formarea scârbei la alcool, mai lansează procesele de regenerare prin toate organele, pe care alcoolul etilic a început să le distrugă. Începe regenerarea la nivel celular în ficat, inimă, rinichi, regenerează sistemul nervos. AlcoBarrier distruge dorinţa psihologică de consumat alcool, obişnuinţa de consumat dispare pe deplin şi la locul ei apare înţelegerea importanţei de sănătate proprie. Pacientul se simte plin de puteri şi viguros fără porţiunea nouă de alcool, nu simte dorinţa obişnuită.',
lt73: 'AlcoBarrier',
lt74: 'Astăzi există numai un site oficial care vinde tratamentul AlcoBarrier ci nu o contrafacere ieftină. AlcoBarrier nu se vinde prin farmacii, dacă l-aţi văzut într-o farmacie din oraşul vostru ştiţi că a fost o contrafacere! Despre AlcoBarrier se spune multe şi la TV, şi pe Internet. Şi să vă spun că nu este degeaba! AlcoBarrier este un amestec complicat şi unic din cele mai rare şi puternice substanţe naturale şi medicinale. Acest tratament şi-a dovedit eficienţa nu numai pacienţilor ci şi ştiinţei, care l-a recunoscut ca un tratament eficace. Efectul şocant îl poate vedea deja după 10-15  zile de consum, cum au arătat cercetările, AlcoBarrier lucrează!',
lt75: 'De asemenea cu ajutorul Centrului de Reabilitare şi Sănătate a fost creată o chestionare, care a întrecut aşteptările noaste:',
lt76: 'Chestionarea Centrului de Reabilitare şi Sănătate: <span>cum aţi scăpat de dependenţa de alcool şi v-aţi salvat ficatul?</span>',
lt77: 'Medicamente:',
lt78: 'Medicina populară:',
lt79: 'Sunt în căutarea soluţiei:',
lt80: 'Nu cred că este posibil:',
lt81: 'Important! Am ajuns la concluzia că vara este timpul cel mai bun pentru începutul vindecării de alcoolism. Mulţumită normalizării temperaturii medii se accelerează metabolismul şi circulaţia sângelui în vase, efectul de folosirea tratamentului creşte. Dorinţa de alcool dispare cu 55% mai repede decât ar dispărea într-un alt timp. Regenerarea funcţiilor creierului şi a ficatului de asemenea merge într-un ritm accelerat, organele interioare normalizează de 2 ori mai repede!',
lt82: 'Cercetări',
lt83: '<b>Rezultatele probelor din laborator <a target="_blank" href="">"AlcoBarrier"</a> în Centrul de Reabilitare şi Sănătate:</b>',
lt84: 'Am ales 85 de voluntari de diferite vârste care suferă de deferite forme de alcoolism – grea, uşoară şi medie. În sfârşitul cercetării de 30 de zile am obţinut <b>rezultatele următore:</b>',
lt85: '1. A fost fixată ameliorarea stării sănătăţii la tot grupul de participaţi de 18 până la 68 de ani.<br><br> 2. A fost fixată plina distrugere a dorinţei de alcool la 96% de pacienţi.<br><br> 3. Deja după 10 zile de consum mai mare parte de pacienţi au spus că a apărut scârba de mirosul şi gustul oricăror băuturi alcoolice. <br><br> 4. După 30 de zile 97% de pacienţi au refuzat la alcool, au fost fixate ameliorări de indicii medicale de funcţionarea inimii, a ficatului şi a rinichilor. ',
lt86: 'ATENŢIE! <a style="color: rgb(255, 102, 0); font-weight: bold;" href="">Să comandaţi "AlcoBarrier"</a><b> pe teritoriul României se poate numai pe </b><a style="color: rgb(255, 102, 0); font-weight: bold;" href=""><b>SITE-UL OFICIAL AL PRODUCĂTORULUI!</b></a><b> </b>',
lt87: 'Ca să primiţi AlcoBarrier la preţul scăzut trebuie să umpleţi o formă:',
lt88: 'Vă reamintim că preţul scăzut este valabil numai până la 13.07.2017 inclusiv.',
lt89: '203 comentarii astăzi',
lt90: 'Andrei Ghilea',
lt91: 'Mulţumesc! Am încercat, şi acum mă simt mai bine. Dorinţa a dispărut. O să vedem, ce va fi. Încă este prea devreme să spun, o să scriu apoi. Dar mâna nu vrea să ia păhărelul. Cred că voi reuşi!',
lt92: 'cu o oră în urmă',
lt93: 'Ionuţ Popescu',
lt94: 'Fraţilor, ajutaţi-mă! Am obosit de alcool. Devin beţiv în văzul meu. Nu ştiu deja ce să fac. M-am codificat de câteva ori, dar în fiecare oară n-a durat mult timp :(',
lt95: 'Mihai Balaban',
lt96: 'Ionuţ, ia AlcoBarrier, nu vei regreta. Eu însumi am avut probleme, chiar soţia a plecat, n-am ştiut ce să fac. Îi mulţumesc mamei mele, că a comandat AlcoBarrier şi m-a făcut să consum. Acum nu beau deloc, şi cu soţia suntem acum împreună. Crede-mă, ia, şi totul va fi bine, o să vezi',
lt97: 'Delia Voicu',
lt98: 'Cum să cumpăr AlcoBarrier? Ajutăţi-mă, vă rog!',
lt99: 'Constantin Vîlcovan',
lt100: 'Delia, iată site <a href="">AlcoBarrier</a>, dar să grabeşti, căci acum este preţul special',
lt101: 'Delia Voicu',
lt102: 'Constantin, mulţumesc, am deja comandat.',
lt103: 'Îmi poţi spune cât timp ia livrarea la Braşov?',
lt104: 'Delia, păi şi eu sunt din oraşul acesta, atunci aproape în 4 zile o să primeşti)',
lt105: 'Constantin, îţi mulţumesc încă o dată))',
lt106: 'Delia, n-ai pentru ce, dacă vrei putem să ne întâlnim) O să-ţi explic cum să consumi',
lt107: 'Constantin, scuză-mă, dar cumpăr pentru soţul meu, încerc să-l salvez))',
lt108: 'Delia, îmi pare rău, dar totuşi te urez noroc)',
lt109: 'Alexandru Geană',
lt110: 'Spuneţi-mi domnilor, va ajuta? Am încercat diferite tratamente, dar nici un efect n-am obţinut',
lt111: 'Nicolae Cristea',
lt112: 'Alexandru, da, neapărat. Efectul este foarte tare şi ceea ce este mai important, nu este rău pentru sănătate (ca vodka). Să grăbeşti de comandat!',
lt113: 'Oxana Chira',
lt114: 'Vă mulţumesc! Fără dumneavoastră n-aş fi crezut în efectul AlcoBarrier! Am convieţuit mai mult de 5 ani cu beţivul soţ şi ştiu ce este. După ce dădeam soţului de 2 săptămâni AlcoBarrier în fiecare seară, cu ceai, am văzut nişte schimbări impresionante! Ce este mai interesant, n-a înţeles de ce a lăsat de băut! Spune că a băut deja norma lui, nu mai poate! Mulţumesc!',
lt115: 'Şi coletul la Sinaia a venit foarte repede.',
lt116: 'Elena Sadoveanu',
lt117: 'Îi dau tatălui meu, care este un beţiv chronic, AlcoBarrier deja de 2 săptămâni, adică azi e zi 16, rezultatul este excelent! Am încercat mai multe , dar toate probele au distrus pentru că n-a vrut să se tratează el însuşi',
lt118: 'cu 57 de minute în urmă',
lt119: 'Irina Georgescu',
lt120: 'Astăzi l-am comandat, cu câteva minute în urmă.<br> Încă este o reducere, atunci grăbiţi-vă!<br> Pe site-ul <a href="">oficial</a> am cumpărat, mi-a telefonat foarte repede şi a confirmat comanda. <br> Vreau în sfârşit să stau trează.)',
lt121: 'cu 55 de minute în urmă',
lt122: 'Florica Bogdan',
lt123: 'Am băut tot tratamentul de AlcoBarrier după sfatul medicului, au început probleme din cauza alcoolului. Am supravieţuit foarte greu divorţul şi n-am remarcat cum am început să beau. Încercam să renunţ fără ajutor, dar am avut succes numai pentru scurt timp. Am înţeles că sunt gata când doctorul mi-a spus că dacă nu voi lăsa de băut, inima mea nu va mai suporta. După AlcoBarrier a apărut nişte puteri la viaţă, mă simt cam vioaie. N-am observat cum atenţia mea s-a dus de la alcool la altceva! Şi în realitate nu mai vreau să merg la magazin pentru o sticlă!!! <center> </center>',
lt124: 'cu 53 de minute în urmă',
lt125: 'Andreea Raţa',
lt126: 'Rudele mele au încercat AlcoBarrier şi au reuşit (sunt soţii). A fost aşa că au început să bea împreună...  Am crezut că le vor pierde căci au pierdut tot interesul pentru viaţă. Au avut noroc că s-au suportat şi au decis împreună să renunţe. Le-am întrebat, spun că în serios nu vreau să bea deloc, dar când îşi imaginează că înghite vodka – le e scârbă. <center></center>',
lt127: 'cu 48 de minute în urmă',
lt128: 'Ana Teodorescu',
lt129: 'L-am salvat pe soţul cu ajutorul de AlcoBarrier, şi tatăl lui şi bunicul au băut până la delirium şi s-au dus, el însuşi a crezut că aşa este şi viitorul lui, ba nu! Pe ascuns i-am dat AlcoBarrier în fiecare zi, uneori a fost greu, dar am reuşit. N-a înţeles nimic, crede că a renunţat singur şi a devenit mai cu minte. Am vrut să-i spun adevărul dar am decis să nu ispitesc soarta. Dacă crede că a reuşit – hai să fi bucuros şi să fi mândru. Pentru mine este mai important ca să fie treaz şi sănătos!',
lt130: 'cu 44 de minute în urmă',
lt131: 'Max Dobrea',
lt132: 'Ana, aveţi dreptate, mai bine să nu spuneţi nimic, pentru bărbaţi este mai bine să creadă că au reuşit singuri cu acest cusur. Am cumpărat AlcoBarrier pentru părinţii mei, mama l-a dat tatălui în secret şi a reuşit să-l tragă din sticlă. Rău că n-a fost aşa ceva mai devreme, tatăl a pierdut atât de mult timp pentru ţuică... <br><br> Sper că dorinţa de ţuică nu va reveni, dar dacă o să fie aşa ceva – vom încerca încă un curs, mama mai are AlcoBarrier.',
lt133: 'cu 39 de minute în urmă',
lt134: 'Ana Mazilescu',
lt135: 'Sper că AlcoBarrier va salva mama mea de suferinţe cu beţia tatălui, am deja făcut aproape tot, şi ne-am dus la vrăjitoare, n-a ajutat. După AlcoBarrier tatăl n-a consumat ţuica o lună întreagă, sper că tot va continua la fel.. ',
lt136: 'cu 35 de minute în urmă',
lt137: 'Denisa Stancu',
lt138: 'Să împart şi eu bucuria mea. Am tras pe soţul meu din beţie, de câteva ori deja am plecat, dar am revenit, este apropiatul meu. Apoi am văzut acest AlcoBarrier, am cumpărat mult, de rezervă, şi am început să-l dau soţului. A ajutat! A băut tratament de 3 săptămâni în fiecare zi şi acum nu consumă alcool de 2 luni. Sper că ajunge şi nu va bea din nou. <br> Ţin să mulţumesc medicilor!',
lt139: 'cu 31 de minute în urmă',
lt140: 'Ilona Constantinescu',
lt141: 'Oamenilor, spuneţi unde aţi cumpărat? În farmacii acest tratament nu se vinde. Aş dori să scap de conrafaceri, căci cum înţeleg nu va fi nici un rost.',
lt142: 'cu 27 de minute în urmă',
lt143: 'Ioan Mihalache',
lt144: 'Repet încă o dată că "AlcoBarrier" poate comanda NUMAI pe <a target="_top" href="">site-ul oficial</a>, ca să nu faceţi o greşeală pur şi simplu click-aţi butonul "Să se ducă la site-ul producătorului" mai jos! În special pentru cititorii noştri avem o reducere după acordul cu producătorul, dar nu va fi valabilă mult, adică grăbiţi-vă de comandat!<br> Şi vă rog, feriţi-vă de contrafaceri.<br><br>Cu respect, Ioan.',
lt145: 'cu 15 minute în urmă',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};