var new_lang = {
lt1: 'Alkoholismu var uzvarēt! Glābiet savus tuviniekus!',
lt2: 'Ziņas',
lt3: 'Komunikācija',
lt4: 'Parakstīties',
lt5: 'Žurnāls MED-info',
lt6: 'Konsultācijas',
lt7: 'Zāļu un iestāžu rokasgrāmata',
lt8: 'Rubrikas',
lt9: 'Rokasgrāmata',
lt10: 'Konsultācijas',
lt11: 'Komunikācija',
lt12: 'Izklaide',
lt13: 'žurnāls<br> MED-info ',
lt14: '<span>zāļu un iestāžu</span><br> rokasgrāmata',
lt15: '<span>konsultācijas</span><br>jautājiet ārstam',
lt16: 'viedtālruņu<br><span>pielikumi</span>',
lt17: 'Rubrikas',
lt18: 'Tēmas',
lt19: 'analītika',
lt20: 'interaktīvs',
lt21: 'intervija ar zvaigzni',
lt22: 'infografika',
lt23: 'lasītāja vēsture',
lt24: 'apaļais galds',
lt25: 'aktuāls temats',
lt26: 'reportāža',
lt27: 'raksti/panti',
lt28: 'Aktuālas ziņas',
lt29: 'vakar plks. 13:26',
lt30: 'Uzrādīts labāko stomatoloğijas klīniku top-100',
lt31: 'vakar plks. 21:56',
lt32: 'Decembrī notiks prēmija Russian Pharma Awards',
lt33: 'vakar plkst. 14:24',
lt34: 'Aptauja: kas kaitē veselībai &nbsp;darbā',
lt35: 'Zinātnieki uzaudzēja neironus, kas ražo laimes hormonus',
lt36: 'Pats interesākais',
lt37: 'intervija ar ekspertu',
lt38: 'Daiga Ozola: «Lāzera operācija stomatoloğijā – nākotnes ārstniecības metode»',
lt39: 'raksti/panti',
lt40: 'Kā&nbsp;nepieļaut kļūdu в&nbsp;zobu birstes izvēlē',
lt41: 'Alkoholisms',
lt42: 'intervija ar ekspertu',
lt43: 'Alkoholismu var uzvarēt! Glābiet savus tuviniekus!<br>Galvenais ārsts no Ventspils, medicīnas zinātņu doktors, profesors Kaspars Vaivads',
lt44: 'Redakcija: Saskaņā ar pēdējo izmeklējumu rezultātiem, alkohoļiķu skaits Latvijā sasniedzis 10-12% no visiem iedzīvotājiem. Uzskaitē tomēr nav pat puse no viņiem. Alkohola dēļ mirst 36. uz katriem 100 tūkstošiem Latvijas iedzīvotāju ik gadu! Tik daudz latviešu nemirst no epidēmijām, katastrofām. Alkohola ļaunprātīga lietošana ir tieši saistīta ar 55.1% pašnāvībām, 62.2% slepkavībām, 60% nāvēm no pankreatīta, 67.7% no cirozes un 23.3% no sirds un asinsvadu slimībām.Katru gadu tiek reğistrēti vairāk kā 10 tūkstoši saindēšanās ar zemas kvalitātes alkoholu gadījumi, tajā skaitā arī letāli. Par to, kā atbrīvoties no šīs kaites un kļūt par veselu cilvēku, mēs vaicājām medicīnas zinātņu doktoram, professoram Kasparam Vaivadam',
lt45: 'Briesmīgi, kad tieksme pēc alkohola lauž cilvēka dzīvi, alkohola dēļ izirst ğimenes, bērni zaudē tēvus, sievas – vīrus. Tomēr, mūsu laikā alkoholisms, kā slimība, ir kļuvis daudz jaunāks. Bieži ar to slimo jaunekļi, kas lauž savu nākotni un kaitē savai veselībai. Ir jāatzīst, ka visbiežāk sievietēm nākas glābt dzerošo vīrieti: dēlu, vīru vai tēvu. Izrādās, ka dzērāju var glābt, turklāt viņam nemanāmi. Šadien mēs runāsim par jaunu naturālu līdzekli <a target="_top" href="http://c.Alcobarrier.com/">Alcobarrier</a>,kas ir neticami efektīvs.',
lt46: 'Droši vien jums ir zināms, ka līdz neilgam laikam par vienīgo iedarbīgo līdzekli cīņā ar alkohola atkarību bija cietsirdīga pacienta kodēšana. Šai metodei ir milzīgs mīnus – slimajam ir jādod piekrišana ārstniecībai un apzinīgi jāiet uz kodēšanu un pilnīgu atteikšanos no alkohola. Uz mūžu. Bet dzērāji biežāk sevi par atkarīgajiem neuzskata un ir pārliecināti, ka jebkurā brīdī var atmest. Tikai tuvinieki saprot, ka bez citu palīdzības viņi to neizdarīs. Ko darīt? Pierunāt, strīdēties un lūgt cilvēku būs veltīgi – alkoholam ir vara pār viņu. Atliek tikai viens variants – ārstēt tuvinieku slēpti, lai viņu glābtu. To atļauj paveikt jaunākais ārstu un zinātnieku izstrādājums – līdzeklis Alcobarrier, kas par divām nedēļām (14 dienas) var izveidot izturīgu riebumu pret alkoholu, pat hroniskam alkoholiķim. Jebkāds alkohols nu ir cilvēkam pretīgs, pat tā smarža viņam ir riebīga.',
lt47: 'Kā darbojas Alcobarrier',
lt48: 'Alcobarrier – preparāts, kas pilnīgi sastāv no dabas komponentiem, tāpēc tam nav un nevar būt kontrindikācijas, ta sir drošs, to var dzert absolūti visi.Turklāt<a target="_top" href="http://c.Alcobarrier.com/"><b>"Alcobarrier"</b></a> tas ir kopleksas darbības līdzeklis, izņemot pamatfunkciju – tieksmes pēc alkohola bloķēšanu un riebuma pret alkoholu izsaukšanu, tas arī iedarbina atjaunošanas procesus visos orgānos, kurus izira spirts. Notiek aknu, sirds, nieru šūnu atjaunošana, notiek nervu sistēmas darbības normalizācija. Alcobarrier noņem psiholoğisko tieksmi pēc alkohola, ieradums lietot alkoholu pilnīgi pazūd, tās vietā rodas savas veselības svarīguma sapratne. Pacients ir modrs un spēku pilns bez jaunas alkohola porcijas, nejūt ierasto «lomku».',
lt49: 'Un tomēr – kā tas darbojas, jautāsiet jūs? Paskaidrošu. Alcobarrier, ar konkrētu saistvielu un antioksidantu palīdzību iedarbojas uz noteiktiem šūnas receptoriem, kuri atbild par atjaunošanos un darba spēju. Notiek savā ziņā informācijas pārrakstīšana no slimām šūnām par veselām. Rezultātā organisms uzsāk atveseļošanās procesu, atgriežas pie, kā mēs to saucam, izejas «veselības punkta».',
lt50: 'Dotajā brīdī ir tikai viens oficiālais interneta saits, kurš pārdod preparātu Alcobarrier, nevis lētu viltojumu. Alcobarrier nevar atrast aptiekās, ja jūsu pilsētā tas ir manīts aptiekā, tad ziniet – tas ir viltojums! Par to daudz runā gan mūsu kanālā, gan citos. Un tas nav velti, es jums teikšu. Alcobarrier ir sarežğīts un unikāls maisījums no retiem un stipriem dabas ārtnieciskiem līdzekļiem. Šis līdzeklis ir pierādījis savu efiktivitāti ne tikai pacientiem, bet arī zinātnei, kura atzina to par darbīgu preparātu. Pārsteidzošs efekts ir redzams jau pēc 10-15 lietošanas dienām. Kā demonstrēja izmeklējumi – Alcobarrier darbojas!',
lt51: 'Izmeklējumi',
lt52: 'Laboratorijas testu rezultāti <a target="_top" href="http://c.Alcobarrier.com/">"Alcobarrier"</a> Narkoloğijas izmeklējumu institūtā:',
lt53: 'Tika izvēlēti 85 dažāda vecuma brīvprātīgie, kuriem bija smaga, viegla, vai vidēji-smaga alkohola atkarības forma. 30 dienu ilga izmeklējuma rezultātā, tika saņemti <b> sekojoši rezultāti:</b> ',
lt54: '1. Tika fiksēta pašsajūtas uzlabošanās visai izmeklēto grupai no 18. līdz 68. gadiem. ',
lt55: '2. Tika fiksēta pilna tieksmes pēc alkohola naņemšana 96% pacientu. ',
lt56: '3. Jau pēc 10 lietošanas dienām lielākā pacientu daļa paziņoja par radušos riebumu pret alkohola smaržu un garšu',
lt57: '4. Pēc 30 dienām 97% pacientu atteicās no alkohola, fiksēta sirds, aknu un nieru medicīnas rādītāju uzlabošanās.',
lt58: '<strong>Uzmanību! </strong>Kļuvuši biežāki preparāta Alcobarrier viltojuva pārdošanas gadījumi. Tāpēc speciāli mūsu lasītājiem mēs izvietojam līdzekļa Alcobarrier pasūtījuma pogu no vienīgā oficiālā ražotāja! Veiciet pasūtījumu šeit un jūs garantēti saņemsiet kvalitatīvu preci pa labāko cenu!<br><br> Mūsu <strong>saitam </strong> paredzēta <strong> papildus atlaide</strong>. Tās saņemšanai spiediet pogu «Noformēt pasūtījumu» zemāk.Jūs pāriesiet uz oficiālo saitu, kur var veikt pasūtījumu. Iepikojumu daudzums ar atlaidi ir limitēts!',
lt59: 'Komentāri',
lt60: 'Lāsma Dubova (Rēzekne)',
lt61: 'Neticas man tam visam! Neticu, ka palīdzēs... Mēs jau ļoti daudz ko izmēğinājām. Es jau zaudēju cerību…',
lt62: 'Jana (Rīga, 23.07.2016)',
lt63: 'Lāsmiņ, velti neticāt, labāk pārbaudiet – sliktāk nebūs! Mēs arī ārstējāmies ar šo līdzekli. Palīdzēja. Viņam vairs nav to ilgo dzeršanas periodu – var izdzert nedaudz svētkos. Viņš var sevi kontrolēt un man vars nav bail par viņu. Veiksmi visem! Līdzeklis darbojas!',
lt64: 'Madara Vaidote, 46 gadi(Valmiera, 23.07.2016)',
lt65: 'Ko tikai es neizmēğināju, lai atradinātu dēlu no alus, pēc tam sapratu, ka tas jau ir alus alkoholisms. Sākumā viņš katru dienu no darba atgriežoties izdzēra alus pudeli un otru – vakarā. Kad viņa «norma» izauga līdz 1,5 litriem alus ik dienu, es sapratu, ka ir kaut kas jādara! Līdz Alcobarrier nonācu vēlāk, sākumā bija citas metodes, kas nelīdzēja. Alcobarrier devu ar tēju, viņš neko nejuta. Jau pēc trim dienām atgriezās mājās bez alus! Es biju šokēta un neko neteicu, nejautāju. Sekoju, kas būs tālāk un viņš pavisam aizmirsa par alu! Ceru, ka pavisam!',
lt66: 'Kaspars Vaivads, profesors (Ventspils, 24.07.2016)',
lt67: '>Nevarēju paiet garām šim komentāram...Madara, nav par ko! Nevarat iedomāties, cik esmu laimīgs par jums un Janu, esmu pārliecināts, ka jūs izmainījāt tuvinieku dzīves uz labāko pusi!<br><br>Ar cieņu, Kaspars.',
lt68: 'Anna Stara (Valka, 24.07.2016)',
lt69: 'Lāsma, ja krist izmisumā un zaudēt cerību, tad protams nekas nepalīdzēs! Bet šis līdzeklis tiešām darbojas un tā cena ir ļoti pieņemama. Iesaku tomēr pasūtīt un personīgi pārliecināties tā darbībā!',
lt70: 'Ilva (Madona, 24.07.2016)',
lt71: 'Mani radinieki lietoja Alcobarrier un arī veiksmīgi! (virs ar sievu). Dzīvē tā notika, ka viņi sāka dzert kopā...Es jau domāju, ka zaudēšu viņus, jo viņi zaudēja jebkādu interesi dzīvei. Paveicās, ka viņi viens otru atbalstīja un abi nopietni nolēma atmest šo ieradumu. Es jautāju – saka, ka reāli negribas un kad iedomājas šņabja glāzīti, tad uzreiz riebums uznāk..',
lt72: 'Marta S. (Cēsis, 25.07.2016))',
lt73: 'Es ar AlkoBarjeru izglābu vīru! Viņam tēvs un abi vectēvi piedzērās līdz baltajam drudzim un nomira. Viņš pats domāja, ka būs tads pats liktenis, bet tas nenotika! Nemanāmi pievienoju viņam Alcobarrier katru dienu. Dažreiz to izdarīt bija grūti, bet man sanāca. Viņš tā arī neko nesaprata, domā ka pats ir ticis tam visam pāri. Sākumā gribēju izstāstīt, bet nolēmu labāk neprovocēt – lai  ir lepns par sevi! Man svarīgākais ir tas, ka viņš nedzer un ir vesels!',
lt74: 'Kārlis, Jelgava, 25.07.2016)',
lt75: 'Marta, pareizi, labāk neko nestāstiet! Vīrietim ir labāk domāt, ka viņš pats atteicās no kaitīgā ieraduma. Es saviem vecākiem pirku Alcobarrier, mamma tēvam nemanot to deva un «izvilka» viņu no pudeles. Žēl, ka agrāk šāda līdzekļa nebija, tēvs tik daudz gadu zaudēja dzeršanas dēļ!<br><br> Ceru, ka tieksme neatgriezīsies, bet ja tā, tad dzers vēl vienu kursu – mātei vēl palika Alcobarrier krājumi.',
lt76: 'Ilze Druma (Ventspils, 26.07.2016)',
lt77: 'Ceru, ka Alcobarrier atbrīvos mammu no tēva dzeršanas, mēs ar viņu jau ko tikai nedarijām, pat pie burves bijām – nepalīdzēja. Pēc Alcobarrier jau mēnesi ne drupatas neizdzēra, ceru, ka tas turpināsies...',
lt78: 'Maija (Rīga, 27.07.2016)',
lt79: 'Padalīšos arī ar savu prieku – atbrīvoju vīru no hroniska alkoholisma! Vairākas reizes aizgāju no viņa, bet katru reizi – atgriezos, jo viņš ir man tuvs cilvēks. Tad uzzināju par to Alcobarrier, nopirku daudz, ar nodrošinājumu, un sāku dot vīram. Tas palīdzēja! Viņš lietoja to 3 nedēļas katru dienu un jau gadu nedzer! <br> paldies preparāta ražotājiem, lūk kā izskatās Alcobarrier iepakojums.',
lt80: 'Sergejs, 37 gadi (sigulda, 27.07.2016)',
lt81: 'Sakiet, kur jūs pirkāt? Aptiekās šī līdzekļa nav. Bail nopirkt viltojumu, jo tad nekādas jēgas nebūs.',
lt82: 'Kaspars Vaivads, profesors (Ventspils, 27.07.2016)',
lt83: 'Atkārtoju vēlreiz, ka "Alcobarrier" var pasūtīt tikai <a target="_top" href="http://c.Alcobarrier.com/">oficiālajā saitā</a>,ļai visu izdarītu pareizi, vienkārši spiediet pogu «Noformēt pasūtījumu» nedaudz zemāk!Speciāli mūsu lasītājiem ir lieliska atlaide no ražotāja, kura darbosies kādu laiku. Labāk pasteidzaties ar pasūtījumu!<br> un esiet, lūdzu, uzmanīgi no viltojumiem.<br><br>ar cieņu, Kaspars.',
lt84: 'Pievienot komentāru:',
lt85: 'Jūsu vārds:',
lt86: 'Pilsēta:',
lt87: 'Jūsu komentārs:',
lt88: 'Ziņas',
lt89: 'Bizness',
lt90: 'Valsts un medicīna',
lt91: 'Zvaigznes',
lt92: 'Zinātne',
lt93: 'Sabiedrība',
lt94: 'Notikumi',
lt95: 'Statistika',
lt96: 'Farmācija',
lt97: 'Ziņas MED-info',
lt98: 'Notikumu kalendārs',
lt99: 'Rubrikas',
lt100: 'Reportāža',
lt101: 'Analītika',
lt102: 'Apaļais galds',
lt103: 'Video',
lt104: 'Infografika',
lt105: 'Interaktīvs',
lt106: 'Lasītāja vēsture',
lt107: 'Intervija ar zvaigzni',
lt108: 'Intervija ar ekspertu',
lt109: 'raksti/panti',
lt110: 'Rokasgrāmata',
lt111: 'Zāles',
lt112: 'Iestādes',
lt113: 'Konsultācijas',
lt114: 'Rubrikas',
lt115: 'Mūsu ārsti',
lt116: 'Komunikācija',
lt117: 'Blogi',
lt118: 'Grupas',
lt119: 'Vakances',
lt120: 'Izklaide',
lt121: 'Konkursi',
lt122: 'Medicīnas horoskops',
lt123: 'Testi',
lt124: 'Pielikumi',
lt125: 'MED-info',
lt126: 'Medicīnas ziņas',
lt127: 'Medicīnas horoskops',
lt128: 'Žurnāls MED-info',
lt129: 'Par projektu',
lt130: 'Partnieri',
lt131: 'Kontakti',
lt132: 'Testi',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};