var new_lang = {
lt1: '¡Es posible eliminar el alcoholismo! ¡Salvan sus amigos y parientes!',
lt2: 'Noticias',
lt3: 'Comunicación',
lt4: 'Suscribirse',
lt5: 'Revista MED-info',
lt6: 'Consulta',
lt7: 'Guía de medicinas y hospitales',
lt8: 'Secciones',
lt9: 'Guía',
lt10: 'Consulta',
lt11: 'Comunicación',
lt12: 'Diversiones',
lt13: 'Revista<br>MED-info',
lt14: '<span>guía</span><br>de medicinas y hospitales',
lt15: '<span>consultas</span><br>pregunta al médico',
lt16: 'aplicaciones<br><span>móviles</span>',
lt17: 'Secciones',
lt18: 'Temas',
lt19: 'análisis',
lt20: 'interactividad',
lt21: 'entrevista con la estrella',
lt22: 'infografía',
lt23: 'cuento del lector',
lt24: 'mesa redonda',
lt25: 'temas controvertidos',
lt26: 'reportaje',
lt27: 'artículos',
lt28: 'Noticias de vanguardia',
lt29: 'ayer a las 13:26',
lt30: 'Presentaron Top-100 mejores estomatologías',
lt31: 'ayer a las 21:56',
lt32: 'En el diciembre tendrá lugar Spanish Pharma Awards',
lt33: 'ayer a las 14:24',
lt34: 'Encuesta: ¿Qué perjudica la salud en el &nbsp; trabajo? ',
lt35: ' Los científicos han crecido las neuronas que producen la hormona de la felicidad',
lt36: 'Lo más interesante',
lt37: 'entrevista con el experto',
lt38: 'María Gómez: «La cirugía con láser en odontología es un método de tratamiento del futuro»',
lt39: 'artículos',
lt40: 'Como &nbsp; no equivocarse &nbsp; eligiendo un cepillo de dientes',
lt41: 'Alcoholismo',
lt42: 'Entrevista con el experto',
lt43: '¡Es posible eliminar el alcoholismo! ¡Salvan sus amigos y parientes!<br>El médico de Madrid, doctor en ciencias, profesor Carlos García López',
lt44: 'Redacción: De acuerdo con los últimos datos de la estadística oficial, el número de alcohólicos en España superó 5.000.000 personas, o el 3,4% de la población total. Sólo 1,7% de los enfermos están registrados. El alcohol fue la causa del muerto de un tercio de todos hombres y 15% de mujeres. Cada año por el alcohol mueren aproximadamente 500.000 personas. ¡Datos impactantes! Hasta por la causa de las guerras, las epidemias y los desastres naturales juntos no mueren tantas personas. En España el 62,1% de los suicidios, el 72,2% de los homicidios, 60% de los muertos por pancreatitis, el 67,6% de la cirrosis y el 23,3% de las enfermedades cardiovasculares son relacionados con el abuso de alcohol. Cado año registran más de 40 mil casos de intoxicación por alcohol de mala calidad, incluyendo las muertes. Para aprender cómo deshacerse de esta enfermedad y convertirse en una persona sana, le preguntamos al doctor en ciencias médicas, profesor Carlos García López',
lt45: 'Es terrible cuando la adicción al alcohol destruye la vida, cuando por el alcohol se destruyen las familias, cuando los niños pierden a sus padres y los esposas a esposos. Pero hoy en día el alcoholismo como una enfermedad es más joven. A menudo, los jóvenes son los que beben mucho y destruyen su futuro y hacen daño irreparable a su salud. Debemos admitir que en la mayoría de los casos son las mujeres que salvan a sus esposos, hijos o padres de la adicción. Resulta que es posible salvar a un miembro de la familia sin que el miembro lo sepa. Hoy hablaremos de un remedio natural <a target="_top" href="">XX</a>, que es muy eficaz.',
lt46: 'Ud. sabrá que hasta hace poco el único medio eficaz contra la adicción del alcohol fue un método muy grave de codificación del alcoholismo. Este método tiene una desventaja enorme – el paciente debe dar su consentimiento para el tratamiento y aceptar la codificación y la abstinencia completa de alcohol. Para siempre. Pero la mayoría de la gente que bebe no se consideran adictos al alcohol y creen que pueden dejar de beber en cualquier momento. Sólo sus seres queridos entienden que nunca serán capaz de dejar de beber el alcohol sin la ayuda. ¿Qué hacer? Persuadir, argumentar, jurar y pedir a la persona es completamente inútil, el alcohol ya tiene poder sobre ellos. Sólo hay una opción - tratar a un ser querido en secreto, para salvarlo. Esto permite el desarrollo más reciente de médicos y científicos - XX, que durante 2 semanas (14 días) es capaz de generar un fuerte sentimiento de aversión al alcohol hasta a los alcohólicos crónicos. Cualquier alcohol se convierte asqueroso, incluso el olor de alcohol.',
lt47: '¿Cómo funciona XX? ',
lt48: 'XX es un medicamento que consiste enteramente de ingredientes naturales, lo que significa que no existe ni puede existir contraindicados, es seguro y todos pueden tomarlo. Además, se trata de un producto de acción compleja, además de la función básica - el bloqueo de la adicción al alcohol y la formación de la aversión al alcohol. También inicia los procesos regenerativos en todos los órganos, que empezaron ser destruido por el alcohol. Se regenera las células en el hígado, el corazón, los riñones, se normaliza el sistema nervioso. XX elimina la adicción psicológica de beber y el hábito de beber alcohol desaparece completamente y lo reemplaza la comprensión de la importancia de su propia salud. El paciente se siente renovado y lleno de energía sin una nueva porción de alcohol.',
lt49: '-Y ¿Cómo funciona? Explico. XX, utilizando las sustancias y antioxidantes específicos, influye a ciertos receptores de las células que son responsables de la regeneración y de la funcionalidad. Tiene lugar la "reescritura" de la información de las células enfermas. Como resultado, el cuerpo comienza el proceso de curación, y vuelve, como se dice, a "punto de la salud".',
lt50: 'Por el momento, sólo hay una página web oficial de venta de XX. XX no se vende en las farmacias, y si lo viste en las farmacias de la ciudad, ya sabes, que es una falsificación! Se hablan mucho de XX en nuestro canal y en otros. ¡Y no es por nada, te digo! XX es una mezcla compleja y única de las sustancias curativas naturales más raros y de gran alcance. Esta herramienta ha demostrado su eficacia no sólo para los pacientes, sino también para la ciencia, que lo encontró un remedio eficaz. Los estudios han demostrado que se observa un efecto impresionante después de 10-15 días de tratamiento. ¡XX funciona!',
lt51: 'Estudios',
lt52: 'Los resultados de las pruebas de laboratorio <a target="_top" href="">"de XX"</a> en la Universidad Nacional de Estudios:',
lt53: ' Se seleccionaron 85 voluntarios de todas las edades que sufrían de la adicción al alcohol de varias formas. El estudio de 30 días mostro los <b> siguientes resultados:</b> ',
lt54: '1. Fue fijado el mejoramiento de la salud del todo el grupo de sujetos de 18 a 68 años.',
lt55: '2. Fue registrado la eliminación completa de la adicción al alcohol de 96% de los pacientes.',
lt56: '3. Después de 10 días de haber recibido, la mayor parte de los pacientes declararon del disgusto surgido del olfato o del gusto de cualquier bebida alcohólica.',
lt57: '4. Después de 30 días, el 97% de los pacientes dejaron de beber alcohol y fueron registrados los mejoramientos de las condiciones médicas del corazón, del hígado y de los riñones.',
lt58: '<strong>¡Atención!</strong> ¡Se han hecho más frecuentes los casos de venta de los medicamentos falsificados XX! Por lo tanto, especialmente para nuestros lectores, colocamos un botón de orden del XX del único fabricante oficial. Haciendo el orden por aquí, le garantizamos que obtendrá el producto de calidad al mejor precio.<br><br> Se proporciona un <strong> descuento adicional</strong> en<strong> nuestro sitio web</strong>. Para obtenerlo haga click en el botón "Comprar". Esto le llevará a la página web oficial donde se puede hacer un pedido. ¡La cantidad de los paquetes de descuento es limitada!',
lt59: 'Comentarios',
lt60: 'Elena (Madrid)',
lt61: '¡No creo! No creo que pueda ayudar… Hemos tratado mucho. He perdido la esperanza. ',
lt62: 'Josefina (Madrid, 23.07.2016)',
lt63: 'Elena, mejor tratáis. No será nada peor. También lo tomaba mi esposo. ¡Ayudó mucho! Mi esposo bebe muy raramente, solo durante las fiestas. Se controla. ¡Suerte a todos!',
lt64: 'Margarita, 46 años (Valladolid, 23.07.2016)',
lt65: 'Es increíble lo mucho que intentaba hacer que mi hijo dejara de tomar cerveza, pero luego me di cuenta de que se trataba del alcoholismo. Primero compraba una botella de cerveza todos los días de ida del trabajo, después tomaba uno en el camino y compraba otro para la noche... Cuando la dosis diaria llegó a 1.5 litros de cerveza, me di cuenta de que tenía que hacer algo. No encontré el XX de una vez, pero había otros métodos que no ayudaron. Le daba el XX también junto con el té, pero no sentía nada. ¡Al tercer día ya llegó a casa sin cerveza! Estaba en shock pero no empecé a decir ni preguntar nada. ¡Esperé a ver lo que sucedería después, y se olvidó de cerveza! ¡Espero que para siempre!',
lt66: 'Carlos, profesor (Zaragoza, 24.07.2016)',
lt67: 'Josefina y Margarita ¡Estoy muy feliz que este medicamente haya cambiado su vida! <br><br>.',
lt68: 'María (Sevilla, 24.07.2016)',
lt69: 'Elena, no es bien perder la esperanza. ¡Nada ayudará! El medicamento realmente ayuda y es bastante barato. Os recomiendo.',
lt70: 'Isabel (Cádiz, 24.07.2016)',
lt71: 'Mis parientes (esposo y esposa) también lo tomaban. ¡Tuvieron éxito! Pensaba que les perdería porque ellos habían perdido el interés a vivir. Pero ahora no quieren ni pueden beber.',
lt72: 'Carmen (Bilbao, 25.07.2016))',
lt73: ' Salvé mi esposo con XX. Su padre y abuelo murieron de beber. Pensaba que también va a morir, pero no. Le daba cada día XX, era difícil, pero logramos. Ahora piensa que hizo todo si mismo, y yo no le digo que le ayudó. Lo más importante es que él es sano.',
lt74: 'Víctor (Valencia, 25.07.2016)',
lt75: 'Carmen, no le diga nada a su esposo. Para los hombres es mejor pensar que ellos hicieron todo si mismos. También lo daba a mi padre. Ahora es sano. Es una lástima que solo hoy tengamos aquel medicamento. <br><br> Espero que no empiece a beber otra vez.',
lt76: 'Laura (Barcelona, 26.07.2016)',
lt77: 'Espero que XX ayude a mi madre soportar a mi padre. Hiciéramos todo para ayudarle, para que dejara de beber. Nada. Pero con XX no bebe. Esperamos que continúe…',
lt78: 'Verónica (Madrid, 27.07.2016)',
lt79: '¡Yo soy muy feliz! Mi esposo bebía mucho, pero con la ayuda de XX no bebe nada desde hace un año. ¡Necesitaba 3 semanas para dejar de beber! <br>Me gustaría decir gracias al equipo de XX. A propósito, aquí tenéis el embalaje.',
lt80: 'Felipe, 37 años (Tarragona, 27.07.2016)',
lt81: '¿Dónde lo compran? En las farmacias el remedio no se vende. No me gustaría atrapar en una falsificación ya que por lo que veo no me servirá para nada',
lt82: 'Carlos, profesor (Zaragoza, 27.07.2016)',
lt83: 'Una vez más repito que XX se puede pedir SÓLO en <a target="_top" href=""> el sitio web oficial. </a> ¡Para no equivocarse simplemente haga click en el botón “Comprar”! ¡Especialmente para nuestros lectores hay un gran descuento de acuerdo con el fabricante pero no va a funcionar durante mucho tiempo, así que dese prisa con su orden! br> Y tenga cuidado con las falsificaciones.<br><br>Atentamente, Carlos.',
lt84: 'Añadir un comentario:',
lt85: 'Su nombre:',
lt86: 'Ciudad:',
lt87: 'Su comentario:',
lt88: 'Noticias',
lt89: 'Negocios',
lt90: 'Estado y medicina',
lt91: 'Estrellas',
lt92: 'Ciencia',
lt93: 'Sociedad',
lt94: 'Eventos',
lt95: 'Estadística',
lt96: 'Farmacia',
lt97: 'Noticias de MED-info',
lt98: 'Calendario de eventos',
lt99: 'Secciones',
lt100: 'Reportaje',
lt101: 'Análisis',
lt102: 'Mesa redonda',
lt103: 'Video',
lt104: 'Infografía',
lt105: 'Interactividad',
lt106: 'Cuento de lector',
lt107: 'Entrevista con estrella',
lt108: 'Entrevista con experto',
lt109: 'Artículos',
lt110: 'Guías',
lt111: 'Medicinas',
lt112: 'Hospitales',
lt113: 'Consultas',
lt114: 'Secciones',
lt115: 'Nuestros médicos',
lt116: 'Comunicación',
lt117: 'Blogs',
lt118: 'Grupos',
lt119: 'Vacantes',
lt120: 'Diversiones',
lt121: 'Concursos',
lt122: 'Horóscopo medico',
lt123: 'Testes',
lt124: 'Aplicaciones',
lt125: 'MED-info',
lt126: 'Noticias de medicina',
lt127: 'Horóscopo medico',
lt128: 'Revista MED-info',
lt129: 'Sobre el proyecto',
lt130: 'Asociados',
lt131: 'Contactos',
lt132: 'Testes',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};