var new_lang = {
	lt1:  '- 100% sicuro ed efficace',
    lt2:  'ci hanno <span class="blue">GIA’</span> chiamato 4 672 persone, per dirci<span class="blue">GRAZIE!</span>',
    lt3:  'Prenota una consulenza gratuita',
    lt4:  '<span class="big">Biorecin:</span>il miglior alleato<span class="blue">nella battaglia contro l’età</span>',
    lt5:  '<span class="blue">Diminuisce</span> le rughe',
    lt6:  '<span class="blue">Ripristina</span> l’elasticità',
    lt7:  '',
    lt8:  '<span class="blue">Tende</span>i contorni',
    lt9:  '<span class="violet">Rivitalizza</span> le cellule “inattive”',
    lt10: '<span class="violet">Ripristina</span> le cellule rovinate',
    lt11: '<span class="violet">Rigenerazione</span> di cellule sane',
    lt12: 'prezzo<br><span class="bold">1 EURO*</span>',
    lt13: 'Prezzo in offerta:<br><span class="big">1 EURO*</span>',
    lt14: 'Vecchio prezzo:',
    lt15: 'fino alla fine dell’offerta rimane:',
    lt16: 'giorni',
    lt17: 'ore',
    lt18: 'minuti',
    lt19: 'secondi',
    lt20: 'Attenzione! Il totale di confezioni in offerta è limitato.',
    lt21: 'rimangono: ',
    lt22: ' confezioni',
    lt23: '* - in caso di ordinazione di un ciclo completo',
    lt24: 'Quanti anni ha la vostra  pelle?',
    lt25: 'Fa piacere pensare che l’unico segno dell’età che avanza sono le rughe. Ma sapete benissimo che èsono solo metà dei problemi reali. <span class="red">OGNI NUOVO PROBLEMA CHE COMPARE VIENE COMPORTATO DALL’ ETA’ CHE AVANZA E AUMENTA L’ETA’ DELLA PELLE!</span>',
    lt26: 'rughe nella zona naso labiale',
    lt27: '+6 anni',
    lt28: 'Pelle che pende ai bori del viso',
    lt29: '+5 anni',
    lt30: 'Zampe di gallina',
    lt31: '+4 anni',
    lt32: 'Rughe in mezzo alle sopracciglia',
    lt33: '+7 anni',
    lt34: 'Borse sotto gli occhi',
    lt35: '<span class="violet">La pelle ha un’età propria.</span> Si differenzia dalla nostra. La pelle infatti è molto vulnerabile, si rovina molto con il passare degli anni, a differenza degli organi. Dopo i 35 anni la pelle invecchia molto rapidamente! Le cause sono molte: forza di gravità, fattore ereditario, aria cattiva, raggi ultravioletti, radiazioni, stress e cattiva alimentazioni. <span class="red">Contate, quanti anni ha la vostra pelle ora.</span> <span class="underline">Contate i punti con i quali siete d’accordo.</span>',
    lt36: 'Inserite la vostra età reale:',
    lt37: 'Ho le rughe nell’area naso labiale',
    lt38: 'La pelle ha perso elasticità:',
    lt39: 'Le rughe da espressione sono più accentuate:',
    lt40: 'Ho qualche ruga molto profonda:',
    lt41: 'Inserite la vostra età',
    lt42: 'Si raccomanda: 17 interventi con tossina butolinica, 2 cicli di mesoterapia, 28 fili biologici<br><span class="white">OPPURE un ciclo di cura con la crema Biorecin</span>',
    lt43: 'Si raccomanda: 37 interventi con tossina butolinica, 3 cicli di mesoterapia, 38 fili biologici, 1 ciclo con dei filler <span class="white">OPPURE 2 cicli di crema Biorecin</span>',
    lt44: 'Si raccomanda: 47 interventi con tossina butolinica, 4 cicli di mesoterapia, 48 fili biologici, 1 ciclo con dei filler <span class="white">OPPURE 3 cicli con la crema  Biorecin</span>',
    lt45: 'Si raccomanda: 57 interventi con tossina butolinica, 5 cicli di mesoterapia, lifting facciale <span class="white">OPPURE 4 cicli con la crema Biorecin</span>',
    lt46: 'perché apparire più vecchi della propria età reale, se ',
    lt47: 'potete sembrare più giovani?',
    lt48: 'MOLTO PIU’ GIOVANI SENZA DOLORI E RISCHI!',
    lt49: 'le donne si lamentano di essersi lasciate fare iniezioni e interventi chirurgici',
    lt50: 'efficacia e sicurezza comprovati',
    lt51: 'DALLA NUOVA FORMULA DI Biorecin',
    lt52: 'contro l’invecchiamento',
    lt53: 'RIPRENDERSI I MIGLIORI ANNI DELLA VITA E DELLA GIOVINEZZA',
    lt54: 'Biorecin — INNOVAZIONI E RISULTATO',
    lt55: 'Biorecin -è una crema rivoluzionaria, che contiene "segnali peptidi", che sono capaci di  " rialzare dal profondo le cellule che modellano la pelle.',
    lt56: 'ovvero la crema stimola attivamente la produzione di collagene e la rigenerazione di “matrici” all’interno delle cellule. Grazie a ciò saranno capaci di <span class="violet">stendere in maniera pen visibile le rughe da espressione, all’altezza di bocca e occhi (zampe di galline). </span><br><span class="orange">Biorecin — è un incredibile "cocktail" per la correzione delle rughe naso labiali e tra le sopracciglia.</span>',
    lt57: 'Contiene componenti, che sono perfetti per "aumentare la massa" nel punto adatto, per far si ché <span class="violet">vengano riempite le rughe dall’interno,</span> "spingendo" la pelle indietro. E allo stesso modo "rilassa" le micro contratture dei muscoli, per far si che il lavoro dei muscoli non rovini la pelle, soprattutto tra le sopracciglia.',
    lt58: 'Biorecin – contiene uno dei più forti antiossidanti, che neutralizza i radicali liberi — la causa principale dell’ invecchiamento.',
    lt59: 'Inibisce il calo di collagene, in parole povere, combatte la vecchiaia difendendo le cellule da ogni attacco. Stimola la circolazione sanguigna per sgonfiare il viso, per eliminare le “borse” sotto gli occhi e diminuire i cerchi neri sotto gli occhi. Fortifica la struttura della pelle <span class="violet">tende la pelle infossata, la pelle penzolante</span> grazie allo stimolo della produzione di collagene e elastina.',
    lt60: 'acido ialuronico A BASSO CONTENUTO MOLECOLARE',
    lt61: 'Cellule dal gambo della cicoria',
    lt62: 'Estratto di germoglio di rosmarino',
    lt63: 'Olio di palma rossa',
    lt64: 'Fuoco Dorato',
    lt65: 'Effetto Sensazionale Biorecin.',
    lt66: 'L’89% delle donne anno iniziato ad apparire più giovani di diversi anni, appaiono come si sentono!',
    lt67: 'Dopo i 40 anni la rigenerazione delle cellule inizia a rallentare.',
    lt68: 'Compaiono sempre più rughe, la pelle perde elasticità, e i contorni del viso diventano meno delineati. Una cura rivoluzionaria contro l’invecchiamento Biorecin,  creata apposta per trattare la pelle che invecchia.',
    lt69: 'Il triplo effetto di Biorecin è confermato dai più avanzati test clinici:',
    lt70: '1183 donne',
    lt71: 'Hanno notato <span class="violet">evidenti miglioramenti</span>delle rughe e dei problemi della pelle da espressione (il 77%), agli angoli degli occhi (il 56%) e sulla fronte (il 76%)',
    lt72: '927 donne',
    lt73: 'Scomparse le rughe nell’area naso labiale,',
    lt74: 'ripristino della massa corretta nell’area degli zigomi  (+41%).<br>Il viso ha una forma più delineata, la pelle è tesa e ha la massa corretta.',
    lt75: '1321 donne',
    lt76: 'Risultati visibili<br><span class="violet">Il tono della pelle è in salute e aumenta (+65%),</span> la pelle è più spessa (+54%) e idratata per 48 ore.',
    lt77: '<span class="red">UN SONDAGGIO DI GRANDE DIMENSIONE HA DIMOSTRATO -</span> CHE LA MAGGIOR PARTE DELLE PERSONE "LA PENSANO COSI’"',
    lt78: 'NON CATTURANO L’ATTENZIONE',
    lt79: 'Il 74% degli uomini hanno risposto sinceramente, che le donne con le rughe i con i segni d’invecchiamento sulla faccia non sono e non possono essere sessualmente attraenti.',
    lt80: 'TETTO LAVORATIVO',
    lt81: 'Il 67% dei datori di lavoro non assumono e non promuovono una donna che appare più anziana dei 45 anni.',
    lt82: 'TRADIMENTI',
    lt83: 'il 96% dei mariti hanno lasciato le loro mogli in favore di amanti più giovani dato che l emogli hanno smesso di prendersi cura di sé ',
    lt84: 'Gli studi hanno dimostrato: L’87% degli uomini affermano,che  <span class="red">l’età delle donne non ha valore,</span> l’importante è che la donna appaia <span class="red">curata e attraente.</span>E’ questo a renderla agli occhi degli uomini <span class="red">sensuale e rispettabile.</span>',
    lt85: 'Abbiate il controllo del tempo',
    lt86: 'DIVENTATE <span class="red">PIU’ GIOVANI DI 10 ANNI</span> CON 2 CICLI E MEZZO',
    lt87: 'Rughe naso labiali<span class="orange">SCOMPARSE</span>in 2 cicli',
    lt88: 'Zampe di gallina<span class="orange">SCOMPARSE</span> in 3 cicli',
    lt89: 'Rughe tra le sopracciglia<span class="orange">SCOMPARSE</span> in 2 cicli',
    lt90: 'Pelle penzolante<span class="orange">SCOMPARSA</span> in 1 ciclo',
    lt91: 'Borse sotto gli occhi<span class="orange">SCOMPARSE</span> in 1 ciclo',
    lt92: 'PARERE INDIPENDENTE DEI COSMETOLOGI',
    lt93: 'Maria Fello<br>Cosmetologo – Dermatologo<br>Stage lavorativo 18 anni',
    lt94: 'Se ci fossi io al posto del vostro cosmetologo, certamente tenterei di fare sempre il meglio e di proporvi solo il meglio di quello che la tecnologia moderna può offrire: <span class="violet">botox, lifting chirurgico, filler ecc.</span>Ma come persona, come donna, capisco che con <span class="violet">Biorecin  tutte queste procedure sono rinviabili di 6 anni.</span>',
    lt95: 'E lasciate che gli altri pensino si tratti di chirurgia...',
    lt96: 'Vittoria Moroso<br>Assistente anziano del chirurgo plastico<br>Stage lavorativo 7 anni',
    lt97: 'Raccomando di non andare di fretta con le iniezioni, le operazioni e gli altri interventi intrusivi e traumatici. Lasciate stare questa idea per una 20ina. Semplicemente<span class="violet">provate Biorecin e tra un mese capirete che la rivoluzione nella medicina estetica è avvenuta</span> La medicina estetica (medicina applicata alla cosmetologia) - è il futuro di bellezza e giovinezza, e possiamo servircene già ora e goderci i risultati.',
    lt98: 'Lasciate che la vostra pelle ringiovanisca!',
    lt99: 'In tutti i prestigiosi saloni di Milano <span class="blue">da tempo ormai utilizzano Biorecin.</span> Una procedura di scrab, massaggio del viso e applicazione della crema, costa di norma 100 euro',
    lt100:'RECENSIONI SINCERE',
    lt101:'Raccomandata da donne vere.',
    lt102:'Nel 2016 abbiamo venduto più di  3 000 000 confezioni.',
	lt103:'Avete già ordinato Biorecin?',
    lt104:'Michela, Piacenza',
    lt105:'Giulia, Roma',
	lt106:'Caterina, Pisa',
    lt107:'12 000 000 di euro sono stati spesi per creare Biorecin',
    lt108:'anni spesi per creare il prodotto',
	lt109:'anni per creare la formula',
    lt110:'specialisti impegnati ',
    lt111:'percentuale di efficacia',
	lt112:'percentuale di donne felici',
    lt113:'certificati di qualità ЕС, РТС, ISO',
    lt114:'percentuale di componenti naturali',
	lt115:'ATTENZIONE!',
    lt116:'Per via della popolarità acquisita in Italia e in tutta Europa, e anche nel resto del mondo, sono comparsi in vendita esemplari falsi a prezzi ridicoli! <br> Fate attenzione! Sulla confezione originale deve esserci lo strip code con il numero di riconoscimento unico! Qualora manchi lo strip code, inviateci una lamentela,scrivendoci all’indirizzo indicato in basso nella pagina. VI restituiremo la perdita e affronteremo il problema contro il falso per vie legali.',
    lt117:'come lavoriamo?',
	lt118:'PRIMO PASSO',
    lt119:'Effettuate l’ordine velocemente <span class="red">a prezzo scontato</span>',
    lt120:'SECONDO PASSO',
	lt121:'Attendete la consulenza per definire i dettagli',
    lt122:'TERZO PASSO',
    lt123:'Non pagate nulla finché non ricevete il pacco',	
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};