var new_lang = {
lt1:  '- 100% saugu ir efektyvu',
    lt2:  'Mums <span class="blue">JAU</span> paskambino 4 672 žmonės ir pasakė <span class="blue">AČIŪ!</span>',
    lt3:  'Užsakyti nemokamą konsultaciją',
    lt4:  '<span class="big">Bioretin:</span> pagrindinis sąjungininkas <span class="blue">kovoje su amžiumi</span>',
    lt5:  '<span class="blue">Mažina </span> raukšles',
    lt6:  '<span class="blue">Atstato</span> tamprumą',
    lt7:  '',
    lt8:  '<span class="blue">Patempia</span> kontūrus',
    lt9:  '<span class="violet">”Snaudžiančių”</span> ląstelių atnaujinimas',
    lt10: '<span class="violet">Pažeistų</span> ląstelių atnaujinimas',
    lt11: '<span class="violet">Sveikų</span> ląstelių regeneracija',
    lt12: 'kaina<br><span class="bold">1 EURAS*</span>',
    lt13: 'Kaina pagal akciją:<br><span class="big">1 EURAS *</span>',
    lt14: 'Sena kaina:',
    lt15: 'iki akcijos pabaigos liko:',
    lt16: 'dienų',
    lt17: 'valandų',
    lt18: 'minučių',
    lt19: 'sekundžių',
    lt20: 'DĖMESIO! Pakuočių skaičius pagal akciją yra ribotas.',
    lt21: 'Liko: ',
    lt22: ' vnt..',
    lt23: '* - užsakant visą kursą',
    lt24: 'Kiek metų jūsų odai?',
    lt25: 'Manoma, kad senėjimo požymis yra vienas – tai raukšlės. Bet jūs žinote, kad raukšlelės yra tik pusė bėdos. <span class="red">KIEKVIENA NAUJA PROBLEMA PRIDEDA JUMS AMŽIAUS!</span>',
    lt26: 'Nosies-lūpų raukšlės',
    lt27: '+6 metų',
    lt28: 'Formą prarandantis veido ovalas',
    lt29: '+5 metų',
    lt30: 'Žąsies letenėlė',
    lt31: '+4 metų',
    lt32: 'Raukšlės tarp antakių',
    lt33: '+7 metų',
    lt34: 'Maišeliai po akimis',
    lt35: '<span class="violet">Oda turi savo amžių.</span> Jis skiriasi nuo mūsų amžiaus. Ne soda yra labia lengvai pažeidžiama, maksimaliai jautri laiko sunaikinimui, skirtingai nuo kitų organų. Po 35 metų oda sensta greitai! Priežastis yra gravitacija, paveldimumas, bloga ekologija, ultravioletas, spinduliuotė, stresas ir neteisinga mityba. <span class = "red"> Paskaičiuokite, kiek metų jūsų odai dabar. </ span> <span class = "underline"> Pažymėkite punktus, su kuriais jūs sutinkate.</span>',
    lt36: 'Įveskite Jūsų tikrą amžių:',
    lt37: 'Aš turiu nosies-lūpų raukšles:',
    lt38: 'Oda prarado tamprumą:',
    lt39: 'Raiškios mimikos raukšlės:',
    lt40: 'Yra keletas gilių raukšlių:',
    lt41: 'Nurodykite Jūsų amžių',
    lt42: 'Rekomenduota: 17 vienetų botulotoksino, 2 kursai mezoterapijos, 28 bio-siūlų <br><span class="white">ARBA 1 kursas kremo Bioretin</span>',
    lt43: 'Rekomenduota: 37 vienetų botulotoksino, 3 kursai mezoterapijos, 38 bio-siūlų, 1 kursas filerių <span class="white">ARBA 2 kursai kremo Bioretin</span>',
    lt44: 'Rekomenduota: 47 vienetų botulotoksino, 4 kursai mezoterapijos, 48 bio-siūlų, 1 kursas filerių <span class="white">ARBA 3 kursai kremo Bioretin</span>',
    lt45: 'Rekomenduota: 57 vienetų botulotoksino, 5 kursai mezoterapijos, chirurginis veido patempimas <span class="white">ARBA 3 kursai kremo Bioretin</span>',
    lt46: 'kam atrodyti senesniems nei jūs esate, jeigu',
    lt47: 'jūs galite atrodyti jaunesniems?',
    lt48: 'DAUG JAUNESNIEMS, BE SKAUSMO IR RIZIKOS!',
    lt49: 'moterys gailisi, kad sutiko injekcijoms ir chirurginiam įsikišimui',
    lt50: 'įrodytas saugumas ir efektyvumas',
    lt51: 'Bioretin NAUJAUSIOS FORMULĖS',
    lt52: 'prieš senėjimą',
    lt53: 'GRĄŽINTI GERIAUSIUS GYVENIMO METUS IR JAUNYSTĘ',
    lt54: 'Bioretin – INOVACIJOS ir REZULTATAS',
    lt55: 'Bioretin yra inovacinis kremas, kurio sudėtyje yra odai gydomieji arganos ir avokado aliejai, vitaminai ir gialurono rūgštis, maitina ir jaunina gilius odos sluoksnius, stimuliuoja epitelinio audinio augimą',
    lt56: 'Tai yra, kremas aktyviai stimuliuoja kolageno gaminimą ir tarpląstelinės „matricos“ regeneraciją. Todėl gali <span class="violet">pastebimai išsilyginti mimikos raukšles ant kaktos, burnos ir akių srityje (žąsies letenėlės). </span><br><span class="orange">Bioretin yra įspūdingas „kokteilis“ nosies-lūpų ir tarp antakių esančių raukšlėms koreguoti.</span>',
    lt57: 'Jo sudėtyje yra komponentai, kurie sukurti „didinti tūrį“ poveikio vietoje, kas <span class="violet">užpildys raukšleles iš vidaus,</span> “išstūmiant” odą atgal. Jie taip pat “atpalaiduos” raumenų mikro trumpėjimą ir trukdys raumenims raukti odą antakies srityje.',
    lt58: 'Bioretin sudėtyje yra vienas stipriausių antioksidantų, neutralizuojantis laisvuosius radikalus – pagrindinę senėjimo priežastį.',
    lt59: 'Mažina kolageno suirimą, paprasčiau sakant, kovojasi su senėjimo apsaugodamas ląsteles nuo suirimo. Stimuliuoja kraujos apyvartą limfoje patinimui, „maišelių“ šalinti ir tamsiems ratilams po akimis mažinti. Stiprina odos struktūra, <span class="violet">patempia veido reljefą, ovalą,</span> nes natūraliai gamina kolageną ir elastiną.',
    lt60: 'Gialurono rūgštis',
    lt61: 'Arganos aliejus',
    lt62: 'Avokado aliejus',
    lt63: 'Glicerinas',
    lt64: '',
    lt65: 'Bioretin sensacinis efektas.',
    lt66: '89 proc. moterų pradėjo atrodyti taip, kaip jos jaučiasi!',
    lt67: 'Po 40 metų ląstelių regeneracija pradeda letėti.',
    lt68: 'Atsiranda vis daugiau raukšlių, oda praranda tamprumą, o veido kontūrai darosi mažiau ryškiomis. Revoliucinė priežiūra prieš senėjimą Bioretin specialiai sukurtas senstančios odos priežiūrai.',
    lt69: 'Bioretin trigubą veikimą patvirtina didelio masto klinikiniai tyrimai:',
    lt70: '1183 moterys',
    lt71: 'Pažymėjo, kad <span class="violet">žymiai sumažėjo </span> raukšlių ir niūraus žvilgsnio linijų (77 proc.), akių kampeliuose (56 proc.) ir ant kaktos (76 proc.)',
    lt72: '927 moterys',
    lt73: 'Užsipildė tūris nosies-lūpų raukšlėse,',
    lt74: 'tūris skruostikaulių srityje atnaujintas (+41 proc.).<br>Veido ovalas ryškesnis, oda labiau patempta ir užpildyta tūrio.',
    lt75: '1321 moteris',
    lt76: 'Metomi rezultatai<br><span class="violet">Odos tonusas didėja (+65 proc.),</span> ji yra tankesnė (+54 proc.) ir sudrėkinta 48 valandoms.',
    lt77: '<span class="red">DIDELIO APIMTIES APKLAUSA PARODĖ -</span> SUSENUSIUS ŽMONES “NURAŠO IŠ SĄSKAITŲ "',
    lt78: 'NESIKREIPIA DĖMESIO',
    lt79: '74 proc. vyrų atvirai atsakė, kad moterys su raukšlėmis ir senėjimo požymiais ant veido negali būti seksualiai patrauklios.',
    lt80: 'KARJEROS LUBOS',
    lt81: '67 proc. darbdavių nepriims į darbą ir nepasiūlys aukštesnių pareigų moteriai, kuri atrodo vyresne nei 45 metų',
    lt82: 'VYRO NEIŠTIKIMYBĖS',
    lt83: '96 proc. vyrų metį savo žmonas dėl jaunesnės meilužės ir dėl to, kad žmona liovėsi save prižiūrėti.',
    lt84: 'Tyrimas patvirtino: 87 proc. vyrų teigia, kad <span class="red">moters amžiaus neturi reikšmės,</span> svarbu, kad moteris atrodytų <span class="red">prižiūrėta ir patraukli.</span> Tai vyro akyse ją  daro <span class="red"> seksualine ir sukelia pagarbą.</span>',
    lt85: 'Imkite laiką savo rankuosna',
    lt86: 'TAPKITE <span class="red"> 10 METŲ JAUNESNE</span> PO 2,5 KURSO',
    lt87: 'Nosies-lūpų raukšlės <span class="orange">DINGO</span> po 2 kursų',
    lt88: 'Žąsies letenėlės <span class="orange">DINGO</span> po 3 kursų',
    lt89: 'Raukšlė tarp antakių <span class="orange">DINGO</span> po 2 kursų',
    lt90: 'Formą prarandantis veido ovalas <span class="orange">DINGO</span> po 1 kurso',
    lt91: 'Maišeliai po akimis <span class="orange">DINGO</span> po 1 kurso',
    lt92: 'NEPRIKLAUSOMA KOSMETOLOGŲ NUOMONĖ',
    lt93: 'Agnė Jonuškaitė<br>Gydytoja kosmetologė-dermatologė <br>Praktikos stažas 18 metų',
    lt94: 'Jeigu aš būčiau Jūsų kosmetologo vietoj, tai žinoma pasistengčiau Jums pasiūlyti maksimumą iš to, ką galiu, ir iš to, ką gali grožio technologijos: <span class="violet">botoksą, plazmoloiftingą, filerius ir kt.</span> Bet kaip žmogus, kaip moteris, aš suprantu, kad su <span class="violet">Bioretin visas šias procedūras galima atidėti dar 6 metams.</span>',
    lt95: 'Ir tegul mano, kad tai plastika...',
    lt96: 'Indrė Kusienė<br>Plastinio chirurgo vyresnioji asistentė <br> Praktikos stažas 7 metų',
    lt97: 'Aš rekomenduoju neskubėti su injekcijomis, operacijomis ir kitais traumatiniais įsikišimais. Palikite šią ideją 20 metams. Tiesiog <span class="violet">pabandykite Bioretin ir po 1 mėnesio jūs suprasite, kad revoliucija estetinėje medicinoje įvyko.</span>Kosmeceutika (medicininė kosmetika) yra grožio ir jaunystės ateitis, ja mes galime naudotis jau dabar ir džiaugtis iš rezultatų.',
    lt98: 'Leiskite Jūsų odai tapti jaunesne!',
    lt99: 'Visuose prestižiniuose salonuose Vilniuje <span class="blue">jau seniai taiko Bioretin.</span> Viena procedūra iš skrabo, veido masažo ir patepimo kremu kainuoja apie 80 eurų',
    lt100: 'ATVIRI ATSILIEPIMAI',
    lt101:'Realių moterų rekomenduota.',
    lt102: 'Per 2016 metus parduota daugiau nei 3 000 000.',
	lt103:'Ar Jūs jau užsisakėte savo Bioretin?',
    lt104:'Kamila, Alytus',
    lt105:'Viktorija, Tauragė',
	lt106:'Birutė, Šilutė',
    lt107:'12 000 000 $ buvo investuota sukuriant Bioretin',
    lt108:'metų tyrimams atlikti',
	lt109:'metų formulei sukurti',
    lt110:'veikiančių specialistų',
    lt111:'proc. efektyvumas',
	lt112:'procentų laimingų moterų',
    lt113:'kokybės sertifikatai ЕС, РТС, ISO',
    lt114:'procentų natūralių komponentų',
	lt115:'ATSARGIAU!',
    lt116:'Dėl populiarumo Lietuvoje ir Europos Sąjungos šalyse, padažnėjo padirbinių pardavimo atvejų pusdykio kaina!<br>Būkite atidūs! Ant originalios pakuotė būtinai bus brūkšniuotas kodas su tikrumo numeriu! Jeigu brūkšniuoto kodo nėra, kreipkitės su skundu, parašęs mums paštu, nurodytu puslapio apačioje. Mes jums atlyginsime nuostolius ir persekiosime sukčius apgal įstatymus.',
    lt117:'Kaip mes dirbame?',
	lt118:'1 ŽINGSNIS',
    lt119:'Padarykiter momentalų užsakymą <span class="red">akcijos kaina</span>',
    lt120:'2 ŽINGSNIS',
	lt121:'Sulaukite konsultanto skambučio detalėms suderinti',
    lt122:'3 ŽINGSNIS',
    lt123:'Jūs nieko nemokate iki siuntos gavimo momento',	
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};