var new_lang = {
    lt1: 'Obejdnat bezplatné volání',
    lt2: 'Účinek «Tinedol»',
    lt3: 'Efektivita',
    lt4: 'Recenze',
    lt5: 'Snadný způsob překonat kvasinky, svědění a praskliny!',
    lt6: 'Léčí kvasinky na chodidlech a nehtů',
    lt7: 'Odstraňuje svědění a loupání kůže',
    lt8: 'Odstraňuje pocení a zápach',
    lt9: 'Hojí praskliny na patách',
    lt10: 'SLEVA',
    lt11: '-50%',
    lt12: 'Omezená řada!<br>Spěchejte!<br> Jenom <span class="product-how-much"><span class="lastpack">5</span> balení</span> <br>po akční ceně!',
    lt13: 'Do konce akce zbývá',
    lt14: '00',
    lt15: 'Hodin',
    lt16: '25',
    lt17: 'Minut',
    lt18: '59',
    lt19: 'Sekund',
    lt20: 'Původní cena:',
    lt21: 'Cena se slevou',
    lt22: 'Objednat',
    lt23: 'Vaše osobní údaje jsou chráněné',
    lt24: 'span class="title2-span1">Myslíte si, že kvasinky vás obešly?</span> Pokud jste si všimli na sobě alespoň jednoho příznaku,<br> tak začněte léčení již dnes<',
    lt25: 'Zvláštní zápach',
    lt26: 'Praskliny a loupání kůže',
    lt27: 'Nesprávný tvar nehtu',
    lt28: 'Nehet se mění <br>do hnědá nebo žlutá',
    lt29: 'Ryhy a bílé <br>skvrny na nehtu',
    lt30: 'Svědění a pálení',
    lt31: 'Puchýře na chodidlech',
    lt32: 'Necitlivost a brnění',
    lt33: 'Ztvrdnutí <br>kůže na chodidlech',
    lt34: 'Co se stane, když nebudete léčit kvasinky(plíseň) na chodidle',
    lt35: 'Na základě statistiky každý pátý obyvatel v Rusku má kvasinkové onemocnění.<br> Utěsněná uzavřená obuv, syntetické ponožky, sauny, bazény.<br> <span class="stage__span1">V letní období se přidávájí pláže, parky, kde většina chodí naboso.<br> Všechno tohle vede k strašným nemocem!</span> Stop!',
    lt36: 'První etapa:',
    lt37: '<i></i>Loupání kůže',
    lt38: '<i></i>Svědění',
    lt39: '<i></i>Pocení',
    lt40: '<i></i>Nepříjemný zápach',
    lt41: '<i></i>Nepohodlí',
    lt42: 'Druhá etapa:',
    lt43: '<i></i>Kvasinky na nehtech',
    lt44: '<i></i>Hluboke praskliny<',
    lt45: '<i></i>Zvýšené pocení a svědění',
    lt46: '<i></i>Trvalý zápach',
    lt47: '<i></i>Žluté, křehké nehty',
    lt48: '<i></i>“Mrtvá”, hrubá kůže',
    lt49: '<i></i>Velké nepohodlí <br>během chůze',
    lt50: 'Třetí etapa:',
    lt51: '<i></i>Loupání kůže a svědění <br>mezi prsty',
    lt52: '<i></i>Jizvy a hluboké <br>praskliny',
    lt53: '<i></i>Bolest',
    lt54: '<i></i>Vředy',
    lt55: '<i></i>Ztáta nehtů',
    lt56: '<span class="stage__main-block-span">Pokud nezačít léčit chodidla, je riziko celkem rychle zanedbat nebezpečnou nemoc!</span><br> Představte si, že to jsou vaše nohy! Chcete mít taková chodidla?<br> Řekněte ne!',
    lt57: 'Jak funguje <span class="title4-span1">krém «Tinedol»?</span>',
    lt58: '<span class="work__span1">Při pravidelném použití, «Tinedol» zbavuje hned několika problémům.</span> Nacházející aktivní složky ve složení efektivně odstraňují',
    lt59: 'Kvasinky',
    lt60: 'Zápach',
    lt61: 'Pocení',
    lt62: 'Praskliny',
    lt63: '<span class="consist__text--b">Klimbazol</span> — zastavuje růst kvasinek. Zbavuje svědění. Účinně ničí kvasinky.',
    lt64: '<span class="consist__text--b">Farnezol</span> — “vypíná” potní žlázy. Dezifinkuje, suší, daruje trvalou příjemnou vůni. <span class="consist__text--b">Propolis </span> má silné antibakteriální vlastnosti.<span class="consist__text--b"> Olej z čajového stromu </span> dostává se hluboko do podkožní vrstvy, zahojuje problémové zóny kůže, dává chládek a odstraňuje nepříjemné zápachy po namáhavému pracovními dni. ',
    lt65: 'Krém výborně zvhlčuje a vyživuje pokožku nohou, odstraňuje hrubost, oloupává, zahojuje praskliny.',
    lt66: 'Na rozdíl od jiných prostředků, Krém «Tinedol» se rovnoměrně rozkládá po celém povrchu chodidla. Rychle se vstřebává a nezanechává otisky na povlečení nebo oblečení. ',
    lt67: 'Do limitované sérii jsme přidali kamenný olej. Efektivně bojuje s mozoly a otlačeniny. Daruje kůži chládek a pohodlí po náročném dni.',
    lt68: 'Snadný způsob se zbavit <br>kvasinků, svědění a prasklin!',
    lt69: 'Výsledek po 30 dnech <span class="title6-span1">používání oleje</span> «Tinedol»',
    lt70: 'Zmizí kvasiky na <br>chodidlech a nehtech',
    lt71: 'Zadejte osobní údaje dále do pole',
    lt72: 'Mizí svědění a <br>loupání kůže',
    lt73: 'Příjemná vůně',
    lt74: 'Nohy se nepotí',
    lt75: 'Zahojují se <br>praskliny',
    lt76: 'Čilost a pohodlí <br>v pohybu',
    lt77: 'Krásná, <br>upravená chodidla',
    lt78: 'Jak se používá <span class="title7-span1">krém «Tinedol»?</span>',
    lt79: 'Před nanášením pořádně umyjte nohy a utřete. Dejte tenkou vrstvu na celé chodidlo. Každý večer před spaím během 30 dní.<br> Všimnete si, že paty se mění do růžová a kůže se stává zdravou!',
    lt80: 'Čím je krém «Tinedol» lepší než jiné protikvasinkové prostředky?',
    lt81: 'Protikvasinkové prostředky se dělí na 2 druhy: první nepomáhají, druhý fungují jen během použití. Lidé, kteří se trápí kvasinky nohou, musí stále pužívat krémy a mastičky.',
    lt82: '«Tinedol» mění sitauci zásadním způsobem. Hromadné klinické průzkumy ukázaly, že tento prostředek efektivně zbavuje kvasinky nohou a nehtů. Již po 1 kurzu léčení kvasinky mizí a nevrací se. Takový silný účinek je díky přírodním složkám.',
    lt83: 'Názor odborníka',
    lt84: 'Tento prostředek dokázal svoji účinnost. Hlavní přednosti- je komplexní péče. I když se symptomy neprojevují, je třeba začít používat «Tinedol» pro prevencí již teď. Kvasinky nohou se rozvíjí hodně rychle! Dnes lehké oloupání a svědění, a zítra budete muset jít do nemocnici a brát antibiotika 5 krát denně. Nečekejte! Lečte problém teď. Kromě toho, kvasinky jsou nakažlivé. Pokud jste nemocní nebo někdo z blízkých – je nemocná celá rodina!<br>',
    lt85: '<br>— Alexej Bozunov<br>k.m.n., MMSI jm.N.A. Seaško. Lékař – dermatolog, kosmetolog, mykolog.',
    lt86: 'Recenze',
    lt87: 'Před «Tinedol» jsem myslela, že kvasinky – jsou jako kvasinky, že zmizí na nějakou dobu, a pak se znovu objeví...Zkoušela jsem spousta jiných prostředků. Symptomy zmizely,ale kvasnice asi zůstavaly v nohou. Musela jsem jít k doktorovi, ten mi předepsal «Tinedol». Už jako půl roku mě nic netrápí. <br>Děkuji!',
    lt88: 'Elena, Praha',
    lt89: 'Patičky jsou jako u malého dítěte! Furt chodím do bazénu. A když jsem se dozvěděla, že mám kvasinky, tak moc jsem se tomu nedívila, sprchy jsou pro všechny, šatny také, chlor proti kvasinkám nezachrání. A co mám dělat. Všechny holky u nás vědí, že není nic lepšího, než «Tinedol»! Všechny to používáme a nikdo není nemocný!',
    lt90: 'Alexandra, Karlovy Vary',
    lt91: 'Kvasinky se zvykají na ty prostředky, kterými léčíte. Manželovi se strašně moc potily nohy a kvůli tomu nemizely kvasinky. Kvůli 2 vlasntostem jsme si vybrali «Tinedol». Protože je proti pocení a kvasinkám. 3 měsíce používal. Všechno zmizelo!',
    lt92: 'Kateřina, Tvěr',
    lt93: 'BERNADATTE LTD, Av Ricardo J. Alfaro, Panama International       <br>       <a href="http://leadbit.com" target="_blank">Leadbit</a> | <a href="/cdn/files/Privacy Policy.html" target="_blank">Privacy Policy</a>',
    title: 'Koupit «Tinedol» levně. Ceny, recenze. Objednejte «Tinedol» teď!',
};

function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
};