var new_lang =   {

lt0: '<span class="glyphicon glyphicon-eye-close"></span>Versión para las personas con descapacidad visual ',
lt1: '<span class="glyphicon glyphicon-bullhorn"></span>RSS',
lt2: '<span class="glyphicon glyphicon-globe"></span>Mapa del sitio web',
lt3: '<span class="glyphicon glyphicon-log-in"></span>Entrar',
lt4: '<i class="fa fa-twitter"></i>Leer',
lt5: '<span class="glyphicon glyphicon-phone"></span>Aplicación para iPhone',
lt6: 'Blog de Arturo Vargas ',
lt7: 'Noticias',
lt8: 'Blog<span class="caret"></span>',
lt9: ' Archivo de los documentos ',
lt10: 'Principal<span class="caret"></span>',
lt11: 'Actividades<span class="caret"></span>',
lt12: 'Encuestas',
lt13: 'Contactos<span class="caret"></span>',
lt14: 'Anuncios',
lt15: 'PROGRAMA FEDERAL DE LUCHA CONTRA LAS ENFERMEDADES DEL APARTO LOCOMOTOR (ARTICUALCIONES) ESTÁ POR REALIZAR en<span class="city" style="text-transform: uppercase">&nbsp;Madrid</span>',
lt16: 'Publicado<span class="date__yesterday">el 13 de septiembre del año 2017, 10:27</span>.<br><br><br><img src="./i_files/1.jpg" style="float: left; margin-right: 25px" width="50%">',
lt17: '<strong>El señor Arturo Vargas</strong><br>, médico español, doctor en ciencias médicas, profesor catedrático. Traumatólogo Ortopedista de categoría superior.  Jefe del Departamento de cirugía de la columna vertebral. Posee todas las metodologías modernas del tratamiento quirúrgico y no quirúrgico de las enfermedades y lesiones de la columna verteblar y la médula espinal',
lt18: ' “Recordad una simple verdad, y no escuchéis a nadie: las articulaciones son curables siempre, hasta en la vejez avanzada”',
lt19: 'Pedimos al señor Arturo Vargas, doctor en ciencias médicas,  profesor catedrático, que nos cuente más detalladamente sobre el programa federal “España Sana”.',
lt20: 'Este doctor declara que curará la osteocondrosis de 18 años en un par de meses. Que curará por completo a una abuela viejita que tenga la artrosis más descuidada en 78 días. ¡Y dice que los dolores en las articulaciones pasarán en 4 días con el cuidado adecuado! Y, durante 48 años de su actividad reafirma cada su declaración en práctica. Después de la emisión en el canal de telivisión TVE1 (del tema “cómo guardar las articulaciones sanas en cualquier edad”), el señor Arturo Vargas, profesor catedrático conocido, aceptó participar en la entrevista.',
lt21: '— Hola, señor Vargas. Diga por favor, ¿Si es cierta la afirmación de que las enfermedades de las articulaciones y la osteocondrosis son concomitantes “obligatorios” de la edad madura?',
lt22: '— ¡Hola, Irene! Claro que no es verdad. El concomitante  obligatorio de la edad madura es la confianza excesiva en los médicos que os están curando durante 10 años, pero no logran sanar. Y en realidad las articulaciones, las condrosis y todo el esqueleto se curan perfectamente en cualquier edad. Y no es milagro ninguno, es la ciencia normal.',
lt23: 'Además, si uno sabe el secreto y tiene un poco de disciplina – se puede curarse hasta en casa y muy rápido, y es lo que están haciendo miles pacientes míos.',
lt24: '— ¿Y en que consiste este secreto?',
lt25: '— El secreto consiste en comprender  porqué os duele. En general, las enciclopedias  cuentan con más de 147 causas posibles del desarollo de la osteocondrosis y artrosis, pero la consecuencia es una – las articualciones, vértebras y cartílagos pierden su elasticidad, que provoca el dolor. Se desgastan por la mala circulación.',
lt26: '¡Y ese es todo el secreto – al recuperar el suministro de sangre a la articulación la sanamos!',
lt27: '— Si, ¿pero si se considera que es casi imposible recuperar el suministro de sangre después de los 40 años?',
lt28: '— ¡Son tonterías no más! Yo me saqué de la silla de ruedas después de un accidente, y es peor que la edad de 40 años.',
lt29: '— ¿Cuáles son los primeros síntomas del empeoramiento de funcionamiento de las articulaciones después de los 40 años?',
lt30: 'Se puede considerar que son los primero síntomas  cuando el paciente siente una limitación en los movimientos de las articulaciones de los brazos  o piernas. Esto sucede por la sobrecarga de las articualciones; el levantamiento de los cargos, por ejemplo, bolsas pesadas, calzado incomodo, los movomientos repetitivos, todo eso lleva a la sobrecarga. Los cartílagos articulares se destruyen, los huesos empiezan a tocarse, por eso Ud siente la incomodidad. Como consecuencia de eso primero aparece la limitación en los movimientos y la edemetización, y después <strong>la extremidad puede paralizarse totalmente </strong>. También lo que desempeña un papel muy importante es el contenido elevado de la sal en el organismo. Si tenéis calambre en los brazos o piernas, es necesario limitarse urgente en el consumo de los productos y líquidos que contienen el sodio:',
lt31: 'No se recomienda beber:',
lt32: 'Agua mineral',
lt33: 'Jugo de tomates',
lt34: 'Salmueras',
lt35: 'Bebidas alcohólicas',
lt36: 'Tan, kumís (productos de leche agria con el alto contenido del sodio)',
lt37: 'No se recomienda comer:',
lt38: 'Mantequilla salada, margarina',
lt39: 'Todos los tipos de quesos duros y blandos',
lt40: 'Carne ahumada, jamón, beicon, carnaje, filete de carne, gelatina, carne en conserva ',
lt41: 'Salchichas, embutidos, (a los chorizos de fabricación industrial y otros productos de carne se les añaden muchos conservantes y estabilizadores, que contienen mucho sodio)',
lt42: 'Platos de carne y pescado semipreparados (en conserva o congelados)',
lt43: 'Pescado y mariscos ahumados y en conserva ',
lt44: 'Cangrejos, langostas, gambas, langostinos (si no estan preparados sin sal)',
lt45: 'Verduras en conserva (aparte de las especiales, en las que no se utiliza la sal en calidad del conservante)',
lt46: 'Patatas fritas, col en salmuera ',
lt47: 'Cacahuetes fritos y salados, manteca de cacahuete ',
lt48: 'Salsas, adobos, kétchups, escabeches, marinadas (excepto los caseros, preparados sin sal)',
lt49: 'Todos los tipos de las sopas semipreparadas',
lt50: 'Cubitos de caldo',
lt51: '— ¿Y ha sacado Ud a otros de la silla de ruedas?',
lt52: '— Y más de una vez. Pero la mayor parte de mis pacientes son las personas ordinarias mayores de 40 años, las enfermedades de los que aparecieron “con la edad”. Vienen con los problemas muy parecidos: la osteocondrosis, artrosis, artritis, radiculitis, pinzamiento. Estas enfemedades agotan y impiden vivir.',
lt53: 'Lloran, les duele, les es difícil andar incluso. Y, pareciera que son las personas ordinarias – no son deportistas ni descapacitados. Y se quejan –“¿Por qué me pasa esto, por qué yo?".  Y contesto: no vamos a lamentarnos, sino recuperar el suministro de sangre.',
lt54: '— ¿Y cómo recuperar el suministro de sangre en tal edad?',
lt55: '— Hasta hace poco tiempo estaba curando a la gente con la ayuda del movimiento y el complejo de 96 ejercicios en las máquinas de entrenamiento. Es un método muy eficaz, pero muy duro y largo. A la gente le duele, es dificil, no le da tiempo para visitar el gimnacio.  Yo creía que debía haber  un método más moderno y fácil – y lo encontré.',
lt56: '— ¡Qué interesante! ¿Contará Ud sobre este método a nuestros lectores?',
lt57: '— Si, voy a contar. Nuestro centro fue el primero en España que recibió el acceso certificado a un remedio moderno contra la osteocondrosis y dolores en las articulaciones. Os confieso que cuando oí de él por primera vez – me reí simplemente, porque no creí en su eficiencia. Pero estuve asombrado, cuando terminamos la prueba – 4.567 personas se curaron totalmente de sus enfemedades, son más del 94% de todas las personas sometedias a prueba. 5.6% sintieron mejoras notables, y tan solo 0.4% no notaron mejoras .',
lt58: '— ¿Y qué remedio es?',
lt59: '— Estoy hablando de un gel especial <a href="">"Hondrocream"</a>. Es  un remedio que permite en un tiempo corto, desde 4 días, olvidar del dolor en la espalda y las articualciones, y durante un par de meses curar hasta los casos muy complicados ',
lt60: 'Se fabrica solamente en la China, y el estado gastó 1.3 millones de dolares para el dasarrollo de la fórmula. Y nosotros, por cierto, pagamos casi 600 mil euros por tener el derecho de comercializar este gel en el territorio de España.',
lt61: '— ¿Y cómo funciona esta maravilla de gel?',
lt62: '— Pués, aquí no hay milagro ninguno, pura ciencia. El gel consiste de 9 componentes potentes que al contactar con las células viejas y débiles las hacen funcionar 7 veces más rápido, y las células se rejuveneces poco a poco.',
lt63: 'Hasta después de un uso de gel en la zona afectada se activan cerca de 930.000 células, que sirven de ayuda para vuestra circulación sanguínea. Y así se realiza la curación. Aquí lo más principal es la estabilidad.',
lt64: '— Suena impresionante. ¿Pero, explíquenos, por favor, que significa esto para la gente común que tiene las enfermedades?',
lt65: '— Significa que la medicina española medieval se val al pasado, y podéis curar vuestras enfermedades en casa en uno o dos meses. El gel no congela, no anestesia, sino “reinicia” el organismo en el nivel celular. Elimina la misma causa de las enfermedades y recupera las articculaciones, la columna vertebral hasta su estado inicial. El paciente no se deshace de los síntomas, sino elimina la raíz de la enfermedad  - la circulación sanguínea cortílaginosa debilitada por las células viejas.',
lt66: 'El primer día el gel reinicia los sistemas de regeneración del organismo. Pués, elimina el síndrome doloroso también, lo sentiréis en seguida. En unas dos o tres semanas del uso ya se acabará el tratamiento, y, lo más principal, no admitir la recidiva de los dolores y repetir el tratamiento.',
lt67: '—<a href="">¿Este gel ayuda solamente</a>contra la artosis y osteocondrosis?',
lt68: '— No, pués, si digo: actua en el nivel celulalr, recuperando la circulación. Cura cualquier enfermedad relacionada con los cartílagos y columna vertebral: artrosis y artritis, ciática, reumatismo, radiculitis y osteocondrosis, disclocación de discos vertebrales. Lujaciones,cardenales, equimosis, roturas, pués aunque sean tilomas – el gel es extremadamente eficaz.',
lt69: '— Es un remedio muy interesante. ¿Y qué, de verdad cura todas estas enfermedades y no tan solo elimina el dolor?',
lt70: '— El gel elimina el dolor también (en las etapas iniciales del tratamiento) y liquida la enfermedad por completo. Entendedme correctamente – me gusta la cultura física y el deporte, y no dejaré de practicarlo, pero para la mayoría de los pacientes este gel – es el método de tratamiento más simple, eficaz y accesible.',
lt71: '¡Ud dijo que se puede comprar Hondrocream a precio ventajoso<!— a 1 solo euro.-->?¿Cualquier persona puede hacerlo?',
lt72: 'Sí, absalutamente cualquiera. La verdad que hay un pero. En el momento actual el programa federal se está realizando solamente en el territorio de <span class="city">г.&nbsp;Madrid</span>.',
lt73: 'Esto está relacionado con lo que las cadenas de farmacias se negarón ayudarnos a comercializar este remedio, al explicar su nolición con lo que es economicamente desventajoso para ellas. De todos modos, las farmacias son las organizaciones comerciales que están interesadas  más en obtener las  ganancias que sanar  а la población.',
lt74: 'En relación con eso tomamos la decisión de comercializar Hondrocream por medio<a href="">de un sitio web especialmente creado </a>. Sin embargo, trabajar para todo el país a la vez es imposible, por eso decidimos realizar el programa federal por turno en todas las regiones del país. Ahora se está realizando en <span class="city">г.&nbsp;Madrid</span>. Precisamente los habitantes de<span class="city">&nbsp;Madrid</span> hoy pueden comprar el gel a precio ventajoso.',
lt75: 'En adelante vamos a realizar el programa en otras regiones de España.',
lt76: '¿Hasta que fecha se estará realizando el programa en<span class="city">&nbsp;Madrid</span>? ¿Después de esta fecha será imposible comprar Hondrocream en<span class="city">&nbsp;Madrid</span> a precio ventajoso?',
lt77: 'Es completamente cierto. La fecha de finalización del programa federal en<span class="city">&nbsp;Madrid</span>–<span class="date__tomorrow">16&nbsp;septiembre&nbsp;2017</span>. Precisamente hasta esta fecha es necesario <a href="">hacer el pedido en el sitio web</a>. Por eso los que quieren comprar Hondrocream a precio ventajoso de un solo euro y pasar el tratamiento con su ayuda, os recomendamos con insistencia apresuraros.',
lt78: 'En el momento actual Hondrocream fue comprado por unas docenas mil de personas. Diariamente recibimos muchos comentarios positivos sobre este producto, y también las palabras de agradecimiento. Este remedio ayuda a todos.',
lt79: '¡ATENCIÓN!¡Ojo con las falsificaciones! ¡El gel Hondrocream en<span class="city">&nbsp;Madrid</span>se vende solamente en<a href="">EL SITIO WEB OFICIAL DEL PROGRAMA!</a>',
lt80: '—¡Señor Vargas, gracias por la entrevista! ¿Tal vez Ud quiere decir algo a nuestros lectores antes de despedirnos?',
lt81: '— ¡Sí! Si, claro. Quiero señalar a la atención de los lectores que las enfermedades de la espalda y articulaciones “se rejuvenecen”, y hasta los dolores débiles que surgen de vez en cuando es el motivo para prestar la atención al problema. Un médico no va a convenceros que se curéis.',
lt82: 'Y recordad: las enfermedades que surgen por el dolor en la espalda y articulaciones no solamente causan la incomodidad. Acortan la vida en 10-15 años.',
lt83: 'La entrevista fue realizada por Irene Marrero<br> La foto es de fuentes abiertas',
lt84: 'Pasar al sitio web del programa federal',
lt85: '194 comentarios',
lt86: 'Zoe Loriente ',
lt87: 'Compré este gel intentando a deshacerme de los dolores articulares, aunque no creía mucho en el efecto. Pero a mí personalmente me ayudó, por eso ahora es un componente constante y irreemplazable del botiquín doméstico.',
lt88: '15 septiembre del año 2017 - 18:51',
lt89: 'Edith Fernández',
lt90: 'Es un gel perfecto para la curación de las articulaciones. Me ayudó mucho. Recomiendo a todos los que tienen los problemas con las articulaciones. ¡Muchas gracias!!!',
lt91: '15 septiembre del año 2017 - 18:06',
lt92: 'Pedro Garrido',
lt93: '¡Hola a todos! Tengo 68 años. Pedí a mi nieta escribir el comentario. Soy una persona del pueblo, toda la vida estaba trabajando en el campo. Antes trabajabamos sin escatimarnos.  Y al jubilarme el labor se hacía recordar con el dolor articular intenso. Dolían todas  las articulaciones: la lumbasacra, de la cadera, de la rodilla, tibiotarsiana. A veces hasta sollozaba por el dolor, francamente. Hubo un caso, pasé medio día echado en el patio, hasta que llegó mi hija. En el hospital diagnosticaron la artrosis de las articulaciones y prescribieron una crema, que fue completamente inútil, y eso fue todo su tratamiento. Después leí en un boletín médico sobre el gel y pedí a mi nieta pedirlo en internet. Yo mismo no sé hacerlo. Y así empecé a aplicarlo sobre la espalda y los dolores empezaron a pasar poco a poco, y logré andar libremente por la casa. ¡Y en 2 meses del uso del gel las articulaciones dejaron de doler completamente! Gracias al gel volví a tener una vida normal.',
lt94: '15 septiembre del año 2017 - 14:43',
lt95: 'Irene Ayala',
lt96: 'En el trabajo paso todo el día sentada en el sillón y para el final del día mi espalda simplemente “se destroza”, y duelen las articulaciones.  ¡Ya llevo un mes utilizando este gel, el efecto es estupifaciente – al aplicar el gel se siente el efecto refrescante, y un tiempo corto el dolor se calma y puedo volver a moverme normalmente y empezar a ocuparme de los asuntos de casa! Mi espaldita )',
lt97: '15 septiembre del año 2017 - 11:52',
lt98: 'Alejandra Callu',
lt99: 'Los médicos explicaban mis enfermedades con la edad avanzada, y me molestaba. ¿Cómo así? Si me siento joven. Mi vida es mi familia, mi jardín, mis flores, y por la enfermedad se me hizo dificil ir de compras a la tienda cercana. Los dolores en las articulaciones, en la cintura, la hernia discal me hicieron rechazar el estilo de vida habitual. Yo estaba encorvada, y mi postura parecía el signo de interrogación. Mis búsquedas de una salida de esta situación me llevarón a la clínica del doctór Arturo Vargas y su remedio moderno contra el dolor en las articulaciones. Aplicaba el gel sobre la cintura, articulaciones de las rodillas y hacía gimnasia. El resultado – me enderecé, empecé a andar fácil y libremente. Gracias al gel paseo mucho con mi nieta y visito diferentes exposiciones y eventos.',
lt100: '15 septiembre del año 2017 - 11:00',
lt101: 'Sergio Juarez',
lt102: 'Honestamente, primero pensé con escepticismo de este gel. Y sin embargo decidí arriesgarme y usarlo. El resultado me asombró y no me hizo esperar. Me gustó mucho.',
lt103: '15 septiembre del año 2017 - 09:41',
lt104: 'Nicolás Bernalte',
lt105: 'En este verano la podagra me recompensó con los dolores fuertes. Apenas andaba, cojeando. No podía trabajar en el jardín, yo mismo me reprochaba mirando avergonzado como la esposa y la hija hacían el trabajo masculino en la tierra en vez de mí. Hasta dormía separado de mi mujer, tenía miedo que ella durmiendo tocara de casualidad mis pies inflamados. Pronto la podagra apareció más en el dedo índice de la mano derecha, el juante fue de 1,5 cm de tamaño. Trabajo de artista-decorador en una empresa. A pesar de los dolores constantes aguantaba, dibujaba a duras penas, trazaba los esquemas, decoraba los tableros – para que no me despidan solamente. Cuando en el programa federal fue incluida la comunidad de Madrid, llegué a saber de un remedio nuevo, aprobado por el estado. Decidí probarlo. Después de unos días del uso los dolores se redujeron, y más tarde desaparecieron los juanetes. Gracias a Ud ya vivo un mes disfrutando de la vida de antes.  Ahora puedo estrechar la mano a los amigos, recogimos la cosecha junto con toda la familia.  Por las noches duermo abrazando a mi sposa nuevamente.',
lt106: '15 septiembre del año 2017 - 07:38',
lt107: 'Sergio Gomez',
lt108: 'Hace mucho que sufro por el dolor en las articulaciones, sobre todo en tiempo húmedo no me dejan vivir. Probé diferentes parches, pero me ayudó solamente el gel. ¡Lo apliqué una vez, y el dolor empezó a reducirse ya! Ahora lo estoy utilizando regularmente.',
lt109: '15 de septiembre del año 2017 - 06:55',
lt110: 'Rodrigo Viena',
lt111: 'Soy conductor y estoy al volante ocho horas al día, este gel me ayuda mucho a combatir el dolor en la nuca, y también en la cintura.',
lt112: '15 septiembre del año 2017 - 05:55',
lt113: 'Rudolfo Navarro',
lt114: 'Mi esposa desde los años 80 padece la artritis y artrosis, pero los últimos 2 años el dolor estaba presente siempre. Antes no pude imaginarme que una persona puede gritar tanto por el dolor. Fue terrible, sobre todo por las noches, cuando en el silencio completo sonaban los gritos que helaban la sangre. Según sus palabras, el dolor era así como si los perros estubieron mordiendo sus piernas. Y no podía ayudarle en nada, solamente la tomaba de la mano y calmaba. Se inyectaba el analgésico y se dormía, y en un tiempo todo se repetía... Al despertarse por las mañanas la esposa estaba llorando más y más seguido. La sonrisa desapareció de su rostro por completo, como si el sol abandonara nuestra casa para siempre. Se desplazaba con dificultad también – las articulaciones de las rodillas y el hueso sacro no dejaban ni girar. La primera noche después de aplicar el gel pasó sin gritos por primera vez. Y por la mañana la esposa se me acercó alegre y dijo con la sonrisa: “¡Y no hay dolor!” Y el sexto día compré seis cajas más de prevención. Y por primera vez en estos 2 años vi a mi esposa querida feliz y sonriente. Revolea por la casa como una golondrina, los rayos de la vida brillan en sus ojos.',
lt115: '15 septiembre del año 2017 - 03:52',
lt116: 'Luzmila Ortiz',
lt117: 'A un familiar mío después de la apoplejía no le funcionaba el brazo, y los dedos no se le desencorvaban  por el dolor . Compré el gel y le dije: “¡APLICALO!” Claro que es perezoso, pero hasta en unas sesiones sentió mejoramientos. Lo primero, se fueron los dolores en los dedos y él puede desencorvarlos libremente, lo segundo, todo el brazo empezó a moverse normalmente, y el hombro  y codo. Falta poco para la recuperación completa. ',
lt118: '15 septiembre del año 2017 - 01:16',
lt119: 'Angélica  Moiron,',
lt120: 'Este remedio es una salvación para los que saben todo sobre los dolores no de oídas.  Durante un año estaba sufriendo mucho. Las articulaciones en las piernas se me estaban inflamando de vez en cuando hasta no poder yo pisar con los pies, articulaciones tibiotarsianas se hinchaban, aparecían los dolores en la columna vertebral, y este dolor se estaba difundiendo por todo el cuerpo. Los brazos se hincharon, empezaron a entumecerme. El dolor se concentró en el brazo isquierdo, ahí se entumecieron 3 dedos.  Visité al masajista que me salvaba a menudo de las recidivas de la osteocondrosis, pensé que la causa estaba en ella. El masaje no me ayudó – dió las mejoras temporales en unos 10 %, y después de nuevo – los dolores y sufrimientos. La conocida me dió el gel, y resultó ese mismo. El mismo día sentí que los dolores se redujeron. Más pensé que solo me parecía, que era una autosugestión. ¡Pero cuando el tercer día se acabó el ataque de infalmación y dolores, me dí cuenta de que era mi salvación!',
lt121: '15 septiembre del año 2017 - 00:03',
lt122: 'Eugenio Meda',
lt123: 'Hace poco empezaron a doler las articualciones de rodillas. El médico dijo que había que curarlo urgente, prescribió una serie de inyecciones. La esposa me convenció probar este gel. Llevo un mes curandome –  me siento mucho mejor.',
lt124: '14 del septiembre del año 2017 - 22:37',
lt125: 'Marina  López',
lt126: 'Duarante el cambio del tiempo mis huesos empiezan a doler por el frio, tuve que ir al médico, me recomendó este gel. Empecé a utilizarlo como se debe y en dos semanas noté que el tiempo no influía en mí ya y mis artculaciones se sienten bien.  Este gel es bueno, seguiré utilizandolo.',
lt127: '14 septimebre del año 2017 - 18:37',
lt128: 'Alejandro Sánchez ',
lt129: 'En el marzo lesioné mucho la cintura, 2 meses no podía echarme boca arriba. Dormía solamente al poner 6-8 almohadas debajo de la barriga...  En enero pedí este gel, aunque también lo miré con escepticismo . En un mes del uso puedo hacer casi cualesquiera ejercicios acrobáticos .',

lt130: '14 del septiembre del año 2017 - 16:34',
lt131: 'Natalia Torres',
lt132: '¡Y estoy muy contenta! Un año estaba sufriendo por la articualción de la rodilla, los médicos hicieron tantas cosas y al final dijeron que en el futuro se requeriría cambiar las articualciones (tengo la diabetes y la hipertensión maligna y un montón de otras cosas más). Ya no podía caminar sin bastón. Subir la escalera era simplemente insoportable, y aun más difícil era bajar.  Y en esta primavera de casualidad y hasta por una simple curiosidad (porque ya no creo en nada) escribí  en el sitio web y describí mi estado. Me llamaron y preguntaron todo hasta los mínimos detalles y dijeron que estaban seguros de que me ayudaría este gel. Y les creí. Empecé a aplicarlo sobre las rodillas. Primero sentí un alivio el primer día.  Las rodillas funcionan bien, ando sin bastón, no crujen, no me molestan por las noches, aunque no corro por las escaleras, pero si subo sin ayuda por lo menos. No sé si se fueron para siempre los dolores y problemas, PERO HOY EN DÍA estoy contenta  y doblo el espinazo ante los fabricantes de este producto! ¡GRACIAS!!!! ¡No promociono – simplemente estoy alegre!!!',
lt133: '14 septiembre del año 2017 - 15:23',
lt134: 'Lucia Aguilar',
lt135: 'A mí también me dolía la espalda hace mucho. Nada ayudaba. Y después el doctor me recomendó este gel. ¡Y es todo un milagro! ¡Ayudó de verdad!!!',
lt136: '14 septiembre del año 2017 - 13:41',
lt137: 'Ana Alvaro',
lt138: '¡Este producto es excelente! Anestesia en un instante, cuando se aplica sobre la piel se siente su efecto en seguida, huele bien, se absorbe bien, no deja el brillo, y, lo principal, es muy eficaz. Tengo la osteocondrosis del cuello. Una vez apliqué el gel y sentí un alivio, y en 2-3 días olvidé del dolor por completo. ¡Recomiendo a todos!',
lt139: '14 de septiembre del año 2017 - 13:22',
lt140: 'Alejandro  Herrera',
lt141: 'Tengo problemas con la espalda, sufro constantamente. Los conocidos de mi esposa le aconsejaron comprar este gel. Resultó un gel excelente. La espalda dejó de doler en 30 minutos ya. Ahora este gel es mi salvador.',
lt142: '14 septiembre del año 2017 - 12:18',
lt143: 'Daniela Ascanoa',
lt144: '¡Estoy entusiasmada! ¡Cuantos remedios están probados, y este gel me dió el efecto tan esperado! ¡Más no hay dolor, ni limitación en movimientos! ¡Cómo estaba extrañando de la libertad de los movimientos! Voy a comprar para mi marido también.',
lt145: '14 de septiembre del año 2017 - 09:47',
lt146: 'Elena Gonzales',
lt147: 'Tengo 42 años. Hace unos años tuve una gripe muy grave, después de la que me hospitalicé con las complicaciones. Una de las complicaciones fue el proceso de inflamación en las articulaciones, sobre todo en la rodilla. La radiografia mostró los síntomas iniciales de la artrosis de la rodilla. Y yo tenía 39 años en aquel momento. A la hora de andar la rodilla estaba chasqueando, crujiendo, cuando me estaba subiendo la escalera surgían las sensaciones dolorosas. Probé muchas cosas: algo ayudó más, algo menos. Pero solamente este gel satisfizo todas mis exigencias. Logró eliminar los crujidos y el dolor. El último ultarsonido no mostró nada. La verdad que me dan ganas de enseñar el resultado de este ultarsonido a los médicos que dijeron que podía ser peor, y mejor ya no. Tengo a mano este gel  y lo recomiendo a todos. A mí si me salvó, es cierto.',
lt148: '14 septiembre del año 2017 - 06:45',
lt149: 'Andrés Sandoval ',
lt150: 'A mí hace mucho que no me ayuda nada contra el dolor articular. Probé un montón de medicamentos: pastillas, geles, restregamientos. Y todo en vano. Una amiga me recomendó pedir el gel. Pensé que ya no tenía que perder, además el precio no es alto. Me decidí y lo pedí. Literalmente en un mes mis sufrimientos casi se acabaron. Y en un mes más me olvidé del dolor por completo. Lo utilizo regularmente y estoy muy contento.',
lt151: '14 septiembre del año 2017 - 03:51',
lt152: 'Sergio Perez',
lt153: 'Me estaba doliendo el hombro, no podía ni levantar el brazo. Mi colega del trabajo  me prestó un gel, me lo apliqué  sobre el hombro y el dolor se fue en cuarenta minutos. La sensación fue agradable, como si me hubieran puesto un calentador. Hasta me dio sueño, tan bien me sentí. Después me compré uno igual por si acaso, y desde aquel momento lo tengo siempre. En cuanto comience a doler la espalda o el brazo, en seguida aplico el gel y el dolor se va.',
lt154: '14 de septiembre del año 2017 - 02:01',
lt155: 'Pasar al sitio web del programa federal',
lt156: 'Sumario',
lt157: 'Programa federal de lucha contra las enfermedades del aparato locomotor (articulaciones)',
lt158: 'Lista de los ciudades subsidiadas',
lt159: 'Lista de los fármacos subsidiados',
lt160: 'Información sobre las compras para la distribución entre la población',
lt161: 'Orden de la recepción de los pedidos de los fármacos de los ciudadanos de España según el programa federal',
lt162: 'Orden de la recepción de los pedidos de los fármacos subsidiados según el programa federal',
lt163: 'Pasar al sitio web del distribuidor pulsando el botón <img height="14" src="./i_files/icon_button.png">',
lt164: 'En el sitio web del distrubuidor completar los campos: Apellidos, nombre, número de teléfono<img height="26" src="./i_files/icon_anketa.png">',
lt165: 'Esperar la llamada del operdor <img height="20" src="./i_files/icon_operator.png">',
lt166: 'Confirmar el pedido al operdor <img height="26" src="./i_files/icon_ok.png">',
lt167: 'Hacer el pedido',

};
function Translater () {
               for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                 for (key in elements) {
                  elements[key].innerHTML = new_lang[class_name];
                 }
              }
            }
          };