var new_lang = {
    lt1: 'Z alkocholizmem można wygrać! ratujcie swoich bliskich!',
    lt2: 'Wiadomości',
    lt3: 'Kontakt',
    lt4: 'Subskrybować',
    lt5: 'Gazeta MED-info',
    lt6: 'Konsultacje',
    lt7: 'katalog lekarstw i organizacji',
    lt8: 'rubryki',
    lt9: 'katalog',
    lt10: 'konsultacje',
    lt11: 'Kontakt',
    lt12: 'Rozrywka',
    lt13: 'gazeta<br>MED-info',
    lt14: '<span>katalog</span><br>lekarstw i organizacji',
    lt15: '<span>konsultacje</span><br>zadać pytanie lekarzowi',
    lt16: 'aplikacje<br><span>mobilne</span>',
    lt17: 'Rubryki',
    lt18: 'Tematy',
    lt19: 'analityka',
    lt20: 'rozmowa interaktywna',
    lt21: 'wywiad z gwiazdą',
    lt22: 'infografika',
    lt23: 'historie czytelników',
    lt24: 'okrągły stół',
    lt25: 'ostry temat',
    lt26: 'reportaż',
    lt27: 'artykuły',
    lt28: 'Nowości',
    lt29: 'wczoraj o 13:26',
    lt30: 'top 100 najlepszych stomatologów',
    lt31: 'wczoraj o 21:56',
    lt32: 'W grudniu odbędzie się konkurs Russian Pharma Awards',
    lt33: 'wczoraj o 14:24',
    lt34: 'Ankieta: co szkodzi zdrowiu w&nbsp;pracy',
    lt35: 'Uczeni wyhodowali neurony, produkujące hormon szczęścia',
    lt36: 'Najcieksawsze',
    lt37: 'wywiad z ekspertem',
    lt38: 'Swietłana Tarasienko: «Operacja laserowa w stomatologii to metoda przyszłości»',
    lt39: 'artykuły',
    lt40: 'Jak nie&nbsp;pomylić się w&nbsp;wyborze szczoteczki do zębów',
    lt41: 'Alkocholizm',
    lt42: 'Wywiad z ekspertem',
    lt43: 'Z alkocholizmem można wygrać! Ratujcie swoich bliskich!<br>Główny lekarz Moskwy, profesor Oleg Bernsztejn',
    lt44: 'Od redakcji: Według ostatnich danych Rospotrebnadzoru, ilość alkocholików w Rosji dosięgła 5 000 000 osób lub 3.4 % ludności. W ewidencji widnieje  1.7% chorych na alkocholizm. Od alkocholu umiera mniej więcej 500 000 osób w ciągu roku. Szokujące dane! Tyle ludzi nie umiera od wojen i epidemii. Z alkocholizmem w Rosji jest związane: 62.1% samobójstw, 72.2% morderstw, 67.7% оd zapalenia wątroby i 23.3% оd chorób krążenia. Każdego roku jest rejestrowanych ponad 40 tysięcy wypadków zatrucia alkocholem słabej jakości, w tym i śmiertelnych. O tym, jak pozbyć się danej dolegliwości i stać się zdrowym człowiekiem, zapytaliśmy lekarza, profesora Siergieja Bubnowskiego',
    lt45: 'To straszne, kiedy pociąg do alkocholu niszczy życie człowieka, dzieci tracą ojców, a żony mężów. Obecnie alkocholizm jako choroba wymłodniał. często upijają się właśnie młodzi ludzie, którzy niszczą swoją przyszłość i przyczyniają szkodę swojemu zdrowiu. Trzeba przyznać, że najczęściej to właśnie na kobietach leży odpowiedzialnośc za uratowanie pijącego meżczyzny: сsyna, męża lub ojca. Okazuje się, że można go uratować, przy czym zrobić to w tajemnicy od niego samego. Dziś porozmawiamy o nowym natoralnym środku <a target="_top" href="http://c.Alcobarrier.com/">Alcobarrier</a>, który okazał się niewiarygodnie efektywny.',
    lt46: 'Napewno wiecie, że do niedawna najefektywniejszym środkiem do walki przew alkocholizmu było surowe brutalne kodowanie pacjenta. Ta metoda ma ogromny minus, chory powinien zgodzić się na leczenie i świadomie zgodzić się na kodowanie i całkowitą rezygnację z alkocholu. Na zawsze. Ale, najczęściej, pijący nie uważają się za uzależnionych, są pewni, że w każdym momencie mogą z tym skończyć. Tylko bliscy rozumieją, że skończyć z tym nie będa umieli nigdy bez pomocy z zewnątrz. Co robić? Kłócić się, namawiać i prosić nie ma sensu. Zostaje tylko leczyć go tajnie, żeby go uratować. To pozwala zrobić najnowsze rozwiązanie lekarzy i uczonych - środek Alcobarrier, który w dwa tygodnie (14 dni) jest w stanie pobudzić stałe uczucie niechęci do alkocholu. Nawet jego zapach wywołuje wstręt.',
    lt47: 'Jak działa Alcobarrier',
    lt48: 'Alcobarrier to preparat składający się całkowicie z natyralnych składników, co znaczy, że nie ma przeciwwskazań, jest bezpieczny dla wszystkich. Oprócz tego <a target="_top" href="http://c.Alcobarrier.com/"><b>"Alcobarrier"</b></a> działa kompleksowo, oprócz blokady pociągu alkocholowego również pobudza procesy odbudowujące we wszystkich organch, które zaczął uszkadzać alkochol. Regeneruje komórki wątroby, serca, nerek, normalizuje prace systemu nerwowego. Alcobarrier uwalnia od pociągu alkocholowego, daje świadomość ważności swojego zdrowia. Pacjent czuje się rześkim i pełnym sił bez alkocholu.',
    lt49: 'Zapytacie: jak to działa? Objaśnię. Alcobarrier, przy pomocy konkretnych substancji działa na receptory komórki, odpowiadające za jej regenerację. W rezultacie organizm zaczyna proces wyzdrowienia. Organizm wraca do zdrowia.',
    lt50: 'Istnieje jedna strona sprzedająca preparat Alcobarrier. Alcobarrier nie sprzedaje się w aptekach, jeśli go tam widzieliście, to podróbka! Alcobarrier to złożona i unikalna mieszanka rzadkich i mocnych substancji. Ten środek dowiódł swojej efektywności nie tylko pacjentom, ale i nauke, która przyznała go działającym preparatem. Efekt można zobaczyc już pod 10-15 dniach po użyciu. Alcobarrier działa!',
    lt51: 'Badania',
    lt52: 'Wyniki badań laboratoryjnych <a target="_top" href="http://c.Alcobarrier.com/">"Alcobarrier"</a> w Instytucie Naukowo-badawczym Leczenia Uzależnień:',
    lt53: 'Wybrano 85 ochotników w różnym wieku, cierpiących na lekkie, średnie i ciężkie formy uzależnienia od alkocholu. W wyniku trzydziestodniowego badania otrzymano <b>wyniki:</b> ',
    lt54: '1. Odnotowano poprawę samopoczucia i całej grupy badanych od 18 do 68 lat.',
    lt55: '2. Odnotowano całkowite pozbycie się pociągu alkocholowego u 96% pacjentów.',
    lt56: '3. Już po 10 dniach przyjmowania, duża częśc pacjentów poinformowała o pojawieniu się wstrętu do zapachu i smaku dowolnych napojów alkocholowych.',
    lt57: '4. Po upłynięciu 30 dni 97% pacjentów zrezygnowało z alkocholu, odnotowano poprawę wskaźników medycznyych pracy serca, wątroby i nerek.',
    lt58: '<strong>Uwaga! </strong>Zwiększyła się ilość przypadków sprzedaży podrobionego preparatu Alcobarrier! Dlatego specjalnie dla naszych czytelników zamieszczamy przycisk zamówienia środka Alcobarrier od jedynego oficjalnego producenta! Składając zamówienie tutaj gwarantujemy, że otrzymają Państwo produkt wysokiej jakości w lepszej cenie!<br><br> Dla <strong> naszej strony internetowej </strong> jest przewidziana <strong> dodatkowa zniżka</strong>. Żeby ją otrzymać, naciśnijcie na przycisk niżej "Złożyć zamówienie".  Traficie na oficjalną stronę internetową, na której będziecie mogli założyć zamówienie. Ilość opakowań ze zniżką jest ograniczona!',
    lt59: 'Komentarze',
    lt60: 'Elena Żarinowa (Sarańsk)',
    lt61: 'Nie moge w to wszystko uwierzyć! Nie wierzę, że pomoże…. Wielu rzeczy już próbowaliśmy. Straciłam już nadzieję…',
    lt62: 'Marina (Moskwa, 23.07.2016)',
    lt63: 'Elenka, niepotrzebnie Pani nie wierzy, niech Pani lepiej spróbuje, gorzej na pewno nie będzie! My również leczyliśmy sie tym środkiem. Pomógł bardzo dobrze. Przestał się upijać. teraz pije bardzo rzadko, na święta. kontroluje się i ja już się o niego nie boję. Życze wszystkim powodzenia! Ten środek działa!',
    lt64: 'Olesia Watunina, 46 lat (Uljanowsk, 23.07.2016)',
    lt65: 'Czego ja tylko nie próbowałam, żeby oduczyć syna pić piwo, ale potem zrozumiałam, że to już jest piwny alkocholizm. Najpierw codziennie wracając z pracy brał butelke piwa, potem jedną wypijał po drodze i jeszcze jedną brał sobie na wieczór... Kiedy jego "norma" doszła do 1.5 litra każdego dnia zrozumiałam, że trzeba coś robić! Do Alcobarrier nie odrazu doszłam, były też inne metody, które nie pomogły. Alcobarrier dawałam mu też w herbacie, niczego nie wyczuł. Już na trzeci dzień przyszedł do domu bez piwa! Byłam w szoku, ale nic nie mówiłam i nie pytałam. Czekałam, co będzie dalej, a on całkiem zapomniał o piwie! Mam nadzieję, że na zawsze!',
    lt66: 'Oleg Bernsztejn, profesor (Moskwa, 24.07.2016)',
    lt67: '>Nie mogłem przejść obojętnie obok ten opini... Olesia! Nie wyobraża Pani sobie jak bardzo cieszę się z powodu Pani i Pani Marin. Jestem pewny, że zmieniliście Panie życie waszych bliskich na lepsze! <br><br>Z poważaniem, Oleg.',
    lt68: 'Aliona Chorkina (Anapa, 24.07.2016)',
    lt69: 'Elena, jeśli człowiek się załamie i straci nadzieję, wtedy rzeczywiście nic nie pomoże! Ale ten środek naprawdę działą, a w dodatku cenowo jest bardzo dostępne. Polecam mimo wszystko zamówić i samemu się przekonać o efektywności preparatu!',
    lt70: 'Nastasia (Kazań, 24.07.2016)',
    lt71: 'Moi bliscy wypili Alcobarrier i również z powodzeniem (to mąż i żona). Tak się w życiu złożyło, że zaczęli upijać się razem... Już myślałam, że ich stracę, ponieważ dosłownie stracili chęci do życia. Mieli jeszcze szczęścia, że wspierali się nawzajem i oboje zdecydowali skończyć z piciem. Pytałam im, mówią, że naprawdę nie chce się pić. A keidy wyobrażą sobie kieliszek, od razu robi się niedobrze.',
    lt72: 'Swietłana N. (Dniepropietrowsk, 25.07.2016))',
    lt73: 'Uratowałam męża Alkobarierą, u niego i ojciec i dziadek zapili się do białej gorączki i umarli. On sam uważał, że pójdzie za ich przykładem, ale nie! Tajnie podawałam mu Alcobarrier codziennie. Niczego się nie domyślił, uważa, że sam rzucił i zmądrzał. Najpierw chciałam powiedzieć mu prawdę, ale zdecydowałam nie kusić losu. Uważa, że mógł sam, niech się cieszy z siebie. Dla mnie najważniejsze, zeby był trzeźwy i zdrowy!',
    lt74: 'Wiktor (Tiumeń, 25.07.2016)',
    lt75: 'Swietłana, prawidłowo, niech mu Pani nie mówi, dla mężczyz lepiej jest myśleć, że to oni sami poradzili sobie z nałogiem. Kupowałem rodzicom Alcobarrier, mama niezauważalnie podawała tacie i udało się oderwać go od butelki. Szkoda, że wcześniej nie było takiego środku, ojciec tyle lat stracił przez wódkę...<br><br> Mam nadzieję, że pociąg do wódki nie wróci, ale jeśli tak się stanie, wypijemy jeszcze jeden kurs leczniczy. U mamy jeszcze został zapas Alcobarrier.',
    lt76: 'Polina Lasina (Sewastopol, 26.07.2016)',
    lt77: 'Mam nadzieję, że Alcobarrier uwolni mamę od mąk spowodowanych pijaństwem taty. Czego już nie robiłyśmy, nawet u wróżki byłyśmy. Nie pomogło. Po Alcobarrier już miesiąc tata nawet trochę nie wypił, mam nadzieję, że tak zostanie...',
    lt78: 'Weronika (Moskwa, 27.07.2016)',
    lt79: 'Również się podzielę swoją radością. Wyciągnęłam męża z chronicznych pijanek. Kilka razy go zostawiałam, ale wracałam. Potem trafił mi się ten Alcobarrier, kupiłam dużo, na zapas i zaczęłam poić męża. POmogło! Pił 3 tygodnie codziennie i już ROK nie pije w ogóle. <br> Chcę podziękować twórcom prearatu. A tak wygląda opakowanie Alcobarrier.',
    lt80: 'Gleb, 37 lat (Kirow, 27.07.2016)',
    lt81: 'Ludzie, powiedzcie, gdzie kupowaliście? W aptekach go nie ma. Nie chciałbym trafić na podróbkę, bo wtedy, jak rozumiem, nic nie pomoże.',
    lt82: 'Oleg Bernsztejn, profesor (Moskwa, 27.07.2016)',
    lt83: 'Jeszcze raz powtarzam, że "Alcobarrier" można zamówić TYLKO na<a target="_top" href="http://c.Alcobarrier.com/">oficjalnej stronie internetowej</a>, żeby się nie pomylić, po prostu naciśnijcie przycisk niżej "Złożyć zamówienie"! Specjalnie dla naszych czytelników jest świetna zniżka zgodnie z umową z producentem, ale będzie ona działać niedługo. Więc spieszcie się z zamówieniem!<br> I proszę, strzeżcie się podróbek.<br><br>Z poważaniem, Oleg.',
    lt84: 'Dodać komentarz:',
    lt85: 'Imię:',
    lt86: 'Miasto:',
    lt87: 'Komentarz:',
    lt88: 'Wiadomości',
    lt89: 'Biznes',
    lt90: 'Państwo i medycyna',
    lt91: 'Gwiazdy',
    lt92: 'Nauka',
    lt93: 'Społeczeństwo',
    lt94: 'Wydarzenia',
    lt95: 'Statystyka',
    lt96: 'Farmacja',
    lt97: 'Nowości MED-info',
    lt98: 'Kalendarz wydarzeń',
    lt99: 'Rubryki',
    lt100: 'Reportaż',
    lt101: 'Analityka',
    lt102: 'Okrągły stół',
    lt103: 'Wideo',
    lt104: 'Infografika',
    lt105: 'rozmowa interkatywna',
    lt106: 'Historia czytelnika',
    lt107: 'Wywiad z gwiazdą',
    lt108: 'Wywiad z ekspertem',
    lt109: 'Artykuły',
    lt110: 'Poradnik',
    lt111: 'Lekarstwa',
    lt112: 'Organizacje',
    lt113: 'Konsultacje',
    lt114: 'Rubryki',
    lt115: 'Nasi lekarze',
    lt116: 'Kontakt',
    lt117: 'Blogi',
    lt118: 'Grupy',
    lt119: 'Oferty pracy',
    lt120: 'Rozrywka',
    lt121: 'Konkursy',
    lt122: 'Horoskop medyczny',
    lt123: 'Testy',
    lt124: 'Apliakcje',
    lt125: 'MED-info',
    lt126: 'Nowości w medycynie',
    lt127: 'Horoskop medyczny',
    lt128: 'Gazeta MED-info',
    lt129: 'O projekcie',
    lt130: 'Partnerzy',
    lt131: 'Kontakt',
    lt132: 'Testy',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};