var new_lang = {
    lt1: 'Pagrindinis',
    lt2: 'Blogai',
    lt3: 'Atjaunėjimas',
    lt4: 'Komentarų: 15',
    lt5: 'Tekstas: <a href="" rel="author">Arlauskaite</a>',
    lt6: 'Be jokio botokso - minus 15 metų garantuota',
    lt7: '<strong>Laura Šustickaitė<br>Konkurso laimėtoja:</strong> «Gyvenimo istorijos apie tai, kaip tapti gražia».',
    lt8: 'Sveiki, mano mielieji skaitytojai. Noriu papasakoti savo istoriją, kaip galima ieškoti grožio už trijų marių, o galiausiai rasti jį namuose.',
    lt9: 'Susipažinkime. Aš Laura Šustickaitė, man 47 metai, gyvenu Kaune.',
    lt10: 'O dabar ir pati istorija',
    lt11: 'Kartą, vieną gražų rytą aš pažiūrėjau į save veidrodyje ir apsiverkiau. Gilios raukšlės ant kaktos, tiesiog didžiulės nosies-lūpų raukšlės, maišeliai po akimis, kažkokie odos nelygumai – jau ateina šaltas pilkas ruduo, o jug dar taip norisi šilumos ir šviesos. Kažkaip iš karto prisiminiau vienos moters pasakojimą apie tai, kaip jai puikiai pavyko atjauninti veidą Tuniso spa salonuose. Kad ten, buvusioje Prancūzijos kolonijoje, dirba daug patyrusių kosmetologų iš Prancūzijos, naudodami Prancūzijos gamybos priemones. Išeina, kad niekuo blogiau, nei pačioje Prancūzijoje, tik 2-3 kartus pigiau. Todėl spa kelionės į Tunisą yra labai populiarios visame pasaulyje ir Prancūzijoje taip pat :-)',
    lt12: '«Negi aš nenusipelniau būti graži?! – pagalvojau aš ir pradėjau domėtis kelionėmis į Tunisą. Man smarkiai pasisekė. Pačioje pirmoje kelionių agentūroje man buvo pasiūlyta paskutinės minutės kelionė su 50% nuolaida! Žodžiu, po dviejų dienų aš jau buvau Hamameto kurorte, didžiausiame spa centre Bio Azur. Vietiniai meistrai iš karto ėmėsi mano veido ir kūno. Apie visokius dumblių ir purvo įvyniojimus, bei hidromasažines vonias nepasakosiu. Ne apie tai kalba. Papasakosiu, ką jie darė su mano veidu.',
    lt13: 'Buvo skirtas 12 dienų kursas. Iš pradžių daroma veido nuotrauka, kad vėliau pacientas galėtų akivaizdžiai pamatyti skirtumus. Toliau manęs laukė prabangi kosmetologinė kėdė. Atsisėdi ir pamiršti apie viską. Tyliai groja muzika, užuodžiami malonus aromatai, o moteris švelniais masažuojančiais judesiais tepa veidą skaniai kvepiančiu kremu. Visos procedūros trukmė buvo apie 15-20 minučių. Ir taip visas 12 dienų. Pabaigoje vėl padarė nuotrauką. Štai, galite patys įvertinti rezultatą.',
    lt14: 'Maišeliai po akimis, nosies-lūpų raukšlės bei kitos tiesiog ištirpo! O kartu su jais netekau kokių 15 metų! Buvau šokiruota ir tuo pačiu labai laiminga! Mano kosmetologė, kuri jau per tiek metų priprato prie klykiančių iš laimės pacientų, tik mielai nusišypsojo. Be to aš įsiminiau šio efektyvaus kremo-kaukės pavadinimą. <a href="">COLLAMASK</a> – toks jos pavadinimas!',
    lt15: 'Žinoma, kai grįžau į Kauną, mano draugės buvo pakerėtos ir užversdavo mane klausimais! Aš visiems sąžiningai atsakydavau, o pati buvau… nusiminusi. Džiūgaudama dėl savo veido naujos išvaizdos, aš pastebėjau liūdną mano mamos žvilgsnį. Ir iš karto viską supratau. Moteris lieka moterimi bet kokiame amžiuje. Ir bet kokiame amžiuje ji nori buti graži. Bet išsiųsti 71 metų moterį į Tunisą buvo tiesiog nerealu. Aš ieškojau šios kaukės parduotuvėse – nieks net negirdėjo apie ją…',
    lt16: 'Pasirodo, šį kremą-kaukę galima užsisakyti ir pas mus',
    lt17: 'Praėjo pusė metų. Ir netikėtai pamačiau Internete pažįstamą pavadinimą – COLLAMASK! Skaitau, lyg viskas tas pats. Tik pakuotė ne tokia, kokią aš mačiau Tunise. Ir kaina daug prieinamesnė. Ar Tunise tiek daug kainuoja paslaugos? Žodžiu, dvejonės nors ir buvo, bet aš vis tiek padariau užsakymą! Jau kas-kas, o aš tai tikrai žinau kaip kaukė atrodo ir veikia! Jeigu tai <a href="">tikras COLLAMASK</a>, tada aš nieko neprarasiu, o tik laimėsiu!',
    lt18: 'Siuntinį gavau po 5 dienų. Ir aš iš karto pradėjau bandyti ant mamos. Juolab aš žinojau, ką turiu daryti. Žinoma, be kosmetologinės kėdės, muzikos ir aromaterapijos. Bet COLLAMASK suveikė ir taip. Per 12 dienų mano mama pajaunėjo 15 metų. Diena – už metus!!',
    lt19: 'Štai, rodau savo pastangų rezultatą:',
    lt20: 'Aš iš karto užsisakiau dar 6 tūbeles – sau, mamai ir draugei. Tegul būna! Nes dar nieko geresnio veido odai aš neturėjau. Ir rezultatas greitas. Puiku!',
    lt21: 'Tokia vat mano istorija. Tikiuosi, kad mano patirtis bus naudinga daugumai. Juk moteris bet kokiame amžiuje turi būti graži!',
    lt22: 'COLLAMASK',
    lt23: 'Pereiti į svetainę COLLAMASK',
    lt24: 'Pagarbiai, Laura Šustickaitė',
    lt25: 'Palikite savo balsą:',
    lt26: 'Įdomybės nuo mūsų partnerių',
    lt27: 'Netradiciniai lieknėjimo metodai',
    lt28: 'Voločkova pranešė, kad išeina į vienuolyną',
    lt29: 'Reklama ir vitaminai — kur tiesa?',
    lt30: 'Kakava gerina atmintį',
    lt31: 'Vitaminas D išgelbės nuo senatvinės silpnaprotystės',
    lt32: 'Iš viso komentarų: 15',
    lt33: 'Komentarai',
    lt34: 'Kad galėtumėte palikti komentarą, būtina <a href="">užsiregistruoti</a>',
    lt35: 'Vitale Kleveckaite',
    lt36: '71 metai? Netikiu)) Bet kaukę užsisakysiu. Ar matėte jos sudėtį svetainėje? Tiesiog superinė))',
    lt37: 'Justina Maciukenaite',
    lt38: 'COLLAMASK nerealiai geras! Tapo labai populiarus per pastarąjį pusmetį.',
    lt39: 'Kristina Pranckūnaitė',
    lt40: 'Negi kažką gero sukūrė? Atsibodo švaistyti pinigus perkant visiškai nenaudingas priemones. Jei tikrai veikianti, būtinai užsisakysiu.',
    lt41: 'Rasa Baltramaitienė',
    lt42: 'Pritariu! Labai efektyvi jauninanti priemonė! Mažos raukšlelės visiškai dingsta.',
    lt43: 'Jurgita Ausrotaite',
    lt44: 'ačiū už nuotraukas! Puikus rezultatas! Mergaitės, rašykite dar apie savo rezultatus! Labai įdomu.',
    lt45: 'Jovita Dirsienė',
    lt46: 'Aš irgi tokių parduotuvėse nemačiau….Turbūt rimtai <a href=""><strong>tik šioje </strong></a> svetainėje galima užsisakyti.',
    lt47: 'Brigita Sitkauskiene',
    lt48: 'Per 3 kursus aš visiškai atsikračiau raukšlių, net nuo pačių giliausių. Tiesiog pasaka! Labai laiku aš radau jūsų blogą. Ačiū!',
    lt49: 'Laura Lauryciuke',
    lt50: 'Tai nuostabu! ) Aš pati iš tikrųjų visai netyčia atradau šią kaukę. Tokius dalykus reikia būtinai pasakoti ir kitiems!',
    lt51: 'Giedre Maciene',
    lt52: 'Nuostabi moteris! Aš budama 30-ties blogiau atrodau :(( Viskas, tikrai imsiu.',
    lt53: 'Jurgita Klimaitė-Rudaitienė',
    lt54: 'Mūsų Lietuvos elitas tuoj greitai viską užuos. Reikia užsakynėti, kol dar yra. Nes maža kas)',
    lt55: 'Lina Jančiuvienė',
    lt56: 'COLLAMASK, mergaitės, ne tik šalina raukšles, bet ir patinimus. Pas mane buvo tokie baisūs patinimai po akim, o dabar nėra. Netikiu savo laime.',
    lt57: 'Laura Šustickaitė',
    lt58: 'Puikiai matomas efektas! Nuostabus rezultatas! Ačiū už jūsų atsiliepimą)))',
    lt59: 'Vaida Viluckienė',
    lt60: 'Aš jau girdėjau apie COLLAMASK, bet nežinojau, kur užsisakyti. Ačiū,kad pasakėt!',
    lt61: 'Donata Berūkštienė',
    lt62: 'Jau užsisakiau! Valio valio…',
    lt63: 'Kristina Maslauskaite',
    lt64: 'O man vyras gimtadieniui padovanojo)) Pasakė, kad dabar busiu pati gražiausia)) Ir ką jūs galvojate? Taip ir įvyko:)',
    lt65: 'Kamilė Karkauskaitė',
    lt66: 'Nusipirkau, kaukė patiko! Naudojau 2 mėnesius. Tikrai ši kaukė jaunina veido odą!!! Žiūrėkit rezultatą',
    lt67: 'Išbandyti COLLAMASK<br>dabar'
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};