var new_lang = {

 
    "lt14": "Contact",
    "lt0": "Home",
    "lt1": "Sobre",
    "lt2": "Loja",
    "lt3": "Blog",
    "lt4": "Imprensa",
    "lt5": "Fases do amor <span class=\"sf-sub-indicator\">»</span>",
    "lt6": "Por que muitos param na fase três",
    "lt7": "Fases do casamento",
    "lt8": "Salve seu casamento de meia-idade",
    "lt9": "Raiva masculina <span class=\"sf-sub-indicator\">»</span>",
    "lt10": "Por que meu marido está tão bravo?",
    "lt11": "Por que os homens se tornam violentos",
    "lt12": "Teste da Síndrome do Homem Irritável (IMS)",
    "lt13": "Por que meu marido é tão mau comigo?",
    "lt14": "Contato",
    "lt15": "Um método que substituirá a operação para remover o adenoma da próstata em um futuro próximo (e que eu já experimentei em mim mesmo)",
    "lt17": "Olá! Meu nome é Marco, sou o editor do jornal. Quero contar a minha história sobre como me livrei da prostatite. O que me ajudou não foi antibiótico, nem a cirurgia, nem a massagem da próstata, mas sim o remédio mais (aparentemente) comum",
    "lt18": "Prostatite e como ela é tratada em nosso país",
    "lt19": "Eu trabalho sentado à mesa. Gosto do ar fresco do meu escritório e abro as janelas com frequência. Um dia eu me esqueci de fechar as janelas, estava trabalhando e em algum momento percebi que senti uma sensação de queimação abaixo do umbigo. Pensei que congelei a parte inferior das costas e que a dor desapareceria sozinha. Em uma semana eu comecei a sentir dor ao urinar, em duas - sentar por um longo tempo, e depois das três comecei a ter problemas com ereção e ejaculação. ",
    "lt20": "Fui ao médico, fiz os exames. Vim para uma consulta de retorno e o médico me falou: Você tem um tumor benigno, vamos fazer uma cirurgia para removê-lo.",
    "lt21": "Fiquei em choque. Pela primeira vez na minha vida eu não sabia o que fazer. Uma cirurgia de remoção da próstata é a última coisa que qualquer homem gostaria de experimentar.",
    "lt22": "No dia marcado, eu estava tenso. Tentei não pensar no que aconteceria, mas não consegui me livrar do pensamento de que a cirurgia estava ocorrendo sem anestesia.",
    "lt29": "Самым большим шоком для меня стало то, что <b>простатит может возникнуть снова, даже после операции</b>. В голове был какой-то туман, непонятно, что делать. Идти на повторную операцию? Сколько я так буду “лечиться”? Если рецидив случился однажды, то где гарантия, что он не произойдет после второй, третьей, восьмой, двадцатой операции?",
    "lt23": "Quando me deitei na mesa de cirurgia, senti uma dor cortante na virilha, como se alguém estivesse me cortando vivo com uma serra elétrica. Eles inseriram uma agulha elétrica na minha uretra e começaram a remover o tumor na próstata com microfacas. Dava pra aguentar, mas foi terrivelmente doloroso",
    "lt24": "O período de recuperação durou cerca de uma semana e pareciam duas eternidades. Todo esse tempo eu tomava antibióticos, quase não saí da cama, e o pênis estava doendo muito. Eu me senti esmagado.",
    "lt25": "Quanto mais o tempo passava desde o momento da cirurgia, pior estava meu estado moral. A imunidade diminuiu muito devido a antibióticos, fazer xixi e fazer sexo era desagradável e às vezes até doloroso.",
    "lt26": "Algo com o que eu não contei",
    "lt27": "Uma vez que voltei da piscina e senti uma sensação de queimação familiar novamente. Entendi que algo estava errado comigo, mas eu esperava ter apenas uma inflamação simples. Vou tomar remédios e antibióticos e me tornarei novo." ,
    "lt28": "Só que não.<b>O médico novamente viu a inflamação da próstata</b>. Estou em pânico, à beira da histeria, fora de mim mesmo gritando com o médico quase obscenamente: Você tirou tudo seis meses atrás! Como é possível que a prostatite esteja de volta?!",
    "lt29": "O maior choque para mim foi que <b> prostatite pode ocorrer novamente, mesmo após a cirurgia</b>. Havia algum tipo de neblina na minha cabeça, não estava claro o que fazer. Tenho que passar por uma segunda cirurgia? Quantas cirurgias então devo fazer? 'Quantas vezes eu terei que ser 'tratado' desse jeito? Se a recaída ocorreu uma vez, onde está a garantia de que não ocorrerá após a segunda, terceira, oitava e vigésima operação?",
    "lt30": "Em estado de agonia, comecei a procurar informações científicas sobre prostatite. Vasculhei muitas coisas: de livros didáticos para estudantes de faculdades médicas a palestras para proctologistas praticantes.",
    "lt31": "Depois de ouvir as palestras de um professor, soube que ele era um médico praticante com grande experiência e decidi marcar uma consulta com ele. Só consegui marcar a consulta em um mês e meio. Pensei que era melhor que nada, e marquei.",
    "lt32": "Para minha própria segurança, comecei a procurar opiniões sobre esse médico. A maior parte delas eram opiniões boas, mas havia também algumas opiniões negativas. Fiquei mais surpreso com o comentário de um de seus pacientes, cito literalmente:",
    "lt33": "Eu vim de outra cidade com PROSTATITE CRÔNICA para consultar um médico, e ele me prescreveu o ProstEro feito de alguma erva que você só pode pedir na Internet ou comprar com ele! Isso é normal? Se você for nesse médico não conte com tratamento adequado.",
    "lt34": "O administrador do site respondeu a este comentário com muita calma. Algo como 'envie sua reclamação e nós a responderemos'",
    "lt35": "É claro que essas informações me deixaram fortemente passado. Se mesmo uma pessoa tão famosa não dá a mínima para seus pacientes, então como deveríamos viver neste mundo?",
    "lt36": "Experiência arriscada",
    "lt37": "Depois de me acalmar um pouco, tive a boa ideia de descobrir que tipo de medicamento o professor prescreve para seus pacientes. Comecei a procurar pelas opiniões médicas sobre ele, estudei a composição em detalhes e até encontrei os resultados de ensaios clínicos em voluntários.",
    "lt38": "Ervas, como disse um comentarista zangado, em ProstEro não é apenas um kit de uma farmácia. Os principais ingredientes ativos são a ameixa africana, saw palmetto e zinco que você não pode simplesmente comprar em uma farmácia. É em primeiro lugar.",
    "lt39": "Em segundo lugar, são substâncias muito poderosas de origem vegetal que interrompem a inflamação e ajudam a se livrar da prostatite para sempre.",
    "lt40": "Em terceiro lugar, são produzidas por extração a frio, a fim de preservar o máximo de nutrientes em sua forma original e na maior concentração.",
    "lt41": "Esse conjunto em combinação com vitaminas tem um efeito muito favorável no sistema geniturinário, na ereção e na saúde da próstata. As informações são impressionantes, os resultados da pesquisa e as declarações dos médicos também. Eles falaram que <a href=\"#\"> o ProstEro </ a> trata a prostatite mesmo em casos avançados. É um concorrente verdadeiro de antibióticos e até de cirurgia, sem mencionar medidas preventivas. ",
    "lt42": "As dúvidas e o espírito aventureiro lutaram dentro de mim. O primeiro insistiu que tudo isso fosse ficção, o segundo insistiu que eu me arriscasse. E eu arrisquei quando estava convencido de que não teria nenhum efeito colateral e eu não me tornaria um sapo. No pior das hipóteses, eu perderia apenas dinheiro, e seria apenas pouco. ",
    "lt43": "Fiz um pedido no site, o consultor me ligou de volta e respondeu a todas as minhas dúvidas. Após essa conversa eu me animei e senti com meu órgão dolorido que tomei uma decisão certa.",
    "lt44": "As primeiras melhorias eu notei após alguns dias de uso do<a href=\"#\"> ProstEro </a>. <b> A dor ao urinar desapareceu, o desejo noturno de ir ao banheiro sumiu</b>. O desejo sexual começou a surgir, <b> a ereção retornou totalmente </b>. Não houve problemas com o sexo.",
    "lt45": "<b> Depois a situação apenas estava melhorando cada vez mais</b>. Fiquei mais alegre, comecei a dormir melhor, até minha imunidade ficou mais forte.",
    "Lt46": "Apesar disso, o medo de cirurgia me mandou que eu fosse submetido a todo o curso do tratamento, como deveria, então eu religiosamente tomei todas as cápsulas. A essa altura, chegou a hora daquela consulta com um médico, que eu havia marcado no mês passado. ",
    "lt47": "Decidi não cancelar a visita, porque já havia feito um pagamento adiantado. E sim, queria ouvir a opinião de um especialista em primeira mão.",
    "lt48": "Visita ao médico",
    "lt49": "Durante a consulta, contei ao professor sobre o meu problema, entreguei os exames, que realizei antes na minha cidade, e me preparei para esperar pelo o pior. O médico franziu a testa e me pediu para deitar no sofá para iniciar o exame.",
    "lt50": "O exame usual durou surpreendentemente muito tempo, eu estava preocupado, será que eu já estou com  já câncer de adenoma de próstata? Após o exame, o professor juntou minhas análises em um arquivo e falou: 'E quem falou que você estava com o adenoma? Não observo nenhum desvio, os exames são perfeitos, a próstata é normal.' ",
    "lt51": "A pedra caiu da minha alma. Exalei e contei tudo ao médico sobre minhas 'aventuras': contei sobre a cirurgia, recaída e que eu resolvi tomar o ProstEro por conta própria.",
    "lt52": "Em vez de falar que não valia a pena tomar nada sem indicação, o médico falou  inesperadamente: 'Finalmente, meus pacientes começaram a pensar com a cabeça, e não com o lugar que dói. Você fez tudo certo. Na verdade, é por isso que a próstata ficou curada. ",
    "lt53": "<b> ProstEro </b> é um medicamento muito bom. Ainda não está disponível nas farmácias, mas é uma questão de tempo. Após 3-4 meses ele estará lá, apenas irá custar mais caro. Muitos pacientes estão céticos sobre meus métodos de tratamento. Somente quando eles se dobram devido à dor, eles começam a agir. E então eles vêm com olhos culpados, eles me agradecem. Tipo, eles deveriam ter me ouvido imediatamente.",
    "lt54": "Faz um ano e meio desde que fiz aquela consulta com o médico. Vivo uma vida plena e não tenho a mesma doença. A imunidade é recuperada, e a minha vida sexual é ideal.<b>Não haveria felicidade sem infelicidade</b> . ",
    "lt55": "Onde obter ProstEro",
    "lt56": "A ideia de contar uma história tão íntima surgiu quando me lembrei de quantos homens eu encontrei nos fóruns. Existem milhares, senão milhões, daqueles que confiam humildemente no médico e que não têm condição financeira para consultar com os profissionais verdadeiros. ",
    "lt57": "Sei que o problema é extremamente delicado, você não pede conselhos a um amigo, nem usa qualquer coisa para se tratar. Portanto, decidi compartilhar minha história com o público.",
    "lt58": "Se submeter para uma cirurgia, tomar antibióticos ou tomar ProstEro fica a seu critério. Para aqueles que decidirem fazer o último, deixarei um link do site do fabricante. Lá você pode ler todos os detalhes sobre este medicamento e, se tiver muita sorte, obter um desconto.",
    "lt59": "Passar para o site do fabricante do ProstEro",
    "lt63": "Recurso",
    "lt64": "Comments",
    "lt65": "Vagner",
    "lt66": "diz",
    "lt68": "Sim, eu me salvei do prostatite assim. Eu entendo o autor, eu também quase que fui submetido a segunda cirurgia! Ainda bem que eu liguei o cérebro no momento certo e comecei a pensar das consequências da segunda cirurgia. Para mim também não ajudou nada menos ProstEro. Vocês não imaginam o que é isso viver sem prostatite!",
    "lt69": "Pedro",
    "lt70": "diz",
    "lt72": "Prostatite é o problema masculino, ele não tem dó de ninguém. Pela primeira vez eu fiquei doente aos 24 ou 25 anos de idade, rapazes, sejam atentos!",
    "lt73": "Marcelo",
    "lt74": "diz",
    "lt76": "É necessário comprá-lo. Eu já havia testado vários comprimidos, remédios caseiros, massagens da próstata, até uma cirurgia…",
    "lt77": "Leon",
    "lt78": "diz",
    "lt80": "Amigo, todos nós passamos por isso. Experimente. Não vai acontecer nada pior do que já aconteceu.",
    "lt81": "Leônidas",
    "lt82": "diz",
    "lt84": "Encomendei o ProstEro recentemente. O pacote chegou literalmente em poucos dias. Parece ótimo! A prostatite desapareceu em apenas após um curso de tratamento, como se eu não tivesse tido!",
    "lt85": "Eva",
    "lt86": "diz",
    "lt88": "Eu não pude ver o meu marido sofrendo de prostatite. Eu consultei com minha amiga proctologista, ela aconselhou a tomar ProstEro. Sem nenhum problema! Meu marido até parece mais jovem e temos um ótimo bônus – nossa vida íntima melhorou bastante" ,
    "lt89": "Clara",
    "lt90": "diz",
    "lt92": "Eu concordo sobre o marido! Também tratei o meu com o ProstEro, agora ele se sente muito melhor do que antes",
    "lt93": "Voltar ao topo da página",
    "lt94": "Peça seu E-Book grátis e descubra o seu mapa do amor",
    "lt95": "Entre na nossa lista de emails para receber um e-book gratuito.",
    "lt96": "ASSINAR!",
    "lt97": "Você assinou com sucesso! Verifique seu e-mail para obter um link para fazer o download do seu E-Book gratuito.",
    "lt98": "Digite seu e-mail e enviaremos o 1º capítulo imediatamente!",
    "lt96": "ASSINAR!",
    "lt99": "ENVIAR",
    "lt100": "Sucesso! Logo você receberá seu primeiro capítulo.",
    "lt101": "Obtenha seu livro gratuito do Dr. Veríssimo&nbsp; <em> Os motivos secretos pelos quais os homens ficam zangados com as mulheres </em>",
    "lt102": "Enviar!",
    "lt103": "Verifique seu email e obtenha seu E-Book!",
    "lt105": "Obrigado por compartilhar",
    "lt216": "Mais…"
    
};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };