var new_lang = {
lt1: ' - 100% sûr et efficace',
lt2: '<span class="blue">DEJA</span> 4 672 personne nous ont téléphoné pour dire<span class="bleu">MERCI!</span>',
lt3: 'Commander la consultation gratuite',
lt4: '<span class="big">Biorecin</span> est un allié principal <span class="blue">dans la lutte contre l`âge</span>',
lt5: '<span class="blue">Réduit</span> ride',
lt6: '<span class="blue">Récupère</span> élasticité',
lt7: '',
lt8: '<span class="blue">Resserre</span> chemins',
lt9: '<span class="violet">Mise à jour</span> les cellules "dormantes" ',
lt10: '<span class="violet">Restauration</span> les cellules',
lt11: '<span class="violet">Régénération</span> cellules saines',
lt12: 'Prix<br><span class="bold">1 EURO *</span>',
lt13: 'Prix avec la réduction:<br><span class="big">1 EURO *</span>',
lt14: 'Prix avant la réduction:',
lt15: 'Jusqu`à la fin des actions reste:',
lt16: 'jours',
lt17: 'heures',
lt18: 'minutes',
lt19: 'secondes',
lt20: 'ATTENTION! Le nombre de colis est limité.',
lt21: 'il Reste: ',
lt22: 'pièce',
lt23: '* - lors de la commande complète de cours',
lt24: 'Combien d`années a votre peau?',
lt25: 'il est considéré qu`un signe de vieillissement c`est une ride. Mais savez-vous que les rides ce n’est pas la chose la plus terrible ? <span class="red">CHAQUE NOUVEAU PROBLÈME AJOUTE VOUS l`ÂGE!</span>',
lt26: 'Sillons nasogéniens',
lt27: '+ 6 ans',
lt28: 'Ovale pas fixé',
lt29: '+ 5 ans',
lt30: 'Patte d`oie',
lt31: '+4 ans',
lt32: 'Pli cutané entre les sourcils ',
lt33: '+7 ans',
lt34: 'les poches sous les yeux',
lt35: '<span class="violet">La peau a son âge.</p> Elle diffère de la nôtre. En effet, la peau est très vulnérable, le maximum est vulnérable à la destruction du temps, contrairement à d`autres organes. Après 35 ans, la peau vieillit rapidement! La raison est la gravité, l`hérédité, de mauvais environnement, ultraviolet, le rayonnement, le stress et une mauvaise alimentation. <span class="red">Calculez l`âge de votre peau maintenant.</span> <span class="underline">Marquez des articles avec lesquels vous êtes d`accord.</span>',
lt36: 'Entrez Votre âge:',
lt37: 'J`ai des sillons nasogéniens:',
lt38: 'Ma peau a perdu son élasticité:',
lt39: 'Il y a les rides d`expression:',
lt40: 'il y a quelques rides profondes:',
lt41: 'Indiquez Votre âge',
lt42: 'Recommandé: 17 unités de toxine botulique, un cours de 2 mésothérapie, 28 bio-fils<br><span class="white">OU 1 cours de la crème Biorecin</span>',
lt43: 'Recommandé: 37 unités de toxine botulique, 3 cours de mésothérapie, 38 bio-fils, 1 cours de charge <span class="white">OU 2 cours crème Biorecin</span>',
lt44: 'Recommandé: 47 unités de toxine botulique, 4 cours de mésothérapie, 48 bio-fils, 1 cours de charge <span class="white">OU 3 cours crème Biorecin</span>',
lt45: 'Recommandé: 57 unités de toxine botulique, 5 cours de mésothérapie, la chirurgie lifting <span class="white">OU 3 cours crème Biorecin</span>',
lt46: 'pourquoi vous devez être plus âgés, si ',
lt47: 'vous pouvez paraître plus jeune?',
lt48: 'BEAUCOUP plus JEUNE, sans DOULEUR ET SANS RISQUE!',
lt49: 'les femmes regrettent qu’elles ont fait les injections et la chirurgie',
lt50: 'l`innocuité et l`efficacité sont prouvées ',
lt51: 'LA DERNIÈRE FORMULE Biorecin',
lt52: 'contre le vieillissement',
lt53: 'RENVOYER les MEILLEURES ANNÉES de la VIE ET de la JEUNESSE',
lt54: 'Biorecin - l`INNOVATION et le RÉSULTAT',
lt55: 'Biorecin est une révolution de la crème contenant "peptides de signalisation", qui sont capables de "soulever des profondeurs" de la peau de jeunes cellules.',
lt56: 'C`est la crème qui stimule la production de collagène et la régénération intracellulaire de "la matrice". En raison de ce que sont capables de <span class="violet">visiblement détruire les rides sur le front, dans la zone de la bouche et des yeux (pattes d`oie). </span><br><span class="orange">Biorecin est impressionnant "cocktail" pour la correction de la nasogéniens et intersourcilières plis.</span>',
lt57: 'Contient des composants, qui sont créés "augmenter le volume" à l`endroit de l`impact que le <span class="violet">remplit les rides et les plis de l`intérieur</span> "poussant" la peau du dos. Ainsi que de "se détendre" des micro-contractions des muscles pour empêcher les muscles de plisser la peau dans la glabelle.',
lt58: 'Biorecin - contient l`un des plus puissants antioxydants, neutralisateur de radicaux libres - la cause principale du vieillissement.',
lt59: 'Inhibe la désintégration de collagène, autrement dit, aux prises avec le vieillissement de la méthode de protection des cellules de la destruction. Stimule la circulation du sang dans la lymphe pour soulager l`enflure, des"poches" et de réduire les cernes sous les yeux. Renforce la structure de la peau, <span class="violet">resserre le relief, l`ovale du visage,</span> grâce à la production naturelle de collagène et d`élastine.',
lt60: ' l`acide hyaluronique MICRO MOLECULAIRE',
lt61: 'les cellules Souches de la Chicorée',
lt62: 'extrait de bourgeons de romarin',
lt63: 'Huile rouge du palmier',
lt64: 'Varech d`Or',
lt65: 'Sensationnel effet Biorecin.',
lt66: '89% des femmes ont commencé à regarder pour tant d`années qu’elles se sentent!',
lt67: 'Après 40 ans de la régénération des cellules commence à ralentir.',
lt68: 'Apparaît de plus en plus de rides, la peau perd de son élasticité, mais les contours du visage sont moins claires. Révolutionnaire de soins contre le vieillissement Biorecin créé spécialement pour les soins de la décoloration de la peau.',
lt69: 'le Triple effet du BiorecinE confirment des études cliniques à grande échelle:',
lt70: '1183 femmes',
lt71: 'ont noté <span class="violet">une réduction significative</span> des rides et des lignes de froncement de sourcils (77%), dans les coins des yeux (56%) et sur le front (76%)',
lt72: '927 femmes',
lt73: 'ont rempli de volume dans les plis nasogéniens ',
lt74: 'le volume dans le domaine de la pommette restaurée (+41%).<br>l`Ovale du visage est visiblement plus nette, la peau est remplie du volume.',
lt75: '1321 femme',
lt76: 'les résultats sont visibles<br><span class="violet">le Tonus de la peau augmente (+65%),</span> il est plus dense (+54%) et hydratée pendant 48 heures.',
lt77: '<span class="rouge">LA GRANDE ÉCHELLE DE l`ENQUÊTE A MONTRÉ que</span> LES VIEILLISSENT "COPIENT DES COMPTES"',
lt78: 'ATTENTION',
lt79: '74% des hommes ont honnêtement répondu que les femmes avec les rides et les signes de vieillissement sur le visage ne peuvent pas être sexuelles.',
lt80: 'LA PLAFOND DE LA CARRIÈRE',
lt81: '67% des employeurs ne prennent pas de travail et n`offrent pas une augmentation d`une femme qui ressemble de plus de 45 ans',
lt82: 'LA TRAHISON DE MARI',
lt83: '96% des maris jettent leurs femmes à cause de la plus jeune maîtresse et à cause du fait que la femme a cessé d`être belle.',
lt84: 'Les recherches l`ont confirmé: 87% des hommes affirment que <span class="red">l`âge de la femme n`a pas de valeur,</span> il est important, pour que la femme avait l`air <span class="red">soignée et attrayante.</p> Il le fait dans les yeux des hommes <span class="red">sexuelle et provoque le respect.</span>',
lt85: 'Prenez le temps dans leurs mains',
lt86: 'DEVENIR <span class="red">10 ANS plus JEUNE</span> 2,5 COURS',
lt87: 'les plis naso-géniens<span class="orange">ONT DISPARU</span> pour un cours de 2',
lt88: 'les pattes d`oie<span class="orange">ONT DISPARU</span> pour 3 cours',
lt89: 'les plis cutanés entre les sourcils <span class="orange">ONT DISPARU</span> pour un cours de 2',
lt90: 'l`ovale pas fixé <span class="orange">A DISPARU</span> pour 1 cours',
lt91: 'les poches sous les yeux<span class="orange">ONT DISPARU</span> pour 1 cours',
lt92: 'OPINION INDÉPENDANTE DES ESTHÉTICIENNES',
lt93: 'Nathalie <br>un Médecin esthéticienne dermatologue<br>le Stage de pratique - 18 ans',
lt94: 'Si j`avais été à la place de votre esthéticienne, ce serait bien sûr essayé de vous offrir le maximum de ce que je sais et de ce qui est disponible à la technologie de la beauté: <span class="violet">le botox, fillers, etc.</span> Mais, comme femme, je comprends qu`avec un <span class="violet">Biorecin toutes ces procédures, vous pouvez reporter les années de 6.</span>',
lt95: 'Et qu`ils pensent que c`est en plastique...',
lt96: 'Marie<br>Principal adjoint d`un chirurgien plasticien<br>le Stage pratique de 7 ans',
lt97: 'Je vous recommande de ne pas se précipiter avec les injections, les opérations et autres traumatique interventions. Laissez cette idée des années 20. Il suffit de <span class="violet">essayez de Biorecin et dans 1 mois, vous vous rendrez compte que la révolution dans la médecine esthétique s`est produite.</span>Cosmétique médicale - c`est l`avenir de la beauté et de la jeunesse, où nous pouvons profiter et apprécier les résultats.',
lt98: 'Laissez Votre peau plus jeune!',
lt99: 'tous les de moscou, les prestigieux salons de <span class="bleu">utilisent déjà Biorecin.</span> Une procédure de gommage, massage du visage et de l`application de la crème coûte environ 100 euros',
lt100:'TÉMOIGNAGES',
lt101:'Recommandé de vrais femmes.',
lt102:'En 2016 vendu plus de 3 000 000.',
lt103:'avez-Vous déjà commandé votre Biorecin?',
lt104:'Julie, Paris',
lt105:'Victoria, Nantes',
lt106:'Laura, Toulouse',
lt107:'12 000 000 $ a été investi dans la création du Biorecin',
lt108:'de l`année à la recherche',
lt109:'de l`année sur la création d`une formule',
lt110:'de spécialistes',
lt111:'% de l`efficacité',
lt112:'% des femmes heureuses',
lt113:'un certificat de qualité de l`UE, RTS, ISO',
lt114:' % de composants naturels',
lt115:'ATTENTION!',
lt116:'En raison de la popularité en France, les pays d`EU, les cas de la vente de contrefaçons pour un prix cassé!<br>attention! Sur l`emballage d`origine il y a le code à barres avec le numéro d`authentification! Si le code est manquant, reportez-vous à la plainte, en nous écrivant un mail, figurant en bas de la page. Nous vous remboursons les dommages et allons poursuivre les fraudeurs par la loi.',
lt117:'Comment travaillons-nous?',
lt118:'ÉTAPE 1',
lt119:'Faites l`ordre tout de suite avec <span class="red">le prix réduite</span>',
lt120:'ÉTAPE 2',
lt121:'Attendez un appel d’un consultant pour accorder les détails',
lt122:'ÉTAPE 3',
lt123:'Vous ne payez rien jusqu`à la réception de votre colis',
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};