var new_lang = {
lt0: 'Hipertonija un spiediena lēcieni, ko tā izsauc – 89% gadījumos nogalina slimnieku pie infarkta vai insulta!',
    lt1: 'Latvijas Republikas Veselības ministrija',
    lt4: 'Veselība',
    lt5: 'Darbība',
    lt6: 'Dokumenti',
    lt7: 'Preses centrs',
    lt8: 'Konkursi',
    lt9: 'Galvenā',
    lt10: ' Preses centrs',
    lt11: 'Ziņas',
    lt12: 'Hipertonija un spiediena lēcieni, ko tā izsauc – 89% gadījumos nogalina slimnieku pie infarkta vai insulta!',
    lt13: 'Hipertonija un spiediena lēcieni – paliks pagātnē!',
    lt14: 'Infarkts ar insultu- apmēram 70% iemesls visām nāvēm pasaulē. Septiņi no desmit cilvēkiem mirst sirds vai smadzeņu artēriju aizsprostojuma dēļ. Praktiski visos gadījumos tādu šausmīgu beigu iemesls – spiediena lēcieni hipertonijas dēļ. “Klusais slepkava”, kā to nodēvēja kardiologi, katru gadu paņem miljoniem dzīves.',
    lt15: 'Leonīds Beķeris',
    lt16: 'Ārsts-kardioķirurgs, izgudrotājs, medicīnas zinātnes organizators, pedagogs, profesors.',
    lt17: 'Darba stāžs - 48 gadi ',
    lt18: 'Par problēmu:',
    lt19: 'Nevienam nav noslēpums, ka sirds–asinsvadu slimības – pasaules līderi slimību skaitā pēc dzīvību skaita, ko tās paņem. Tad lūk hipertonija uzstājas kā visu infarktu un insultu galvenais iemesls, kas tiek norakstīti uz sirds–asinsvadu slimību rēķina. Neapšaubāmi, citas slimības arī rada spiedienu uz organismu, bet tieši hipertonija un tās izraisītie spiediena lēcieni uzstājas par to nospiešanas mēlīti, kas nosūta cilvēka uz to pasauli.',
    lt20: 'Ja runā par konkrētiem lielumiem, tad aptuveni <strong>77-78% nāves "dabisko" iznākumu – to iemesls ir tieši hipertonija.</strong> Absolūtos skaitļos, tas ir apmēram 1,54 miljoni nāves 2015.gadā un 1,49 miljonu 2014.gadā. Tas ir skaitļi patiešām kolosāli un biedējoši. Līdz nesenam laikam par nelaimes mērogu neviens neaizdomājas, jo netika veikta detalizēta statistika un analīzes. Starplaikā no 2011.gadam līdz 2015.gadam mēs savācām milzīgu datu masīvu, kas noveda pie pavisam neiepriecinošiem slēdzieniem.',
    lt21: 'Spiediena lēcieni katru reizi izsauc kolosālas sirds muskuļa slodzes, kas agri vai vēlu beidzas ar sirds apturēšanu. Rupji sakot, katru reizi paaugstināts spiediens noved pie sirds pārslodzes 10–20 reizes. Ja runā par slimības attīstības finālu, tad',
    lt22: 'hipertonija vienmēr noved pie viena un tā paša – pie nāves',
    lt23: 'Vispār, ja izceļ to tieši kā galveno cilvēka nāves iemeslu, tad tas notiek 89% gadījumos. Tas ir 89% situācijās hipertonija beidzas ar infarktu vai insultu un cilvēka nāvi. Turklāt ja vēl pirms 20–30 gadiem slimniekiem ar tādu diagnozi bija nelielas iespējas nodzīvot 10–20 gadus, tad šobrīd apmēram <strong>2/3 (divas trešdaļas) pacientu nomirst slimības attīstības pirmo piecu gadu laikā.',
    lt24: '2/3 (divas trešdaļas) pacientu nomirst slimības attīstības pirmo piecu gadu laikā. ',
    lt25: 'Īpaši šausmīgs tas fakts, ka vairums cilvēku vispār nenojauš, ka viņiem ir hipertonija. Un viņi zaudē iespēju kaut ko labot, vienkārši nolemjot sevi bojāejai.',
    lt26: 'Lūk, pēc šiem simptomiem jūs varat noteikt, ka jums ir hipertonija:',
    lt27: 'Galvas sāpes',
    lt28: 'Paātrināta sirdsdarbība',
    lt29: 'Melnie punktiņi acu priekšā (mušiņas)',
    lt30: 'Apātija, satraucamība, miegainība',
    lt31: 'Neskaidra redze',
    lt32: 'Svīšana',
    lt33: 'Hronisks nogurums',
    lt34: 'Sejas tūska',
    lt35: 'Pirkstu notirpums un trīsas',
    lt36: 'Spiediena lēcieni',
    lt37: 'Pats vienam no šiem simptomiem jāliek aizdomāties. Bet ',
    lt38: 'ja tie ir divi, tad nešaubieties - jums ir hipertonija',
    lt39: 'Vārdu sakot, atbilstoši statistikai, ',
    lt40: '67% hipertoniķiem vispār nav aizdomas, ka viņi slimi.',
    lt41: 'Kādā veidā var pasargāt sevi un uzvarēt slimību?',
    lt42: 'Vispirms ir jāsaprot, ka vērts atteikties no daudziem saviem kaitīgiem ieradumiem, īpaši no smēķēšanas un alkohola. Tas tikai padziļina situāciju ar arteriālo spiedienu. Nākamais fakts – nodzīt spiedienu var un vajag, savādāk nekādi. Bet tas nekādi neārstē pašu slimību. Pat vairāk, ja pārdozēt medikamentus un iegūt krasu spiediena pazemināšanos, tas var izsaukt ļoti negatīvu organisma reakciju līdz pat pašai infarktam. Pat nerunājot par to, ka tabletes rada ļoti lielu slodzi uz aknām.',
    lt43: ']Patiesībā šobrīd, vienīgās zāles, kuras oficiāli rekomendē ārsti hipertonijas ārstēšanai un, kuras izmanto kardiologi savā darbā – tās ir<a href=""><strong>ReCardio</strong></a>. To izstrādāšana iesākās pirms vairākiem gadiem un tika pabeigta burtiski nesen. Ar preparāta radīšanu nodarbojās speciālistu komanda, kas cieši sadarbojās ar praktizējošiem kardiologiem. Beigās sanāca unikāls pēc saviem parametriem līdzeklis, droši “dzēsošs” hipertoniju un likvidējošs tās iemeslu, atšķirībā no visiem citiem preparātiem.',
    lt44: '2016.gadā Kardioloģijas un kardioķirurģijas zinātniski–praktiskā centrā, kas iekļauts Valsts profilaktiskās medicīnas zinātniski–pētnieciskā centra sastāvā veiksmīgi pabeigti jaunās paaudzes preparāta klīniskie izmēģinājumi. - <a href=""><strong>ReCardio</strong></a>, kas izgatavots cīņai ar hipertoniju. Institūta preses dienests paziņoja par sekojošo:',
    lt45: '1. ReCardio efektivitāte, aprēķināta pēc standarta metodes (izveseļojošos skaits pret kopējo slimnieku skaitu grupā no 100 cilvēkiem, kas izgāja ārstniecības kursu) sastādīja:',
    lt46: ' –	spiediena normalizēšanās – 97%',
    lt47: ' –	vēnu trombozes novēršana – 80%.',
    lt48: ' –	stipras sirdsdarbības novēršana – 99%',
    lt49: ' –	galvassāpju novēršana – 100%',
    lt50: ' –	mundruma palielināšanās dienā, miega uzlabošanās naktī – 97%.',
    lt51: '*Ar atveseļošanos šajā gadījumā saprot visu simptomu novēršanu un recidīva iztrūkšanu 6 mēnešu laikā. ',
    lt52: '2.	Nevēlamie blakusefekti, tajā skaitā alerģiskas reakcijas nav atklātas.',
    lt53: '3.	ReCardio atzīts par vadošo preparātu cīņā ar hipertoniju.',
    lt54: 'Jānis Kalniņš',
    lt55: 'Kardioloģijas un kardioķirurģijas zinātniski–praktiskā centra direktors. Profesors.',
    lt56: 'Darba stāžs- 29 gadi',
    lt57: 'Mūsu institūta darbinieki noteica, ka preparāts iedarbojas uz slimības iemeslu, kam pateicoties rodas iespēja pilnībā atbrīvoties no hipertonijas. Tas likvidē simptomātiku praktiski vispār jau pirmajās sešās stundās pēc lietošanas, uz sava aktīvā komponenta rēķina. Tas dod iespēju uzreiz pēc kursa sākuma, kā to sauc, uzelpot ar pilnu krūti.',
    lt58: 'Asinsvadu tonuss atjaunojas pēc viena lietošanas kursa. Turklāt ReCardio efektīvs jebkurā hipertonijas stadijā. Preparāts dabiski izgājis klīniskos izmēģinājumus. Vēlos atzīmēt, ka efektivitāte, kas nodemonstrēta izmēģinājumu procesā, sniegs handikapu jebkuram ārvalstu līdzeklim. Labākais rezultāts ārvalstu preparātiem – 20–21% izārstēto. Mūsu gadījumā, runa iet par 75–77% izārstētiem. Visiem pārējiem situācija vienkārši stabilizējas. Tas ir pati hipertonija iedīglī saglabājas (problēma ar asinsvadu tonusu). Turklāt jums nelēkā spiediens un jūs jūtaties vienkārši lieliski.',
    lt59: 'Izņemot Latviju, ReCardio izgājis klīniskos izmēģinājumus Šveicē un Vācijā, kas arī apstiprināja tā efektivitāti. Šobrīd pastāv kolosāls pieprasījums pēc šī preparāta. Taču saskaņā ar speciālu rīkojumu, to pārdod tikai mūsu valstī, kas saistīts ar nelieliem ražošanas apjomiem, kas nav gatava tādam pieprasījuma līmenim.',
    lt60: 'Šobrīd zāles tiek ražotas mazās partijās, lai arī ražotājs veido jaunas jaudas, kas ļaus palielināt apjomu vairākas reizes. ',
    lt61: 'Šobrīd oriģinālo preparātu <strong>ReCardio</strong> var pasūtīt caur <a href=""><strong>ražotāja oficiālo vietni</strong></a>.',
    lt62: '194 komentāri',
    lt63: 'Inese Kļaviņa',
    lt64: 'Pirmo reizi dzirdēju par preparātu pirms trīs mēnešiem un uzreiz pasūtīju. Ar spiedienu bija šausmīgākās problēmas. Bet tagad jau pēc pirmās lietošanas dienas – ne reizi nepaaugstinājās. Vienkārši baudu dzīvi.',
    lt65: 'Pirms 12 minūtēm',
    lt66: 'Ieva Dzene',
    lt67: 'Arī nopirku savai vecmāmiņai – viņai mūžīgas problēmas ar spiedienu. Pati viņa diez vai tiks līdz tam, lai internetā kaut ko pasūtītu, lai arī pa tālruni. Tāpēc es pati. Varu teikt, ka palīdzēja par visiem 100%, kaut gan problēmas bija senas un globālas – viņa ļoti stipri lietoja zāles vairākus gadus.', 
    lt68: 'Pirms 17 minūtēm ',
    lt69: 'Šmites k-dze',
    lt70: 'Es lasīju kaut kādā medicīnas žurnālā par šo līdzekli. Ekspertu raksts, man liekas, bija, bet te uz tevis...',
    lt71: 'Pirms 19 minūtēm ',
    lt72: 'Kristīne',
    lt73: 'Es arī kaut kur dzirdēju pa ausu galiem. Kāds no pazīstamiem laikam pasūtīja sev. Pašai problēmas ar spiedienu jau otro gadu, tagad kā izlasīju – dīvaini palika. Laikam noformēšu pasūtījumu, pamēģināšu.',
    lt74: 'Pirms 21 minūtes',
    lt75: 'Oskars',
    lt76: 'Arī pasūtīju. Apsolīja nedēļas laikā piegādāt (uz Rīgu), nu ko, gaidīsim',
    lt77: 'Pirms 25 minūtēm',
    lt78: 'Daiga',
    lt79: 'Tikko kā noformēju pasūtījumu 2 kursiem. Mums ģimenē pa sieviešu līniju absolūti visām problēmas ar spiedienu. Un visbiežāk tieši mirst no infarkta.',
    lt80: 'Pirms 27 minūtēm',
    lt81: 'Aija',
    lt82: 'Lūk, tikai vakar es skatījos par šo ReCardio pa televizoru. Tur stāstīja par to, kādas labas zāles pret hipertoniju radījuši mūsu ārsti.',
    lt83: 'Pirms 30 minūtēm',
    lt84: 'Ainārs',
    lt85: 'Man ģimenē gandrīz visas sievietes nomirušas no infarktiem. Visām bija problēmas ar spiedienu. Liekas, ka arī pa vīriešu daudziem tas bija. Iešu, atstāšu pieteikumu arī.',
    lt86: 'Pirms 34 minūtēm',
    lt87: 'Vīrietis',
    lt88: 'Ceru, ka arī turpmāk zāles tikpat maksās, nevis 1000 eiro par kursu.',
    lt89: 'Pirms 39 minūtēm',
    lt90: 'Sabīne',
    lt91: 'Pasūtīju savai māsai jau pirms diviem mēnešiem. Viņa ilgi mocījās ar spiedienu. Ja jūs zinātu, kā viņa pēc tam man pateicās, ka esmu riskējusi un pasūtīju zāles.',
    lt92: 'Pirms 42 minūtēm',
    lt93: 'Egija Liepa',
    lt94: 'Man it kā viss normā ar spiedienu, bet mana mamma pastāvīgi mokās. Pasūtīšu viņai – ceru palīdzēs.',
    lt95: 'pirms stundas',
    lt96: 'Marika Bērziņa',
    lt97: 'Jūtos pēc lietošanas daudz labāk, it kā būtu jaunāka kļuvusi. Uz ārējo izskatu ļoti izpaudās. Viss kļuvis jaunāks un veselīgāks.',
    lt98: 'pirms stundas',
    lt99: 'Lenārs',
    lt100: 'Tas vienkārši ir brīnums, jā. ReCardio es uzreiz pasūtīju. Žēl tikai, ka nezināju par to pirms 5 gadiem, daudzus gadus cietu no sāpēm, toties šobrīd esmu dzīvs–vesels! Atvērts pasaulei! Liels paldies.',
    lt101: 'pirms stundas',
    lt102: 'Kazimirs Jankovskis',
    lt103: 'Daudz atsauksmju par šo ReCardio redzēju, gāju garām. Bet te pēkšņi draugs paraudāja par līdzīgu problēmu. Lūk, domāju, varbūt arī ieteikt draugam?',
    lt104: 'pirms stundas',
    lt105: 'Ēvija Muižniece',
    lt106: 'Vīram ļoti palīdzēja! Spiediens stabilizējās! Pietika tikai ar 3 pudelītēm. Tagad pasūtīšu sev! Palīz teicami.',
    lt107: 'pirms stundas',
    lt108: 'Tas ir labi! Vajag pasūtīt, savādāk esmu nomocījusies ar to spiedienu!',
    lt109: 'pirms divām stundām',
    lt110: 'Anna816',
    lt111: 'Jūs neticēsiet, arī man bija tāda problēma, pastāvīgs spēku kritums, pavisam pazaudēju interesi par dzīvi, biju izmisusi un te šis ReCardio – tas vienkārši ir brīnumlīdzeklis, visiem iesaku.',
    lt112: 'pirms divām stundām',
    lt113: 'Sandis',
    lt114: 'Skopais maksā divreiz. Atradu informāciju par ReCardio, bet nepasūtīju. Nolēmu nopirkt interneta plašumos, lētāk. Atradu kaut kādu viltotu partiju. Rezultātā norāju sevi un pasūtīju oficiālā vietnē. Dīvaini, bet <a href="">ReCardio</a> atnāca momentāni, kas mūsu pastam ir ļoti neparasti. Paldies Jums.',
    lt115: 'Pirms 3 stundām',
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};