var new_lang = {
lt1: 'Alcobarrier – SPUNE «NU» DEPENDENŢEI DE ALCOOL!',
lt2: 'Hitul vânzărilor. Fără chimie.',
lt3: 'şi sindrom de retragere',
lt4: 'anonimitate',
lt5: '50% reducere',
lt6: 'numai astăzi',
lt7: 'Până la sfârşitul reducerii rămâne:',
lt8: 'comandă un telefon',
lt9: 'Alcobarrier distruge dorinţa de alcool <br class="hidden-lg hidden-sm hidden-xs">după 1 curs! ',
lt10: 'Alcobarrier taie pofta pentru băutură odată pentru totdeauna',
lt11: '<b>Ajută</b> producerii dopaminei <b>naturale</b>, care <b>eliberează de dependenţa de alcool</b>',
lt12: '<b>Cauzează indiferenţa la alcool</b> şi <b>exclude posibilitate de zădărnicire</b>',
lt13: '<b>Lansează procesul de regenerare a celulelor stricate</b>',
lt14: '<b>Nu cauzează obişnuinţă sau efecte colaterale</b> mulţumită conţinutului <b>exceptional de natural</b>',
lt15: 'Reuşiţi să comandaţi Alcobarrier la preţul promo avantajos',
lt16: 'Până la sfârşitul reducerii rămâne:',
lt17: 'Preţul vechi:',
lt18: 'Preţul nou:',
lt19: 'Ţara',
lt20: 'Scrieţi numele vostru',
lt21: 'Scrieţi numărul vostru de telefon',
lt22: 'Atenţie!',
lt23: 'Rămâne',
lt24: 'mărfuri cu reducere:',
lt25: 'bucăţi',
lt26: 'Au deja cumpărat <br class="hidden-lg hidden-md hidden-sm">săptămâna aceasta:',
lt27: '<span class="people">4332</span> oameni',
lt28: 'Datele voastre sunt protejate. Vă garantăm să nu transmitem  <br class="hidden-sm hidden-xs">informaţii personale la persoane străine.',
lt29: 'Verificaţi dacă aveţi semne de dependenţa de alcool!',
lt30: 'Alcoolismul se apropie de dumneavoastră pe furiş, dar puteţi să n-o observaţi',
lt31: 'Marcaţi simptome care aţi observat la dv. <br class="hidden-sm hidden-xs" /> şi apăsaţi butonul<span class="green">«Verifică»</span>',
lt32: '<b>Greaţa şi ameţeala</b> în stare de <b>îmbătare alcoolică</b>',
lt33: 'Căutarea pricinelor pentru <b>consumul de alcool</b>',
lt34: 'Apariţia dependenţei <b>fizice de alcool</b>',
lt35: '<b>Probleme cu somn</b>',
lt36: '<b>Iritabilitatea</b> şi agresivitatea <b>ridicată</b>',
lt37: 'Dorinţa <b>irezistibilă de-a se drege după beţie</b>',
lt38: 'Absenţa de vomitare <b>după consum de mult alcool</b>',
lt39: '<b>Durerea de cap</b> şi <b>setea</b> dimineaţa',
lt40: '<b>Pierderea controlului</b> de cantitatea băuturii',
lt41: '<b>Tremor de mâini</b> şi tot trupul',
lt42: 'Pierderea<b>parţială de memorie</b>ziua viitoare <b>după consum de alcool</b>',
lt43: 'Beţie <b>de mai multe zile</b>',
lt44: 'Verifică',
lt45: 'Reuşiţi să comandaţi Alcobarrier la preţul promo avantajos',
lt46: 'Până la sfârşitul reducerii rămâne:',
lt47: 'Dacă aţi remarcat chiar o simptomă din acestea, în в 99% de cazuri se poate că <span class="red">aveţi dependenţa de alcool.</span>',
lt48: 'De la păhărelul la sărbătorii – până la fundul social<br> Ce va fi dacă dorinţa de alcool va ieşi de sub control?',
lt49: '<b>Dependenţa de alcool</b> se apropie pe furiş. <b>Când beţi un păhărel</b> cu prietenii voştri, chiar <b>nu bănuiţi</b>, că <b>aţi făcut</b> un pas spre <b>alcoolism</b>.',
lt50: 'Păhărelul seara, bere cu prieteni.',
lt51: 'Beţie, a fost demisionat, n-are bani.',
lt52: 'A cheltuit în beţii toată proprietatea, şi-a făcut datorii.',
lt53: 'Şi-a pierdut apartamentul, soţia a plecat cu copiii.',
lt54: '<b>A făcut o crimă când a fost beat, s-a dus la închisoare</b>',
lt55: 'Cum apare dependenţa de alcool?',
lt56: '<b>Alcoolul influenţează</b> la <b>neuronii</b> creierului, <b>în mod artificial mărind</b> nivelul de <b>dopamină</b> — hormon de satisfacţie, <b>cauzând euforie</b>.',
lt57: 'La consumul regulat <b>de alcool</b> creierul <b>produce mai puţină cantitate</b> de dopamina <b>naturală</b>. ',
lt58: 'Omul trebuie să <b>mărească cantitatea de alcool</b>. Cu fiecare oară <b>bea</b> cu <b>cât mai mult</b>. Apare <b>dependenţa de alcool.</b>',
lt59: 'Producerea dopaminei:',
lt60: 'Vreau',
lt61: 'Îmi trebuie',
lt62: 'Alcoolismul se poate termina cu pierderea familiei, <br class="hidden-sm hidden-xs"> a proprietăţii şi a libertăţii!',
lt63: '<b>93% de cazuri de violenţă la copiii proprii şi soţiile au loc în stare de ameţeală alcoolică. Se poate conduce la pierderea familiei şi închisoare.</b>',
lt64: 'Impotenţă',
lt65: '<b>Neputinţă masculină</b>, scădere de <b>libido</b> şi plina <b>impotenţă</b>, scârbă şi <b>dezgust</b> din partea sexului opus, <b>dispreţ</b> de apropiaţi şi prieteni mereu sunt<b>însoţitori ai alcoolului</b>',
lt66: 'Închisoare',
lt67: 'După datele statistice, <b>în Rusia</b> mai mult decât <b>85% de crime, 90% de accidente pe drum</b> sunt făptuite în stare de <b>ameţeală alcoolică.</b> Pentru <b>alcoolic</b>, mai degrabă, aceasta se termină cu <b>pierderea libertăţii.</b>',
lt68: 'Pierderea familiei',
lt69: '<b>93% de cazuri de violenţă </b> la <b> copiii şi soţiile </b> au loc <b> în stare de ameţeală alcoolică. Pierderea</b> rudelor şi apropiaţilor, <b>pierderea proprietăţii</b> sau <b>statutul omului fără locul de viaţă</b> — iată ce vă poate ameninţa dacă <b>nu veţi renunţa la băutură.</b>',
lt70: 'Invaliditate',
lt71: '<b>Ciroză</b> de ficat, <b>cancer</b> a tuturor organelor importante, <b>impotenţă</b>, plina <b>demenţă, infarct</b> şi <b>accident vascular cerebral, invaliditate</b>, psihoze <b>alcoolice şi «delirium»</b> aşteaptă <b>pe alcoolici</b> la fiecare pas.',
lt72: '«Să scăpaţi de dependenţa alcoolică repede fără frângere şi dorinţa de băut <br class="hidden-sm hidden-xs">din nou — este posibil»',
lt73: 'Semen Isaakovici Smoleevskii — medic cu vechime în muncă de 20 ani, PhD în medicină, naturopat',
lt74: '<b>Alcoolismul</b> — este o boală <b>grozavă</b>, cu care omul nu poate <b>lupta singur</b>. Dar astăzi <b>să eliberaţi repede</b> de dependenţa de alcool fără frângere şi <b>dorinţa de băut</b> din nou este în realitate posibil.',
lt75: 'Astăzi avem<b>un tratament</b> unic, care <b>se deosebeşte</b> de toate tratamentele care au existat mai devreme. Este un proiect comun de <b>savanţii ruşi</b> şi <b>elveţieni</b> — tratamentul <b>Alcobarrier</b>, care constă numai din <b>componente naturale.</b> Ajută pe om să refuze uşor la băuturi alcoolice<b>fără frângere, dorinţa de băut</b> din nou şi <b>efecte colaterale.</b>',
lt76: 'Deosebirea <b>principală</b> a tratamentului <b>Alcobarrier</b> este că <b>înlăturează</b> cauza principală <b>a dorinţei de alcool — regenerează</b> producerea de către organism <b>a dopaminei naturale,</b> înlăturând pe deplin dependenţa fără <b>sindrom de mahmureală, sindrom de retragere</b> şi <b>daună pentru sănătate</b>. <b>Consumul</b> tratamentului <b>Alcobarrier garantează</b> eliberare <b>de dependenţa de alcool</b> numai <b>după un curs.</b>',
lt77: 'Eliberaţi de dependenţa de alcool <br class="hidden-xs hidden-sm"> odată şi pentru totdeauna fără chimie şi zădărnicire!',
lt78: '<b>Ajută</b> producerii dopaminei <b>naturale</b>, care <b>eliberează de dependenţa de alcool</b>',
lt79: '<b>Cauzează indiferenţa la alcool</b> şi <b>exclude posibilitate de zădărnicire</b>',
lt80: '<b>Lansează pocesul de regenerare a celulelor stricate</b>',
lt81: '<b>Nu cauzează obişnuinţă sau efecte colaterale</b> mulţumită conţinutului <b>exceptional de natural</b>',
lt82: 'Reuşiţi să comandaţi Alcobarrier la preţul promo avantajos',
lt83: 'De ce Alcobarrier vă ajută<br class="hidden-xs hidden-sm"> să scăpaţi uşor de dependeţa de alcool?',
lt84: '100% conţinut natural',
lt85: 'Mulţumită <b>exstraselor</b> naturale 100% <b>influenţează</b> la organism <b>fără chimie, efecte colaterale şi codificare</b>, înlăturând <b>dorinţa de alcool</b>. Nu trebuie <b>reţeta de doctor</b>.',
lt86: 'Formula elveţiană АКТ 500',
lt87: '<b>Savanţii</b> din Europa cu grijă au ales <b>componente rare</b>, care în consistenţa precisă <b>acţionează sinergic</b>, completând şi<b>întărind</b> activitatea lor.',
lt88: 'Înlăturează dependenţa',
lt89: '<b>Alcobarrier</b> nu numai cauzează <b>indiferenţa la alcool</b>, ci şi înlăturează pricina principală <b>a dependenţei de alcool — regenerează</b> producerea dopaminei <b>proprii</b>.',
lt90: 'Efectivitatea tratamentului Alcobarrier a fost probată de cercetări clinice',
lt91: '<b>Organizaţia mondială</b> de luptă <b>cu alcoolism</b> în timp de <b>8 luni</b> a făcut un rând de<b>probe clinice</b>şi cercetări <b>fundamentale</b> a tratamentului <b>Alcobarrier.</b> În cercetări au participat <b>9500</b> de voluntari. În rezultatul cercetărilor am aflat:',
lt92: 'Codificare',
lt93: 'Alte tratamente',
lt94: 'Eliberarea de <b>dependenţa de alcool</b>',
lt95: '<b>Sindrom de<br>mahmureală</b>',
lt96: '<b>Restabilirea</b> funcţionării organelor interioare',
lt97: '<b>Sindrom de retragere</b> <br>de tratament',
lt98: 'Cercetarea tratamentului a fost încercată pe baza Centrului Rus de Ştiinţe şi Cercetare privind Dependenţe în numele lui E.M. Erofeev',
lt99: 'Formula ştiinţifică АКТ 500 conclude o reţetă antică de Hippocrate şi biotehnologii noi',
lt100: 'Exstras de anghinare',
lt101: '<b>Înlăturează</b> dorinţa de alcool, are efectul de hepatoprotector şi dezintoxicare',
lt102: 'Acid succinic',
lt103: 'Diminuează <b>efectul</b> toxic al alcoolului, <b>înlătureză</b> mahmureală,  îmbunătăţeşte funcţionarea inimii',
lt104: 'EXSTRAS DE TALPA-GÂŞTEI',
lt105: 'Calmează <b>sistemul</b> nervos, ajută <b>să înlătureze</b> intoxicarea alcoolică',
lt106: 'GUMĂ ARABICĂ',
lt107: 'Scoate toxine din organism şi <b>îmbunătăţeşte</b> funcţionarea de tubul digestiv',
lt108: 'Alcobarrier dă efectul sigur, pentru că înlăturează cauza principală a dependenţei de alcool',
lt109: '<b>Eliberează</b> de dependenţa <b>de alcool</b> fără <b>sindrom de mahmureală </b> şi <b>dorinţa de băut</b> din nou',
lt110: '<b>Înlăturează</b> cauza <b>dependenţei</b> de alcool, <b>regenerând</b> producerea dopaminei proprii.',
lt111: '<b>Lansează</b> procesul <b>de regenerare</b> a celulelor <b>stricate</b> de alcool, prevenind <b>ciroza</b> de ficat',
lt112: 'Este uşor de consumat înainte de muncă şi după',
lt113: 'Este foarte comod în aplicare',
lt114: '<b>Tratamentul este repede solubil în apă.</b>',
lt115: 'Efectul pozitiv se vede din cea dintâi zi de aplicare',
lt116: 'Pentru efect stabil recomandăm să consume de 2 ori pe zi.',
lt117: 'Eliberaţi de dependenţa de alcool <br class="hidden-xs hidden-sm"> odată şi pentru totdeauna fără chimie şi zădărnicire!',
lt118: '<b>Ajută</b> producerii de dopamina <b>naturală</b>, care <b>vă eliberază de dependent de alcool</b>',
lt119: '<b>Cauzează indiferenţa la alcool</b> şi <b>exclude posibilitate de zădărnicire</b>',
lt120: '<b>Lansează pocesul de regenerare a celulelor stricate</b>',
lt121: '<b>Nu cauzează obişnuinţă sau efecte colaterale</b> mulţumită conţinutului <b>exceptional de natural</b>',
lt122: 'Reuşiţi să comandaţi Alcobarrier la preţul promo avantajos',
lt123: 'Cele mai dese întrebări de clienţii noştri',
lt124: '<span>Am băut mai mult decât 10 ani. Recent am băut pe rând multe zile sau chiar multe săptămâni. Oare Alcobarrier îmi poate ajuta?</span>',
lt125: 'Da, tratamentul <b>Alcobarrier ajută</b> chiar <b>la consumul lung de alcool.</b> Activitatea lui principală este că <b>înlăturează</b> pricina <b>de bază a dependenţei de alcool — regenerează</b> producerea de către organism a dopaminei <b>naturale</b>, pe deplin <b>distruge dorinţa de băuturi alcoolice.</b>',
lt126: '<span>Beau de mai mulţi ani. Pot consuma Alcobarrier pe baza consumului îndelungat de alcool?</span>',
lt127: 'Da, se poate. Tratamentul conţine <b>Alcobarrier</b> componente<b>îndeosebit de naturale.</b> Toate au trecut <b>probe clinice.</b> În rezultatul <b>cercetărilor</b> am aflat că <b>Alcobarrier</b> eliberează <b>de dependenţa de alcool</b> fără influenţa chimică şi <b>efecte colaterale.</b> Tratamentul <b>nu este recomandat</b>de consum numai când individual aveţi <b>insuportabilitate de componente.</b>',
lt128: '<span>Consum Alcobarrier de două săptămâni. Spuneţi-mi, vă rog, dacă nu voi avea o zădărnicire după terminarea cursului?</span>',
lt129: 'Nu. <b>Dorinţa de alcool</b> nu trebuie să iveşte pentru că tratamentul <b>Alcobarrier nu cauzează obişnuinţă</b> şi <b>sindrom de retragere</b> mulţumită componentelor <b>extrem de naturale. Alcobarrier</b> a trecut <b>probele clinice.</b>Nici unul din participanţi după terminarea<b>consumului de curs</b> nu a avut <b>dorinţa de băuturi alcoolice.</b>',
lt130: '<span>Spuneţi-mi, vă rog, dacă este necesar să trec prin tot cursul de tratamentul Alcobarrier?</span>',
lt131: '<b>Alcobarrier începe să ajute,</b> desigur după primele zi de <b>folosire.</b> Ca să obţineţi un efect<b>maximal</b> şi să-l fixaţi este necesar să treceţi prin<b> tot cursul de tratamentul Alcobarrier.</b>',
lt132: '<span>Alcobarrier are efecte colaterale?</span>',
lt133: 'Nu. <b>Alcobarrier</b> este făcut din <b>componente naturale,</b> de aceea orice <b>efecte colaterale</b> cu aplicarea lui sunt imposibile. <b>Toată lumea</b> îl poate consuma. Tratamentul <b>nu este recomandat</b> de consumat numai pentru cei care au individual<b>insuportabilitate de componente.</b>',
lt134: '<span>De ce preţul este atât de mic?</span>',
lt135: 'Da într-adevăr preţul tratamentului este<b>Alcobarrier</b> mai mic decât preţul unei <b>vizite la doctor, a codificării</b> şi a monitoringului <b> la centru de reabilitare.</b> Iar aceste vizite pot fi mai multe. <b>Alcobarrier</b> — este <b>economia pentru pungă</b> plus rezultatul <b>sigur.</b>',
lt136: 'Părerile oamenilor cărora Alcobarrier le a deja ajutat',
lt137: 'Bună ziua! Soţul meu are stadiu 2 de alcoolism. Nu se poate cum sunt obosită. A băut toţi bani, a vândut maşina, a ieşit în datorii. Şi nu spun despre probleme cu sănătate. Copilul vede toate astea. Care model este tatăl. Am răbdat, l-am chiar codificat. Dar a fost numai pentru un an şi jumătate.Când termenul codificării a expirat, a început să bea din nou, şi mai mult decât mai înainte. Ce tratamente am încercat. Degeaba. Am decis să căutam ceva prin Internet. Am găsit tratamentul Alcobarrier. Am cercetat toate informaţiile. Desigur că am avut îndoieli. Dar am decis să încercăm căci nu se poate să fi mai rău. Am comandat, soţul a început de consumat. A terminat de băut imediat, fără frângere, chiar a apărut scârba la alcool. Foloseşte vreo o lună. Se simt mai bine, este bine dispus. Va trece cursul până la capăt.',
lt138: 'Irina, 33 de ani',
lt139: 'Bună ziua! Am deja probleme cu alcool de câţiva ani. Să fiu sincer n-am vrut s-o înţeleg de nu au început nişte probleme serioase cu sănătate şi la serviciu. Mai întâi, când beam, nu puteam să ajung la culminaţie foarte lung timp. Apoi şi când eram treaz nu reuşeam. Recent am avut sex foarte rar, căci am fost beat. Iar atunci a terminat deloc. M-a demisionat de la serviciu după beţie. Am decis că e timp să refuz la băut, dar am vrut foarte tare. N-am fost treaz mai mult decât 2 săptămâni. Împreună cu soţia am găsit pe Internet un tratament natural Alcobarrier. A livrat repede. Am trecut tot cursul. Nu beau şi nu vreau. Mă simt excelent. Am găsit un nou serviciu, şi am regulat relaţiile cu soţia.',
lt140: 'Ştefan, 38 de ani, Bucureşti',
lt141: 'Bună ziua! Recent am avut multe conflicte cu soţia mea. Din această cauză am început să beau. Nu numai am băut ci şi am intrat într-o beţie adevărată pentru câteva zile. De câteva ori am băut de două săptămâni. Era să mor apoi. Chiar am trebuit să chem instilator. Femeia desigur a răbdat mult, dar apoi n-a suportat şi a plecat, a promis să divorţeze. Am decis că trebuie să pun capăt la alcool. Singur n-am putut, am început din nou. Prietenul m-a sfătuit tratamentul Alcobarrier, mi-a trimis linkul. Am cercetat atent toate informaţiile. M-a interesat că nu vor fi înfrângeri, şi pe baza naturală. Folosesc vreo 2 săptămâni. Şi atunci nu beau deloc. N-am nici o frângere. Dispoziţia a îmbunătăţit. Recomand tuturora cu probleme cu alcool.',
lt142: 'Mihail, 35 de ani, Timişoara',
lt143: 'Ce se va întâmpla când veţi elibera de băutură?',
lt144: 'Dumneavoastră<b>veţi termina</b> să staţi în frica veşnică <b>de-a muri din cauza cirozei</b> <br class="hidden-sm hidden-xs"> de ficat, <b>a cancerului de panceas</b> şi a altor boli  <br class="hidden-sm hidden-xs"> groaznice',
lt145: 'N-o să mai aveţi frica<b>de-a pierde muncă</b>, familie <br class="hidden-sm hidden-xs"> şi <b>de-a pirde</b> drepturi <b>de paternitate din cauza beţiilor</b>',
lt146: 'Veţi <b>termina</b> de-a trăi în starea <br class="hidden-sm hidden-xs"> beţiei <b>veşnice</b> sau <b>a frângerii</b>',
lt147: 'Veţi <b>arăta normal</b>, veţi relua <br class="hidden-sm hidden-xs"> <b>atenţia sexului opus</b>',
lt148: 'Din nou veţi începe <b>să aveţi</b> <br class="hidden-sm hidden-xs"> <b>sexul de calitate corespunzătoare</b>',
lt149: 'În sfârşit veţi readuce  <b>viaţa</b> <br class="hidden-sm hidden-xs"> <b>fericită fără alcool</b>',
lt150: 'Specialiştii noştri lucrează pentru dumneavoastră!',
lt151: 'Florica Stănescu',
lt152: 'Director de calitate',
lt153: '“Nu economisim la calitate, de aceea pentru producţie se folosesc cele mai bune ingrediente şi tehnologii”',
lt154: 'Elena Dumitrescu',
lt155: 'Director de Call-Centre',
lt156: '“Lăsaţi numărul vostru şi specialiştii noştri vă vor povesti amănunţit cum puteţi primi comandă şi să folosiţi tratamentul corect”',
lt157: 'Tiberius Pahonea',
lt158: 'Şeful serviciului de livrare',
lt159: '“Comanda voastră va fi livrată în termen scurt ca să puteţi începe cât mai devreme să folosiţi produsul nostru unic”',
lt160: '19 000 000 $ a fost depus în crearea de Alcobarrier',
lt161: 'ani',
lt162: 'cercetări',
lt163: '<b>Formula АКТ 500</b> a fost creată în timp de <b>7 ani de cercetări</b> cu ajutorul <b>laboratoarelor</b>farmaceutice <b>independente</b> în <b>Rusia</b> şi <b>Elveţia.</b>',
lt164: 'crearea formulei',
lt165: '<b>Mai mult decât 5 ani</b> a durat <b>crearea</b> softului pentru selecţionarea <b>formulei de inovaţie</b> pe baza rezultatelor testelor clienţilor.',
lt166: 'efectivitate',
lt167: '<b>Extragerea extraselor</b> de substanţe active în <b>soluţie</b> este o tehnologie <b>foarte</b> grea <b>şi scumpă</b>, dar ne permite la<b>100%</b> să păstrăm <b>efectivitatea</b> tuturor componentelor.',
lt168: 'Pentru un timp de promo este stabilit preţul special la produs',
lt169: 'în loc de',
lt170: 'Cum să comandaţi Alcobarrier şi să primiţi <br class="hidden-sm hidden-xs">tratamentul Alcobarrier?',
lt171: 'Cerere',
lt172: 'Trimiteţi o cerere, şi specialistul nostru vă telefonează.',
lt173: 'Livrare',
lt174: 'Comanda se trimite într-un ambalaj anonim fără marcare de tratament.',
lt175: 'Plată',
lt176: 'Plătiţi comanda voastră la poştă sau la curier.',
lt177: 'Aplicare',
lt178: 'De atunci sunteţi indiferent la alcool, viaţa dumneavoastră devine mai bună.',
lt179: 'În timp ce trageţi timpul continuaţi<br class="hidden-xs hidden-sm"> să cadeţi în groapa alcoolică',
lt180: 'Mai întâi beţi „la sărbători”, apoi fiecare seară după serviciu. Apoi <b>sunteţi demisionat</b>. Şi iată sunteţi gata<b>pentru o sticlă să luaţi</b> ultimii<b>bani de copil.</b> Familia voastră <b>cufundă în datorii,</b> pierde proprietate şi locuinţă. Toată lumea arată cu un deget: tatăl este <b>alcoolic,</b> familia este nefericită! În acelaşi timp justiţia juvenală aşteaptă momentul ca să le ia pe copiii „nefericiţi” <b>la casa de copii</b> şi să le dea la adoptat <b>altor oameni.</b>',
lt181: 'Oare trebuie <b>să aşteptaţi</b> cele mai <b>ireversibile</b> şi <b>groaznice consecinţe</b> de alcoolizm dacă <b>problema</b> se poate <b>o salva</b> tocmai <b>acum?</b>',
lt182: 'Alcobarrier înlăturează dorinţa de alcool după un curs!',
lt183: '<b>Ajută</b> producerii dopaminei <b>naturale</b>, care <b>eliberează de dependenţa de alcool</b>',
lt184: '<b>Cauzează indiferenţa la alcool</b> şi <b>exclude posibilitate de zădărnicire</b>',
lt185: '<b>Lansează pocesul de regenerare a celulelor stricate</b>',
lt186: '<b>Nu cauzează obişnuinţă sau efecte colaterale</b> mulţumită conţinutului <b>exceptional de natural</b>',
lt187: 'Reuşiţi să comandaţi Alcobarrier la preţul promo avantajos',
lt188: '',

};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};