var new_lang = {

    "lt0": "Magyar",
    "lt1": "Hírlevél",
    "lt2": "Európa",
    "lt3": "Világ",
    "lt4": "Üzlet",
    "lt5": "Sport",
    "lt6": "Kultúra",
    "lt7": "Európa",
    "lt8": "Világ",
    "lt9": "Üzlet",
    "lt10": "Sport",
    "lt11": "Kultúra",
    "lt12": "Sci-tech",
    "lt13": "Utazás",
    "lt14": "Videó",
    "lt15": "mások",
    "lt16": "Programok",
    "lt17": "Live",
    "lt18": "Otthon",
    "lt19": "&gt;",
    "lt20": "Hírek",
    "lt21": "&gt;",
    "lt22": "Világ",
    "lt23": "&gt;",
    "lt24": "Halálosan veszélyes betakarítás 2020-ban!",
    "lt25": "Halálosan veszélyes betakarítás 2020-ban!",
    "lt26": "Európában a gyümölcsök és zöldségek 75% -a veszélyes parazitákkal fertőzött !",
    "lt27": "<span class=\"c-article-spotim__count spot-im-replies-count\"></span>Hozzászólások- 4",
    "lt28": "<span class=\"c-article-date__bullet\">&nbsp;&nbsp;•&nbsp;&nbsp;</span><span class=\"c-article-date__last-updated-label\">Utolsó frissítések:</span>&nbsp;<script>document.write(date(-1))</script>-&nbsp;11:36",
    "lt29": "Cikk megosztása",
    "lt30": "Megosztás",
    "lt31": "Megosztás",
    "lt32": "Tweet",
    "lt33": "Még több",
    "lt34": "Elrejtés",
    "lt35": "Szöveg mérete",
    "lt36": "Aa",
    "lt37": "Aa",
    "lt38": "A gyümölcsök az egészségre veszélyesek lehetnek! Mérgezési eseteket Európa szerte rögzítettek.",
    "lt39": "Mi történt?",
    "lt40": "Veszélyes helmintákat találtak zöldségekben és gyümölcsökben. Európa szerte összesen kétezer ember fertőződött meg, akik közül 300-an súlyos állapotban vannak.<b>Németországban a valószínűleg Spanyolországból  beszállított uborka okozta mérgezés miatt 2-en is meghaltak, egyes adatok szerint pedig a halálos esetek száma a 12-t is elérte.</b>",
    "lt41": "Egész Európát megrázta ez a fertőző hullám..Egy amerikai turista bél rendellenességre utaló tünetekkel került a prágai kórházba.Jelenleg az állapota stabil.A megbetegedett nő Észak - Németországból érkezett Prágába, ahol nyilatkozata szerint friss zöldségsalátát evett.",
    "lt42": "A fertőzés terjedése miatt sürgősségi intézkedésekre készülnek Németország, Franciaország, a Cseh Köztársaság, Spanyolország, Magyarország, Svájc és Ausztria hatóságai is.",
    "lt43": "Mi okozta a mérgezést?",
    "lt44": "Az első változatot németországi tudósok fedezték fel, a mezőgazdasági vállalkozásokban a növények fertőzéséhez a vegyi anyagokkal és a peszticidekkel való kezelésük során elkövetett szabálysértések vezettek, amelyek az európai zöldségek és gyümölcsök termesztésénél minden termesztési ciklusban kötelezőek (még azoknál a a gyümölcsöknél és zöldségeknél is, amelyek ökológiai tanúsítvánnyal rendelkeznek, csak a környezetbarát termesztés során jóval természetesebb peszticideket használnak). A termesztési technológiájában elkövetett szabálysértés az alma, a körte, a sárgarépa, a burgonya, a kukorica, az uborka, a paradicsom, a cukkini és a bogyók termésének nagymértékű szennyeződését eredményezte. ",
    "lt45": "<b> A járvány megállítása egyelőre még nem lehetséges. </b> A rothadt gyümölcsök, amelyek még mindig a fákon lógnak és a földben növekednek, nagyon veszélyesek, a férgek petesejtjei a talajba kerülnek, így megfertőzve az állatokat, mint hordozókat. Az negatív következmények elkerülése érdekében a kertészeknek a lehető leggyakrabban kell betakarítást végezniük, és a törvényekkel és az ökológiai előírásokkal összhangban kell megsemmisíteniük a leszedett gyümölcsöket. De sajnos a legtöbb termék már forgalomba került, a veszélyt azonnal nem vették észre. ",
    "lt46": "Az emberek a féreg úgynevezett \"helytelen\" gazdatesteiként működnek, amelyekben a féreg nem fejlődik tovább.A lárvák legfeljebb néhány hónapig élnek a testben.Az emberek nem tudják megfertőzni egymást.Ezek a paraziták a tudósok szerint elsősorban a központi idegrendszert támadják.A kutatások szerint az embereknél ez a parazita az agyhártyagyulladás ritka formájának leggyakoribb oka.A betegség súlyos lefolyása gyakran érinti a gyenge immunrendszerű embereket, ahogyan azt a stuttgarti Német Parazitológiai Intézet orvosa is magyarázza.",
    "lt47": "A CDC adatai szerint a betegeknek komoly kezelésre van szükségük, mivel betegség során súlyos károsodás figyelhető meg a belső szervekben, ideértve a tüdőt, a májat és a szívet. A mai napon Európában kb. 2800 féregbetegségre utaló esetet regisztráltak. ",
    "lt48": "Az első tünetek, amelyek a paraziták jelenlétét jelzik a testben.",
    "lt49": "Amikor az élősködők bejutnak a testbe, gyakran sokáig észrevétlenek maradnak mindaddig, amíg a nőstények éjjel a petéiket le nem rakták.",
    "lt50": "Az ember ekkor éjszaka viszkető és szúró érzésre lehet figyelmes az intim területeken. Utána a következő tünetek figyelhetők meg:",
    "lt51": "kellemetlen szájszag",
    "lt52": "allergiák (kiütés, hányás, orrfolyás)",
    "lt53": "bűrkiütés vagy bőrpír",
    "lt54": "gyakori megfázás, torokgyulladás, orrdugulás",
    "lt55": "krónikus fáradtság (gyorsabban elfárad az ember)",
    "lt56": "gyakori fejfájás",
    "lt57": "székrekedés vagy hasmenés",
    "lt58": "izomfájdalom és ízületi fájdalom",
    "lt59": "ingerlékenység, alvászavar és étvágytalanság",
    "lt60": "szem alatti sötét karikák és táskák",
    "lt61": "Mivel a paraziták a vastagbélben fészkelik be magukat, a fertőzés gyakran sokáig észrevétlen marad - magyarázza Alsó - Szászország Gyógyszerészeti Kamarája.De amint a nőstények átvándorolnak éjszaka a végbélnyíláshoz, és leteszik a petéiket a redőkbe, viszketés jelentkezik.",
    "lt62": "Hogyan védekezzünk?",
    "lt63": "A német sajtó azt írja, hogy létezik egy hatékony gyógyszer, amely felveszi a harcot a fertőzéssel, az orvosok már elkezdték felírni a betegek számára. Szerintük ezeket a gyógyszerek pozitív eredményeket érhetnek el a kezelésben, mivel kettős hatást fejtenek ki.",
    "lt64": "A kezelés első szakasza. A gyógyszer elpusztítja az élő parazitákat, természetes módon eltávolítva azokat a szervezetből.",
    "lt65": "A kezelés második szakasza. A készítmény megsemmisíti a férgek baktériumait és hulladéktermékeit, és eltávolítja azokat a mérgeket is, amelyeket az élősködők haldoklásukkor választanak ki.",
    "lt66": "Jelenleg ilyen  tulajdonságokkal bír a <b><a href=\"{url}\"><span class="productName"></span></a></b>, amelyet egész Európában hivatalosan  forgalmaznak.",
    "lt67": "Manapság ez az egyetlen hatékony szer a világon, amely lehetővé teszi a szervezet parazita testétől való megtisztítását.Pontosan ezért kívánják megszerezni  a nemzetközi gyógyszertárláncok és gyógyszeripari cégek is.Más antiparazita szerekkel ellentétben a < b > <a href=\"{url}\"><span class="productName"></span></a> < /b> azonnali hatást fejt ki az emberi szervezetben előforduló élősködők összes fajtájára.",
    "lt68": "Figyelembe véve a diagnózis során felmerülő nehézségeket, ez a készítményt lehetővé teszi az egész test hatékony megtisztítását.A paraziták jelenlétét szinte lehetetlen pontosan meghatározni a korai szakaszban, még nehezebb megállapítani, hogy milyen paraziták fertőzték meg az embert.A < b > <a href=\"{url}\"><span class="productName"></span></a> < /b> elpusztítja és eltávolítja a szervezetből az ismert paraziták 99,9 % -át, bármilyen szervről legyen is szó. A mai napig ez az egyetlen olyan készítmény, amely képes erre.",
    "lt69": "A <span class="productName"></span> klinikai vizsgálatai",
    "lt70": "A<b><a href=\"{url}\"><span class="productName"></span></a></b> klinikai vizsgálatait a Budapesti Dermatológiai Kutatóintézet bázisán végezték. A kutatásban összesen 3289 önkéntes vett részt.",
    "lt71": "az alanyok 100% -ánál: a helminthiasis és petesejtjük eltávolításra került",
    "lt72": "a résztvevők 91%-ánál: normalizálódott a hasnyálmirigy állapota és működése",
    "lt73": "az alanyok 83% -ánál: megszűnt az atópiás ekcéma",
    "lt74": "a résztvevők 92%-a: megszabadult a gyomorhurutról, a fekélyektől, a hasmenéstől",
    "lt75": "a tesztalanyok 98% -a esetében: megszűnt a vérszegénység",
    "lt76": "a tesztalanyok 100% -ánál: eltűnt a papillomavírus vagy megállt a fejlődése",
    "lt77": "Ezenkívül a Budapesti Dermatológiai Kutatóintézet megosztotta kiadónkkal azt az információt, hogy több mint 11.900 gyógyszercsomag rendelhető meg egész Európában!",
    "lt78": "Hogy bizonyítsák a<b><a href=\"{url}\"><span class="productName"></span></a></b> magas hatékonyságát és felhívják az európai lakosság figyelmét, a Nemzeti Dermatológusok Szövetségére, amelynek tagjai között több híres orvos is található, a készítményt a lakosság számára <span class=\"new_price_val\">teljesen ingyen osztja szét</span><span class=\"new_price_cur\"></span>",
    "lt79": "LÁTOGASSON EL A HIVATALOS HONLAPRA",
    "lt80": "Hozzászólások:",
    "lt81": "Sarkadi Mária",
    "lt82": "Én is megrendeltem magamnak a készítményt.Sok papillóma volt a nyakamon és a hónaljamban.Már az ötödik napon úgy éreztem, hogy egyre kisebbek lettek.Ugyanakkor a hasamon is javult a helyzet.<br> Most háromhavonta elvégzek egy előzetes kúrát. ",
    "lt83": "Karakas Judit",
    "lt84": "Nemrégiben néztem egy TV - műsort az emberi parazitákról.Beszéltek erről a gyógyszerről is, azzal dicsekedve, hogy a világ legjobb gyógyszerét a paraziták ellen nálunk hozták létre.Ha jól emlékszem, ott volt a miniszter is.",

    "lt85": "Siska Katalin",
    "lt86": "Tegnap éjjel egy egész csomó jött ki ebből a fenéből belőlem!!! Egyszerűen le vagyok döbbenve! Jó, hogy megvettem magamnak megelőzés céljából a<b><a href=\"{url}\"><span class="productName"></span>t</a></b>, nem volt semmilyen tünetem!",
    "lt87": "Kassai Lajos",
    "lt88": "Soha nem bíztam a zöldség- és gyümölcstermelőkben, mindig mindent megpróbáltam magamnak megtermelni. De ebben az évben sikerült hozzájutnom farmon termesztett zöldségekhez és gyümölcsökhöz, És a paraziták engem sem kíméltek meg! Most várom, hogy megérkezzen a<b><a href=\"{url}\"><span class="productName"></span></a></b>, és kezelni fogom magam!",
    "lt89": "LÁTOGASSON EL A HIVATALOS HONLAPRA",

    "lt90": "Még több a témában",
    "lt91": "Paraziták",
    "lt92": "Aratás",
    "lt93": "Covid-19",
    "lt94": "Szenzációs ajánlat!",
    "lt95": "Nyár",
    "lt96": "Forró témák",
    "lt97": "Részletek:",
    "lt98": "Covid-19",
    "lt99": "Forró témák",
    "lt100": "Részletek:",
    "lt101": "Covid-19",
    "lt102": "<svg viewBox=\"0 0 37.32 37.32\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M40.29,8S28.56,6.25,25.38,6.25v0a1.55,1.55,0,0,0-.77.1L5.14,25.82a1.54,1.54,0,0,0,0,2.16L20.28,43.12a1.51,1.51,0,0,0,1.08.45,1.5,1.5,0,0,0,1.08-.45L41.91,23.66C42.51,23.06,40.29,8,40.29,8ZM21.36,38.55,9.72,26.9,26.33,10.29c2.26.15,6.71.71,10.42,1.22.58,4.15,1.09,8.37,1.23,10.42Z\" fill=\"#002e44\" transform=\"translate(-4.7 -6.25)\"></path><circle cx=\"27.3\" cy=\"9.75\" fill=\"#002e44\" r=\"2.5\"></circle></svg>Keresés a nap címkéi között",
    "lt103": "Aratás",
    "lt104": "Robbanás",
    "lt105": "Budapest",
    "lt106": "Zöldségeskert",
    "lt107": "Magyarország",
    "lt108": "Covid-19",
    "lt109": "járvány",
    "lt110": "Természeti katasztrófa",
    "lt111": "Történetek",
    "lt112": "Európa",
    "lt113": "Világ",
    "lt114": "Üzlet",
    "lt115": "Sport",
    "lt116": "Kultúra",
    "lt117": "Sci-tech",
    "lt118": "Utazás",
    "lt119": "Videó",
    "lt120": "Programok",
    "lt121": "Szolgáltatások",
    "lt122": "Live",
    "lt123": "Hírek",
    "lt124": "Időjárás",
    "lt125": "A sürgős üzenetek szalagja",
    "lt126": "Feliratkozás",
    "lt127": "Widgets &amp; Szolgáltatások",
    "lt128": "Afrikanews",
    "lt129": "Foglalja le a jegyét",
    "lt130": "Együttműködés",
    "lt131": "Az \"Euronews-ról\"",
    "lt132": "partnerség az EU-val",
    "lt133": "Felhasználói szerződés",
    "lt134": "Cookies politika",
    "lt135": "Kapcsolat",
    "lt136": "Forgalmazás",
    "lt137": "Hirdetések",
    "lt138": "Álláshirdetések",
    "lt139": "Feliratkozás",
    "lt140": "Copyright © euronews<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 * 60 * 60 * 000);var year = d.getFullYear();document.write(year);</script>20202020",
    "lt141": "-",
    "lt142": "Magyar"
};
function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
}
;

