var new_lang = {
lt0: "Acheter Tinedol à prix réduit. Les prix, les commentaires. Commandez Tinedol maintenant!",
lt1: "Conçu <br>en utilisant <br>de la nanotechnologie",
lt2: "Approuvé par <br>l'Association Nationale des dermatologues",
lt3: "Commander le service",
lt4: "OUBLIEZ POUR JAMAIS",
lt5: "A PROPOS DES DERMATOPHYTES, DES DÉMANGEAISONS ET <br>DES FISSURES DE PIEDS!",
lt6: "Élimine les symptômes de la mycose des la première application",
lt7: "Élimine complètement du dermatophyte en 1 cours",
lt8: "Soulage les démangeaisons, la desquamation et des irritations de la peau des pieds",
lt9: "Élimine les odeurs désagréables",
lt10: "Normalise les glandes sudoripares",
lt11: "Panser les plaies et les fissures sur les jambes",
lt12: "REMISE",
lt13: "La série limitée, dépêchez-vous <span>commander par action</span> ce mois-ci!<br>",
lt14: "La série limitée, dépêchez-vous <span>commander par action</span> ce mois-ci!<br>",
lt15: "Jusqu'à la fin de l’actions il reste:",
lt16: "Heures",
lt17: "Minutes",
lt18: "Secondes",
lt19: "Prix régulier:",
lt20: "Prix réduit de ce mois-ci:",
lt21: "Commander",
lt22: "Vos données sous la protection",
lt23: "Pensez toujours que vous êtes hors de la zone à risque?<br>Vérifiez la présence d'un de ces symptômes. Et même si vous avez un seul de ces symptômes vous avez, puis COMMENCEZ IMMÉDIATEMENT  LE TRAITEMENT!!!",
lt24: "L'odeur désagréable",
lt25: "Les brûlures et Les démangeaisons dans la zone de pieds",
lt26: "Les fissures sur les talons et la desquamation de pieds",
lt27: "Les cloques et les rougeurs sur les pieds",
lt28: "La forme mauvaise de l'ongle",
lt29: "Les engourdissements et les picotements stop",
lt30: "Le changement de couleur de l'ongle avec du rose au jaune (brun)",
lt31: "L'étanchéité de la plaque de l'ongle",
lt32: "Les tâches et les stries sur les ongles",
lt33: "Les cors d'étanchéité dans la zone de stop",
lt34: "Quelles conséquences vous pouvez avoir sans le traitement de dermatophyte?",
lt35: "Selon les statistiques,un habitant sur trois de notre pays au moins une fois est confronté à des symptômes de la mycose. Et chaque cinquième habitant a cette maladie. Le dermatophyte se développe rapidement, si vous portez une chaussure en matériaux non-naturels, des chaussettes en fibres synthétiques, et si vous visitez régulièrement les saunas, les bains et les piscines. En été, le risque est sur les plages, dans les parcs, où en marchant pieds nus et même dans votre cabine de douche!",
lt36: "ARRÊTEZ LA PROPAGATION DE CETTE MALADIE! PROTÉGEZ VOTRE SANTÉ!",
lt37: "La première étape de l'infection fongique:",
lt38: "<i></i>de l'Inconfort lors de la marche",
lt39: "<i></i>Mauvaise odeur",
lt40: "<i></i>Transpiration",
lt41: "<i></i>Ininterrompue des démangeaisons",
lt42: "<i></i>Desquamation",
lt43: "Le deuxième stade de l'infection fongique:",
lt44: "<i></i>Démangeaisons lors de la marche",
lt45: "<i></i>Peau durcie",
lt46: "<i></i>Fissures profondes sur les talons",
lt47: "<i></i>Mauvaise haleine Persistante",
lt48: "<i></i>Fragile ongles jaunis",
lt49: "Le troisième stade de l'infection fongique:",
lt50: "<i></i>Purulentes crack",
lt51: "<i></i>Perte des ongles",
lt52: "<i></i>Ulcères les plus profonde",
lt53: "<i></i>Desquamation entre les doigts",
lt54: "<i></i>Blancs flocons de peau",
lt55: "Si ce n'est de pratiquer le traitement de la mycose des pieds, vous pouvez exécuter une dangereuse maladie! Imaginez que vous êtes tourmenté par la douleur, les démangeaisons et hideux de la vue et de l'odeur de vos pieds. Voulez-vous ce qui arriva? ALORS DITES PAS UN dermatophyte!",
lt56: "une pommade Antifongique, <p>ENRICHIE en IONS d'ARGENT</span>",
lt57: 'Comment fonctionne <span class="title4-span1">pommade Tinedol?</span>',
lt58: "avec l'utilisation continue, Tinedol élimine un certain nombre de problèmes avec la peau des pieds. Entrant dans la composition des éléments vous aideront à la première application pour toutes les ÉLIMINER:",
lt59: "dermatophyte",
lt60: "l'odeur Désagréable",
lt61: "Sueurs",
lt62: "Crack",
lt63: "Peau seche",
lt64: "les Démangeaisons et l'inconfort lors de la marche",
lt65: '<span class="se consist__text--b">Climbazole</span> — arrête le développement de levures et de dermatophytes. Il soulage les démangeaisons. Exerce un effet destructeur sur le dermatophyte.',
lt66: '<span class="se consist__text--b">Фарнезол</span> — “coupe” les glandes sudoripares. Désinfecte, sèche, donne un parfum agréable pour longtemps.',
lt67: '<span class="se consist__text--b">Propolis</span> - a des propriétés fortes.',
lt68: '<span class="se consist__text--b">l`Huile de théier</span> - pénètre profondément dans la couche sous-cutanée, guérissant les zones de la peau, donne de la fraîcheur et élimine les mauvaises odeurs après une dure journée de travail.',
lt71: "Cette onguent élimine les dermatophytes et les sensations inconfortables dans les jambes, qui sont de tous ceux qui l'ont déjà rencontré avec le dermatophyte.",
lt72: "L’onguent est rapidement absorbée, elle n'a pas brillant odorantes et répartie uniformément sur toute la surface du pied. Elle ne laisse aucune trace sur le tissu et ne nécessite pas de rinçage. Il suffit d'appliquer l’onguent  sur les deux pieds (interne et la partie supérieure), les mouvements massant frictionner la pommade dans la peau et attendre 1 à 2 minutes, jusqu'à ce qu'il soit absorbé dans la peau des pieds.",
lt73: 'La série limitée!<br>Dépêchez-vous!<br> Seulement <span class="product-how-much"><span class="lastpack"></span> paquets</span> <br>avec le prix spécial!',
lt74: "Tinedol - c'est une façon simple de se débarrasser de la moisissure pour TOUJOURS!",
lt75: "Prix régulier:",
lt76: "Prix réduit de ce mois-ci:",
lt77: 'La série limitée! Dépêchez-vous!<br><span class="product-how-much-all"><span class="lastpack"></span> paquets</span> à un prix spécial!',
lt78: "Entrez vos informations dans le formulaire ci-dessous.",
lt79: "Qu'il adviendra DE VOS PIEDS APRÈS 30 JOURS D'UTILISATION de la POMMADE Tinedol",
lt80: "Vous allez vous débarrasser de mycose des pieds et des ongles",
lt81: "La sensation d'inconfort et les démangeaisons dans les jambes va vous quitter pour toujours",
lt82: "Vos pieds n’ont jamais de désagréable odeur",
lt83: "Vous allez ressentir la douceur et le confort lors de la marche",
lt84: "Vos pieds cessent de fournir, transpirer",
lt85: "La peau des pieds est mise à jour et devient douce et lisse",
lt86: "Vos ongles viennent en parfait état",
lt87: "Vous avez de belles jambes, qui n'ont pas honte de mettre à nu sur la plage ou dans la piscine",
lt88: "COMMENT UTILISER L'ONGUENT Tinedol",
lt89: "Il faut laver les pieds, les essuyer, puis appliquer une fine couche de l’onguent sur le pied, à l'intérieur et à l'extérieur. Étalez la pommade dans la peau des pieds, attendez jusqu'à ce qu'il soit absorbé (1-2 minutes). Répétez la procédure pour chaque soir avant de se coucher, pendant 30-35 jours. Et après la fin des cours de l'utilisation <strong>vous verrez le changement de votre peau, et les jambes sont en bonne SANTÉ!</strong>",
lt90: 'La série limitée!<br>Dépêchez-vous!<br> Seulement <span class="product-how-much"><span class="lastpack"></span> paquets</span> <br>avec le prix spécial!',
lt91: "Pourquoi l’onguent Tinedol est plus efficace que les autres onguents contre le dermatophyte?",
lt92: "Les médicaments sont divisés en deux catégories: soit ils ne fonctionnent pas ou aident seulement jusqu'à ce que vous les utilisez. Si vous rencontrez un dermatophyte, alors c'est sûr, comprenez de quoi il s'agit, et utilisez régulièrement, handicapés et inefficaces, des crèmes et des onguents.",
lt93: "<strong>Tinedol</strong> change complètement l'idée de médicaments antifongiques. La masse des études cliniques a montré que cet onguent est extrêmement efficace pour éliminer les mycose des pieds et des ongles. Après le premier cours de la réception dermatophyte disparaît à jamais. Cet effet est obtenu grâce à exclusivement choisi des ingrédients.",
lt94: "l'Opinion de l'expert - dermatologue",
lt95: "Après une recherche approfondie de l’onguent <strong>Tinedol</strong> je peux affirmer que c'est très efficace. La chose principale c’est le complexe de soins de la peau des pieds. Même si vous avez seulement un ou plusieurs des symptômes, il <strong>faut</strong> utiliser l'onguent <strong>Tinedol</strong>, pour éviter les effets dangereux de l'infection fongique. Rappelez-vous, le choléra apparaît tout d'un coup et se développe très rapidement! Aujourd'hui, vous vous sentez mal à l'aise et facile intermittent des démangeaisons, et demain, vous pouvez boire des antibiotiques et se soigner dans un hôpital. NE PAS TROP SERRER LE TRAITEMENT! Résoudrez le problème lorsque les premiers symptômes. Et n'oubliez pas! Le dermatophyte est la plus contagieuse des infections. Il suffit de toucher la source de l'infection et vous courez le risque de contracter, et donc infecter toute votre famille!",
lt96: "— Alexandre Dupont<br>Dermatologue, esthéticienne, mycologue.",
lt97: "Commentaires",
lt98: "J'ai toujours pensé que le dermatophyte ne m'a jamais touché. Mais quand, après la piscine, de plus j'ai commencé à me démanger les pieds, j'ai commencé à penser que, après tout, est tombée malade... Avant de pouvoir utiliser le Tinedol j'ai essayé un tas de moyens, sur le temps de nettoyage des gale et les fissures. Mais tous les aidait seulement quelques jours. Finalement, quand mes talons sont gercées et a commencé à saigner, je suis allée chez le docteur. Il m'a prescrit du TinedolE. Et maintenant je n'ai plus peur de retirer les chaussures sur la plage!<br>Merci!",
lt99: "Marie, Paris",
lt100: "Quand mes talons gercées, je me souviens que mes grands-parents sont les mêmes. Mais en effet, sous les 70, et moi seulement 28! C'était terrible. J'ai ensuite réalisé que c'est encore le dermatophyte, en particulier au moment où les fissures sont devenus terriblement me démanger. J’allais un mois à la piscine sans la claque, et j'ai compris d'où vient le dermatophyte. Finalement j’ai appris d'un ami qu'elle a aidé à Tinedol, je l’ai goûté et voila! Avec cela signifie que votre talons comme dans l'enfance!!!",
lt101: "Pierre, Nice",
lt102: "J'ai longtemps essayé de guérir le dermatophyte de vinaigre, jusqu'à ce que j'ai brûlé même leur peau.. C'était terriblement douloureux et désagréable. Et le dermatophyte, j'ai un problème constant, parce que la transpiration des pieds est très doué. Ma mère a appris sur Tinedol, je l’ai essayé, il les a délivrés de la démangeaison pour la première application. Mais ma mère a dit que si je vais 3 mois étalée, et le dermatophyte se tiendra. ET C'EST AINSI! Merci à la maman, et les créateurs du TinedolE!",
lt103: "Camille, Toulouse",
lt104: "Livraison du courrier",
lt105: "ou par le courrier",
lt106: "Confidentialité est assurée.",
lt107: "le paiement lors de la réception.",
lt108: "Comment nous travaillons:",
lt109: "Vous demandez",
lt110: "sur site",
lt111: "Nous contactons",
lt112: "vous",
lt113: "Nous envoyons votre",
lt114: "colis",
lt115: "Vous payez lors de '",
lt116: "la réception",
lt117: "Nos opérateurs sont en ligne",
lt118: "24/7 Commandez!",
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};