var new_lang = {

"lt0": "Prostatito<span class=\"order-title_green\">gydymas</span> ",
"lt1": "natūraliu būdu",
"lt2": "Be<br>skausmo",
"lt3": "Be<br>operacijų",
"lt4": "Be rektalinio<br>masažo",
"lt5": "Užsakyti dabar<br> <span class=\"form-title_green\">su nuolaida</span> ",
"lt8": "Šalis<select class=\"form-input\"><option>Rusija</option></select>",
"lt9": "Jūsų vardas: <input class=\"form-input\" type=\"text\">",
"lt10": "Telefono numeris: <input class=\"form-input\" type=\"text\">",
"lt11": "Iki akcijos pabaigos:",
"lt12": "užsakyti",
"lt13": "\"Nesmagi\" liga – <span class=\"text-red\">daug pasekmių</span> ",
"lt14": "Prostatitas – iš tokių ligų, kurios reikalauja sutelkto dėmesio. Jeigu nepradėti gydytis laiku, yra rizika, kad bus rimtos komplikacijos.",
"lt15": "Pačios išplitusios iš jų:",
"lt16": "Impotencija",
"lt17": "Nevaisingumas",
"lt18": "Prostatos adenoma",
"lt19": "Šlapimo nelaikymas",
"lt20": "Chroniškas dubens skausmas",
"lt21": "Prostatos vėžys",
"lt22": "Prostatito gydymo <span class=\"text-red\">konservatyvūs metodai</span> ",
"lt23": "Rektalinis masažas",
"lt24": "Prostatos rankinio masažo procedūra. Daugybė vyrų mano, kad toks gydymas yra skausmingas ir žeminamas.",
"lt25": "Gali padėti pradinėje ligos stadijoje.",
"lt26": "Kaina: <span class=\"text-semiBold\">nuo 60000 PHP.</span> ",
"lt27": "Medikamentai",
"lt28": "Gydymas medikamentais reikalauja, kad vaistai būtų atsargiai parinkti. Daug turi labai nemalonius šalutinius efektus.",
"lt29": "Gali padėti, jeigu pavyks parinkti idealiai tinkamą vaistą.",
"lt30": "Kaina: <span class=\"text-semiBold\">nuo 40000 PHP.</span> ",
"lt31": "Operacija",
"lt32": "Nėra šimto procentų pasveikimo garantijos. Dažnai būna pooperacinių komplikacijų ir recidivų (prostatito simptomų atsiradimas) atvejai.",
"lt33": "Gali padėti tik 25% atvejų.",
"lt34": "Kaina: <span class=\"text-semiBold\">nuo 1000000 PHP.</span> ",
"lt35": "Liaudiški metodai",
"lt36": "Yra didelė rizika padaryti žalą savo organizmui ir pabloginti priešinės liaukos būklę. Liaudiškų gydymo metodų veiksmingumas kliniškai neįrodytas.",
"lt37": "Gali padėti kaip susirgimo profilaktikos priemonė.",
"lt38": "Kaina: <span class=\"text-semiBold\">nuo 5000 PHP.</span> ",
"lt39": "XX – <span class=\"text-green\">padės kiekvienam žmogui</span> ",
"lt40": "Visiškai grąžina vyro sveikatą ir išvaduoja nuo prostatito simptomų:",
"lt41": "nutraukia skausmą šlapinimojo metu",
"lt42": "mažina potraukius šlapintis, taip pat ir naktimis",
"lt43": "padidina seksualinį aktyvumą",
"lt44": "mažina navikų augimo riziką",
"lt45": "trukdo susirgimo recidyvui plisti",
"lt46": "trukdo susirgimo recidyvui plisti",
"lt47": " <span class=\"text-green\">Gamtos jėga</span> kiekviename komponente",
"lt48": "Afrikos slyva",
"lt49": "Palengvina prostatos pabrinkimą ir uždegimą, stabdo aseptinio uždegimo augimą, trukdo per dideliam fibroblastų augimui prostatoje, trukdo formuotis naviko audiniui .",
"lt50": "Likopinas",
"lt51": "Kovoja su visais vyrų seksualinio senėjimo veiksniais. Antioksidantas, trukdo naviko audiniui augti ir migruoti, sumažina prostatos vėžio plitimo riziką.",
"lt52": "Palmė sabal",
"lt53": "Stimuliuoja hormoninės sistemos funkciją gaminant testosteroną. Sustiprina potenciją. Užkerta kelią skaidulinio audinio formavimuisi.",
"lt54": "Moliūgo sėklos",
"lt55": "Grąžina erekcijos mechanizmo veiksmingumą ir sustiprina imunitetą. Leidžia išvengti priešinės liaukos uždegimo augimo, pašalina sąstingį urogenitalinėje sistemoje .",
"lt56": "Specialisto nuomonė",
"lt57": "Dėl prostatito vyras susiduria su daugybe nepatogumų: deginimas besišlapinant, aštrus skausmas gaktos srityje, dažni potraukiai šlapintis. Atsisakymas gydyti šį susirgimą baigiasi prostatos vėžiu, impotencija ir nevaisingumu.",
"lt58": "Praktikoje prostatitą galima išgydyti trimis skirtingais būdais: 1) operacija su ilgalaike reabilitacija ir galimu ricidyvu; 2) antibiotikų panaudojimas; jie turi daug šalutinių efertų ir ne visada parodo rezultatą; 3) neseniai išrastas naturalus vaistas XX.",
"lt59": "Visiems pacientams aš pirmiausiai rekomenduoju preparatą XX. Jis neturi šalutinių efektų ir kovoja su susirgimu net esant pačiai sunkiausiai formai. Šis vaistas teikia vyro organizmui visus reikalingus vitaminus ir mikroelementus, kad kovotų su priešinės liaukos uždegimu.",
"lt60": "Viljamas Markos, gydytojas-urologas.",
"lt61": "Darbo stažas - 23 metų.",
"lt62": "Atsiliepimai apie XX",
"lt69": "Armani, <span class=\"age\">41 metai</span> ",
"lt70": "Daugiau nei metus trukdė aštrus skausmas pilvo apačioje, po to prasidėjo karščiavimas ir deginimas tarpvietėje. Antibiotikai, kuriuos skyrė gydytojas, demonstravo trumpalaikį efektą. Masažai taip pat. Ką tik aš pradėjau vartoti XX – tuoj pasirodė užuominos į pasveikinimą: nebebėgiojau į tualetą, išnyko nuolatinis skausmas ir pagerėjo potencija. Po kurso tik prisimenu apie prostatitą..",
"lt71": "Nabas, <span class=\"age\">55 metai</span> ",
"lt72": "Prostatitas – nėra paprasta liga, o ištisa greta apsiribojimų ir kančių. Pirma, dažni potraukiai šlapintis neleidžia nueiti nuo namų toli. O skausmai besišlapinant net aprašyti sunku. Iš pradžių pabandžiau gydytis namuose – nepavyko, tik pradėjau blogiau jaustis. Forume sužinojau apie XX. Pradėjau vartoti jį ir iškart situacija pagerėjo. Pakako tik vieno kurso, kad atsisveikintų su prostatitu! Jokių operacijų ir masažų. ",
"lt73": "Matthew, <span class=\"age\">32 metai</span> ",
"lt74": "Aš susidūriau su prostatitu, kai man sukako 30 metų. Buvau labai nustebęs, maniau, kad ši istorija paliečia tik garbingo amžiaus žmones.  Vieną kartą papasakojau apie savo problemą draugui. Paaiškėjo, kad jis taip pat susidūrė su tokia problema, sėkmingai nusprendė ją ir patarė XX. Po dviejų savaičių vartojimo aš vėl jaučiausi puikiai, lyg nieko nebuvo. Po vieno kurso prostatitas išnyko. Patariu šį vaistą.",
"lt75": "Šejla, <span class=\"age\">46 metai</span> ",
"lt76": "Mano vyras ilgai kankinosi su prostatitu. Aš jau negalėjau žiūrėti į jo kančias ir pradėjau pati tyrinėti šią temą internete. Vieną kartą suradau atsiliepimus į preparatą XX. Žmonės rašo apie savo pasveikinimą jo dėka, ir net tie, kieno atvejai buvo labai sunkūs. Pajutusi įkvėpimą aš įtikinau vyrą pabandyti šį vaistą, nors jis jau visiškai netikėjo, kad bus teigiamas rezultatas. Ir ką galvojate, dabar mano vyras visiškai sveikas! :)",
"lt85": "PRAŠOM<br>ATKREIPTI DĖMESĮ!",
"lt86": "Pakuočių XX kiekis, reikalingas, kad pasiektų geidaujamo rezultato, <span class=\"alarm-bold\">nustatomas individualiai ir tam tikrais atvejais gali padidėti.</span> ",
"lt87": "Prostatito <span class=\"order-title_green\">gydymas</span> ",
"lt88": "natūraliu būdu",
"lt89": "Be<br>skausmo",
"lt90": "Be<br>operacijų",
"lt91": "Be rektalinio<br>masažo",
"lt92": "Užsakyti dabar<br> <span class=\"form-title_green\">su nuolaida</span> ",
"lt95": "Šalis<select class=\"form-input\"><option>Rusija</option></select>",
"lt96": "Jūsų vardas: <input class=\"form-input\" type=\"text\">",
"lt97": "Telefono numeris: <input class=\"form-input\" type=\"text\">",
"lt98": "Iki akcijos pabaigos:",
"lt99": "užsakyti",




};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };