var new_lang = {

"lt0": "Salud",
"lt1": "Belleza",
"lt2": "Comida",
"lt3": "Fitness",
"lt4": "Revista",
"lt5": "Suscripciones",
"lt6": "Competencias",
"lt7": "¿Cómo curar la prostatitis?",
"lt8": "Cada día un gran número de cartas llegan a nuestra oficina editorial, pero una de ellas ha atraído nuestra atención especial. Creemos que sería útil para nuestro auditorio masculino que es la mitad de los lectores de nuestra revista",
"lt9":  "Quiero compartir mi historia y tal vez ayudar a otros hombres que sufren de prostatitis a volver a estar sanos. Por razones obvias, deseo permanecer anónimo",
"lt10": "Primero, ¿qué es la prostatitis? En términos simples, es inflamación de la glándula prostática. Ella produce la secreción que permite a su esperma viajar a su objetivo y no morir en las primeras etapas de su ya corta vida. Además, es la próstata la que bloquea el canal urinario durante las relaciones sexuales, no permitiendo que los espermatozoides entren en la vejiga y viceversa. Hay muchas causas de la prostatitis, pero las principales son el estilo de vida sedentario y el alcohol",
"lt11": "Mi historia comenzó mucho antes de saber lo que es la prostatitis. Siempre me pareció que esta palabra estaba en la lista de enfermedades de los pensionados y y nada tenía que ver conmigo. Desde, mas o menos, los 15 años, empecé a tener dolor. El dolor era punzante, muy extraño. En ese momento, ni siquiera podía explicar dónde. Sucedió muy rara vez y no le di mayor importancia. Era raro y no era difícil soportar 5-10 minutos",
"lt12": "Han pasado 10 años. Durante este tiempo, casi nada me molestaba. Bueno, había un poco de dolor cada 2-3 meses, a veces menos a menudo. Y por alguna razón, se me atascó en la cabeza, que probablemente así pasaba con todos. Hay sólo una cosa de la que no hablan. Lo más doloroso fue cuando apareció después del sexo. No era un buen momento para acurrucarse empapado en mi sudor frío.",
"lt13":   "Ya cuando tenía 25 años, tuve un dolor en la ingle. Después de una semana se intensificó en el interior de la pierna, la rodilla comenzó a entumecerse. Lo primero que me vino a la mente fue una hernia. Además, me sometí a cuatro cirugías de hernia, tres de las cuales estaban en la ingle. Las sensaciones eran muy similares y comencé a prepararme mentalmente para la operación. Habiendo hecho esta suposición, fui al cirujano, el cual palp+ó la ingle y rechazó mis conjeturas, así que me envió al urólogo",
"lt14": "El examen del urólogo fue insoportable. El médico me puso en una postura no muy agradable y me metió el dedo (sentí como si hubiera sido toda la mano) en un lugar intocable para cualquier hombre. Y esto es lo que diré: si te dicen que te relajes en una situación así, es posible que ni siquiera lo intentes. Pasé un minuto en esa posición. Por supuesto, es difícil concentrarse en una situación de este tipo, pero aún tenía que responder en qué momento aumentaba  el dolor. Y se amplificó cuando presionó la próstata",
"lt15": "Después de terminar los procedimientos diagnósticos, el médico ofreció ir a la oficina, soltando simultáneamente algunas bromas sobre la hipotermia. Pero una vez me senté, como un buen tío se convirtió en un fiscal. Escuché la explicación más dura y humillante que había escuchado sobre la enfermedad de los 45-50 años. Hubo una pausa. El silencio fue interrumpido por mí con la pregunta ¿Qué hacer?. El urólogo redujo su fervor y comenzó a explicar lentamente con qué me estaba enfrentando Me recetó supositorios, píldoras y pruebas.",
"lt16": "El tratamiento ayudó. Por cierto, por consejo del mismo médico, comencé a practicar deportes (supuestamente, previene el deterioro patológico en la próstata). Y un día después de la piscina sentí una sensación de ardor familiar. Fui a otro médico. De nuevo la misma historia con los análisis y las mismas recomendaciones. Me ayudó por un tiempo, pero el problema volvió de nuevo",
"lt17": "Entiendo que es una práctica normal que los urólogos no traten la enfermedad, sino que alivien temporalmente los síntomas. Así que decidí actuar por mi cuenta. Me metí a Internet, releí una tonelada de comentarios sobre diferentes médicos. En uno de los foros me encontré con un segmento sobre un profesor que cura la prostatitis de una vez por todas. Por cierto, su consejo vale bastantísimo dinero.",
"lt18": "Pero, ¿qué más podía hacer? Me inscribí, esperé mi turno durante un mes y medio. Llegué  al profesor con una pila de pruebas ya hechas. Casi sin mirarlas, sacó un paquete de pastillas del cajón, me lo entregó y lo envió a la recepción para pagar ",
"lt19": "La droga se llamaba Prostaline.  Bebí todo el curso como e debía. El efecto fue impresionante: no sólo se fue el dolor y el malestar general desapareció. La potencia aumentó varias veces, la erección se ha vuelto mejor y más larga.",
"lt20": "Lo más agradable es que ha pasado un año y medio desde que completé mi tratamiento con Prostaline, y desde entonces no ha habido una recaída",
"lt21": "Recientemente decidió beber el <b>«Prostaline»  como prevención de la prostatitis y para aumentar la potencia.  Como resultó, sí, funciona.",
"lt22": "Y descubrí otro punto interesante: El Prostaline cuesta varias veces menos de lo que pagué en la clínica. .<b> El medicamento se puede pedir directamente del fabricante sin ningún tipo de marcas.</b> Mi doctor además resultó ser también un estafador.<b> Por eso quiero compartir el enlace de donde se puede ordenar el “Prostaline” por el precio de fabrica: </b>",
"lt23": "Ordenar Prostaline en el sitio web del fabricante",
"lt24": "Comentarios",
"lt25": "Nicolás",
"lt27": "El compuesto es realmente muy bueno! Tuve el mismo problema, sólo que tengo 40. Fui a pescar con mis amigos, dormí en tiendas de campaña y me resfrié allí. ¡Fue una pesadilla! Corría al baño cada hora, tenía una sensación de ardor constante en la ingle. Al principio probé losmedicamentos de marcas conocidas que veía de la publicidad en la televisión, pero que no me trataron, simplemente me permitían vivir. Fue cuando vi el Prostaline en Internet y desde hace seis meses estoy completamente saludable",
"lt28": "Roberto Antonio",
"lt30": "Tuviste suerte de encontrar un urólogo experto, a pesar de que resultó ser un estafador. ¡Lo principal es que encontramos nuestra medicina!",
"lt31": "Maninblack",
"lt33": "¡Tienes que cuidar de tu cuerpo! Leo siempre todo lo que puedo encontrar antes de empezar a tomar un nuevo medicamento.  El Prostaline mejora la eficacia de la terapia contra la prostatitis. Lo probé, obtuve un resultado positivo y lo mejor es que es seguro.",
"lt34": "Alejandro",
"lt36": "Gracias por este artículo. Tengo el mismo problema. Por la noche empecé a dormir mal, a menudo quería ir al baño. Durante una semana tuve fiebre, no enía fuerzas. Menos mal que me topé con este texto. Me ordené el Prostaline, preferiría comenzar el tratamiento con él.",
"lt37": "Ignacio López",
"lt39": "No conozco a gente a la que no le haya ayudado el Prostaline, ya no tengo miedo de ir al baño. ¡Para su precio el compuesto es muy eficaz!",
"lt40": "Andrés",
 "lt42":  "También me ayudó el Prostaline y el proceso de curación fue mucho más rápido. Sentí el alivio de los síntomas al quinto día de tomarlo, comencé a conciliar el sueño. Ha pasado un mes sin que se agrave, la depresión se ha ido",
"lt43": "María C.",
"lt45": "Mi marido categóricamente se niega admitir su problema de salud! Todo el mundo espera un y si no es nada. Ya han comenzado el dolor y los problemas en la vida íntima. El urólogo descubrió que la enfermedad ya estaba en una etapa crónica. Se ha puesto inyecciones, supositorios, pero no mejora... Supongo que tendremos que pedir el Prostaline, es  la última esperanza.",
"lt46": "Alberto",
"lt48": "He estado trabajando en el frío toda mi vida, probablemente por eso la enfermedad apareció a mis 60 años. Le pedí a mi hijo que ordenara el paquete y no me equivoqué. El compuesto está bien, ha cumplido con su tarea durante una semana, pero sigo bebiéndolo hasta que termine el curso",
"lt49": "Juancho",
"lt51": "He estado buscando una buena droga durante mucho tiempo, me dan pavor las inyecciones cada tres días y no quisiera beber un montón de píldoras. Ya he pedido un paquete, gracias por el artículo.",
"lt52": "Jorge",
"lt54": "Me ayudó con la inflamación crónica, fortaleció el sistema inmunológico. Muy buena medicina.",
"lt55": "Elchicomalo",
"lt57": "Sentí el alivio al instante, desaparecieron las sensaciones desagradables. Mi esposa cambió de opinión sobre el divorcio, así que Prostaline salvó a mi familia",
"lt58": "Sergio",
"lt60": "Me enteré sobre el compuesto en un foro de hombres, un montón de personas lo aconsejaron, las opiniones allí no mienten. Me olvidé de las recaídas, la micción frecuente. La vida ha vuelto a la normalidad",
"lt61": "Daniel",
"lt63": "La prostatitis es el flagelo del siglo ProstalineI, que también me ha marcado a mí. Al igual que el autor, pensaba que la enfermedad se presentaba en las personas mayores. Me trataron con algunos compuestos estándar, supositorios, pero con este tipo de tratamiento desde la etapa aguda mi prostatitis pasó a crónica",
"lt64": "Eduardo",
"lt66": "Quien está buscando información por primera vez sobre el compuesto, no lo dude, ¡pedídlo! ¡Me ayudó mucho! Así curé mi prostatitis.",
"lt67": "¿Te gustaría escribir un mensaje?",
"lt68": "Enviar",
"lt69": "Su mensaje fue enviado a moderación",
"lt70": "Suscríbete a nosotros",
"lt74":"Encuestas",
"lt75": "¿Te gustó nuestro nuevo sitio?",
"lt76":"Sí",  
"lt77":"No",
"lt78": "Ver resultados",
"lt79":"Últimos tweets",
"lt80": "Suscribirse por sólo 23,90 euros",
"lt81": "Disfruta de ocho números de la revista de salud y bienestar más vendida del Reino Unido",
"lt82": "Entregado directamente en tu puerta",
"lt83": "El paquete lleno de consejos de expertos",
"lt84": "Historias de salud actualizadas",
"lt85": "Recoger 100&nbsp;<a href=\"#\" style=\"color:#000000\">rewards for life</a>puntos cuando te suscribes",
"lt86": "Descubre más",
"lt87":"Salud"  ,
"lt88": "Belleza",
"lt89": "Comida",
"lt90": "Fitness",
"lt91": "Revista",
"lt92": "Suscripciones",
"lt93": "Competencias",
"lt94": "Política de Privacidad",
"lt95": "Suscríbete a nosotros",
"lt99": "Sobre la SALUD",
"lt100":"Healthy es la revista de bienestar más vendida creada por Holland &amp; Barrett.. Lanzamos ocho ediciones al año que recogen las últimas historias sobre salud, psicología, belleza, comida y fitness, todo lo que necesitas para una vida más saludable",
"lt101":"IR AL INICIO",
"lt102": "© Healthy Magazine <span class=\"year\">2020</span>",
"lt103": "Menú"



};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };