var new_lang = {

"lt0": "Hlavní stránka",
"lt1": "O nás",
"lt2": "často kladené dotazy",
"lt3": "Služby",
"lt4": "Terapie",
"lt5": "Archivy",
"lt6": "Zdroje",
"lt7": "Vědci se snaží už 15 let najít speciální přípravek pro omlazení kožních buněk",
"lt8": "Čeští vědci z Univerzity Karlové, vyvíjeli přípravek na bázi speciálních rostlinných extraktů. Až 15 let pracovali nad omlazením buněk pokožky.",
"lt9": "Datum příspěvku: <span class = \"commits__date\"> 21/21/2021 ????? </span>",
"lt10": " VĚDCI ZKOUMALI 15 LET, A KONEČNĚ VYNALEZLY PŘÍPRAVEK KTERÝ OMLAZUJE POKOŽKOVÉ BUŇKY",
"lt11": "16 Komentářů",
"lt12": "Sdílet",
"lt13": "Autor: ing.Jan Boháček",
"lt14": "Všechno to začalo lékařským experimentem. Účastníci brali experimentální lék na posílení imunitního systému. Ve výsledku výzkumu vypadali zkoumané subjekty o několik let mladší, zmizeli jím vrásky a pokožka byla naprosto jako z hedvábí",
"lt15": "Vědci neočekávali podobné výsledky: chtěli jen otestovat účinek několika konkrétních bylinných extraktů na imunitní systém. Po měsíci užívání bylinného extraktů dobrovolníci zjistili, že se každý ze zkoumaných subjektu omladil průměrně o 15 let. ",
"lt16": "Hlavní vědecký pracovník v oblasti vývoje léků MUDr.Štěpán Řehák to komentuje takto:",
"lt17": "Po výzkumu účinku léku jsme zjistili, že lék stimuluje buňky těla k aktivnější funkci. Počet volných radikálů v krvi subjektů se výrazně snížil. Tyto dva faktory přímo ovlivňovaly stav organismu a pokožky zkoumaných subjektů. Rozhodli jsme se že přejdeme k výzkumu omlazujících účinku přípravku.",
"lt18": "Podle stejného vzorce byl vyroben krém pro atopickou pokožku. Byla pak vytvořena další experimentální skupina dobrovolníků ve věku od 45 až 60 let a výzkum pokračoval. Krém aplikovali celý měsíc, dvakrát denně. Po experimentu pokožka obličeje dobrovolníků vypadala v průměru až o 8 let mladší.",
"lt19": "Vědci studovali kožní buňky po aplikaci krému. Začali fungovat výrazně aktivněji, bylo možné je srovnávat s kožními buňkami u lidí v 25 let. Metabolické procesy se zrychlily, fibroblasty začaly produkovat třikrát více kolagenu .",
"lt20": "Po experimentu zůstala se aktivita buněk vysoká. Pouze za šest měsíců po použití aktivita buněk začala pomalu klesat.",
"lt21": "Tady vidíte fotografií dobrovolníků. S jejích souhlasem jsme zveřejnili jejích fotografie ve výsledků výzkumu experimentálního krému",
"lt24": "Tyto fotografie se rychle rozšířily na internetu a vyvolaly vlnu komentářů lidí, kteří si chtěli koupit lék proti stárnutí. To přimělo vědce vyrábět lék pro všichni lidí a podepsat smlouvy s výrobcem. Nyní se produkt vyrábějí pod značkou s názvem Intenskin. Neexistuje nic podobného, ačkoli se jiní výrobci snaží o něco podobného.",
"lt25": "Krém se prodává v pár kamenných obchodech v Česku a <a href=\"#ordera0\" style=\"font-size: 18px; font-style: italic; text-decoration: underline; color: #f00;\">  na oficiálních stránkách výrobce </a>. Nový nástroj Intenskin si může vyzkoušet každý.",
"lt26": "Vše, co musíte udělat, je zadat vaše jméno a telefonní číslo. <span> Pospěšte si! Zbývá se vám jen málo času: </span> <div class = \"all-form__count\"> <span class = \"all-form__min\"> 10 </span>: <span class = \"all-form__sec \"> 00 </span> </div> ",
"lt27": "Přihláška <span> Intenskin </span>",
"lt28": "Vaše země:",
"lt29": "Vaše jméno:",
"lt30": "Telefon:",
"lt31": "Získejte 50% slevu",
"lt34": "Komentáře:",
"lt35": "Pavlína", 
"lt37": "Tento krém nahradí většinu jiných přípravku proti stárnutí, to jsem si jistá!",
"lt38": "Sandra Vojtěchová",
"lt40": "Už dlouhou dobu se nevyrábělo nic podobného z přírodních složek) Poprvé jsem zadala objednávku přes internet, v naší zemi ještě Intenskin neprodává v kamenných obchodech, ale opravdu bych to chtěla vyzkoušet!",
"lt41": "Klára Komárková.",
"lt43": "Čekala jsem na to jíž dlouho, hurá, konečně si to můžu koupit! Přečetla jsem si o tom víc recenzi, všichni tento krém mají rádi",
"lt44": "Vendula Doufková",
"lt46": "Tento krém mi doručili nedávno. Můj první dojem byl, že má velmi v hezký obal. Po několika aplikacích jsem si uvědomila, že je velmi kvalitní: rychle se vstřebává a hezky to voní. O týden později jsem měla hedvábnou a zpevněnou pokožku, vrásky přestaly být výrazné a některé i zmizeli. Obecně ho může používat každý! ",
"lt47": "Kamča",
"lt49": "Kde to kupujete?",
"lt50": "Jana Boháčová",
"lt52": "Klikla jsem na webovou stránku, která je uvedena v tomto článku. Našla jsem několik dalších online obchodů, ale jsou to podvodnici, cena je tam třikrát vyšší.",
"lt53": "Helena Janošková",
"lt55": "Myslela jsem, že to je skoro vůbec není nemožné ... Jak můžete omladit pokožku obličeje bez injekcí krásy? Používám tento krém jíž tři týdny a nevěřím vlastním očím ... Pokožku na obličeji je měkká, a hedvábná, má hezký tón, kontura je jasnější. To jsem příjemně překvapená ... ",
"lt56": "Marta Bohouškova",
"lt58": "Předtím jsem kupovala krém na odstranění vrásek, který byl o 3 !!! krát dražší než tento. Účinek těchto krému byl nulový. Když jsem začala používat Intenskin, cítila jsem v tom velký rozdíl. Krém se okamžitě vstřebává - hned poznáte, že obsahuje jen přírodní složky! ",
"lt59": "Johana",
"lt61": "Teď používám pouze přírodní krémy. Moje pokožka je problematická, je pořád podrážděná, a mám pořád nějaké vyrážky. Předtím přírodní krémy maximálně zvlhčily pokožku a Intenskin má opravdu silný účinek. Jsem velmi ráda že jsem objevila tento krém",
"lt62": "Klára Vacíková.",
"lt64": "Je pro mě těžké najít krém, protože v podstatě všichni co se nabízejí ucpávají póry a způsobuje vyrážky. Tenhle funguje perfektně. Ale co je nejdůležitější, opravdu mě to zachránilo před vráskami na obličeji! Objednala jsem si další balíček.",
"lt65": "Martina",
"lt67": "Je mi 48 let. Už půl roku se věnuji obličejové masáži. Ale neodmítám tu teorií že tradiční léky pomáhají :)) Ale, bohužel žádný z krémů které jsem kupovala mi nepomohl protože nebyl žádný účinek. Zkoušela jsem i velmi drahé luxusní značky. Nedávno jsem si objednala Intenskin. A velmi rychle mi to pomohlo! Zmizeli z obličeje vůbec. Pokožka se rychle zpevnila, jako v mladiství. Samozřejmě jsem dělala i masáže, ale tak výrazný efekt vidím až teď. ",
"lt68": "Gabriela",
"lt70": "Dobrý den! Je tento krém vhodný pro osoby starší 65 let? Pomůže mi to vůbec",
"lt71": "Emma Vodičková",
"lt73": "Gabrielo, neváhejte, krém obsahuje jenom přírodní složky, po 35 letech to pomáhá každému :))",
"lt74": "Anna Jindřichová",
"lt76": "Kosmetička říká, že už mám jemné vrásky. Zeptám se jí na tento krém.",
"lt77": "Monika Korbová",
"lt79": "Je mi 32 let, kvůli silnému stresu se mi objevily hluboké vrásky na čele a kolem očí. Starší kamarádky doporučují injekce krásy. Intenskin je moje poslední naděje a šance, jak se tomu vyhnout!",
"lt80": "Ivana Mihlová",
"lt82": "V 59 let všichni říkají že vypadám mladší o 10 let. Jako produkt denní péče jsem si vybrala Intenskin. Přejí všem hodně lásky!",
"lt83": "Chcete napsat zprávu?",
"lt84": "Odeslat",
"lt85": "Vaše zpráva byla odeslána pro moderátorovi",
"lt203": "Přejít na domácí stránku|",
"lt204": "FAQ |",
"lt205": "Research Foundation |",
"lt206": "Služby |",
"lt207": "Investování |",
"lt208": "Terapie |",
"lt209": "Tiskové středisko |",
"lt210": "Archivy |",
"lt211": "O nás",
"lt212": "Přečtěte si naše podmínky a zásady ochrany osobních údajů.",


};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };