var new_lang = {

    "lt0": "NEWSLETTER DIÁRIA",
    "lt1": "Assine a nossa newsletter diária por e-mail",
    "lt2": "Menu",
    "lt3": "notícias",
    "lt4": "tecnologia",
    "lt5": "espaço",
    "lt6": "física",
    "lt7": "saúde",
    "lt8": "mente",
    "lt9": "ambiente",
    "lt10": "mais",
    "lt11": "palavras cruzadas",
    "lt12": "vídeo",
    "lt13": "lojas",
    "lt14": "passeios",
    "lt15": "eventos",
    "lt16": "trabalhos",
    "lt17": "ASSINE A NEWSLETTER DIÁRIA",
    "lt18": "Pesquisa",
    "lt19": "Fazer login",
    "lt20": "Faça login no facebook",
    "lt21": "Faça login no google",
    "lt22": "E-mail",
    "lt23": "Senha",
    "lt24": "Esqueceu a senha?",
    "lt25": "Assine gratuitamente",
    "lt27": "Acesso educacional",
    "lt28": "Assine para obter mais artigos on-line",
    "lt29": "Uma seleção dos principais artigos escolhidos a dedo por nossos editores, disponível apenas para usuários cadastrados.",
    "lt30": "Obtenha acesso aumentado agora",
    "lt31": "Gerencie sua assinatura",
    "lt32": "Verifique seu pacote de assinatura, renove ou atualize seus dados.",
    "lt33": "Gerencie sua assinatura aqui",
    "lt34": "Ativar assinatura",
    "lt35": "Fernando Vieira: o adenoma da próstata é uma doença mortal para cada terceiro homem.",
    "lt36": "Saúde",
    "lt38": "Por<span class=\"author font-sans-serif-ProstEros--bold\"><a class=\"author font-sans-serif-ProstEros--bold\"> Miguel Coelho</a></span> ",
    "lt39": "Fernando Vieira, médico do Hospital Real de Portugal, médico proctologista, fez uma declaração sensacional sobre prostatite. <b>Ele afirma que a mortalidade por prostatite é de 99,8%.</b>",
    "lt40": "Nossa equipe de filmagem foi até ele para descobrir por que ele fez essa declaração e se existem maneiras de curar a prostatite de uma vez por todas?",
    "lt41": "- Fernando, recentemente você publicou um trabalho em dois volumes sobre problemas de prostatite, onde você descreveu em detalhes os problemas da prostatite avançada. Então, afinal, qual é o perigo da prostatite e será que os sintomas podem ser ignorados sem tratamento adequado?",
    "lt42": "- Sim, eu escrevi em mais de 800 páginas sobre a prostatite avançada. Posso falar sobre isso por horas, mas tentarei dizer brevemente: sem tratamento, a prostatite evoluirá da inflamação para o adenoma de próstata. O adenoma de próstata é um tumor na pélvis pequena. Abafando os sintomas, você não sentirá dor na transição da prostatite para um tumor e degeneração de um tumor benigno em um maligno. Portanto, se você perder a última degeneração do tumor, em vez de um proctologista, irá ao oncologista.",
    "lt43": "- Você quer dizer que a prostatite é mortal?",
    "lt44": "Sim, e não apenas por causa da oncologia. A doença requer intervenção precoce e uma abordagem delicada. O problema é que, na prostatite, existe uma retenção urinária crônica e, se isso não for tratado, pode se desenvolver a insuficiência renal. A pessoa pode morrer da insuficiência renal. Diante dessa complicação, se desenvolvem as infecções que levam a óbito. Morte pode ocorrer por três causas: insuficiência renal, sepse e complicações de intervenções cirúrgicas.",
    "lt45": "Recentemente, conduzi um estudo em larga escala e descobri que todo terceiro homem após 45 anos, durante 2,8 anos, com quase cem por cento de probabilidade, pode morrer dos efeitos do adenoma de próstata: isso pode ser oncologia, insuficiência renal ou envenenamento do sangue",
    "lt46": "Isso parece horrível. Mas a prostatite não é considerada uma doença incurável. De onde vem essa estatística assustadora?",
    "lt47": "- O problema é que os médicos geralmente não tratam, mas apenas aliviam temporariamente as dores de prostatite dos pacientes. Antibióticos, cirurgias, pomadas e soros interrompem o desenvolvimento da doença sem curá-la completamente. O desenvolvimento de infecções é suprimido com a ajuda de antibióticos, eles não ajudam no tumor do adenoma de próstata. As recaídas geralmente ocorrem após a cirurgia. Sem mencionar que este é um procedimento extremamente doloroso. Métodos como soro e pomadas são eficazes apenas como analgésicos, pois esse é um bloqueio temporário. o desenvolvimento de sintomas sem afetar a redução do tumor. ",
    "lt48": "- Por que outros homens estão usando esses tratamentos e ninguém morre?",
    "lt49": "- É uma afirmação forte, é claro, mas vou tentar responder à sua pergunta. Você está errado. Uma das principais causas de morte em homens após 45 anos é <b> câncer de próstata </b>. As razões pelas quais eles não falam sobre isso, são essas: ",
    "lt50": "Médicos e patologistas não divulgam informações fora do círculo médico sobre as estatísticas reais de mortes por câncer de adenoma de próstata nos últimos cinco anos.",
    "lt51": "Os próprios homens que enfrentam esse problema não procuram o médico, considerando a prostatite como algo vergonhoso. É por isso que é difícil avaliar objetivamente quantos homens morreram de câncer de adenoma de próstata nos últimos anos do que dizem as estatísticas oficiais.",
    "lt52": "- Por que ninguém discute esse problema?", 
    "lt53": "- Infelizmente, a maior parte dos médicos está tentando esconder o fato da possibilidade de morte por adenoma de próstata, para não semear pânico entre as pessoas. Vamos enfrentar a verdade: a prostatite é uma doença grave que pode prejudicar a saúde, destruir a vida pessoal e pôr fim ao sistema reprodutivo. ",
    "lt54": "- Não pode existir este círculo fechado: a doença não pode ser curada, mas é impossível viver com prostatite! Que dica você dá para seus pacientes?",
    "lt55": "Francamente, estou preocupado com a situação no mercado farmacêutico. Nos últimos anos, poucos medicamentos realmente bons para prostatite foram entregues à venda nas farmácias. No entanto, recentemente, meus colegas desenvolveram um medicamento ProstEro para prostatite, com uma composição eficaz. Eu o prescrevia aos pacientes e toda vez fiquei mais convencido de que este medicamento é líder de mercado em qualidade. O produto contém ameixa africana, saw palmetto, zinco e vitamina E. Os ingredientes são obtidos por extração a frio, o que permite manter o máximo de substâncias úteis biologicamente ativas extraídas da planta. É devido a isso, elas têm tão alta eficácia.",
    "lt56": "Vou contar uma história curta. Um dia eu me deparei com um estudo de médicos franceses que descobriram uma tribo africana nas regiões montanhosas dos Camarões. Depois que um especialista conseguiu examinar a maioria dos homens da tribo, descobriu-se que <b>nenhum deles não tinha prostatite</b>. Mais tarde, verificou-se que era a ameixa africana que a tribo usava como principal componente da nutrição que se tornou um fator principal na manutenção de sua saúde.",
    "lt57": "Foram realizados sérios ensaios clínicos da ameixa africana. Foi demonstrado claramente que o extrato de ameixa africana fica bastante ativo no tratamento da prostatite e adenoma de próstata.",
    "lt58": "- Onde e como eu posso obter ProstEro?", 
    "lt59": "- Ainda não é possível comprá-lo por meio de uma rede de farmácias, portanto acesse o site oficial. Como médico, estou preocupado com a possibilidade de venda dos remédios falsificados e enfrentar problemas sérios de saúde subsequentes para pessoas que compraram produtos de baixa qualidade, por isso peço que você anexe um link do<um href=\"\">site oficial</a>. ",
    "lt60": "- Muito obrigado Fernando! Tenho certeza que nossos leitores irão apreciar o ProstEro.",
    "lt61": "Acrescentaremos:  amigos, não ignorem os sintomas de prostatite antes que seja tarde demais. Atitude cuidadosa com a saúde é a melhor maneira de prolongar sua vida.",
    "lt62": "Link para o site oficial",
    "lt63": "Comentários:",
    "lt64": "Bruno",
    "lt65": "Foi exatamente assim que escapei da prostatite. Pertenço àqueles homens preocupados com sua saúde. Quando percebi que tinha prostatite, li todas as informações sobre essa doença, aprendi sobre o alto risco de oncologia e recaída após a cirurgia, e fiquei chocado. Se não fosse pelo ProstEro, poderia estar na UTI ou em algo pior.",
    "lt66": "Pedro",
    "lt67": "Prostatite é o perigo para homens. Ela não poupa ninguém.",
    "lt68": "Marcelo",
    "lt69": "É necessário tomá-lo. Tentei todos os tipos de comprimidos, remédios populares, massagens na próstata e até fui submetido à cirurgia...",
    "lt70": "Leo",
    "lt71": "Muitos de nós passaram por cirurgias e recaídas. Honestamente, não existe nada pior do que ficar sentado na porta do consultório médico e afastar pensamentos de possível oncologia",
    "lt72": "André",
    "lt73": "Encomendei o ProstEro recentemente. O pacote chegou em poucos dias. Literalmente, depois de um curso de tratamento, a prostatite desapareceu como se não existisse! Além disso, fui ao médico e certifiquei-me que estava completamente curado da prostatite.",
    "lt74": "Eva",
    "lt75": "Eu não pude mais observar o meu marido sofrendo de prostatite. Consultei com a amiga proctologista, ela me aconselhou a comprar ProstEro. Não existe mais problema nenhum!",
    "lt76": "Clara",
    "lt77": "Eu concordo com todas as palavras sobre o marido! Também curei meu com o ProstEro, agora ele se sente muito melhor do que estava se sentindo antes",
    "lt78": "Link para o site oficial",
    "lt79": "Entre em contato",
    "lt80": "Suporte",
    "lt81": "Sobre nós",
    "lt82": "Privacidade &amp; cookies",
    "lt83": "Termos &amp; condições",
    "lt84": "Publicidade",
    "lt85": "Escrevam para nós",
    "lt86": "Eventos",
    "lt87": "Trabalhos científicos",
    "lt88": "Sindicatos",
    "lt89": "RSS",
    "lt90": "Assinaturas de presente",
    "lt91": "Assinaturas de alunos",
    "lt92": "Assinaturas educacionais",
    "lt93": " Assinaturas corporativas",
    "lt94": "© Copyright New Scientist Ltd.",
    "lt95": "Voltar ao topo"
    
};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };