var new_lang = {
    lt1: 'Alcoolismul poate fi învins! Salvați-i pe cei apropiați!',
    lt2: 'Știri',
    lt3: 'Comunicare',
    lt4: 'A se subscrie',
    lt5: 'Revista ”MED-info”',
    lt6: 'Consultări',
    lt7: 'catalog de medicamente și instituții',
    lt8: 'Categorii',
    lt9: 'Catalog',
    lt10: 'Consultări',
    lt11: 'Comunicare',
    lt12: 'Divertisment',
    lt13: 'revista<br>”MED-info”',
    lt14: '<span>catalog</span><br>de medicamente și instituții',
    lt15: '<span>consultări</span><br>adresați întrebare medicului',
    lt16: 'aplicații<br><span>mobile</span>',
    lt17: 'Categorii',
    lt18: 'Subiecte',
    lt19: 'analitică',
    lt20: 'interactiv',
    lt21: 'interviu cu vedetă',
    lt22: 'infografică',
    lt23: 'istoria cititorului',
    lt24: 'masă rotundă',
    lt25: 'subiect acut',
    lt26: 'reportaj',
    lt27: 'articole',
    lt28: 'Cele mai recente știri',
    lt29: 'ieri la orele 13:26',
    lt30: 'A fost prezentat top-100 cei mai buni stomatologi',
    lt31: 'ieri la orele 21:56',
    lt32: 'În decembrie va fi decernat premiul Russian Pharma Awards',
    lt33: 'ieri la orele 14:24',
    lt34: 'Sondaj: ce dăunează sănătății la&nbsp;locul de muncă',
    lt35: 'Oamenii de știință au crescut neuroni care produc hormonul fericirii',
    lt36: 'Cel mai interesant',
    lt37: 'interviu cu expert',
    lt38: 'Roxana Marinescu: «Intervențiile chirurgicale cu laserul stomatologic — o metodă de tratament a viitorului»',
    lt39: 'articole',
    lt40: 'Cum să nu&nbsp;greșim atunci&nbsp;când alegem periuța de dinți',
    lt41: 'Alcoolism',
    lt42: 'Interviu cu expert',
    lt43: 'Alcoolismul poate fi învins! Salvați-i pe cei apropiați!<br>Medic șef din orașul București, doctor în medicină, profesorul Alexandru Graur',
    lt44: 'Din partea redacției: Conform ultimelor date statistice, numărul de alcoolici în România a depășit cifra de 684500 de oameni sau 3.4 % din numărl total de populație. La evidență se află doar 1.7% dependenți de alcool. Alcoolismul a devenit cauza decesului 1/3 din numărul total de bărbați și 15 % de femei. Transformând în cifre de la alcool mor aproximativ 50000 de oameni anual. Date groaznice! Un număr atât de mare de oameni nu mor în timpul războaielor, în urma epidemiilor și calamiăților naturale. De abuzul de alcool în România țin direct sau indirect: 62.1% sinucideri, 72.2% omoruri, 60% decese cauzate de pancreatită, 67.7% cauzate de ciroză și 23.3% cauzate de boli cardiovasculare. Anual sunt înregistrate peste 40 mii de cazuri de intoxicații cu alcool de calitate scăzută, inclusiv și cazuri fatale. Cum putem scăpa de această boală și să devenim oameni sănătoși, l-am întrebat pe doctorul în medicină, profesorul Alexandru Graur',
    lt45: 'Este groaznic, când pofta de alcool distruge viața omului. Din cauza alcoolului se destramă familiile, copiii își pierd tații, iar soțiile bărbații. În prezent alcoolismul, ca boală, a întenerit considerabil. Adeseori alcoolici devin anume oameni tineri, care își distrug viitorul și cauzează un prejudiciu ireparabil sănătății. Trebuie să recunoaștem că cel mai frecvent anume femeilor le revine misiunea de a-și sălva bărbatul alcoolic: fiu, soț sau tată. Este de necrezut, dar membrul familiei, care este dependent de alcool, poate fi salvat, și în așa mod ca acesta să nu știe nimic, în taină. Astăzi vorbim despre un produs nou<a target="_top" href="../../../../c.alcobarrier.com/default.htm">Alcobarrier</a>, care și-a demonstrat eficacitatea.',
    lt46: 'Probabil cunoașteți că până nu de mult unicul remediu eficient în lupta împotriva dependenței de alcoolе a fost codarea pacientului. Această metodă are un minus major - bolnavul trebuie să-și dea acordul pentru tratament și în mod conștient să accepte codarea și să renunțe totalmente la alcool. Pentru totdeauna. Însă de obicei ei nu recunosc că sunt dependenți de alcool, și sunt încrezuți că în orice moment pot să renunțe. Doar cei apropiați conștientizează că a renunța la alcool aceștia nu vor putea fără a fi ajutați. Ce ramâne de făcut? A convinge, a aduce argumente, a vă certa a ruga persoana dependentă nu are rost. Alcoolul a pust stăpânirea pe ea. Nu rămâne decât o singură opțiune - a trata persoana aproiată în taină, pentru a-l salva. În acest scop poate fi noul produsul creat de medici și oamenii de știință - produsul Alcobarrier, care în timp de 2 săptămâni (14 zile) poate crea o senzație puternică de dezgust față de alcool chiar și la alcoolici cronici. Alcoolul provoacă persoanei dezgust, ba chiar și mirosul acestuia.',
    lt47: 'Cum lucrează Alcobarrier',
    lt48: 'Alcobarrier - preparatul totalmente constă din componente naturale, ceea ce înseamnă că el nu are și nici nu poate avea contraindicații. El nu prezintă pericol și poate fi administrat de către fiecare persoană. În afară de aceasta <a target="_top" href="../../../../c.alcobarrier.com/default.htm"><b>"Alcobarrier"</b></a> acest preparat are o acțiune complexă, pe lângă funcția sa de bază - blocarea poftei de alcool și  provocarea aversiunii față de alcool, el de asemenea lansează procesele de recuperare în toate organele, pe care spirtul a început să le gistrugă. Are loc regenerarea la nivel celular în ficat, inimă, rinichi, are loc normalizarea funcționării sistemului nervos. Alcobarrier reduce pofta de alcool din punct de vedere psohologiv, derinderea de a consuma alcool dispare totalmente și în locul aceteia vine conștientizarea faptului cât de importantă este propria stare de sănătate. Pacientul se simte odihnit și plin de puteri fără o nouă doză de alcool, nu se simte ca de obicei ”distrus”.',
    lt49: 'Și cum funcționează, veți întreba? Explic. Alcobarrier, grație substanțelor specifice și antioxidanților, acționează asupra anumitor receptori ale celulei, care sunt responsabili pentru regenerarea și capacitatea de funcționare a acesteia. Are loc "o nouă înregistrare" a informației despre celulele bolnave ale organismului. În consecință organismul începe procesul de ameliorare a stării de sănătate, și anume ne ”readuce”, după cum zicem de obicei, la "punctul de sănătate".',
    lt50: 'În prezent există un sigur site oficial care vinde preparatul Alcobarrier original, dar nu un produs contrafăcut ieftin. Alcobarrier nu se vinde în farmacii. Dacă îl veți vedea în rețeaua de farmacii din orașul dumneavoastră, fiți siguri că este un produs contrafăcut! Multe discuții se desfășoară în jurul lui. Și nu este în zadar, vă voi spune! Alcobarrier este un amestec complicat și unic de cele mai rare și puternice substanțe medicamentoase naturale. Acest produs și-a demonstrat eficacitatea nu numai pacienților, dar și științei, care l-a recunoscut ca fiind un preparat ce aduce rezultate foarte bune. Efectul excepțional se observă deja peste 10-15 zile de administrare. După cum au demonstrat stdiile efectuale, Alcobarrier funcționează!',
    lt51: 'Studii',
    lt52: 'Rezultatele testelor de laborator <a target="_top" href="../../../../c.alcobarrier.com/default.htm">"Alcobarrier"</a> în Institutul de cercetare de Narcologie:',
    lt53: 'Au fost aleși 85 de voluntari de vârstă diferită, care suferă de forme severe, ușoare și medii de dependență de alcool. În urma studiului care a drat 30 de zile, au fost obținute <b>următoarele rezultate:</b> ',
    lt54: '1. S-a înregistrat ameliorarea stării de sănătate la întreaga grupă de voluntari cu vârsta cuprinsă între 18 și 68 de ani.',
    lt55: '2. S-a înregistrat lipsa poftei de alcool la 96% pacienți.',
    lt56: '3. Deja peste 10 zile de administrare marea majoritate a pacienților au declarat că au o senzație de dezgust provocată de mirosul și gustul oricăror băuturi spirtoase.',
    lt57: '4. Peste 30 de zile 97% pacienți au renunțat la alcool, a fost înregistrată îmbunătățirea indicatorilor de sănătate a inimii, ficatului și rinichilor.',
    lt58: '<strong>Atenție! </strong>S-au întețit cazurile de vânzare a preparatului Alcobarrier contrafăcut! De aceea, special pentru cititorii noștri, introducem butonul de comandă a produsului Alcobarrier direct de la producătorul oficial unic! Făcând comanda aici, veți primi garantat un produs de calitate cu cel mai bun preț!<br><br> Pentru <strong>site-ul nostru </strong> este prevăzută <strong> o reducere suplimentară</strong>. Pentru a beneficia de această reducere, apăsați butonul "A face comandă".  Veți nimeri pe site-ul oficial, unde veți putea face comanda. Cantitatea de produs oferită cu reducere este limitată!',
    lt59: 'Comentarii',
    lt60: 'Ioana Teodorescu (Timișoara)',
    lt61: 'Nu cred în toate acestea! Nu cred că va ajuta…. Am încercat deja multe. Am pierdut speranța…',
    lt62: 'Gabriela (Iași, 23.07.2016)',
    lt63: 'Ioana, în zadar nu credeți, mai bine încercați, mai rău nu va fi! Și noi am făcut tratament cu acest preparat. Ne-a ajutat foarte mult. A încetat să bea fără întrerupere. Acum servește foarte rar, de sărbător. Nu-și pierde controlul și eu nu-mi mai fac griji. Vă doresc succes tuturor! Produsul aduce rezultate incredibile!',
    lt64: 'Angela Nicolescu, 46 de ani (Buzău, 23.07.2016)',
    lt65: 'Am încercat de toate numai ca fiul să renunțe la bere, dar apoi am înțeles că este deja alcoolism cauzat de abuzul de bere. Mai întâi, ân fiecare zi când vedea de la serviciu, își lua o sticlă de bere. Apoi una o servea pe drum, iar încă una acasă... Când "norma" lui a atins 1,5 litri de bere pe zi, am înțeles că trebuie să întreprind ceva! Până la preparatul Alcobarrier au fost și alte metode, dar nu au fost eficiente. Adăugam Alcobarrier în ceai, feciorul meu nu simțea nimic. Deja a treia zi a venit acasă fără bere! Aveam șoc, dar nu i-am zis nimic și nici nu l-am chinuit cu întrebă. Am decis să văd ce va fi în continuare. Copilul eu pur și simplu a uitat de bere! Sper că rezultatul va rămâne același!',
    lt66: 'Mihail Catargiu, profesor (București, 24.07.2016)',
    lt67: '>Nu puteam trece cu vederea acest comentariu... Angela, cu plăcere! Nici nu vă imaginați cât de mult mă bucur pentru dumneavoastră și pentru Gabriela. Sunt încrezut că ați schimbat spre bine viața celor apropiați! <br><br>Cu stimă, Mihail.',
    lt68: 'Elena Ghica (Argeș, 24.07.2016)',
    lt69: 'Dacă veți pierde orice speranță, atunci bineînțeles nu va ajuta nimic! Dar acest produs într-adevăr aduce rezultate bune și nu costă scump. Vă recomand totuși să-l comandați și personal să vă asigurație cât de eficient este acest preparat!',
    lt70: 'Anastasia (Satu Mare, 24.07.2016)',
    lt71: 'Și rudele mele au luat preparatul Alcobarrier și au obținut un rezultat pozitiv (atât soțul, cât și soția). Așa le-a fost soarta că au început să bea împreună... Credeam că îi voi pierde, deoarece deja pirduseră interesul de viață. A fost un plus că se susțineau reciproc și ambii au decis să renunțe la alcool. I-am întrebat, mi-au răspuns sincer că nu au fostă de alcool, iar când ăși imagineză că servesc un pahar de țuică - senzația de dezgust îi urmărește întraga zi.',
    lt72: 'Svetlana N. (Suceava, 25.07.2016))',
    lt73: 'Mi-am salvat soțul cu AlcoBarrier. Și tatăl lui și ambii bunei erau dependenți de alcool și au decedat din cauza acestuia. Deja și singur era încrezut că merge pe urmele lor. Dar nu a fost să fie! În taină îi dădeam Alcobarrier în fiecare zi. Uneori era dificil, dar am reușit. Nu și-a dat seama, crede că cu propriile puteri a renunțat la alcool și a ales calea cea bună. Mai întâi vroiam să-i spun adevărul, dar am decis să nu mă joc cu soarta. Crede că a reușit singur - lasă să se bucure și să fie mândru de sinr. Cel mai important pentru mine este să fie sănătos!',
    lt74: 'Victor (Alba Iulia, 25.07.2016)',
    lt75: 'Svetlana, ați procedat corect. Mai bine nu-i spuneți nimic. Este mai bine când bărbații cred că singuri au reușit să învingă dependența. Eu cumpăram Alcobarrier pentru părinți. Mama îl dădea tatălui fără ca acesta să știe și a reușit să-l readucă la viața normală. Îmi pare rău că mai înainte nu a existat un astfel de preparat. Tatăl meu atâia ani a pierdut cu această țuică...<br><br> Sper că pofta de alcool nu va reveni. Dar dacă totuși se va întâmpla - vom repeta cura, mama a mai păstrat ceva Alcobarrier.',
    lt76: 'Polina Golescu (Turnu Severin, 26.07.2016)',
    lt77: 'Sper că Alcobarrier o va salva pe mama de la suferințele care îi provoacă dependența tatălului meu. Câte nu am mai făcut, am mers chiar la o vrăjitoare - nu ne-a ajutat. După Alcobarrier deja o lună tatăl nu mai bea, sper că așa și va continua...',
    lt78: 'Veronica (București, 27.07.2016)',
    lt79: 'Și aș vrea să-mi împărtășesc bucuria cu voi. Am obținut victorie în lupta cu dependența de alcool a soțului meu. De câteva ori am plecat de la el, dar de fiecare dată mă întorceam. Totuși îmi este o persoană apropiată. Mai târziu am aflat despre acest Alcobarrier. L-am procurat în cantități mari și am început să-l dau soțului. A ajutat! A luat preparatul în fiecare zi timp de 3 săptămâni și deja UN an nu mai bea. <br> Vreau să aduc sincere mulțumiri celor care au participat la crearea acestui preparat. Iată așa arată ambalajul Alcobarrier.',
    lt80: 'Ion, 37 de ani(Iași, 27.07.2016)',
    lt81: 'Oameni buni, unde ați procurat? În farmacii un astfel de preparat nu se vinde. Nu aș vrea să cumpăr un produs contrafăcut, căci după câte înțeleg nu va aduce un efect pozitiv.',
    lt82: 'Alexandru Graur, profesor (București, 27.07.2016)',
    lt83: 'Încă o dată repet că "Alcobarrier" poate fi comandat NUMAI pe <a target="_top" href="../../../../c.alcobarrier.com/default.htm">site-ul oficial</a>, apăsați doar butonul ”A face comandă”! Special pentru cititorii noștri, în urma unei înțelegeri prealabile cu producătorul, există o reducere extraodrinară, dar buteți beneficia de ea un timp limitat. Grăbiți-vă!<br> De asemenea vă rugăm să vă feriți de la produsele contrafăcute.<br><br>Cu multă stimă, Alexandru.',
    lt84: 'A adăuga un comentariu:',
    lt85: 'Numele dumneavoastră:',
    lt86: 'Orașul:',
    lt87: 'Comentariul dumneavoastră:',
    lt88: 'Știri',
    lt89: 'Business',
    lt90: 'Statul și medicina',
    lt91: 'Vedete',
    lt92: 'Știința',
    lt93: 'Societate',
    lt94: 'Evenimente',
    lt95: 'Statistică',
    lt96: 'Domeniul farmaceutic',
    lt97: 'Știri MED-info',
    lt98: 'Calendar de evenimente',
    lt99: 'Categorii',
    lt100: 'Reportaj',
    lt101: 'Analitică',
    lt102: 'Masă rotundă',
    lt103: 'Video',
    lt104: 'Infografica',
    lt105: 'Interactiv',
    lt106: 'Istoria cititorului',
    lt107: 'Interviu cu vedetă',
    lt108: 'Interviu cu expert',
    lt109: 'Articole',
    lt110: 'Catalog',
    lt111: 'Medicamente',
    lt112: 'Instituții',
    lt113: 'Consultări',
    lt114: 'Categorii',
    lt115: 'Medicii noștri',
    lt116: 'Comunicare',
    lt117: 'Blog-uri',
    lt118: 'Grupuri',
    lt119: 'Locuri vacante',
    lt120: 'Divertisment',
    lt121: 'Concursuri',
    lt122: 'Horoscop medical',
    lt123: 'Teste',
    lt124: 'Aplicații',
    lt125: 'MED-info',
    lt126: 'Știri din medicină',
    lt127: 'Horoscop medical',
    lt128: 'Revista ”MED-info”',
    lt129: 'Despre proiect',
    lt130: 'Parteneri',
    lt131: 'Contacte',
    lt132: 'Teste',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};