var new_lang = {
lt1: 'Reich werden und nicht versoffen werden :papay1000',
lt2: 'LiveJournal',
lt3: 'Zeitschrift AlcoBarrier',
lt4: 'Shop',
lt5: 'Hilfe',
lt6: 'Enter',
lt7: 'ANMELDUNG',
lt8: 'Deutsch (de)',
lt9: '11. Platz nach Einschätzung in Deutschland',
lt10: 'loggen Sie ein mit Account im Facebook:',
lt11: 'Name des Users:',
lt12: 'papay1000 schreibt',
lt13: '‘vor 3 Tagen',
lt14: 'Reich werden und nicht versoffen werden ',
lt15: 'Das Geld kommt nicht von ungefähr, um was zu haben, muss man arbeiten bei Tag und Nacht – ewige und einfache Wahrheit. Wollen Sie Geld haben, sehr geehrte Herren? Dann Kniescheiben und Brustwarzen und schuften Sie wie ein Galeerensklave bis dem Sonnenuntergang!',
lt16: 'Ich habe Geld, indem ich es verdiente, wurde ich fast versoffen. Wenn man eine Firma leitet, wenn man überalles selbst denkt und für alles verantwortlich ist, sind Strass und Spannung ständig. Diejenige, die denken, dass eigen Unternehmen leicht ist, sind dumm. Von der 24-Stunden-Arbeit wird man wahnsinnig. Um Gehirn zu entspannen, begann ich ein wenig zu trinken. Am Abend sitzt man vor dem Laptop, ein bisschen Wein und alles wir klar und einfach, das Kopf ruht sich aus. Unbemerkbar schnell wurde es für mich gewöhnlich, bald stellte ich meinen Abend nicht anders vor. Dann bemerkte ich, dass am Tag ich dasselbe mit Vergnügen tun möchte, aber Status und Pipapo, verboten. <b>Jetzt verstehe ich, dass da ich bloß fast versoffen wurde.</b> Irgendwie unerwartet bekam ich Interesse zu allen Partys. Ich kann nicht trinken, trinke bis Besinnungslosigkeit, na und - wennschon, dennschon. Und so lebte ich. Bei einer solcher “Partys”, ich glaube, dass es Neujahrstage waren, fühlte ich mich schlecht. Schmerzen im Herzen, so heftig, ich konnte nicht atmen, ein jäher Schmerz rechtsseitig. Ich stelle nur vor, wie ich da aussah, meine Freunde riefen einen Krankenwagen sofort...',
lt17: 'Ich kam heil davon. In dem Krankenhaus nahm man Probe, sah, leuchtet durch, <b>meine Diagnose - destruktive Veränderungen der Leber, kurz gesagt, fast Zirrhose.</b> Ausgezeichnete Neuigkeit, wenn man nur 35 ist! Ehrlich gesagt, war ich erschrocken. Ich entschied, ich trinke nicht mehr. Dann stellte es sich heraus, dass es nicht so einfach ist, ich hab schon eine Angewöhnung. Irgendeine Unbedeutendheit, Wirre, sofort möchte ich trinken. Es reißt mich in allen Gliedern, bittere Kopfschmerzen, also konnte ich nicht selbst aufhören, ich schaffte es nicht. Nein, denke ich, es geht nicht so, ich kam zu einem Narkologe und setzte mir einen Präparat ein. Es war keine “Todesampulle”, einfach wenn Alkohol in den Körper geriet, geht es mir so schlecht, dass ich nicht mir leben will, höllische Schmerzen. Das Allerärgste ist, dass ich schon nicht konnte nicht trinken, IMMER WOLLTE ICH TRINKEN. Nachdem ich zum 2. Mal trank und hatte ich zum 2. Mal das Gefühl, dass meine Kopf jetzt zerplatzt, Herz steht still und ich jetzt abkratze, da sag ich dem Narkologen, damit der den Präparat aus mich herausgenommen hat. Jammerlappen, im Spiegel sah ich immer einen Jammerlappen. Nichts, Knalltüte, der mit eigenem Körper nicht fertig werden kann, willenloser Stück Fleisch. Ich hasste mich für meine Kraftlosigkeit, aber ich konnte nichts damit machen. <b>Ich zerstörte meinen Körper und konnte nicht damit aufhören.</b> Mein Zustand war „auf dem Boden“. Ich weiss nich, womit das alles sich beenden konnte, und ich will nicht darüber denken…',
lt18: 'Onkel eines meiner Freunde(Narkologe) empfiehl mir die Tropfen <b>AlcoBarrier</b> zu trinken, um die Leber zu unterstützen. Und er beölt sich, so, sagt er, wirst du nicht sofort fertig. Sehr lächerlich. Und ich entschied diese Tropfen zu trinken. Alkohol stellte ich nicht ab, aber in zwei Wochen bemerkte ich, dass mein Zustand sich verbesserte. Ich wurde munterer, und die Laune auch.., allmählich fiel mir die Binde von den Augen. <b>Zauber, aber ich wollte nicht trinken, den schwachen Drang, der noch da war, konnte ich leicht kontrollieren.</b> Dieses herzerschütternde Gefühl - sehen, fühlen, wie dein Körper vor deinen Augen vor dem Dreck befreit, der ihn tötete! Ich war sogar stolz auf mich, ich kann, ich bin kein Jammerlappen, ich habe Willenskraft! Nach einem Monat oder mehr sogar Geruch des Alkohols machte mich auf. Kaif-Gefühl von alkoholischer Vergessenheit verschwand. Die Tage, die ich darauf verschwendet habe, sind verloren, verstand ich irgendwie plötzlich. Ich verstand, dass ich frei bin. Onkel meines Freunds sagte dann ehrlich, dass er mich absichtlich betrogen hat. <br><b>Die Tropfen <ahref="" target="_blank" class="underline">AlcoBarrier</a> das ist ein Mächtiges Mittel gegen der alkoholischen Abhängigkeit,</b> aber ich so zu sagen bin nicht gekränkt, ich bedanke ihn, dass er nicht gleichgültig war und mir half. ',
lt19: 'Ich hörte nicht total auf, ich trinke manchmal, aber ohne Ausschweifung und Tranksucht, Ich tue es um kein Spielverderber zu sein. Es stellte sich heraus, dass Stress beseitigen auch folgende angenehme Dinge: Sport, Sex, Spaziergang, und noch was solches, früher dachte ich nicht darüber. Und noch bemerkte ich, dass ich viel ruhiger wurde, in meinem Innere erschien Ruhe und Frieden und das gefällt mir, ich verliere nicht die Nerven umsonst und ich schlafe ausgezeichnet. ',
lt20: 'Das ist meine Geschichte. Für meinen Wohlstand und Blödheit habe ich mit meiner Gesundheit gezahlt. Ich hoffe, dass Sie leichter drumrumkommen, aber in jedem Fall, um etwas zu bekommen, muss man was geben. Viel Erfolg!',
lt21: 'Neuigkeiten des Blogs abonnieren',
lt22: 'Markers:',
lt23: 'Alkoholismus',
lt24: 'Trinken aufhören',
lt25: '442 Kommentare',
lt26: 'Viktor42',
lt27: '‘vor 3 Tagen',
lt28: 'Viele Trinker verstehen nicht, dass sie Trinker sind, sie meinen, dass sie immer aufhören können, hat sich was! Hier braucht man starken Stress, damit man endlich verstand oder Zwangsbehandlung',
lt29: 'ANTWORTEN',
lt30: 'AlexFray',
lt31: '‘vor 3 Tagen',
lt32: 'Wo haben Sie AlcoBarrier gekauft? Ich kann nicht finden.',
lt33: 'papay1000',
lt34: '‘vor 3 Tagen',
lt35: 'Bestellt nut auf<ahref="" target="_blank" class="underline"><b>offizielle Website</b></a>, alles anderes sind Verfälschungen.',
lt36: 'Bernd_Krass',
lt37: '‘vor 3 Tagen',
lt38: 'Na ja… alle wollen alles leicht und problemlos bekommen. Nur nicht arbeiten, aber so geschieht nicht…',
lt39: 'tom.kalden',
lt40: '‘vor 3 Tagen',
lt41: 'Man sollte meinen, dass wenn man arbeitet, wie ein Kuli verdient man viel. Gesundheit verliert man, und die Taschen sind leer. In unserem Land kann man nicht viel verdienen… Unternehmerschaft  pass auch nicht jedem, man brauch eine gewisse Denkart dazu.',
lt42: 'Johann Mayrhofer',
lt43: '‘vor 2 Tagen',
lt44: 'AlcoBarrier half mir und meiner Familie, befreite mich! Ich trank sehr stark fast 10 Jahre, ich kam zur Besinnung nur als meine Frau mit unseren Kinder zu ihrer Mutter wegging. Ich kam zu einem Narkologe, er verschrieb mir diese Tropfen. Ich glaubte nicht, dass es so leicht ist  sich vom Alkohol zu befreien! Selbstverständlich war zuerst Dyskomfort, ich wollte trinken, es war abe kein Entzug oder Depresssion, nichts dergleichen. Ich duldete ein wenig, ich trank diese Tropfen während eines Monats und jetzt trinke ich nicht über 3 Jahre. Danke meinem Doktor und den Tropfen!',
lt45: 'retyx67',
lt46: '‘vor 2 Tagen',
lt47: 'Jetzt habe ich bestellt, na warten wir',
lt48: 'jungermann900',
lt49: '‘vor 2 Tagen',
lt50: 'ich weiss nicht, ich glaube, das  ein Trinker der ist, der hinterm Zaun liegt, und wenn man arbeitet kann er trinken, macht nichts, er hat recht dazu!',
lt51: 'Jobst46',
lt52: '‘vor 2 Tagen',
lt53: 'Ich will trocken werden, aber ich kann nicht, ich habe nicht genug Charakter. Ich habe Angst, dass ich bald meine Familie und meine Arbeit verliere, vor mir ist irgendein Abgrund..',
lt54: 'OttoDAN',
lt55: '‘vor 2 Tagen',
lt56: 'AlcoBarrier ist das wirksamste Mittel gegen Alkoholismus, das ich probiert hat! Nur dieses Mittel half mir! Ich trank es fast 2 Monate, aber das Ergebnis ist cool! Wer wirklich will trocken werden, dem empfehle ich, ihr findet nicht besser!',
lt57: 'DanIELstavo_chik',
lt58: '‘vor 2 Tagen',
lt59: 'Und was dann mit diesen Tropfen? Gute Laune und so was. rufen sie Angewöhnung hervor?',
lt60: 'papay 1000',
lt61: '‘vor 2 Tagen',
lt62: 'Keine Angewöhnung, ich trank einfach diesen Flakon und hörte auf. Nichts betäubendes in der Zusammensetzung, guck selbst auf der Website mal.',
lt63: 'Arthur-381',
lt64: 'vor 1 Tag',
lt65: 'Wie kann man in 35 Jahre Zirrhose bekommen? Trinken Sie von Kindheit an??',
lt66: 'papay1000',
lt67: 'vor 1 Tag',
lt68: 'Ich habe keine Zirrhose, und hatte nie. Abe wenn ich weiter tränke, so hätte ich die Zirrhose, ich habe es doch geschrieben.',
lt69: 'marlonbrando',
lt70: 'vor 1 Tag',
lt71: 'Das ekelhafteste ist, dass man nicht bemerkt, wie man Alkoholiker wird und man denkt immer, dass man zu jedem Zeitpunkt stoppt. Ich verstand dass es genug ist nachdem ich betrunken meine Beine abgefroren habe und ich habe sie fast verloren. Ich war in einer Klinik, aber da wurde ich fast drogenabhängig, beim Entzug bekam ich Morphin. Kurz gesagt, aber es war sehr schwer, jetzt trinke ich nicht. Ich hörte über diese Tropfen nicht, meinerzeit fand ich leider solch ein wunderbares Mittel nicht.',
lt72: 'demonWQ',
lt73: 'vor 1 Tag',
lt74: 'Ich verstand nicht früher, das es eine Problemist, ich dachte ich kann zu jeder Zeit aufhören. Aber als ich  meine Arbeit verloren hat und ohne Geld blieb, da verstand ich. Jetzt bekomme ich Behandlung, ich trinke auch AlcoBarrier, etwa 2 Wochen. Es hilft vom Alkohol abzugewöhnen, kein Entzug oder auch Depression, dieses Mittel ist billig und ausgezeichnet',
lt75: 'MILENA PETERSON_y',
lt76: 'vor 1 Tag',
lt77: 'Sag mal, liefert man diese Tropfennach Österreich oder nur in Deutschland?',
lt78: 'papay1000',
lt79: 'vor 9 Stunden',
lt80: 'fragen Sie auf der Website, ich meine es gibt Lieferung europaweit',
lt81: 'PavlikMorozov5000',
lt82: 'vor 5 Stunden',
lt83: 'O, so ein Super-Clever-Man. Freund, wie hast du gleichzeitig gesauft und Firma geleitet?',
lt84: 'papay1000',
lt85: 'vor 3 Stunden',
lt86: 'abge***t, habe ich geleitet. Ist es nicht verständlich?',
lt87: '4Annette-Schoemburg1',
lt88: 'vor 2 Stunden',
lt89: 'Blog ausgezeichnet! Danke sehr! Es ist sinnvoll für einige zu lesen und zu verstehen, dass sie nicht so klug sind)',
lt90: 'Wie sieht Bauch der Dreifach-Mutter? War und ist',
lt91: 'Körper von Britney Spears. Etwas über Scham und Faulheit',
lt92: 'Lesen Sie uns:',
lt93: ' Lesen Sie uns auf Facebook',
lt94: 'Aktuelle Fassung',
lt95: 'Über Projekt',
lt96: 'Nutzungsvereinbarung',
lt97: 'Über den Datenschutz',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};