var new_lang = {
lt1: 'Bioretin cremă contra ridurilor',
lt2: 'sigur și eficient',
lt3: 'Noi DEJA an fost apelați de <spanclass="bold">4672 persoane, </span> ca să ne spună MULȚUMESC!',
lt4: 'Consultație gratuită',
lt5: 'SUCCES REVOLUȚIONAR <br>ÎN LUPTA CONTRA RIDURILOR',
lt6: 'Reduce ridurile',
lt7: 'Restabilește elasticitatea',
lt8: 'Redă fermitatea contururile',
lt9: 'Reînnoirea celulelor ”adormite”',
lt10: 'Restabilirea celulelor deteriorate',
lt11: 'Regenerarea celulelor sănătoase',
lt12: 'PREȚUL NOU',
lt13: 'Datele dvs sunt protejate',
lt14: 'GRĂBIȚI-VĂ!',
lt15: 'Cutii la promoție au rămas:',
lt16: 'CÂȚI ANI ARE PIELEA DVS?',
lt17: 'Se consideră că este un singur indiciu al bătrâneții – ridurile. Dar dvs știți, că ridurile sunt doar o parte a necazului.',
lt18: 'FIECARE NOUĂ PROBLEMĂ VĂ ADAUGĂ ANI LA NUMĂR',
lt19: 'Pliurile nasolabiale',
lt20: '+ 2 ani',
lt21: 'Ovalul feței lăsat',
lt22: '+ 3 ani',
lt23: 'Laba gâstei',
lt24: '+ 4 ani',
lt25: 'Ridul dintre sprâncene',
lt26: '+ 2 ani',
lt27: 'Pungi sub ochi',
lt28: '+ 1 an',
lt29: 'Pielea are propria sa vârstă. Ea diferă  de a noastră. Pielea este doar foarte vulnerabilă, este  expusă maximum distrugerii de către timp, spre deosebire de alte organe. După 35 de ani pielea îmbătrânește foarte repede! De vină sunt: gravitația, ereditatea, starea proastă a ecologiei, razele ultraviolete, radiația, stresurile și alimentația incorectă. Calculați, câți ani are pielea dvs acum.',
lt30: 'Marcați punctele cu care sunteți de acord.',
lt31: 'Introduceți <br>vârsta dvs reală',
lt32: 'Eu am pliuri nasolabiale',
lt33: 'Pielea și-a pierdut din elasticitate',
lt34: 'Ridurile mimetice sunt pronunțate',
lt35: 'Sunt câteva riduri adânci',
lt36: 'Acum pielea dvs are:',
lt37: 'Indicați',
lt38: 'vârsta dvs',
lt39: 'Aici vor apărea toate recomandările noastre, după ce veți completa formularul',
lt40: 'Se recomandă:',
lt41: '57 unități de toxină botulinică',
lt42: '5 cursuri de tratament mezoterapie',
lt43: 'corecția chirurgicală a feței',
lt44: 'sau trei cursuri de tratament cu crema Bioretin',
lt45: '47 unități de toxină botulinică',
lt46: '4 cursuri de tratament mezoterapie',
lt47: '48 fire bio',
lt48: '1 curs de tratament cu agent de umplere',
lt49: '37 unități de toxină botulinică',
lt50: '3 cursuri de tratament mezoterapie',
lt51: '38 fire bio',
lt52: '1 curs de tratament cu agent de umplere',
lt53: 'sau 2 cursuri de tratament cu crema Bioretin',
lt54: '17 unități de toxină botulinică',
lt55: '2 cursuri de tratament mezoterapie',
lt56: '28 fire bio',
lt57: 'sau 1 curs de tratament cu crema Bioretin',
lt58: 'DE CE SĂ ARĂTAȚI MAI ÎN VÂRSTĂ DECÂT SUNTEȚI, DACĂ PUTEȚI ARĂTA MAI TÂNĂRĂ?',
lt59: 'MULT MAI TÂNĂRĂ, FĂRĂ DURERE ȘI RISC!',
lt60: 'femeile regretă că au acceptat să facă injecții și intervenții chirurgicale',
lt61: 'siguranța și eficacitatea dovedită a NOII FORMULE a Bioretin împotriva îmbătrânirii',
lt62: 'Magia ia naștere sub ochii dvs',
lt63: 'Fără precedent. Uimitor. Impresionant.',
lt64: 'Readuce cei mai frumoși ani ai vieții și tinereții',
lt65: 'Bioretin – INOVAȚII și REZULTAT',
lt66: '— o cremă revoluționară care conține ”peptide semnal” ce sunt capabile să ”ridice din adâncurile” pielii celulele tinere.',
lt67: 'Astfel, crema stimulează activ elaborarea de colagen și regenerarea ”matricei” intercelulare. Aceasta face posibilă <span class="pink">netezirea vizibilă a ridurilor mimetice</span> pe frunte, în regiunea gurii și ochilor (”laba gâștei”).',
lt68: '— este un ”coktail” impresionant pentru corectarea pliurilor nasolabiale și dintre sprâncene.',
lt69: 'Conține componente, care sunt create pentru ”creșterea volumului” în locul de acționare, ceea ce <span class="orange">va umple ridurile rine și pliurile din interior</span>, "împingând" pielea înapoi. Și deasemenea ”relaxează” micro-contracțiile mușchilor, pentru a împiedica mușchii de a plia pielea între sprâncene.',
lt70: '— conține unul dintre cei mai puternici antioxidanți, care neutralizează radicalii liberi – principala cauză a îmbătrânirii.',
lt71: 'Inhibă dezintegrarea colagenului, mai simplu vorbind, luptă cu îmbătrânirea prin metoda protejării celulelor de distrugere. Stimulează circuitul sanguin în limfă pentru micșorarea umflăturilor, ”pungilor” și diminuării cercurilor întunecate de sub ochi. Fortifică structura pielii, <span class="blue">redă fermitatea reliefului, ovalului feței,</span> din contul elaborării naturale de colagen și elastină.',
lt72: 'ACIDUL HIALURONIC + PROPILEN GLICOL',
lt73: 'EXTRACT DE ZMEURĂ + ASCORBIL FOSFAT DE MAGNEZIU',
lt74: 'PROVITAMINA B%+ALANTOINĂ',
lt75: 'ACID LACTIC + EXTRACT DE LĂMÂIE',
lt76: 'EXTRACT DE LEVĂNȚICĂ+EXTRACT DE PELARGONIUM',
lt77: 'comandați la',
lt78: '89% de femei au început să arate acea vârstă, pe care o simt în suflet!',
lt79: 'După 40 de ani regenerarea celulelor începe să se încetinească. Apar tot mai multe riduri, pielea pierde din elasticitate, contururile feței devin mai puțin clare. Metoda revoluționară împotriva îmbătrânirii Bioretin a fost creată special pentru îngrijirea pielii în curs de ofilire.',
lt80: 'Acțiunea triplă a Bioretin este confirmată de cercetări clinice la scară largă:',
lt81: 'femei',
lt82: 'Au remarcat o reducere considerabilă a ridurilor și liniilor privirii încruntate (cu 77%), la colțul ochilor (cu 56%) și pe frunte (cu 76%)',
lt83: 'femei',
lt84: 'S-a umplut volumul în pliurile nasolabiale, volumul în regiunea pomeților a fost restabilit (+41%). <br>Ovalul feței este vizibil mai clar, pielea este mai fermă și plină de volum.',
lt85: 'femei',
lt86: 'Rezultate vizibile<br>Tonusul pielii crește(+65%), ea este mai compactă (+54%) și hidratată pentru 48 de ore.',
lt87: 'Produsul este certificat deplin',
lt88: 'Vezi certificatul',
lt89: 'UN SONDAJ DE OPINIE LA SCARĂ LARGĂ A ARĂTAT CĂ <br> CEI ÎMBĂTRÂNIȚI SUNT IGNORAȚI ȘI NEGLIJAȚI',
lt90: 'NU LI SE ATRAGE <br>ATENȚIA',
lt91: '74% de bărbați',
lt92: 'au răspuns sincer că femeile cu riduri și semne de ofilire pe față nu pot fi atractive sexual.',
lt93: 'LIMITĂ <br>DE CARIERĂ',
lt94: '67% dintre angajatori',
lt95: 'nu vor angaja și nu vor propune o avansare unei femei care arată mai în vârstă de 45 de ani',
lt96: 'INFIDELITAREA<br>SOȚULUI',
lt97: '96% din soți',
lt98: 'și-au lăsat soțiile pentru o amantă mai tânără și din cauza că soția a încetat să se îngrijească.',
lt99: 'Cercetarea a confirmat: 87% de bărbați afirmă că vârsta femeii nu contează, ci este important ca femeia să arate îngrijită și tânără. Aceasta o face atractivă sexual în ochii bărbatului și îi aduce respect din partea lor.',
lt990: 'Luați timpul în propriile mâini',
lt100: 'DEVENIȚI CU <span class="orange">10 ANI MAI TÂNĂRĂ ÎN 2 LUNI</span>',
lt101: 'Pliurile nasolabiale <br>AU DISPĂRUT în 24 de zile',
lt102: 'Ridul dintre sprâncene A DISPĂRUT în 19 zile',
lt103: 'Ovalul lăsat A DISPĂRUT în 30 de zile',
lt104: 'Ridurile ”laba gâștei” AU DISPĂRUT în 21 de zile',
lt105: 'Pungile de sub ochi AU DISPĂRUT în 14 zile',
lt106: 'OPINIA INDEPENDENTĂ A COSMETOLOGILOR',
lt107: 'Tamara Agapie <br>Medic cosmetolog-dermatolog <br> Stagiul de practică 18 ani',
lt108: 'Dacă aș fi în locul cosmetologului Dvs, atunci, desigur, m-aș strădui să vă propun maximumul din ceea ce știu și din ceea ce este accesibil tehnologiilor de frumusețe: botox, plasmolifting, agenți de umplere ș.a.m.d. Dar, ca om, ca femeie, eu înțeleg că prin folosirea Bioretin toate aceste proceduri pot fi amânate cu încă 6 ani.',
lt109: 'Permiteți pielii Dvs să devină mai tânără! ',
lt110: 'Valentina Micu<br>Asistent superior<br>al chirurgului plastician<br>Stagiu de practică 7 ani',
lt111: 'Eu recomand a nu se grăbi cu injecțiile, operațiile și alte intervenții traumatizante. Lăsați această idee pentru peste 20 de ani. Doar încercați Bioretin și peste 1 lună veți înțelege că revoluția în medicina estetică a avut loc. Cosmeteutica (cosmetica medicinală) – este viitorul frumuseții și tinereții, de care putem să ne folosim chiar acum și putem să-i savurăm rezultatele.',
lt112: 'Și lăsați-i să  creadă că aceasta se datorează operațiilor plastice...',
lt113: 'În toate saloanele românești de prestigiu deja demult se folosește Bioretin. <br> O procedură compusă din scrub (exfoliere), masaj facial și aplicare de cremă costă aproximativ 150 de euro',
lt114: 'APRECIERI SINCERE. <br>Recomandat de femei reale.',
lt115: 'În anul 2016 au fost vândute mai mult de 3 000 000.<br> Dvs deja ați comandat pentru sine Bioretin?',
lt116: 'a fost investit în crearea Bioretin',
lt117: '4 ani',
lt118: 'în desfășurarea<br> cercetărilor',
lt119: '3 ani',
lt120: 'pentru crearea <br>formulei',
lt121: 'eficacitate',
lt122: 'femei <br>fericite',
lt123: 'specialiști activi',
lt124: '3 certificate',
lt125: 'de calitate UE, RTS, ISO',
lt126: 'a componentelor <br>naturale',
lt127: 'ATENȚIE!',
lt128: 'În legătură cu popularitatea produsului în România și în Europa au devenit frecvente cazurile de vânzare a falsurilor la preț de nimic!',
lt129: 'Fiți atenți!',
lt130: 'Pe ambalajul original va fi obligatoriu indicat codul de bare cu numărul de autentificare!',
lt131: 'Dacă lipsește codul de bare, adresați-vă cu o plângere, scriindu-ne pe adresa poștală indicată în josul paginii. Vă vom compensa pierderile și vom urmări excrocii comform legii.',
lt132: 'CUM LUCRĂM',
lt133: 'Faceți o comandă chiar acum și obțineți<span class="discount">50%</span>reducere.',
lt134: 'Așteptați apelul operatorului pentru precizarea detaliilor',
lt135: 'Nu plătiți nimic până la recepționarea coletului',
lt136: 'Acceptăm comenzi <span class="red">în toată România și Europa</span>',
lt137: 'Reduce ridurile',
lt138: 'Restabilește elasticitatea',
lt139: 'Redă fermitatea contururile ',
lt140: 'Înnoirea celulelor ”adormite',
lt141: 'Restabilirea celulelor deteriorate',
lt142: 'Regenerarea celulelor sănătoase',
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};