var new_lang = {
lt0: 'Koupit Tinedol levně. Ceny, recenze. Objednejte si Tinedol nyní!',
lt1: 'Vyrobený <br>pomocí <br>nano-technologií',
lt2: 'Schváleno Národní <br>asociaci dermatologů',
lt3: 'Kontaktovat bezplatnou linku',
lt4: 'ZAPOMEŇTE NAVŽDY',
lt5: 'NA PLÍSNĚ, SVĚDĚNÍ A <br>PRASKLINY NOHOU!',
lt6: 'Zbavuje příznaky plísně s prvním použitím',
lt7: 'Úplně zbavuje plísně za 1 kurz léčení',
lt8: 'Zbavuje svědění, olupování kůže a podráždění nohou',
lt9: 'Odstraňuje nepříjemný zápach',
lt10: 'Normalizuje fungování potních žlaz',
lt11: 'Zahojuje rány a praskliny na nohou',
lt12: 'SLEVA',
lt13: 'Řada je omezená, pospěšte si <span>objednat se slevou</span> v tomhle měsíci!<br>',
lt14: 'Řada je omezená, pospěšte si <span>objednat se slevou</span> v tomhle měsíci!<br>',
lt15: 'Do konce akce zbývá:',
lt16: 'Hodin',
lt17: 'Minut',
lt18: 'Sekund',
lt19: 'Původní cena:',
lt20: 'Cena po slevě v tomhle měsíci:',
lt21: 'Objednat',
lt22: 'Vaše údaje jsou chráněné',
lt23: 'stálé si myslíte, že vám nehrozí riziko?<br>Prověřte sebe, zda nemáte jeden z těchto symptomu. A pokud máte alespoň jeden  z nich, tak OKAMŽITĚ ZAČNĚTE LÉČBU!!!',
lt24: 'Nepříjemý, kyselý zápach',
lt25: 'Svědění a podráždění v oblasti chodidel',
lt26: 'Praskliny na patách a loupání kůže na nohou',
lt27: 'Puchýře a červenání na chodidlech',
lt28: 'Špatný tvar nehtu, boulovitý',
lt29: 'Necitlivost a brnění nohou',
lt30: 'Změna barvy nehtu od růžového k žlutému (hnědý)',
lt31: 'Tvrdnutí nehtů',
lt32: 'Bílé skvrny a brázdičky na nehtech',
lt33: 'Otlačeniny, ztvrdnutí na chodidlech',
lt34: 'Co očekávát, pokud nebudete léčit plíseň na chodidlech?',
lt35: 'Podle průzkumu, každý třetí obyvatel našeho státu se alespoň jednou setkal se symptomy plísně. A každý pátý má tohle onemocnění. Plíseň se rychle vyvíjí, pokud nosíte těsnou obuv z nepřírodních materiálů, ponožky z syntetiky, a také pokud pravidelně chodíte do sauny, bazénu. V létě je toto nebezpečí na pláží, v parku, kde lidé chodí na boso a dokonce i ve vašem sprchovém koutu!',
lt36: 'ZASTAVTE ŠÍŘENÍ NEMOCI! OCHRAŇTE SVÉ ZDRAVÍ!',
lt37: 'První etapa plísňové infekce:',
lt38: '<i></i>Diskomfort při chůzi',
lt39: '<i></i>Nepříjemný zápach',
lt40: '<i></i>Zvýšené pocení',
lt41: '<i></i>Stálé svědění',
lt42: '<i></i>Stálé loupání',
lt43: 'Druhá etapa plísňové infekce:',
lt44: '<i></i>Silné svědění při chůzi',
lt45: '<i></i>Ztvrdlá kůže',
lt46: '<i></i>Hluboké praskliny na patách',
lt47: '<i></i>Stálý nepříjemný zápach',
lt48: '<i></i>Křehké nažloutlé nehty',
lt49: 'Třetí etapa plísňové infekce:',
lt50: '<i></i>Hnisavé praskliny',
lt51: '<i></i>Ztráta nehtů',
lt52: '<i></i>Jizvy a hluboké krvavé praskliny',
lt53: '<i></i>Loupání kůže mezi prsty',
lt54: '<i></i>Bílé šupinky kůže',
lt55: 'Pokud neléčit plíseň na chodidle, tak můžete zanedbat hodně nebezpečnou nemoc! Představte si, jak se trápíte bolestmi, svěděním a ošklivým vzhledem a zápachem vašich nohou.Chcete, aby se to vám přihodilo? TAK ŘEKNĚTE „NE“ PLÍSNI!',
lt56: 'Protiplísňová mast, <span>OBOHACENÁ O IONTY STŘÍBRA</span>',
lt57: 'Jak funguje <span class="title4-span1">mast Tinedol?</span>',
lt58: 'Při pravidelném použití, Tinedol odstraňuje řadu problém s kůží nohou. Obsahující ve složení látky pomůžou z prvního použití a navždy ODSTRANÍ:',
lt59: 'Plíseň',
lt60: 'Nepříjemný zápach',
lt61: 'Pocení',
lt62: 'Praskliny',
lt63: 'Ztvrdlou kůži',
lt64: 'Svědění a diskomfort při chůzi',
lt65: '<span class="consist__text--b">Klimbazol</span> — zastavuje rozvíjení kvasnic a plísně. Odstraňuje svědění. Má ničivý účinek na plísně.',
lt66: '<span class="consist__text--b">Farnezol</span> — “vypíná” potní žlázy. Dezinfikuje, vysušuje, dodává příjemnou vůni na delší dobu.',
lt67: '<span class="consist__text--b">Propolis</span> - má silné protibakteriální účinky.',
lt68: '<span class="consist__text--b">Olej Čajovníku</span> -proniká hluboko do podkožní vrstvy, zahojuje problémové oblasti, dodává chládek a odstraňuje nepříjemné zápachy po náročnému pracovnímu dni.',
lt71: 'Mast navždy zbavuje plísně a diskomfortních pocitů v nohou, které pronásledují každého, kdo se alespoň jednou setkal s plísni.',
lt72: 'Mast se rychle vstřebává, nemá výraznou vůni a rovnoměrně se rozmísťuje po celém povrchu chodidla. Nezanechává skvrny a není potřeba proplachovat vodou. Stačí nanest mast na oba chodidla (vnitřní a vnější část), masírovacími pohyby vetřít mast a počkat 1-2 minuty až se vstřebá do kůže nohou.',
lt73: 'Omezená řada!<br>Pospěšte si!<br> Pouze <span class="product-how-much"><span class="lastpack"></span> balení</span> <br>za speciální cenu!',
lt74: 'Tinedol – je jednoduchý způsob, jak se zbavit plísně NAVŽDY!',
lt75: 'Původní cena:',
lt76: 'Cena po slevě v tomhle měsíci:',
lt77: 'Omezená řada! Pospěšte si!<br>Pouze <span class="product-how-much--all"><span class="lastpack"></span> balení</span> za speciální cenu!',
lt78: 'Uveďte vaše údaje do pole níže',
lt79: 'CO SE STANE S VAŠIMI CHODIDLY PO 30 DENNÍM POUŽÍVÁNÍ MASTI Tinedol',
lt80: 'Navždy se zbavíte plísně na nohou a chodidlech',
lt81: 'Zbavíte se pocitu diskomfortu a svědění na nohou',
lt82: 'Vaše nohy přestanou nepříjemně smrdět',
lt83: 'Budete cítit měkkost a pohodlí při chůzi',
lt84: 'Vaše nohy se přestanou silně potit',
lt85: 'Kůže nohou se obnoví a bude hebčí a hladší',
lt86: 'Nehty se promění v dokonalý stav',
lt87: 'Budete mít krásné nohy, které se nebudete stydět ukázat na pláži nebo v bazénu',
lt88: 'JAK SPRÁVNĚ POUŽÍVAT MAST Tinedol',
lt89: 'Umyjte nohy, utřete do sucha. Naneste tenkou vrstvu mastičky na celé chodidlo, zevnitř a zevnějšku. Vetřete mast do kůže nohou, počkejte až se vstřebá (1-2 minuty). Zopakujte procedúru každý večer před spaním, během 30-35 dní. A již po skončení kurzu použití <strong>uvidíte, jak se mění vaše kůže a nohy se stavají ZDRAVÝMI!</strong>',
lt90: 'Řada je omezená, pospěšte si objednat se slevou v tomhle měsíci!<br>Pouze <span class="product-how-much"><span class="lastpack"></span> balení</span> <br>za speciální cenu!',
lt91: 'Proč mast Tinedol je účinnější než jiné masti proti plísně?',
lt92: 'Protiplísňové přípravky se dělí na 2 kategorii: buď nepomáhají, nebo pomáhají jen dokud je využíváte. Pokud jste se setkali s plísni, tak asi rozumíte o co jde,  a stále používáte nefunkční a neúčinné krémy a masti.',
lt93: '<strong>Tinedol</strong> úplně mění názor ohledně protiplísňových příprvků. Velké laboratorní testy ukázaly, že tahle mast dost účinně odstraňuje plíseň na nohou a nehtech. Po prvním kurzu použití, plíseň zmizí navždy. Tenhle efekt se dosahuje jen díky upraveným složkám.',
lt94: 'Názor expertu - dermatologu',
lt95: 'Po pořadným testováním masti <strong>Tinedol</strong> mohu s jistotou říct, že je to hodně účinný přípravek. Hlavní v této masti je -  komplexní péče o kůži. Pokud máte jen jeden nebo několik příznaků,měli byste <strong>už teď</strong> použít mast <strong>Tinedol</strong>, aby předejít nebezpečným následkům plísňové infekce. Pamatujte si, že plíseň chodidel se obejvuje náhle a rozvíjí se hodně rychle! Dnes máte diskomfort a lehké krátkodobé svědění a zítra už můžete brát antibiotika a léčit se v klinice. NEODDALUJTE LÉČENÍ! Odstraňujte problém při prvních symptomech. A pamatujte si! Plíseň – je nejvíc nakažlivá infekce. Stačí se dotknout ložiska infekci a už máte riziko se nakazit, a to znamená i nakazit vaši rodinu!',
lt96: '— Alexandr Bílý<br>kandidát lékařských věd, 1.LF UK. Doktor- dermatolog, kosmetolog, mykolog.',
lt97: 'Recenze',
lt98: 'Vždycka jsem myslel, že plíseň se mě nikdy nedotkne.  Ale když jsem mi po bazénu začly se česat nohy, myslela jsem, že jsem se nakazil... Předtím, než jsem začal používat Tinedol, jsem vyzkoušel hodně přípravku, které na krátkou dobu mě zbavily česání a prasklin. Ale pomáhalo to na několik dní. Nakonec, kdy se moje paty praskly a začly krvacet jsem šel k doktorovi. A předepsali mi Tinedol. Teď se nebojím zouvat na pláži!<br>Děkuji!',
lt99: 'Marie, Brno',
lt100: 'Kdy se moje paty praskly,jsem si vzpomněla, že moje babičky a dědečkové mají stejné. Ale jim už je skoro 70 let, a mně je jen 28! Bylo to hrozný. Pak jsem pochopila, že je to plíseň, hlavně v ten okamžik, kdy praskliny se začaly česat. Vzpomněla jsem si, že jsem chodila měsíc do bazénu bez žabek, a pochopila jsem odkud mám plíseň. Nakonec jsem zjistila u známé, že ji pomohl Tinedol, vyzkoušela jsem si to a je to! Zase paty jsou jako u malého dítěte!!!',
lt101: 'Anička, Liberec',
lt102: 'Dlouho jsem se snažila zbavit se plísně octem, dokud jsem nespálila kůži. Bylo to hrozný a nepříjemné. A plíseň je můj stálý problém, protože se mi moc potějí nohy. U mamky jsem zjistila o Tinedol, pomohl ji se zbavit svědění po prvním použitím. Mama řekla, že pokud budu mazat 3 měsíce tak i zmizí plíseň. TAK SE TO I STALO! Děkuji mámě a výrobci Tinedol!',
lt103: 'Kateřina, Plzeň',
lt104: 'Doručení poštou',
lt105: 'nebo kurýrem',
lt106: 'Ochrana údajů je zaručená.',
lt107: 'Platba při převzetí.',
lt108: 'Jak pracujeme:',
lt109: 'Objednávejte',
lt110: 'na webu',
lt111: 'Kontaktujeme',
lt112: 'vás',
lt113: 'Posíláme Váš',
lt114: 'balík',
lt115: 'Platíte pří',
lt116: 'převzetí',
lt117: 'Naše operatoři online',
lt118: '24 hodin denně bez víkendu - objednávejte!',
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};