var new_lang = {
    lt1:  '- 100%-ban biztonságos és hatékony.',
    lt2:  'Nekünk <span class="blue">MÁR</span> telefonált 4 672 ember, hogy megrendeljék<span class="blue">KÖSZÖNJÜK!</span>',
    lt3:  'Ingyenes konszultáció kérése',
    lt4:  '<span class="big">Bioretin:</span> legfőbb társunk<span class="blue">a kor elleni harcban</span>',
    lt5:  '<span class="blue">Eltávolítja a</span>ráncokat',
    lt6:  '<span class="blue">Visszaállítja a</span> fiatalságot',
    lt7:  '',
    lt8:  '<span class="blue">Meghúzza</span> a kontúrokat',
    lt9:  '<span class="violet">Megújítja az</span> "alvó" sejteket',
    lt10: '<span class="violet">Helyrehozza a</span> megsérült sejteket',
    lt11: '<span class="violet">Regenerálja az</span> egészséges sejteket',
    lt12: 'ára<br><span class="bold">1 EURÓ*</span>',
    lt13: 'Akciós ár*:<br><span class="big">1 EURÓ*</span>',
    lt14: 'Régi ár:',
    lt15: 'az akció végéig maradt:',
    lt16: 'nap',
    lt17: 'óra',
    lt18: 'perc',
    lt19: 'másodperc',
    lt20: 'FIGYELEM! A csomagok száma korlátozott.',
    lt21: 'Maradt: ',
    lt22: ' db.',
    lt23: '* Egy kúra megvásárlása esetén',
    lt24: 'Hány éves a bőre?',
    lt25: 'Úgy gondolja, hogy az öregedés jele csak a ráncok. De Ön nem tudja, hogy a ránc az csak a probléma fele. <span class="red"> MINDEN ÚJ PROBLÉMA IDŐSEBBÉ TESZI ÖNT!</span>',
    lt26: 'Orr, száj körüli barázdák.',
    lt27: '+6 év',
    lt28: ' Ovális elváltozás.',
    lt29: '+5 лет',
    lt30: ' Szarkalábak.',
    lt31: '+4 év',
    lt32: 'Szemöldök közötti barázdák.',
    lt33: '+7 év',
    lt34: 'Táskás szemek.',
    lt35: '<span class="violet">A bőrnek saját kora van.</span> Különbözik a miénktől. Mert a bőr sokkal érzékenyebb, mint a többi szervünk. 35 év után a bőr nagyon gyorsan öregszik! Ennek az okai: gravitáció, örökség, rossz ökológia, ibolyántúli sugárzás, radiáció, stressz és helytelen táplálkozás. <span class="red">Számolja ki, hogy a bőre hány éves most.</span> <span class="underline"> Válassza ki a képen azokat az elváltozásokat, amelyek már megjelentek az Ön arcán.</span>',
    lt36: 'Írja be az igazi korát:',
    lt37: 'Nekem van orr - száj körüli barázdám:',
    lt38: 'A bőrőm elveszítette a fiatalságát:',
    lt39: 'Vannak mimikai ráncaim:',
    lt40: 'Van néhány mély ráncom:',
    lt41: 'Írja le a korát',
    lt42: 'Javasolt: 17 egység botulinum toxin, 2 mezoterápia kúra, 28 bionit<br><span class="white">VAGY 1 Bioretin krém kúra</span>',
    lt43: 'Javasolt: 37 egység botulinum toxin, 3 mezoterápia kúra, 38 bionit, 1 kúra<br><span class="white">VAGY 2 Bioretin krém kúra</span>',
    lt44: 'Javasolt: 47 egység botulinum toxin, 4 mezoterápia kúra, 48 bionit, 1 kúra<br><span class="white">VAGY 3 Bioretin krém kúra</span>',
    lt45: 'Javasolt: 57 egység botulinum toxin, 5 mezoterápia kúra, műtési beavatkozás<br><span class="white">VAGY 3 Bioretin krém kúra</span>',
    lt46: 'minek nézzen ki idősebben, a korához képest, ha ',
    lt47: 'ki tud nézni fiatalabban?',
    lt48: 'SOKKAL FIATALABBAN, FÁJDALOM ÉS KOCKÁZAT NÉLKŰL!',
    lt49: 'nő megbánta, hogy elfogadta az injekciókat és a műtéteket',
    lt50: 'bizonyítottan biztonságos és hatékony',
    lt51: 'A LEGÚJABB Bioretin FORMULA',
    lt52: 'az öregedés ellen',
    lt53: 'VISSZANYERNI AZ ÉLET LEGJOBB ÉVEIT ÉS A FIATALSÁGOT',
    lt54: 'Bioretin - INNOVÁCIÓK és EREDMÉNY	',
    lt55: 'Bioretin az egy innovációs krém, amely gyógyító olajokat tartalmaz, ami kedvez a bőrnek, vitaminokat és galiron savat tartalmaz, táplálja és fiatalítja a bőr mély rétegeit, stimulálja a hámszövet növekedését.',
    lt56: ' A krém aktívan stimulálja a kollagén termelését és az intercellurális „mártrix” regenerálódását. Ennek következtében <span class="violet"> a homlok, a száj barázdái és a szem szarkalábai észrevehetően kisimulnak. </span><br><span class="orange">Bioretin - egy elképesztő "koktél" az orr-száj barázdák és a szemöldök ráncok kisimításáért </span>',
    lt57: ' Olyan összetevőket tartalmaz, amelyek un."térfogat növelők", amelyek <span class="violet"> belülről betöltik a ráncokat </span> "visszaállítják" a bőr eredeti állapotát. Hozzájárul még az izmok pihenéséhez, hogy megakadályozzák a barázdák kialakulását a szemöldökök között.',
    lt58: 'Bioretin - tartalmazza az egyik legerősebb antioxidánst, amely a szabad gyököket semlegesíti, ami az egyik legfontosabb öregedést okozó tényező.',
    lt59: 'Gátolja a kollagén lebomlását, vagyis a sejtek pusztulását gátolja, így lassítja az öregedést. Serkenti a vérkeringést a nyirokrendszerben, hogy a szem alatti „táskákat” eltüntesse. Megerősíti a bőr strukturáját, <span class="violet"> erősíti a bőr szerkezetét, meghúzza az arc kontúrját,</span> a kollagén és az elasztin természetes termelése miatt ',
    lt60: 'Hyaluro-sav',
    lt61: 'Orgánolaj',
    lt62: 'Avokádóolaj',
    lt63: 'Glicerin',
    lt64: '',
    lt65: 'Szenzációs hatás  - Bioretin.',
    lt66: ' A nők 89%-a kezdett úgy kinézni a krém hatására, mint amilyen korúnak érezte magát.',
    lt67: '40 év után a sejtek regenerációja lassulni kezd.',
    lt68: 'Egyre több ránc jelenik meg, a bőr elveszíti a rugalmasságot, az arc kontúrjai észrevehetetlenebbek lesznek. A forradalmi öregedés gátló hatását a Bioretin készítménynek kifejezetten a bőr fiatalítására fejlesztették ki.',
    lt69: 'Bioretin háromszoros hatásával egyet ért:',
    lt70: '1183 nő',
    lt71: 'a kutatás szerint="violet">jelentős csökkenést érzékelt</span> a ráncok és a ráncos vonalak kialakulásában(77%), a szemek sarkában ( 56%) és a homlokon ( 76%)',
    lt72: '927 nő',
    lt73: ' szerint az orr - száj körüli barázdák eltűntek',
    lt74: ' és az arc ovális kontúrja feltöltődött (+41).<br> Így az arc ovális kontúrja megerősödött.',
    lt75: '1321 nő',
    lt76: ' szerint látható eredmény, hogy <br><span class="violet">a bőr tónusa megnőtt (+65%),</span>  teltebb lett (+54%) és 48 órán át hidratált.',
    lt77: '<span class="red">ÓRIÁSI KISÉRLET AZT MUTATTA -</span> HOGY AZ ÖREGEKET "LEÍRJÁK"',
    lt78: 'NEM FIGYELNEK RÁJUK',
    lt79: 'A férfiak 74% -a őszintén bevallotta, hogy a ráncokkal rendelkező nők nem vonzóak szexuálisan.',
    lt80: ' MUNKAHELY HOZZÁÁLLÁSA ',
    lt81: '67%-a a munkáltatóknak nem veszi fel és nem ad előrelépési lehetőget azoknak a nőknek, akik 45-nél idősebbnek néznek ki.',
    lt82: 'FÉRJ MEGCSALÁSOK',
    lt83: ' A férjek 96% elhagyta a feleségüket, mert nem figyeltek oda a külsejükre.',
    lt84: 'A vizsgálat megerősítette: a férfiak 87%-a azt mondja, hogy <span class="red"> egy nő életkora nem számít.</span> Fontos viszont, hogy a nő <span class="red"> jól ápolt és vonzó legyen.</span> Így lesz a nő a férfi szemében <span class="red">szexuálisan vonzó és kivívja a tiszteletet.</span>',
    lt85: 'Vegye az időt a kezébe',
    lt86: 'LEGYEN <span class="red">10 ÉVVEL FIATALABB</span> 2,5 KÚRA UTÁN',
    lt87: 'Orr-száj körüli barázdák <span class="orange">ELTŰNTEK</span> 2 kúra alatt',
    lt88: 'Szem alatti szarkalábak<span class="orange">ELTŰNTEK</span> 3 kúra alatt',
    lt89: 'Szemöldök közötti barázdák<span class="orange">ELTŰNTEK</span> 2 kúra alatt',
    lt90: 'Arc amorf alakja<span class="orange">ELTŰNT</span> 1 kúra alatt',
    lt91: 'Szem alatti táskák<span class="orange">ELTŰNTEK</span> 1 kúra alatt',
    lt92: 'KOZMETOLÓGUSOK FÜGGETLEN VÉLEMÉNYE',
    lt93: 'Németh Angéla<br>Orvos kozmetológus- dermatológus<br>18 éve dolgozik',
    lt94: 'Ha én az ön kozmetológusa helyében lennék, akkor azokat a kezeléseket javasolnám, ami elérhető számomra és amit ismer a mai kozmetológia: <span class="violet">botox, plazmolofting, fillerek és stb.</span> De mint ember, mint nő én megértem, hogy <span class="violet">Bioretin segítségével mindezt elhalaszthatja akár még 6 évig is.</span>', 
    lt95: 'És azt gondolják, hogy ez műtétek eredménye...',
    lt96: 'Kis Katalin<br>Sebész fő aszisztense<br>7 éve dolgozik',
    lt97: 'Én azt javaslom, hogy ne siessenek az injekciókkal, műtétekkel és más szépészeti beavatkozásokkal. Azt javaslom, hogy ne rohanjon injekciós kezelésekre, műtétekre és egyéb beavatkozások elvégzésére. Hagyja ezt az ötletet 20 évvel későbbre. Csak <span class="violet">probálja ki Bioretin és 1 hónap múlva látja, hogy a változás megtörtént.</span> Kozmetika -  a szépség és a fiatalság jövője, amit mi alkalmazni tudunk már most.',
    lt98: 'Engedje meg hogy a bőre fiatalabb legyen!',
    lt99: 'Minden budapesti szalonban <span class="blue">már használnak Bioretin -t.</span> Egy arckezelés és masszázs krém nélkül kb. 20.000Ft',
    lt100:'IGAZI VISSZAJELZÉSEK',
    lt101:'Igazi nőknek javasolt.',
    lt102:'2016 alatt már több mint 3 000 000 db került eladásra.',
	lt103:'Már megrendelte a Bioretin -jét?',
    lt104:'Anna, Pest megye',
    lt105:'Viktória, Esztergom',
	lt106:'Veronika, Veszprém',
    lt107:'12 000 000 $ -ba került a Bioretin kifejlesztése',
    lt108:'év kellett a kisérletek elvégzéséhez',
	lt109:'év kellett a formula kifejlesztéséhez',
    lt110:'műkődő szakértő',
    lt111:'százalék hatás',
	lt112:'százalék boldog nő',
    lt113:'minőségi tanúsítvány ЕС, РТС, ISO',
    lt114:'természetes összetevő',
	lt115:'VIGYÁZAT!',
    lt116:'Mivel híres Magyarországon és Európában, gyakori a hamisítvány!<br>Legyenek óvatosak! A hivatalos csomagoláson lesz kód, amin leszenek számok! Ha a kód nincs rajta, írjon postán arra a címre, ami a csomag alján található. Mi kifizetjük az Ön veszteségét és eljárunk a csalók ellen törvényes úton.',
    lt117:'Hogyan dolgozunk?',
	lt118:'LÉPÉS 1',
    lt119:'Indítsa el gyorsan rendelést <span class="red">akciós áron</span>',
    lt120:'LÉPÉS 2',
	lt121:'Várja meg a hívást a részletek megbeszéléséhez.',
    lt122:'LÉPÉS 3',
    lt123:'Ön semmit sem fizet, amíg meg nem kapja a csomagot',

};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};