var new_lang = {
   lt1: 'AlcoBarrier – medio eficaz para luchar el alcoholismo',
   lt2: 'AlcoBarrier – <br/> medio eficaz <br/>para luchar el alcoholismo',
   lt3: 'AlcoBarrier – <br/> diga <span>«NO»</span> al alcoholismo!',
   lt4: 'Elimina la adicción al alcohol',
   lt5: 'Ayuda a las células dañadas del hígado a recuperarse ',
   lt6: 'Desintoxica el cuerpo',
   lt7: 'Calma el sistema nervioso',
   lt8: 'Insípido e inodoro',
   lt9: 'La oferta especial se termina en…',
   lt10: 'Сomprar',
   lt11: 'AlcoBarrier – Medio eficaz que desintoxica el organismo y elimina la adicción al alcohol. Ácido succínico y fibregum son los ingredientes de AlcoBarrier que desintoxican el cuerpo después de haber bebido el alcohol y que tienen un efecto tónico. El componente único – extracto de alcachofa - elimina la dependencia psicológica al alcohol. La fórmula patentada de AlcoBarrier incluye la vitamina B6, cuya deficiencia se observa en los organismos de todos los adictos al alcohol. Gracias a esta vitamina se elimina la psicosis alcohólica y es más fácil dejar el consumo del alcohol. <br> AlcoBarrier es insípido e inodoro y se disuelve fácilmente en agua. Por eso no provoca el rechazo y la adicción',
   lt12: '<span>¿Cómo funciona</span> AlcoBarrier?',
   lt13: '<div class="item-title">Fibregum</div> Desintoxica el organismo y mejora el funcionamiento del tracto gastrointestinal',
   lt14: '<div class="item-title">Extracto de alcachofa</div> elimina la adiccion al alcohol, tiene efecto hepatoprotector y de desintoxicación',
   lt15: '<div class="item-title">Extracto de leonurus</div> calma el sistema nervioso, ayuda a desintoxicar el cuerpo',
   lt16: '<div class="item-title">Ácido succínico </div> reduce el efecto toxico de alcohol, elimina Resaca, mejora el funcionamiento del corazón',
   lt17: '<div class="item-title">La vitamina В6</div> mejora el estado mental, reduce la adicción al alcohol',
   lt18: 'AlcoBarrier',
   lt19: 'probado',
   lt20: 'en la práctica',
   lt21: 'En el año 2016 fue realizado el estudio, en el cual 1.000 voluntarios que sufrían del alcoholismo, durante un mes regularmente tomaron AlcoBarrier.',
   lt22: 'Según los resultados del estudio un 25% notó una reducción significativa en la adicción al alcohol y el mejoramiento del organismo, y un 75% de los sujetos dejó de beber por completo! De acuerdo con los resultados del estudio se muestra una mejora significativa en los parámetros hepáticos, el estado del sistema cardiovascular y nervioso',
   lt23: 'Nuestra bebida mostro eficacia a todos los voluntarios, independientemente de la gravedad de la enfermedad y la duración de la ingesta de alcohol',
   lt24: 'Después de divorciarme, yo bebía cada día durante unos meses y perdí mi trabajo. Entendía todo, pero no pude hacer nada. Mi hermano acudió en mi ayuda y me hizo tomar AlcoBarrier. Insistió que yo lo tomara con regularidad. Ahora puedo decir con confianza que no soy adicto al alcohol. Si tu o tus amigos tienen aquel problema, tomen AlcoBarrier. ¡Realmente ayuda!',
   lt25: 'Francisco, 40 años',
   lt26: 'Antes, mi marido bebía con menos frecuencia, pero después se convertió en una adicción. Sin embargo, no quería admitir que estaba enfermo. Mi amiga nos recomendó AlcoBarrier para luchar al alcoholismo. Empecé a añadir AlcoBarrier en su bebida, porque es insípido e inodoro. Luego, su adicción se eliminó. ¡Ahora está sano!! ¡Gracias a AlcoBarrier!',
   lt27: 'Daniela, 53 años',
   lt28: 'Mi padre tuvo una adicción al alcohol muy fuerte. Muchas veces tuvimos que recurrir a la ayuda de los médicos, quienes lo devolvieron a su estado normal. Mi madre y yo compramos AlcoBarrier y empezamos a añadirlo a sus bebidas. Desde hace tres meses mi padre no bebe nada de alcohol, pero no sabe por qué. ¡Si tienen el mismo problema, compren AlcoBarrier! ',
   lt29: 'Jorge, 35 años ',
   lt30: 'Narcólogos recomiendan AlcoBarrier',
   lt31: '«Recomiendo AlcoBarrier a todos mis pacientes y a las personas quienes quieran dejar de beber. La herramienta no sólo elimina el deseo psicológico del alcohol, sino también restaura el cuerpo, tiene un efecto positivo en el hígado, el corazón, los riñones y el sistema nervioso. Complejos efectos ayudan a mis pacientes a dejar de beber y volver rápidamente a la normalidad»',
   lt32: 'López А.А., psiquiatra-narcólogo de la categoría más alta',
   lt33: 'AlcoBarrier – <br/> medicina única y certificada',
   lt34: 'AlcoBarrier no contiene GMO, clínicamente probado y no causa efectos secundarios.',
   lt35: '90% de AlcoBarrier – componentes naturales',
   lt36: ' AlcoBarrier no aumentó el nivel de azúcar en la sangre, y les conviene a los diabéticos',
   lt37: 'AlcoBarrier pasó la certificación, lo que confirma su alta calidad y seguridad',
   lt38: '¿Cómo utilizarlo?',
   lt39: 'Es muy fácil de utilizar – <br/> Es un <span>polvo <br/> instantáneo</span>',
   lt40: 'El efecto positivo se observa <br/> <span>desde el primer día.</span> Se recomienda <br/> utilizar una vez al día.',
   lt41: 'Entrego y pago',
   lt42: 'Recibirás AlcoBarrier en dos o tres días después de comprarlo (en Madrid y Barcelona). Entregamos a otras regiones dentro de 14 días. ¡Pagas cuando lo recibas!',
   lt43: '¡Cuidado con falsificaciones!',
   lt44: '¡El producto se vende en el empaque original con un código de registro único! <br> Encuentra el código en el paquete y comprueba su autenticidad.',
   lt45: 'comprobar el código',
   lt46: '¿Cómo comprar AlcoBarrier?',
   lt47: 'rellena el formulario',
   lt48: 'elige el método de entrega',
   lt49: 'paga al recibirlo',
   lt50: 'descuento -50%',
   lt51: 'el precio antiguo',
   lt52: 'la oferta <br/> se termina',
   lt53: 'Nombre <small>Por ejemplo: Jose Maria Aznar</small>',
   lt54: 'Teléfono <small class="phone_helper">por ejemplo: +34 600 69 93 88</small>',
   lt55: 'Comprar',
   lt56: 'Producto <br/> es aprobado',
   lt57: 'Garantía <br/> del resultado',
   lt58: '',
   lt59: 'Pedido: <font size="6">4986</font>',
   lt60: 'Tenemos: <font size="6">14</font>',
   lt61: 'Deja un pedido!',
   lt62: '¡Oferta!',
   lt63: ' La oferta especial <strong>AlcoBarrier</strong> <br /> <br /> solo por <span class="newprice price_main">1490 euros</span>!',
   lt64: 'Nombre:',
   lt65: 'Por ejemplo:',
   lt66: 'Teléfono:',
   lt67: 'Producto: <span style="color:#F00;">AlcoBarrier</span>',
   lt68: 'Precio: <span class="newprice price_main">1490 euros</span>',
   lt69: '*La solicitud no le obliga comprarlo',
   lt70: ' ¿Le gustó esta oferta? ',
   lt71: 'Мы расскажем Вам все об этом товаре, предложим наилучшие условия и ознакомим с подходящими акционными предложениями! Le hablaremos todo de este producto y ofreceremos las mejores ofertas especiales',
   lt72: 'Le llamaremos dentro de 15-30 minutos'
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};