var new_lang = {
lt1: 'ALCOBARRIER – c’est un nouveau outil efficace pour la lutte contre l`alcoolisme ',
lt2: 'ALCOBARRIER – <br/> un outil efficace <br/> pour la lutte contre l`alcoolisme ',
lt3: 'ALCOBARRIER – <br/> dit <span>«NON»</span> à la dépendance de l`alcool!',
lt4: 'Diminue le besoin d`alcool',
lt5: 'Répare les cellules du foie',
lt6: 'Élimine les toxines du corps',
lt7: 'Apaise le système nerveux',
lt8: 'N`a pas de goût et d`odeur',
lt9: 'Jusqu`à la fin de l’action il vous reste',
lt10: 'Commander',
lt11: 'ALCOBARRIER – un outil efficace, qui élimine les toxines du corps et finit l’addiction à l`alcool. L`acide succinique et le fibregum qui sont dans la composition ХХа dérivent les toxines de l`organisme après l`ingestion de l’alcool. Ils ont aussi une action fortifiant. Un composant végétal unique - l`extrait d`artichaut – retire la dépendance psychologique à l`alcool. Dans une formule brevetée ХХа il y a une vitamine B6, dont l`absence a été observée chez tous les alcooliques. Grâce à compenser cette vitamine dans l’organisme, la psychose alcoolique est retirée et ça devient plus facile de renoncer de l`alcool. ALCOBARRIER n`a pas de goût et d`odeur et se dissout facilement dans l`eau. C’est pourquoi il ne provoque pas de rejet ou de dépendance.',
lt12: '<span>Comment fonctionne-t-il?</span> ALCOBARRIER',
lt13: '<div class="item-title">Le fibregum</div> élimine les toxines du corps et améliore le fonctionnement du tractus gastro-intestinal',
lt14: '<div class="item-title"> L`extrait d`artichaut </div> désamorce l’addiction à l`alcool. De plus, il a un effet hypertoprotecteur et de désintoxication',
lt15: '<div class="item-title"> L`extrait de l`agripaume</div> apaise le système nerveux et aide à soulager l`intoxication alcoolique',
lt16: '<div class="item-title"> L`acide succinique</div> réduit les effets toxiques de l`alcool, enlève la gueule de bois, améliore le fonctionnement du cœur ',
lt17: '<div class="item-title">Une vitamine В6</div> améliore l`état mental, aide de sortir de l’addiction à l`alcool ',
lt18: 'ALCOBARRIER',
lt19: 'est testé',
lt20: 'dans la vie réelle',
lt21: ' En 2016, on a fait une recherche, au cours de laquelle 1000 volontaires l`alcoolique prenaient régulièrement ALCOBARRIER pendant un mois.',
lt22: 'Selon les résultats de la recherche 25% de volontaires ont noté une grande réduction de l’addiction à l`alcool et l`amélioration de l`état de l`organisme. Donc 75% des alcooliques sont arrêtés de boire complètement! Selon les résultats de l`enquête on a observé une amélioration significative de la santé du foie, de l`état cardio-vasculaire et le système nerveux.',
lt23: 'La boisson a montré son efficacité chez 100% des volontaires qui ont n’importe quelle gravité de la maladie et durée de la consummation de l`alcool.',
lt24: 'Quand j’ai divorcé avec ma femme, je me déchaînais. Pendat quelques mois je buvais presque tous les jours, j’ai perdu ma vie, mais je ne pouvais rien faire. Merci à mon frère qui m’a bcp aidé. Il m`a fait prendre ALCOBARRIER. Il a insisté, et a veillé à ce que je l`ai pris régulièrement. Maintenant, je peux dire avec confiance que je n’ai plus aucune envie de prendre l’acool. Si vous ou vos proches avez ce problème, essayez le ALCOBARRIER, il aide vraiment!',
lt25: 'Pierre, 40 ans',
lt26: 'Auparavant, mon mari ne buvait pas de l’alcool si souvent, mais puis ça est devenu une addiction. Cependant il ne voulait pas admettre qu`il était malade. Mon amie m`a conseillé d`essayer ALCOBARRIER. J`ai commencé à ajouter ALCOBARRIER dans ses boissons. Je pouvais le faire tranquillement grâce à l’absence de goût de ХХа. Après quelque temps le besoin de l`alcool a disparu. Maintenant, il s`est débarrassé de son addiction! Merci aux développeurs de ХХа!',
lt27: 'Camille, 53 ans',
lt28: 'Mon père avait la plus forte addiction à l`alcool, et pas seulement après la «célébration» on a dû aller aux médecins, qu`ils le retournaient à son état normal. Ma mère et moi nous avons commandé ALCOBARRIER et  commencé à ajouter à ses boissons sans le faire savoir. Maintenant, le père ne boit pas du tout de l’alcool depuis trois mois, et seulment moi et ma mère nous savons pourquoi. Si vous avez aussi ce terrible problème dans votre famille, utilisez le ALCOBARRIER!',
lt29: 'Louis, 35 ans',
lt30: 'Les toxicologues recommandent ALCOBARRIER',
lt31: '«Je recommande ALCOBARRIER à tous mes patients -quelqu`un qui sort de l’acoolisme, et quelqu`un qui en boit un peu, mais veut s’arrêter. Cet outil soulage non seulement les besoins psychologiques de l`alcool, mais restaure l`organisme et produit un effet positif sur le foie, le cœur, les reins, le système nerveux. Le traitement avec ALCOBARRIER aide mes patients à cesser de prendre de l’alcool et de revenir rapidement à une pleine vie»',
lt32: 'Paul Babinet, le toxicologue de la catégorie superieure ',
lt33: 'ALCOBARRIER – <br/> est un outil certifié unique ',
lt34: 'ALCOBARRIER ne contient pas d`OGM, il est vérifiée cliniquement et ne provoque pas d`effets secondaires.',
lt35: 'A 90% composée d`ingrédients à base sur des plantes naturelles `',
lt36: 'ALCOBARRIER n`augmente pas la glycémie et est adapté pour les diabétiques',
lt37: 'ALCOBARRIER a passé la certification attestante de sa qualité et de la sécurité',
lt38: 'Comment l’utilizer?',
lt39: 'Très facile à utiliser - <br/> c’est <span> une poudre <br/> soluble dans l`eau rapidement </span>',
lt40: 'L`effet positif est observé <br/> <span> à partir du premier jour de l`utilisation.</span> On recommande <br/> de prendre 1 fois par jour.',
lt41: 'La livraison et le paiement',
lt42: 'Vous recevrez ALCOBARRIER dans deux ou trois jours après la commande(pour les habitants de Paris).Dans les autres régions la livraison est effectuée dans 14 jours. Le paiement de la commande s`effectue lors de la réception! ',
lt43: 'Méfiez-vous des imitations!',
lt44: 'Le produit est vendu dans l`emballage d`origine avec un code d`enregistrement unique! <br> Trouvez le code sur l`emballage et vérifier son authenticité.',
lt45: 'Vérifier le code',
lt46: 'Comment commander ALCOBARRIER?',
lt47: 'Traiter une commande',
lt48: 'Choisissez le mode de la livraison ',
lt49: 'Payez le produit lors de la réception',
lt50: 'Rabais -50%',
lt51: 'L`ancien prix ',
lt52: 'Jusqu`à la fin de l’action<br/> il vous reste',
lt53: 'Nom Prénom <small>Par exemple: Paul Blanc</small>',
lt54: 'Numéro de téléphone <small class="phone_helper"> Par exemple: 01 48 06 43 68 </small>',
lt55: 'Commander', 
lt56: 'Le produit <br/> certifié',
lt57: 'La garantie <br/> du résultat',
lt58: '',
lt59: 'Déjà commandé: <font size="6">4986</font> pièces ',
lt60: 'Il y a encore: <font size="6">14</font> pièces ',
lt61: 'Mettez votre commande maintenant! ',
lt62: 'Action!',
lt63: 'Offre spéciale pour ce remède <strong>ALCOBARRIER</strong> <br /> <br /> juste pour <span class="newprice price_main">1490 руб</span>!',
lt64: 'Nom Prénom:',
lt65: 'Par exemple:',
lt66: 'Numéro de téléphone:',
lt67: 'Produit: <span style="color:#F00;">ALCOBARRIER</span>',
lt68: 'Prix: <span class="newprice price_main">1490 руб</span>',
lt69: '*Cette demande ne vous oblige pas à acheter ',
lt70: 'Aimez-vous cette offre?',
lt71: 'Nous allons tout vous dire sur le produit, offrir les meilleures conditions et présenter l`offre spéciale appropriée!',
lt72: 'L`opérateur vous rappellera dans 15-30 minutes',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};