
var new_lang = {
lt0: 'l’ipertensione (gli sbalzi di pressione ) nell’89% dei casi uccide il malato nel sonno ! 1,54 milioni di infatti nel 2016! Come salvarsi dalla morte causata dalla pressione alta con uno sconto del 50% - intervista al primario dell’istituto di cardiologia, la dottoressa Eleonora Vitale!',
lt2: 'Riceviamo sempre più lamentele,<br>collegate all’ IPERTENSIONE e collegate con le malattie da essa causate!<br>PEr questo per i cittadini del posto "ReCardio" è disponibile con lo sconto del 50%!<br>',
lt3: 'COMPRARE CON LO SCONTO',
lt4: 'Pagina succesiva',
lt5: 'Siete di Roma<span class="user-city"></span>? Aspettate!',
lt6: 'E’ da li che ci arriva il maggior numero di lamentele collegate con ipertensione e pressione alta, !<br>Per questo per i cittadini del posto "ReCardio" è disponibile con uno sconto del 50%!',
lt7: 'Ricevere lo sconto!',
lt8: 'Salute',
lt9: 'Attività',
lt10: 'Documenti',
lt11: 'Ufficio stampa',
lt12: 'Concorsi',
lt13: 'Home',
lt15: 'Ufficio stampa',
lt17: 'News',
lt19: 'Conferenza stampa speciala!',
lt20: 'L’ipertensione (sbalzi di pressione) - nell’ 89% dei casi uccide il paziente nel sonno! 1,54 milioni di infarti nel 2016 год!<span style="font-weight: normal;">Come salvarsi dalla morte per via di sbalzi di pressione con lo sconto del<span style="color:red;">50%</span>- Intervista con il primario dell’Istituto di Cardiologia</span>',
lt21: 'Introduzione: Gli infarti e gli ictus per via della pressione — sono la causa di quasi il 70% di tutte le morti al mondo. Sette persone su dieci muoiono per via di ostruzioni nelle arterie del cuore o del cervello. La causa è sempre praticamente la stessa, gli sbalzi di pressione dovuti all’ipertensione. L’"Assassino silenzioso", come lo hanno definito i cardiologi, ogni giorno si porta via diverse vite. Oggi pubblicheremo un’intervista con il primario dell’Istituto di Cardiologia  che ci racconterà cosa fare se avete sbalzi di pressione e non volete morire nel sonno.',
lt22: '<strong>Eleonora Vitale</strong><br>Dottoressa di scienze mediche, professore di scienze mediche, direttrice dell’Istituto di Cardiologia<br>Stage lavorativo - 25 anni',
lt23: '<i>Corrispondente</i>: "Dottoressa Vitale, Ci potrebbe illustrare qualche statistica riguardante le morti per sbalzi di pressione in Italia?"',
lt24: '<strong>Dottoressa Vitale:</strong>Non è un segreto per nessuno che le malattie del sistema cardiovascolare sono i leader mondiali tra le malattie per la quantità di vite che spendono.  L’ipertensione (sbalzi di pressione) è la causa principale di infarti ed ictus, tra le malattie del sistema cardiovascolare. Ovviamente anche altre malattie di questo tipo hanno pessimi effetto sull’organismo, ma è proprio l’ipertensione assieme ai problemi che comporta che solitamente porta le persone all’altro mondo .',
lt25: 'Se vogliamo parlare di dati statistici,circa il<strong>77-78% delle morti cosiddette "naturali" ha solitamente come causa scatenante l’ipertensione.</strong>In cifre assolute, parliamo di circa 1,54 milioni di morti nel 2016 e 1,49 milioni nel 2015.</strong>Ovvero si tratta di cifre enormi e spaventose. Fino a poco tempo fa nessuno poteva neanche sospettare un tale numero, perché non era mai stata effettuata un’analisi così accurata. Nel periodo di tempo tra il 2011 e il 2016 abbiamo ricevuto una massa enorme di dati, che ha dato questi risultati spaventosi.',
lt26: '<i>Corrispondente</i>: "E più precisamente in che modo gli sbalzi di pressione possono comportare conseguenze cosi grave?"',
lt27: '<strong>Dottoressa Vitale:</strong>Gli sbalzi di pressione ogni volta provocano un grande sforzo per il sistema cardiovascolare, e questo prima o poi comporta l’arresto cardiaco. In parole povere ogni volta che abbiamo uno sbalzo di pressione il cuore lavora tra le 10 e le 20 volte più del dovuto. Se vogliamo parlare di qual’è lo stadio finale della malattia<strong>l’ipertensione può portare ad un solo risultato, la morte</strong>’Se vogliamo calcolarla come causa effettiva della morte, ben l’89% delle morti al mondo è causa sua. Ovvero l’ 89% delle situazioni ipertoniche si concludono con infarto, ictus e morte. In più solo 20 – 30 anni fa i malati con questa diagnosi potevano vivere tranquillamente altri 10-20 anni, ora invece circa <strong>2/3 (due terzi) muore entro 5 anni dall’inizio dello sviluppo della malattia.</strong>',
lt28: 'La cosa peggiore è che la maggior parte delle persone nemmeno sospetta di soffrire di ipertensione . Perdono così la possibilità di curarsi fino a che c’è tempo, prima che sia troppo tardi.',
lt29: 'In base a questi sintomi potete accorgervi di soffrire di ipertensione:',
    lt30: 'Mal di testa',
    lt31: 'Battito cardiaco accelerato',
    lt32: 'punti neri davanti agli occhi (mosche)',
    lt33: 'Apatia, irritabilità, sonnolenza',
    lt34: 'Visione offuscata',
    lt35: 'Sudorazione',
    lt36: 'Stanchezza cronica',
    lt37: 'Viso gonfio',
    lt38: 'Perdita di sensibilità delle dita',
    lt39: 'Sbalzi di pressione',
lt40: 'Anche uno solo di questi sintomi dovrebbe farvi riflettere, e se<strong>invece sono almeno due non c’è da titubare, avete l’ipertensione</strong>Secondo i dati del Ministero il 67% dei malati di ipertensione non hanno il minimo dubbio di essere malati.',
lt41: '<i>Corrispondente</i>: "Ha detto che le persone perdono la possibilità di curarsi. Come si fa a curarsi? In che modo si può combattere la malattia?"',
lt42: '<strong>Dottoressa Vitale:</strong>Prima di tutto bisogna capire che è tempo di lasciarsi alle spalle un sacco di abitudini negative, soprattutto fumo e alchool . Questi non fanno che peggiorare la situazione con la pressione arteriosa. In seguito bisogna abbassare la pressione, non ci sono alternative. Ma questo non basta a curare la malattia. In più se si esagera con le medicine si rischia un brusco calo di pressione, che può provocare reazioni molto gravi da parte dell’organismo fino ad arrivare all’infarto stesso. Per non parlare dell’effetto che le pillole hanno sul fegato.',
lt43: 'Sostanzialmente al momento,<strong>l’unico preparato che viene raccomandato ufficialmente dai dottori per curare l’ipertensione e che viene usato regolarmente dai cardiologi per curare i pazienti è<a href="" target="_blank">ReCardio</a>che fortunatamente è distribuito con lo sconto del<span style="color:red;"> 50%</span>!</strong>Gli studi per perfezionarlo sono iniziati diversi anni fa e sono terminati da veramente poco. Un gruppo di specialisti si è occupato della creazione del preparato, lavorando a stretto contatto con cardiologi praticanti. Come risultato è stato creato un preparato unico nel suo genere, che in maniera affidabile "uccide" l’ipertensione liquidandone la causa principale, a differenza degli altri preparati simili.',
lt44: '<i>Corrispondente</i>: "Ci può raccontare qualcosa di più su<a href="" target="_blank">ReCardio</a>?"',
lt45: '<strong>Dottoressa Vitale:</strong>Senza entrare nei dettagli tecnici<strong>il preparato combatte alla radice la causa dell’ipertensione riuscendo così a curare completamente l’ipertensione. /strong>I sintomi scompaiono già 6 ore dopo l’assunzione del preparato, grazie al componente attivo. Questo da la possibilità di iniziare a vivere pienamente subito dopo l’assunzione .',
lt46: 'Il tono dei vasi sanguigni si ristabilizza rapidamente dopo aver iniziato l’assunzione. In più<a href="" target="_blank">ReCardio</a>è efficace a qualsiasi stadio dell’ipertensione. Il medicinale ha passato ogni test clinico. Voglio annotare che l’efficacia dimostrata durante la fase di sperimentazione lascia anni luce indietro qualsiasi altro tipo di preparato estero. Il miglior risultato ottenuto con preparati esteri è il 20-21% di casi curati. Nel nostro caso invece parliamo del 75-77% di casi curati. E nei casi restanti comunque la situazione si stabilizza. Ovvero l’ipertensione rimane ma in stato passivo (rimane il problema del tono dei vasi sanguigni). Ma nonostante ciò la pressione non balza e vi sentirete benissimo..',
lt47: 'Oltre all’Italia<a href="" target="_blank">ReCardio</a>ha superato i test clinici in Svizzera e in Germania, che ne hanno confermato allo stesso modo l’efficacia. Ora la richiesta per questo preparato è enorme. Ma<strong>grazie ad una direttiva particolare si vende solo all’interno della nostra nazione</strong>, e questo è collegato al fatto che la disponibilità è troppo piccola rispetto alla domanda..',
lt48: 'Allo stesso modo è stato effettuato un sondaggio che ha dato risultati stupefacenti',
lt49: 'Sondaggio:<span>come vi siete liberati dell’ipertensione?</span>',
lt50: 'Preparati medici:',
lt52: 'Preparato ReCardio:',
lt54: 'Medicina popolare:',
lt56: 'Sono alla ricerca di una soluzione:',
lt58: 'Non credo sia possibile:', 
lt60: '<i>Corrispondente</i>: "Dove si può acquistare<a href="" target="_blank">ReCardio</a>? Penso che questa domanda sarà nella testa di tutti i lettore. E che cosa diceva dello sconto del  50% ?"',
lt61: '<strong>Dottoressa vitale:</strong>Al momento il preparato è prodotto in piccoli partite, nonostante si stia già attrezzando con mezzi maggiori, che permetteranno di aumentare notevolmente la produzione. ',
lt62: 'All’inizio di quest’anno il produttore ha ricevuto un grande finanziamento che sta utilizzando per ingrandirsi. Così ha lanciato la vendita sul<a href="" target="_blank">sito speciale</a>per i pazienti che possono compilare online un modulo per ordinare<a href="" target="_blank">ReCardio</a>. In parole povere basta lasciare il proprio nome e il proprio numero di telefono, dopo di che verrete contattati per definire i dati,rispondendo a qualche domanda. La consegna avviene via posta.Pagate solo dopo aver ricevuto e controllato il pacco.<strong>Il sistema è trasparente e chiaro, il che lo rende molto comodo anche per chi ordina on line per la prima volta.</strong>IO stessa l’ho controllato e non ho trovato problemi. IL sito mostra perfino quante confezioni sono rimaste nel magazzino più vicino.',
lt63: '15 novembre a<script>document.write(((YMaps.location.city)?(YMaps.location.city):'Москва'));</script>Roma abbiamo lanciato un programma federale per la lotta contro l’ipertensione che si chiama "liberiamoci dell’ipertensione", che sarà attivo fino al<script type="text/javascript">d = new Date(); p = new Date(d.getTime() -0*86400000);monthA = 'Января,Февраля,Марта,Апреля,Мая,Июня,Июля,Августа,Сентября,Октября,Ноября,Декабря'.split(',');var w = p.getDate();document.write(p.getDate() + ' ' + monthA[p.getMonth()] + ' ' + p.getFullYear());</script>1 Dicembre 2017 compreso. Il prezzo del preparato fa veramente ridere, ma il nostro obbiettivo infatti non è guadagnarci su, vogliamo dare la possibilità ad ogni cittadino, indipendentemente da quella che è la sua situazione finanziaria, di liberarsi della malattia e vivere una vita serena!',
lt64: 'Scopo del programma: Salvare le persone dall’ipertensione, che non solo ne distruba la vita, ma la mette seriamente a rischio. Siamo orgogliosi di essere riusciti a lanciare un programma del genere nella nostra nazione! In nessuna nazione al mondo esiste qualcosa del genere!',
lt65: 'Importante!Si è scoperto che<script type="text/javascript">d = new Date(); p = new Date(d.getTime() -0*86400000);monthA = 'январь,февраль,март,апрель,май,июнь,июль,август,сентябрь,октябрь,ноябрь,декабрь'.split(',');var w = p.getDate();document.write(monthA[p.getMonth()]);</script>dicembre è il mese milgiore per curare ipertensione e sbalzi di pressione. Grazie alla stabilizzazione della temperatura media, si velocizza il metabolismo e la circolazione sanguigna, quindi l’effetto dell’assunzione del preparato aumenta La cura dell’ipertensione avviene al 47% più rapidamente di quanto sarebbe accaduto in un altro periodo.',
lt66: '<i>Corrispondente</i>: "C’è qualcosa che vorrebbe dire ai nostri lettori prima di concludere l’intervista?"',
lt67: '<strong>Dottoressa Vitale:</strong>L’unica cosa che voglio dire è, prendetevi cura della vostra salute. L’ipertensione ormai è un problema di massa. E vi ricordo che il<strong>67% dei malati di ipertensione neanche sospettano di avere un problema</strong>. Sarete d’accordo ch enon deve essere bello morire di una malattia che neanche si sapeva di avere. Controllate i sintomi, e se ci sono delle affinità rivolgetevi ad uno specialista o semplicemente curatevi con <a href="" target="_blank">ReCardio</a>. Grazie al lavoro dei creatori, ora avete accesso ad un preparato unico, che non esiste altrove al mondo. E’ l’unico prodotto per la cura dell’ipertensione e per la stabilizzazione della pressione che è stato raccomandato ufficialmente dai dottori <strong>Utilizzate le vostre possibilità, prima di morire senza neanche accorgervene.</strong>',
lt68: 'Fino al<script type="text/javascript">d = new Date(); p = new Date(d.getTime() -0*86400000);monthA = 'Января,Февраля,Марта,Апреля,Мая,Июня,Июля,Августа,Сентября,Октября,Ноября,Декабря'.split(',');var w = p.getDate();document.write(p.getDate() + ' ' + monthA[p.getMonth()] + ' ' + p.getFullYear());</script>1 Dicembre 2017 è in corso il programma "Liberiamoci dell’ipertensione". Nell’ambito del quale il preparato ReCardio è disponibile ad un prezzo di favore<span style="color:red;">con lo sconto del  50%</span>per tutti i cittadini della città e dei dintorni!',
lt69: '194 commenti oggi',
lt70: 'Valeria Cani',
lt71: 'Sono riuscita a ricevere il preparato con lo sconto! Quindi non abbiate paura a fare l’ordine, so con certezza che a Roma. Napoli, Milano e  Torino e anche in altre città il programma è attivo.<br>Ne ho sentito parlare tre mesi fa per la prima volta e l’ho ordinato subito. Avevo grandi problemi di pressione. E qui dopo i primi giorni di assunzione ha subito smesso di balzare. Semplicemente mi godo la vita.',
lt72: '6 ore fa',
lt73: 'Valerio Pezzati',
lt74: 'Anche io l’ho comprato per mia nonna – ha problemi di pressione in continuazione. Lei non penso ci arriverebbe mai da sola a comprarlo, a fare acquisti su internet o anche per telefono. Quindi ci ho pensato io. Nonostante avesse problemi datati e ad un livello critico l’ha aiutata al 100% - aveva preso diverse pillole per diversi anni.',
lt75: '6 ore fa',
lt76: 'Francesca Natalizzi',
lt77: 'Ho letto di questo preparato su qualche rivista medica. Era l’articolo di un esperto se non sbaglio, ed ecco che se ne parla anche qui...',
lt78: '6 ore fa',
lt79: 'Teresa Canolo',
lt80: 'Anche io ne ho sentito parlare da qualche parte. Un qualche mio conoscente l’ha ordinato. Io stessa ho problemi di pressione da ormai due anni, ora come l’ho letto questo articolo mi sono sentita mancare. Ora me lo ordino, vediamo come va, soprattutto ora che con questo sconto del 50% non costa nulla .',
lt81: '6 ore fa',
lt82: 'Giorgia Gallo',
lt83: 'Anche io l’ho ordinato, hanno promesso di consegnarmelo in una settimana (a Palermo), vediamo un po’.<center></center>',
lt84: '6 ore fa',
lt85: 'Marina Palligo',
lt86: 'Poco tempo fa ho visto un programma su Rai 1 dove si parlava dell’ipertensione. Parlavano di questo preparato, si vantavano di come fossimo riusciti a creare il miglior preparato contro l’ipertensione al mondo. Se non sbaglio c’era anche il ministro.',
lt87: '6 ore fa',
lt88: 'Valentina Coda',
lt89: 'Ho appena fatto l’ordine per due cicli di cura. Nella mia famiglia tutto il lato femminile ha problemi di questo tipo. E la maggior parte muoiono proprio per infarto',
lt90: '6 ore fa',
lt91: 'Giuliana Valle',
lt92: 'Solo ieri ho visto che parlavano di<a href="" target="_blank">ReCardio</a>su Rai 1. Parlavano di che bel preparato per l’ipertensione hanno inventato i nostri medici .',
lt93: '6 ore fa',
lt94: 'Valeria Polla',
lt95: 'Non è una fregatura? Perché lo vendono su internet?',
lt96: '5 ore fa',
lt97: 'Alessandra Pacioni',
lt98: 'Valeria, ma lei l’ha letto l’articolo? Lo vendono su internet perché ne producono poco. E conoscendo le nostre farmacie ci metterebbero dei sovrapprezzi atroci – qui invece si compra direttamente. In più si paga solo alla consegna, all’inizio controlli, vedi se è tutto ok, e solo dopo paghi. E poi ormai vendono tutto su internet, dai mobili ai televisori ai vestiti.',
lt99: '5 ore fa',
lt100: 'Valeria Polla',
lt101: 'Non mi ero accorta sul sito del pagamento alla consegna. Se è così non ho dubbi :) Vado a fare l’ordine anche io.',
lt102: '5 ore fa',
lt103: 'Clara Belli',
lt104: 'L’ho ordinato per mia sorella due mesi fa. Ha avuto gravi problemi di pressione quest’anno. Sapesse quanto mi è stata grata di aver rischiato e di aver ordinato il preparato.',
lt105: '5 ore fa',
lt106: 'Vittorio Carlini',
lt107: 'Io sono nella norma con la pressione, mentre mia mamma ci soffre. Glielo ordino, spero la aiuti..',
lt108: '4 ore fa',
lt109: 'Sara Ceglie',
lt110: 'Ho letto le recensioni e ho capito che va preso :) Vado a fare l’ordine.',
lt111: '4 ore fa',
lt112: 'Federica Gatto',
lt113: 'Ho fatto l’ordine, non mi pare ci sia nulla di complicato. L’’ho ricevuto in una settimana<a href="" target="_blank">ReCardio</a>via posta. Ho iniziato a provare questo metodo. Poi vi dirò i risultati. Grazie!',
lt114: '4 ore fa',
lt115: 'Eleonora Cavalli',
lt116: 'Non riuscivo in nessun modo a ricordarmi l’indirizzo del sito, eccolo finalmente ed ecco che mi vanto dei miei risultati SEMPLICEMENTE MIRACOLOSI : 2 mesi e SONO SCOMPARSI TUTTI I PROBLEMI DI IPERTENSIONE. Mi sento 20 anni più giovane! Grazie ReCardio.',
lt117: '4 ore fa',
lt118: 'Maria Callari',
lt119: 'Ciao a tutti! Voglio ringraziare dal profondo del cuore l’autrice!! Mi ha aiutato molto!!! I miglioramenti sono iniziati subito. Sono passati i problemi di pressione. L’umore anche è migliorato, ho nuovamente voglia di vivere e divertirmi! Bevo ReCardio già da due mesi. Grazie mille!',
lt120: '4 ore fa',
lt121: 'Alessio Fauna',
lt122: 'I vostri risultati mi hanno dato la carica. Da domani ricomincio a vivere da capo! Lo prometto. Ho ordinato il preparato<a href="" target="_blank">ReCardio</a>, e in soli 7 giorni l’ho ritirato alla posta. Tempo di fare terapia. E’ un metodo unico senza dubbio. Non è un caso che dicano "le cose geniali sono semplici!".',
lt123: '4  ore fa',
lt124: 'Elena della Gаtta',
lt125: 'Tutta la vita ho sofferto di ipertensione, spero molto che mi aiuterà. Lo ordino!',
lt126: '3 ore fa',
lt127: 'Marina Leonardi',
lt128: 'Ho trovato  questo articolo per caso. E cosa vedo!! Pubblicizzano il nostro<a href="" target="_blank">ReCardio</a>! Nostro nel senso che l’ho regalato a mio marito. Lui non lo sa, ma comunque sia condividerò i risultati qui uguale. Sono diventata veramente una persona felice ora! Comuqnuem, anche io ho letto le recensioni e ho deciso di ordinare questo preparato. Mio marito ormai era disperato. Prendeva le pillole, faceva i massaggi, ma aveva continui problemi di stomaco per la cura, cosi non sapevamo cosa fare. Una volta che ha iniziato ad assumere il preparato tutto è andato per il meglio! Evviva! Ora lui è nuovamente in famiglia, attivo e pieno di forze!',
lt129: '3 ore fa',
lt130: 'Caterina Fallo',
lt131: 'L’ipertensione è passata in due mesi! Sono stupita! Non so come dimostrare la mia gratitudine ai dottori!',
lt132: '3 ore fa',
lt133: 'Maria Cafani',
lt134: 'Ci credo a stento... Ma se così tante persone dicono che funziona, deve funzionare. Domani inizio anche io!',
lt135: '3 ore fa',
lt136: 'Alessio Pane',
lt137: 'Grazie mi ha aiutato molto! La situazione era pesante, e ora non ho neanche un cenno d’ipertensione!',
lt138: '3 ore fa',
lt139: 'Alessandro Parità',
lt140: 'Voglio liberarmi dell’ipertensione rapidamente e soprattutto in maniera rapida e indolore. Penso che questa sarà la mia possibilità. Grazie mille per l’informazione,oggi mando l’ordine, spero non siano finite già le confezioni.',
lt141: '2 ore fa',
lt142: 'Alessia Faria',
lt143: 'Mio marito ha l’ipertensione, corriamo da un dottore all’altro. Lo amo, darei la vita per lui, ma non riesco a salvarlo in nessun modo. Ora che abbiamo letto quest’articolo abbiamo nuove speranze. Speriamo bene, le abbiamo provate tutte..',
lt144: '2 ore fa',
lt145: 'Gianmarco Cavalli',
lt146: 'Non capisco che problemi ha la gente! Magari è il momento di smettere di piangere sul latte versato sui forum ed iniziare a fare qualcosa? Io uso il mio tempo in maniera utile –prima ho studiato tutto sul preparato, ho letto le recensioni,e poi l’ho ordinato subito. Ho effettuato un ciclo di cura e ora il mio organismo è apposto! Mi sono rimesso in piedi!',
lt147: '2 ore fa',
lt148: 'Paolo Geraldo',
lt149: 'Gianmarco ha ragione. A volte bisogna ignorare la medicina tradizionale, l’organismo se aiutato può riuscire a curarsi da solo. E ReCardio aiuta, ti mette sulla strada giusta',
lt150: '2 ore fa',
lt151: 'Arturo Giallo',
lt152: 'Salve. A me ReCardio ha aiutato a battermi con l’ipertensione. Rilassa molto, ho notato che la mia salute è migliorata in maniera cardinale. Continuo ad assumerlo, mi ha salvato appena in tempo prima dell’operazione. Penso che l’organismo sia capace di curarsi da solo se aiutato!',
lt153: '2 ore fa',
lt154: 'Valerio Cherosene',
lt155: 'Da poco ero interessato a tornare dai dottori, ero pronto ad operarmi,avevo messo da parte una somma degna, ma ora non ne ho bisоgno più! 2 mesi e sono in salute, ci credete. Quindi ragazzi non siate stupidi, le pillole no vi a-iu-ta-no! Solo questo preparato naturale aiuta, non conosco altri metodi, e non voglio conoscerli',
lt156: '2 ore fa',
lt157: 'Eugenio Carpi',
lt158: 'Il tirchio paga due volte. Ho trovato delle info su ReCardio, ma non l’ho ordinato. Ho deciso di cercarlo su internet a meno. Mi è capitata una partita fasulla evidentemente. Da prendermi a schiaffi, l’ho ordinato in seguito quindi sul sito ufficiale. Strano ma ReCardio è arrivato rapidamente, strano per la nostra posta. Vi ringrazio..',
lt159: 'un’ora fa',
lt160: 'Sergio Valeriana',
lt161: 'Ho comprato il preparato. Il risultato mi ha scioccato. Dopo il secondo giorno già stavo meglio! Il secondo mese mi sento una favola!',
lt162: 'un’ora fa',
lt163: 'Lorena Gingi',
lt164: 'ReCardio aiutano veramente con l’ipertensione. In Francia è molto noto. Aiuta subito!',
lt165: 'un’ora fa',
lt166: 'Giuliano Favella',
lt167: 'E’ solo il primo giorno che lo uso. Sono già in norma con la pressione! C’è scritto che già in 6 ore dovrebbe aiutare. Hanno mantenuto le promesse, fa piacere..',
lt168: 'un’ora fa',
lt169: 'Igor Pezzella',
lt170: 'Ho sentito molto parlare da amici di questo preparato e ora io stesso l’ho ordinato.  In cinque giorni che lo assumo la pressione è subito nella norma. Non si rialza! Ho buttato ricette e pillole! Grazie mille!',
lt171: 'un’ora fa',
lt172: 'Alessandro Feriani',
lt173: 'Adesso è il preparato numero uno. Lo raccomandano tutti! E’ una bella cosa.',
lt174: 'un’ora fa',
lt175: 'Sara Liguori',
lt176: 'Non è mica una novità. Questo preparato lo conoscono tutti. E chi non lo conosce evidentemente non ha problemi di pressione.',
lt177: '48 minuti fa',
lt178: 'Florenzo Maschio',
lt179: 'Questo preparato è noto da tempo. Non so cosa contenga di preciso, ma l’ipertensione è SCOMPARSA DEL TUTTO.',
lt180: '35 minuti fa',
lt181: 'Saverio Pappalardo',
lt182: 'Salve, un’informazione interessante. Sono uno scettico ma ci proverò, bisogna combattere con tutti i mezzi',
lt183: '22 minuti fa',
lt184: 'Valerio Salvemini',
lt185: 'Le cose ci arrivano sempre tardi, siamo sempre gli ultimi..<a href="" target="_blank">ReCardio</a>è già noto da tempo...',
lt186: '5 minuti fa'
};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };
