var new_lang = {

    "lt0": "Página inicial",
    "lt1": "Home",
    "lt2": "Notícias",
    "lt3": "Esporte",
    "lt4": "Reel",
    "lt5": "Vida profissional",
    "lt6": "Viagem",
    "lt7": "Futuro",
    "lt8": "Cultura",
    "lt9": "Música",
    "lt10": "TV",
    "lt11": "Clima",
    "lt12": "Sons",
    "lt13": "Mais",
    "lt14": "N / A",
    "lt15": "Tratamento da prostatite de A a Z",
    "lt16": "Karina Moreira",
    "lt18": "Compartilhar isso:",
    "lt19": "A inflamação da próstata é a doença mais comum do sistema geniturinário masculino. A prostatite aguda ocorre em apenas 10% dos casos, enquanto a crônica é diagnosticada em cada segundo homem. Há uma tendência a 'rejuvenescer' a doença. Agora, a inflamação da próstata cada vez mais ocorre em homens de 20 a 30 anos. Por que a próstata está inflamada? - O artigo contém os dados mais importantes sobre prostatite, seus sintomas e tratamento. ",
    "lt20": "A inflamação da próstata é mais frequentemente causada por uma infecção da uretra, da bexiga ou do reto, mas para o desenvolvimento da doença a infecção não é suficiente. Os fatores que ajudam no desenvolvimento da prostatite: ..",
    "lt21": "trabalho sedentário, estilo de vida sedentário;",
    "lt22": "distúrbios frequentes da evacuação, prisão de ventre;",
    "lt23": "hipotermia",
    "lt24": "vida sexual excessivamente ativa e mudança frequente de parceiras;",
    "lt25": "vida sexual irregular, abstinência prolongada;",
    "lt26": "maus hábitos;",
    "lt27": "comer demais, abuso de alimentos picantes;",
    "lt28": "estresse constante.",
    "lt29": "Com a inflamação da próstata, a infecção se espalha com o fluxo sanguíneo para órgãos próximos (rins, bexiga, testículos). A prostatite é um dos fatores no desenvolvimento da infertilidade, adenoma da próstata e disfunção sexual no homem, acompanhada de dor durante a relação sexual e a impossibilidade de ejacular.",
    "lt30": "O aumento do desejo de ir ao banheiro é um dos principais sintomas da prostatite, mas não o único.",
    "lt31": "VERIFIQUE SE VOCÊ TEM:",
    "lt32": "dificuldade em urinar",
    "lt33": "fluxo fraco ou intermitente de urina;",
    "lt34": "desconforto, queimação e dor durante a micção;",
    "lt35": "bifurcação, pulverização do jato, aumento do tempo de processo de micção;",
    "lt36": "sensação de esvaziamento incompleto da bexiga, vontade repetida;",
    "lt37": "micção frequente de madrugada;",
    "lt38": "dor na área genital, abdômen inferior ou nas costas.",
    "lt39": "A presença de dois dos sete sintomas é um motivo a ser examinado",
    "lt40": "Como tratar a prostatite?",
    "lt41": "A resposta a esta pergunta é deixada ao Martin Dias - profissional, chefe do departamento de urologia",
    "lt42": "Após o exame completo do paciente, bem como após os resultados dos exames e do ultrassom, eu prescrevo o tratamento. Quando uma infecção é detectada, não são prescritos apenas antibióticos, mas também inibidores da 5-alfa redutase e anti-inflamatórios não esteroides. Às vezes, prescrevo procedimentos adicionais, como massagem na próstata, fisioterapia ou acupuntura. ",
    "lt43": "O tratamento com antibióticos nem sempre dá um resultado positivo, pois eles só podem remover a infecção. O que, por sua vez, pode ser retomada devido à não conformidade com a dose do paciente ou à negligência das recomendações. Além disso, o tratamento com antibióticos é inútil se a causa não for tratada imediatamente, ou com prostatite crônica, que é mais frequentemente diagnosticada em homens.",
    "lt44": "Para tais casos, existem agentes não esteroides complexos. <a href=\"#\"> ProstEro </a> é reconhecido como o mais eficaz no tratamento da prostatite bacteriana e crônica. Sua peculiaridade reside no efeito estimulante não apenas no sistema geniturinário, mas também no sistema imunológico dos pacientes. E, ao contrário de outros medicamentos similares, <a href=\"#\"> ProstEro </a> desenvolve imunidade a bactérias, mesmo em pacientes com estágios avançados da doença. ",
    "lt45": "A composição do medicamento contém apenas ingredientes naturais. Portanto, diferentemente dos antibióticos, o ProstEro pode ser tomado em qualquer idade e a pessoa não precisa seguir uma dieta especial. Literalmente em um curso de tratamento, a inflamação passa e a micção normal é recuperada. Em particular, o fluxo de urina se intensifica, a frequência da micção diminui, o inchaço é aliviado, a ejaculação melhora, as dores durante a relação sexual passam. Foi provado que ProstEro também contribui para um efeito positivo na função sexual e tem um efeito geral sobre o corpo ",
    "lt46": "Lembre-se, com o tratamento prematuro da prostatite, o risco de desenvolver adenoma e impotência da próstata é muito alto. Para evitar métodos mais radicais de tratamento, por exemplo, intervenção cirúrgica aconselho você a não ignorar os sinais do seu corpo e a não atrasar o tratamento",
    "lt47": "ProstEro melhora o suprimento de sangue para os órgãos pélvicos, devido ao qual<b>as primeiras melhorias ocorrem no 2º ou 3º dia do uso do medicamento</b>. E mais uma boa notícia. Como parte da semana de saúde masculino, foi lançado um programa federal, de acordo com o qual<a href=\"#\">ProstEro pode ser adquirido com um desconto de 50%</a>. ",
    "lt48": "encomendar",
    "lt49": "Compartilhar isso:",
    "lt50": "Comentários:",
    "lt51": "Felipe",
    "lt52": "Obrigado, eu precisava muito saber disso!",
    "lt53": "Evandro",
    "lt54": "Prostatite surge devido a falta do sexo. E aqui depende muito da mulher.",
    "lt55": "Davi",
    "lt56": "Minha esposa está no sétimo céu de felicidade! Ela estava tão preocupada que eu tinha prostatite com suspeita de infertilidade. Ela tinha medo que não pudéssemos ter um bebê. 4 anos tentando, está tudo bem com ela, comigo também. Os médicos disseram que eu deveria curar a prostatite, mas nada ajudou. E agora está tudo bem. A infertilidade não me incomoda mais, porque tratei a causa – que é a prostatite. E tudo isso graças a ProstEro. Eu aconselho !!! ",
    "lt57": "Otávio",
    "lt58": "Ele realmente ajuda???",
    "lt59": "Antônio",
    "lt60": "Estou tomando o ProstEro já há uma semana e posso dizer que não dói no momento de fazer xixi. E eu não vou ao banheiro com tanta frequência como antes.",
    "lt61": "Adriano",
    "lt62": "Um artigo muito útil! Obrigado.",
    "lt63": "Bruno",
    "lt64": "Eu não acredito....nada me ajuda, nem massagem nem remédios. E esse troço ajudará em um mês? Não existe isso. E esses componentes naturais…",
    "lt65": "Robson",
    "lt66": "Nisso é o poder do ProstEro. Parece que não tem nada demais nele, mas eu nunca havia testado o remédio melhor.",
    "lt67": "Hector",
    "lt68": "Sim sim, eu estou com medo de lembrar que eu acordava toda hora para ir ao banheiro...E em uma semana após o começo do tratamento com o ProstEro eu dormi que nem um bebê.",
    "lt69": "Ricardo",
    "lt70": "Lembro-me de como fiquei com muito frio dentro de um carro parado no inverno e depois chorei no mictório. No começo, eu estava aguentando, eu estava com medo de ir ao médico, pensei que iria passar. Mas a situação apenas piorava. E quando fiquei completamente pressionado, mesmo assim eu não fui, tinha vergonha de ir à farmácia ... Então, encontrei tudo sobre ProstEro na Internet. Comprei e me senti aliviado em uma semana. Então, quem precisa, nem pense e peça! O remédio é comprovado e poderoso. ",
    "lt71": "Explore a BBC",
    "lt72": "Casa",
    "lt73": "Notícias",
    "lt74": "Esporte",
    "lt75": "Reel",
    "lt76": "Vida profissional",
    "lt77": "Viagens",
    "lt78": "Futuro",
    "lt79": "Cultura",
    "lt80": "Música",
    "lt81": "TV",
    "lt82": "Clima",
    "lt83": "Sons"
    
};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };