var new_lang = {
    lt1: 'Kupić Bactefort niedrogo. Ceny, opinie. Zamówcie Bactefort teraz!',
    lt2: 'Nowości medyczne w Warszawa',
    lt3: 'Parazytologia // ',
    lt4: 'Wywiad z ekspertem',
    lt5: 'Nieprzyjemny zapach z ust spowodowany PASOŻYWAMI. Główny specjalista od infekcjiopowiedział mieszkańcom moskwy o tym, jak uratować siebie i bliskich.',
    lt6: 'Od redakcji: Lekarze odkryli nowa przyczynę nieprzyjemnego zapachu z ust: pasożyty. Niedawno zakończone badanie informuje, że produkty wytwarzane przez pasożyty są toksyczne i sprzyjają rozmnażaniu się w żołądku bakterii gnilnych. Właśnie dlatego u osób zarażonych można zauważyć nieprzyjemny zapach z ust.',
    lt7: '—Dziś porozmawiamy o tym z szefem instytutu Parazytologii Federacji Rosyjskiej Siergiejem Rykowem.',
    lt8: '—Dzień dobry, Panie Siergieju! Zacznę od najważniejszego: czy to prawda, że Warszawa jest liderem w ilości zarażonej pasożytami ludności?',
    lt9: '«— Tak. Warszawa zajmuje pierwsze pozycje w rankingu zakażeń. Winę ponosi zła sytuacja ekologiczna i brak działań ze strony władzy.»',
    lt10: '—Panie Siergiuju, Czy prawdziwe są dane z badania o związku zakażeń i nieprzyjemnego zapachu z ust?',
    lt11: '—Jeszcze parę lat temu środkowidko medyczne uważało, że nieprzyjemny zapach tworzy się w jamie ustnej. Jednak ostatnie badania pokazały, że inną przyczyną sa problemy z żołądkiem (które występują zawsze przy zakażeniu pasożytami). Nie można ignorować takiego "zwykłego objawu". Zakażenie prowadzi do powstania ciężkich chorób.',
    lt12: 'Nieprzyjemny zapach z ust to wyraźnia oznaka obecności pasożytów w organizmie, która <br>prowadzi do fatalnych powikłań',
    lt13: '<br>Osobiście ufam badaniu i potwierdzają się one z badaniami naszego instytutu. Banalny "nieprzyjemny zapach" z ust przeradza się w poważną chorobę. Około 92% śmierci są spowodowane zakażeniem pasożytami. Przytłaczająca większośc tak zwanych "śmierci naturalnych" to skutki działalności pasożytów wewnątrz waszego ciała.',
    lt14: '—Zazwyczaj pasożyty rozumie się banalne glisty, jak mogą one doprowadzić do pojawienia sią nieprzyjemnego zapachu z ust, a nawet śmierci?',
    lt15: '—Tak naprawdę, wielkim błędem jest uważać, że pasożyty to tylko glisty. Istnieje ogromna ilośc różnych pasożytów, prowadzących do różnych skutków. I glisty również, a dokładniej helminty sa bardzo niebezpieczne. Niszczą jelita, doprowadzając do ich gnicia, a w końcu, do śmierci. Nawet helminty ciężko wykryć i zniszczyć <br><br>                     Oprócz nich są jeszcze tysiące pasożytów, które mogą żyć w wątrobie, mózgu, płucach, krwi, żołądku, jelitach. I praktycznie wszystkie są śmiertelne. Część z nich odrazu zaczyna niszczyć organizm. Często, do czasu działa niezauważalnie, póki ich ilośc nie bedzie tak dużo, że organizm już nie wytrzymuje i człowiek umiera.  <br><br>                     Przy czym mogę powiedzieć z pełną odpowiedzialnością, że praktycznie wszyscy są zarażeni pasożytami. Po prostu większość trudno wykryć. A keidy pojawiają się skutki, to lekarze próbują leczyć właśnie ich. Nawet przy sekcji zwłok dla wykrycia pasożytów potrzebne sa specjalne analizy. Przynajmniej dla większości  z nich.',
    lt16: '"Są tysiące pasożytów, mogących żyć w wątrobie, mózgu, płucach, krwi, żołądku. Praktycznie wszystkie są śmiertelne. А wszystko zaczyna się z nieprzyjemnego zapachu z ust"',
    lt17: '—Czy może Pan podać konkretne przykłady zarażenia?',
    lt18: '<br>—Mogę podać setki. Ale zatrzymam się na tych, które najlepiej oddają niebezpieczeństwo pasożtów.  <br><br> Po pierwsze, okazało się, że niektóre tasiemce są w stanie powodować raka, a zaraża się nie sam człowiek, a same tasiemce. Ich złośliwe komórki rozprzestrzeniają się w organiźmie, zarażając człowieka. Dzieje się to, kiedy larwy tasiemca trafiają do węzłów chłonnych. Śmierć następuje dosłownie w ciągu kilku miesięcy. W tym tygodniu odnotowano przypadek śmierci z powodu takiego raka. <br><br> Na środku tego zdjęcia: komórki raka złośliwego, przekazane człowiekowi przez pasożyta',
    lt19: 'Jest jeszcze jeden rozprzestrzeniony przypadek - zarażenie mózgu przez pasożyty. Prowadzi do do nerwicy, szybkiego męczenia si i nadmiernej pobudliwości. W poźniejszym stadium, w miarę zapełnienia się mózgu przez pasożyty, rozwijają się poważniejsze choroby.',
    lt20: '«Prowadzimy archiwum zdjęć z sekcji zwłok, gdzie były wykryte pasożyty w organach. Nie mogę ich pokazać, są straszne.»',
    lt21: 'Trzeci przykład to zarażenie pasożytami serca. Uważa się, że to mało rozprzestrzeniona choroba. Naprawdę, w mniejszym lub większym stopniu są one obecnie u około 23% ludzi. Praktycznie u co czwartego człowieka. We wczesnym stadium sa niezauważalne, a ich wpływ zerowy. Lecz im więcej czasu przechodzi, tym bardziej są zauważalne w organizmie. Często są przyczyną chorób serca i w prawie 100% są przyczyną śmierci przez zatrzymanie serca.',
    lt22: '—W czym jest jeszcze niebezpieczne zakażenie pasożytami?',
    lt23: '«U mężczyzn wywołują: prostatę, impotencję, a dalej: gruczolaki, zapalenie pęcherza moczowego piasek i kamienie w nerkach, w pęcherzu moczowym.  <br>U kobiet: Bóle i zapalenia jajniów. Rozwijają się włókniaki i mięśniaki, mastopatia, zapalenia nadnerczych, pęcherza moczowego i nerek. I oczywiście przedwczesne starzenie się skóry.»',
    lt24: '—Jak się obronić przed pasożytami? Czy istnieją jakieś analizy, lekarstwa?',
    lt25: '—Niestety, na dzień dzisiejszy nie istnieją dokładne przyrządy dla diagnostyki pasożytów w organizmie. Jest to związane z dużą ilością rodzajów pasożytow (tysiące), jak i również z wysokiem stopniem trudności ich wykrywania. Pełna procedura w Rosji jest dotępna tylko w kilku miejscach i bardzo droga.',
    lt26: 'Pierwsze objawy, po którym można rozpoznać pasożyty w organizmie to:',
    lt27: '<b>Nieprzyjemny zapach z ust</b>',
    lt28: 'Alergia (wysypki, łzawiące oczy, katar)',
    lt29: 'Częste przeziębienia, angina, zapchany nos',
    lt30: 'Zmęczenie chroniczne (Szybko się męczycie)',
    lt31: 'Częste bóle głowy, zaparcia lub biegunki',
    lt32: 'Ból w stawach i mięśniach',
    lt33: 'nerwowość, zaburzenie snu i apetytu',
    lt34: 'Ciemne worki pod oczami',
    lt35: 'Przy występowaniu dwoch objawów w waszym organizmie z pewnością są pasożyty.   <br><br> Jeśli mowa o lekarstwach, to problematyczne. Na dzień dzisiejszy istnieje tylko jedno orpacowanie, pozwalające uwolnić się od pasożytów. Która, a propos, została stworzona w Rosji.',
    lt36: '—Co to za opracowanie i przez kogo zostało stworzone. Czy można więcej szczegółów?',
    lt37: '<br>—to przeciwpasożytniczy środek "Bactefort", opracowany przy pomocy naszego instytutu Parazytologi Federacji Rosyjskiej i grupy niezależnych uczonych. Pracowaliśmy również nad innymi środkami, ale w trakcie zdecydowaliśmy zatrzymać się na "Bactefort", jako na najefektywniejszym wariancie. <br><br>  Bactefort to unikalne połączenie żółci niedźwiedziej asantu, soku z owoców sumaka i jeszcze 20 innych składników wspomagających. W procesie badań ten środek okazał się być całkowicie efektywnym. Jeśli mowa byłaby tylko o pieniądzach, to eksportowany był by w pełnym zakresie. Na zachodzie ludzie są gotowi kupować Bactefort w każdej cenie. Ale mamy nakaz od wladz, zgodnie z którym większy nakład powinien zostać w kraju i być sprzedawany mieszkańcom Rosji. <br><br> Podwyżka eksportowa dla zachodnich klientów (Bactefort jest sprzedawany za granicą 10 razy drożej), pozwoli nam sprzedaważ w kraju w cenach o wiele niższych niż wartość produktu.',
    lt38: '—Dlaczego Bactefort jest tak dobry? Czym różni się od innych sposobów oczyszczania organizmu?',
    lt39: '<br>—Na dzień dzisiejszy to jedyny działający środek na całym świecie. Własnie dlatego tak bardzo chcą go sieci apteczne i firmy farmaceutyczne. Działa on odrazu przeciwko wszystkim rodzajom pasożytów, którymi mogą być zarażeni ludzie. Biorąc pod uwagę problemy z diagnostyką, pozwala to efektywnie oczyszczać cały organizm. Jak już wspomniałem, praktycznie nie można zrozumieć, jakim dokładnie pasożytem jest zarażony człowiek. А Bactefort niszczy wszytskie pasożyty, gdziekolwiek by nie żyły: w mózgu, sercu, wątrobie czy jelitach. <br><br> Oprócz tego, nie jest to środek chemiczny, a produkt całkowicie naturalny, wykluczający reakcje alegriczne i inne problemy, które mogą pojawić sie przy leczeniu klasycznymi tabletkami, które obciążają organizm masą związków chemicznych.',
    lt40: '—Myślę, że dla naszych czytelników będzie ciekawe, gdzie można nabyć Bactefort? ',
    lt41: '<br>—Obecnie Bactefort jest dostępny tylko na zamówienie <a target="_top" href="http://l.Bactefort.com/" class="underline"><font color="red"></font>na stronie internetowej</a> projektu. Wiele razy próbowaliśli przebić się do sieci aptecznych, ale chca one postawić maksymalnie wysoka cenę. Instytut Parazytologi nie jest strukturą komercyjną. I nie mamy na celu zarobić. Chcemy zaopatrzyć w ten środek wszystkich mieszkańców. Dlatego sprzedajemy ze stratą dla siebie, kompensując sobie różnicę eksportem. A apteki chcą zarobić, dlatego mamy inne podejście do ustalania cen. <br><br>  Mam nadzieję, że kiedyś się dogadamy i Bactefort będzie sprzedawany za naszą cenę w sieciach aptek. Póki co, można go kupić tylkok przez internet. Zrobiliśmy wszystko maksymalnie prosto, środek przychodzi pocztą lub kurierem, opłata jest realizowana po otrzymaniu i sprawdzeniu.',
    lt42: '—Być może chciał by Pan powiedzieć coś jeszcze naszym czytelnikom, zanim skończymy wywiad?',
    lt43: '<br>—Jedyno, co chce się powiedzieć - strezeżcie swoje życie i zdrowie. Możecie nawet nie podejrzewać, że z prawdopodobieństwem 97-98% żyją w was pasożyty. Mogą być gdziekolwiek: w krwi, jelitach, płucach, sercu, mózgu. Pasożyty pożerają was od środka. Pojawiają się problemy zdrowotne, które skracają wasze życie o 15-25 lat. I to jeśli nie mówić o problemie nagłych śmierci, które na ogół również są związane z wpływem pasożytów na organizm człowieka.',
    lt44: 'P.S.:Poprosiliśmy profesora Siergieja udostępnić dodatkową zniżkę dla naszych czytelników. Teraz każdy może kupić  <a target="_top" href="http://l.Bactefort.com/" class="underline"><font color="red">Bactefort z dodatkową zniżką 75%. </font></a>',
    lt45: 'Zamówić Bactefort ze zniżką 75%',
    lt46: 'Rozmawiała Kristina Rżewaва<br>Fotografii z otwartego źródła',
    lt47: 'Dzisiejsze komentarze',
    lt48: 'Swietłana K.,Warszawa',
    lt49: 'Zamawiałam dla siebie ten środek. Niepokoił mnie zapach z ust. Już na piąty dzień poczułam, że oddech stał się świeższym i przyjemniejszym. Oprócz tego poprawiła się praca żołądka. Teraz dla profilaktyki wypijam kurs leczenia co 3 miesiące.',
    lt50: 'Walerij, Kijów',
    lt51: 'Kiedy zacząłem przyjmować Bactefort, nawet sobie nie wyobrażałem, że efekt będzie takim. Przeszły bóle brzucha (wygląda na to, że coś było w jelitach), zniknęła zadyszka i niezbyt przyjemny zapach z ust. I teraz w wieku 53 lat mogę dać fory 30 latkom. Dziękuję, że otwieracie ludziom oczy na ten problem. Od lekarza rodzinnego się o tym nie dowiesz.',
    lt52: 'Natasza, Nowokuznieck',
    lt53: 'Zamówiłam Bactefort, przywieźli na drugi dzień kurierem. Zaczęłam pić i wyszło ze mnie coś takeigo... Nawet nie sądziłam, że w jelitach może być tyle żywych organizmów. Aż strasznie pomyślec, że z nimi żyłam.',
    lt54: 'Weronika, Bełgorod ',
    lt55: 'Dziękuję za artykuł! Również zamówiłam ten środek.',
    lt56: 'Michaił_00, Warszawa',
    lt57: 'Też zamówiłem. Obiecali dostarczyć w ciągu ygodnia. Cóż, będziemy czekać',
    lt58: 'Diana, Władywostok',
    lt59: 'Piłam Bactefort. Efekt był wspaniały. Poczułam się młoda i zdrowa. Podniosła się odporność, w ciągu 8 miesięcy od czasu, jak przeszłam przez leczebny kurs, ani razu nie chorowałam. Wcześniej mogłam o tym tylko marzyń. Polecam wszystkim.',
    lt60: 'Ludmiła Konstantinowna, Warszawa',
    lt61: 'Niedawno na 1 kanale oglądałam program o pasożytach w organizmie człowieka. Tam mówili o tym środku, chwalili się, że jest najlepsze na świecie. Chyba nawet jakiś minister tam był.',
    lt62: 'Antonina, Niżniewartowsk',
    lt63: 'Babcia uczyła wypędzać pasożyty bylicą. Cała rodzina pije, z dzieci wychodza glisty. Ale z nieprzyjemnym zapachem z ust nie mogliśmy sobie poradzić. Zamówiłam baktefort i problem nieświeżego ddechu zniknął. Zrezygnowaliśmy z gorzkiej bylicy i przeszliśmy na krople baktefort. Ten sam efekt, cena odpowiednia, wygodniej pić.',
    lt64: 'Paweł, Nieriungri',
    lt65: 'Dawno męczyłem się od bólu głowy. Piłem Bactefort kilka tygodni, wszystko przeszło. Teraz myślę, a może tam coś żyło....',
    lt66: 'Weronika, Kazań',
    lt67: 'Ciekawy wywiad, dziękuję! Odkrywacie ludziom oczy!',
    lt68: 'Wiktor, Poliewoj',
    lt69: 'Dołączam się do rekomendacji. Kiedy zaczęłam pić, zaczęło się ze mnie dosłownie wylewać, w panice pojechałam do stolicy. Znalazłam parazytologa. Popatrzył i powiedział, że mam robaki w wątrobie. Jeśli by nie Bactefort, to za 2-3 lata by mnie zabiły.',
    lt70: 'Rita, Warszawa',
    lt71: 'Czy to nie podstawa? Czemu sprzedają w internecie?',
    lt72: 'Swietłana, Saratow',
    lt73: 'Rita, czytała Pani w ogóle artykuł? Sprzedają w internecie, bo w aptekach łapówkarze i chcą na tym jeszcze zarobić! I jaka tu może być podstawa, jeśli opłata po otrzymaniu? Ja zamawiałam, kurier przywiózł, wszystko sprawdziłam, obejrzałam i tylko potem zapłaciłam. Na poczcie to samo. No i w internecie teraz wszystko sprzedają, od ubrań po sprzęt i meble.',
    lt74: 'Rita, Niewinny',
    lt75: 'Wybacz, nie zauważyłam <a target="_top" href="http://l.Bactefort.com/" class="underline"><font color="red"></font>na stronie internetowej</a> najpierw informacji o opłacie za pobraniem. W takim razie wszystko w porządku, jeśli opłata za pobraniem. Też złożę zamówienie.',
    lt76: 'Ksenia68, Czyta',
    lt77: 'Świetny środek. Piliśmy z mężem, u obojga znaczna poprawa samopoczucia. Jak byśmy odmłodnieli, więcej sił i chęci. Pasożyty przytłaczają człowieka. Kiedy się ich pozbędziesz, czujesz się zupełnie inaczej.',
    lt78: 'Władysław Dudnik, Możajsk',
    lt79: 'Dzięki za cynk. Trzeba się oczyścić. Choć raz w życiu. Nigdy tego nie robiliśmy, a teraz myślę, ze bez pasożytów będzie zdecydowanie lepiej :) A to, że jakiekolwiek są, to prawie pewnie. Co to się tylko nie nazbiera w ciągu życia',
    lt80: 'Julia',
    lt81: 'czytam opinie i rozumie, że trzeba brać ) idę złożyć zamówienie.',
    lt82: 'Zamówić Bactefort od Instytutu Parazytologii ze zniżką 75%',
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};