var new_lang = {

    "lt0": "Home",
    "lt1": "<span class=\"icon icon-fire\"><img alt=\"\" src=\"img/fire.svg\"></span> Classificação",
    "lt2": "Curiosidades",
    "lt3": "Seu 2019 em LJ",
    "lt4": "Entrar",
    "lt5": "Criar",
    "lt7": "Assinar",
    "lt8": "Médico é uma vocação.",
    "lt9": "<span class=\"text-blue post-date\">24 de janeiro 2020</span> 19:02",
    "lt10": "Categorias:<span class=\"categ tags text-block bg-grey\">Medicina</span><span class=\"categ tags text-block bg-grey\">Sociedade</span>",
    "lt11": "Esqueça-se da próstata de uma vez por todas!",
    "lt12": "Sou um proctologista praticante com mais de 30 anos de experiência. Recentemente, tive um caso interessante, onde simplesmente aconteceu um milagre. Com a permissão dos participantes da história, estou publicando uma história sobre <b>um método eficaz de tratamento de prostatite.</b>",
    "lt13": "Células cancerígenas do adenoma de próstata devido à prostatite avançada",
    "lt14": "Na minha prática, havia um paciente que sofria de prostatite aguda por mais de seis meses. Vamos chamá-lo de Fred. Ele era um típico funcionário de escritório. Os primeiros sintomas de prostatite já passaram. Devido ao fato de ele estar sentado o tempo todo, a circulação sanguínea na pelve ficou ruim. Sua saúde foi finalmente prejudicada por um ar condicionado, na frente de que Fred estava sentado. Juntamente com um estilo de vida sedentário e resfriados, desenvolveu-se prostatite nele.",
    "lt15": "Um homem veio para se consultar comigo quando não tinha mais forças para suportar a dor. Eu o observava por vários meses, o esquema de tratamento padrão não ajudou (Prostatilen , Vibramycin, massagem de próstata). Queimação e dor durante a micção não podiam ser eliminadas, problema com a ereção tornou-se crônica. E dor, nada ajudava Fred a se livrar da dor.",
    "lt16": "Eu estava o preparando para o mais desagradável: cirurgia. A cirurgia é assim: um tubo longo e fino com alças elétricas é inserido através do canal urinário (uretra) na próstata. Uma corrente que é fornecida com uma frequência bastante alta passa pela próstata. A operação dura cerca de duas horas. Não há anestesia.",
    "lt17": "Mandei Fred novamente para fazer os testes. Era óbvio que nem antibióticos, nem massagem, nem procedimentos de fortalecimento imunológico ajudariam. Os sintomas de prostatite avançada indicavam a necessidade de cirurgia. Eu disse a Fred sobre o procedimento para remover a prostatite. A próxima consulta foi agendada antes da cirurgia.",
    "lt18": "No entanto, em todos os dias de testes e exames, não vi Fred na clínica. Dos meus colegas eu soube que o paciente Frederico Carneiro cancelou todas as consultas.",
    "lt19": "Parece o começo de uma história triste, mas tudo correu como se fosse um filme. Algumas semanas depois, encontrei Fred no balcão do supermercado. Ele parecia completamente saudável e um pouco envergonhado. O ex-paciente me contou a história de sua recuperação:",
    "lt20": "Depois de você ter contado para mim da cirurgia, apenas um pensamento nela fez minhas pernas doerem. Decidi tentar sair dessa. Pensei que ainda não havia tentado de tudo. Nas três semanas seguintes, tentei de tudo: infusões de camomila, pomada fedorenta de alguma raiz, cheguei até a usar os tampões da esposa com decocção de ervas... Foi nojento e humilhante, mas eu estava sentindo muita dor. Deve existir algo que me alivie a dor!",
    "lt21": "Eu estava me sentindo maluco: o tempo todo eu estudava sobre a prostatite para entender como evitar a cirurgia.",
    "lt22": "De uma palestra de um famoso proctologista no YouTube, aprendi sobre um novo desenvolvimento, algo que um dia estará disponível em uma farmácia. Um dia, quando um novo remédio for registrado e começará a ser vendido. Escrevi para o médico e perguntei sobre este remédio, sobre tudo o que poderia ser feito de forma independente, evitando a cirurgia, e literalmente implorei pela uma oportunidade de participar dos estudos. ",
    "lt23": "Recebi as cápsulas pelo correio com as dicas detalhadas. E me senti melhor! Em apenas um curso de tratamento! Tenho certeza de que me recuperei completamente. Portanto, decidi não ir até você. Mas, eu ainda gostaria de fazer uns testes: minha esposa ainda não acredita que eu fui curado. Quero mostrar a ela meus resultados para que ela tenha calma.",
    "lt24": "Eu nem sabia o que dizer em resposta. Fiquei atormentado com o pensamento de que o remédio simplesmente tampasse os sintomas e Fred já estivesse desenvolvido câncer de próstata.",
    "lt25": "Não falei em voz alta e o chamei para a clínica, dizendo que estava pronto para examiná-lo e fazer testes.",
    "lt26": "Na noite do dia seguinte, recebi novos resultados dos testes e de ultrassom do Fred. Todos os indicadores são normais. Nunca vi nada parecido em minha prática. Estava interessado em aprender mais sobre o medicamento. Sugeri aos cientistas que o desenvolveram a conduzir minha pesquisa independente.",
    "lt27": "Recebi certificados e autorizações. Estudei cuidadosamente a composição nos documentos: uma combinação de ameixa africana, saw palmetto, zinco e vitamina E. Os cientistas concordaram em mandar para mim a quantidade necessária de embalagens do medicamento em troca de manter relatórios sobre o uso do medicamento",
    "lt28": "20 colegas do centro científico médico participaram dos estudos. Cada médico avaliou um grupo de 50 homens com diferentes tipos de prostatite: bacteriana aguda, crônica, bacteriana, assintomática e granulomatosa. A cada três dias, meus colegas e eu examinamos os homens e comparamos seus testes atuais com os iniciais. Foi incrível! Ao final do estudo, todos os homens tinham indicadores ótimos e estavam completamente curados de prostatite. É interessante que foram descobertas mais três propriedades do remédio: ",
    "lt29": "Faz efeitos benéficos para ereção.",
    "lt30": "Não tem efeitos colaterais.",
    "lt31": "Pode ser tomado com álcool.",
    "lt32": "Eu estava convencido de que o medicamento foi testado e pode ser prescrito para pacientes. O fabricante disse que está sendo lançando apenas o primeiro lote do<a href=\"#\"> ProstEro </a> e ele é vendido com um grande desconto se você comprar através do<a href=\"#\"> site oficial </a>. ",
    "lt33": "O fabricante gentilmente me forneceu um link para o site oficial. Estou convencido de que posso recomendar este remédio a todos os pacientes que sofrem de adenoma de próstata.",
    "lt34": "Acessar o site oficial do ProstEro",
    "lt35": "<span class = \' strong \ '> Tags </span>: <span class = \' text-blue \ '> eu </span>",
    "lt36": "Inscrever-se",
    "lt37": "Prostatite não pode ser curada com antibióticos! Existe apenas um medicamento para prostatite - <a href=\"#\"> ProstEro </a>",
    "lt35": "<span class=\"strong\">Метки</span>: <span class=\"text-blue\">me</span>",
    "lt38": "Adicionar comentário",
    "lt39": "9 comentários",
    "lt40": "Comentário oculto",
    "lt41": "</g></svg>Mateus</b></span><br><span class=\"comment-date\">24 de janeiro de 2020</span>, 13:36:27 UTC",
    "lt42": "Se realmente fizeram ensaios clínicos, tem certificado e autorização, então eu vou comprar para testar",
    "lt43": "RESPONDER",
    "lt44": "Leo",
    "lt45": "Se realmente funciona, tem que comprar",
    "lt46": "RESPONDER",
    "lt47": "Davi",
    "lt48": "Assim que eu chequei aos quarenta anos, comecei a me sentir mais velho. A ereção enfraqueceu e a micção foi dolorosa. Minha esposa começou a bater no alarme e me levou aos médicos. Nada ajudou, é verdade. Depois que acidentalmente encontrei um artigo e pedi ProstEro, tanto a saúde masculina, como uma ereção, voltou rapidamente ao normal. Sinto-me jovem. Obrigado. ",
    "lt49": "RESPONDER",
    "lt50": "João",
    "lt51": "Funciona mesmo? Tem efeitos colaterais?",
    "lt52": "RESPONDER",
    "lt53": "Marcos",
    "lt54": "Bem, se você quiser se encontrar na mesa de cirurgia, fique duvidando por mais seis meses. A composição é normal, os estudos foram realizados, até o PREÇO foi reduzido. Eu experimentei os 'encantos' dessa cirurgia em mim! E pior ainda, literalmente seis meses depois, minha prostatite voltou e a única coisa que me ajudou foi o ProstEro! ",
    "lt55": "RESPONDER",
    "lt56": "Laura",
    "lt57": "Depois de todas as noites sem dormir devido às dores do meu marido, de todas as idas aos médicos, fico feliz em comunicar que ele já está bem! Hurrah! Sinto-me mais jovem com ele!",
    "lt58": "RESPONDER",
    "lt59": "Gerusa",
    "lt60": "Estou de acordo com a pessoa que comentou sobre a recuperação! Que legal quando seu marido está saudável!",
    "lt61": "RESPONDER",
    "lt62": "Romero",
    "lt63": "Encomendei, em poucos dias o remédio chegou. Após um curso de tratamento estou me sentindo muito melhor! Se eu soubesse antes sobre<a href=\"#\">o ProstEro</a>Eu não teria gastado tanto dinheiro e tempo com outros “remédios”",
    "lt64": "RESPONDER",
    "lt65": "Éric",
    "lt66": "Fiz apenas um curso de tratamento e estou me sentindo maravilhosamente bem! Aconselho, vocês não irão se arrepender!",
    "lt67": "RESPONDER",
    "lt68": "Leiam",
    "lt69": "Aplicativos",
    "lt70": "Sobre o projeto",
    "lt71": "Contrato do usuário",
    "lt72": "Ajuda",
    "lt73": "Botão Compartilhar"
    
};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };