var new_lang = {

    "lt0": "Sănătate sexuală: medicii și urologii au dezvăluit cea mai eficientă metodă pentru mărirea penisului!",
    "lt1": "Asociația de urologie și andrologie",
    "lt2": " <script type=\"text/javascript\">dtime_nums(-13, true);</script>12.06.2019",
    "lt3": "Care este dimensiunea normală a penisului?",
    "lt4": "Azi aș vrea să discutăm despre un subiect foarte important, dar și foarte sensibil, mărirea penisului. Zilnic, primesc multe întrebări atât de la bărbați, cât și de la femei, interesați să știe ce dimensiune a penisului poate oferi orgasme multiple. Sunt suficienți 15 cm? Ar trebui mărit penisul? Sau ce poți face când nu ești mulțumit de dimensiunea lui? Și așa mai departe.",
    "lt5": "Pentru a mă pregăti pentru această discuție, am consultat mulți medici, precum medici specializați în sănătatea sexuală, chirurgi, ginecologi și urologi. Am aflat statistici privind dimensiunea penisului și am discutat cu zeci de bărbați și femei. Desigur, speram să las deoparte acest subiect și să spun că dimensiunea nu contează, ci dragostea. Cu toate acestea, adevărul este că dimensiunea penisului chiar contează!",
    "lt6": "Orgasmele intense la femei depind de stimularea punctelor G și A din vagin. Punctul G este situat pe partea superioară a peretelui vaginului. Bărbații ar trebui să aibă un penis gros pentru a stimula acest punct. Punctul principal, punctul A, se află adânc în vagin, iar penisul ar trebui să fie suficient de lung. Din păcate, penisurile mici nu pot atinge acest punct, așa că femeile nu vor putea avea orgasme multiple intense.",
    "lt7": "punctul A",
    "lt8": "punctul G",
    "lt9": "Să discutăm despre dimensiuni. Care este dimensiunea normală? Nu putem spune care este dimensiunea normală, însă putem vorbi despre dimensiunea medie a penisului.",
    "lt10": " <b> 16-18 cm: </b> aceasta este dimensiunea medie a unui penis în erecție. Îmi imaginez că mulți bărbați se simt ușurați să afle acest lucru, dar femeile și-ar dori să aibă ceva mai mult cu care să se joace...",
    "lt11": " <b> 18-20 cm: </b> această dimensiune nu poate fi considerată ca fiind mare. Bărbații cu un astfel de penis pot fi mândri. Femeile ai căror bărbați sau parteneri au un penis de această dimensiune nu au probleme cu orgasmele.",
    "lt12": " <b> Peste 20 cm: </b> această dimensiune este destul de mare. Deși există destul de mulți bărbați care se laudă cu un penis mare, această dimensiune este foarte neobișnuită. Mai puțin de 1% dintre bărbați o au. Bărbații respectivi sunt adevărați cuceritori și subiect de bârfă printre doamne.",
    "lt13": " <b> 14-16 cm: </b> aceasta este dimensiunea satisfăcătoare a penisului. În pofida cuvântului \"satisfăcătoare\", de obicei, este foarte dificil să satisfaci o femeie cu această dimensiune. Cu toate acestea, din punct de vedere medical, această dimensiune este perfect normală.",
    "lt14": " <b> 12-14 cm: </b> această dimensiune este considerată mică. Din păcate, este aproape imposibil să satisfaci o femeie cu această dimensiune. În acest caz, bărbații ar trebui să ia în considerare mărirea penisului.",
    "lt15": " <b> Mai puțin de 12 cm: </b> dacă penisul are mai puțin de 12 cm în erecție, este definit ca micropenis. Femeile, de obicei, râd de el și spun povești amuzante despre bărbații cu această dimensiune. În acest caz, nu ar trebui să aștepți un miracol, căci există modalități moderne de a rezolva această problemă.",
    "lt16": " <b> Ce pot face bărbații în cazul unui penis mic? </b> Desigur, nu ar trebui să fie deprimați sau să ignore problema, ci să o rezolve. În prezent, există două metode care pot îmbunătăți activitatea sexuală.",
    "lt17": " <b> Prima metodă: operația </b> În prezent, majoritatea centrelor medicale oferă acest serviciu. Însă are anumite dezavantaje, cum ar fi riscul de a vătăma penisul, disfuncție erectilă sau durere severă timp de două-trei luni după procedură, care este realizată sub anestezie generală.",
    "lt18": " <b> A doua metodă: acasă </b> Această metodă include utilizarea unor capsule speciale. Potrivit medicilor specialiști în sănătatea sexuală și urologilor cu care am discutat, <a class=\"orange\" href=\"{url}\">XX</a>.",
    "lt19": "este cea mai eficientă metodă de a mări penisul, începând chiar de azi. Cum funcționează? Ia o capsulă înainte de sex sau masturbare. Vei avea imediat o erecție puternică. De asemenea, vei observa că penisul tău crește imediat după prima administrare. După administrarea acestor capsule, penisul tău va fi cu 3-5 cm mai mare. După administrarea regulată a acestor capsule (nu mai puțin de o lună), rezultatul va fi menținut. Astfel, după o cură cu <a class=\"orange\" href=\"{url}\">XX</a>, penisul tău își va menține noua dimensiune.",
    "lt20": "Am fost surprins că până și Universitatea medicală națională de urologie a realizat un test asupra lui <a class=\"orange\" href=\"{url}\">XX</a>, cu peste 100 de voluntari. Toți aveau micropenisuri și nu erau mulțumiți de dimensiunea lor. Chiar și oamenii de știință sunt interesați să rezolve această problemă, ceea ce înseamnă că este o chestiune foarte importantă. Au fost făcute următoarele comentarii <a class=\"orange\" href=\"{url}\"> despre rezultatele unei cercetări de două luni asupra lui </a>XX:",
    "lt21": " <b> 1. Mărirea penisului: </b> dimensiunea penisului în erecție crește cu 3-5 cm. Ne referim la efectul pe termen lung al capsulelor, care a fost observat la finalul lunii.",
    "lt22": " <b> 2. Orgasme intense: </b> bărbații au orgasme mai intense, datorită sensibilității sporite a penisului și libidoului.",
    "lt23": " <b> 3. Act sexual de durată mai lungă: </b> Durata actului sexual crește semnificativ. Acest lucru este foarte important, deoarece ejacularea prematură privează femeile de plăcerea sexului.",
    "lt24": " <b> 4. Erecție puternică: </b> excitarea apare foarte rapid; erecția consecventă este menținută pe întreaga durată a actului sexual.",
    "lt25": " <b> 5. Penisul crește în grosime: </b> datorită unei erecții rapide și depline, grosimea penisului crește, ceea ce contribuie la satisfacerea femeilor, prin stimularea punctului G.",
    "lt26": " <b> 6. Calitatea spermei: </b> sunt îmbunătățite cantitatea și calitatea spermei ejaculate la finalul actului sexual.",
    "lt27": "Testul doctorului Voiculescu",
    "lt28": "Răspunde la aceste nouă întrebări pentru a afla ce dimensiune a penisului poți obține cu <a class=\"orange\" href=\"{url}\">XX</a> .",
    "lt29": "Cei care parcurg acest test vor primi și un preț special la prima achiziție de < span class = \"orange\">XX</span>.",
    "lt30": "ÎNTREBAREA <span id=\"qn\">1</span>../../../../9",
    "lt31": "REZULTATUL TĂU:",
    "lt32": "În funcție de durata administrării capsulelor, poți obține următoarele rezultate:",
    "lt33": "În 30 de zile de administrare, penisul tău va crește cu <span id=\"plus\">3.85</span> cm",
    "lt34": "În 42 de zile de administrare, penisul tău va crește cu <span id=\"plus2\">5.43</span> cm",
    "lt35": "În 60 de zile de administrare, penisul tău va crește cu <span id=\"plus3\">7.32</span> cm",
    "lt36": "Mulțumim că ai parcurs testul!",
    "lt37": "Ți-am rezervat o reducere pentru prima achiziție de <a class=\"orange\" href=\"{url}\">XX</a>",
    "lt38": "Reducerea ta va expira în:",
    "lt39": " <span id=\"min\">08</span>:<span id=\"sec\">15</span>",
    "lt40": "Comandă acum sau reducerea ta va fi oferită următorului participant.",
    "lt41": "comandă",
    "lt42": "O secundă, se calculează eficiența medicamentului...",
    "lt43": "Vârsta ta:",
    "lt44": "(OPȚIUNI)",
    "lt45": "Înălțimea ta:",
    "lt46": "(OPȚIUNI)",
    "lt47": "Mai puțin de 140 cm",
    "lt48": "141 cm",
    "lt49": "142 cm",
    "lt50": "143 cm",
    "lt51": "144 cm",
    "lt52": "145 cm",
    "lt53": "146 cm",
    "lt54": "147 cm",
    "lt55": "148 cm",
    "lt56": "149 cm",
    "lt57": "150 cm",
    "lt58": "151 cm",
    "lt59": "152 cm",
    "lt60": "153 cm",
    "lt61": "154 cm",
    "lt62": "155 cm",
    "lt63": "156 cm",
    "lt64": "157 cm",
    "lt65": "158 cm",
    "lt66": "159 cm",
    "lt67": "160 cm",
    "lt68": "161 cm",
    "lt69": "162 cm",
    "lt70": "163 cm",
    "lt71": "164 cm",
    "lt72": "165 cm",
    "lt73": "166 cm",
    "lt74": "167 cm",
    "lt75": "168 cm",
    "lt76": "169 cm",
    "lt77": "170 cm",
    "lt78": "171 cm",
    "lt79": "172 cm",
    "lt80": "173 cm",
    "lt81": "174 cm",
    "lt82": "175 cm",
    "lt83": "176 cm",
    "lt84": "177 cm",
    "lt85": "178 cm",
    "lt86": "179 cm",
    "lt87": "180 cm",
    "lt88": "181 cm",
    "lt89": "182 cm",
    "lt90": "183 cm",
    "lt91": "184 cm",
    "lt92": "185 cm",
    "lt93": "186 cm",
    "lt94": "187 cm",
    "lt95": "188 cm",
    "lt96": "189 cm",
    "lt97": "190 cm",
    "lt98": "191 cm",
    "lt99": "192 cm",
    "lt100": "193 cm",
    "lt101": "194 cm",
    "lt102": "195 cm",
    "lt103": "196 cm",
    "lt104": "197 cm",
    "lt105": "198 cm",
    "lt106": "199 cm",
    "lt107": "200 cm",
    "lt108": "Peste 200 cm",
    "lt109": "Greutatea ta:",
    "lt110": "(OPȚIUNI)",
    "lt111": "mai puțin de 40 kg",
    "lt112": "41 kg",
    "lt113": "42 kg",
    "lt114": "43 kg",
    "lt115": "44 kg",
    "lt116": "45 kg",
    "lt117": "46 kg",
    "lt118": "47 kg",
    "lt119": "48 kg",
    "lt120": "49 kg",
    "lt121": "50 kg",
    "lt122": "51 kg",
    "lt123": "52 kg",
    "lt124": "53 kg",
    "lt125": "54 kg",
    "lt126": "55 kg",
    "lt127": "56 kg",
    "lt128": "57 kg",
    "lt129": "58 kg",
    "lt130": "59 kg",
    "lt131": "60 kg",
    "lt132": "61 kg",
    "lt133": "62 kg",
    "lt134": "63 kg",
    "lt135": "64 kg",
    "lt136": "65 kg",
    "lt137": "66 kg",
    "lt138": "67 kg",
    "lt139": "68 kg",
    "lt140": "69 kg",
    "lt141": "70 kg",
    "lt142": "71 kg",
    "lt143": "72 kg",
    "lt144": "73 kg",
    "lt145": "74 kg",
    "lt146": "75 kg",
    "lt147": "76 kg",
    "lt148": "77 kg",
    "lt149": "78 kg",
    "lt150": "79 kg",
    "lt151": "80 kg",
    "lt152": "81 kg",
    "lt153": "82 kg",
    "lt154": "83 kg",
    "lt155": "84 kg",
    "lt156": "85 kg",
    "lt157": "86 kg",
    "lt158": "87 kg",
    "lt159": "88 kg",
    "lt160": "89 kg",
    "lt161": "90 kg",
    "lt162": "91 kg",
    "lt163": "92 kg",
    "lt164": "93 kg",
    "lt165": "94 kg",
    "lt166": "95 kg",
    "lt167": "96 kg",
    "lt168": "97 kg",
    "lt169": "98 kg",
    "lt170": "99 kg",
    "lt171": "100 kg",
    "lt172": "101 kg",
    "lt173": "102 kg",
    "lt174": "103 kg",
    "lt175": "104 kg",
    "lt176": "105 kg",
    "lt177": "106 kg",
    "lt178": "107 kg",
    "lt179": "108 kg",
    "lt180": "109 kg",
    "lt181": "110 kg",
    "lt182": "111 kg",
    "lt183": "112 kg",
    "lt184": "113 kg",
    "lt185": "114 kg",
    "lt186": "115 kg",
    "lt187": "116 kg",
    "lt188": "117 kg",
    "lt189": "118 kg",
    "lt190": "119 kg",
    "lt191": "120 kg",
    "lt192": "121 kg",
    "lt193": "122 kg",
    "lt194": "123 kg",
    "lt195": "124 kg",
    "lt196": "125 kg",
    "lt197": "126 kg",
    "lt198": "127 kg",
    "lt199": "128 kg",
    "lt200": "129 kg",
    "lt201": "130 kg",
    "lt202": "peste 130 kg",
    "lt203": "Dimensiunea penisului tău",
    "lt204": "(OPȚIUNI)",
    "lt205": "Sub 15 cm",
    "lt206": "Peste 15 cm",
    "lt207": "Cât de des faci sex sau te masturbezi?",
    "lt208": "(OPȚIUNI)",
    "lt209": "ZILNIC",
    "lt210": "DE CÂTEVA ORI PE SĂPTĂMÂNĂ",
    "lt211": "DE CÂTEVA ORI PE LUNĂ",
    "lt212": "MAI RAR DE O DATĂ PE LUNĂ",
    "lt213": "Ai fost operat vreodată la penis?",
    "lt214": "(OPȚIUNI)",
    "lt215": "DA",
    "lt216": "NU",
    "lt217": "AI AVUT VREODATĂ BOLI ALE GLANDEI PROSTATEI?",
    "lt218": "(OPȚIUNI)",
    "lt219": "DA",
    "lt220": "NU",
    "lt221": "Stilul tău de viață:",
    "lt222": "(OPȚIUNI)",
    "lt223": "Activ",
    "lt224": "Sedentar",
    "lt225": "Nu știu",
    "lt226": "Grupa sanguină:",
    "lt227": "(OPȚIUNI)",
    "lt228": "O",
    "lt229": "A",
    "lt230": "B",
    "lt231": "AB",
    "lt232": "Nu știu",
    "lt233": "Poți cumpăra <a class=\"orange\" href=\"{url}\">XX</a>. Parcurge testul de mai jos, completează câmpurile pentru a participa la oferta specială sau comandă de pe website-ul oficial",
    "lt234": "Nu este disponibil în farmacii și nici nu va fi în viitor. Aveți grijă la produsele contrafăcute! Producătorul mi-a oferit o reducere specială pentru cititori, deci, dacă vă îngrijorează această problemă, o puteți rezolva acum! Oferă-ți ție și partenerei ocazia de a vă bucura de viața sexuală.",
    "lt235": "comandă",
    "lt236": "Vă reamintim că reducerea este disponibilă doar până la data expirării. <span class=\"current-date\" style=\"color: red;\"><script type=\"text/javascript\">dtime_nums(-1, true);</script>24.06.2019</span>",
    "lt237": "Comentarii noi: <em style=\"color: rgb(255, 255, 255); font-size: 12px;\">(47/47)</em> ",
    "lt238": "Andreea",
    "lt239": "Fostul meu iubit avea 15 cm.Am irosit un an fără orgasm, așa că l - am părăsit.",
    "lt240": " <script type=\"text/javascript\">dtime_nums(-13, true);</script>12.06.2019",
    "lt241": "Angela",
    "lt242": "13 cm... Am încercat să fiu delicată când discutam despre asta, dar nu a funcționat. Ne-am despărțit.",
    "lt243": " <script type=\"text/javascript\">dtime_nums(-12, true);</script>13.06.2019",
    "lt244": "Dan Roman",
    "lt245": "Bărbații au stimă de sine scăzută din cauza femeilor ca voi! Vă purtați ca niște târfe.",
    "lt246": " <script type=\"text/javascript\">dtime_nums(-11, true);</script>14.06.2019",
    "lt247": "Carla",
    "lt248": "Dan Roman, se pare că ai un penis mic. Atât bărbații, cât și femeile ar trebui să se bucure de sex.",
    "lt249": " <script type=\"text/javascript\">dtime_nums(-10, true);</script>15.06.2019",
    "lt250": "Maria",
    "lt251": "Aceste miniaturi nu sunt mai mari ca un tampon, 13-15 cm... Mă bucur că am un Superman acum.",
    "lt252": " <script type=\"text/javascript\">dtime_nums(-9, true);</script>16.06.2019",
    "lt253": "Vlad",
    "lt254": "Cum ai rezolvat problema? Dimensiunea penisului meu este de doar 15 cm. Când mă uit la reacția soției mele, realizez că nu se termină întotdeauna. Aș vrea să-l cresc câțiva centimetri. Cei care ați încercat capsulele, puteți împărtăși rezultatele voastre?",
    "lt255": " <script type=\"text/javascript\">dtime_nums(-8, true);</script>17.06.2019",
    "lt256": "Darius",
    "lt257": "Salutare tuturor! Iau aceste capsule de o lună. Penisul meu avea 13 cm, iar acum are 17. Simt totul. I-am oferit prietenei mele primul orgasm vaginal din viața ei! <img src=\"src/g5.jpg\">",
    "lt258": " <script type=\"text/javascript\">dtime_nums(-7, true);</script>18.06.2019",
    "lt259": "Uau",
    "lt260": "Penisul meu avea 10 cm. Fetele râdeau întotdeauna de mine. Iau în prezent <a class=\"orange\" href=\"{url}\">XX</a> și acum penisul meu are 15 cm. Aștept să mai crească încă 2-3 cm, dar deja mă simt mult mai încrezător. Nu-mi vine să cred că nu voiam să trăiesc!",
    "lt261": " <script type=\"text/javascript\">dtime_nums(-6, true);</script>19.06.2019",
    "lt262": "Zoe",
    "lt263": "Căsnicia mea de 15 ani, cu un soț care avea 13 cm, s - a încheiat cu un divorț.Noul meu prieten are 19 cm și știți ceva? Dimensiunea chiar contează!",

    "lt264": " <script type=\"text/javascript\">dtime_nums(-5, true);</script>20.06.2019",
    "lt265": "Cristi",
    "lt266": "Aveam 15 cm, apoi am încercat <a class=\"orange\" href=\"{url}\">XX</a> și acum am 20 cm! Relațiile mele cu fetele sunt complet diferite acum. Unele dintre ele chiar au ejaculat! <img src=\"src/g6.jpg\">",
    "lt267": " <script type=\"text/javascript\">dtime_nums(-4, true);</script>21.06.2019",
    "lt268": "Horea",
    "lt269": "Din păcate, am înțeles că am o problemă abia după divorț. Încă nu sunt pregătit să recurg la operație. Mă puteți sfătui de unde să comand produsul original, nu vreo imitație?",
    "lt270": " <script type=\"text/javascript\">dtime_nums(-3, true);</script>22.06.2019",
    "lt271": "Doctor",
    "lt272": "Horea, <a class=\"orange\" href=\"{url}\">XX</a> este disponibil pentru comandă doar pe website-ul oficial! Poți apăsa pe butonul \"COMANDĂ\" de mai jos. Potrivit acordului cu producătorul, telespectatorii și cititorii noștri beneficiază de o reducere exclusivă, disponibilă doar câteva zile, deci, comandă acum!",
    "lt273": "Aveți grijă la produsele contrafăcute!",
    "lt274": " <script type=\"text/javascript\">dtime_nums(-2, true);</script>23.06.2019",
    "lt275": "comandă",
    "lt276": "Autorul acestui articol: Ionuț Coman, chirurg",
    "lt277": "Medic specialist;",
    "lt278": "Medic acreditat;",
    "lt279": "Profesor.",
    "lt280": "Universitatea medicală națională de urologie și-a continuat studiul asupra proprietăților lui <a class=\"orange\" href=\"{url}\">XX</a>.",
    "lt281": "Pe parcursul protocolului de 60 de zile, medicii au examinat 124 de voluntari cu micropenisuri sau care nu erau mulțumiți de dimensiunea lor. Rezultatele au fost după cum urmează:",
    "lt282": " <b> 1. </b> Toți participanții și-au mărit penisurile cu aproximativ 3-5 cm.",
    "lt283": " <b> 2. </b> Nu s-au observat efectele secundare în această perioadă.",
    "lt284": " <b> 3. </b> Majoritatea participanților au observat o creștere semnificativă a duratei actului sexual.",
    "lt285": " <b> 4. </b> Aproape toți participanții au observat o creștere a grosimii penisului în timpul erecției.",
    "lt286": " <b> 5. </b> De asemenea, au observat creșterea cantității spermei.",
    "lt287": " <b> 6. </b> Orgasmele au devenit mai intense.",
    "lt288": "Vă reamintim că reducerea este disponibilă doar până la data expirării <span style=\"color: red\"></span><span class=\"current-date\" style=\"color: red;\"><script type=\"text/javascript\">dtime_nums(-1, true);</script>24.06.2019</span>",
    "lt289": "comandă",
    "lt290": "© <span class=\"ryear\">2019</span>Drepturi de autor",
    "lt291": "Raportare"
};
function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
}
;
