var new_lang = {
 lt1: ' I segreti della medicina ',
    lt2: 'Russo',
    lt3: 'Ministero',
    lt4: 'Salute',
    lt5: 'Competenze',
    lt6: 'Documenti',
    lt7: 'ufficio stampa',
    lt8: 'Concorsi',
    lt9: 'home',
    lt10: 'ufficio stampa',
    lt11: 'novitàи',
    lt12: 'I dottori ANNUNCIANO: Ipertensione e picchi di pressione causati dalla stessa  - nel 89% dei casi di uccidono il paziente con infarto o ictus!',
    lt13: 'Ipertensione e picchi di pressione ormai saranno solo il passato !',
    lt14: 'L’infarto e l’ictus sono la causa di praticamente il 70 % delle morti umane. 7 persone su 10 muoiono per via di arterie collegate a cuore o cervello. Praticamente in ognuno di questi casi la colpa è dei picchi di pressione causati dall’ ipertensione. 2L’assassino silenzioso”, come lo chiamano i cardiologi, ogni giorno si porta via un milione di vite. ',
    lt15: 'Riccardo Maria Fruzzi',
    lt16: 'Medico cardiologo, inventore, responsabile di scienza medica, insegnante, professore. Primario di chirurgia cardiaca. Presidente dell’organizzazione pubblica “Lega per la Salute della Nazione” .',
    lt17: 'Esperienza lavorativa di 48 anni ',
    lt18: 'riguardo il problema:',
    lt19: 'Non è un segreto per nessuno che i problemi cardio circolatori sono al primo posto nella classifica delle malattie che si portano via più vite. Proprio l’ipertensione è la causa principale di tutti gli infarti e degli ictus, che vengono diagnosticati come problemi cardio circolatori. Ovviamente anche altri problemi effettuano una cattiva pressione nei confronti dell’organismo , ma l’ipertensione e gli sbalzi di pressione che comporta sono proprio quella spinta che manda le persone all’altro mondo.',
    lt20: 'Se vogliamo parlare proprio di dati statistici <strong>circa il  77-78% delle cosiddette “morti naturali” è causato proprio dall’ipertensione.</strong> In numeri parliamo di circa 1,54 milioni di morti nel 2015 e 1,49 milioni di morti nel 2014. Quindi la cifra reale è colossale e paurosa. Fino ad ora nessuno aveva pensato alla pericolosità dell’ipertensione, dato che non c’erano dati ufficiali.  .nell’arco di tempo che va dal 2011 al 2015 abbiamo raccolto un enorme numero di dati, che ha comportato risultati disastrosi e paurosi.',
    lt21: 'Gli sbalzi di pressione provocano ogni volta gravi danni ai muscoli del cuore, e questo alle lungo comporta l’arresto cardiaco. In parole povere, ogni volta che c’è uno sbalzo di pressione il cuore può arrivare a fare fino a 20 volte quello che sarebbe lo sforzo normale. Se quindi vogliamo parlare dei risultati che comporta in uno stato avanzato',
    lt22: 'l’ipertensione porta sempre ad un unico risultato, la morte',
    lt23: 'Se quindi ci mettiamo ad analizzare le cause abituali delle morti, viene fuori che l’ipertensione è collegata all’89% dei casi totali. Ovvero l’ 89% dei casi di ipertensione si conclude con infarto o ictus e morte della persona. In più, se fino a 20-30 anni fa i pazienti con questa diagnosi avevano una speranza di vita futura di circa 10-20 anni, ora invece  <strong>2/3 (due terzi) dei pazienti muore nei primi 5 anni di sviluppo della malattia.',
    lt24: '2/3 (terzi ) dei pazienti muore nei primi 5 anni di sviluppo della malattia. ',
    lt25: 'fa paura soprattutto il fatto che un sacco di persone neanche si immagina di avere l’ipertensione. E quindi perdono la possibilità di intervenire per tempo, semplicemente perché non sono al corrente .',
    lt26: 'da questi sintomi potete capire se soffrite di ipertensione:',
    lt27: 'mal di testa',
    lt28: 'battito accelerato',
    lt29: 'punti neri alla vista (punticini)',
    lt30: 'sonnolenza, nervosismo, apatia',
    lt31: 'vista in calo',
    lt32: 'sudorazione',
    lt33: 'stanchezza cronica',
    lt34: 'faccia gonfia',
    lt35: 'problemi collegati alle dita',
    lt36: 'sbalzi di pressione',
    lt37: 'Se avete anche solo uno di questi sintomi meglio insospettirsi, e se  ',
    lt38: 'ne avete due o più, potete star certi di soffrire di ipertensione',
    lt39: 'sfortunatamente, guardando i dati, ',
    lt40: 'notiamo che il 67% dei malati non sospetta neanche di avere un problema.',
    lt41: 'Come fare per proteggersi e combattere questo malessere?',
    lt42: 'prima di tutto bisogna capire, che bisogna lasciarsi alle spalle un sacco di abitudini dannose, soprattutto tabacismo e alcolismo. Questi infati fanno solo danni alle arterie. In seguito bisogna urgentemente abbassare la pressione. Tuttavia questo non vi curerà. In più se si ottiene un rapido abbassamento della pressione con i farmaci, c’è il rischio di una reazione molto negativa da parte dell’organismo , infarto compreso. Inoltre le pasticche fanno molto male al fegato.  .',
    lt43: 'sostanzialmente, al giorno d’oggi, l’unico prodotto che si raccomanda ufficialmente per curare l’ipertensione, e che viene usato da praticamente tutti i cardiologi è <a href=""><strong>ReCardio</strong></a>. La sua creazione è iniziata molto tempo fa, ma si è conclusa solo di recente. Della creazione del preparatosi è occupato un gruppo di specialisti dell’accademia delle scienze  italiana , che ha lavorato in fitta collaborazione con cardiologi praticanti. Come risultato ne è uscito fuori un prodotto unico, che abbassa in maniera efficace l’ipertensione sradicando il problema alla radice, a differenza di tutti gli altri preparati.  .',
    lt44: 'Nel  2016 , nel centro scientifico pratico di cardiologia e cardiochirurgia , membri del centro statale per la profilassi medica hanno completato gli studi sulla somministrazione del preparato di nuova generazione  <a href=""><strong>ReCardio</strong></a>, creato per combattere l’ipertensione. Ecco i risultati sorprendenti resi noti dalla stampa:',
    lt45: '1. L’ efficacia di ReCardio è stata testata con i metodi standard (totale di pazienti guariti su un gruppo di 100 individui che hanno assunto il prodotto):',
    lt46: ' –	Pressione normalizzata  – 97%',
    lt47: ' –	Eliminazione della trombosi – 80%.',
    lt48: ' –	eliminazione della tachicardia – 99%',
    lt49: ' –	eliminazione del mal di testa – 100%',
    lt50: ' –	stabilizzazione dei ritmi vitali, con forza di giorno e sonno di notte – 97%.',
    lt51: '*Con guarigione completa in questo caso si intende la completa mancanza di sintomi e l’assenza di ricadute nei 6 mesi successivi. ',
    lt52: '2.	Non sono stati riscontrati effetti collaterali, non sono state riscontrate possibili allergie.',
    lt53: '3.	ReCardio E’ riconosciuto come migliore preparato per la lotta all’ipertensione.',
    lt54: 'Michele Pavoletti',
    lt55: ' direttore del centro scientifico pratico di cardiologia e cardiochirurgia. Dottore in scienze mediche.',
    lt56: 'stage lavorativo, 29 anni',
    lt57: 'E’ stato reso noto ai collaboratori del nostro centro, che il preparato in questione attacca e sconfigge l’ipertensione alla radice. I sintomi in generale vengono eliminati già dopo poche ore dal momento dell’assunzione, grazie ai principi attivi . Questo da un immenso sollievo già non appena si comincia ad assumerlo.',
    lt58: 'Il tono delle valvole ritorna normale già dopo un ciclo di cura. In più  ReCardio è efficace a qualsiasi stadio dell’ipertensione.Ha passato con lode ogni test clinico. Qualsiasi prodotto estero non è riuscito neanche a stare al passo di questo preparato. I prodotti stranieri hanno avuto un massimo di efficacia del  20-21% . Con il prodotto in questione invece parliamo del  75-77% di pazienti totalmente curati. I restanti sono stati semplicemente stabilizzati. Ovvero l’ipertensione non da effetti ma c’è (problema con il tono delle valvole). Tuttavia le persone si sentono molto bene e non hanno più sbalzi di pressione.',
    lt59: 'Oltre che in Italia, ReCardio ha passato i test in Svizzera e in Germania, dimostrando ancora una volta la sua efficacia. Ora da tutto il mondo c’è una richiesta incredibile di questo preparato. Ma secondo le direttive del Ministero della Salute, al momento si vende solo in Italia, dato che al momento la produzione non permette una vendita globalizzata.',
    lt60: 'Al momento il prodotto viene prodotto in piccole partite, anche se ci si sta organizzando per aumentare la produzione, per poterne produrre molto di più. Per questo al momento non è in vendita in farmacia, dato che appena viene prodotto le case farmaceutiche se lo prendono tutto. Inoltre fino a poco tempo fa era del tutto impossibile procurarselo dato che tutto il preparato prodotto veniva inviato agli ospedali e alle cliniche per essere somministrato ai pazienti.',
    lt61: 'Al momento il preparato originale <strong>ReCardio</strong> è acquistabile sul <a href=""><strong>sito ufficiale del produttore</strong></a>.',
    lt62: '194 commenti',
    lt63: 'Sara Scotto',
    lt64: 'Ne ho sentito parlare la prima volta tre mesi fa e l’ho ordinato subito . Avevo grandi problemi di pressione. E qui, dopo un solo giorno non ne ho più avuti. Semplicemente mi godo la vita.',
    lt65: '12 minuti fa',
    lt66: 'Marta Laganà',
    lt67: 'Anche io l’ho comprato, per mia nonna che ha sempre avuto problemi di pressione. Infatti difficilmente lei riuscirà mai a comprare qualcosa da sola su internet, ma neanche per telefono. Quindi ci ho pensato io.  Ha aiutato al 100%, nonostante avesse problemi da una vita e ormai ad uno stadio avanzato e avesse preso medicinali per tutta la vita.',
    lt68: '17 minuti fa ',
    lt69: 'Saretta',
    lt70: 'Ho letto su una rivista internazionale di questo preparato. Se non sbaglio si trattava di una intervista ad un esperto...',
    lt71: '19 minuti fa ',
    lt72: 'Crisitna',
    lt73: 'Anche io ho sentito qualcosa di sfuggita. Qualche conoscente deve averlo ordinato. Io stessa ho problemi di pressione da due anni, e come ho letto quest’articolo mi sono emozionata. Ora lo ordino, vediamo un po’.',
    lt74: '21 minuti fa',
    lt75: 'Andrea',
    lt76: 'Anche io l’ho ordinato. Hanno promesso di consegnarmelo in una settimana (Padova), staremo a vedere',
    lt77: '25 minuti fa',
    lt78: 'Lorena',
    lt79: 'Ho appena ordinato il prodotto per il secondo ciclo.  Tutte le femmine della mia famiglia hanno problemi di pressione. E molto spesso muoiono di infarto, per l’appunto..',
    lt80: '27 minuti fa  ',
    lt81: 'Nicoleta delli Carri ',
    lt82: 'Solo ieri ho visto un programma su questo  ReCardio  sulla mediaset.Parlavano di quale stupenda invenzione avessero fatto dei medici per curare l’ipertensione.',
    lt83: '30 minuti fa',
    lt84: 'Alessandro',
    lt85: 'Quasi tutte le donne della mia famiglia sono morte di infarto. Tutte ovviamente avevano problemi di pressione. E a dirla tutta anche gli uomini. Meglio che lo ordina anche io va.',
    lt86: '34 minuti fa ',
    lt87: 'Tipo',
    lt88: 'Spero che in futuro continuerà a costare così poco e non mi toccherà spendere mille euro per curarmi con un ciclo.',
    lt89: '39 minuti fa',
    lt90: 'valentina',
    lt91: 'l’ho ordinato per mia sorella due mesi fa. Ha sofferto a lungo di pressione. Sapeste come mi ha ringraziato, di aver rischiato e di averle ordinato questo medicinale.',
    lt92: '42 minuti fa',
    lt93: 'Ирина Винс',
    lt94: 'Io sto a posto con la pressione, ma mi madre soffre. Glielo ordino speriamo aiuti.',
    lt95: 'un’ora fa',
    lt96: 'Camilla Lattanzi',
    lt97: 'Dopo averlo preso mi sento molto meglio, come se fossi ringiovanita. Ha effetti anche sul campo estetico, sembro molto più giocane e in forma.',
    lt98: 'un’ora fa',
    lt99: 'Luigi',
    lt100: 'E’ un miracolo, si. ReCardio lo ho ordinato subito, come ne ho sentito parlare. Peccato che 5 ani fa non ne ero a conoscenza , ho sofferto molti anni, ma per lo meno ora sono vivo e in perfetta salute! Il mondo è mio! Mille grazie.',
    lt101: 'un’ora fa',
    lt102: 'Giorgio Verdone',
    lt103: 'Ho visto un sacco di recensioni su questo ReCardio, ma me ne sono fregato. E un mio amico si è lamentato di avere problemi . Ora penso, forse dovrei consigliarglielo?',
    lt104: 'un’ora fa',
    lt105: 'Marina Albertazzi',
    lt106: 'Ha aiutato molto mio marito! La pressione si è stabilizzata! Sono bastati 3 flaconi. Тora lo ordino anche per me, aiuta tantissimo!.',
    lt107: 'un’ora fa',
    lt108: 'Che ficata! Devo ordinarlo, mi sono rotta di questi problemi di pressione!',
    lt109: 'Due ore fa',
    lt110: 'Moretta816',
    lt111: 'non ci crederete ma avevo lo stesso problema, stanchezza cronica, depressione totale, ero disperata poi ho visto ReCardio, fa miracoli, lo consiglio a tutti.',
    lt112: 'due ore fa',
    lt113: 'Sergio',
    lt114: 'Il tirchio paga due volte. Ho trovato varie informazioni su  ReCardio, ma ho deciso di non ordinarlo. Ho deciso di comprarlo sempre su internet, ma su siti economici e dubbi. Ho comprato una partita che evidentemente era stata scartata. Alla fine mi sono preso a parolacce e l’ho ordinato originale.Stranamente <a href="">ReCardio</a> mi è arrivato praticamente subito. Con le nostre poste è strano! Grazie mille!.',
    lt115: '3 ore fa', 
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};