var new_lang = {
lt1: 	'Hatékony gyógyszer a magas vérnyomás ellen!', 
lt2: 	'Szerves',
lt3: 	'3567 ember<br>megrendelt ma',
lt4: 	' Rendeljen visszahívást', 
lt5: 	' Rendeljen visszahívást', 
lt6: 	'Vérnyomás normális<br>az első alkalmazás után és örökre', 
lt7: 	'Mentse meg magát a haláltól<br>szívroham vagy agyi érkatasztrófa miatt!', 
lt8: 	'Normalizálja a nyomást<br>az első 6 órában<br>bioflavonoidnak köszönhetően', 
lt9: 	'Helyreállítja<br>a tónust és rugalmasságot<br>az ereknek 1 kúra alatt', 
lt10: 	'Biztonságos minden korban<br>Hatékony I, II, III<br>hipertónia fokozatkor', 
lt11: 	'A legközelebbi raktárban a termékek száma<br> korlátozott: <br>', 
lt12: 	'Csomagolás.',
lt13: 	'Export', 
lt14: 	'ár:', 
lt15: 	'Kedvezményes', 
lt16: 	'ár:', 
lt17: 	' Ország', 
lt18: 	'Adja meg a nevét', 
lt19: 	'Adja meg a telefon számát', 
lt20: 	'Rendelés', 
lt21: 	'Ellenőrizze magát!<br>Legalább 1 tünet azonos?', 
lt22: 	'<br>Fejfájás', 
lt23: 	'Fekete pontok a szemek<br> előtt (légy)', 
lt24: 	'Apátia,<br>ingerlékenység<br>álmosság', 
lt25: 	'Zavaros<br>látás', 
lt26: 	'Izzadás', 
lt27: 	'Szívverés<br>gyorsulása', 
lt28: 	'Krónikus<br>fáradtság', 
lt29: 	'Az arc<br>duzzanata', 
lt30: 	'Az ujjak zsibbadása<br> és hidegrázása',
lt31: 	'Nyomás<br>ugrások', 
lt32: 	'EZ HIPERTÓNIA!', 
lt33: 	'Fontos tudni!<br>67% - a hipertóniás betegeknek <b>Magyarországon<br>nem gyanakodnak<br>hogy,<br>betegek.', 
lt34: 	'Mivel veszélyes a hipertónia?', 
lt35: 	'A hipertónia következményei veszélyesebbek, mint az onkológiai betegségek és a tuberkulózis kombinációja.<br> A hipertónia 89% -a szívrohamot eredményez. Eltömődés alakul ki az edényekben.<br>Az agyvérzés és a agyi érkatasztrófa kialakulásának kockázata magas.', 
lt36: 	'Különösen veszélyesek a következmények ha ön dohányzik, alkoholt fogyaszt, helytelen étrend, ülő életmód, stressz, magas koleszterinszint. A túlsúlyos emberek 3-4-szer gyakrabban szenvednek Hipertóniával.', 
lt37: 	'FONTOS!<br>Hipertónia gyorsan halad, és minden ötödiket halálra fenyeget. Indítsa el a kezelést most és teljesen egészséges legyen.', 
lt38: 	'Tudósok szenzációs  fejlesztése', 
lt39: 	'A megelőző-terápiás szer létrehozása érdekében a magyar tudósok 8 évet töltöttek. Az év megnyitását a Gaydner orvosi nemzetközi díjjal jelölték ki. A többlépcsős tesztek bizonyították a létesítmény hatékonyságát, amelyhez az akadémikusok megkapták az összes szükséges engedélyt, minőségi tanúsítványt és állami támogatást.', 
lt40: 	'A ReCardio© készítmény <span> a következő elemeket tartalmazza: </ span>', 
lt41: 	'Csalán', 
lt42: 	'Számos vitamint, savakat, aktív mikroelemeket tartalmaz. Nagyon hatékony a szívbetegségek kezelésében. Segít megszüntetni az idegességet, javítja a szívműködést, javítja a véráramlást, elpusztítja a vérrögöket és erősíti az ereket.', 
lt43: 	'Galagonya', 
lt44: 	'Tónusozza a szívizomot, vasodilatációs hatást fejt ki, megakadályozza a plakk képződését és javítja a vérképet. Normalizálja a koleszterinszintet a vérben.', 
lt45: 	'Csökkenti a vérnyomást a szövetekben és a testrendszerekben, segít a felesleges folyadék felszámolásában.', 
lt46: 	'Riboflavin, B2-vitamin', 
lt47: 	'Az egyik legfontosabb vitamin az emberi szervezet számára. Szükséges a vörösvérsejtek és antitestek kialakulásához, a sejtek légzéséhez és a sejtek növekedéséhez.', 
lt48: 	'Tiamin, B1-Vitamin', 
lt49: 	'Olyan anyag, amely nélkül az idegrendszer nem képes megfelelően működni, megnyugtató hatással bír. Javítja a vérkeringést és részt vesz a hematopoiesisben', 
lt50: 	'Szakértői vélemény', 
lt51: 	'Megerősítem!<br>A fő harcos magas vérnyomással - bioflavonoid.Csak kátrányból és vadvörös fenyő kérgéből nyerik ki. Szinte minden magas vérnyomás elleni termékben jelen van.<br>De! Legtöbb gyártónak, annak tartalma egy maroknyi! Tehát a hatás évekig várható. Biztos vagyok benne, hogy az egyetlen bioflavonidban gazdag gyógyszer - ez ReCardio ©. .<b> Megláttam a képletét és a független szakértők megkötését. Megbecsült emberek. A gyógyszert a betegeknek ajánlom és szidom őket, ha öngyógyászattal foglalkoznak vagy elfogadják, amit a barátnők mondják "az interneten" "vagy a  műsorban hallott" . Ez rossz! Hipertóniával csak bizonyított módon kell harcolnia! Mely orvosok bíznak abban, amellyel a betegsége örökre eltűnik.', 
lt52: 	'Vadász Gzula<br>Doktor, Orvostudomány kandidátusa<br>30 éves tapasztalat', 
lt53: 	'Hatékonyság', 
lt54: 	'igazolt<br> klinikai vizsgálatokkal', 
lt55: 	'Klinikai vizsgálatokat végeztek 2016-ban a Kardiológiai Intézetben. Négy önkéntes csoport vett részt a klinikai vizsgálatokban 25 napon át.<br>1 csoport - 28-80 év közötti férfiak és nők, akik magas vérnyomású betegségben szenvednek és az ReCardio© szedtek.<br>2. csoport - Hasonló fogyatékkal élő férfiak és nők, "placebot" szedtek.', 
lt56: 	'A vizsgálat eredményei', 
lt57: 	'PLACEBO', 
lt58: 	'Az artériás nyomás<br> normalizálása', 
lt59: 	'Vénás trombózis eliminációja', 
lt60: 	'Arthritis eliminációja', 
lt61: 	'Az artériás nyomás<br> normalizálása', 
lt62: 	'Vénás trombózis eliminációja', 
lt63: 	'Arthritis eliminációja', 
lt64: 	'Visszajelzés emberektől, akik használták',
lt65: 	'Nővérem példáján meggyőződtem, hogy a tabletták vérnyomáscsökkenése iszkémiás stroke-ot - agyi infarktust eredményez. Az orvosok megmentették az életet, de soha nem érte el a végét. Amikor ezt a betegséget megérintettem, már régóta meg voltam és tudtam, hogy mit keresek a gyógynövények között. Az orvosom, nagyon bölcs asszony, ReCardio ajánlott. Nagyon hálás vagyok. 4 évig nem érzem magam hipertóniásnak. Teljesen egészséges vagyok, és nem félek szívrohamtól vagy stroke-tól. Mindenki számára jó egészséget kívánok!', 
lt66: 	'Katalin, Győr, 61 éves', 
lt67: 	'Néhány éve kezeltem szanatóriumában. Ott tanulmányokat végeztek egy új gyógyszer hipertónia ellen. Természetesen féltem. De mit tegyek? Egyik gyógyszer sem segített, és úgy döntöttem. Szerencsére, olyan csoportban voltam, aki ReCardio-t kapott, nem pedig "bábot". 2 óra elteltével a nyomás visszaállt a normális értékre. És fokozatosan nagyszerűen éreztem magam. Nagyon örülök, hogy részt vettem a termék vizsgálatában. Nyomás mindig rendben van.', 
lt68: 	'Inga, Debrecen, 47 éves', 
lt69: 	'51 éves vagyok. 3 évvel ezelőtt a klinikánál hipertóniát, szívelégtelenséget stb. diagnosztizáltak. Kínoztam, de nem tettem semmit. És fél évvel ezelőtt minden jel szerint micro strok volt. Aztán pánikba estem, de azonnal elutasítottam az előírt tablettákat. A kémia káros, mindenki tudja ezt. De mit tegyek, nem tudtam. Jó, hogy egy véletlen találkozó egy barátommal bemutatott a ReCardio. Most, ahogy kitalálhatod, nincs semmi. A nyomás normális, az egészség olyan, mint egy bikának!', 
lt70: 	'István, Pécs, 51 éves', 
lt71: 	'Előnyei', 
lt72: 	'Mentő.', 
lt73: 	'Már az első 6  órában  a vérnyomása normális!',
lt74: 	'Nem okoz hirtelen nyomásesést.', 
lt75: 	'Harmonikusan szabályozza a szív munkáját.', 
lt76: 	'Teljes rehabilitáció.',
lt77: 	'Az angina pectoris, az aritmia, a neuroza, a memória javítása, a beszéd és a mozgás helyreállítása a stroke után.', 
lt78: 	'Hatékony hatások mellékhatások nélkül',
lt79: 	'Az élő növényi sejtek teljesen megfelelnek az emberi test sejtjeinek.', 
lt80: 	'Alkalmazás módja', 
lt81: 	'A gyógyszer bevitele naponta kétszer 100 ml. <br> A javasolt 30 napos időtartam. <br> A részletes utasítások csatolva vannak.', 
lt82: 	'Adja meg az adataidat az alábbi űrlapon:', 
lt83: 	'B6-Vitamin',
lt84:   'A ReCardio a <sup class="sup_f_size">©</sup> <span class="lt40">következő elemeket tartalmazza:</span>'
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};