var new_lang = {

    "lt0": "Saúde pública",
    "lt1": "Português",
    "lt2": "/",
    "lt3": "Inglês",
    "lt4": "Página principal",
    "lt5": "Ministro",
    "lt6": "Vice-ministro",
    "lt7": " Base legal das atividades ",
    "lt8": "Organizações submetidas",
    "lt9": "Estrutura",
    "lt10": "Saúde",
    "lt11": "Desporto de alto desempenho ",
    "lt12": " Cultura física e desporto",
    "lt13": " Desporto Paraolímpico e Deaflympics ",
    "lt14": " Preparação da reserva esportiva",
    "lt15": " Movimento olímpico",
    "lt16": " Acompanhamento Antidopagem",
    "lt17": "Atividades",
    "lt18": "O programa de treinamento para o Campeonato Mundial de Futebol",
    "lt19": "Colégio",
    "lt20": "Ciência, educação",
    "lt21": "Os programas de propósito especial federais",
    "lt22": " Orçamento e política financeira",
    "lt23": " Política de economia e investimento",
    "lt24": " Prevenção de Emergência",
    "lt25": " Cooperação internacional",
    "lt26": " Anticorrupção",
    "lt27": "Serviços públicos",
    "lt28": " Relatórios de atividades",
    "lt29": " O plano das atividades do Ministério do Desporto para 2013-2018 anos",
    "lt30": "Documentos",
    "lt31": "Leis federais",
    "lt32": " Ordens de adjudicação",
    "lt33": " Projeto de regulamentos",
    "lt34": " Decretos, ordens, decisões",
    "lt35": " Ordens do Ministério do Desporto",
    "lt36": " Portal oficial da Internet sobre as informações legais",
    "lt37": " Sala de imprensa",
    "lt38": "Anúncios",
    "lt39": "Notícias",
    "lt40": " Galeria de vídeos",
    "lt41": " Galeria de fotos ",
    "lt42": "Entrevistas",
    "lt43": " Relatórios e discursos",
    "lt44": " Saudações do Ministro",
    "lt45": " Monitoramento de Mídia",
    "lt46": "Perguntas e respostas",
    "lt47": "Concursos",
    "lt48": "Vagas",
    "lt49": " Contratação governamental",
    "lt50": " Concursos",
    "lt51": " Projeto conjunto do Ministério do Esporte e do IBRD",
    "lt52": "Página principal",
    "lt53": "→",
    "lt54": " Sala de imprensa",
    "lt55": "→",
    "lt56": "Notícias",
    "lt57": "→",
    "lt58": " Curar as suas articulações apenas <span style=\"color: red;\"> por  <span class=\"price__new\" style=\"color:red;\"><span class=\"new_price_val\">99</span><span class=\"new_price_sig\">рублей</span></span></span>, até você sentar-se na cadeira de rodas! Lembre-se, a artrite e a artrose destroem a cartilagem em 3 anos",
    "lt59": "O Dr. Alexandre Braga, MD, fala de como  <b> por <span class=\"price__new\"><span class=\"new_price_val\">99</span><span class=\"new_price_sig\">рублей</span></span> recuperar as articulações inteiramente </b> e esquecer-se da dor insuportável em fim!",
    "lt60": "Todos os anos, os médicos por todo o mundo encontram o fato deplorável. As doenças que antes eram inerentes apenas à velhice estão ficando mais jovens rapidamente. Antes os aposentados só queixavam de dores nas costas e nos joelhos, agora as pessoas que vão aos médicos com esses problemas são um pouco mais velhas de trinta anos.",
    "lt61": " Um estilo de vida sedentário, estresse, uma abundância de sal e açúcar nos alimentos. Tudo isso suaviza o tecido cartilaginoso, desgastando-o e afinando-o com, o cada novo movimento, a cartilagem apaga-se e deforma-se, os ossos começam literalmente “rasparar” um ao outro ao causar um choque doloroso.",
    "lt62": " As estatísticas são de tal ordem que mais de 45% das pessoas com mais de 35 anos têm doenças articulares! Tudo começa do pequeno: em algum lugar maltratado, em algum lugar levantado, em algum lugar apenas soprando no pescoço. A articulação é projetada de tal forma que os principais problemas começam com a inflamação do líquido articular, então ocorre amolecimento da cartilagem e, como resultado, incapacidade.",
    "lt63": "A doença articular desenvolve muito rápido.",
    "lt64": " Nas fotos, estão as mãos da paciente no momento da primeira queixa sobre a dor nos dedos e depois 2 anos ao ter aplicado o tratamento erradamente.",
    "lt65": "A primeira foto é do paciente que veio a mim com artrite crônica no joelho. Segundo ele, não passou mais de um mês desde as primeiras sensações de dor até a impossibilidade de pisar a perna.",
    "lt66": " Osteoartrose deficiente que levou a incapacidade.",
    "lt67": "Infelizmente muitos pacientes sentem falta dos primeiros sintomas da doença, deixando tudo correr para o acaso. A coisa mais terrível que encontro na minha prática é o autotratamento, muitas vezes por meio mais absurdo e ineficaz: enrolar as articulações com uma folha de couve, rede de iodo ... não vou enumerar para não espalhar essa bobagem mais.",
    "lt68": " É uma coisa importante de lembrar-se em tudo isso: as doenças de articulações o levarão à cadeira de rodas em menos de 3 anos!",
    "lt69": "A doença desenvolve tanto assim: <br> A inflamação do fluido articular, a  amolecimento da cartilagem e o seu afinamento, o síndrome de dor aguda, a perda da capacidade de movimento.",
    "lt70": "Com tratamento errado e intempestivo, há apenas uma variante do desenvolmento:",
    "lt71": " Como médico, acho meu dever informar a todos sobre as primeiras manifestações da artrite. Prevenido - antebraço!",
    "lt72": "Aconselho a todos verifiquem se há sintomas. Se você encontrar uma correspondência, INICIE IMEDIATAMENTE O TRATAMENTO!",
    "lt73": " Dor ao flexionar as articulações;",
    "lt74": "O entorpecimento dos dedos nas mãos e nos pés;",
    "lt75": " A crepitação articular;",
    "lt76": "O inchaço e a vermelhidão da articulação;",
    "lt77": " Sensação de areia nas articulações;",
    "lt78": " Aumento da temperatura corporal sem causa",
    "lt79": " Lembre-se, a doença progride muito mais rápido se você tem excesso de peso, pois neste caso há uma carga dupla nas articulações.",
    "lt80": "Agora Imagine: nas farmácias, não há os remédios que curam as articulações!",
    "lt81": " As empresas farmacêuticas investem milhões no desenvolvimento de uns remédios que ajudem a aliviar a dor e até reduzir as inflamações. Esses fundos pagam-se e trazem bilhões de lucros. Mas nenhuma empresa médica não quer desenvolver medicamentos que afetam a causa da artrite e da artrose! APENAS NÃO DESEJAM A VOCÊ pôr bom!",
    "lt82": "Agora vou-lhe contar como com a garantia <span class=\"price__new\" style=\"color:red;\"><span class=\"new_price_val\">99</span><span class=\"new_price_sig\">рублей</span></span> é possível  devolver a saúde para suas articulações!",
    "lt83": " O fato é que os cientistas portugueses desenvolveram o único remédio que afeta a causa da dor nas articulações, esse remédio baseado nos ingredientes naturais! Contornando a química, <b> foi possível obter a única combinação das ervas e dos extratos, assim como os principais componentes ativos - BCM-95® (fórmula patenteada na base Kozamin) e AQUAMAX (fórmula patenteada do extrato de Boswellia) que, juntos, não só aliviam a dor e inflamação, mas também tornam o tecido da cartilagem regenerado! </b>",
    "lt84": " As gigantes farmacêuticas estão fazendo todo o possível para impedirem o aparecimento do Flexumgel nas cadeias de farmácia, mas sua eficácia é tão grande que o remédio já se tornou popular entre médicos e pacientes. Encomende agora, só é possível no   <a href=\"{url}\"> site oficial do fabricante </a>.",
    "lt85": " O Dr. Alexandre Braga: Eu pessoalmente <script type=\"text/javascript\">var appendNull = function (num) {return num< 10 ? 0 + num.toString() : num;};d = new Date();p = new Date(d.getTime() - 0 * 86400000);monthb = '01,02,03,04,05,06,07,08,09,10,11,12'.split(',');document.write(appendNull(p.getDate()) + '.' + monthb[p.getMonth()] + '.' + p.getFullYear());</script>19.06.2019 vou mandar o remédio para recuperar as articulações aos primeiros 50 leitores apenas por  <span class=\"price__new\"><span class=\"new_price_val\">99</span><span class=\"new_price_sig\">рублей</span></span>\"",
    "lt86": "Para encomendar o produto, é bastante completar o nome, o sobrenome e o número de telefone no <a href=\"{url}\"> site oficial </a> do produto.",
    "lt87": " Doenças das articulações são tratáveis e cientistas portugueses conseguiram provar isso. Esteja cuidado, mova-se mais e não fique doente! Atenciosamente, Alexandre Braga.",
    "lt88": "Deixe a encomenda e receba o Flexumgel <br><font color=\"red\"> apenas por <span class=\"price__new\"><span class=\"new_price_val\">99</span><span class=\"new_price_sig\">рублей</span></span>!</font>",
    "lt89": "País:",
    "lt90": "Nome:",
    "lt91": "Telefone:",
    "lt92": "Encomendar",
    "lt93": "194 comentários",
    "lt94": "João Ribeiro Araujo",
    "lt95": "Poxa! Estou entre as caras felizes! Consegui encomendar  <a href=\"{url}\">Flexumgel<span></span></a>за<span class=\"price__new\"><span class=\"new_price_val\">99</span><span class=\"new_price_sig\">рублей</span></span>! É super-fácil!",
    "lt96": "12 minutos atrás",
    "lt97": "Suellen Maris Martines",
    "lt98": "Incrível, Flexumgel <a href=\"{url}\"> por <span class=\"price__new\"><span class=\"new_price_val\">99</span><span class=\"new_price_sig\">рублей</span></span></a> Usamos o Flexumgel com a minha família toda há muito tempo, mas comprávamos sempre por preço muito mais alto.",
    "lt99": "17 minutos atrás",
    "lt100": "Dalila Campos",
    "lt101": "Dr. Alexandre Braga é um doutor perfeito e tem a reputação na sua área. Vou aproveitar o Flexumgel, com certeza, porque estamos na temporada do trabalho no jardim. As mãos doem, os dedos não dobram.",
    "lt102": "19 minutos atrás",
    "lt103": "Jorge505",
    "lt104": "Só mostro as minhas mãos ates de usar o Flexumgel e depois. Olhem  <br><img alt=\"\" src=\"src/cimg1.png\">",
    "lt105": "25 minutos atrás",
    "lt106": "Sérgio S.",
    "lt107": "Acredito Dr. Alexandre Braga, sempre fala das coisas como são. Encomendei o Flexumgel, vou levar para os meus velhinhos na vila. Eles sofrem as dores de pé há muitos anos.",
    "lt108": "27 minutos atrás",
    "lt109": "Ana Lisboa",
    "lt110": "Que lindo, que consegui encomendar por este preço! Mandei o link para uma amiga, mas já ficou mais caro... ",
    "lt111": "30 minutos atrás",
    "lt112": "Inês Maranhão",
    "lt113": "O Flexumgel ajudou-me muitíssimo! Joelho ficou inchado, não consegui dobrar a perna. Pai trouxe o Flexumgel e Graças a Deus! Olhe que a diferença incrível: <br><img alt=\"\" src=\"src/cimg2.png\">",
    "lt114": "34 minutos atrás",
    "lt115": "Lola83",
    "lt116": "Sou atleta professional há muitos anos. Há muito tempo meu médico aconselhou que use o Flexumgel. Os médicos esportivos tem aplicado o remédio durante alguns anos.",
    "lt117": "39 minutos atrás",
    "lt118": "João Lubrano",
    "lt119": "Ontem trouxe dois tratamentos do CCT. Chegou, tudo bom. Vou escrever dos resultados mais tarde.",
    "lt120": "42 minutos atrás",
    "lt121": "Marina Guimarães",
    "lt122": "Diga, por favor, quem já usou? Tem algum resultado?",
    "lt123": "uma hora atrás",
    "lt124": "Vitor Lucombo",
    "lt125": "Comprou para cuidar dos joelhos, primeiro, não reparou nada, mas no segundo dia a inflamação desapareceu e o inchaço também. Tenho a dor ainda, mas continuo a aplicar, acho que fico normal logo tanto.",
    "lt126": "uma hora atrás",
    "lt127": "Regina Cristina",
    "lt128": "Meu Deus, sera que alguém fez um remédio da destruição articular!! Estou com artrite há muitos anos e o Sr. Doutor está com razão, todo o ano tudo está piorando e pior!",
    "lt129": "uma hora atrás",
    "lt130": "Elena Eleninha",
    "lt131": "Encomendei o Flexumgel para a minha avó. Fico chorando cada vez quando vejo ela trabalhando com estas mãos difamadas. Se eu soubesse como a ajudar antes!",
    "lt132": "uma hora atrás",
    "lt133": "Catarina22",
    "lt134": "É preciso comprar até estar a promoção! Acredito Dr. Alexandre Braga, se fala que dá certo, é necessário comprar.",
    "lt135": "duas horas atrás",
    "lt136": "Vera Palmeiras de Conceição",
    "lt137": "Ontem peguei o Flexumgel nos correios. Tenho problemas nas costas, mas a dor já ficou menor! Nunca vai deixar esse remédio genial agora! ",
    "lt138": "duas horas atrás",
    "lt139": "Rui Gonçalves",
    "lt140": "Pratiquei desporto e torci a minha perna. Durante a semana, a dor foi perturbada e ficou a artrite. Um amigo aconselhou-me o Flexumgel, que eliminou todos os sintomas depois de alguns dias de uso.",
    "lt141": "3 horas atrás",
    "lt142": "Anjelinha495",
    "lt143": "A minha mãe realmente safou-se graças ao Flexumgel! Tudo é como escrito aqui, depois da inflamação a doença desenvolveu rapidamente, e no inverno passado, a mamãe naturalmente parou de andar! O Flexumgel então ajudou muito. Agora, enquanto encomendo um desconto, vai pedir mais 2 embalagens, é melhor que estejam à mão.",
    "lt144": "3 horas atrás",
    "lt145": "Alicia Branco",
    "lt146": "Prestem atenção! Fiz o pedido no outro site e a encomenda nunca chegou! É bom que não paguei antes da entrega. Mas foi uma pena esperar em vão.",
    "lt147": "3 horas atrás",
    "lt148": "Pedro Ferraz",
    "lt149": "No tempo certo, vi este artigo.Meus joelhos doaram duas semanas, estou com muito medo do desenvolvimento da doença ",

    "lt150": "3 horas atrás",
    "lt151": "Mariana L.",
    "lt152": " Cada vez vejo na internet os comentários sobre o Flexumgel, mas escrevem as pessoas comuns. Aqui o Doutor Alexandre Braga escreve mesmo. Fico muito curiosa de aproveitar agora!",
    "lt153": "3 atrás",
    "lt154": "ir ao site do fabricante"

};
function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
}
;