var new_lang = {
lt1: 'Alkoholismus může vyhrát! Zachraňte své blízké!',
lt2: 'Zprávy',
lt3: 'Komunikace',
lt4: 'Sledovat',
lt5: 'Časopis Med-Info',
lt6: 'Poradenství',
lt7: 'seznam léku a institucí',
lt8: 'Kategorie',
lt9: 'seznam',
lt10: 'Poradenství',
lt11: 'Sdělení',
lt12: 'Zábava',
lt13: '<br> Časopis Med-Info',
lt14: '<span> seznam </span> <br> léků a institucí',
lt15: '<span> konzultace </span> <br> položte otázku doktorovi',
lt16: 'mobilní <br> <span> </span> aplikace',
lt17: 'kategorie',
lt18: 'Témata',
lt19: 'analytika',
lt20: 'interaktivní články',
lt21: 'rozhovory s hvězdou',
lt22: 'infografika',
lt23: 'Historie čtenáře',
lt24: 'kulatý stůl',
lt25: 'citlivé otázky',
lt26: 'reportáž',
lt27: 'Články',
lt28: 'Nejnovější zprávy',
lt29: 'Včera v 13:26',
lt30: 'Prezentován top 100 nejlepších zubařů',
lt31: 'Včera v 21:56',
lt32: 'V prosinci proběhne prémie Czech Pharma Awards',
lt33: 'Včera v 14:24',
lt34: 'Dotazník: co je škodlivé pro zdraví v & nbsp; práci',
lt35: 'Vědci pěstují neurony, které produkují hormon štěstí',
lt36: 'Nejzajímavější',
lt37: 'rozhovor s odborníkem',
lt38: 'Simona Prudilová:’ Laserová operace v zubním lékařství – metoda budoucnosti',
lt39: 'Článek',
lt40: 'Jak se & nbsp; nesplést & nbsp; při výběru zubního kartáčku',
lt41: 'Alkoholismus',
lt42: 'Rozhovor s odborníkem',
lt43: 'Alkoholismus může být poražen! Zachraňte své blízké! <br> Primář z Prahy, MD, profesor Karel Bernstein',
lt44: 'Poznámka redakce: Podle nejnovějších údajů Rospotrebnadzoru, počet alkoholiků v Česku přesáhl 5 milionů osob, tj. 3,4% z celkového počtu obyvatel. Registrovaní jsou pouze 1,7% pacientů s alkoholismem. Alkohol byl příčinou úmrtí 1/3 všech mužů a 15% žen. Pokud to přeložíme do čísel, z alkoholu umírají asi 500 tis lidí ročně. Šokující údaje! Tolik lidí neumírají kvůli válkám, epidemiím a přírodním katastrofám, i když to dáme všechno dohromady. S nadměrným pitím alkoholu v Rusku přímo či nepřímo souvisí: 62,1% sebevražd, 72,2% vražd, 60% úmrtí na pankreatitidu, 67,7% na cirhózu a 23,3% na kardiovaskulární onemocnění. Každý rok je zaznamenáno více než 40 tisíc případů otravy nekvalitním alkoholem včetně úmrtí. Chcete-li se dozvědět, jak se zbavit tohoto onemocnění a stát se zdravějším člověkem, jsme se zeptali doktora lékařských věd, profesora Ondřeje Zítky',
lt45: 'Je to hrozné, když touha po alkoholu ničí lidský život, kvůli alkoholu rozpadají se rodiny, dětí ztrácí své otce a manželky manžele. Ale v dnešní době alkoholismus jako nemoc se stál o hodně mladším. Často propadají alkoholu zrovna mladí lidé, kteří ničí svou budoucnost a způsobují nenapravitelné škody na zdraví. Musím přiznat, že většinou zrovna ženy musí zachraňovat mužem, který je závislý na alkoholu: syna, manžela nebo otce. Ukazuje se, že závislého rodinného příslušníka lze zachránit a to v tajemství od něj. Dnes budeme hovořit o novém druhu prostředku <a target=‘_top’ href=‘‘> XX </a>, který se ukázala jako velmi efektivní.',
lt46: 'Jistě víte, že až donedávna jediným účinným prostředkem pro boj s závislost na alkoholu bylo kódování pacienta. Tato metoda má obrovské zápory - pacient musí dát souhlas s léčbou a uváženě jít na kódování a úplné odmítnutí alkoholu. Navždy. Ale většinou lidí, kteří pijí, nepovažují sebe za závislého na alkoholu a věří, že kdykoliv můžou ‘přestat’. Pouze jejich blízcí chápou, že ‘přestat’ s alkoholem nikdy nebudou schopní bez cizí pomoci. Co v tomto případě dělat? Přesvědčovat, argumentovat, nadávat a prosít člověka je úplně k ničemu, alkohol už má moc nad ním. Existuje jen jedna možnost – léčit milovaného člověka v tajnosti, abychom ho zachránili. To umožňuje nejnovější vývoj lékařů a vědců – prostředek XX, který za 2 týdny (14 dnů) je schopen vytvořit silný pocit averze k alkoholu a to i u chronických alkoholiků. Jakýkoli alkohol se stává odpůrným, dokonce i zápach alkoholu je nechutný.',
lt47: 'Jak funguje XX',
lt48: 'XX je preparát zcela se skládající se výhradně z přírodních surovin, což znamená, že nemá a nemůže mít kontraindikace, je bezpečný a může ho používat absolutně každý. Navíc <a target=‘_top’ href=‘‘> <b>‘,XX’ </b> </a> ta je lék s komplexním účinkem, kromě základní funkce blokování závislosti na alkoholu a formování návyků znechucení také zahajuje rekonstrukci procesů ve všech orgánech, které se začaly rozpadat pod vlivem alkoholu. Regeneraci dochází na buněčné úrovni v játrech, srdci, ledvinách a normalizaci nervového systému. XX odstraňuje psychologickou závislost na alkoholu, zvyk pití alkoholu zcela mizí a nahrazuje ho pochopením významu vlastního zdraví. Pacient se cítí svěže a plný energie bez nové porce alkoholu, necítí obvyklé ‘lámání’. ',
lt49: 'A jak to funguje, ptáte se? Vysvětlím to. XX pomocí použití specifických látek a antioxidantů ovlivňuje některé buněčné receptory, které jsou odpovědné za regeneraci její funkčnost. Probíhá ‘přepsání’ informace o nemocných buňkách na zdravé. Výsledkem toho je to, že tělo začíná proces ozdravení a vrací na zdravou vlnu.',
lt50: 'V současné době existuje pouze jedna oficiální internetové stránky, které prodávají preparát XX a ne levnou imitaci. XX se neprodává v lékárnách, pokud jste ho viděl v lékárně, je to podvod! O něm hodně mluví na našem kanálu a na dalších. A ne pro nic za nic, říkám vám! XX je složitá a unikátní směs nejvzácnějších a nejmocnějších přírodních léčivých látek. Tento nástroj se ukázal jako účinný nejen pro pacienty, ale i pro vědu, která uznala jako účinný lék. Ohromující účinek je pozorován již po 10-15 dnech léčby. Jak ukázaly studie, XX funguje!',
lt51: 'Výzkum',
lt52: 'Výsledky laboratorních testů <a target=‘_top’ href=‘‘>‘ XXa ‘</a> ve Výzkumném ústavu pro drogovou závislost:',
lt53: 'Vybrali jsme 85 dobrovolníků všech věkových kategorií, kteří trpí těžkou, lehkou a středně těžkou až těžkou formou závislosti na alkoholu. Výsledkem je, že po 30denní studii byly získány <b> následující výsledky: </b> ',
lt54: '1. Je zaznamenané zlepšení zdraví celé skupiny od 18 do 68 let.',
lt55: '2. Úplné odstranění závislosti na alkohol byl zaznamenáno u 96% pacientů.',
lt56: '3. Do 10 dnů od aplikaci většina pacientů uvedla o vzniklém odporu z vůní nebo chuti jakýchkoliv alkoholických nápojů.',
lt57: '4. Po 30 dnech 97% pacientů přestali používat alkohol, je zaznamenán zlepšený zdravotní stav srdce, jater a ledvin.',
lt58: '<strong>Pozor!</Strong>Stávají se stále častějšími případy prodeje padělaných výrobků XX! Proto speciálně pro naše čtenáře zadáváme tlačítko pro objednávky XX od jediného oficiálního výrobce! Tvorbou objednávky zaručeně získáte kvalitní produkt za nejlepší cenu! <br> Pro <strong> naše webové stránky</strong>je určená<strong>dodatečná sleva</strong>. Chcete-li ji získat, klikněte na tlačítko ‘Objednat’ níže. Tím se dostanete na oficiální stránky, kde si můžete vytvořit objednávku. Množství balení ve slevě je omezené!',
lt59: 'Komentáře',
lt60: 'Lucka Kovárska (Ostrava, 07.23.2016)',
lt61: 'No, nemůžu na to uvěřit! Nevěřím, že to pomůže…. Zkoušeli jsme se spoustu věcí. Ztratila jsem už naději…',
lt62: 'Lenka (Praha, 07.23.2016)',
lt63: 'Lucko, marně nevěříte, lépe si to zkuste, horší to pak prostě nebude! Také jsme byli léčeni s tímto prostředkem. Velice dobře nám to pomohlo. Přestal pít. Nyní pije velmi zřídka, o svátcích. Ovládá sebe a už se o něj nebojím. Hodně štěstí! Preparát funguje!',
lt64: 'Markéta Fabiánová, 46 let (Písek, 23. 07. 2016) ',
lt65: 'Co všechno jsem zkoušela, abych odnaučila svého syna pit pivo, ale pak jsem si uvědomila, že se jedná pivní alkoholismus. Ze začátku každý den po práci bral láhev piva, pak jednu pil po cestě a další bral na večer domu … Když ‘standard’ dosáhl 1,5 litru piva denně, uvědomila jsem si, že musím něco udělat! XXa jsem našla ne hned, byly i jiné metody, které nepomohly. XX mu dávala také spolu s čajem, nic necítil. Už třetí den přišel domů bez piva! Byla jsem šokována, ale nic neříkala a neptala se. Sledoval jsem, co se bude dít dál, a on absolutně zapomněl o pivu! Doufám, že navždy! ',
lt66: 'Radek Němec, profesor (Praha, 07.24.2016)',
lt67: '> Nemohl projít kolem této recenze… Markéto, nemáte za co! Neumíte si představit, jak jsem šťastný za vás a Marinu, jsem si jistý, že jste změnili životy blízkých k lepšímu! <br><br>S pozdravem, Radek.',
lt68: 'Katka Pospíšilova (Most, 24/07/2016)',
lt69: 'Lucko, pokud přestanete doufat a ztratíte veškerou naději, pak rozhodně nic nepomůže! Ale tento nástroj opravdu funguje, kromě toho cenově je velmi dostupný. Doporučuji všem objednat a osobně ověřit účinnost léku! ',
lt70: 'Monika Brožíkova (Hradec Králové, 07.24.2016)',
lt71: 'Moji příbuzní používali XX a také úspěšně (jsou muž a žena). Stálo se tak, že spolu začali propadat alkoholu… Už jsem myslela, protože doslova ztratili veškerý zájem o život. Měli štěstí, že podporovali se navzájem a oba tvrdě se rozhodli přestat. Ptala jsem si jich, říkají, že opravdu nechtějí pít, a když představují, že polykají sklenici vodky, hned se cítí špatně',
lt72: 'Helena Kolínská (Kladno, 25. 07. 2016)',
lt73: 'Zachránila jsem manžela pomocí XX, jeho otec a oba dědové zemřeli kvůli alkoholismu, už sám se také myslel, že bude následovat jejich příkladu, ale ne! Tajně jsem mu dávala XX každý den, a někdy to bylo těžké, ale podařilo se mi to. Na nic nepřišel a myslel, že sám přestal a přešel k rozumu. Zpočátku jsem chtěla mu říct pravdu, ale nedokázala jsem pokoušet osud. Věří, že dokázal to sám – ať se raduje a je na sebe hrdý. Pro mě je hlavní, aby byl střízlivý a zdravý!',
lt74: 'Honza (Kbely, 25. 07. 2016)',
lt75: 'Helena, správně, raději nic neříkejte, pro muži je lepší si myslet, že sami zvládli tento zlozvyk. Koupil jsem si mým rodičům XX, matka dal ho tajně otci a dokázala ho vytáhnout z lahve. Je škoda, že dřív tento preparát neexistoval, otec ztratil tolik let s vodkou… <br> Doufám, že touha po vodce se nevrátí k otci, ale pokud budete táhnout zpět, dáme mu to ještě jednou, matce  ještě zůstala zásoba XXa.',
lt76: 'Lucie Dvořáčkova (České Budějovice, 26.07.2016)',
lt77: 'Doufám, že XX zachránit matku před trpěným s otcovým pijáctvím, kolik toho jsme udělali, dokonce chodili k čarodějnici - nepomohlo. Po XXa již měsíc nebral prostředek, a doufám, že tak to bude pokračovat…',
lt78: 'Veronika (Praha, 07.27.2016) ',
lt79: 'Sdílím svou radosti taky. Vytáhla jsem manžela z chronického nadměrného pití, už několikrát jsem ho opouštěla, ale vracela jsem se, vždyť je to blízký člověk. Pak jsem narazila na XX, koupil jsem hodně s rezervou a začala dávat pít manželovi. A pomohlo to! Používal ho každý den po dobu 3 týdnů a je už celý ROK střízlivý. <br> Chci poděkovat tvůrcům preparátu, a takhle vypadá obal tohoto XXa.',
lt80: 'Patrik, 37 let (Zlín, 27.07.2016)',
lt81: 'Lidé, řekněte, kde jste to koupili? V lékárnách se neprodává. Rád bych se nedostal na padělek, jinak, když chápu správně, bude to k ničemu. ',
lt82: 'Radek Němec, profesor (Praha, 27.07.2016)',
lt83: 'Znovu opakuji, že’ XX ‘lze objednat pouze na <a target=‘_top’ href=‘‘> </a> oficiálních internetových stránkách, abyste se nespletli, jednoduše klikněte níže na tlačítko ‘Objednat’! Speciálně pro naše čtenáře máme skvělou slevu po dohodě s výrobcem, ale bude funkční jen malou chvíli, takže si pospěšte s objednávkou! <br>A dejte si prosím pozor na padělky. <br><br> S pozdravem, Radek. ',
lt84: 'Přidat komentář',
lt85: 'Vaše jméno',
lt86: 'Město',
lt87: 'Váš komentář: ',
lt88: 'Zprávy',
lt89: 'Podnikání',
lt90: 'Stát a medicína',
lt91: 'Hvězdy',
lt92: 'Věda',
lt93: 'Společnost',
lt94: 'Události',
lt95: 'Statistika',
lt96: 'Lékárna',
lt97: 'Zprávy MED-info',
lt98: 'Kalendář událostí',
lt99: 'Kategorie',
lt100: 'Reportáž',
lt101: 'Výzkum',
lt102: 'Kulatý stůl',
lt103: 'Video',
lt104: 'Infografika',
lt105: 'Interaktivní články',
lt106: 'Historie čtenáře',
lt107: 'Rozhovor s hvězdou',
lt108: 'Rozhovor s odborníkem',
lt109: 'Články',
lt110: 'Příručka',
lt111: 'Léky',
lt112: 'Instituce',
lt113: 'Poradenství',
lt114: 'Kategorie',
lt115: 'Naši lékaři',
lt116: 'Komunikace',
lt117: 'Blogy',
lt118: 'Skupiny',
lt119: 'Pracovní nabídky',
lt120: 'Zábava',
lt121: 'Soutěže',
lt122: 'Lékařský horoskop',
lt123: 'Testy',
lt124: 'Aplikace',
lt125: 'Med-Info',
lt126: 'Lékařské zprávy',
lt127: 'Lékařský horoskop',
lt128: 'Časopis Med-Info',
lt129: 'O projektu',
lt130: 'Partneři',
lt131: 'Kontakt',
lt132: 'Testy',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};