var new_lang = {

"lt1": "Seleccione su idioma preferido",
"lt2": "Inglés",
"lt10":"Ruso",  
"lt11": "Español",
"lt12": "Tagalog",
"lt13": "Menú",
"lt18": "Búsqueda por palabra clave, síntoma o condición",
"lt19":"Buscar",
"lt20": "Encontrar un médico",
"lt21": "Ubicaciones",
"lt22": "Ubicación",
"lt23": "Programas & Servicios",
"lt24": "Programas y servicios",
"lt25": "Biblioteca Health", 
"lt26": "Salud",
"lt27": "Pacientes &amp; & Visitantes",
"lt28":"Pacientes" , 
"lt29": "Información para pacientes y visitantes",
"lt30": "Cedars-Sinai",
"lt31":"Blog",  
"lt32": "La prostatitis",
"lt33": "Compartir",
"lt34": "Correo",
"lt35": "Imprimir",
"lt36": "Artículo de Andrés Prieto",
"lt37": "La prostatitis es una amenaza para tu masculinidad. ¿Cómo reconocerla y tratarla ?" , 
"lt38": "Fecha : <span class=\"commits__date commits__date_post\">19.12.2020</span> <i>Andrés Prieto </i>",
"lt39": "Compartir",
"lt40": "Tweet",
"lt41": "Publicar",
"lt42": "La prostatitis es una de las enfermedades crónicas más comunes en los hombres. Según la Organización Mundial de la Salud, el 80% de los hombres mayores de 35 años experimentan la enfermedad, y muchos de ellos ni siquiera saben que tienen la enfermedad. La prostatitis puede no manifestarse de ninguna manera, pero al mismo tiempo dar un golpe devastador a la salud de un hombre e incluso amenazar la vida",
"lt43": "Nos contó el andrólogo – urólogo Andrés Prieto sobre qué es la prostatitis, cómo reconocerla y tratarla adecuadamente.",
"lt44": "Andrés Prieto",
"lt45": "El gran papel de la pequeña glándula",
"lt46": "Bueno, en términos simples, la prostatitis es una inflamación de la próstata. Siguiendo el dicho la próstata es el segundo corazón de un hombre corresponde al papel que desempeña tanto en la vida biológica como social de un hombre.",
"lt47": "La función de la glándula prostática es producir la secreción que se considera caldo de cultivo para los espermatozoides. También realiza la regulación hormonal en el cuerpo - transforma y activa la hormona sexual masculina testosterona.",
"lt48": "Es el trabajo correcto de la próstata lo que determina la función reproductiva, la calidad de vida sexual, el bienestar general y la apariencia de un hombre.",
"lt49": "Pero debido a la ubicación anatómica, la secreción hormonal activa y las infecciones, la próstata a menudo se convierte en un objetivo de prostatitis, que en casos desatendidos conduce a consecuencias terribles.",
"lt50": "Próstata normal e inflamada",
"lt51": "La prostatitis: ¿qué la hace tan peligrosa?",
"lt52": "La prostatitis puede causar inflamación de la vejiga, riñones, vesícula seminal, testículos, de hecho, la próstata se convierte en la fuente de una inflamación crónica, la cual con la corriente de la sangre lleva la infección a otros órganos, más a menudo cercanos.",
"lt53": "También la inflamación crónica en la glándula prostática puede causar esclerosis: el reemplazo de las células glandulares por tejido conectivo.",
"lt54": "Además, la prostatitis es un factor determinante en el desarrollo del adenoma prostático, un crecimiento benigno del tejido glandular. Muchos estudios también han demostrado un vínculo entre la prostatitis y el cáncer de próstata.",
"lt55": "Las patologías crónicas de la próstata conducen inevitablemente al desarrollo de la disfunción sexual en un hombre, acompañado de dificultad para obtener el orgasmo y eyaculación, dolor durante el contacto sexual. Impotencia, infertilidad, andropausia temprana,  son todos los efectos de la prostatitis.",
"lt56": "¿Cómo reconocer la prostatitis?",
"lt57": "No hay problemas con esto cuando se pronuncian los síntomas de la prostatitis: dolor punzante en la zona de la ingle y la parte inferior del abdomen, micción dolorosa.",
"lt58": "Pero la prostatitis también puede filtrarse de forma oculta, sin dar un cuadro clínico preciso.",
"lt59": "Un hombre puede sentirse débil, con fatiga, un ligero aumento de la temperatura, dolor muscular.",
"lt60": "El deterioro también se observa en el ámbito sexual: la libido disminuye, la erección se vuelve lenta e inestable.",
"lt61": "Aparecen la apatía, irritabilidad, sensibilidad, depresión.",
"lt62": "Los problemas con la eyaculación, la incapacidad para culminar las relaciones sexuales o culminar demasiado temprano",
"lt63": "Sobre los tratamientos para la prostatitis",
"lt64": "Anteriormente, el tratamiento estándar incluía toda una gama de procedimientos y medicamentos: El masaje de próstata es desagradable para los hombres, la fisioterapia, los antibióticos a largo plazo.",
"lt65": "Los antibióticos en las cantidades prescritas para la prostatitis, ocesionan un golpe devastador para el cuerpo. El hígado, riñones, estómago, la microflora intestinal sufren mucho. Se desarrolla una enfermedad ulcerosa, el sistema inmunitario se deprime",
"lt66": "La inmunodeficiencia crónica se desarrolla. El cuerpo ya no es capaz de luchar por sí solo, la persona se ve obligada a pasar el resto de su vida  bebiendo medicamentos: algunos son tratados, otros enmascaran las consecuencias. La persona deja de sentir las señales del cuerpo: dolor, por lo que mientras su cuerpo es destruido, permanece en la oscuridad.",
"lt67": "Masaje prostático",
"lt68": "¿Cómo tratarse?",
"lt69":  "Los mejores urólogos españoles insisten en que es posible y necesario tratar la prostatitis exclusivamente por medios naturales. Es gracias a este tratamiento que los médicos tratan la prostatitis como casi resfriado común",
"lt70": "Juan Méndez y Alberto Casas, urólogos del Instituto de Salud Reproductiva de Sevilla, patentaron en 2012 el único compuesto que alivia los síntomas de la inflamación y la prostatitis en el menor tiempo posible. No fue hasta 2020 que los fabricantes europeos pudieron negociar con los desarrolladores del compuesto y sobre su patente comenzaron a producir un medicamento llamado <a href=\"\">XX</a>.",
"lt71": "Este compuesto actúa como un inmunoactivador:",
"lt72": "Se activa la propia inmunidad del cuerpo, aumenta la producción de anticuerpos",
"lt73": "Se mejora la microcirculación de sangre y linfa en la pelvis pequeña, lo que previene el estancamiento patológico en la próstata",
"en74": "A",
"lt75": "se mejora la función eréctil",
"lt76": "se alivia el dolor",
  "lt 77": "A su vez, el <a href=\"\">XX</a> protege contra el adenoma y el cáncer de próstata, ya que reduce la actividad de las células atípicas que conducen al desarrollo de tumores malignos.",      
 "lt78": "El <a href=\"\">XX</a> se recomienda incluso para los hombres que no tienen prostatitis, sólo para mantener la salud del sistema reproductivo, ya que ayuda a mejorar la potencia, aumenta la duración de las relaciones sexuales y mejorar la calidad del líquido seminal.",  
"lt79": "¿Dónde comprarlo?",
"lt80":"El XX se puede encontrar en farmacias o pedir en el sitio web del fabricante, aquí no se encontrará con una falsificación y podrá comprar el producto a costo, sin porcentajes de los revendedores. El enlace al sitio web del fabricante está más abajo:",
"lt81": "Ordenar el XX en el sitio web del fabricante con descuento",
"lt82": "Comentarios:",
"lt83": "Pedro Alcantara",
"lt85": "Siempre he considerado la prostatitis una enfermedad de las personas de avanzada edad. Nunca pensé que me afectaría a mis 38 años. Hace aproximadamente un año, de vez en cuando comenzó a aparecer algo de dolor en la ingle. No muy fuerte, así que ni siquiera le presté atención. En el examen programado, el urólogo sólo se enteró de que tenía prostatitis. Inmediatamente prescribió un tratamiento con <a href=\"\">XX</a>. Después de tomar el tratamiento, los exámenes mostraron que no había inflamación! Es más, notó una mejora en la potencia; el sexo se hizo mucho más largo y vivo",
"lt86": "Miguel Santos",
"lt88": "Wow. No pensé que la prostatitis pudiera filtrarse de forma oculta. Debería chequearme, tengo algunas sospechas.",
"lt89": "Leonardo Jiménez",
"lt91": "Oh, pero cuanto me ha hecho sufrir este mal! Con que no me he tratado, antibióticos, masajes, muchas drogas. Todo para nada. Sólo me dañé el tracto gastrointestinal. La prostatitis volvía constantemente con nuevos síntomas, empeorando cada vez más. Un amigo me aconsejó el XX. Ya no tengo que recordar este problema",  
"lt92": "Fernando Buendía",
"lt94": "En cambio yo me pedí el medicamento desde América, ",
"lt95": "Ivan Domínguez",
"lt97": "¡Gracias por el artículo! He ordenado el <a href=\"\">XX</a>",
"lt98": "Gregorio Manzanares",
"lt100": "Siempre he tenido miedo d contraer alguna enfermedad de la próstata. Hasta ahora, creo que todo está bien, pero pediré el XX como prevención",
"lt101": "David Juárez",
"lt103": "Gracias por hablar abiertamente de este problema! Sufrí de prostatitis durante muchos años, fui a muchos médicos, vivía con antibióticos todo el tiempo. Pero la enfermedad no se iba a ninguna parte. Tal vez los síntomas desaparecieron por un tiempo, pero luego regresaron con el doble fuerza. Me enteré sobre el compuesto XX por accidente, ahora ni siquiera recuerdo dónde. Me bebí el curso sin creer que me ayudaría. Pero este compuesto realmente funcionó! Ya pasó más de un año y la enfermedad no vuelve.",
"lt104": "Margarita Viñas",
"lt106": "Mi marido tiene prostatitis crónica, constantemente vemos a los doctores, estamos desesperados. Tal vez  le ayude el XX ?",
"lt107": "Eva Santamaria",
"lt109": "¡Gracias por el consejo!",
"lt110": "Andrés Silva",
"lt112": "Tenemos que probar este remedio. Tan pronto como me traten, la prostatitis volverá de todos modos. Estoy cansado de eso.",
"lt113": "¿Te gustaría escribir un mensaje?",
"lt114": "A¿Desea escribir un mensaje?",
"lt115": "Su mensaje fue enviado para moderación",
"lt116": "Compartir",
"lt117": "Tweet",
"lt118": "Publicar",
"lt119": "Categorías populares",
"lt120": "SALUD",
"lt121": "CIENCIA E INNOVACIÓN",
"lt122": "Comunidad",
"lt123": "Blog y revistas",
"lt124": "Revistas de Blog y Inicio",
"lt125": "Blog",
"lt126": "Revistas",
"lt127": "Tecnologías",
"lt128": "Nuestra Comunidad",
"lt135": "Temas Populares",
"lt136": "Investigación",
"lt137": "Innovaciones",
"lt138": "Tecnologías",
"lt139": "Pruebas clínicas ",
"lt140": "Salubridad",
"lt141": "Compartir",
"lt142": "Correo",
"lt143": "Imprimir",
"en144": "Ayuda",
"lt145": "Regalar",
"lt146": "solitariossy ancianos",
"lt147": "Voluntariado",
"lt148": "Curso de formación",
"lt149": "Acerca de nosotros",
"lt150": "Los indicadores de calidad",
"lt151": "Acerca de nosotros",
"lt152": "Cómo encontrarnos",
"lt153": "Acerca de la Compañía",
"lt154": "Para Profesionales",
"en155": "A",
"lt156": "Manual de personal médico",
"lt157": "Entrada para el personal",
"lt158": "Contactos",
"lt159": "Contáctenos",
"lt160": "Noticias",
"lt161": "Blog y revistas",
"lt162": "Acontecimientos",
"lt163":"SUBSCRÍBETE ",
"lt164": "Acompáñanos en Facebook",
"lt165": "Síguenos en Twitter",
"lt166": "Míranos en YouTube",
"lt167": "Síguenos en Instagram",
"lt168": "Descargar nuestra aplicación",
"lt169": "© 2020 Cedars-Sinai. Todos los derechos están protegidos.  Una organización sin fines de lucro 501(c)(3) ",
"lt170": "Condiciones de operación",
"lt171": "política de privacidad",
"lt172": "Mapa del sitio",




};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };