var new_lang = {

    "lt0": "ext_2646875",
    "lt1": "weniger als 10",
    "lt2": "Abonnieren",
    "lt3": "Profil",
    "lt4": "div[id^=AdFox_banner],div[id^=begun_block],div[id^=begun_block]>iframe,iframe[id^=AdFox_iframe] {display: block;margin-right: auto;margin-left: auto}div[id^=begun_block],div[id^=__ban_] {flex: 1 1 auto;max-width: 100%;width: 100%}",
    "lt5": "[]",
    "lt6": "HTML BODY {margin: 0;padding: 103px 0 0;}HTML.html-adaptive BODY {padding-top: 0;}",
    "lt7": "?",
    "lt8": "LiveJournal",
    "lt9": "Startseite",
    "lt10": "<!---- >Rating<!---->",
    "lt11": "Werbung Deaktivieren",
    "lt12": "<!---->#LJ20<!---->",
    "lt13": "<svg class=\"svgicon flaticon flaticon--login\" height=\"16\" width=\"16\" xmlns=\"http://www.w3.org/2000/svg\"><use xlink:href=\"#flaticon--login\"></use></svg>Anmelden",
    "lt14": "Anmelden",
    "lt15": "Blog ERSTELLEN",
    "lt16": "ERSTELLEN",
    "lt17": "<span class=\"s-header-item-post--long\" > Deutsch</span>(de)",
    "lt18": "anna_wagner",
    "lt19": "—",
    "lt20": "Abonnieren",
    "lt21": " LJ Stil",
    "lt22": "Anmelden",
    "lt23": "Kein Konto?",
    "lt24": "Registrieren",
    "lt25": "aktuelle Einträge",
    "lt26": "Archiv",
    "lt27": "Freunde",
    "lt28": "Persönliche Info",
    "lt29": "Früher Themen",
    "lt30": "WIE HABE ICH DEN FUSSPILZ IN NUR EINEM MONAT BESIEGT!",
    "lt31": "Hier werde ich mit Ihnen interessante Ereignisse aus dem Leben teilen",
    "lt32": "Previous Entry",
    "lt33": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 * 60 * 60 *2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month +\".\" + year);</script>22.8.2020",
    "lt34": "anna_wagner",
    "lt35": "Gestern habe ich mir endlich gesagt: \'Gott Sei Dank ist es vorbei.\"Sechs Monate lang habe ich mit Fußpilz gequält.Wenn jemand denkt, dass ich aus einer Mücke einen Elefanten mache, dann weiß er oder sie nichts darüber, was eine Person durchmachen muss, die mit dieser Krankheit konfrontiert ist.Hören Sie es!? MIT DER KRANKHEIT.Nicht einer Unannehmlichkeit, das man als unwichtig abtun kann, sondern eine ernsthafte, gesundheitsgefährdende und lebensbedrohliche Pathologie.Aber das Wichtigste zuerst.",
    "lt36": "ANGST UND VERWIRRUNG",
    "lt37": "Die ersten alarmierenden Anzeichen habe ich nach dem Urlaub in Thailand bemerkt. Nein, nicht so. Eine Woche nach meiner Rückkehr aus Thailand hatte ich einen leichten Juckreiz zwischen meinen Zehen. Es ist mir jetzt klar, dass ich sofort zum Arzt laufen musste. Aber dann habe ich es nicht Wert gelegt, zu entscheiden, dass es selbst passieren wird. Und der Juckreiz tat mir nicht weh.",
    "lt38": "Zu meinem Entsetzen, nach zwei Wochen Juckreiz war nicht vorbei, sondern auch deutlich verstärkt. In anderen Momenten schien es mir völlig unerträglich, ich wollte sogar die Haut von meinen Füßen entfernen, nur um dieses lästige Gefühl loszuwerden. Die Füße begannen stark zu schwitzen und schrecklich zu riechen. Als ich meine Schuhe auszog, hatte ich das Gefühl, dass irgendwo in der Nähe gerade Müll gegossen wurde. Und als ob ich nicht genug von unerträglichem Juckreiz und giftigem Gestank hatte, änderten meine Nägel ihre Farbe.",
    "lt39": "Von der plötzlichen Erkenntnis, dass ich einen Pilz habe, verlor ich den Mut. Kann ich nie wieder offene Schuhe tragen? Werden meine Nägel zu hässlichen Wucherungen von schmutzigem Grün? Warum ist mir das passiert? Und was wird jetzt passieren? Oh mein Gott, das ist eine Schande!",
    "lt40": "BRUTALER BETRUG",
    "lt41": "Ich musste mich anstrengen, um endlich einen Spezialisten zu finden. Der Arzt untersuchte meine Beine und schüttelte den Kopf, und so er mich noch mehr erschreckte. Ich habe direkt in seinem Büro geweint. Er fing sofort an, mich zu beruhigen. Er sagte, dass ich eine zweite Phase der Mykose habe, aber ich muss nicht verzweifeln. Wenn ich geheilt werden will, muss ich mich in die Hand nehmen und strikt seinen Anweisungen folgen. Ansonsten erwarten mich katastrophale Folgen. Schließlich, die Ausbreitung des Pilzes und die von ihm Mykotoxine verschlimmern meine Darmflora so, dass wird der Körper für das eindringen von verschiedenen pathogenen Bakterien, Viren, sowie für die Entwicklung von Krebserkrankungen anfällig.",
    "lt42": "Natürlich war ich bereit, alles zu tun, nur um diesen verdammten Pilz loszuwerden. Der Arzt hat mir die Menge von teuren Medikamente und Salben verschrieben. Ich begann die Behandlung, befolgte alle Einschränkungen, nahm Tabletten und benutzte die Creme. Einen Monat später schien es mir, dass der Pilz zurückging. Ich war so froh, dass ich es nicht mit Worten beschreiben konnte. Leider war die Freude nur von kurzer Dauer. Der Juckreiz ist nach anderthalb Wochen wieder da. Ich ging wieder zum selben Arzt, er verschrieb mir wieder den gleichen teuren Kurs. Nachdem passierte das gleiche: die Krankheit zog sich angeblich zurück und kehrte dann plötzlich eine Woche später zurück.",
    "lt43": "Ich konnte nicht verstehen, was passierte. Ich brauchte etwas Unterstützung. Ich beschloss, meiner engen Freundin über diese Situation zu erzählen. Sie hörte mir zu und rief sofort ihren Ex-Mann, Hans, der als Arzt arbeitet, an und bat ihn, mit mir zu treffen.",
    "lt44": "Eine Woche später saß ich schon in seinem Büro und erzählte ihm die gleiche Geschichte. Als ich über die erneute Behandlung und den nächsten Durchgang des Kurses erzählte, griff er sich an den Kopf. Ich habe nicht verstanden, was ich falsch gesagt und getan habe. Dann hat er mir erklärt, dass der Arzt, an den ich gerichtet habe, gelinde gesagt, gewissenlos ist. Er hat mich nicht angelogen, als er meinen Fall als ernst eingestuft hat, und er hat mich nicht verstellt, als er von den schrecklichen Folgen sprach. Aber als er mir teure Medikamente verschrieb, war er nicht von der medizinischen Ethik und dem Eid des Hippokrates geleitet, sondern von einem Durst nach persönlichem Gewinn. Es ist schon lange kein Geheimnis mehr, dass viele Ärzte in Absprache mit Pharmaunternehmen sind. Es ist vorteilhaft, die Krankheit nicht zu behandeln, sondern nur ihre Symptome zu beseitigen, so dass die Menschen immer wieder für eine weitere portion Medikamente kommen und eine ordentliche Summe verteilen.",
    "lt45": "DIE LANG ERSEHNTE RETTUNG",
    "lt46": "Ich war wie mit Eiswasser übergossen! Ich dachte, ich würde in Ohnmacht fallen. Als ich wieder zu mir kam, fragte ich, was ich tun sollte. Hans antwortete, dass es einen Mittel gibt. Er riet mir, die Salbe<b><a href=\"{url}\"><span class="productName"></span></a></b>im Internet zu bestellen. Er sagte, dass dieses Mittel kann man kaum in Apotheken finden. Wegen hoher Effizienz und niedrigen Preis ist es einfach unrentabel, es zu verkaufen. Die Sache ist, dass<b><a href=\"{url}\"> <span class="productName"></span> < /a></b > nicht nur die Symptome bekämpft, sondern die Ursache der Krankheit beseitigt.Darüber hinaus wirken sich die Wirkstoffe von < b > <a href=\"{url}\">Salben</a> < /b>positiv auf die Mikroflora des Körpers aus und verhindern mögliche Rückfälle.",

    "lt47": "In Büro von Hans holte ich das Telefon aus der Tasche und fand eine Website, wo kann man<b><a href=\"{url}\"><span class="productName"></span></a></b> bestellen. Buchstäblich am nächsten Tag lieferte mir der Kurier ein Paket nach Hause, und ich begann mit der Behandlung. Als ich<b><a href=\"{url}\">Salbe</a></b>gecremt habe, spürte ich fast sofort die Linderung des Juckens. Es war das erste gute Zeichen. Nach anderthalb Wochen verschwand schließlich der unangenehme Geruch, und nach einem Monat mit ein wenig Fingernägel wurden wieder rosa. Es war eine echte Freude! Ich beschloss jedoch, nicht aufzuhören und fuhr fort, meine Füße für einen Monat zu schmieren. Als die Salbe in der Tube zu Ende kam, war ich nervös. Was wird als Nächstes passieren? Kommt dieser verdammte Pilz zurück? Wie glücklich war ich, als es innerhalb von eineinhalb Monaten nach dem Ende des Kurses keine Anzeichen von Krankheit gab! Und noch nicht! Ich habe gewonnen! Dank<b><a href=\"{url}\"><span class="productName"></span></a></b>kann ich wieder ein normales Leben führen. Offene Schuhe tragen, ohne Angst, in den Pool zu gehen. Es ist ein wahres Wunder. Ich bin wieder gesund und glücklich, was ich allen Wünsche.",
    "lt48": "Wenn jemand leidet unter Fußpilze so wie noch vor kurzem ich litt, lasse ich für euch einen Link, wo man <b><a href=\"{url}\"><span class="productName"></span></a></b>bestellen kann. Ich gebe mein Wort, in eineinhalb Monaten werden Sie völlig gesund sein.",
    "lt49": "Geben Sie Ihre Daten in das Formular um<b><a href=\"{url}\" style=\"font-size: 20px;\">«<span class="productName"></span>»</a></b><br>zum Aktionspreis<b><span class=\"new_price_val\">39</span><span class=\"new_price_cur\">€</span></b> zu bestellen",
    "lt50": "Das Angebot dauert bis<script type=\" text/javascript\"> var appendNull = function (num) {return num < 10 ? 0 + num.toString() : num; }; d = new Date(); p = new Date(d.getTime() - 0 * 86400000); monthb = 'Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember'.split(','); document.write(appendNull(p.getDate()) + ' + monthb[p.getMonth()] + ' + p.die Methode getFullYear()); </script>24. August 2020",
    "lt51": "bestellen",
    "lt52": "* bei Buchung eines Kurses",
    "lt53": "Tags:",
    "lt54": "<a href=\"{url}\" rel=\"tag\">Frankfurt < /a>,",
    "lt55": " <a href=\"{url}\"rel=\"tag\">Ich</a>,",
    "lt56": " <a href=\"{url}\"rel=\"tag\" >Italiener und Italiener</a>,",
    "lt57": " <a href=\"{url}\"rel=\" tag\">Wer in einem fremden Land gut leben kann</a>,",
    "lt58": "mein Deutschland",
    "lt59": "165 Kommentare",
    "lt60": "einen Kommentar schreiben",
    "lt61": "teilen",
    "lt62": "Link",
    "lt63": "Kommentare",
    "lt64": "( 165 comments —<a href=\"{url}\" rel=\"nofollow\">Leave a comment</a>)<div id=\"ljqrttopcomment\" style=\"display: none;\"></div>",
    "lt65": "Seite1 aus 2",
    "lt66": "&lt;&lt;",
    "lt67": "[1]",
    "lt68": "[2]",
    "lt69": "&gt;&gt;",
    "lt70": "Paulina Bauer",
    "lt71": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 05:33 am (UTC)",
    "lt72": "Ich hatte die gleichen Probleme, genau so. Ich musste sogar auf eine Reise zum Meer mit Freunden verzichten, weil es eine Schande war, mit diesem am Strand zu kommen. Was ich nur nicht versucht hatte, am Ende half genau<b><a href=\"{url}\"><span class="productName"></span></a></b>.<br>",
    "lt73": "Link",
    "lt74": "|",
    "lt75": "Reply",
    "lt76": "|",
    "lt77": "Thread",
    "lt78": "Emil Müller",
    "lt79": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 04:31 pm (UTC)",
    "lt80": "Schämen Sie sich nicht?! Warum halten Sie Leute für Narren?! Jeder weiß genau, dass keine Medikamente diesen Effekt erzielen. Es ist eine lange und komplexe Behandlung notwendig!",
    "lt81": "Link",
    "lt82": "|",
    "lt83": "Reply",
    "lt84": "|",
    "lt85": "Thread",
    "lt86": "Maria Kaufmann",
    "lt87": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 04:35 pm (UTC)",
    "lt88": "Emil, sagen Sie keinen Unsinn. Lesen Sie zuerst, was andere Leute schreiben. Wenn Sie es nicht glauben, hier ist mein Ergebnis für einen Monat.<p><img alt=\"\" src=\"./src/9.png\" style=\"width: 300px; margin: 20px 0 0\"></p>",
    "lt89": "Link",
    "lt90": "|",
    "lt91": "Reply",
    "lt92": "|",
    "lt93": "Thread",
    "lt94": "Simona Schröder",
    "lt95": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 04:58 pm (UTC)",
    "lt96": "Maria, das Ergebnis ist toll!",
    "lt97": "Link",
    "lt98": "|",
    "lt99": "Reply",
    "lt100": "|",
    "lt101": "Thread",
    "lt102": "Emil Müller",
    "lt103": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 05:10 pm (UTC)",
    "lt104": "Was für eine Dummheit? Keine Salbe ohne Kombination mit anderen Medikamenten ist dazu nicht fähig.",
    "lt105": "Link",
    "lt106": "|",
    "lt107": "Reply",
    "lt108": "|",
    "lt109": "Thread",
    "lt110": "Maria Kaufmann",
    "lt111": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 05:23 pm (UTC)",
    "lt112": "Was brauchen Sie noch? Sie haben bereits Fotos gesehen…",
    "lt113": "Link",
    "lt114": "|",
    "lt115": "Reply",
    "lt116": "|",
    "lt117": "Thread",
    "lt118": "Otto Neuner",
    "lt119": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 05:58 pm (UTC)",
    "lt120": "Ich habe schon lange von dieser Salbe gehört. Ich dachte, das wäre noch ein Trick von Betrügern. Aber immer noch hatte ich beschlossen, es zu versuchen, weil ich nichts zu verlieren hatte. Das Ergebnis hat mich angenehm überrascht, obwohl bis zur vollständigen Heilung noch gearbeitet werden muss.<p><img alt=\"\" src=\"./src/img4.jpg\" style=\"width: 300px; margin: 20px 0 0\"></p>",
    "lt121": "Link",
    "lt122": "|",
    "lt123": "Reply",
    "lt124": "|",
    "lt125": "Thread",
    "lt126": "Andreas Pfeiffer",
    "lt127": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 06:13 pm (UTC)",
    "lt128": "Otto,<b><a href=\"{url}\"><span class="productName"></span></a></b>wirklich funktioniert! Versuchen Sie, den Kurs fortzusetzen! In einem Monat werden Sie völlig gesund sein!",
    "lt129": "Link",
    "lt130": "|",
    "lt131": "Reply",
    "lt132": "|",
    "lt133": "Thread",
    "lt134": "Nina Lindermann",
    "lt135": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 06:22 pm (UTC)",
    "lt136": "Können Sie mir helfen? Kann ich noch<b><a href=\"{url}\"><span class="productName"></span></a></b>bestellen? Ich kann es nicht aushalten, es gibt keine Kräfte.",
    "lt137": "Link",
    "lt138": "|",
    "lt139": "Reply",
    "lt140": "|",
    "lt141": "Thread",
    "lt142": "Paul Becker",
    "lt143": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 06:35 pm (UTC)",
    "lt144": "Natürlich! Sie haben die Zeit. Ich habe vorgestern bestellt, heute schon geliefert.<p><img alt=\"\" src=\"./src/<span class="productName"></span>.png\" style=\"width: 300px; margin: 20px 0 0;\"></p>",
    "lt145": "Link",
    "lt146": "|",
    "lt147": "Reply",
    "lt148": "|",
    "lt149": "Thread",
    "lt150": "Peter Hubert",
    "lt151": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 07:01 pm (UTC)",
    "lt152": "<b><a href=\"{url}\"><span class="productName"></span></a></b>wirklich funktioniert! Keine teuren Pillen, einfach vergessen Sie nicht, Ihre Füße einmal am Tag zu cremen!<p><img alt=\"\" src=\"./src/-ololZdZIWw.jpg\" style=\"width: 300px; margin: 20px 0 0\"></p>",
    "lt153": "Link",
    "lt154": "|",
    "lt155": "Reply",
    "lt156": "|",
    "lt157": "Thread",
    "lt158": "Robert Braun",
    "lt159": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 07:28 pm (UTC)",
    "lt160": "Was ich nur nicht mit diesem verdammten Pilz gemacht habe. Jetzt habe ich den Mut verloren. Um ehrlich zu sein, wird<b><a href=\"{url}\"><span class="productName"></span></a></b>es helfen?",
    "lt161": "Link",
    "lt162": "|",
    "lt163": "Reply",
    "lt164": "|",
    "lt165": "Thread",
    "lt166": "Helena Schneider",
    "lt167": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 07:33 pm (UTC)",
    "lt168": "Natürlich! Ich habe den Pilz in zwei Monaten vollständig losgeworden.",
    "lt169": "Link",
    "lt170": "|",
    "lt171": "Reply",
    "lt172": "|",
    "lt173": "Thread",
    "lt174": "Johanna Klein",
    "lt175": "<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 *60 * 60 * 2000);var day = d.getDate();var month = d.getMonth() + 1;var year = d.getFullYear();document.write(day + \".\" + month + \".\" +year);</script>22.8.2020 08:15 pm (UTC)",
    "lt176": "Das ist toll! Ich bestellte, und ich habe keine Angst mehr, auf meine Füße zu schauen!<p><img alt=\"\" src=\"./src/IMG_2831.jpg\" style=\"width: 300px; margin: 20px 0 0\"></p>",
    "lt177": "Link",
    "lt178": "|",
    "lt179": "Reply",
    "lt180": "|",
    "lt181": "Thread",
    "lt182": "Page 1 of 2",
    "lt183": "&lt;&lt;",
    "lt184": "[1]",
    "lt185": "[2]",
    "lt186": "&gt;&gt;",
    "lt187": "( 165 comments —<a href=\"{url}\" rel=\"nofollow\">Leave a comment</a>)<div id=\"ljqrtbottomcomment\" style=\"display: none;\"></div>",
    "lt188": "Beilen Sie sich, ein Salbe «<span class="productName"></span>» zum Aktionspreis<b><span class=\"new_price_val\">39</span><span class=\"new_price_cur\">€</span></b>zu bestellen!",
    "lt189": "Es gibt nur noch<span class=\"count\">54</span>Pakete.",
    "lt190": "Bestellen",
    "lt191": "* bei Buchung eines Kurses",
    "lt192": "100% Garantie",
    "lt193": "Wirksamkeit durch klinische Studien nachgewiesen",
    "lt194": "Profile",
    "lt195": "anna_wagner",
    "lt196": "Blog über alles",
    "lt197": "Einkaufen, Reisen, Küche, Mamas Alltag und Dolcevita",
    "lt198": "Tags",
    "lt199": "Zecken",
    "lt200": "Wie man nicht krank wird",
    "lt201": "Klinistil",
    "lt202": "Parasiten",
    "lt203": "Wie werden Parasiten behandelt",
    "lt204": "Wie kann man Zecken ziehen",
    "lt205": "Was ist die Gefahr von Parasiten",
    "lt206": "Hirnparasiten",
    "lt207": "Darmparasiten",
    "lt208": "subkutane Parasiten",
    "lt209": "subkutane Darmparasiten",
    "lt210": "Ferienhaus",
    "lt211": "Gefahren am Ferienhaus",
    "lt212": "Was zu tun ist, um eine Zecke nicht zu erwischen",
    "lt213": " Wie man sich vor Parasiten und Zecken schützt",
    "lt214": "Leben im Dorf",
    "lt215": "Sommer am Ferienhaus",
    "lt216": "Heilmittel gegen Parasiten",
    "lt217": "Klinistil gegen Parasiten",
    "lt218": "Klinistil gegen Zecken",
    "lt219": "Womit wird die Infektion behandelt",
    "lt220": "Würmer",
    "lt221": "Überlebenstechniken",
    "lt222": "Ärzte",
    "lt223": "Krankenhäuser",
    "lt224": "Tropfer",
    "lt225": "Sehen Sie sich meine Tags an",
    "lt226": "Page Summary",
    "lt227": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"poliva\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>poliva</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+17]</a>",
    "lt228": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"livejournal\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"{url}\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>livejournal</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+0]</a>",
    "lt229": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"dolbotema\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>dolbotema</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+11]</a>",
    "lt230": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"lulily\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>lulily</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+29]</a>",
    "lt231": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"wendeline_fog\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>wendeline_fog</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+0]</a>",
    "lt232": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"yutecs\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>yutecs</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+2]</a>",
    "lt233": "<span class=\"ljuser i-ljuser i-ljuser-type-I\" data-ljuser=\"ext_279186\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/facebook-16.png?v=29916?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>Eugene Katyukhin</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+9]</a>",
    "lt234": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"suters\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>suters</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+2]</a>",
    "lt235": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"living_for_free\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>living_for_free</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+2]</a>",
    "lt236": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"oldtimer_lj\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>oldtimer_lj</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+9]</a>",
    "lt237": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"sergeeva777\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>sergeeva777</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+14]</a>",
    "lt238": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"gonchar1\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>gonchar1</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+6]</a>",
    "lt239": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"hazar_99\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>hazar_99</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+3]</a>",
    "lt240": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"prazskijpoet\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>prazskijpoet</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+3]</a>",
    "lt241": "<span class=\"ljuser i-ljuser i-ljuser-type-P\" data-ljuser=\"altedo\"><a class=\"i-ljuser-profile\" href=\"{url}\"><img class=\"i-ljuser-userhead\" src=\"./src/userinfo_v8.svg?v=17080?v=316\"></a><a class=\"i-ljuser-username\" href=\"{url}\"><b>altedo</b></a></span>:<a href=\"{url}\"><i class=\"nosubject\">(no subject)</i></a><a href=\"{url}\">[+1]</a>",
    "lt242": "Powered by<a href=\"{url}\">LiveJournal.com</a>",
    "lt243": "Beitrag wurde bewertet",
    "lt244": "<!---->LJ Magazine<!---->",
    "lt245": "Sind Sie sicher, dass Sie diesen Repost löschen möchten?",
    "lt246": "Ja",
    "lt247": "Nein",
    "lt248": "Zu Rückblicken hinzufügen",
    "lt249": "Die Datenschutzeinstellung auswählen",
    "lt250": "Die Datenschutzeinstellung editieren",
    "lt251": "Öffentlich",
    "lt252": "Nur Freunde",
    "lt253": "Privat",
    "lt254": "Entfernen",
    "lt255": "Vollausstattung"
};
function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
}
;
//WIE HABE ICH DEN FUSSPILZ IN NUR EINEM MONAT BESIEGT!
//Name
//Telefonnummer
