var new_lang = {

    "lt0": "Deutsch",
    "lt1": "Newsletters",
    "lt2": "Europa",
    "lt3": "Welt",
    "lt4": "Business",
    "lt5": "Sport",
    "lt6": "Kultur",
    "lt7": "Leben",
    "lt8": "Sci-tech",
    "lt9": "Reisen",
    "lt10": "Video",
    "lt11": "Kultur",
    "lt12": "Sci-tech",
    "lt13": "Leben",
    "lt14": "Sport",
    "lt15": "Programme",
    "lt16": "Live",
    "lt17": "Startseite",
    "lt18": "&gt;",
    "lt19": "Lebensstil",
    "lt20": "&gt;",
    "lt21": "Reisen",
    "lt22": "&gt;",
    "lt23": "Junge Wissenschaftler haben ein Stipendium in Höhe von 1 Million Dollar für eine einzigartige Erfindung im Bereich der Diätetik und Nutriziologie erhalten!",
    "lt24": "Junge Wissenschaftler haben ein Stipendium in Höhe von 1 Million Dollar für eine einzigartige Erfindung auf dem Gebiet der Diätetik und Nutriziologie erhalten! Jetzt kann Fettleibigkeit ohne Diät und Training behandelt werden!",
    "lt25": "<span class=\"c-article-spotim__count spot-im-replies-count\"></span>Kommentare",
    "lt26": "<span class=\"c-article-date__bullet\">&nbsp;&nbsp;•&nbsp;&nbsp;</span><span class=\"c-article-date__last-updated-label\">Letzte Updates:</span>&nbsp;<script>document.write(date(-1))</script>06/10/2020-&nbsp;11:36",
    "lt27": "Diesen Artikel teilen",
    "lt28": "teilen",
    "lt29": "teilen",
    "lt30": "Tweet",
    "lt31": "Mehr",
    "lt32": "Ausblenden",
    "lt33": "Textgröße",
    "lt34": "Aa",
    "lt35": "Aa",
    "lt36": "Eine echte Revolution in der Behandlung von Fettleibigkeit hat stattgefunden! Dank eines Teams von Jungen talentierten Ernährungswissenschaftlern der Huntington University of Health Sciences wurde eine aktive Formel entwickelt, die Millionen von Menschen helfen wird, mit dem Problem der Fettleibigkeit fertig zu werden. Diese Studie wurde zu einer weltweiten Sensation und ein Team von Dr. Stefany Marill führte erhielt ein Stipendium, um die Produktion des Medikaments zu starten. Investoren aus den USA waren ebenfalls an der Entwicklung interessiert und das Produkt wurde kürzlich unter dem Markennamen<b><b><a href=\"{url}\">Reduslim</a></b></b>auf den Markt gebracht. .",
    "lt37": "Das Team von Stefany Marill beantwortete die Fragen, es wirklich viele von denen gab.",
    "lt38": "- Was ist die Einzigartigkeit Ihrer Droge?",
    "lt39": "- Die Einzigartigkeit des Mittels liegt in einer speziellen Formel, die von unseren Wissenschaftlern entwickelt wurde.<b>Aufgrund der einzigartigen Zusammensetzung verlieren unsere Patienten 12 bis 16 kg in einem Monat ohne Diät und Training.</b>Aber das wichtigste ist, dass wir ein Medikament absolut sicher für die Gesundheit schaffen wollten, also verwendeten wir nur natürliche Komponenten. Für uns war es wichtig, dass Menschen jeden Alters, mit unterschiedlichem Grad an Fettleibigkeit und Begleiterkrankungen, das Übergewicht loswerden konnten.",
    "lt40": "- Erzählen Sie mir bitte ausführlicher über die Zusammensetzung von<b><a href=\"{url}\">Reduslim</a></b>und wieso ereignet sich die schnelle Gewichtsabnahme?",
    "lt41": "- Eine solche schnelle Gewichtsabnahme kann nur mit der Ganzheitsbetrachtung sein. Die aktive Formel des Medikaments wirkt in mehreren Richtungen: es ist die direkte Fettverbrennung, Beschleunigung der Stoffwechselprozesse im Organismus und die Sperrung der mit der Nahrung verbrauchten Kalorien. Darüber hinaus enthält die Zusammensetzung nützliche Ergänzungen und Vitamine, die die Vitalität erhöhen und überschüssige Flüssigkeit und Giftstoffe aus dem Organismus entfernen.",
    "lt42": "- Das heißt, wenn wir richtig verstanden haben,<b><a href=\"{url}\">Reduslim</a></b>verbrennt Fett und  die Kalorien davon abhält, aufgenommen werden? Wie das funktioniert?",
    "lt43": "- Ja, Sie haben Recht. Das Medikament verhindert die Aufnahme von Fetten und Kalorien. Wenn sie in den Magen-Darm-Trakt gelangen, lösen sich die Kapseln auf und erzeugen einen dünnen Film, der verhindert, dass das Fett absorbiert wird und es natürlich aus dem Körper ausgeschieden wird.<b>Durch die Beschleunigung des Stoffwechsels werden Kalorien sogar im Ruhezustand schneller verbrannt und Fett wird nicht abgelegt.</b>",
    "lt44": "Natürliche Extrakte helfen, Giftstoffe und Schlacken zu entfernen, und unsere Patienten spüren schon nach ein paar Tagen eine beispiellose Leichtigkeit und einen Ansturm von Kraft. Leider ist der Organismus von übergewichtigen Menschen stark verschlackt und um Stoffwechselprozessen zu starten, muss man ihn zuerst reinigen, was<b><a href=\"{url}\">Reduslim</a></b>perfekt bewältigt.",
    "lt45": "- Werden Sie uns das Geheimnis der Zusammensetzung dieses einzigartigen Mittels offenbaren?",
    "lt46": "- Grundlegende Komponenten von<b><a href=\"{url}\">Reduslim</a></b>sind allen Ernährungswissenschaftler bekannt. Dies sind:",
    "lt47": " Dehydriertes Koffein, das \"weißes Fett\" in braune Lipide umwandelt. Der Organismus verbrennt sie selbstständig und verzögert den Vorrat nicht.",
    "lt48": "Schwarzer Pfeffer - Extrakt fördert den Stoffwechsel, verbrennt Fettreserven, einschließlich des gefährlichen viszeralen Fettes.",
    "lt49": "Cayennepfeffer - Extrakt ist der stärkste Aktivator der Fettverbrennung und fördert die Wiederherstellung des Fettstoffwechsels.",
    "lt50": "L - Carnitin beschleunigt die Verarbeitung von Kalorien, hilft dem Körper, die Nährstoffe schnell zu verarbeiten, aktiviert die Produktion von Hormonen der Freude, was die Fröhlichkeit und gute Laune fördert.",
    "lt51": "Grüner Tee - Extrakt tonisiert den Organismus, entfernt Giftstoffe und Schlacken, kontrolliert den Appetit, verhindert Überessen.",
    "lt52": "Dies sind die Hauptbestandteile und wie Sie sehen können, sind Sie absolut natürlich, wir haben versucht, Chemie zu vermeiden und die Zusammensetzung so sicher wie möglich zu machen.",
    "lt53": "- Es ist einfach erstaunlich! Sicherheit für die Gesundheit ist ein wichtiges Kriterium für die Wahl eines Schlankheitsmittels. Erzählen Sie uns, wie Patienten sich fühlen, wie Gewichtsreduktion auftritt, was sie selbst sagen?",
    "lt54": "Daniela und Mark",
    "lt55": "- 100 % unserer Patienten, die<b><a href=\"{url}\">Reduslim</a></b>einnehmen, waren zufrieden. Die Abnahme des Körpergewichts Betrug im Durchschnitt 12-18 kg pro Monat, abhängig vom Grad der Fettleibigkeit. Je größer das Körpergewicht, desto schneller ist die Gewichtsabnahme. Dabei fühlten sie sich wunderbar, waren munter und aktiv, da sie sich nicht auf Diät setzen, sich auf Ernährung beschränken oder im Fitnessstudio trainieren mussten. Sie sehen, dass einige für die Kursaufnahme mehr als 50% des Körpergewichts verloren haben und es ist bemerkenswert, wir sind sehr glücklich für jeden unserer Patienten! Daniela und Mark nahmen etwa 8 Monaten unter unserer Aufsicht ab. Das Ergebnis können Sie selbst bewerten.",
    "lt56": "- Oft klagen Menschen über mangelnde Motivation, vorschützen die Vererbung und glauben, dass Gewicht kann man nur durch Fasten und schwere körperliche Anstrengung verlieren. Und jetzt widerlegen Sie es und sagen, dass jeder leicht und schnell ohne jede Anstrengung abnehmen kann?",
    "lt57": "- Nein, wir widerlegen nicht, dass Gewicht durch Diäten und Training reduziert werden kann. Aber es braucht viel mehr Zeit. Und um eine Diät zu halten oder ständig ins Fitnessstudio zu gehen, hat nicht jeder genug Motivation. Deshalb haben wir eine Droge erfunden, die allen hilft, unabhängig von körperlicher Form, Disziplin und anderen Eigenschaften. Sie müssen einfach eine Kapsel einnehmen und ihre Angelegenheiten kümmern, und das war's! Regina, zum Beispiel, ist körperliche Aktivität völlig kontraindiziert, aber wie Sie sehen können, hat es nicht verhindert, dass sie in Form kommt.",
    "lt58": "Regina Hühn",
    "lt59": "- Wenn das, was Sie sagen, wahr ist, dann ist es wirklich erstaunlich und wird vielen Menschen helfen. Bitte teilen Sie uns mit, wem<b><a href=\"{url}\">Reduslim</a></b>bereits geholfen hat. Wie fühlen Sie sich, sind die Kilos nicht wieder da?",
    "lt60": "- Nein, Kilos werden nicht zurückkommen, wir haben auch darüber nachgedacht, als wir unser Produkt kreierten.",
    "lt61": "<span>Erstens,</span>Reduslim kontrolliert perfekt den Appetit und reduziert das Verlangen nach süßem-das haben 98% unserer Patienten festgestellt. Eine Person will nicht viel essen, er gewöhnt sich daran, kleine Portionen zu essen und nach der Abschaffung des Mittels hat er bereits die Gewohnheit entwickelt, fraktioniert zu essen.",
    "lt62": "<span>Zweitens,</span>wird der Stoffwechsel verbessert und der Kalorienverbrauch erhöht. Was früher auf die Seiten und den Bauch gelegt wurde, verbrennt jetzt im Körper.",
    "lt63": "<span>Drittens</span>während der Einnahme von Kapseln bemerken unsere Patienten Lebhaftigkeit und Aktivität, die zur Gewohnheit wird und nach dem Abnehmen viele weiterhin einen aktiven Lebensstil führen, Sport treiben und so weiter. Und wenn das Gewicht nach oben gegangen ist (aber praktisch hatten wir es noch nicht), jeder weiß, dass er jederzeit die Einnahme wieder beginnen und die zusätzlichen Kilos verlieren kann.",
    "lt64": "- Und die Letzte, vielleicht die wichtigste Frage, die alle, die schnell und sicher von Übergewicht loswerden wollen haben- wie kann man Ihre wunderbare Droge kaufen?",
    "lt65": "- Wir verkaufen unser Produkt über die offizielle Website. Und wir möchten unseren zukünftigen Kunden ein Geschenk machen! Während des Angebots können Sie<b><a href=\"{url}\">Reduslim</a></b>zum Sonderpreis bestellen! Beeilen Sie sich, die Anzahl der Waren zum Angebot ist begrenzt!",
    "lt66": "Zur offizielle Webseite gehen",
    "lt67": "Kommentare:",
    "lt68": "Hanna",
    "lt69": "Ich habe von<b><a href=\"{url}\"> Reduslim </a></b> zufällig erfahren, aber dieser Tag hat mein Leben verändert! Eines Tages kehrte ich von der Arbeit frustriert zurück, ich trug eine Jeans 58 Größe und einen Kapuzenpullover.Und dann habe ich zufällig meine Freundin gesehen, die wir uns seit 20 Jahren nicht mehr getroffen haben.Sie sah toll aus! Schlank, stilvoll, und ich habe nicht einmal sofort erkannt.Ja, ich war noch nie dünn, aber in letzter Zeit, nach der Scheidung, habe ich noch zugenommen.Wir unterhielten uns und sie erzählte, dass sie nach der Geburt stark abgenommen hatte und dabei < b > <a href=\"{url}\">Reduslim</a> < /b>half. Ich kam nach Hause, fand es im Internet und bestellte zum Angebot mit einem großen Rabatt. Nach drei Monaten trage ich 6 Größen kleiner und sehe gut aus! Ich bin sehr dankbar für dieses Treffen und ein wunderbares Mittel!<img alt=\"\" class=\"comment-img\" src=\"src/img / comment_img1.jpg\">",
    "lt70": "Mila",
    "lt71": "Ich war seit meiner Kindheit dick, und die Schuld daran ist die Scheidung meiner Eltern. Ich hatte Frustessen wie Fast Food, ich trank literweise süße Limonade und wog am Ende der Schule mehr als 90 kg und war dabei 162 cm groß. Viele Male habe ich auf Diäten gesessen, aber ich habe nichts bekommen. In der Oberschule hatte ich sogar Bulimie bekommen, konnte bis zu Magenschmerzen essen und dann Erbrechen provozieren. Ich habe es alleine geschafft, aber ich konnte nicht mit dem Gewicht umgehen. Ich habe vor einigen Monaten von<b><a href=\"{url}\">Reduslim</a></b>erfahren. Ich hörte von ihm aus dem Programm im Fernsehen, dann fand ich die offizielle Website im Internet und bestellte eine Packung zu versuchen. Für einen Monat habe ich 11 kg verloren! Dieses Ergebnis hat mich natürlich inspiriert, und ich habe noch bestellt. Im Allgemeinen habe ich 30 kg abgenommen ohne Sport zu treiben und auf Diäten zu sitzen. Ich habe Fast Food und Süßes eingeschränkt, nur weil es der Gesundheit schadet, nicht weil es unmöglich ist. Ich mag mich jetzt, ich habe endlich einen Freund! Ich bin glücklich!",
    "lt72": "Maria",
    "lt73": "Ausgezeichnetes Mittel! Es hat mir geholfen, 20 kg in drei Monaten ohne Sport und Hungern zu verlieren! Ich bin sehr zufrieden.",
    "lt74": "Max",
    "lt75": "Ich beschloss, mein Gewicht ernst zu nehmen, als der Arzt mir eine schwere Diagnose stellte und sagte, wenn ich nicht abnehmen würde, könnte ich jeden Moment sterben. Aber Diäten haben mir nicht geholfen, ich scheiterte immer wieder und aß übermäßig. Ich bin es gewohnt, so zu leben - Bier, Chips, Wandern mit Freunden in die Bar. Mein Gewicht war 90 kg vor zwei Jahren, und als ich von einem Arzt gewogen wurde - bereits 134. Dann habe ich gemerkt, dass ich das alleine nicht schaffen kann. In einem der Foren habe ich von<b><a href=\"{url}\">Reduslim</a></b>erfahren. Es gab gute Kritiken über ihn und ich glaubte nicht wirklich, dass er mir helfen würde, aber immer noch beschlossen, es zu versuchen. Ich einfach nahm die Kapseln ein und lebte ein normales Leben. Eine Woche später fiel die Hose herunter und als ich auf die Waage kam, stellte ich fest, dass ich 7 kg abgenommen hatte! Weiterhin nahm ich<b><a href=\"{url}\">Reduslim</a></b>ein und habe 45 kg verloren, ich rate allen, dieses Mittel zu gebrauchen!<img alt=\"\" class=\"comment-img\" src=\"src/img/comment_img2.jpg\"><!-- Foto von Verpackung -->",
    "lt76": "Olivia",
    "lt77": "Ich schließe mich dem positiven Feedback zu diesem Mittel an! Ich erfuhr von ihm vom Arzt, als ich wieder mit einer Essstörung zu ihm kam. Ich konnte nicht mit mir selbst umgehen und nicht einmal eine Woche Diät aushalten. Und dann erzählte er mir über<b><a href=\"{url}\">Reduslim</a></b>. Ich hatte zunächst nicht gehofft, dass es mir helfen würde, aber in einem Monat habe ich 12 kg abgenommen und ich bin sehr glücklich!",
    "lt78": "Lucia",
    "lt79": "Nach meiner Erfahrung bin ich überzeugt, dass das Mittel funktioniert! Aber das schönste ist, dass Sie sich nicht verhungern oder im Fitnessstudio üben müssen. Ich hasse Sport und deshalb sind wunderbare Kapseln meine Rettung! Ich habe bereits 15 kg abgenommen und setze fort, Gewicht zu verlieren!",
    "lt80": "Amanda",
    "lt81": "Ich wurde in der Schule immer ausgelacht, ich hatte keine Freunde. Und mein Übergewicht ist daran Schuld. Und jetzt habe ich beschlossen, dieses Problem endgültig zu lösen. Meine Mutter erzählte mir von diesen Kapseln und wir beschlossen, es zu versuchen, weil sie natürlich sind, was bedeutet, dass sie der Gesundheit nicht schaden. Dank der Kapseln<b><a href=\"{url}\" >Reduslim</a></b>habe ich in sechs Monaten 54 kg abgenommen! Ich habe jetzt ein aktives, geschäftiges Leben, viele Freunde und einen geliebten Menschen! Dein Aussehen hat eine große Bedeutung im Leben, es ist wahr. Und du hast die Wahl, entweder zu leiden oder das Schicksal selbst in die Hand zu nehmen. Wähle!<img alt=\"\" class=\"comment-img\" src=\"src/img/comment_img3.jpg\">",
    "lt82": "Eva",
    "lt83": "Ich glaube nicht, dass Kapseln helfen, es gibt nichts besseres als Sport und Ernährung! Nur einigen fehlt die Willenskraft",
    "lt84": "Sofia",
    "lt85": "<b>Eva,</b>du bist einfach nicht mit Stoffwechselstörungen konfrontiert, wenn du einen Monat auf Diät bist, und das Ergebnis ist nur -2 kg! Oder du trainierst jeden Tag, und die Waage zeigt + kg. Dann machst du schlapp. Ich hatte genau diese Situation, und die Kapseln<b><a href=\"{url}\">Reduslim</a></b>wurden zu einer Rettung für mich. Das Gewicht begann zusehends abzufallen, und nach zwei Wochen musste ich meine Garderobe komplett erneuern, da die alten Sachen sehr groß waren. Sei nicht so kategorisch, jeder hat unterschiedliche Situation! Und mein Ergebnis kannst du auf dem Foto sehen!<img alt=\"\" class=\"comment-img\" src=\"src/img/comment_img4.jpg\">",
    "lt86": "Emma",
    "lt87": "Ich mochte das Mittel auch sehr! Mit seiner Hilfe habe ich 10 kg pro Monat abgenommen. Es war eine schwere Scheidung, ich hatte Frustessen betrieben und hier ist das Ergebnis-ich habe 20 kg gewonnen! Dann habe ich zufällig den Ex mit der neuen Freundin gesehen. Sie war schlank, schön und ich wollte auch abnehmen! Aber ich konnte nur eine Woche aushalten, und dann kamen diese zwei Kilo sofort zurück, sobald ich zur normalen Ernährung zurückkehrte. Aber dann habe ich zufällig von einem Kollegen über<b><a href=\"{url}\">Reduslim</a></b>erfahren - Sie hat mit seiner Hilfe nach der Geburt abgenommen und hat mir geraten. Zuerst glaubte ich nicht, aber eine Woche später, mit dem üblichen Rhythmus des Lebens und der üblichen Ernährung, habe ich 4 kg verloren! Und 12 in einem Monat . Ich werde weiterhin abnehmen und werde bald mein Ziel erreichen! Vielen Dank an die wunderbaren Wissenschaftler, die es geschaffen haben!",
    "lt88": "Paulina",
    "lt89": "Ich bestätige, dass ist eine wunderbare Droge, die mir ein neues Leben geschenkt hat! Sie verlieren Gewicht ohne Müdigkeit, Schläfrigkeit, und wollen kein schädliches Essen!",
    "lt90": "Viktoria",
    "lt91": "Ich möchte den Schöpfern dieses wunderbaren Mittels bedanken! Ich konnte selbst abnehmen, riet es meiner Schwester und Mutter. Wir sind alle zufrieden! Am meisten habe ich abgenommen - 22 kg für 2,5 Monate - ein tolles Ergebnis, ich habe mich völlig verändert und fühle mich großartig! Bestellen Sie nur auf der<b>< a href=\"{url}\">offiziellen Website</a></b>, da es Fälschungen gibt!",
    "lt92": "ZUR OFFIZIELLE WEBSEITE GEHEN",
    "lt93": "Mehr zum Thema",
    "lt94": "Porno",
    "lt95": "Sex",
    "lt96": "Covid-19",
    "lt97": "Erektion",
    "lt98": "VIP Porno",
    "lt99": "Hot Topic",
    "lt100": "Mehr erfahren:",
    "lt101": "Covid-19",
    "lt102": "Hot Topic",
    "lt103": "Mehr erfahren:",
    "lt104": "Covid-19",
    "lt105": "<svg viewBox=\"0 0 37.32 37.32\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M40.29,8S28.56,6.25,25.38,6.25v0a1.55,1.55,0,0,0-.77.1L5.14,25.82a1.54,1.54,0,0,0,0,2.16L20.28,43.12a1.51,1.51,0,0,0,1.08.45,1.5,1.5,0,0,0,1.08-.45L41.91,23.66C42.51,23.06,40.29,8,40.29,8ZM21.36,38.55,9.72,26.9,26.33,10.29c2.26.15,6.71.71,10.42,1.22.58,4.15,1.09,8.37,1.23,10.42Z\" fill=\"#002e44\" transform=\"translate(-4.7 -6.25)\"></path><circle cx=\"27.3\" cy=\"9.75\" fill=\"#002e44\" r=\"2.5\"></circle></svg>In heutigen Tags suchen",
    "lt106": "Porno",
    "lt107": "Sex",
    "lt108": "Berlin",
    "lt109": "Potenz",
    "lt110": "Deutschland",
    "lt111": "Covid-19",
    "lt112": "Filme",
    "lt113": "VIP Porno",
    "lt114": "Geschichten",
    "lt115": "Europa",
    "lt116": "Welt",
    "lt117": "Business",
    "lt118": "Sport",
    "lt119": "Kultur",
    "lt120": "Sci-tech",
    "lt121": "Reisen",
    "lt122": "Video",
    "lt123": "Programme",
    "lt124": "Dienste",
    "lt125": "Live",
    "lt126": "Nachrichten",
    "lt127": "Wetter",
    "lt128": "Feed RSS",
    "lt129": "Folgen Sie uns",
    "lt130": "Widgets &amp; Services",
    "lt131": "Africanews",
    "lt132": "Reservieren",
    "lt133": "Corporate",
    "lt134": "Über \"Euronews\"",
    "lt135": "Zusammenarbeit mit EU",
    "lt136": "Nutzungsvereinbarungen",
    "lt137": "Cookie-Richtlinie",
    "lt138": "Kontakte",
    "lt139": "Verteilung",
    "lt140": "Werbung",
    "lt141": "Jobs",
    "lt142": "Folgen Sie uns",
    "lt143": "Copyright © euronews<script type=\"text/javascript\">var d = new Date(new Date().getTime() - 24 * 60 * 60 * 000);var year = d.getFullYear();document.write(year);</script>2020",
    "lt144": "-",
    "lt145": "Deutsch"
};
function Translater() {
    for (class_name in new_lang) {
        var elements = document.getElementsByClassName(class_name);
        if (elements.length) {
            for (key in elements) {
                elements[key].innerHTML = new_lang[class_name];
            }
        }
    }
}
;

