var new_lang =   {
lt0: "Comment j'ai perdu 34 kg",
lt1: "Publié<span class=\"rstart\"> le 29 juillet 2017</span>, 19:51 | Auteur: <a href=\"\" style=\"cursor: pointer;\" target=\"_top\">Monique</a>",
lt2: "Salut, c'est à nouveau Monique. Je veux partager avec vous ma petite victoire sur les complexes et le surpoids. Mon histoire de la maladie, le divorce avec son mari bien-aimé, et le succès de surmonter ces difficultés.",
lt3: "Je veux commencer par le fait qu'après l’avortement j'étais si stressée, et dans le contexte de stress, j'ai eu un échec et la dépression a évolué. Jusqu'à ce que j'étais en dépression, j'avais mangé 2 fois supérieur à la norme. Comme je suis sujette à la plénitude, j’ai commencé a <span class=\"bold\"> prendre de poids immédiatement. Le bilan est triste - 92 kg</span>. D'abord, mon mari est essayé de me soutenir, tentait de sortir de la dépression, mais ensuite, il suffit de moi.",
lt4: "Un jour, mon mari m'a dit qu'il n'a pas besoin d'une telle femme  défectueuse qui ne peut pas porter l'enfant, oui, et aussi <span class=\"bold\">semblable à une grosse vache</span>. Vous ne pouez pas imaginer comment cela a été pour moi: la personne aimée m'a humilié, et puis il a demandé le divorce.",
lt5: "Je voulais déjà même de rendre la pareille à la vie parce que la vie sans la personne aimée et des enfants, je ne l'imaginais. Ma copine m’a emmené chez le  médecin à peine , et celui-là m'a conseillé de perdre du poids, afin de normaliser les hormones et porter un bébé en bonne santé...",
lt6: "Le temps est venu de prendre vous-même!",
lt7: "Les mots de mon ex-mari de sa propre infériorité m'ont donné du repos, et debout une fois devant le miroir, j’avais peur de mon corps obèse, j'ai décidé qu'il est nécessaire de me changer et de devenir idéal.",
lt8: "Voici, j'ai commencé la transformation de mon propre corps: j’ai essayé toutes sortes d'exercices de yoga pour maigrir, pilules, 25 images, la crème anti-cellulite durs, des massages etc.<span class=\"bold\">TOUT CELA NE FONCTIONNE PAS DU TOUT</span>. N'aide pas. Inutile.",
lt9: "J'ai même voulu l’accepter. Après tout, mon poids était le même -  à environ 92 kg... J'ai envie de pleurer de mon impuissance.",
lt10: "En général, je n'ai presque abandonné cette idée",
lt11: "Perdre du poids wn un mois, c’est possible?!",
lt12: "Un jour, surfant sur les blogs sur internet, je suis tombée sur un blog où la jeune fille a <span class=\"bold\">perdu miraculeusement chez elle 22 kg en un mois, </span>avec un truc <span class=\"bold\">(OneTwoSlim)</span> Je me suis intéressée bien sûr tout de suite et j’ai examiné tout de manière approfondie.",
lt13: 'D`abord, je n`ai pas cru à cet effet parce que j`ai déjà essayé toutes sortes de pilules, en effet, déjà tellement vanté par la télévision qui n`aide pas... Mais cette jeune fille est assez chère en ligne, quand même elle a montré des photos \"avant/après", et j`ai décidé de faire confiance à son conseil.',
lt14: "En général, j'ai commandé ce complexe (OneTwoSlim), il est venu en quelques jours en contre remboursement par la poste. Tout déballé, j'ai lu les instructions et commencé à l’utiliser activement.",
lt15: "Quel est le résultat?",
lt16: "je l'ai pris le matin et le soir. Honnêtement, j'ai un peu d'enthousiasme l'outil, et je ne croyais pas à son efficacité. Mais peu à peu j'ai commencé à remarquer que les volumes précédents ont commencé à disparaître.",
lt17: "J'ai décidé d'attendre une semaine, et puis....j'ai un peu la mâchoire sur le sol! <span class=\"bold\">LE POIDS A DIMINUÉ DE 6 KILOS!!! 7 jours!</span>Pouvez-vous le croire@@@ Je ne suis pas en croire mes yeux, et encore une fois - _3Cspan class=\"bold\">7 kilo 200 grammes sont disparus</span>, tout est vrai! Je suis pas trompée et je ne suis pas folle! Je ne peux pas décrire ma joie. La dernière fois je suis tellement heureuse probablement il ya 20 ans :)",
lt18: "J'ai continué à prendre ce remède régulièrement pendant 2 mois, et quand j’ai repris  la balance, la prochaine fois, j’ai été tout simplement stupéfaite - -<span class=\"bold\">34 KG EN 2 MOIS!!!</p>J'ai même vérifié plusieurs fois - l'aiguille sur la balance montrait <span class=\"bold\">58 KG!</span>",
lt19: "Au travail, bien sûr, tout le monde a commencé à remarquer que je n'ai brusquement vide le poids, et on a commencé à m'interroger - qu’est-ce qui se passe. Mon collègue très beau et célibataire a commencé à prendre soin de moi, il disait qu'il était toujours jaloux de mon mari",
lt20: "En général, ma vie a changé après cette rapide minceur . Les hommes maintenant me disent<span class=\"bold\"> toujours des compliments</span> de tous les côtés. En fait, c’est très agréable por moi.",
lt21: "Vous savez, je me marie bientôt. Oui-oui, mon beau collègue. Et pas seulement cela, le porte déjà un nouveau bébé :) Grâce à poids perdu, mon corps a surmonté d'un échec, et maintenant je me prépare à devenir un femme et une mère heureuse et une famille unie, où tous les uns des autres apprécient et aiment!",
lt22: "c'est grâce à mon ex-mari, qui m’a insulté et jeté, j'ai surmonté la maladie, la dépression et l'excès de kilos, et <span class=\"bold\"> maintenant, je suis femme la plus heureuse, mince et belle!!!</span>",
lt23: "Je suis très heureuse que tout est arrivé. Simultanément avec le fait de maigrir, j'ai réalisé le problème de beaucoup d'entre nous que la plus simple des choses nous semblent inefficaces. Et plus complexes, par exemple, les opérations - efficaces. Mais ce n'est pas le cas. Perdre beaucoup de poids en aucun moment, vous pouvez naturellement, de manière sûre et rapide, sans régime et l'exercice. Récupérée! Par ailleurs, les fillettes, le poids n'a pas augmenté, le volume est resté le même :)",
lt24: 'Je l’ai commandé sur<a href=\"\" target=\"_top">ce site</a>. C`est la seule <span class=\"bold\">compagnie certifiée</span> en France, qui vend  <span class=\"bold\">OneTwoSlim</span>. En ce qui concerne la livraison, le colis vient <span class=\"bold\">avec le remboursement</span> par courrier. De sorte que <span class=\"bold\">c’est en toute sécurisé</span>, et personne ne saura votre petit secret.',
lt25: "Le prix de<span class=\"bold\">OneTwoSlim</span> est égal à 2 billets de cinéma, ou 1 marche à l'épicerie. Décidez vous - même- beaucoup ou non. Mon opinion est un moyen efficace devrait être vendu à un prix deux fois plus cher!",
lt26: "eh Bien, j'espère que cette information vous a été utile et Vous, enfin, nous retrouverons <span class=\"bold\"> la taille et le poids souhaités en peu de temps!</span> Amusez-Vous!",
lt27: "Commander OneTwoSlim",
lt28: "194 commentaires",
lt29: "Marie",
lt30: "WOW! J'ai tout simplement pas de mots que vous êtes belle! Je vous souhaite du bonheur et de la santé de bébé!",
lt31: "Il y a 5 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt32: "Camille",
lt33: "Bonjour, Monique! Je l'ai aussi apprécié, et j’ai perdu 12 kilos en un mois. Un tel effet sur moi - aucun régime. Donc entièrement je te soutiens et je partage ton enthousiasme!<br><img src=\"review-2.jpg\" style=\"width: 100%;\">",
lt34: "Il y a 7 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt35: "Angélique",
lt36: "d'Accord, Je vous comprends  très bien. Mais un jour le médecin m’a ordonné ce complexe et ma santé est devenue normale - pas plus de l'essoufflement, la transpiration, et d'autres problèmes.<br><img src=\"review-6.jpg\" style=\"width: 500px;\">",
lt37: "Il y a 11 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt38: "Julie",
lt39: "Oh, je sais c'est un outil. Très populaire maintenant. Apparemment, ca marche",
lt40: "Il y a 14 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt41: "Brigitte",
lt42: "salut Tout le monde! J'ai des résultats plus modestes. Mais plusieurs kilos sont partis, je suis contente.",
lt43: "Il y a 16 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt44: "Camille",
lt45: "je suis la deuxième semaine de tout bois. Dans des quantités nettement été emportée, ce qui plaît.",
lt46: "Il y a 17 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt47: "Ahastasia",
lt48: "Cool-cool! Je veux aussi! Où on peut l’acheter?",
lt49: "Il y a 18 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt50: "Sophie",
lt51: "Monique a donné, dans son post, le lien sur le site officiel du fabricant, soyez prudent.",
lt52: "Il y a 20 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt53: "Elene",
lt54: "Cool. J’ai lu sur ce médicament OneTwoSlim il y a quelques jours dans le blog d'unejeune fille, mais alors j’ai pensé que c'est des conneries. Il faut essayer, à la fois en cours d'exécution. Comme quelque chose coûte pas cher.",
lt55: "Il y a 21 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt56: "Mireille",
lt57: "Et j'ai acheté! Jusqu'à ce que trois jours, prends, et sur la balance déjà moins de 1,5 kg!",
lt58: "il y a 23 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt59: "Viola",
lt60: "6 jours plus tard, le colis est venu. Et le plus important - sans acompte, je ne risquais d'argent d'avance. Il ya beaucoup d'escrocs aujourd’hui",
lt61: "il y a 24 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt62: "Annette",
lt63: "Bonjour, les filles! tout simplement  une photo:<br><img src=\"review-3.jpg\" style=\"width: 100%;\">",
lt64: "Il y a 25 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt65: "Ksenia",
lt66: "la Beauté de ce qui a \"nouveau\" silhouette élancée :)",
lt67: "Il y a 34 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt68: "Valérie",
lt69: "Mes résultats - moins de 9 kilos le premier mois, est maintenant le deuxième paquet ouvert, je vais continuer à maigrir. La santé est super, aucun mois n'a pas remarqué. Je mange comme un oiseau))<br><img src=\"review-4.jpg\" style=\"width: 100%;\">",
lt70: "Il y 39 minutes ago |<span class=\"vk-comment-answer\">Commentaire</span>",
lt71: "le Rêve de l'Enfance)",
lt72: "Joue déjà avec ça! À chaque coin de lui écrivent!!!",
lt73: " il y a 41 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt74: "Ksenia",
lt75: "j'ai pas d'écrire quelque chose, si? Maintenant, si vous avez eu des problèmes avec le poids, puis vous perdez quelques tailles trop envie de se vanter :)",
lt76: "Il y a 44 minutes |<span class=\"vk-comment-answer\">Commentaire</span>",
lt77: "La Belle",
lt78: "je m'en fous de qui et de quoi parle, me complexe. Il y a deux ans les joui - perdu 18 kilos. Et l'hiver dernier a été la plus forte de stress, et j'ai de nouveau pris un peu, environ 5 ou 6 kilos. Et encore complexe et moins de 11 kilos!!! 11!!!! En général, je suis très heureux qu'un tel outil est, les filles! Maigrir super rapide, sur les régimes ne sont pas assis, et la peau de la elle est belle, parce que le corps est bien à nettoyer. Comme là, il est à la mode aujourd'hui, à la désintoxication.<br><img src=\"review-5.jpg\" style=\"width: 100%;\">",
lt79: "Il y a 49 minutes|<span class=\"vk-comment-answer\">Commentaire</span>",
lt80: "Commander OneTwoSlim",
lt81: "les Blogueurs en ligne",
lt82: "Et encore 327 sans avatar...",
lt83: "la Bande de postes",
lt84: "Comment j'ai perdu 34 kg",
lt85: "Monique",
lt86: "29.05.2017 - 20:24",
lt87: "194 commentaires",
lt88: "Comment vous trouvez cette photo?",
lt89: "Monique",
lt90: "30.05.2017 - 09:38",
lt91: "18 commentaires",
lt92: "Hmm vraiment. Air France c’est bon..",
lt93: "IMonique",
lt94: "01.06.2017 - 01:23",
lt95: "9 commentaires",
lt96: "Il ne pleut pas a Londres, enfin!",
lt97: "Monique",
lt98: "01.06.2017 - 19:47",
lt99: "64 commentaires",
lt100: "Qui est sur la mer?)",
lt101: "Monique",
lt102: "02.06.2017 - 16:56",
lt103: "33 commentaires",
lt104: "Maman veut le chat, quoi faire?",
lt105: "Monique",
lt106: "03.06.2017 - 16:57",
lt107: "98 commentaires",
lt108: "salut Tout le monde.Je suis t à Paris",
lt109: "Monique",
lt110: "04.06.2017 - 19:55",
lt111: "51 commentaire",
lt112: "Comment j'ai appris le français",
lt113: "Monique",
lt114: "06.06.2017 - 01:57",
lt115: "17 commentaires",
lt116: "le Blog de Monique.<span class=\"ryear\">2017</span>©",
lt117: "le Blog de Monique. Comme j'ai perdu du poids en 1 semaine",
};
function Translater () {
               for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                 for (key in elements) {
                  elements[key].innerHTML = new_lang[class_name];
                 }
              }
            }
          };