var new_lang = {
    lt1: 'Hlavní stránka',
    lt2: 'Blogy',
    lt3: 'Omlazení',
    lt4: 'Komentáře: 15',
    lt5: 'Text:  <a href="" rel="author">Kvapilová</a>',
    lt6: 'Bez botoxu, zaručeně o 15 let méně',
    lt7: '<strong>Zuzana Kamarádová<br>Vítězka soutěže: </strong> «Příběh o tom, jak se stát krásná».',
    lt8: 'Dobrý den milí čtenáři. Chci Vám vyprávět příběh o tom, jak žena může hledat krásu za mořem a nakonec ji najít u sebe doma.',
    lt9: 'Dovolte mi se představit. Jsem Zuzana Kamarádová, je mi 47 let a žiji ve Vigu.',
    lt10: 'A teď k mému příběhu',
    lt11: 'Jednoho rána, jsem se uviděla v zrcadle a propukla v pláč. Hluboké vrásky na čele, obrovské nosoretní rýhy, váčky pod očima, nejednotná pleť, všechno naznačovalo tomu, že přišla podzimní šeď a zima, i když jsem měla ještě takovou chuť si užívat světla a tepla. Z nějakého důvodu jsem si okamžitě vzpomněla na příběh jedné ženy, která si omladila obličej v jedněch lázních v Tunisku. Samozřejmě, tam, v bývalé francouzské kolonii, pracuje řada  francouzských kosmetologů, kteří používají francouzské produkty. Takže nemají Francii co závidět a navíc je vše 2-3 krát levnější. Proto jsou výlety do Tuniska za krásou tak oblíbené po celém světě, dokonce i ve Francii :-)',
    lt12: '«Copak já si nezasloužím být krásná? Pomyslela jsem si a začala se poohlížet po dovolené v Tunisku. A jak je známo, kdo hledá, najde.Už v první cestovní agentuře mi nabídli last minute dovolenou s 50% slevou! Takže už za 2 dny jsem byla ve středisku Hammamet, v největších lázních, Bio Azur. Místní odborníci začali pracovat na mém obličeji a těle. Nebudu Vám vyprávět o tělových kůrách s pomocí řas a bahna, ani o hydromasážních koupelích. Nesouvisí to s příběhem. Povím Vám o obličejových kůrách.',
    lt13: 'Ošetření bylo rozvrženo do 12 dní. Na začátku Vám vyfotí obličej, abyste později mohli ocenit rozdíl. Čekalo mě luxusní křeslo. Posadíte se do něj a poddáte se slasti. Hudba tichoučce hraje, vzduch, který dýcháte příjemně voní, a při tom všem Vám dívky jemnou masáží aplikují příjemně vonící krém. Celé to trvá asi 15-20 minut. A tak po celých 12 dní. Nakonec Vás opět vyfotí. Výsledek můžete vidět samy.', 
    lt14: 'Váčky, vrásky a nosoretní rýhy zmizely! A s nimi i mých 15 let navíc! Byla jsem v šoku a nadšená! Má kosmetoložka, která byla zvyklá na nezměrnou radost svých zákazníků, se na mě příjemně usmála. Zapamatovala jsem si jméno té krémové masky, která byla tak účinná. Jmenuje se <a href="">COLLAMASK</a> !',
    lt15: 'Samozřejmě, že když jsem se vrátila zpět do Viga, tak mé kamarádky a známé byly překvapené. Neustále se mě vyptávaly! Všem jsem říkala pravdu, ale byla jsem smutná, protože mezi vším tím štěstím nad svým novým obličejem, jsem zachytila smutný pohled mé maminky. Okamžitě jsem to celé pochopila. Žena zůstává ženou v každém věku a v každém věku chce být krásná. Nicméně poslat 71 letou ženu do Tuniska byla utopie. Vyptávala jsem se na masku po obchodech, ale nikdo ji neznal...', 
    lt16: 'Ukázalo se, že je také možné objednat si tuto krémovou masku zde',
    lt17: 'Uběhlo půl roku. A najednou, zázrak! Narazila jsem na internetu na ten povědomý název, COLLAMASK! Podle toho, co jsem četla, to vypadalo, že všechno odpovídá. Jen obal byl jiný než ten, který jsem zahlédla v Tunisku. A cena byla také dostupnější. Možná si v Tunisku účtují více za služby? S těmito pochybnostmi jsem si ji objednala. Věděla jsem jak vypadala a jaký účinek maska měla.  Pokud je to <a href="">opravdu COLLAMASK</a>, tak jsem vyhrála na plné čáře!',
    lt18: 'Balíček dorazil za 5 dní. Bez otálení jsem ji mamince aplikovala tak, jak už jsem to uměla. Samozřejmě bez toho křesla, které měla kosmetoložka, bez hudby a bez aromaterapie, ale COLLAMASK i přesto účinkovala. Během 12 dní moje maminka omládla o 15, o rok každý den!',
    lt19: 'Tady vidíte výsledky:',
    lt20: 'Objednala jsem 6 dalších balení, pro maminku a pro jednu kamarádku. Nikdy jsem neviděla nic lepšího k péči o pokožku. Výsledek je velmi rychlý. Výborné!',
    lt21: 'Takový je můj příběh. Doufám, že moje zkušenost bude pro vás užitečná. Protože žena má být krásná v každém věku!',
    lt22: 'COLLAMASK',
    lt23: 'Přejít na stránky COLLAMASK',
    lt24: 'S pozdravem, Zuzana Kamarádová',
    lt25: 'Nechte Váš komentář:',
    lt26: 'Nabídky spolupracovníků',
    lt27: 'Zajímavé metody k omlazení...',
    lt28: 'Hvězda pop music říká, že odejde do kláštera',
    lt29: 'Akce a vitamíny. Kde je pravda?',
    lt30: 'Kakao zlepší vaši paměť',
    lt31: 'Vitamín D zachrání před demencí',
    lt32: 'Všechny komentáře: 15',
    lt33: 'Komentáře',
    lt34: 'K okomentování není potřeba <a href="">se zaregistrovat</a>',
    lt35: 'Iva Polcarová',
    lt36: '71 let? Neuvěřitelné)) I tak si masku objednám. Viděli jste na stránce složení? Je prostě úžasné)))',
    lt37: 'Trina_Paris',
    lt38: 'COLLAMASK je bomba! V posledních 6 měsících si získala velkou oblibu.',
    lt39: 'Anna Šebestová',
    lt40: 'Nemůžu uvěřit tomu, že vynalezli něco tak užitečného! Mám plné zuby vyhazování peněz za neúčinné produkty. Jestli opravdu funguje, určitě si ji objednám.',
    lt41: 'Andrea Zavadilová',
    lt42: 'Souhlasím s vámi! Je to velmi účinný výrobek k omlazení! Malé vrásky beze stopy zmizí.',
    lt43: 'Zuzana Kamarádová',
    lt44: 'díky za fotku! Je to skvělý výsledek! Dámy, prosím, svěřte se s výsledky! Je to strašně zajímavé.',
    lt45: 'Marie Ilčíková',
    lt46: 'Já jsem ji v obchodech neviděla...Bude to asi pravda, že se dá <a href=""><strong>objednat jen na této stránce</strong></a>.',
    lt47: 'Veronica Strel’cova',
    lt48: 'Po 3 použitích moje vrásky úplně zmizely, dokonce i ty nejhlubší. Je to pohádka! Ještě že jsem narazila na Váš blog včas. Díky!',
    lt49: 'Zuzana Kamarádová',
    lt50: 'Jednoduše geniální!) Čirou náhodou jsem objevila tuto masku. Tyhle věci se musí sdílet!',
    lt51: 'Polina Cezareva',
    lt52: 'Úžasná žena! Já ve svých 30 letech vypadám hůř :(( Rozhodnuto, objednám si ji.',
    lt53: 'Jarmila Drbalová',
    lt54: 'Naše elita se na ni teď určitě rychle vrhne. Je potřeba objednat ji dříve, než dojdou zásoby. Nikdy se neví)',
    lt55: 'Lada Rudolfová',
    lt56: 'Dámy, COLLAMASK, nejenže odstraní vrásky, ale i otoky. Předtím jsem mívala strašné kruhy pod očima, a teď úplně zmizely. Radostí nevím co mám dělat.',
    lt57: 'Zuzana Kamarádová',
    lt58: 'Efekt je velmi zřetelný! Výsledek je úžasný! Díky za komentář)))', 
    lt59: 'Olga Tarasova',
    lt60: 'Už jsem o COLLAMASK slyšela, ale nevěděla jsem, kde si ji objednat. Díky za tip!',
    lt61: 'Liza Gladkaya',
    lt62: 'Už jsem si ji objednala! To mám radost, to se těším...',
    lt63: 'Věra Marková',
    lt64: 'Manžel mi ji daroval k narozeninám)) Říkal, abych byla ta nejkrásnější)) A co byste řekli? Je to tak :)',
    lt65: 'Věra Marková',
    lt66: 'Koupila jsem si ji a líbila se mi! Používala jsem masku po dobou 2 měsíců. Je to opravdu maska k omlazení obličeje!! Přikládám výsledek',
    lt67: 'Vyzkoušet Collamask <br>teď hned'
}