var new_lang =   {
"lt00": "Blogul Anei Ionescu. Cum să măriți timpul sexului!",
"lt0": "SEXUL cu soțul meu acum durează până la 2 ore! În loc de 3 minute!!!",
"lt1": "<a href=\"\" style=\"font-weight: normal; text-decoration: none; color: rgb(0, 0, 0); cursor: pointer;\" target=\"_top\">A fost publicat</a><span class=\"startdate\">11.03.2014, 19:51</span>| Autor:<a class=\"yelpay-target\" href=\"\" style=\"cursor: pointer;\" target=\"_top\">ana</a>",
"lt2": "Bună prietenilor! Vă aduceți aminte cum acum un an am plâns că soțul<strong>ejaculează</strong><strong>foarte repede</strong>când avem sex?Chiar dacă numai îi masturbez<strong>ejaculează repede</strong>, după<strong>1-4 minute!</strong>",
"lt3": "Sunt încă îngrijită că penisul lui<strong>ridică rău</strong>și lungimea nu este<strong>mare</strong>. Dar când vezi pornofilme – acolo toți mădularii sunt ca baionete: lungi, tari și elastici.",
"lt4": "Am ascultat sfaturile voastre, soțul a încercat pe toate: de la viagra și alte pastile până la yoga și alte rituale tantrice. Sunt prostii! Sexul cum a fost<strong>1-3 minute</strong>, a și rămas. Penisul cum a fost scurt și leneș - a și rămas!",
"lt5": "Deci m-am resemnat cu asta și<a href=\"\" style=\"font-weight: normal; text-decoration: none; color: rgb(0, 0, 0); cursor: pointer;\" target=\"_top\">am acuzat</a>genetica soțului și<b>sănătatea fizică</b>. Cred că totul se bazează pe nivelul genetic. Am notat că a început să dezvolteze chiar un complex la soțul meu înaintea mea...",
"lt6": "Salvarea a sosit pe neașteptate...",
"lt7": "A trecut vreo o jumătate de an, am văzut un interviu al actorului de pornofilme<b>Pierre Woodman</b>(sigur ați auzit despre el) într-o revistă vestită. A povestit că omul poate face <strong>sex până la 2 ore</strong>, și desigur penisul va fi tare! În plus, există posibilitate<strong>de-a mări penis cu 5 cm</strong>. Este ceea ce ne trebuie – am gândit.",
"lt8": "După cuvintele lui – pentru un sex atât de prelungit omului îi trebuie <b>extrasul  de\"Muira Puama\"</b>. (arborele pe care indienii din America de Sud l-au folosit pentru ridicarea potenței). Când contactează trupul omului întărește producerea hormonilor intime cu sute de ori. Grație acestuia orgasmele vor fi ca la pornoactori. În plus această cremă<strong>mărește penisul într-o săptămână cu 3-5 cm</strong>(după cuvintele lui)!",
"lt9": "Pierre Woodman a recomandat să folosească o cremă specială cu acest extras -<b>\"XX\"</b>. După cuvintele lui, numai în cremă de această firmă se conține extrasul natural de acest arbore, dar alte sunt contrafaceri care nu lucrează și sunt din chimie.",
"lt10": "După citirea articolului m-am dus să comand crema. În România există numai o companie certificată, care vinde această cremă \"XX\" -<a href=\"\" style=\"cursor: pointer;\" target=\"_top\"><b>iată linkul la site-ul lor</b></a>.",
"lt11": "Adică am făcut comandă, coletul a sosit după câteva zile prin poștă cu ramburs. Nu e periculos.",
"lt12": "Care e rezultatul?",
"lt13": "Am pus ambalajul pe de o parte, i-am dat soțului crema și am decis să încerc – care va fi efect.",
"lt14": "Cum trebuie am încercat rezultatul împreună: am avut sex<strong>o oră și 47 de minute</strong>,  și când a venit orgasmul- ......doamne....<b>AM STRIGAT ÎMPREUNĂ DE A AUZIT TOATĂ CASA, PLĂCEREA A FOST COSMICĂ</b>!!!! N-am simțit așa ceva niciodată în viață! Am crezut desigur că va fi un rezultat, dar că va fi<b>ATÂT DE</b>tare – n-am putut<a href=\"\" style=\"font-weight: normal; text-decoration: none; color: rgb(0, 0, 0); cursor: pointer;\" target=\"_top\">chiar</a>imagina.",
"lt15": "Apoi au trecut vreo 2 săptămîni de cînd a început să folosească această cremă și am remarcat că<strong>penisul lui a mărit cu 5 cm</strong>! Atunci am fost șocanți, a fost<strong>un rezultat uimitor</strong>!",
"lt16": "Așa se întâmplă uneori. Niciodată n-aș fi crezut că un extras poate influența așa de tare trupul omenesc. Prețul este ca 2 bilete la cinema. Decideți voi  oare este mult sau nu, luând în considerație că cinema nu este utilă deloc. <b>NU ECONOMISIȚI LA PLĂCERI</b>.",
"lt17": "Adică domnilor, vă sfătuiesc tuturora să încercați acest<a href=\"\" style=\"cursor: pointer;\" target=\"_top\"><b>XX</b></a>! Noroc! Dacă cineva o folosește deja – scrieți referințele voastre.",
"lt18": "Comandă crema!",
"lt19": "194 de comentarii",
"lt20": "Alexandru Cuza",
"lt21": "Păi Ano mulțumesc)) n-am așteptat asemenea articol)) despre temă – acum un an n-am știut despre această cremă. Sunt foarte mulțumit. Orgasmele sunt cosmice!)) Penisul a fost 14 cm, a devenit 18 cm!!<br><img src=\"photo-4.jpg\">",
"lt22": "cu 4 minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt23": "Kostik Ed",
"lt24": "Mulțumesc Anei, ieri am luat coletul de la poștă, totul e ok))",
"lt25": "cu 6 minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt26": "Ivan Priveghetoare",
"lt27": "Fratul meu stă în SUA, și spune cp acolo această cremă este FOARTE vestită...Toții sunt încântați se pare...nu știu",
"lt28": "cu 7 minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt29": "Delia Popescu",
"lt30": "Ana, bună ziua! Impresionează! Te felicit! Acum o să comand soțului).",
"lt31": "cu 9 minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt32": "Ionuț Suciu",
"lt33": "Aplic a doua zi. Să fiu sincer – nu am așteptat ASEMENEA efect. Este INCREDIBIL. Iată foto puiului meu ;)))))))<br><img src=\"review-1.jpg\">",
"lt34": "cu 11 minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt35": "Anastasia Dincu",
"lt36": "Bună Ana! Am comandat două ambalaje – pentru viitor, aștept cu nerăbdare coletul. :)",
"lt37": "cu 12 minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt38": "Vladimir Înger",
"lt39": "E fascinant, Ano! Și eu vreau așa))",
"lt40": "cu 15 minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt41": "Princesa Elena",
"lt42": "Bună, Ana! Am aplicat această cremă în vagină vreo 5 zile. Mișto! Foarte mișto! Am început sp simt orgasme, mai devreme am numai simulat) sfătuiesc tuturora.",
"lt43": "cu 16 minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt44": "Oxana Chira",
"lt45": "Hey! Am comandat soțului și mie. Nu știu ce să spun! Ano, îți mulțumesc! Orgasmele sunt fără descriere!!!!!",
"lt46": "cu 21 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt47": "Stefan Drag",
"lt48": "O folosesc o săptămână, a mărit numai cu un centimetru, dar am deja obosit să curăț covorul de spermă)))",
"lt49": "cu 22 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt50": "Dan Petrescu",
"lt51": "Am cumpărat, mi-a plăcut! În trecut n-am avut destule puteri în pat și orgasmele au fost slabe. Acum totul a schimbat spre bine. Ano – îți mulțumesc)",
"lt52": "cu 25 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt53": "Anton Tor",
"lt54": "Și eu știu despre acest XX, l-am cumpărat în Grecia demult. Lucrează. Vă sfătuiesc.",
"lt55": "cu 34 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt56": "Stelia Ilfov",
"lt57": "Soția mea sunt foarte fericită. Spune păi ce s-a întâmplat cu tine? Sexul acum e de 5 ore și mădularul a mărit cu 3 cm)))",
"lt58": "cu 39 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt59": "Paul Manole",
"lt60": "De asemenea am uzat asta cremă. Lucrează. Am comandat de pe același site, cu ramburs, coletul a sosit în 6 zile. Descarc fotografia prietenei, a avut un orgasm vaginal))<br><img src=\"review-2.jpg\">",
"lt61": "cu 41 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt62": "Vlad Maior",
"lt63": "Felicități-mă, aam devenit un cumpărător fericit al acestui lucru!",
"lt64": "cu 44 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt65": "Petru Ian",
"lt66": "Flăcăilor, sper că veți obține asemenea fericire ca și mine. Orgasmele au devenit mai tari nu cu 10, ci cu 100 de ori! Penisul a mărit cu 5 cm, sunt șocat. Ana mulțumesc pentru articol!",
"lt67": "cu 49 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt68": "Flora Motanu",
"lt69": "Și eu știu despre această cremă. Soțul e totdeauna cu el, ejaculează ca un taur...m-a obosit deja...",
"lt70": "cu 50 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt71": "Eugeniu Băieșu",
"lt72": "hello, crema e super, pur și simplu – aplică, curăță - și ejaculează cât vrei. Dar ca să obțineți mărime, mai bine să nu curățați 10 minute!",
"lt73": "cu 51 de minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt74": "Dan Romanof",
"lt75": "Bună. Soția a cumpărat această crema, am înjurat-o desigur, că a cumpărat o prostie din publicitate... dar după 2 săpămîni am avut nevoie să cer scuze și să cumpăr încă una))",
"lt76": "cu o oră minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt77": "Bărbatul Cool",
"lt78": "Nu e o noutate. Toții știu despre asta cremă. Cei care nu știu nu vreau să întărească simțăminte. XX lucrează real. Recomand.",
"lt79": "cu o oră minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt80": "Соня Максимова",
"lt81": "Ceea ce îmi trebuie!Apropo am citit demult acest articol dar n-am adus în atenție… acum bărbatul face ceva foaaaarte interesant)))",
"lt82": "cu două ore minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt83": "Ion Iliescu",
"lt84": "La vest toată lumea folosește această cremă demult. Și toate studiile de pornografie o folosesc de asemenea. Până la noi totul vine prea tarziu...",
"lt85": "cu două ore minute în urmă |<span class=\"vk-comment-answer\">Comentați</span>",
"lt86": "Bloggeri online",
"lt87": "Și încă 279 fără foto...",
"lt88": "Blogul Anei Ionescu.<span class=\"nowyear\">2017</span>©",
};
function Translater () {
               for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                 for (key in elements) {
                  elements[key].innerHTML = new_lang[class_name];
                 }
              }
            }
          };