var new_lang = {
    lt1: 'Alcobarrier – un nou produs eficient pentru combaterea dependenței de alcool',
    lt2: 'Alcobarrier - <br><span>Скажи <span>&laquo;Nu&raquo;</span> alcoolismului</span>',
    lt3: 'preț vechi',
    lt4: 'A comanda cu',
    lt5: 'Alcobarrier – un nou produs eficient pentru combaterea dependenței de alcool',
    lt6: 'Reduce pofta de alcool',
    lt7: 'Calmează sistemul nervos',
    lt8: 'Îmbunătățește starea psihică',
    lt9: 'Are un efect benefic asupra ficatului',
    lt10: 'Elimină toxinele din organism',
    lt11: 'Alcobarrier – un produs eficient, care elimină toxinele din organism și reduce pofta de alcool. Acidul succinic și fibregam (fibregum) din compoziția prosului Alcobarrier elimină toxinele din organism după consumul de băuturi alcoolice și au un efect de restaurare asupra organismului.',
    lt12: 'Alcobarrier <br> <span>complex de componente extrem de active</span>',
    lt13: '<span>Va elimina <br> toxinele</span>',
    lt14: 'Fibregam',
    lt15: 'smoala de acacia contribuie la eliminarea toxinelor și normalizarea tractului gastro-intestinal',
    lt16: 'Va reduce <br> pofta',
    lt17: 'Extractul de anghinare',
    lt18: 'reduce pofta de alcool, are un efect hepatoprotector și de detoxifiere',
    lt19: 'Va calma <br> nervii',
    lt20: 'Extractul de Talpa Gâștei (Leonurus cardiaca)',
    lt21: 'calmează sistemul nervos, ajută la ameliorarea intoxicației cu alcool',
    lt22: 'Alcobarrier <br> <span>complex de componente extrem de active',
    lt23: 'Va elimina <br> toxinele',
    lt24: 'Fibregam',
    lt25: 'smoala de acacia contribuie la eliminarea toxinelor și normalizarea tractului gastro-intestinal',
    lt26: 'Va reduce <br> pofta',
    lt27: 'Extractul de anghinare',
    lt28: 'reduce pofta de alcool, are un efect hepatoprotector și de detoxifiere',
    lt29: 'Va calma <br> nervii',
    lt30: 'Extractul de Talpa Gâștei (Leonurus cardiaca)',
    lt31: 'calmează sistemul nervos, ajută la ameliorarea intoxicației cu alcool',
    lt32: 'Alcobarrier <br> <span>complex de componente extrem de active</span>',
    lt33: 'Va elimina <br> toxinele',
    lt34: 'L-CARTININĂ',
    lt35: 'smoala de acacia contribuie la eliminarea toxinelor și normalizarea tractului gastro-intestinal',
    lt36: 'Va reduce <br> pofta',
    lt37: 'CEAI VERDE',
    lt38: 'reduce pofta de alcool, are un efect hepatoprotector și de detoxifiere',
    lt39: 'Va calma <br> nervii',
    lt40: 'L-ORTININĂ',
    lt41: 'calmează sistemul nervos, ajută la ameliorarea intoxicației cu alcool',
    lt42: 'Acid succinic',
    lt44: 'reduce efectul toxic al alcoolului, elimină mahmureala, contribuie la o mai bună funcționare a inimii',
    lt44: 'Vitamina B6',
    lt45: 'contribuie la ameliorarea stării psihice, reduce pofta de alcool',
    lt46: 'Acid succinic',
    lt47: 'reduce efectul toxic al alcoolului, elimină mahmureala, contribuie la o mai bună funcționare a inimii',
    lt48: 'Vitamina B6',
    lt49: 'contribuie la ameliorarea stării psihice, reduce pofta de alcool',
    lt50: 'ZINCUL',
    lt51: 'neutralizează etanolul, reduce efectul toxic al alcoolului, elimină mahmureala',
    lt52: 'VITEMINELE GRUPEI B',
    lt53: 'contribuie la ameliorarea stării psihice, reduce pofta de alcool',
    lt54: 'Alcobarrier',
    lt55: 'testat',
    lt56: 'practic',
    lt57: 'În anul 2014 a fost efectuat un studiu în care 1000 de voluntari, care suferă de alcoolism, timp de o lună au luat câte 2 porții de băutură.',
    lt58: 'Conform rezultatelor studiului 75% din aceștia au marcat reducerea poftei de alcool și ameliorarea stării organismului, iar 25% au renunțat totalmente la alcool. În urma examenului medical s-a constatat o ameliorare vizibilă a parametrilor hepatici, a stării de sănătate a sistemului cardio-vascular și a sistemului nervos.',
    lt59: 'Băutura și-a demonstrat eficacitatea la toți cei 100% de voluntari, indiferent de severitatea bolii și durata consumului de alcool.',
    lt60: 'Nu mă consideram alcoolic, dar îmi plăcea să beau. Însă cu timpul am început să observ că cu cât mai puternică este mahmureala, cu atât aveam dureri din ce în ce mai mari de ficat, dar și pofta de alcool creștea. Am înțeles că e timpul să încetez. Am început să beau "Alcobarrier" și îndată m-am simțit mai bine, iar peste câteva săptămâni și pofta de alcool a dispărut. Acum nu beau deloc!',
    lt61: 'Nicolae, 40 de ani',
    lt62: 'Cândva soțul meu servea nu atât de des, dar cu timpul s-a transformat în dependență. Însă soțul meu nu dorea să recunoască că este bolnav. O cunoscută mi-a recomandat să încerc produsul ”Alcobarrier” în lupta soțului meu împotriva dependenței de alcool. Am început să adaug Alcobarrier în băutura lui. Bine că forma și gustul Alcobarrier mi-a permis s-o fac fără ca soțul să observe ceva. Peste ceva timp pofta de alcool la soțul meu a dispărut.',
    lt63: 'Antonina, 53 de ani',
    lt64: 'Tatăl meu era puternic dependent de alcool. Adeseori după «sărbători» eram nevoiți să ne cerem ajutorul medicilor, pentru ca aceștia să cu ajutorul glucozei să-l readucă la starea normală. Împreună cu mama mea am comandat produsul Alcobarrier și am început să-l adăugăm imperciptibil în băuturile tatălui. De acum trei luni tata nu bea deloc, iar din care cauză știu numai eu și mama. Dacă în familia dumneavoastră există această problemă groaznică, folosiți produsul Alcobarrier!',
    lt65: 'Nicolae, 35 de ani',
    lt66: 'Medici norcologi recomandă <br> Alcobarrier',
    lt67: '"Alcobarrier recomand tuturor pacienților – și celor,care ies din chef, și celor, care nu beau mult, dar doresc deloc să nu mai bea. Produsul nu  numai că elimină pofta de alcool din punct de vedere psihologic, dar și îmbunătățește starea de sănătate a organismului, are o influență pozitivă asupra ficatului, inimii, sistemului nervos. Acțiunea complexă a preparatului ajută pacienților mei să renunțe la alcool și să revină la viața normală”.',
    lt68: 'Niconov А.А., medic narcolog categorie superioară',
    lt69: 'reducere <br> -50%',
    lt70: 'preț vechi',
    lt71: 'a rămas <br> până la sfârșitul promoției',
    lt72: 'A comanda',
    lt73: 'Produs certificat, compoziție, modul și calea de administrare sunt indicate în prospect și pe ambalaj. Plata se face cash (în numerar) la livrare.',
    lt74: '',
    lt75: '',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};