var new_lang = {
    lt1: 'Pasūtīt bezmaksas zvanu',
    lt2: '"TINEDOL" iedarbība',
    lt3: 'Efektivitāte',
    lt4: 'Atsauksme',
    lt5: 'Vienkārš veids lai uzvarētu sēnīti, kņudēšanu, plaisas!',
    lt6: 'Ārstē papēžu un nagu sēnīti',
    lt7: 'Novāc kņudēšanu un lobīšanās',
    lt8: 'Novērš svīšanu un smaku',
    lt9: 'Ārstē plaisas papēžos',
    lt10: 'ATLAIDE',
    lt11: '-50%',
    lt12: 'Ierobežota sērija!<br>Steidzaties<br> Tikai <span class="product-how-much"><span class="lastpack">5</span> iepakojumi</span> <br>pa speciālo cenu!',
    lt13: 'Līdz akcijas beigām palika:',
    lt14: '00',
    lt15: 'stundas',
    lt16: '25.',
    lt17: 'minūtes',
    lt18: '59.',
    lt19: 'sekundes',
    lt20: 'Pilna cena:',
    lt21: 'Cena ar atlaidi',
    lt22: 'Pasūtīt',
    lt23: 'Jūsu dati ir aizsargāti',
    lt24: '<span class="title2-span1">Uzskatāt, ka sēnitie jums neattiecas?</span> Ja jums ir kaut viens simptoms,<br> tad sāciet ārstēšanos jau šodien<br>',
    lt25: 'Nepatīkama smaka',
    lt26: 'Plaisas un lobīšanās',
    lt27: 'Nepareiza naga forma',
    lt28: 'Nags paliek <br>brūns vai dzeltens',
    lt29: 'Vadziņas un balti <br>punkti uz naga',
    lt30: 'Kņudēšana un dedzināšana',
    lt31: 'Tulznas uz papēžiem',
    lt32: 'Notirpums un durstīšana',
    lt33: 'Lokāli ādas blīvējumi<br>papēža apvidū',
    lt34: 'Kas notiks, ja neārstēt papēžu sēnīti',
    lt35: 'Statistika rāda, ka katrs piektais Latvijas iedzīvotājs mocās no sēnīšu slimībām. <br>Cieši un aizvērti apavi, sintētiskas zeķes, saunas, baseini. <br> <span class="stage__span1">Vasaras sezonā pievienojas pludmales un parki, kur daudzi staigā plikām kājām.<br>Tas viss izraisa smagas slimības!</span> Stop!',
    lt36: '1. stadija:',
    lt37: '<i>Lobīšanās</i>',
    lt38: '<i></i>',
    lt39: '<i>Kņudēšana</i>Svīšana',
    lt40: '<i>Nepatīkama smaka</i>',
    lt41: '<i>Diskomforts</i>',
    lt42: '2. stadija:',
    lt43: '<i>Nagu sēnīte</i>',
    lt44: '<i>Dziļas plaisas</i>',
    lt45: '<i>Stiprāka kņudēšana un svīšana</i>',
    lt46: '<i>Ļoti stipra un nepatīkama smaka</i>',
    lt47: '<i>Dzelteni, vāji nagi</i>',
    lt48: '<i>“Mirusi”, raupja āda</i>',
    lt49: '<i>Spēcīgs diskomforts <br>staigāšanas laikā</i>',
    lt50: '3. stadija:',
    lt51: '<i>Lobīšanās un kņudēšana<br>starp pirkstiem</i>',
    lt52: '<i>Čūlas un dziļas<br>plaisas</i>',
    lt53: '<i>Sāpes</i>',
    lt54: '<i>Pūžņu perēkļi</i>',
    lt55: '<i>Nagu zaudēšana</i>',
    lt56: '<span class="stage__main-block-span">Ja papēžus neārstēt, tad ātri var ielaist bīstamu slimību!</span><br> Iedomājaties, ka tās ir jūsu kājas! Vai jūs vēlētos šādus papēžus?<br> Sakiet nē!',
    lt57: 'Kā darbojas <span class="title4-span1">krēms "TINEDOL"?</span>',
    lt58: '<span class="work__span1">Regulāri lietojot, "TINEDOL" atbrīvo uzreiz no vairākām problēmām.</span> Tā aktīvie komponenti Climbazole un Farnesol novērš:',
    lt59: 'Sēnīti',
    lt60: 'Smaku',
    lt61: 'Svīšanu',
    lt62: 'Plaisas',
    lt63: '<span class="consist__text--b"> Climbazole</span> — apstādina raugu un sēnīšu attīstību. Atbrīvo no kņudēšanas. Postoši ietekmē sēnītes',
    lt64: '<span class="consist__text--b"> Farnesol</span> — “izslēdz” sviedru dziedzerus. Dezinficē, sausina un baro kāju ādu, uz ilgu laiku piedod patīkamu aromātu. ',
    lt65: 'Krēms lieliski mitrina un baro kāju ādu, novāc rupjumus, noloba, aizdziedē plaisas.',
    lt66: 'Salīdzinājumā ar citiem līdzekļiem, "TINEDOL" krēms vienmērīgi izlīdzinās pa visu papēža platību.Ātri iesūcas un neatstāj pēdas uz gultas veļas un drēbēm.',
    lt67: 'Ierobežotā sērijā mēs pievienojām akmens eļļu. Tā efektīvi cīnās ar tulznām. Dāvina ādai maigu vēsumu un komfortu pēc smagas dienas.',
    lt68: 'Vienkāršs veids kā uzvarēt<br>sēnīti, kņudēšanu un plaisas!',
    lt69: 'Efekts pēc 30 dienu<span class="title6-span1">eļļas lietošanas</span> "TINEDOL"',
    lt70: 'Pazūd papēžu un nagu <br>sēnīte',
    lt71: 'Ievadiet savus datus formā zemāk',
    lt72: 'Paiet kņudēšana un<br>lobīšanās',
    lt73: 'Patīkama smarža',
    lt74: 'Kājas nesvīst',
    lt75: 'Ārstējas <br>plaisas',
    lt76: 'Kustību modrums <br>un komforts',
    lt77: 'Skaisti, <br>kopti papēži',
    lt78: 'Kā lietot <span class="title7-span1">"TINEDOL" krēmu?</span>',
    lt79: 'Pirms lietošanas izmazgājiet kājas ar ziepēm un kārtīgi noslauciet ar dvieli.Pārklājiet krēmu ar plānu kārtu uz visa papēža.  Katru vakaru pirms miega 30 dienu laikā. <br>Ievērojāt, ka jūsu pēdiņas paliek rozā krāsā, bet āda vesela!',
    lt80: 'Ar ko "TINEDOL" krēms ir labāks par citiem pretsēnīšu preparātiem?',
    lt81: 'Pretsēnīšu līdzekli dalās uz divām grupām: pirmie nepalīdz, otrie darbojas tikai lietošanas procesā. Cilvēkiem, kas slimo ar kāju sēnīti, ir jālieto krēmi un smēri pastāvīgi.',
    lt82: '"TINEDOL" maina situāciju pašos pamatos. Masvelda klīniskse izmeklējumi pierādīja, ka šis līdzeklis efektīvi atbrīvo no papēžu un nagu sēnītēm. Jau pēc 1. kursa sēnīte pazūd un neatgriežas. Tik spēcīgs efekts ir pateicoties noturālajiem dabas komponentiem.',
    lt83: 'Speciālista viedoklis',
    lt84: 'Šis prerarāts jau sen pierādīja savu efiktivitāti. Tā galvenā vērtība – kompleksa kopšana. Pat ja jums nav visu simptomu, ir vērts sākt lietot "TINEDOL" profilaksei jau tagad. Sēnite attīstās ļoti ātri! Šodien jums ir viegla lobīšanās un kņudēšana, bet rītdien jums nāksies gulties klīnikā un dzert antibiotikas 5. reizes dienā.Nevilcināties! Ārstējiet problemu tūlīt.vairāk par to, sēnīte ir lipīga. Ja slimi esat jūs vai kāds no tuviniekiem – slimo visa ğimene!',
    lt85: '— Aleksējs Bozunovs<br>medicīnas zinātņu kandidāts, Maskavas valsts medicīnas un stomatoloğijas universitāte N.A. Semaško vārdā. Ārsts dermatologs, kosmetologs, mikologs.',
    lt86: 'Atsauksmes',
    lt87: 'Līdz "TINEDOL" es domāju, ka sēnītes ir kā sēnes un pazūd tikai uz laiku. Izmēğināju vairākus līdzekļus. Simptomi pārgāja, bet sēnīte, acīmredzot, palika pēdā. Nācās griezties pie ārsta, viņš arī izrakstīja "TINEDOL". Jau pusgadu mani nekas netraucē.<br>Paldies! ',
    lt88: 'Gunita, Rīga',
    lt89: 'Pēdiņas ir kā bēbītim! Es regulāri apmeklēju baseinu. Kad uzzināju, ka man ir sēnīte, nebiju šokēta, jo dušas ir kopējas, ğērbtuves – arī, hlors no sēnītēm nepalīdzēs. Ko lai dara. Mumus visas meitenes ğērbtuvē zina, ka labāka par "TINEDOL" līdzekļa nav! Visas lietojam, no mums neviena neslimo!',
    lt90: 'Zane, Cēsis',
    lt91: 'Sēnīte pierod pie tām vielām, ar kurām jūs to ārstējat. Vīram drausmīgi svīda kājas, tādēļ sēnīte negāja prom. Izvēlējāmies "TINEDOL" divu kvalitāšu dēļ: tas noņem gan svīšanu, gan sēnīti. Lietoja 3 mēnešus. Viss nonāca!',
    lt92: 'Kate, Brenguļi',
    lt93: '',
    title: 'Nopirkt "TINEDOL" Lēti. Cenas, atsauksmes. Pasūtiet "TINEDOL" tūlīt!',
}