var new_lang = {
lt1: 'Alcobarrier - efektywny środek w walce z alkoholizmem',
lt2: 'Alcobarrier – <br/> efektywny środek <br/>w walce z alkoholizmem',
lt3: 'Alcobarrier – <br/> powiedz <span>«NIE»</span> nałogowi!',
lt4: 'likwiduje pociąg do alkoholu',
lt5: 'Odbudowywuje uszkodzone komórki wątrobowe',
lt6: 'Usuwa toksyny z organizmu',
lt7: 'Uspokaja system nerwowy',
lt8: 'Nie posiada smaku ani zapachu',
lt9: 'do końca promocji zostało',
lt10: 'Zamówić',
lt11: 'Alcobarrier – ekeftywny środek, który usuwa toksyny z organizmu i likwiduje pociąg do alkoholu. Kwas bursztynowy i fibregum w składzie Alkobariery usuwają toksyny z organizmu po spożyciu napojów alkoholowych i wywiera ogólnowzmacniające działanie. Unikalny składnik roślinny - ekstrakt z karczocha – likwiduje psychiczne uzależnienie od alkoholu. W skład opatentowanej formuły Alkoberiery wchodzi witamina B6, której niedobór występuje u wszystkich uzależnionych od alkoholu. Dzięki wyrównaniu ilości tej witaminy w organiźmie, eliminuje się psychozę alkoholową i dla człowieka staje się łatwą rezygnazja ze spożycia alkoholu. <br> Alcobarrier nie posiada wyraźnego smaku i zapachu oraz łatwo rozpuszcza się w wodzie. Dlatego nie wywołuje nudności i uzależnienia.',
lt12: '<span>Jak działą</span> Alcobarrier',
lt13: '<div class="item-title">fibregum</div> usuwa toksyny z organizmu i usprawnia pracę układu pokarmowego',
lt14: '<div class="item-title">ekstrakt z karczocha</div> likwiduje pociąg do alkoholu, posiada działanie hepatoprotekcyjne i detoksykacyjne.',
lt15: '<div class="item-title">Ekstrakt z serdecznika</div> uspokaja system nerwowy, pomaga zlikwidować intoksykację',
lt16: '<div class="item-title">Kwas bursztynowy</div> usuwa toksyczne działanie alkoholu, likwiduje kaca, usprawnia pracę serca',
lt17: '<div class="item-title">Witamina B6</div> Sprzyja polepszeniu stanu psychicznego, likwiduje pociąg do alkoholu',
lt18: 'Alcobarrier',
lt19: 'sprawdzony',
lt20: 'w praktyce',
lt21: 'W 2016 roku zostało przeprowadzone badanie, w trakcie którego 1000 ochotników, cierpiących na alkoholizm, w ciągu miesiąca regularnie stosowali Alcobarrier.',
lt22: 'W wyniku badania 25% zauważyło znaczne zmniejszenie pociągu do alkoholu i polepszenie stanu organizmu, а 75% badanych całkowicie rzucili picie! W wyniku badania odnotowano znaczne polepszenie wskaźników wątroby, stan układu krwionośnego i nerwowego.',
lt23: 'Napój dowiódł swojej efektywności u 100% ochotników, niezależnie od ciężkości zachorowania i czasu trwania spożywania alkoholu.',
lt24: 'Kiedy rozwiodłem się z żoną, poszedłem, jak sie mówi, «na całość». Kilka miesięcy piłem praktycznie codziennie, straciłem pracę, zrozumiałem, że się staczam, ale nic nie mogłem z tym zrobić. Dziękuję bratu, którzy przyszedł z pomocą. Zmusił mnie do stosowania Alcobarrier. On wymagał i pilnował, żebym regularnie go stosował. Teraz zdecydowanie mogę powiedzieć, że jestem człowiekiem wolnym od uzależnienia.Jeśli wy albo wasi bliscy mają taki problem, stosujcie Alcobarrier, on naprawdę pomaga!',
lt25: 'Siergiej, 40 lat',
lt26: 'Wcześniej, mój mąż upijał się niezbyt często, ale z czasem przerodziło się to w uzależnienie. Jednakże mąż nie chciał się przyznać, że jest chory. W związku z walką męża z uzależnieniem alkoholowym, znajoma poradziła użyć Alcobarrier. Zaczęłam mu dodawać Alcobarrier do napojów, na szczęście, postać i smak Alkobariery pozwala robić to niezauważalnie. Po pewnym czasie pociąg do alkoholu u męża zniknął. Teraz od pozbył się uzależnienia! Dziękuję twórcom Alkobariery!',
lt27: 'Antonina, 53 lata',
lt28: 'Mój ojciec cierpiał na ogromne uzależnienie alkoholowe, nie raz po «uroczystościach» trzeba było skorzystać z pomocy lekarzy, żeby oni przy pomocy glukozy przywrócili go do normalnego stanu. Razem z mamą zamówiłyśmy Alcobarrier i zaczęłyśmy dyskretnie dodawał ją tacie do napojów. Już trzy miesiące ojciec nie pije w ogóle, a powód znamy tylko ja i mama. Jeśli w waszej rodzinie też występuje ten straszny problem, użyjcie Alcobarrier!',
lt29: 'Mikołaj, 35 lat',
lt30: 'Lekarze zajmujący się problemami z narkotykami rekomendują Alcobarrier',
lt31: '"Alcobarrier rekomenduję wszystkim swoim pacjentom, zarówno tym, którzy wydostają się z pijaństwa, jak i tym, którzy piją niewiele, ale chcą rzucić całkowicie. środek nie tylko likwiduje psychologiczny pociąg do alkoholu, ale również odbudowywuje organizm, wywiera pozytywnie działanie na wątrobę, serce, nerki i system nerwowy. Kompleksowe działanie preparatu pomaga moim pacjentom rzucić picie i szybko powrócić do pełnowartościowego życia»',
lt32: 'Nikonow А.А., lekarz zajmujący się problemami z narkotykami wyższej kategorii',
lt33: 'Alcobarrier – <br/> unikalny certyfikowany środek',
lt34: 'Alcobarrier nie zawiera GMO, testowany klinicznie i nie wywołuje efektów ubocznych.',
lt35: 'w 90% składa się z naturalnych składników roślinnych',
lt36: 'Alcobarrier nie podwyższa poziomu cukru we krwi i pasuje chorym na cukrzycę',
lt37: 'Alcobarrier przeszedł certyfikację, potwierdzającą jego wysoką jakość i bezpieczeństwo',
lt38: 'Sposób użycia',
lt39: 'Bardzo wygodny w użyciu – <br/> prezentuje sobą <span>szybko rozpuszczalny <br/> w wodzie proszek</span>',
lt40: 'Pozytywny efekt można zaobserwować <br/> <span>od pierwszego dnia stosowania.</span> Zaleca się <br/> stosować raz na dobę.',
lt41: 'Dostawa i opłata',
lt42: 'Otrzymają Pańśtwo Alcobarrier już 2-3 dni po zamówieniu (mieszkańcy Moskwy i Petersburga). Do pozostałych regionów dostawa jest realizowana w ciągu 14 dni. Opłata przy odbiorze zamówienia!',
lt43: 'Strzeżcie się podróbek!',
lt44: 'Produkt jest sprzedawany w oryginalnym opakowaniu z unikalnym numerem seryjnym! <br> Można znaleźć numer na opakowaniu i sprawdzić jego autentyczność.',
lt45: 'Sprawdzić numer',
lt46: 'Jak zamówić Alcobarrier?',
lt47: 'wypełnij formularz zamówienia',
lt48: 'wybierz sposób dostawy',
lt49: 'opłać towar przy odbiorze',
lt50: 'Zniżka -50%',
lt51: 'stara cena',
lt52: 'do końca promocji <br/> zostało',
lt53: 'Imię i nazwisko <small>Na przykład: Jan Kowalski</small>',
lt54: 'Telefon <small class="phone_helper">Na przykład: +48 560 064 735</small>',
lt55: 'Zamówić',
lt56: 'towar <br/> certyfikowanyн',
lt57: 'Gwarancja <br/> rezultatu',
lt58: 'Produkt certyfikowany, skład, sposób i instrukcja użycia są ukazane na opakowaniu. Opłata po otrzymaniu towaru (za pobraniem).',
lt59: 'Zamówiono: <font size="6">4986</font> szt.',
lt60: 'zostało: <font size="6">14</font> szt. ',
lt61: 'Złożyć zamówienie!',
lt62: 'Promocja!',
lt63: 'Specjalna propozycja na preparat <strong>Alcobarrier</strong> <br /> <br /> tylko za <span class="newprice price_main">1490 rubli</span>!',
lt64: 'Imię i nazwisko:',
lt65: 'Na przykład:',
lt66: 'Telefon:',
lt67: 'Towar: <span style="color:#F00;">Alcobarrier</span>',
lt68: 'Cena: <span class="newprice price_main">1490 rubli</span>',
lt69: '*Wypełnienie formularza nie zobowiązuje Państwa do zakupu',
lt70: 'Oferta spodobała się?',
lt71: 'Opowiemy Państwu wszystko o tym towarze, zaproponujemy najlepsze warunki i zapoznamy z odpowiadającymi ofertami promocyjnymi!',
lt72: 'Operator oddzwoni do Państwa za 15-30 minut',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};