var new_lang = {

"lt0": "LiveJournal",
"lt1": "Principal",
"lt2": "Classificações",
"lt3": "Login",
"lt4": "CRIAR BLOG",
"lt5": "Política e sociedade",
"lt6": "Em todo o mundo",
"lt7": "Cinema",
"lt8": "Ciência e tecnologia",
"lt9": "Entretenimento",
"lt10": "Família e filhos",
"lt11": "Comida",
"lt12": "Beleza e saúde",
"lt13": "Estilo de vida",
"lt14": "20 anos de LiveJournal",
"lt15": "Mais <span class=\"categories__more-icon\"><svg class=\"svgicon flaticon flaticon--arrow-right\" height=\"16\" width=\"16\" xmlns=\"http://www.w3.org/2000/svg\"></svg></span>",
"lt16": "Casa",
"lt17": "Noah Grouwet",
"lt18": "10 minutos para ler",
"lt19": "Agora o registro está no 156º lugar em classificação",
"lt20": "LJ recomenda",
"lt24": "Categoria:",
"lt25": "Saúde",
"lt26": "Cancelar",
"lt27": "TRATAMENTO DE ARTRITE COM 1 CURSO DE DURAÇÃO SEM REMÉDIOS E CIRURGIAS",
"lt28": "Um pouco sobre minhas articulações",
"lt29": "Tenho 37 anos. Minhas articulações doem periodicamente a partir dos 21 anos. Vivo bem, mas é difícil tolerar uma mudança de clima. O esporte é contraindicado, depois de praticá-lo eu mal consigo ficar de pé. Com a idade, minhas articulações doem mais e mais, e agora viver tornou-se impossível.",
"lt30": "Para que você entenda todo o quadro do que está acontecendo, todo dia começa com uma dor terrível nas articulações, leva pelo menos meia hora para aquecê-las e aplicar todas as pomadas. Todo dia passo em tormentas, eu carrego um punhado de comprimidos nos bolsos. Periodicamente as articulações incham e a febre aumenta, o meu estado é semelhante à gripe. Nos últimos seis meses eu perdi cerca de 10 kg. Passo todo o meu tempo em dois lugares – no trabalho e na cama.",
"lt31": "Tentativas de tratamento",
"lt32": "Eu não fui para automedicação, então fui para a clínica onde fui diagnosticado com artrite reumatoide crônica e prescreveram o tratamento para mim. Injeções nas articulações, hormônios e anti-inflamatórios, até mesmo antidepressivos. Acrescente a tudo isso o desgaste constante de uma cinta, nutrição fracionada com alto teor de proteínas, que depois de um tempo causa problemas nas fezes. Que horror, que durou seis meses. Às vezes ficava mais fácil, mas depois do alívio a dor era ainda maior. Tomei analgésicos todos os dias e comecei a orar, porque eles quase que não faziam efeito...",
"lt33": "Os médicos elaboraram vários esquemas de tratamento baseando-se na minha artrite que não funcionaram. Na consulta eu quase chorei. Um médico com rosto indiferente ofereceu cirurgia nas articulações. Ele pediu uma boa grana, não deu garantias de recuperação e pediu para não atrasar a fila.",
"lt34": "Desesperança total. Tive que me distrair, assim eu  tirei férias e fui ao resort.",
"lt35": "Tratamento em um resort",
"lt36": "Eu me encontro entre os aposentados, esperando a vez deles para o procedimento. Aconteceu que não era tão ruim. No resort há massagens, lama para o tratamento, piscinas e não há nenhuma injeção de remédios. Eles apenas aplicaram creme de tubarão nas minhas articulações.",
"lt37": "Durante a primeira semana, estávamos criticando vigorosamente nossa medicina, reclamando de dores infernais. Em poucos dias, me senti muito melhor.",
"lt38": "Logo as reclamações diminuíram, discutimos tudo, menos nossas doenças.",
"lt39": "Milagre",
"lt40": "No final da segunda semana, minhas articulações quase não estavam mais doendo. E quando o meu tratamento nesse local terminou, cada um de nós recebeu uma caixa de Artrovex - o mesmo creme com o qual nós fomos tratados aqui. Foi recomendado usá-lo pelo menos de 2 a 3 semanas para dizer adeus à artrite.",
"lt41": "Quando terminei o curso do tratamento, tive medo de ficar em pé. Não, as articulações não estavam doendo, mas eu tive medo de que aquela dor terrível voltasse novamente. Esqueci rapidamente como estava sofrendo. Dois meses depois, me forcei a procurar um médico. ..",
"lt45": "Noah Grouwet",
"lt46": "Adicionar a amigos",
"lt47": "Mais LJ MEDIA",
"lt48": "a_nalgine <span class=\"itemTimereading\">Ler por 5 min. </span>",
"lt49": "Sobre o pecado da juventude, que cada um terço repete ...",
"lt50": "bookmatejournal <span class=\"itemTimereading\">Ler por 9 min.</span>",
"lt51": "Maravilhosa Angelina Jolie pela primeira vez falou sem esconder nada...",
"lt52": "fomaport <span class=\"itemTimereading\">Ler por 10 min.</span>",
"lt53": "«Eu os alimentei de colher, dava comadre, mas...",
"lt54": "gelio <span class=\"itemTimereading\">Ler por 19 min.</span>",
"lt55": "Tashkent de cima: a maior cidade da Ásia Meridional...",
"lt56": "Weekly Newsletter",
"lt57": "Assine notícias independentes",
"lt58": "dos melhores blogueiros do LiveJournal",
"lt59": "Inscrever-se",
"lt60": "Comentários:",
"lt61": "Marco",
"lt62": "História de vida! Eu passei por sete círculos do inferno no hospital, por todos os procedimentos e tratamentos de tortura. As articulações doíam e continuavam doendo. Ainda sofro de dor nas articulações. Onde posso encontrar esse Artrovex?",
"lt63": "Responder",
"lt64": "Minimizar",
"lt65": "Helena",
"lt66": "Não tem tal remédio nas farmácias! Andei por todas as farmácias da minha cidade! Encontrei o site oficial do remédio: aqui está o link para o site. Encomende aqui, o remédio chegou rápido e ainda há um desconto. Comecei o tratamento rs",
"lt67": "Responder",
"lt68": "Minimizar",
"lt69": "Marcos Vinicius",
"lt70": "Fui submetido a duas cirurgias. Fiquei deitado por cerca de seis meses, a recuperação é muito longa. Encontrei Artrovex e depois de um mês me esqueci das cirurgias, as articulações dos joelhos pararam de doer e inchar! Um remédio realmente bom sem efeitos colaterais",
"lt71": "Responder",
"lt72": "Minimizar",
"lt73": "Enrique Mas",
"lt74": "Meu avô fez o tratamento com Artrovex e não tomou nenhum medicamento. Ele me disse que nasceu de novo. Antes disso, ele não levantava da cama há dias, e agora está constantemente andando para lá e para cá, ninguém consegue trancá-lo em casa",
"lt75": "Responder",
"lt76": "Minimizar",
"lt77": "Cristiano",
"lt78": "Fiz o pedido no site oficial. Eles estão com uma promoção no site, logo logo ela irá acabar, corram",
"lt79": "Responder",
"lt80": "Minimizar",
"lt81": "Rosa Franco",
"lt82": "Que boa viagem para o resort o autor fez...",
"lt83": "Responder",
"lt84": "Minimizar",
"lt85": "Simon",
"lt86": "Eu sou personal trainer. Minhas articulações muitas vezes ficam machucadas, e Artrovex ajuda muito. Creme tira dor e resupera a articulação machucada, Eu compro neste site LINK PARA O SITE",
"lt87": "Responder",
"lt88": "Minimizar",
"lt89": "Doris",
"lt90": "Durante toda a minha vida eu fazia patinação artística, mas tive que desistir ... as articulações doíam muito. Não fui ao médico, conheço nossa medicina. Eles prescrevem um monte de pílulas e depois dão de ombros quando não há resultados. Tive sorte de minha tia ser terapeuta, e ela me imediatamente disse para comprar Artrovex. Para uma recuperação completa, eu precisava de apenas 2 caixas! ",
"lt91": "Responder",
"lt92": "Minimizar",
"lt93": "Camila",
"lt94": "Um ano atrás, eu machuquei minha mão esquerda, então minha articulação do cotovelo estava constantemente doendo. Cheguei ao hospital, eles queriam fazer uma cirurgia. Fiquei com medo, me recusei a fazê-la e fui procurar por algumas soluções alternativas. Minha avó experimentou o creme Artrovex, ela tratou as articulações com ele, e ele a ajudou bastante. Após as primeiras aplicações, a dor desapareceu, o desconforto permaneceu e depois o creme acabou ... pedi mais creme kkk",
"lt95": "Responder",
"lt96": "Minimizar",
"lt97": "Edilson Guimaraes",
"lt98": "Consegui curar a artrite crônica com Artrovex! Apenas com um curso do tratamento! Minha esposa comprou este creme para mim. Ela disse que ouviu falar sobre sua eficácia e percorreu todas as nossas farmácias; então, um vendedor lhe disse que era possível comprá-lo apenas pela Internet. . ",
"lt99": "Responder",
"lt100": "Minimizar",
"lt101": "Carlos Garcia",
"lt102": "Tenho 56 anos, trabalhei na fábrica a vida toda. Durante últimos dois anos eu pensava em parar de trabalhar, minhas pernas doem e incham terrivelmente. Nesses dois anos, tirei licença médica umas 10 vezes e tentei curar minhas articulações. Após 10 dias de licença nada aconteceu então eu decidi pedir uma demissão, quando de repente me deparei na Internet com Artrovex. Acreditei nas opiniões sobre o produto, mas não tinha muita esperança. Comecei a me sentir melhor em alguns dias, ficou mais fácil trabalhar, e no final do tratamento as articulações pararam de doer. Eu recomendo este creme para todos.",
"lt103": "Responder",
"lt104": "Minimizar",
"lt105": "Osmar",
"lt106": "Pedi neste site LINK PARA O SITE, ele é de confiança. Aqui eu comprei algumas caixas para meus parentes.",
"lt107": "Responder",
"lt108": "Minimizar",
"lt109": "Agnes",
"lt110": "Encomendei Artrovex para o meu marido no site oficial. Por muito tempo ele tratava a artrite com remédios populares, e depois ele resolveu ir ao médico. O médico disse que havia um bom remédio chamado Artrovex. Ele prescreveu o tratamento e mandou o meu marido para casa. Depois de algumas semanas, o marido declarou com alegria que a artrite quase não o atormenta mais. E após o tratamento ele já está completamente saudável, e até começou a correr pela manhã! Artrovex é realmente um remédio eficaz.",
"lt111": "Responder",
"lt112": "Minimizar",
"lt113": "Manuel Castilho",
"lt114": "Eu concordo com todos os comentadores. Este creme realmente funciona! Duvidei se a compra valeria a pena, experimentei várias pomadas, cremes e medicamentos - o efeito era sempre temporário. Depois de usar Artrovex, as articulações pararam de doer completamente. Levei um pouco mais de um mês para o tratamento." ,
"lt115": "Responder",
"lt116": "Minimizar",
"lt117": "Adicionar comentário",
"lt118": "Sobre",
"lt119": "Termo de Acordo do Usuário",
"lt120": "Ajuda",
"lt121": "Botão \"Compartilhar\""






};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };