var new_lang = {

lt0: 'Hypertenzia (tlakové skoky) - v 89% zabíja pacientov v spánku! Počet infarktov za rok 2016 vyrástol na 1,54 milióna! Ako zabrániť smrti od tlakových skokov so zľavou 50% - rozhovor s vedúcim kardiologického oddelenia, Monikou Jankovou!',
lt2: 'Dostávame veľké počty sťažností,<br>súvisiace s HYPERTENZIOU a ochoreniami!<br>Práve preto, pre domácich je produkt „ReCardio“ dostupný s 50% zľavou!<br>',
lt3: 'KUPIŤ V ZĽAVE',
lt4: 'Nasledujúca strana',
lt5: 'Pochádzate z Bratislavy<span class="user-city"></span>?Počkajte!',
lt6: 'Odtiaľ dostávame aj najväčší počet sťažností, ktoré sa týkajú hypertenzie a vysokého tlaku!<br>A preto, pre domácich je „ReCardio“ dostupný s 50% zľavou!',
lt7: 'Získajte zľavu!',
lt8: 'Zdravie',
lt9: ' Činnosť',
lt10: ' Dokumenty',
lt11: 'Tlačové centrum',
lt12: ' Súťaže',
lt13: 'Domovská stránka',
lt15: 'Tlačové centrum',
lt17: 'Novinky',
lt19: 'Špeciálna tlačová konferencia!',
lt20: 'Hypertenzia (tlakové skoky) - v 89% zabíja pacientov v spánku! Počet infarktov za rok 2016 - 1,54 milióna! <span style="font-weight: normal;"> Ako zabrániť smrti od tlakových skokov so zľavou <span style="color:red;">50% - rozhovor s vedúcim kardiologického oddelenia</span>',
lt21: 'Úvod: Infarkty a mŕtvice zapríčinené tlakom, spôsobujú takmer 70% všetkých úmrtí na svete. Sedem z desiatich ľudí zomiera kvôli zablokovaniu tepien srdca alebo mozgu. Prakticky vo všetkých prípadoch príčinou takého hrozného konca sú tlakové skoky spôsobené hypertenziou. „Tichý zabijak“, ako ho pomenovali kardiológovia, každoročne zabije milióny ľudí. Dnes uverejníme rozhovor s riaditeľkou Kardiologického inštitútu, ktorá vám povie, čo je potrebné robiť ak sa vám neustále mení tlak.',
lt22: '<strong>Ivana Šusterová</strong><br>Doktor lekárskych vied, profesor, riaditeľ Kardiologického inštitútu.<br>25 ročná stáž',
lt23: '<i>Korešpondent</i>: „Ivana Šusterová, Dokážete zostaviť akúsi štatistiku úmrtnosti z nárastu tlaku v dôsledku hypertenzie v Rusku?“',
lt24: '<strong>Šusterová Ivana:</strong>Nie je žiadnym tajomstvom, že kardiovaskulárne ochorenia sú svetovými lídrami medzi chorobami, na ktoré zomierajú veľké počty ľudí. Takže vysoký krvný tlak (hypertenzia) je hlavnou príčinou všetkých infarktov a mŕtvic, ktoré sú spôsobené kardiovaskulárnymi ochoreniami. Samozrejme, že aj iné choroby taktiež vyvíjajú tlak na telo, ale hypertenzia je spúšťačom kolísania tlaku, ktorý následne človeka posiela na druhý svet.',
lt25: 'Ak hovoríme o konkrétnych hodnotách, cca<strong>77-78% úmrtí sú spôsobené hypertenziou, čiže vysokým krvným tlakom.</strong>V číslach je to približne<strong>1,54 milióna úmrtí za rok 2016a 1,49 miliónaza rok 2015.</strong>Z čoho vyplýva, že čísla sú naozaj kolosálne a desivé. Až donedávna nikto nepociťoval rozsah úmrtnosti spôsobené hypertenziou, keďže neboli vytvorené žiaden podrobné štatistiky a analýzy. Za obdobie v rozmedzí od roku 2011 do roku 2016 sme zhromaždili obrovské množstvo údajov, ktoré nás veľmi sklamali.',
lt26: '<i>Korešpondent</i>: „Ako presne spôsobuje pokles tlaku takéto dôsledky?“',
lt27: '<strong>Šusterová Ivana:</strong>Tlakové skoky zakaždým spôsobujú kolosálne preťaženie srdcového svalu, ktoré skôr alebo neskôr končia zástavou srdca. Skoro vždy zvýšený tlak vedie k preťaženiu srdca 10 až 20 krát. Ak budeme hovoriť o konečnom vývoji ochorenia tak<strong>hypertenzia alebo vysoký krvný tlak vždy vedie k rovnakému výsledku a to k smrti.</strong>Ak ju charakterizujeme ako kľúčovú príčinu smrti človeka, tak sa to stáva v 89% prípadov. Znamená to, že v 89% prípadov je hypertenzia ukončená infarktom alebo mŕtvicou. Ak by pred 20-30 rokmi, pacient trpiacic hypertenziou, by mal šancu prežiť ďalších 10-20 rokov, ale teraz približne <strong>2/3 (dve tretiny) pacientov zomiera počas prvých piatich rokov od začiatku vzniku ochorenia.</strong>',
lt28: 'Obzvlášť hrozná je tá skutočnosť, že mnohí ľudia ani nepociťujú, že trpia hypertenziou. Odmietajú príležitosť napraviť to a jednoducho odsúdia svoj život.',
lt29: 'Pri takýchto symptómoch môžete zistiť, že trpíte hypertenziou:',
lt30: 'Bolesť hlavy',
lt31: 'Častejšie búšenie srdca',
lt32: 'Čierne škvrny v očiach',
lt33: 'Apatia, podráždenosť, ospalosť',
lt34: 'Zniženie zraku',
lt35: ' Potenie',
lt36: ' Chronická únava',
lt37: 'Opuch tváre',
lt38: 'Stuhnutosť prstov',
lt39: 'Tlakové skoky',
lt40: 'Aspoň jeden s týchto príznakov  by vás musel donútiť sa zamyslieť. Аk<strong>ich je viac, nie pochybujte- mate hypertenziu.</strong> Mimochodom, podľa štatistík ministerstva zdravotníctva, 67% hypertonikov vôbec nemaju podozrenie, že sú chorí.',
lt41: '<i>Žurnalista</i>: " Povedali ste, že ľudia nechcú zlepšiť situáciu, ale ako sa dá ju napraviť? Ako bojovať proti tejto chorobe?"',
lt42: '<strong>Janková M.:</strong> Najprv musíte pochopiť, že stojí za to vzdať sa masla vašich zlých návykov, najmä fajčenia a alkoholu. To len zhoršuje situáciu s arteriálnym tlakom. Navyše, ak to preženete s liekmy a dostanete prudký pokles tlaku, môže to spôsobiť extrémne negatívnu reakciu organizmu až na ten istý srdcový záchvat. To nehovorím o tom, že tabletky vytvárajú mimoriadne vysoké zaťaženie pečene.',
lt43: 'V skutočnosti,teraz,<strong>jediný liek, ktorý oficiálne odporúča ministerstvo zdravotníctva pre liečbu hypertenzie,a ktory použivajú kardiologovia<a href="" target="_blank">ReCardio</a>,ktorý teraz predavaju so<span style="color:red;">zlavou 50%</span>!</strong>Tvorením tohto prostriedku sa zaoberal tím špecialistov, ktorí úzko spolupracovali s praktizujúcimi kardiológmi. V dôsledku toho sa ukázalo, že je to jedinečný prostriedok, ktorý dokaže  zničit príčinu hypertenzie, na rozdiel od všetkých ostatných liekov..',
lt44: '<i>Žurnalista</i>: " Môžete povedať viac o<a href="" target="_blank">ReCardio</a>?"',
lt45: '<strong>Jankova M.:</strong> Hovoriť všeobecne, <strong> liek pôsobí na príčinu ochorenia, vďaka čomu je možné úplne sa zbaviť hypertenzie.</strong>../../../plne odstra_25C5_2588uje pr_25C3_25ADznaky  uz po prv_25C3_25BDch _25C5_25A1iestich hod_25C3_25ADn p0D852D9E14',
lt46: 'Cievny tonus úplne sa obnoví po prvej aplikacii. Popritom<a href="" target="_blank">ReCardio</a> je účinný v akejkoľvek fáze hypertenzie. Liek, samozrejme, prešiel klinickými skúškami. Chcem poznamenať, že účinnosť, čo sa preukázala počas skúšok, je lepšia ako akykoľvek iný prostriedok. Najlepší výsledok pre západné lieky - 20-21% uzdravených. V našom pripade hovorime o 75-77% . U ostatných sa jednoducho stabilizovala situácia. To znamená, že samotná hypertenzia sa zachováva (problém s vaskulárnym tónom). Ale zároveň mate stabilný tlak a cítite sa skvelo .', 
lt47: 'Okrem Slovenska,<a href="" target="_blank">ReCardio</a> bol klinicky testovaný vo Švajčiarsku a Nemecku, ktoré taktiež potvrdili jeho účinnosť. Teraz je obrovský dopyt po tomto prostriedku. Ale<strong>podľa šreciálneho nariadenia predáva sa len v rámci našej krajiny </strong>, čo súvisí s nízkymi objemami výroby, ktoré nie sú pripravení na túto úroveň dopytu.', 
lt48: ' Vykonali sme aj prieskum, ktorý prekonal naše očakávania.',
lt49: 'Dotaznik:<span> ako sa zbaviť hypertenzie??</span>',
lt50: ' Lekárske prípravky:',
lt52: 'Prípravok ReCardio:',
lt54: 'Tradičná medicína:',
lt56: 'Hľadám riešenie:',
lt58: 'Nemyslím si, že je to možné:', 
lt60: '<i>Žurnalista</i>: "Kde môžem kúpiť<a href="" target="_blank">ReCardio</a>? Myslím, že naši čitatelia budú mať záujem. A čo ste hovorili  o 50 % zľavu?"',
lt61: '<strong> Janková M:</strong>V súčasnosti sa liek vyrába v malých dávkach, hoci výrobca už vytvára nové kapacity, ktoré niekoľkokrát zvýšia objem.',
lt62: ' Ale na začiatku tohto roka výrobca dostal finančné prostriedky na rozšírenie výroby. A spustil predaj rovno na <a href="" target="_blank"> špeciálnej webovej stránke </a> pre pacientov, kde je môžné objednať si <a href="" target="_blank">ReCardio</a> on-line. Postačí nechať svoje meno a telefónne číslo, Potom Vás budu kontaktovať aby ste si upresnilí detaily, zároveň odpovedia na všetký vaše otázky. Dodávka je poštou. Platíte len po obdržaní a kontrole.<strong> Systém je úplne jednoduchý, čo je vhodné pre tých, ktorí si objednať on-line prvýkrát.</strong> Sám som to skontroloval pred pár dňami a nenašiel som žiadne nedostatky. Na stránke dokonca zobrazuje zvyšky lieku v najbližšom sklade pri vas.', 
lt64: 'Účel programu: Pomáhať ľuďom s vysokým krvným tlakom, ktorý nielen zavadza ľuďom žiť, ale aj ohrozuje život. Sme veľmi hrdí, že sa nám podarilo spustiť takýto projekt v našej krajine! V žiadnej krajine na svete neexistuje taká vec!', 
lt66: '<i> Korešpondent</i>: "Chceli by ste niečo odkazať čitateľom skôr než dôjdeme k záveru?"', 
lt67: '<strong>Jankova M.:</strong> Jediná vec, ktorú by som chcel povedať - nebuďte ľahostajní k vlastnému životu. Hypertenzia je mimoriadne rozširená choroba. A pripomínam, že <strong> 67% hypertenzných pacientov si ani neuvedomujú, že sú chorí </strong>. Musite úznať, je škoda zomrieť na chorobu, o ktorej ste ani nevedeli. Skontrolujte, či nemáte príznaky a ak sú nejake symptómy, obráťte sa na špecialistu alebo len použite <a href="" target="_blank">ReCardio</a>. Vďaka práci jeho tvorcov, teraz máte prístup k unikátnemu prostriedku, ktorá už nie je nikde na svete. To je jediný spôsob, ako stabilizovať tlak a liečiť hypertenziu, oficiálne odporúčaný lekármi.<strong> Využite svoju šancu namiesto poslušného čakania na smrť z infarktu.</strong>', 
lt69: '194 komentárov dnes', 
lt70: 'Zuzana Smoradková', 
lt71: 'Podarilo sa mi dostať prostriedok so uľavou! Takže neváhajte si objednať, určite si pamätam že v Bratislave, Košiciach, Prešove a niektorých ďalších mestá už spustili tento program.<br> Prvýkrát som počul o tomto lieku pred tromi mesiacmi a okamžite som objednal. Problemy s krvným tlakom boli hrozne. A tu po prvom dni aplikacie liaku tlak sa mi stabilizoval. Užívam si život.', 
lt72: 'Pred 6 hodinami', 
lt73: 'Anton Čižma', 
lt74: 'Tiež som to kúpoval, pre svojú starku, vždy mala problémy s tlakom. Ona sama nedostane sa pravdepodobne tak skoro ku tomu, aby si objednala niečo cez internet , aj keď telefonický. Preto som to urobil sám. Pomohlo to na všetkých 100%, aj keď problémy boli dlhodobé a globálne, brala lieky už dlhé roky.', 
lt75: 'pred 6 hodinami',
lt76: 'Julia Eštoková',
lt77: 'Čítala som v nejakom lekárskom časopise o tomto lieku....',
lt78: 'pred 6 hodinami',
lt79: 'Lenka Mičudová',
lt80: 'Tiež som niekde o tomto počula. Asi niekto z priateľov si niečo objednaval. Aj ja mám problemy s tlakom už druhý rok . Asi si objednám, vyskušam to, este aj za taku cenu))) , s 50% zľavou.',
lt81: 'pred 6 hodinami',
lt82: 'Marta Bodnárová',
lt83: 'Tiez som si objednala. Slubili, že do konca tyždňa doručia. Čakam))).<center></center>',
lt84: 'pred 6 hodinami',
lt85: 'Tinka Matuškovičová',
lt86: 'Nedávno som čítala článok o hypertenzií.  Spomínali tam aj o tomto lieku. Že je to najlepší liek na liečenie hypertenzie.',
lt87: 'pred 6 hodinami',
lt88: 'Аnka Timková',
lt89: 'Práve som si objednala. U nás v rodine absolútne každa žena má problém s tlakom. Najčastejšie zomierajú na infarkt.',
lt90: 'pred 6 hodinami',
lt91: 'Viktoria Hocková',
lt92: 'Včera som požerala program v<a href="" target="_blank">ReCardio</a>televizii . Tam sa rozprávali o tom, aký dobrý liek na hypertenziu vytvorilii doktori.',
lt93: 'pred 6 hodinami',
lt94: 'Katarina Michalková',
lt95: 'A to nie je podvod? Prečo sa to predáva na internete?',
lt96: 'pred 5 hodinami',
lt97: 'Julia',
lt98: 'Katarina, čítali ste vôbec text? Predavaju cez internet, pretože objem výroby je malý. A viete, ako naše lekárne navyšuju cenu. A tu mate moznosť kupiť priamo u vyrobcu. Platba až po prijatí, čiže mate možnosť skontrolovať tovar. A na internete teraz predávajú všetko - od oblečenia až po televízory a nábytok...',
lt99: 'pred 5 hodinami',
lt100: 'Katarina Michalková',
lt101: 'Nevšimla som si na stránke nič o platbe po prijatí. Objednavam)..',
lt102: 'pred 5 hodinami',
lt103: 'Ivana Polaková',
lt104: 'Pred dvoma mesiacmi so objednala tento liek pre moju sestru. Vedeli by ste, ako mi neskôr ďakovala, že som objednala tento liek.',
lt105: 'pred 5 hodinami',
lt106: 'Viera Sokolová',
lt107: 'Nemam žiadne problemy s  tlakom, ale moja matka neustále trpí. Objednam a dúfam, že pomože.',
lt108: 'pred 4 hodinami',
lt109: 'Olga Senková',
lt110: 'Prečítala som recenzie, a rozhodla som sa objednať tento prostriedok.',
lt111: 'pred 4 hodinami',
lt112: 'Martina Polaková',
lt113: 'Už som si objednala, вроде ничего сложного. Получила через неделю<a href="" target="_blank">ReCardio</a>по почте. Начала пробовать эту методику. Позже отпишусь о результатах. Спасибо!',
lt114: 'pred 4 hodinami',
lt115: 'Natalia Polaková',
lt116: 'Už  to mam vyskušane) A chcem sa vam pochvaliť.Je to ZAZRAK!  Pouzivala som tento liek dva mesiace, a teraz som uplne zdrava! Citim sa o 20 rokov mladsia. Ďakujem ReCardio.',
lt117: 'pred 4 hodinami',
lt118: 'Maťa Ond´aková ',
lt119: 'Ahojte všetci! Tento prostriedok mi naozaj pomohol! Zlepšenia sa začali okamžite. Tiež som mala problémy s tlakom. Aj nálada sa zlepšila, a opäť  túžim žiť a užívať si život! ReCardio použivam dva mesiace.. Ďakujem veľmi pekne!!',
lt120: 'pred 4 hodinami',
lt121: 'Viktor Šimon',
lt122: 'Aj ja som si objednal. Od zajtra bude všetko inak! <a href="" target="_blank"> ReCardio </a> som dostal o 7 dní. Pokračujem v terapii. Metoda je samozrejme jedinečná. Pravda je že "všetko genialné je jednoduché!".',
lt123: 'pred 4 hodinami',
lt124: 'Anna Siváková',
lt125: 'Celý život som trpel hypertenziou, dúfam, že tento prostriedok pomôže. Vyskušam to!!',
lt126: 'pred 3 hodinami',
lt127: 'Lenka',
lt128: 'Náhodne som narazila na tento článok. A čo tu vidim!! Reklamujú naš<a href="" target="_blank">ReCardio</a>! Nemyslim že môj, myslim to tak, že tiež som ho kúpovala. On nevie, že tu píšem, ale aj tak sa podelim s Vami. Veď je to aj moja radosť, skôr, dokonca moje šťastie! V skratke, tiež som čítala recenzie sledovala, ako a čo a tak aj objednala tento prostriedok. A môj manžel už bol zúfalý. Bral tablety, chodil na masaže, kvôli čomu mal žaludočné problemy, rozhodovali sme sa čo budeme robiť ďalej. Začali sme použivať ! A hura! Žiadne problemy, znovu je s rodinou, opäť veselý a aktívny!', 
lt129: 'pred 3 hodinami',
lt130: 'Anna Kováčová',
lt131: 'Vyliečil som hypertenziu za 2 mesiace. Som veľmi prekvapená!!',
lt132: 'pred 3 hodinami',
lt133: 'Julia Medved´ová',
lt134: 'Ťažko sa tomu verí... ale toľko ľudí tvrdí, že to funguje, malo by to fungovať. Začnem zajtra!',
lt135: 'pred 3 hodinami',
lt136: 'Matuš Benko',
lt137: 'Ďakujem, pomohlo mi to! Situácia bola vážna, ale teraž som uplňe zdravý!',
lt138: 'pred 3 hodinami',
lt139: 'Jan Konečný', 
lt140: ' Chcem sa rýchlo zbaviť hypertenzie, a hlavne nejako jednoducho a bezbolestné. Myskim si, že je to akurat pre mňa. Ďakujem pekne za informaciu, ešte dnes si to objednam, dúfam, že nie je všetko vypredané.', 
lt141: 'Pred 2 hodinamy', 
lt142: 'Lea Zbednická', 
lt143: 'Manžel má hypertenziu, ku lekarom chodime spolu. Milujem ho, život by som zaňho dala, ale nemôžem pomôcť zmierniť jeho utrpenie. Dobre, že ste sa objavili so svojím príbehom, je to nádej pre nás. Skusili sme už všetko.', 
lt144: 'pred 2 hodinami',
lt145: 'Michal Guman',
lt146: 'Ľudia, nechapem, čo mate za problemy? Možno by ste nemali sedieť toľko na fóre, sťažujúc sa, že máte problémy, ale okamžite konať? Strávil som celý svoj čas v prospech, najprv som si preštudoval všetky informácie o prostriedku, prečítal recenzie, a potom hneď objednal. Začal som sa poriadne liečiť a teraz je môj organizmus v poriadku! Sám som sa postavil na nohy!', 
lt147: 'pred 2 hodinami',
lt148: 'Branislav Motyl',
lt149: 'Máš pravdu. Niekedy sa oplati ignorovať modernu medicínu - telo sa uzdravuje a obnovuje sa v mnohých prípadoch. A ReCardio - pomáha, smeruje na správnu cestu.',
lt150: 'pred 2 hodinami',
lt151: 'Αртем Κудрявцев',
lt152: 'Dobrý deň. ReCardio mi pomohol vyliečiť  hypertenziu. Dobre uvolňuje, všimol som si zásadné zlepšenie. Budem naďalej uživať liek...zachránil ma od operácie. Verím, že telo dokáže zvládnuť každú chorobu!',
lt153: 'pred 2 hodinami',
lt154: 'Vladimir Vojtaško',
lt155: 'Práve v poslednej dobe som sa chcel opäť obrátiť na lekárov, už som sa rozhodol že pojdem ku chirurgovi, pripravil som si peknu sumu,;ale teraz ju nepotrebujem! 2 mesiace - a ja som zdravý. Takže, ľudia, nevymyšľajte, žiadne tablety  nepomôžu! Iba tento prírodný prostriedok, nepoznam ziadne iné metódy a už ani nechcem vedieť',
lt156: 'pred 2 hodinami',
lt157: 'Peter kollar',
lt158: 'Skupý plati dvakrat. Našiel som informácie o<a href="" target="_blank">ReCardio</a>, ale nekupil som si.  Rozhodol som sa kúpiť na internete. Natrafil som na nejaky nekvalitny fejk! Nakoniec som objednal už  na oficiálnej webovej stránke. ReCardio doručili okamžite, čo je pre našu poštu mimoriadne zvláštne. Použival som ho 2 mesiace! A teraz sa vobec nestažujem na svoje zdravie. Ďakujem!',
lt159: 'pred hodinou',
lt160: 'Matuš Lukač',
lt161: 'Kúpil som tento liek. Výsledok ma šokoval. Po 2 dňoch neskutočna úľava! Cítim sa výborne už druhý mesiac!',
lt162: 'pred hodinou',
lt163: 'Ivka Antušová',
lt164: 'ReCardio skutočne pomáha proti hypertenzii. A pri tom veľmi rychlo!',
lt165: 'pred hodinou',
lt166: 'Šimon Huda',
lt167: 'Používam ho len prvý ďeň. A tlak sa normalizoval už teraz! Výrobca plní prísľub, to ma teši..',
lt168: 'pred hodinou',
lt169: 'Patrik Krajňak',
lt170: 'O tomto lieku som veľa počul od priateľov a teraz som si to objednal sám. Po 5 dňoch použitia  citim sa oveľa lepšie! Vďaka!',
lt171: 'pred hodinou',
lt172: 'Martin Harničar',
lt173: 'Momentálne tento výrobok je najlepší. Každý ho odporúča! Výborná vec.',
lt174: 'pred hodinou',
lt175: 'Ľubomíra Durkačová',
lt176: 'Všetci už vedia o tomto prostriedku. A tie čo nevedia,  asi nepotrebuju vedieť.',
lt177: 'pred 48 minútami',
lt178: 'Valer Vranko',
lt179: 'Tento prostriedok je už dávno známý. Neviem, čo je na ňom mimoriadne, ale on naozaj hypertenziu!.',
lt180: 'pred 35 minútami',
lt181: 'Stano Tomčík',
lt182: 'Dobrý deň. Veľmi zaujímavé informácie. Som skeptický, ale napriek tomu vyskušam. Treba škusit všetko)))',
lt183: 'pred 22 minútami',
lt184: 'Kubo kapral',
lt185: 'Ako vždy, k nám sa všetko dostane neskoro....<a href="" target="_blank">ReCardio</a> je už davno znamy...',
lt186: 'Pred 5 minútami'
};


function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };
