var new_lang = {
lt1: 'ALCOBARRIER – un nouveau outil efficace pour la lutte contre l`alcoolisme',
lt2: 'ALCOBARRIER - <br><span>Dit<span>&laquo;Non&raquo;</span> à l`alcoolisme </span>',
lt3: 'L`ancien prix',
lt4: 'Commander pour',
lt5: 'ALCOBARRIER – un nouveau outil efficace pour la lute contre l`alcoolisme ',
lt6: 'Diminue le besoin d`alcool',
lt7: 'Apaise le système nerveux',
lt8: 'Améliore l`état mental',
lt9: 'Répare les cellules du foie',
lt10: 'Élimine les toxines du corps',
lt11: 'ALCOBARRIER – un outil efficace, qui élimine les toxines du corps et finit l’addiction à l`alcool. L`acide succinique et le fibregum qui sont dans la composition ХХа dérivent les toxines de l`organisme après l`ingestion de l’alcool. Ils ont aussi une action fortifiant.',
lt12: 'ALCOBARRIER <br> <span> complexe de composants de haute activité </span>',
lt13: '<span> Élimine <br> les toxines </span>',
lt14: 'Fibregum ',
lt15: 'La résine d`acacia favorise l`élimination des toxines et la normalisation du tractus gastro-intestinal',
lt16: 'Désamorce <br> le besoin',
lt17: 'L`extrait d`artichaut ',
lt18: 'Diminue le besoin d`alcool et a un effet hypertoprotecteur et de désintoxication',
lt19: 'Apaise <br> le système nerveux',
lt20: 'L`extrait de l`agripaume ',
lt21: 'Apaise <br> le système nerveux, aide à soulager l`intoxication alcoolique',
lt22: 'ALCOBARRIER <br> <span> complexe de composants de haute activité ',
lt23: 'élimine <br> les toxines ',
lt24: 'Fibregum ',
lt25: 'La résine d`acacia favorise l`élimination des toxines et la normalisation du tractus gastro-intestinal',
lt26: 'Diminue <br> le besoin',
lt27: 'L`extrait de l`agripaume',
lt28: 'Diminue le besoin d`alcool et a un effet hypertoprotecteur et de désintoxication',
lt29: 'Apaise <br> le système nerveux ',
lt30: 'L`extrait de l`agripaume',
lt31: 'Apaise le système nerveux, aide à soulager l`intoxication alcoolique',
lt32: 'ALCOBARRIER <br> <span> complexe de composants de haute activité </span>',
lt33: 'Élimine <br> les toxines du corps',
lt34: 'L-CARNITINE',
lt35: 'La résine d`acacia favorise l`élimination des toxines et la normalisation du tractus gastro-intestinal',
lt36: 'Diminue <br> le besoin',
lt37: 'LE THÉ VERT',
lt38: 'Diminue le besoin d`alcool et a un effet hypertoprotecteur et de désintoxication',
lt39: 'Apaise <br> le système nerveux',
lt40: 'L-ORNITHINE',
lt41: 'Apaise le système nerveux, aide à soulager l`intoxication alcoolique',
lt42: 'L`acide succinique',
lt44: 'réduit les effets toxiques de l`alcool, enlève la gueule de bois, améliore le fonctionnement du cœur ',
lt44: 'Vitamine B6',
lt45: 'améliore l`état mental, aide de sortir de l’addiction à l`alcool',
lt46: 'L`acide succinique',
lt47: 'réduit les effets toxiques de l`alcool, enlève la gueule de bois, améliore le fonctionnement du cœur',
lt48: 'Vitamine B6',
lt49: 'améliore l`état mental, aide de sortir de l’addiction à l`alcool',
lt50: 'ZINC ',
lt51: 'neutralise l`effet de l`éthanol, réduit les effets toxiques de l`alcool, élimine la gueule de bois',
lt52: 'LES VITAMINES DU GROUPE B',
lt53: 'contribue à l`amélioration de la santé mentale, soulage le besoin de l`alcool',
lt54: 'ALCOBARRIER',
lt55: 'est testé',
lt56: 'dans la vie réelle',
lt57: 'En 2014, on a fait une recherche, au cours de laquelle 1000 volontaires l`alcoolique prenaient ALCOBARRIER 2 fois par jour dans un mois.',
lt58: 'Selon les résultats de la recherche 25% de volontaires ont noté une grande réduction de l’addiction à l`alcool et l`amélioration de l`état de l`organisme. Donc 75% des alcooliques sont arrêtés de boire complètement! Selon les résultats de l`enquête on a observé une amélioration significative de la santé du foie, de l`état cardio-vasculaire et le système nerveux',
lt59: 'La boisson a montré son efficacité chez 100% des volontaires qui ont n’importe quelle gravité de la maladie et durée de la consummation de l`alcool.',
lt60: 'Je ne trouvais pas un alcoolique moi-même mausa j’aimé boire de l’alcool. Cependant, de plus en plus j’ai commencé à remarquer que la gueule de bois est devenue plus fortte, j’ai eu mal au foie, l`alcool est devenu tirer de plus en plus forte. J’ai réalisé que c’était le temps de m`arrêter.J’ai décidé de boire «ALCOBARRIER» et tout de suit j’ai immédiatement commencé à me sentir mieux! Après une semaine et l’addiction à l`alcool est disparue, et en ce moment je ne bois pas tout à fait!',
lt61: 'Antoine, 40 ans',
lt62: 'Auparavant, mon mari ne buvait pas si souvent, mais puis ça est devenu une addiction. Cependant il ne voulait pas admettre qu`il était malade. Mon amie m`a conseillé d`essayer ALCOBARRIER. J`ai commencé à ajouter ALCOBARRIER dans ses boissons. Je pouvais le faire tranquillement grâce à l’absence de goût de ХХа. Après quelque temps le besoin de l`alcool a disparu.',
lt63: 'Camille, 53 ans',
lt64: 'Mon père avait la plus forte addiction à l`alcool, et pas seulement après la «célébration» on a dû aller aux médecins, qu`ils le retournaient à son état normal. Ma mère et moi nous avons commandé ALCOBARRIER et  commencé à ajouter à ses boissons sans le faire savoir. Maintenant, le père ne boit pas du tout trois mois, et seulment moi et ma mère nous savons pourquoi. Si vous avez aussi ce terrible problème dans votre famille, utilisez le ALCOBARRIER!',
lt65: 'Louis, 35 ans',
lt66: 'Les toxicologues recommandent ALCOBARRIER',
lt67: '«Je recommande ALCOBARRIER à tous ses patients - quelqu`un qui sort de l’acoolisme, et quelqu`un qui boit un peu, mais il veut s’arrêter. L`outil soulage non seulement les besoins psychologiques de l`alcool, mais restaure l`organisme et produit un effet positif sur le foie, le cœur, les reins, le système nerveux. Le traitement avec ALCOBARRIER aide mes patients à cesser de boire et de revenir rapidement à une pleine vie»',
lt68: 'Paul Babinet, le toxicologue de la catégorie superieure ',
lt69: 'Rabais <br> -50%',
lt70: 'L`ancien prix ',
lt71: 'Jusqu`à la fin de l’action <br> il vous reste',
lt72: 'Commander',
lt73: 'Le produit est certifié, la composition, la méthode et les indications d`emploi sont indiquées dans les instructions sur l`emballage. Le paiement est dû à la réception (paiement à la livraison).',
lt74: '',
lt75: ''
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};