var new_lang = {

    "lt0": "Episódios",
    "lt1": "O prato",
    "lt2": "Temas<i class=\"icon rebrand-down-arrow-small arrow\" role=\"img\"></i>",
    "lt3": "Menu principal<i class=\"icon rebrand-down-arrow-small arrow\" role=\"img\"></i>",
    "lt4": "Mais<i class=\"icon rebrand-down-arrow-small arrow\" role=\"img\"></i>",
    "lt5": "Na TV<span id=\"station\"> <span class=\"station-default-text\">Check Listings</span>  <span class=\"sw-station\"></span>  <span class=\"sw-time\"></span> </span> <i class=\"icon rebrand-down-arrow-small arrow\" role=\"img\"></i>",
    "lt6": "Veja Oz Live",
    "lt7": "Esteja no programa",
    "lt8": "Obter ingressos",
    "lt9": "Siga Oz",
    "lt10": "Login",
    "lt11": "Meu<br>perfil",
    "lt12": "Assista Oz<span class=\"pink-dbl-slash\">//</span>  <span class=\"station\"> <span class=\"station-default-text\">Check Listings</span>  <span class=\"station-details\" style=\"display: none;\"> <span class=\"sw-affiliate\"></span>  <span class=\"sw-station\"></span>  <span class=\"time sw-time\"></span> </span> </span> ",
    "lt13": "Listagens",
    "lt14": "Esteja no show",
    "lt15": "Obter ingressos",
    "lt16": "Patrocinado por",
    "lt17": "Edição especial: conspiração de farmacêuticos ou incapacidade de médicos no tratamento de prostatite?", 
    "lt18": "Por Ricardo Pereira",
    "lt19": "<span class=\" icon-comments-bubble-wrap\"><i class=\"icon rebrand-comments\" role=\"img\"></i></span> Comentários",
    "lt20": "Um escândalo farmacêutico no continente europeu:",
    "lt21": "Por que os médicos silenciam sobre a alta mortalidade de homens após 45 anos?",
    "lt22": "Hoje responderemos a essa pergunta junto com o Dr. Oz!",
    "lt23": "Segundo as estatísticas médicas, hoje praticamente não há homens acima de 35 anos que não sofram da prostatite. A próstata de um homem está começando a inchar, a próstata do outro homem já está inchada o suficiente para bloquear o trato urinário e tornar-se um problema ao urinar. Mas mesmo neste caso, os homens não correm para a clínica para realizar o tratamento. Por quê? ", 
    "lt24": "É simples. O tratamento da prostatite é um procedimento muito desagradável e caro. Você precisa tomar antibiótico e ir ao urologista para receber uma massagem retal dolorosa. E mesmo que consiga sobreviver a tudo isso, então com 90% de probabilidade de prostatite retornará novamente.",
    "lt25": "Examinamos a situação no campo da proctologia e chegamos a uma conclusão sensacional: nos últimos 6 anos, menos de um por cento dos homens receberam tratamento sem recorrência de prostatite.",
    "lt26": "Para comentar a situação convidamos o principal urologista da União Europeia, professor doutor Pedro Bulhões.",
    "lt27": "<span class=\"text-decoration\">Dr. Oz: </span> Pedro, o que acontecerá se a prostatite não for tratada? É verdade que um tumor cancerígeno pode aparecer na próstata?",
    "lt28": "<span class = \' text-decoration \ '> Pedro Bulhões: </span> Sim, é verdade. A prostatite nunca desaparece por si própria, ela apenas se intensifica com o tempo. Se houver problemas com a micção, significa que as coisas já estão ruins - a próstata está muito inchada e as células cancerígenas podem aparecer a qualquer momento. Se você demorar muito com o tratamento da prostatite, em um ano pode surgir oncologia. No início, o câncer não se faz sentir, as células cancerígenas crescem e somente então um tumor aparece. O câncer de próstata quase não tem tratamento. ",
    "lt29": "<span class = \' text-decoration \ '> Dr. Oz: </span> Quais são as formas realmente úteis de tratar a prostatite?",
    "lt30": "<span class = \' text-decoration \ '> Pedro Bulhões: </span> Francamente, não há nenhuma. Basicamente, a prostatite não é completamente tratada, mas <b> <i> temporariamente </ i > </b> você consegue livrar-se dela. Antibióticos, intervenção cirúrgica, pomadas e soro interrompem o desenvolvimento da doença, sem curá-la completamente. ",
    "lt31": "<span class = \' text-decoration \ '> Dr. Oz: </span> Mais detalhes por favor. Por que está acontecendo assim?",
    "lt32": "<span class = \' text-decoration \ '> Pedro Bulhões: </span> Com a ajuda de antibióticos, as infecções ficam suprimidas, elas não ajudam no combate ao tumor de adenoma de próstata. As recaídas geralmente ocorrem após a cirurgia. Sem falar que é um procedimento extremamente doloroso. Os métodos como soro e pomadas são eficazes apenas como analgésicos; trata-se de um bloqueio temporário dos sintomas que não afeta a redução do tumor. ",
    "lt33": "No entanto, a próstata pode ser curada. É necessário interromper a proliferação (em outras palavras, a divisão das células tumorais) e direcionar o tratamento na restauração da função urogenital. Assim que isso foi revelado, surgiu toda uma classe de medicamentos direcionados a isso",
    "lt34": "<span class = \' text-decoration \ '> Dr. Oz: </span> Eu estou entendendo corretamente que não existem medicamentos nas farmácias que possam remover efetivamente a proliferação?",
    "lt35": "<span class = \' text-decoration \ '> Pedro Bulhões: </span> Sim, você está certo. Não é segredo que farmácias são business. Elas estão interessadas em clientes que irão voltar. Portanto, as farmácias não terão lucro se vender medicamentos que curam uma pessoa de sua doença completamente. Por esse motivo, os medicamentos mais caros das farmácias destinam-se apenas a aliviar temporariamente os sintomas. Ou seja, resolver a investigação, não uma causa em si. Portanto, nasceu o mito entre os homens de que a prostatite não pode ser curada para sempre, que ela aparecerá novamente e novamente. ", 
    "lt36": "Além disso, esses medicamentos não apenas 'bombeiam' dinheiro, mas também causam vários efeitos colaterais fortes em outros órgãos da pessoa. O que, como resultado, obriga você a ser tratado mais desses efeitos colaterais tarde. E onde procurar o medicamento? Está certo. Na farmácia. Acho que o significado é claro.",
    "lt37": "<span class = \' text-decoration \ '> Dr. Oz: </span> Que imagem horrível. Você poderia falar sobre remédios eficazes? \" ",
    "lt38": "<span class = \' text-decoration \ '> Pedro Bulhões: </span> É claro. No final de 2019, realizamos ensaios clínicos de 15 medicamentos disponíveis hoje. O medicamento mais eficaz, é chamado <a href=\"\"> ProstEro </a>. ",
    "lt39": "<span class = \' text-decoration \ '> Dr. Oz: </span> Conte mais sobre este medicamento.",
    "lt40": "<span class = \' text-decoration \ '> Pedro Bulhões: </span> ProstEro é um medicamento destinado a destruir um tumor, é um conjunto das substâncias mais úteis para o corpo masculino: ameixa africana, saw palmetto, zinco e vitamina E.",
    "lt41": "Vou contar uma história curta. Um dia eu me deparei com um estudo de médicos franceses que descobriram uma tribo africana nas regiões montanhosas dos Camarões. Depois que um especialista conseguiu examinar a maioria dos homens da tribo, descobriu-se que<b>nenhum deles não tinha prostatite</b>. Mais tarde, verificou-se que era a ameixa africana que a tribo usava como principal componente da nutrição que se tornou um fator principal na manutenção de sua saúde. Durante os estudos das propriedades da ameixa africana, verificou-se que o extrato dela fica ativo no tratamento da prostatite e adenoma de próstata. ",
    "lt42": "<a href=\"\"> ProstEro </a> se difere de muitos outros medicamentos, pois nele foi utilizada uma nova tecnologia de extração (chamada extração a frio), que permite salvar o máximo de substâncias úteis biologicamente ativas da planta. Portanto, ele possui uma eficiência tão alta. Devido ao fato de ProstEro ser constituído exclusivamente por componentes vegetais e não conter química, ele pode ser tomado sem receita médica, para a cura caseira de próstata. ",
    "lt43": "<span class = \' text-decoration \ '> Dr. Oz: </span> Existe alguma chance de que esse medicamento ainda apareça nas farmácias?",
    "lt44": "<span class = \' text-decoration \ '> Pedro Bulhões: </span> Bom, o medicamento não está à venda, mas é distribuído por um preço realmente simbólico devido à desestabilização geral da qualidade dos medicamentos no mercado farmacêutico. Isso é suficiente para pagar sua produção. A principal renda é a importação. Esse é o principal conflito com as redes de farmácias. Elas querem ganhar dinheiro com pessoas doentes, tirando o máximo proveito delas. Remédios antigos e ineficazes são ideais para isso. Enquanto o remédio não apenas resolve o problema para sempre, mas e é distribuído ao custo de produção. ",
    "lt45": "<span class = \' text-decoration \ '> Dr. Oz: </span> Por que o preço é tão baixo?",
    "lt46": "<span class = \' text-decoration \ '> Pedro Bulhões: </span> O fabricante é parceiro do programa social 'Ajude-se'. Nesse programa, você pode comprar oficialmente o medicamento pelo preço de custo.",
    "lt47": "Especialistas criaram um <a href=\"\"> site especial </a> onde você pode deixar um pedido para \"ProstEro\"e recebê-lo praticamente de graça. Tudo o que você precisa fazer é deixar seu nome e seus dados de contato. Logo após eles entrarão em contato com você para determinar o horário de entrega conveniente para você. Tentamos fazer tudo da maneira mais simples possível para que todos pudessem receber o medicamento, mesmo que ele não tivesse pedido nada on-line antes.",
    "lt48": "<span class=\"text-decoration\">Dr. Oz:</span> Nosso programa será assistido por milhões de homens. Quantas embalagens do medicamento você pode vender a um preço tão baixo? Afinal, milhares de pedidos serão lançados daqui há pouco.",
    "lt49": "<span class =\' text-decoration \ '>Pedro Bulhões: </span> No momento, temos cerca de 5.000 caixas no estoque. Espero que todos tenham o suficiente para o final do programa.",
    "lt50": "<span class =\' text-decoration \ '> Dr. Oz: </span> Nada mal. Infelizmente, nosso programa está acabando, mas espero que tenhamos conseguido passar as informações básicas para nossos cidadãos. Obrigado por conversar sobre um tema tão importante, Pedro. Você tem algo a dizer adeus aos nossos telespectadores? ",
    "lt51": "<span class = \' text-decoration \ '>Pedro Bulhões: </span> Quero chamar a atenção do público que as doenças de próstata estão 'ficando mais jovens', e até uma leve dor periódica e micção frequente é um motivo para prestar atenção ao problema. Você não precisa esperar até que o câncer de próstata apareça e você estará esperando apenas por sua morte. ",
    "lt52": "Link para o site oficial",
    "lt53": "Comentários",
    "lt54": "Damião",
    "lt55": "Eu gosto do programa do Dr. Oz. Eu assisto e entendo que eu não sou o único quem tivesse enfrentado esse problema",
    "lt56": "Camilo",
    "lt57": "Eu já pedi ProstEro. Francamente, após tantos exames, dinheiro que eu gastei e tempo perdido nas consultas médicas eu achei minha salvação. Fiz o curso de tratamento e há seis meses eu nem estou lembrando a prostatite.",
    "lt58": "Alex",
    "lt59": "Minha esposa pediu uma caixa de ProstEro para mim há alguns meses. Eu era cético em relação ao remédio e o tomei apenas para que minha esposa não fique preocupada comigo. Na primeira semana, percebi que era mais fácil para eu urinar e depois de um tempo a ereção ficou recuperada. Eu fiz o curso até o fim e me tornei novinho em folha!",
    "lt60": "Filipe",
    "lt61": "E a entrega demora muito tempo? Não tenho paciência para esperar ..",
    "lt62": "Reinaldo",
    "lt63": "Não, o frete é rápido. Quando eu tentei tudo o que pude, desesperei-me de me recuperar. É uma pena dizer que até conversei com os filhos e os preparei para o caso de eu ter desaparecido... sério, eu até reclamei para o amigo, e ele me aconselhou o ProstEro. Desesperado, eu comprei uma caixa e, literalmente, ao longo do curso de tratamento, me senti muitas vezes melhor. Eu tinha apenas 43 anos e ia morrer de prostatite, era um pesadelo! ",
    "lt64": "Wilson",
    "lt65": "Gostaria de encomendar uma caixa. Será que tem efeitos colaterais?",
    "lt66": "Vagner",
    "lt67": "Não, não tem efeitos colaterais. Pelo que eu entendi, nem deveria ter, pois não há nada químico na composição.",
    "lt68": "Marcos",
    "lt69": "Sim, o ProstEro também me ajudou! Lembro-me de que cheguei a me consultar com um médico caro já com muitos exames, comecei a falar sobre a minha prostatite e, mesmo sem olhar para mim, ele pegou o remédio da caixa, deu para mim e mandou pagar a consulta. Então eu fiquei bravo, tipo o que aconteceu, cheguei ao médico e ele nem me ouviu! E então comecei a tomar ProstEro e entendi o médico: mil pessoas o procuram com sintomas semelhantes, para que ouvi-las se é possível resolver o problema bem rapidinho",
    "lt70": "Nelson",
    "lt71": "Muito obrigado doutor. Me ajudou muito.",
    "lt72": "Alexandre",
    "lt73": "Estou aconselhando a todos. Eu também não acreditava  no ProstEro, mas depois eu fiquei convencido que ele ajudou melhor do que todos os pomadas e comprimidos. Estou aguardando a próximo episódio do Doctor Oz!",
    "lt74": "#Novo <span class=\"new-now-content__title-highlight\">Agora</span> ",
    "lt75": "Tickets",
    "lt76": "Giveaways",
    "lt77": "Canto dos medicos",
    "lt78": "Contato",
    "lt79": "Anuncie",
    "lt80": "Pressione",
    "lt81": "HealthCorps®",
    "lt82": "Perguntas frequentes",
    "lt83": "Termos",
    "lt84": "DoctorOz.com",
    "lt85": "AskMD",
    "lt86": "Sharecare",
    "lt87": "Este site é apenas para fins informativos e de entretenimento e não substitui aconselhamento médico, diagnóstico ou tratamento. | © 2020 Oz Media LLC, Todos os direitos reservados | <a> Termos </a> | <a> Privacidade </a> "
    
};
function Translater () {
 for (class_name in new_lang) {
 var elements = document.getElementsByClassName(class_name);
 if (elements.length) {
 for (key in elements) {
 elements[key].innerHTML = new_lang[class_name];
 }
 }
 }
 };