var new_lang = {
lt1: 'Arricchirsi e non ubriacarsi : papay1000',
lt2: 'LiveJournal',
lt3: 'Rivista AlcoBarrier',
lt4: 'Negozio',
lt5: 'aiuto',
lt6: 'Entrare',
lt7: 'REGISTRAZIONE',
lt8: 'Italiano(it)',
lt9: '11mo posto nelle classifiche Italiane',
lt10: 'Oppure connettiti con il tuo account:',
lt11: 'Nome utente:',
lt12: 'Scrive papay1000',
lt13: '3 giorni fa',
lt14: 'Arricchirsi e non ubriacarsi',
lt15: 'I soldi non cadono dal cielo,per guadagnare qualcosa, bisogna lavorare giorno e notte, e l’unica sacrosanta verità. Volete soldi? Chinatevi per bene e scrivete fino a che non si fa buio!',
lt16: 'Io ho molti soldi, ma mentre me li sono guadagnati, per poco non mi sono ammazzato di alchool. Quando dirigi un’azienda, quando pensi a tutto da solo e rispondi di ogni cosa, la pressione è una presenza costante. Quelli che pensano che il business in proprio è una cosa facile, sono dei cretini. Per via del lavoro quotidiano , piano piano si inizia ad uscire di testa. Per rilassare il cervello in qualche modo ho iniziato a bevicchiare. Sei seduto la serva davanti al pc, un bicchierino e sembra che la testa si riposi. In maniera veloce senza accorgermene è diventata un’abitudine, a breve non riuscivo più a immaginarmi una serata senza bere. Dopo mi sono accorto che avrei bevuto volentieri anche di giorno se avessi potuto. Ma nono potevo.  <b>Adesso ho capito, che stavo diventando un alcolizzato.</b> Velocemente ed improvvisamente si è svegliato il desiderio di andare per club eccetera. Non sono capace di bere, mi ubriaco alla follia, se devo fare festa lo faccio per davvero. Ecco come vivevo. Una volta, in una di queste feste, se non sbaglio era Capodanno, mi sono sentito male. Il cuore ha iniziato a soffrire, non riuscivo a respirare, avevo un dolore tremendo al fianco destro. Mi immagino come potevo apparire visto che i miei amici hanno chiamato subito l’ambulanza...',
lt17: 'Sono sopravvissuto. In ospedale mi hanno fatto le analisi, mi hanno visitato, controllato <b>ed ecco la diagnosi. Grave lesione del fegato, ad un passo dalla cirrosi epatica.</b> Bella notizia, a 35 anni! Ad essere sinceri mi sono messo paura. E’ venuto fuori che non è poi così semplice, è diventata una dipendenza. Al minimo problema volevo bere. Il corpo ne ha bisogno, la testa fa male, non sono riuscito a smettere di bere da solo. Ho pensato, che diamine, vado dal dal narcologo! Il narcologo mi ha dato un preparato. Non è la “ ampolla della morte”, semplicemente quando l’alchool ti finisce in corpo, ti senti così male che vuoi morire, dolori atroci. Peggio di tutto, non potevo fare a meno di bere, VOLEVO BERE DI CONTINUO. Dopo che ho bevuto la seconda volta che ho bevuto mi sono sentito morire. Come se la testa stesse per esplodere e la testa per fermarsi. Sono andato a chiedere che mi togliesse questo preparato dal corpo. Un essere inutile, mi guardavo e vedevo un essere inutile. Una pezza, una  pezza inutile che non riesce a gestire il proprio corpo, un pezzo di carne senza uno scopo. Mi odiavo per la mia mancanza di forza, ma non potevo fare nulla.<b>Stavo distruggendomi il corpo e non potevo fermarmi. Situazione tragica. Non so come sarebbe potuta finire, e ad essere sincero non voglio pensarci nemmeno.',
lt18: 'Un amico di mio zio (narcologo) mi ha consigliato di assumere delle gocce di  <b>AlcoBarrier</b>, per salvare il fegato. Ride, dice per lo meno non muori! Molto divertente. Ho deciso di provarci ad assumerle. Non ho smesso di bere, ma in un paio di settimane ho iniziato a sentirmi meglio. Sono diventato più tranquillo, il buon umore finalmente è comparso, le occhiaie hanno iniziato a scomparire. <b>La cosa più interessante è che ho iniziato a voler bere di meno, e quel leggero desiderio che avevo, beh, riuscivo a controllarlo. </b> E’ una sensazione meravigliosa, veder e sentire come il tuo organismo si libera sotto i tuoi occhi da questa schifezza. Che lo stava uccidendo! Ho iniziato a sentirmi fiero, io posso, non sono un essere inutile, ho la forza di volontà! In un mese e mezzo mi dava fastidio per fino l’odore di alchool. Mi è passato perfino il desiderio di provare l’ebbrezza da alchool. I giorni sprecati a bere non mi li avrebbe ridati nessuno, l’ho capito alla fine. Mi sono liberato. L’amico di mio zio poi mi ha confessato, mi aveva imbrogliato.  <br> <b>le gocce <a href="" target="_blank" class="underline">AlcoBarrier</a> sono un forte preparato contro l’alcolismo e la dipendenza.</b> Ma io senza offesa lo ho ringraziato per il grandissimo aiuto che mi ha dato. ',
lt19: 'Adesso non ‘ che sono diventato astemio, ogni tanto bevicchio ma senza esagerare, solo se di buon umore con gli amici. Non ho dipendenza. Ho scoperto che ci sono altri modi per liberarsi dallo stress: sporto, sesso, passeggiate, cose a cui prima non avrei mai pensato. Inoltre mi sono accorto che sono diventato più tranquillo, ho una sorta di equilibrio dentro, e questa cosa mi affascina. Non ho problemi di nervi e dormo come un bambino. ',
lt20: 'Questa è la mia storia. Per la mia debolezza e per la mia stupidità ho pagato con la salute. Spero per voi sia più facile, ma in ogni caso, per ricevere qualcosa bisogna prima dare qualcos’altro. Buona fortuna!',
lt21: 'Iscriversi alle news del blog',
lt22: 'Segnalibri:',
lt23: 'alcolismo',
lt24: 'smettere di bere',
lt25: '442 commenti',
lt26: 'MIchele42',
lt27: '3 giorni fa',
lt28: 'Molti alcolisti non ammettono di essere dipendenti, pensano di poter smettere in qualsiasi momento, ma si sbagliano. Serve sbatterci la testa per capire cosa si rischia e smettere, o fare un ciclo di cura.',
lt29: 'RISPONDERE',
lt30: 'AlessandroFray',
lt31: '3 giorni fa',
lt32: 'Dove ha comprato AlcoBarrier l’autore? Non lo riesco a trovare.',
lt33: 'papay1000',
lt34: '3 giorni fa',
lt35: 'Compratelo solo sul <a href="" target="_blank" class="underline"><b>sito ufficiale</b></a>, oppure vi ritrovate con un falso.',
lt36: 'Marco de Pietra',
lt37: '3 giorni fa',
lt38: 'Eh si… tutti vogliono la botte piena e la moglie ubriaca. Cosa non si fa per non lavorare...',
lt39: 'mr.amico',
lt40: '3 giorni fa',
lt41: 'Si può pensare che se lavori giorno e notte come un schiavo non è un bene. Ci lasci la salute e non ti riempi nemmeno le tasche. Nel nostro paese si può solo rubare… Non tutti sono capaci di buttarsi nel business, serve intelligenza e non poca.',
lt42: 'Giulio Bassi',
lt43: '2 giorni fa',
lt44: 'AlcoBarrier ha salvato me e la mia famiglia, ci ha tirato fuori dalla fossa! Ho bevuto senza moderazione per 10 anni, ho capito che cosa stavo combinando solo quando mia moglie ha preso i bambini e e ne è andata. Sono andato dal narcologo e lui mi ha dato queste gocce. Non potevo neanche immaginare che smettere di bere sarebbe stato così facile! All’inizio ho avuto un po’ di problemi ovviamente, la mano si muoveva come si suol dire verso il bicchiere, ma non ho avuto né crisi d’astinenza, né depressione, niente del genere. Ho resistito un po’ e ho assunto le gocce per un mese. Ora sono 3 anni che non bevo. Grazie al dottore e alle gocce!',
lt45: 'sole67',
lt46: '2 giorni fa',
lt47: 'appena ordinato, attendo',
lt48: 'ficone900',
lt49: '2 giorni fa',
lt50: 'non lo so, secondo mo l’alcolista è quello che sviene per strada, se invece uno lavora può anche bevicchiare, ne ha il diritto visto che non fa niente di male! ',
lt51: 'Giorgietta46',
lt52: '2 giorni fa',
lt53: 'Voglio veramente smettere di bere, ma non ci riesco, non mi basta il carattere. Ho paura di perdere lavoro e famiglia, ho un burrone davanti....',
lt54: 'andreaDAN',
lt55: '2 giorni fa',
lt56: 'AlcoBarrier — è il miglior rimedio contro l’alcolismo che sono riuscito a trovare! L’unico che mi ha aiutato! L’ho bevuto per quasi due mesi, e il risultato si vede! Chi vuole veramente smettere, ve lo raccomando, di meglio non trovate!',
lt57: 'LuMAca_boss',
lt58: '2 giorni fa',
lt59: 'come hai fatto poi a smettere di prendere le gocce? Buon umore eccetera. Non da dipendenza?',
lt60: 'papay1000',
lt61: '2 giorni fa',
lt62: 'Non mi ha dato dipendenza, ho finito il flacone e ho smesso. Non presenta ingredienti che danno dipendenza, guarda sul sito.',
lt63: 'Fede-381',
lt64: '1 giorno fa',
lt65: 'Come si fa a rischiare la cirrosi epatica a 35 anni? Beve da quando ha 5 anni o cosa??',
lt66: 'papay1000',
lt67: '1 giorno fa',
lt68: 'Non ho la cirrosi e non la ho avuta. Ma ci sono andato vicino, mi ha salvato che ho smesso, come ho scritto.',
lt69: 'marlonbrando',
lt70: '1 giorno fa',
lt71: 'La cosa peggiore qui è che non te ne accorgi di come ti ubriachi di continuo pensando che puoi smettere quando vuoi. Io me ne sono accorto dopo che da ubriaco mi sono congelato le gambe e le ho quasi perse. Mi hanno ricoverato in clinica e per poco no mi hanno reso drogato, dandomi morfina per curare la crisi d’astinenza. In parole povere, è stata dura, ma ora ho smesso. Non sapevo di queste gocce, se me le avessero date in tempo e avessero funzionato così bene, sarei infinitamente grato all’autore dell’articolo.',
lt72: 'diavoloMQ',
lt73: '1 giorno fa',
lt74: 'A lungo non ho capito di avere un problema, anche io pensavo di poter smettere in qualsiasi momento. Me ne sono accorto solo quando mi hanno licenziato e sono rimasto senza niente. Adesso mi sto curando, bevo anche io AlcoBarrier, da quasi 3 settimane. Aiuta molto a liberarsi dall’alchool, non ho ne crisi d’astinenza ne depressione, un prodotto favoloso ed economico ',
lt75: 'LAURA MARCHETTI_A',
lt76: '1 giorno fa ',
lt77: 'Mi dica, queste gocce le spediscono ovunque o solo in Italia?',
lt78: 'papay1000',
lt79: '9 ore fa',
lt80: 'Controllate sul sito, penso ci sia la consegna in tutt’Europa',
lt81: 'LuchettoPazzerello5000',
lt82: '5 ore fa',
lt83: 'Tipo un super fico di successo. Amico come facevi a ubriacarti e gestire un’azienda allo stesso tempo?',
lt84: 'papay1000',
lt85: '3 ore fa',
lt86: 'Da schifo, ecco come la gestivo. Difficile da capire o cosa?',
lt87: '4Lauretta-Amichetta1',
lt88: '2 ore fa',
lt89: 'Bel blog! Grazie! Qualcuno leggendo capirà che non è poi così intelligente :)',
lt90: 'Come diventa la pancia di una mamma alla terza gravidanza? Com’era e com’è',
lt91: 'Il corpo di Britney Spears. Sulla vergogna e la pigrizia',
lt92: 'Leggici:',
lt93: 'Leggici su Facebook',
lt94: 'Versione attuale',
lt95: 'Sul progetto',
lt96: 'Termini d’utilizzo',
lt97: 'sulla privacy',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};