var new_lang = {
lt1: 'ho salvato mio marito dall’ubriachezza in un mese',
lt2: 'La lettera sincera di una nostra lettrice.',
lt3: 'Tutti i contenuti sono pubblicati in modo anonimo! Con rispetto , gli amministratori del sito “rimedi popolari” ',
lt4: 'la mia storia di vita vissuta su come ho smesso di dipendere da mio marito sempre ubriaco. E non è una storia riguardante il divorzio. Vi racconto come ho salvato la mia famiglia da questa tremenda maledizione.',
lt5: 'Si è bevuto tutto !',
lt6: 'Come per tutti, questa tremenda malattia non mi ha colpito subito, è cresciuto. Siamo sposati da 15 anni. 7 anni fa, sono stata io stessa a farci cadere mio marito',
lt7: 'Diagnosi, alcolismo.',
lt8: 'L’alcool diventava sempre più, e di mio marito invece rimaneva sempre meno.',
lt9: 'Alcolismo',
lt10: 'Gli aveva mangiato il corpo, l’anima, l’intelletto. La vodka è quasi riuscita a distruggere la mia famiglia.',
lt11: 'In ogni momento poteva rimanere senza soldi, e ne risentivano sia le vacanze che i vestiti per i figli. Tutto quello che ho messo da parte l’ho dovuto nascondere. Eppure è riuscito a trovare i soldi e beverseli. A lavoro lo volevano licenziare di continuo. 2 anni fa alla fine lo hanno licenziato. Ha promesso di trovare un alltro lavoro. Ho sperato, creduto che presto “tutto sarà bello come prima, come prima del matrimonio…”. Usciva ogni mattina a cercare lavoro e tornava a mani vuote ogni sera e completamente ubriaco',
lt12: 'Parlare con un alcolizzato che se ne frega altamente.',
lt13: 'Ho portato mio marito a casa ubriaco dopo la sua ennesima passeggiata alcolica, mi sono caricato il suo corpo a peso morto fino a casa, a casa l’ho sgridato, ho fatto pressione sulla sua dignità. La mattina l’ho riempito di sottaceti. L’ho chiuso in casa, per evitare che continuasse. Mi pento, ma a volte io stessa sono andata a comprargli la vodka. Volevo vederlo sorridere. Alla fine non viveva senza alcool. Dopo due anni di questa vita ho capito che non potevo continuare così! ',
lt14: 'Divorzio?',
lt15: 'Io mi sono arresa. Le liti continue e la sua faccia ubriaca tutti i giorni mi hanno destabbilizzato! Ho deciso che per me e mio figlio sarebbe stato meglio rimanere senza questo essere che ci rovina la vita.',
lt16: 'Io mi ricordo quei bei tempi quando era attento, un gran lavoratore. Mi amava, Luigi. Questa morte della madre lo ha distrutto. Forse io stessa sono colpevole, non sono riuscita a supportarlo. Ma ho resistito 7 anni, me lo sono caricato sulle spalle! Non avevo pi+ forze, ho chiesto il divorzio.',
lt17: 'Sguardo sobrio',
lt18: 'Quando gli ho mostrato i documenti del divorzio, è rimasto di stucco. Ha capito di aver toccato il fondo. Ho detto che prendo marco e me ne vado da mia madre. E qui è cominciato tutto. Si è messo in ginocchio, mi ha pregato ,supplicato! Era distrutto e ha promesso',
lt19: ' di smettere di bere ',
lt20: ' e di non berne più neanche una goccia. Non l’avevo mai visto così disperato. L’ho perdonato! Gli ho creduto, e non ha bevuto 2 settimane. Poi è arrivato il compleanno del fratello… ed ecco che si ricomincia…',
lt21: ' Però queste due settimane mi avevano ridato amore e speranza. Ho capito quanto lo amo, che padre perfetto è quando è sobrio. Che facciamo fuoco e fiamme a letto. Ho deciso di fare  TUTTO il possibile e , solo se non funziona, andarmene.',
lt22: 'cura',
lt23: ' mi serviva un qualche  ',
lt24: ' Preparato, che avrebbe aiutato sicuramente.',
lt25: ' In questi anni avevo provato di tutto. Imparando dai propri errori mi sono imposta delle regole riguardanti la cura:',
lt26: '1. Senza ricovero',
lt27: '( 5 anni fa l’ho fatto ricoverare , ho semplicemente reso ricco il ciarlatano di turno. Mio marito si è trattenuto 3 mesi e poi ha iniziato a bere più di prima)',
lt28: '2. Senza che lo sappia, senza insospettirlo',
lt29: '( Ho provato a dargli pasticche contro l’alcolismo, lui si è rifiutato, ha fatto un macello. Ho provato a metterla a pezzettini nella zuppa, ne ha sentito il sapore, ha rotto il piatto, чуть не избил меняper poco non mi ha menato. Per questo mi servivano assolutamente',
lt30: ' delle gocce SENZA GUSTO )',
lt31: '3. Senza pericoli',
lt32: '( Ho paura di magia nera e altre cose simili. Sono sicura che l’anima cambia, ci entra qualcosa. Non sono mai andata dalle vecchie che fanno queste cose, e non ve lo consiglio)',
lt33: 'ho cercato su internet, ho letto libri, mi sono consigliata con le amiche. Alla fine ho trovato per caso quello che cercavo. Italiano, 100% naturale, consigliato dai medici.',
lt34: ' Contiene erbe speciali. Curano fegato, polmoni, stomaco ecc. E soprattutto danno indipendenza ',
lt35: ' e addirittura rifiuto verso l’alcool.',
lt36: ' Ho deciso di rischiare e ho iniziato a versagliele di nascosto ',
lt37: ' nel cibo per 3 giorni, 10 gocce. Non hanno odore, colore e sapore. Quello che mi sereve!',
lt38: ' Il primo effetto l’ho visto il quarto giorno. Dopo mangiato mio marito si è versato un cicchetto e , scusate, si è striminzito come il culo di una vecchia. Prima era estasiato, ora invece la vodka gli faceva ribrezzo! E’ corso in bagno a vomitare...',
lt39: ' Non starò qui a raccontarvi come “ha reagito” ogni volta che provava a bere vodka. Lui stesso non capiva perché stava meglio senza alcool che con. Aveva la nausea solo a berne un goccetto. La testa gli faceva male come se fosse già in hangover. Ha iniziato a tornare prima dalle passeggiate alcoliche e mettersi subito a dormire. Non mi raccontava nulla. Lo chiamavano per ubriacarsi e lui rifiutava',
lt40: ' E così è passato un mese. Al compleanno di Marco sono venuti gli amici.',
lt41: ' tutti bevevano tranne lui.',
lt42: ' Guarda il bicchiere e gli occhi tremano. Ha detto a tutti che per il momento ha smesso. Ma io sapevo che aveva smesso del tutto. Solo la notte mentre eravamo a letto non mi sono trattenuta. . ho chiesto, perché non hai bevuto oggi? Lui dopo un lungo silenzio ha detto: il mio l’ho bevuto. La salute è finita. E si è addormentato.',
lt43: ' Un anno senza vodka ',
lt44: ' Dire che sono felice non rende l’idea. Dopo aver superato l’inferno sono arrivata in paradiso. Non beve da un anno, si è trovato un buon lavoro. Abbiamo finito le ristrutturazioni, in casa è tutto nuovo, mobili, cucina. Mio marito passa tanto tempo in famiglia e va in giro con il figlio. Ha una nuova energia negli occhi. Non ci pensa neanche più a vodka e amichetti. Ecco la mia storia. Se avete ubriaconi in famiglia, provate quello che mi ha salvato. In',
lt45: ' questo sito ',
lt46: ' Leggete di più sull’argomento.  Auguro a tutti la felicità in famiglia! Non perdete mai il desiderio!',
lt47: ' Andare al sito ufficiale ',
lt48: ' Fabio Porro',
lt49: ' Mi p sempre sembrato, что che le medicine sono la cosa migliore. Finchè non mi sono ricoverato. Analisi e prelievi senza fine, di qua di la , i soldi evaporavano. E con che vantaggi??? Psicologi senza arte ne parte, pasticche senza alcun effetto . Dopo anno deciso di ricoverarmi stabilmente. Mi sono solo rovinato i nervi e neanche ho smesso di bere. Adesso studio i metodi popolari. Voglio smettere con questo veleno che mi sta divorando. Grazie dei suggerimenti. Probabilmente ci rpovo.',
lt50: ' Michela Pagliacci ',
lt51: ' per la salute, ovviamente, le erbe fanno bene. Limportante è che non è pericoloso! So di cosa parla, anche io ho usato le gocce con mia madre. Certo lei è stata male. Ma si è decisa a curarsi. Sono felice che sono riuscito a curare mia madre con queste gocce, ormai non beve da due anni!',
lt52: ' Lupoli Andrea ',
lt53: ' Ho curato mio zio dalla dipendenza, dopo 30 anni di ubriachezza, ci sono praticamente riuscito. Ha avuto ricadute, raramente. Ora non beve da 7 anni e mezzo. Faccio gli scongiuri<br>Che dio vi aiuti tutti a salvarvi dalla dipendenza!',
lt54: ' Michela Sentimenti ',
lt55: '  Grazie pe la storia e per la sincerità. La capisco molto bene ho avuto una storia simile.  Marito urbiacone e figlio piccolo. Grazie per la soluzione! Ci proverò sicuramente!!! ',
lt56: ' Lara Pinguello',
lt57: ' Come se avessi appena sentito la storia dell amia vita, solo che non avevamo ancora bambini. Ci siamo curati con queste erbe. Hanno aiutato molto. Ha smesso di ubriacarsi. Adesso bevev raramente, durante le feste. Si controlla, e non mi preoccupo più per lui.  Abbiamo una bambina e un bambino. Buona fortuna! Funziona!',
lt58: ' Laura Estella ',
lt59: ' Grazie per i consigli. Non ci si crede che aiuta…..ho provato tutto. Ho già <br>perso la speranza….poi magari….la speranza è l’ultima a morire ',
lt60: ' Francesca Perdigiorno',
lt61: ' Provate a pregare. Quando usate le gocce dite una preghiera. Vi aiuta sicuramente !',

};
function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};