var new_lang = {
    lt1:  '- 100% bezpiecznie i skutecznie',
    lt2:  'Nam <span class="blue">JUZ</span> zadzwonili 4 672 osoby, żeby powiedzieć<span class="blue">DZIĘKUJĘ!</span>',
    lt3:  'Zamówić darmową konsultacje',
    lt4:  '<span class="big">Bioretin:</span> główny sojusznik<span class=“blue">w wałce z wiekiem</span>',
    lt5:  '<span class="blue">Zmniejsza</span> zmarszczki',
    lt6:  '<span class="blue">Przywraca </span> elastyczność',
    lt7:  '',
    lt8:  '<span class="blue">Podciąga </span> kontury',
    lt9:  '<span class="violet">Aktualizowanie</span> "uśpionych" komórek',
    lt10: '<span class="violet">Odzyskanie</span> uszkodzonych komórek',
    lt11: '<span class="violet">Regeneracja </span> zdrowych komórek',
    lt12: 'Cena<br><span class="bold">1 EURO*</span>',
    lt13: 'Cena z rabatem:<br><span class="big">1 EURO*</span>',
    lt14: 'Stara cena:',
    lt15: 'do końca rabatu zostało:',
    lt16: 'dni',
    lt17: 'godziny',
    lt18: 'minut',
    lt19: 'sekund',
    lt20: 'UWAGA! Ilość sztuk z rabatem jest ograniczona.',
    lt21: 'Zostało: ',
    lt22: ' sz.',
    lt23: '* - przy zamówieniu pełnego kursu',
    lt24: 'Ile łat ma Twoja skóra?',
    lt25: 'Ogólnie przyjmuje się, że jest tylko jedna oznaka starzenia: zmarszczki. Ale możemy Ci powiedzieć, że zmarszczki to tylko połowa kłopotu. <span class="red">KAŻDY NOWY PROBLEM DODAJE CI WIEKU!</span>',
    lt26: 'Fałdy nosowo-wargowe',
    lt27: '+6 łat',
    lt28: 'Pływający owal twarzy',
    lt29: '+5 łat',
    lt30: 'Kurze łapki',
    lt31: '+4 łata',
    lt32: 'Fałda pomiędzy brwi',
    lt33: '+7 łat',
    lt34: 'Torby pod oczami',
    lt35: '<span class="violet">Skóra ma swój wiek.</span> I on różni się od naszego rzeczywistego. Dlatego że skóra jest bardzo wrażliwa, ona zostaje zniszczona czasem o wiele bardziej od innych сzęści ciała. Po 35 leciu skóra starzy się szybko! Powodem tego jest grawitacja, dziedziczność, zła ekologia, promieniowanie ultrafioletowe, stres i złe odżywienie. <span class="red">Sprawdź, ile łat ma Twoja skóra.</span> <span class="underline">Zaznacz elementy, z którymi się zgadzasz.</span>',
    lt36: 'Wpisz swój rzeczywisty wiek:',
    lt37: 'Mam fałdy nosowo-wargowe:',
    lt38: 'Skóra straciła elastyczność:',
    lt39: 'Mimikowe zmarszczki są wyrażane:',
    lt40: 'Istnieje kilka głębokich zmarszczek:',
    lt41: 'Wpisz swój wiek',
    lt42: 'Polecamy: 17 jednostek toksyny botulinowej, 2 zabiegi mezoterapii<br><span class="white">ŁUB 1 kurs kremu Bioretin</span>',
    lt43: 'Polecamy: 37 jednostek toksyny botulinowej, 3 zabiegi mezoterapii, 1 kurs wypełniacze <span class="white"> ŁUB 2 kurs kremu Bioretin</span>',
    lt44: 'Polecamy: 47 jednostek toksyny botulinowej, 4 zabiegi mezoterapii, 1 kurs wypełniacze <span class="white"> ŁUB 3 kurs kremu Bioretin</span>',
    lt45: 'Polecamy: 57 jednostek toksyny botulinowej, 5 zabiegi mezoterapii, lifting chirurgiczny twarzy <span class="white"> ŁUB 3 kurs kremu Bioretin</span>',
    lt46: 'dlaczego wyglądać starzej, niż Twój rzeczywisty wiek, jeżeli ',
    lt47: 'Ty możesz wyglądać bardziej młodą?',
    lt48: 'WYGŁĄDAJ ZNACZNIE MŁODSZĄ, BEZ BÓLU I RYZYKU!!',
    lt49: 'kobiet żałują, że że zgodziły się na operację i chirurgie ',
    lt50: 'sprawdzone bezpieczeństwo i skuteczność',
    lt51: 'NOWA FORMUŁA Bioretin',
    lt52: 'przeciwdziałanie starzeniu się',
    lt53: 'POWRÓĆ NAJLEPSZE LATA ŻYCIA I MŁODOŚĆ',
    lt54: 'Bioretin - INNOWACJE i WYNIK',
    lt55: 'Bioretin - to innowacyjny krem zawierający olej arganowy i olej z awokado, uzdrawiające witaminy i kwas hialuronowy, odżywi i odmłodzi głębokie warstwy skóry, będzie stymulować wzrost tkanki nabłonkowej',
    lt56: 'Oznacza to, że krem aktywnie stymuluje produkcję kolagenu i regenerację macierzy międzykomórkowych. Z powodu czego <span class="violet"> zmarszczki na czole będą nie takie wyraźne, tak samo jak i fałdy w okolicach ust i oczy. </span><br><span class="orange">Bioretin - to jest super "koktajl" służący do korekcji fałd nosowo-wargowych.</span>',
    lt57: 'Zawiera składniki, które są stworzone w celu "zwiększenia objętości" w miejscu pojawienia się <span class="violet"> zmarszczek, które pomagają zagnieceniu się od wewnątrz,</span> "popychając" skórę z powrotem. Zarówno pomaga "odprężyć" mikro-skurczów mięśniowe, aby zapobiec pojawieniu się zmarszczek na skórze.',
    lt58: 'Bioretin - zawiera jeden z najsilniejszych przeciwutleniaczy, neutralizujących wolne rodniki - główne przyczyny starzenia skóry.',
    lt59: 'Wstrzymuje rozkład kolagenu, po prostu wałczy ze starzeniem metodą ochrony komórek przed zniszczeniem. Pobudza krążenie w limfę, aby usunąć obrzęku, "worków" i zmniejszyć cienie kola pod oczami. Wzmacnia strukturę skóry, <span class="violet">podciąga owal twarzy,</span> za pomocą naturalnej produkcji kolagenu i elastyny.',
    lt60: 'Kwas hialuronowy',
    lt61: 'Olej arganowy',
    lt62: 'Olej z awokado',
    lt63: 'Gliceryna',
    lt64: '',
    lt65: 'Sensacyjny efekt Bioretin.',
    lt66: '89% kobiet zaczęły wyglądać na tyle lat, jak się czują!',
    lt67: 'Po 40 roku życia regeneracja komórek zaczyna spowolniać się.',
    lt68: 'Jest coraz więcej zmarszczek, skóra traci elastyczność, a kontury twarzy stają się mniej wyraźne. Rewolucyjny zabieg dla skóry przeciw starzeniu Bioretin jest stworzony specjalnie do pielęgnacji skóry, która starzy się.',
    lt69: 'Potrójne działanie Bioretin potwierdzają badania kliniczne na dużą skalę:',
    lt70: '1183 kobiety',
    lt71: 'Potwierdziły <span class="violet">znaczne zmniejszenie</span> zmarszczek (o 77%) - w kącikach oczy (o 56%) i na czole (o 76%)',
    lt72: '927 kobiety',
    lt73: 'Zauważyły zapełnienie się objętości w fałdach nosowo-wargowych,',
    lt74: 'objętość w miejscu kości policzkowej została przywrócona (+41%).<br>Owal twarzy jest o wiele bardziej wyraźny, skóra jest naprężona i wypełniona objętością.',
    lt75: '1321 kobiety',
    lt76: 'Widoczne wyniki<br><span class="violet">Tonus skóry jest zwiększony (+65%),</span> ona jest bardziej gęsta(+54%) i nawilżona na 48 godziń.',
    lt77: '<span class="red">BADANIA POKAZUJĄ ŻE</span> KOBIET, KTÓRE STARSZĄ SIĘ JUZ "NIE BIORĄ POD UWAGĘ"',
    lt78: 'NIE ZWRACAJĄ UWAGI',
    lt79: '74% mężczyzn szczerze odpowiadali, że kobiety z zmarszczkami i oznakami starzenia na twarzy nie mogą być seksualnie atrakcyjne.',
    lt80: 'GÓRA KARIERY',
    lt81: '67% pracodawców nie chcieli by zatrudniać i oferować promocji kobiecie, która wygląda na ponad 45 lat',
    lt82: 'NIEWIERNOŚĆ MĘŻA',
    lt83: '96% mężów zostawiali żon ze względu na młodszą kochankę i uważając fakt, że żona juz przestała wyglądać młodo.',
    lt84: 'Badanie pokazuje: 87% mężczyzn mówią, że <span class=“red">wiek kobiety nie ma znaczenia,</span> ważne jest żeby kobieta wyglądała <span class=“red”>młodo i atrakcyjnie.</span> To robi ją, w oczach mężczyzny <span class=“red">bardziej seksowną i powoduje szacunek.</span>',
    lt85: 'Weź swój wygląd we własne ręce',
    lt86: 'BĄDŻ <span class="red">O 10 ŁAT MŁODSZA</span> ZA 2,5 KURSY',
    lt87: 'Fałdy nosowo-wargowe<span class="orange">ZNIKNĘŁY</span> za 2 kursy',
    lt88: 'Kurze łapki <span class="orange">ZNIKNĘŁY</span> za 3 kursy',
    lt89: 'Fałda pomiędzy brwi<span class="orange"> ZNIKNĘŁA</span> za 2 kursy',
    lt90: 'Pływający owal twarzy <span class="orange">ZNIKNĄŁ</span> za 1 kurs',
    lt91: 'Torby pod oczami <span class="orange"> ZNIKNĘŁY </span> za 1 kurs',
    lt92: 'NIEZALEŻNA OPINIA KOSMETOLOGÓW',
    lt93: 'Amelia Janicka<br>Lekarz kosmetolog-dermatolog <br> Doświadczenie w praktyce 18 łat',
    lt94: 'Gdybym była w miejscu Twojego lekarza kosmetologa, zdecydowanie zaoferowałabym Ci maksimum tego, co mogę i co jest dostępne na rynku: <span class="violet"> botoks, plazmoleilowanie, wypełniacze itd.</span> Ale jako kobieta rozumiem, że za pomocą <span class="violet">Bioretin wszystkie te procedury mogą zostać przesunięte na kolejne 6 lat.</span>',
    lt95: 'I niech myślą, że zrobiłaś operację...',
    lt96: 'Daria Młodyr<br>Starszy asystent plastycznego chirurga<br> Doświadczenie w praktyce 7 łat',
    lt97: 'Polecam nie śpieszyć się w zrobieniu wstrzyknięć, chirurgii i innech traumatycznych zabiegów. Możesz zostaw ten pomysł na 20 lat. <span class=“violet">Masz sprobować Bioretin i za 1 miesiąc zrozumiesz, że nastąpiła rewolucja w medycynie estetycznej.</span> Kosmetyki medyczne - to jest przyszłość piękna i młodości, którą możemy juz teraz wykorzystywać i cieszyć się wynikami.',
    lt98: 'Niech Twoja skóra stanie się młodszą!',
    lt99: 'Wszystkie prestiżowe salony piękna we Warszawie <span class="blue">juz dawno używają Bioretin.</span> Jedna procedura, składająca się z peelingu, masażu twarzy i zastosowania kremu kosztuje około 1000 złotych',
    lt100:'SZCZERZE OPINIE',
    lt101:'Polecano przez prawdziwych kobiet.',
    lt102:'W 2016 roku było sprzedano 3 000 000 sztuk.',
	lt103:'Ty juz zamówiłaś swój Bioretin?',
    lt104:'Daria, Kraków',
    lt105:'Aga, Warszawa',
	lt106:'Ania, Poznań',
    lt107:'12 000 000 $ wydano dla stworzenia Bioretin',
    lt108:'łata na badania kliniczne',
	lt109:'łata na stworzenie formuły',
    lt110:'działających specjalisty',
    lt111:'procentów efektywność',
	lt112: 'procentów szczęśliwych kobiet',
    lt113:'certyfikaty jakości ЕС, РТС, ISO',
    lt114:'procentów naturalnych składników',
	lt115:'UWAGA!',
    lt116: 'Ze względu na popularność w Polsce i innych krajach Europy, zostało zauważono dużo przypadków sprzedaży falsyfikatów po okazyjnej cenie! <br> Uważaj! Na oryginalnym opakowaniu koniecznie będzie kod kreskowy z numerem autentyczności! Jeśli brakuje kodu kreskowego, skontaktuj się do nas ze skargą, pisząc pod adresem wskazanym na dole strony. Zwrócimy Ci odszkodowanie za straty i będziemy ścigać przestępców zgodnie z prawem.',
    lt117:'Jak my pracujemy?',
	lt118:'KROK 1',
    lt119:'Złóż natychmiastowe zamówienie za<span class="red"> promocyjną ceną</span>',
    lt120: 'KROK 2',
	lt121:'Poczekaj na callback i konsultant zapyta Cię o szczegóły',
    lt122: 'KROK 3',
    lt123:'Nic nie płacisz, dopóki nie otrzymasz paczki',	
};

function Translater () {
 for (class_name in new_lang) {
  var elements = document.getElementsByClassName(class_name);
  if (elements.length) {
   for (key in elements) {
    elements[key].innerHTML = new_lang[class_name];
   }
  }
 }
};