var new_lang = {
lt1: 'Alkoholizmą galima nugalėti tik už 14 dienų! Išgelbėkite savo artimuosius!',
lt2: 'Lietuvoje',
lt3: 'Šalyje',
lt4: 'Ministras',
lt5: 'Ministro pavaduotojai',
lt6: 'Teisiniai veiklos pagrindai',
lt7: 'Pavaldžios įstaigos',
lt8: 'Struktūra',
lt9: 'Sveikata',
lt10: 'Aukščiausių pasiekimų sportas',
lt11: 'Kūno kultūra ir sportas',
lt12: 'Parolimpinis ir kurčiųjų olimpinis sportas',
lt13: 'Sportinio rezervo paruošimas',
lt14: 'Olimpinis judėjimas',
lt15: 'Antidopingo aprūpinimas',
lt16: 'Veikla',
lt17: 'Pasaulio futbolo čempionato rengimo programa',
lt18: 'Kolegija',
lt19: 'Mokslas, išsilavinimas',
lt20: 'Federalinės tikslinės programos',
lt21: 'Biudžeto ir finansų politika',
lt22: 'Ekonomika ir investicijų politika',
lt23: 'Ekstremalių situacijų prevencija',
lt24: 'Tarptautinis bendradarbiavimas',
lt25: 'Kova su korupcija',
lt26: 'Valstybės teikiamos paslaugos',
lt27: 'Veiklos ataskaitos',
lt28: 'Sporto ministerijos veiklos planas 2013- 2018 metams',
lt29: 'Dokumentai',
lt30: 'Federaliniai įstatymai',
lt31: 'Įsakymai dėl apdovanojimo',
lt32: 'Norminių ir teisinių aktų projektai',
lt33: 'Įsakai, potvarkiai, nutarimai',
lt34: 'Įsakymai',
lt35: 'Oficiali teisinės informacijos interneto svetainė',
lt36: 'Spaudos centras',
lt37: 'Anonsai',
lt38: 'Naujienos',
lt39: 'Vaizdo įrašų galerija',
lt40: 'Nuotraukų galerija',
lt41: 'Interviu',
lt42: 'Pranešimai ir pasirodymai',
lt43: 'Tėvai ir Vaikai',
lt44: 'Žiniasklaidos stebėsena',
lt45: 'Klausimai ir atsakymai',
lt46: 'Konkursai',
lt47: 'Vakansijos',
lt48: 'Viešieji pirkimai',
lt49: 'Konkursai',
lt50: 'Bendras vasltybės projektas',
lt51: 'Pagrindinis puslapis',
lt52: 'Spaudos centras',
lt53: 'Naujienos',
lt54: 'Išgydyti alkoholizmą yra lengva!',
lt55: 'Alkoholizmą galima nugalėti tik už 14 dienų! Išgelbėkite savo artimuosius, jiems gresia DIDŽIULIS PAVOJUS!',
lt56: 'Sveiki, Draugai!',
lt57: 'Per 36 metų mano medicinos praktiką esu daug ką pamatęs, bet šiandien mūsų pokalbio tema yra ypač rimta - ALKOHOLIZMAS. Baisu, kai potraukis alkoholiui naikina žmogaus gyvenimą, dėl alkoholio irsta šeimos, vaikai praranda tėvus, o žmonos - vyrus, bet mūsų dienomis alkoholizmas, kaip liga, darosi vis jaunesnis. Dažnau prasigeria būtent jauni žmonės, kurie griauna savo ateitį ir savo sveikatai sukelia nepataisomą žalą. Reikia pripažinti, kad dažniausia būtent moterys turi gelbėti alkoholiką: savo sūnų, vyrą ar tėvą. Geriantis šeimos narys gali būti išgelbėtas, ir padaryti tai galima slaptai nuo jo paties.',
lt58: '<strong>Jonas Malkaitis</strong><br> medicinos mokslų daktaras, profesorius, gastroenterologas, Reabilitacijos ir sveikatos centro direktorius<br> darbo patirtis - 36 metai',
lt59: 'Tai, kad alkoholis kenkia ne tik fizinei, bet ir psichinei sveikatai, žino kiekvienas suaugusis ir vaikas. Mirtis yra dažnas galas nepataisomiems girtuokliams, kurie nepanorėjo gydytis ar tiesiog nepaspėjo laiku kreiptis į specialistus. Net atveju, kai apie alkoholizmą nekalbama, alkoholiniai gėrimai labai kenkia žmogaus sveikatai.',
lt60: 'Neigiama įtaka smegenims yra viena baisiausių alkoholio poveikio žmogui pasekmių. Reguliariai vartojamas alkoholis smegenyse sukelia negrįžtamus pokyčius, kurie trukdo organizmui tinkamai veikti.',
lt61: 'Alkoholiko smegenys',
lt62: 'Parodyti nuotrauką',
lt63: 'Sveiko žmogaus smegenys',
lt64: 'Alkoholiko smegenys',
lt65: 'Kepenys yra dar vienas iš tų organų, kurie visų pirma kenčia nuo alkoholizmo. Daugelis žino, kad kepenys, inkstai, širdis ir galvos smegenys paprastai yra pirmieji, kurie patys jaučia alkoholio kenksmingą poveikį, ir taip iš tikrųjų yra. Sunkios kepenų ligos yra būtent tai, ką sukelia alkoholizmas. Be to, per didelis alkoholio vartojimas sukelia kepenų suardymą. Nėra paslaptis, kad kepenys yra organas, kuris turi kovoti su alkoholio patekimu į žmogaus organizmą.',
lt66: 'Alkoholiko kepenys',
lt67: 'Sveiko žmogaus ir alkoholiko kepenų palyginimas',
lt68: '<br>Tyrėjų komentarai:',
lt69: '<strong >Flora Besienė </strong><br> medicinos mokslų daktaras, profesorė, gastroenterologė, narkologė <br> Darbo patirtis - 22 metai',
lt70: 'Turbūt, jūs žinote, kad dar neseniai vienintelis veiksmingas būdas kovoti su priklausomumu nuo alkoholio buvo griežtas paciento kodavimas. Šis metodas turi milžinišką minusą - sergantysis turi pats sutikti gydytis ir sąmoningai užsikoduoti bei visišką atsisakyti alkoholio visiems laikams. Dažniausia žmonės, kurie geria, nemano, kad priklauso nuo alkoholio, jie yra tikri, kad bet kuriuo metu gali mesti gerti. Tik jų artimieji žmonės supranta, kad jie niekada negali mesti gerti alkoholį be pagalbos. Ką daryti? Įtikinti, ginčytis, bartis ir prašyti žmogų yra visiškai beprasmiška, alkoholis jau jį valdo. Yra tik vienas variantas - gydyti artimąjį žmogų slapta norint jį išgelbėti. Tai leidžia naujausiąs gydytojų ir mokslininkų sukurtas vaistas - Alcobarrier, kuris per 2 savaites (14 dienų) gali suformuoti stiprų bjaurėjimosi alkoholiu jausmą net lėtiniam alkoholikui. Bet koks alkoholis žmogui darosi bjaurus, net alkoholio kvapas.',
lt71: 'Kaip Alcobarrier veikia',
lt72: 'Alcobarrier yra vaistas, visiškai susidedantis iš natūralių komponentų, tai reiškia, kad jis neturi ir negali turėti kontraindikacijų, jis yra saugus, jį gali vartoti visi. Be to <a target="_blank" Href=""> <b> “Alcobarrier” </b> </a> yra kompleksinio veikimo vaistas, be savo pagrindinės funkcijos - potraukio alkoholiui blokavimo ir bjaurėjimosi alkoholiu formavimo - jis taip pat pradeda atkuriamuosius procesus visuose organuose, kurie pradėjo irti dėl alkoholio. Ląstelių lygyje atsinaujina kepenys, širdis, inkstai, normalizuojasi nervų sistema. Alcobarrier pašalina psichologinį potraukį alkoholiui, įprotis vartoti alkoholį visiškai dingsta ir jį pakeičia supratimas, kad sveikata yra svarbi. Pacientas jaučiasi energingas ir kupinas jėgų be kitos alkoholio porcijos, abstinencijos nėra.',
lt73: 'Alcobarrier',
lt74: 'Šiuo metu yra tik viena oficiali interneto svetainė, kur parduodamas vaistas Alcobarrier, o ne pigūs padirbiniai. Alcobarrier nėra parduodamas vaistinėse, ir kai jį pamatėte savo miesto vaistinių tinkle, žinokite, kad tai yra padirbinys! Apie jį daug kalbama ir televizijoje, ir internete. Ir ne veltui, turiu pasakyti! Alcobarrier yra sudėtingas ir unikalus rečiausių ir galingiausių natūralių gydomųjų medžiagų mišinys. Šis vaistas įrodė savo veiksmingumą ne tik pacientams, bet ir mokslininkams, kurie jį pripažino veiksmingu vaistu. Galingas poveikis pastebimas praėjus jau 10-15 dienų vartojimo - kaip parodė tyrimai, Alcobarrier veikia!',
lt75: 'Be to, Reabilitacijos ir sveikatos centras atliko apklausa, kuri viršijo mūsų lūkesčius:',
lt76: 'Reabilitacijos ir sveikatos centro apklausa: <span>Kaip jūs atsikratėte priklausomumo nuo alkoholio ir išgelbėjote savo kepenis?</span>',
lt77: 'Medicininiai preparatai:',
lt78: 'Liaudies medicina:',
lt79: 'Dar ieškau sprendimo:',
lt80: 'Netikiu, kad tai yra įmanoma:',
lt81: 'Svarbu! Buvo padaryta išvada, kad vasarą yra geriausias laikas pradėti gydyti alkoholizmą. Dėl vidutinės temperatūros normalizavimo paspartėja medžiagų apykaita ir kraujotaka kraujagyslėse, didėja vaisto vartojimo poveikis. Potraukis alkoholiui dingsta 55 proc. greičiau, nei kitais metų laikais. Smegenų ir kepenų funkcijos taip pat atkuriamos greičiau, vidaus organai sugrįžta iki normos 2 kartus greičiau!',
lt82: 'Tyrimai',
lt83: '<b>Su <a target="_blank" href="">"Alcobarrier"</a> Reabilitacijos ir sveikatos centre atliktų laboratorinių testų rezultatai:</b>',
lt84: 'Buvo atrinkti 85 skirtingo amžiaus savanoriai, kurie serga sunkia, lengva ir vidutinio sunkumo priklausomumo nuo alkoholio formomis. Atlikus 30 dienų tyrimą, gauti<b> šie rezultatai: </b>',
lt85: '1. Užregistruotas savijautos pagerėjimas visai 18-68 metų amžiaus tiriamųjų grupei. <br> <br> 2. Užregistruotas visiškas potraukio alkoholio pašalinimas 96 proc. pacientų. <br> <br> 3. Jau po 10 dienų dauguma pacientų pareiškė apie atsiradusį bjaurėjimąsi bet kokių alkoholinių gėrimų kvapu ir skoniu. <br><br> 4. Po 30 dienų 97 proc. pacientų atsisakė alkoholio, užregistruotas širdies, kepenų ir inkstų veikimo medicininių rodiklių pagerėjimas.',
lt86: 'DĖMESIO! <a style="color: rgb(255, 102, 0); font-weight: bold;" href="">Užsakyti “Alcobarrier”</a><b> Lietuvos teritorijoje galima tik </b><a style="color: rgb(255, 102, 0); font-weight: bold;" href=""><b>OFICIALIOJE GAMINTOJO SVETAINĖJE!</b></a><b> </b>',
lt87: 'Norėdami gauti Alcobarrier akcine kaina, užpildykite formą:',
lt88: 'Primename, kad akcinė kaina galioja tik iki 2017-07-13 imtinai.',
lt89: '203 komentarai šiandien',
lt90: 'Edvinas Artiuškinas',
lt91: 'Ačiū jums! Pabandžiau, tapo tikrai lengviau. Noras gerti dingo. Pamatysime, kas bus toliau. Dar per anksti sakyti, parašysiu vėliau. Bet jau tikrai nesinori imti į ranką stiklinę. Manau, kad viskas gausies!',
lt92: 'prieš valandą',
lt93: 'Paulius Baranius',
lt94: 'Žmonės, padėkit! Jau pavargau nuo alkoholio. Prasigeriu akyse. Jau tiesiog nežinau, ką daryti. Periodiškai koduojuosi, bet tai kiekvieną kartą neilgam :(',
lt95: 'Lukas Bučiūnas',
lt96: 'Lukai, imk Alcobarrier, nepasigailėsi. Pats turėjau problemų, net žmona išėjo, jau rankos nusileido, nežinojau, ką daryti. Ačiū motinai, kuri užsakė ir privertė vartoti. Dabar visai negeriu, netgi su žmona susiėjau. Patikėk, imk ir viskas bus gerai, pamatysi',
lt97: 'Eimanta Darbutienė',
lt98: 'Kaip įsigyti Alcobarrier? Prašom padėti!',
lt99: 'Dominykas Auglys',
lt100: 'Eimanta, čia tau nuoroda <a href="">Alcobarrier</a>, tik paskubėk, kol ten akcija galioja',
lt101: 'Eimanta Darbutienė',
lt102: 'Dominykai, ačiū, jau užsisakiau.',
lt103: 'Ar gali pasakyt ar ilgai siunta eis į Klaipėdą? ',
lt104: 'Eimanta, na mes su tavim esam iš vieno miesto, todėl maždaug po 4 dienų gausi)',
lt105: 'Dominykai, ačiū tau dar kartą))',
lt106: 'Eimanta, tai nėr už ką, jei nori, galim susitikt) Paaiškinsiu kaip vartoti',
lt107: 'Lukai, atsiprašau, bet perku vyrui, stengiuosi jį išgelbėt))',
lt108: 'Eimanta, gaila, bet vis tiek sekmės tau)',
lt109: 'Kintenis Baranauskas',
lt110: 'Sakykit, liaudis, ar padės? Vartojau įvairių vaistų, bet jokio efekto',
lt111: 'Tadas Čiupaila',
lt112: 'Kinteni, taip, be abejo. Vaisto efektas yra stiprus, ir svarbiausia, kad net sveikatai nekenkia (skirtingai nuo degtinės). Taigi skubėk užsakyt!',
lt113: 'Erika Bartoševič',
lt114: 'Ačiū Jums! Be jūsų nepatikėčiau Alcobarrier efektyvumu! Aš gyvenau su vyru alkoholiku daugiau nei 5 metus ir žinau, kas tai yra. Po savaitės, kai kas vakar duodavau vyrui Alcobarrier kartu su arbata, pastebėjau ryškius pokyčius su juo! Įdomiausia, kad jis net nesuprato, kodėl nustojo gerti! Sako, išgėriau savo normą, daugiau nelinda! Ačiū!',
lt115: 'Ir siuntą Panevežy gavau labai greit.',
lt116: 'Gustė Čepulionytė',
lt117: 'Duodu Alcobarrier tėvui lėtiniam alkoholikui jau 2 savaites, tiksliau šiandien yra 16 diena, rezultatas yra puikus! Aš daug ką išbandžiau anksčiau, bet visi mano bandymai buvo tušti dėl to, kad jis nenorėjo gydytis',
lt118: 'prieš 57 minutes',
lt119: 'Mantė Kapušinskaitė',
lt120: 'Šiandien, ką tik užsakiau.<br> Ten kol kas yra nuolaidų, todėl paskubėkit!<br> Oficialioje <a href="">svetainėje</a> pirkau, labai greitai perskambino ir užsakymą patvirtino. <br> Pagaliau norisi būti blaiva.)',
lt121: 'prieš 55 minutes',
lt122: 'Marija Kupytė',
lt123: 'Aš pati atlikau visą Alcobarrier kursą pagal gydytojo patarimą, o sveikatos problemos prasidėjo dėl alkoholio. Man buvo sunku pergyventi skyrybas ir pati nepastebėjau, kaip pradėjau prasigerti. Bandžiau mesti be kitų pagalbos, bet pavykdavo tik kuriam laikui. Aš supratau, kad pasiekiau ribos, kai gydytojas man pasakė, kad jei nemesiu gerti, mano širdis neištvers. Po Alcobarrier atsirado kokių gyvybiškų jėgų, jaučiausi kažkaip žvaliau. Netgi nepastebėjau, kaip dėmesys nuo alkoholio persijungė į kitus dalykus! Ir tikrai nebesinori į parduotuvę eiti pirkti butelį!!! <center> </center>',
lt124: 'prieš 53 minutes',
lt125: 'Aurima Kuckailytė',
lt126: 'Mano giminaičiai vartojo Alcobarrier ir taip pat sėkmingai (jie yra vyras ir žmona). Tap susiklostė gyvenimas, kad jie kartu pradėjo gerti... Aš jau maniau, kad prarasiu juos, nes jie tiesiog prarado visą susidomėjimą gyvenimu. Jiems dar pasisekė, kad palaikė vienas kitą ir abu tvirtai nusprendė nebegerti. Paklausiau jų, sako tikrai, visai nesinori gerti, o įsivaizduoti, kad geri degtinę - apskritai šleikštu darosi. <center></center>',
lt127: 'prieš 48 minutes',
lt128: 'Justina Kulienė',
lt129: 'Išgelbėjau vyrą pasinaudojusi Alcobarrier, jo tėvas ir abu seneliai mirė dėl alkoholizmo, jis jau pats manė, kad eis jų pavyzdžiu, bet ne! Slapta duodavau jam Alcobarrier kiekvieną dieną, kartais buvo sunku, bet sugebėjau. Jis nieko nesuprato, mano, kad jis pats susitelkė ir nustojo gerti. Iš pradžių norėjau pasakyti jam tiesą, bet nusprendžiau nesakyti. Jeigu mano, kad pats sugebėjo – tegul džiaugiasi ir didžiuojasi savimi. Man svarbiausia, kad jis būtų blaivus ir sveikas!',
lt130: 'prieš 44 minutes',
lt131: 'Donata Muntian',
lt132: 'Tikrai, nesakykit nieko geriau, vyrams geriau galvoti, kad jie patys sugebėjo įveikti šį blogą įprotį. Aš nusipirkau Alcobarrier savo tėvams, mama nepastebimai duodavo tėčiui ir sugebėjo ištraukti jį iš butelio. Gaila, kad anksčiau tokio vaisto nebuvo, tėvas tiek metų išeikvojo degtinei... <br> <br> Tikiuosi, kad potraukis degtinei negrįš, bet jei sugrįš - atliksim dar kursą, mama dar turi Alcobarrier.',
lt133: 'prieš 39 minutes',
lt134: 'Birutė Kiškienė',
lt135: 'Tikiuosi, kad Alcobarrier išgelbės mano mamą, tėtis geria ir geria, mes su ja nieko negalim su juo padaryt, net pas burtininkę buvom – nieko nepadėjo. Po Alcobarrier jau mėnesį negeria, tikiuosi, ir negers..',
lt136: 'prieš 35 minutes',
lt137: 'Aselya Kuralovienė',
lt138: 'Taip pat pasidalinsiu savo džiaugsmu. Ištraukiau savo vyrą iš lėtinio alkoholizmo, jau keletą kartų išeidavau nuo jo, bet sugrįždavau, vis tiek gimtasis žmogus. Tada suradau šį Alcobarrier, nusipirkau daug, su atsargomis ir pradėjau duoti vyrui. Ir padėjo! Jis vartojo 3 savaites kiekvieną dieną ir jau 2 mėnesius nebegeria. Tikiuosi pakaks ir nepradės. <br> Noriu pasakyti ačiū gydytojams!',
lt139: 'prieš 31 minutę',
lt140: 'Vaida Sabaliauskienė',
lt141: 'Žmonės, sakykit, kur jūs pirkot? Vaistinėse toks vaistas neparduodamas. Nesinorėtų gauti padirbinio, nes, taip suprantu, jokios prasmės nebus.',
lt142: 'prieš 27 minutes',
lt143: 'Jonas Malkaitis',
lt144: 'Dar kartą kartoju, kad „Alcobarrier“ galima užsakyti TIK <a target="_top" href="">oficialioje svetainėje</a>, kad nepasiklystumėte, tiesiog paspauskite mygtuką “Pereiti į gamintojo svetainę“ truputį žemiau! Specialiai mūsų skaitytojams yra nuolaida, susitarus su gamintoju, bet ji galios visai neilgai, todėl paskubėkit užsakyti!<br> Ir prašom saugokities padirbinių.<br><br>Pagarbiai, Jonas.',
lt145: 'prieš 15 minutes',

};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};