var new_lang = {
lt1:    'Blog',
lt2:    'Hogyan FOGYTAM LE 36 kg-t 6 hónap alatt',
lt3:    'Beküldve',
lt4:    'Szerző:',
lt5:    'Amalia',
lt6:    'Nagyjából 3 hetet vett igénybe a fogyási eljárás. Mielőtt fogyni kezdtem, természetesen felmentem a netre, több fórumot átolvastam, ahol elbeszélték ki és hogyan fogyott le 40 kg-ot. Nekik rengeteg albumuk van ebben a csoportban. És nem hiszed el, de eltöltve 3 órát a laptopomon, mér el is majszoltam egy fél doboz csokit, két csésze kávét és egy joghurtot. De kizárólagos módszert, <b>hogy hogyan is fogyhatnák le emberkínzó diéták nélköl nem találtam</b>. Valaki uborkával és zabkásával fogyott, valaki almával, és valaki fél évig ölte magát az edzőteremben és szerencsétlen 5 kg-tól szabadult meg. Nekem 10-12 kg-os eredmény kellett és maximum kettő hónap leforgása alatt.',
lt7:    'Szóval',
lt8:    'június 1.',
lt9:    'súly 83 kg, magasság 175сm',
lt10:   'Eldöntöttem, hogy egy hétig zabkásán és főtt csirkemellen fogok ülni. Olvastam, hogy az ilyen párosítás fogyást okoz elő.Eredmény : 2 napig bírtam. Ez szörnyű! Semmi változatosság, az íze meg undorító fűszerek meg szószok nélkül. Hányszor folyt a nyálam, mikor a melóból hazafelé menet elmentem egy pékség vagy étterem mellett, amelyekben annyi finom, illatos és változatos kaja gőzölgött...megértettem, hogy egy hetet se fogok kibírni zabkásán meg csirkemellen. Keressünk tovább.',
lt11:   'június 3:',
lt12:   'Valamit csinálnom kell! Valami oknál fogva újra 2 kilóval lettem nehezebb, emiatt idegeskedek és amikor ideges vagyok akkor mértéktelenül eszek! Változtattam az étrendemen, a zabkása maradt,de közben áttértem az almára és főtt tojásra. Na mit is mondjak, reggelire zabkását ettem banánnal, ebédre igyekeztem zöldség salátát és főtt tojást fogyasztani. 2 darabot. Több tojást nem bírok legyűrni.',
lt13:   'június 6',
lt14:   'Ezalatt a három napos kínszenvedés-étrend alatt a bőröm elkezdett száradni, a hajam nem fénylett. Életkedvem nem volt, a számban meg valami rossz utóíz kerengett. Továbbá, valahol kiolvastam, hogy a főtt tojásban rengeteg a rossz koleszterin, ami ártalmas az egészségre! Hogyan lehet ezeket enni ilyen mennyiségeben?<br><h2>június 8:</h2>Hát ezt meg tényleg nem vártam. Az egyik barátnőm meghívott az esküvőjére! A lakzi meg egy hónap múlva! Ja, csak említésképpen, a súlyom már 85 kg, <b>csúnyának, semmire kellőnek és taszító hájpacninak érzem magam </b>! Gyorsan kell valamit tennem ezzel!!!',
lt15:   'A laptopomon eltöltött napok alatt, amiket fogyási tippek keresésével töltöttem, ráj9ttem, hogy a diéta egyáltalán nem nekem való. Mindenütt írják, hogy utánuk beindul a jo-jo effektus és a kilók visszajönnek. A sport úgyszintén – egy hónap alatt akarok 12 kg-ot megszabadulni, de a mindennapos munka 9-20 óra között nem igazán segít ebben. Már épp leakartam mondani a meghívást, de épp maga a barátnőm hívott és <b>nem tudtam visszatartani magam, könnyek közt elpanaszoltam neki a bánatom.</b>',
lt16:   'Csak említés képpen, észrevettem, hogy Mónika nagyon lefogyott, ő mindig is kövérke volt, most pedig S/M méretű ruhákat hord. Végighallgatva a sopánkodásomat, elmesélte nekem a saját tapasztalatát. Kiderült, <b>hogy a hogyásban neki az OneTwoSlim kúra segített</b>, amelyiket az anyukája szerezte be neki. Igazából, nem igazán hittem a hatásában, de visszagondolva arra, hogy hogy nézett ki Móni fél évvel ezelőtt, nagyooooon, de nagyon ki akartam próbálni! Móni lakodalma július 2-ra lett kitűzve, ami azt jelenti, hogy nekem egy szerencsétlen három hetem maradt, hogy beleférjek az M-es méretű ruhámba, és ne úgy nézzek ki benne, mint egy kötözött virsli.Aznap rá is találtam a honlapra, ahol meg lehetett rendelni az OneTwoSlim kúrát minden probléma és vény nélkül.És még a patikában sem kell szégyenkeznem! Megrendeltem ezen a   <b><a href="">honlapon</a></b>.',
lt17:   'június 12',
lt18:   'Az OneTwoSlim-et gyorsan kézbesítették a postára. Kinyitottam a munkahelyemen, amíg senki sem látta. Az aprócska dobozban volt egy használati utasítás is. Kiderült, hogy ez a szer nem is vényköteles, méghozzá azért, mert teljesen veszélytelen a szervezet számára minden mellékhatás nélkül szedhető. Eleinte nem érdekelt, milyen hatása van a szervezetre, csak a hatás, de az infó, hogy nincs káros hatása azért megnyugtatott. Aznap el is kezdtem a fogyási terápiámat!<br>Ha igaz, ami le van írva, <b>az OneTwoSlim serkenti azon hormonok erejét, amelyek a zsír lebontásáért felelnek</b>, a többi feladatot maga a szervezet végzi. Kivonja a felesleges zsírt, aktivizálja az anyagcserét és aktívan fogyaszt. Na, lesz, ami lesz!',
lt19:   'június 17 :',
lt20:   'találd ki mi a helyzet? Öt nap elteltével – <b>minusz 3,5 kg</b>! Hogy lehetséges? Mióta használom a készítményt, úgy eszek mint eddig, de ami igaz, az étvágyam javában csökkent, így aztán mégis kevesebbet eszem, mint eddig. Ja, és az esti sorozatnézés közben, igyekszek nassolás helyett a karikagyűrűmet forgatni, lkalmanként beválik.',
lt21:   'június 25',
lt22:   'További <b>minusz 6 kg</b>! Majdnem 10 kilogramm! Sokan mondták, hogy lefogytam és amúgy is jobban érzem magam és jobban nézek ki. <b>A dupla tokás gömböcke helyett, végre vonzó nőnek érezhettem magam </b>! Lehet, hogy ezt bebeszélem magamnak, de úgy éreztem, hogy az egészségem javult : jobban aludtam, abbamaradtak a hangulat ingadozásaim, tele vagyok energiával és pozitív világnézettel.',
lt23:   'júlis 2: súly 68 kg, magasság 175 сm',
lt24:   'Mintha a saját évfordulómat ünnepelném))) <b>Minusz 15 kg – ez még több, mint amiről álmodtam</b>! Szavakba sem tudom önteni a boldogságomat, a tükörtől el sem mozdulok – végre saját magamnak is tetszem)))',
lt25:   'június 24',
lt26:   'Abbahagytam a kúrát, eltelt már 3 hét, de a súlyom nem jött vissza, és a szokás, hogy keveset egyek berögződött és megmaradt. Meghagyom itt a linket <a href="">az OneTwoSlim kúrára</a> , minden esetre, hogy el ne felejtsem. Hátha majd S-es méretre akarok lefogyni <b>a tökéletesség határtalan</b>!',
lt27:   'Megrendelem az OneTwoSlim',
lt28:   '194 hozzászólás',
lt29:   'Varga Dóra',
lt30:   'Ez aztán az eredmény! A fotókon két különböző ember! Irigyellek!',
lt31:   '5 perce',
lt32:   'Hozzászólni',
lt33:   'Csillag Viki',
lt34:   'Amalia baba szia))) remekül nézel ki)!! Mondd el légyszi, hogy hogy vacsiztál, vagy vacsiztál+e egyáltalán este 6 után?',
lt35:   '7 perce',
lt36:   'Balla Amalia',
lt37:   'Viki, ne törd magad a kaján! Ha akartam enni – hát ettem, mégha este 9 óra is volt, egyszerűen gyorsan lettem jól lakott, így nem ettem túl magam...mikor strandozunk? Én állig felfegyverzett vagyok!',
lt38:   '11 perce',
lt39:   'Eszti Bartók',
lt40:   'Egy lélegzet alatt elolvastam a naplódat ))) én is próbáltam ilyet vezetni, így könnyebb fogyni, de aztán felmondtam a diétával és a naplóval is egyaránt...kipróbálom a te cuccodat, úgy sincs mit veszítenem)))',
lt41:   '14 perce',
lt42:   'Nagy Livi',
lt43:   'Amalia, a végeredmény szuper! Nagyon csini lettél! Gratula!))) ',
lt44:   '16 perce',
lt45:   'Veres Edit',
lt46:   'Bocsi, véletlenül találtam rá a naplódra és azt kell, hogy mondjam neked Amalia, hogy gyönyörű lettél. Megkérdezném, hogy nincs e káros hatása a hormon háztartásra? ',
lt47:   '17 perce',
lt48:   'Amalia, köszi, mindenképp megrendelem!))) PS:. Strandolni meg akkor megyünk, ha én is ilyen formákkal dicsekedhetek majd, mint te *___*',
lt49:   '18 perce',
lt50:   'Anita hercegnő<',
lt51:   '<u>Edit</u>, engem is érdekelt ez a kérdés, de valahol a neten olvastam, hogy&nbsp;a komplex aktíválja a valimiféle “sovány”hormonok múködését, amelyek&nbsp;a gyors anyagcseréért és az éhségérzet csökkentéséért felelnek. Ás ez teljesen veszélytelen és ,&nbsp;ami a legfontosabb, minden stressz hatás nélkül hat a szervezetre. Csak rendeljétek ne akárhol, hanem a  <a href="">hivatalos weboldalon</a> mert nálunk már megkezdték gyártani a hamisítványokat, a kollégám már pórul járt...Ezek meg az én eredményeim 1,5 hónap&nbsp;leforgása alatt.&nbsp;',
lt52:   '20 perce',
lt53:   'Bodrogi Tina',
lt54:   'Szuper. Az alkatod egyszerűen szuper. Azelőtt sem néztél ki rosszul, de a dundiság ilyen magasságnál egy kedves csajból is nagyanyót tud varázsolni, úgyhogy le a kalappal, hogy megpróbáltad, az eredmény magáért beszél!',
lt55:   '21 perce',
lt56:   'Horváth Veronika',
lt57:   'én még csak egy napja használom a kúrát, egyenlőre még nem nagyon kényelmes egyfolytában figyelgetni magam után, de hozzá fogok szokni. Remélem az eredmény nemsokára láthatóvá válik',
lt58:   '25 perce',
lt59:   'Pető Hanna',
lt60:   'Csajszikák, és ilyen hastól megtudnák szabadulni? Belefáradtam már ezekbe a kozmetikai eljárásokba, szeretnék már valamilyen hatást elérni',
lt61:   '23 perce',
lt62:   'Kerti Viola',
lt63:   'Ó, igen, hallottam már erről a kúráról, de azt hittem, hogy csak valahol receptre adják. Ez a weboldal meg szerinten a hivatalos magyarországi forgalmazó honlapja. Szupi, szeretném mindenképp magamon kipróbálni!',
lt64:   '24 perce',
lt65:   'Balassy Georgina',
lt66:   '<u>Hanna</u>, nekem szülés után még rosszabb volt, neked elég feszes a bőröd, úgyhogy biztosan segít majd. Én a komplexet &nbsp;4 hétig használtam, amíg végül is felhagyatm szégyelni a testemet)',
lt67:   '34 perce',
lt68:   'Anita vagyok',
lt69:   'Hááát... valahogy nem hiszek én ebben. Inkább felemeltétek volna a feneketeket a kanapéról és mentetek volna edzőterembe, minthogy ilyen csodaszerekre költeni.',
lt70:   '39 perce',
lt71:   'Gyerekkori álom)',
lt72:   'Nem mindenkinek van módja edzőtermekbe járni, minek ilyen szavakkal dobálózni',
lt73:   '41 perce',
lt74:   'Fejes Réka',
lt75:   'Hol rendelhető meg? Mennyibe kerül? Válaszoljatok, sürgősen le kell fogynom szabadságig )))!',
lt76:   '1 órája',
lt77:   'Egyedi Nóra',
lt78:   'Köszi a leírást!&nbsp;Az eredményeddel&nbsp;felturbóztál engem is a fogyásra :)&nbsp;Sokáig tartottam magma a diétához és ennek ellenére cask 3 kg-ot szabadultam meg..se erőm, se motivációm ilyen eredménnyel....&nbsp;kipróbálom a te módszeredet is. A kúrát lehet sokáig fogyasztani?',
lt79:   '1 órája',
lt80:   'Balla Amalia',
lt81:   '<u><a href="">Nóra</a></u>, Akár lvekig, amíg le nem fogysz)) Viccelek, persze. De ami igaz, az igaz, a kúra nincs időhöz kötve. Amint eléred a kívánt hatást, hagyj fel vele. Természetesen fanatizmus nélkül.Mert nem egy ember van, aki a mértéktelen fogyásvágytól anorexiás lett.',
lt82:   '54 perce',
lt83:   'Kaszás Emőke',
lt84:   'Amalia, gyönyörű vagy! Már rég olvastam az OneTwoSlim, de az ismerőseim közül senkitől sem hallottam és nem rizikóztam a véres verejtékkel megkeresett pénzecskémmel. Most már megveszem! Te leszel a motivációm!',
lt85:   '51 perce',
lt86:   'Edényi Via',
lt87:   'Sziasztok! Én is sokat kínoztam magam, úgyan úgy mint Amalia, hogy mivel is fogyjak le. Végeredménybe, a sok felesleges és hatástalan múdszer után kipróbáltam ezt a komplexet, de csak azért, mert ez az egyetlen természetes anyagokból megalkotpzz készítmény. Nagyjából egy év telt el a fogyásom óta. Akkor ezt a szert még szinte senki sem ismerte.Valamivel több mint két hónap alatt fogytam le 18 kilogrammot.Az egész gardróbomat le kellett cserélnem!)))',
lt88:   'egy órája',
lt89:   'Katica drága',
lt90:   'Mit ért el a fejlődés! Ülsz, eszel és szemláthatóan fogysz. Csak a lányok ne vinnék túlzásba, mert ismerjük mi a mai fiatalságot – addig fogják nyúzni magukat, amíg a bőrünk a csontukhoz nem ragad, mert ugyebár kövérnek érzzik magukat a kis buták!.',
lt91:   'Ki mondta, hogy ez a szer nem hatékony és hogy ez mind asoronkövetkező humbukk? Minusz 10 kg 2 hét alatt! Én sem hittem benne, de a szer tényleg segített!',
lt92:   'Megrendelem az OneTwoSlim komplexet',
lt93:   'Szia! Amalia vagyok és te most az én privát blogomban jársz, ahol megosztom a saját tapasztalataimat, életemet, sikereimet és kudarcaimat.Helyezkedj el kényelmesen, és remélem összebarátkozunk :)',
lt94:   'Úgy döntöttem, hogy megosztom veletek a fogyi-naplómat, amelyben el szeretném mondani, hogyan is fogytam le, mit is csináltam a cél elérésével, és végeredményben hogyan is szabadultam meg 15 kg súlyfeleslegtől mindössze 3 hét alatt!',
lt95:   'Online bloggerek',
lt96:   'És még 279 fotó nélkül...',
lt97:   'Bejegyzések',
lt98:   'Hogyan FOGYTAM LE 36 kg-ot 6 hónap alatt',
lt99:   'Amalia Balla',
lt100:  '194 hozzászólás',
lt101:  'Értékeld a fotót',
lt102:  '18 hozzászólás',
lt103:  'Milyen táppal kezdjük etetni...',
lt104:  '9 hozzászólás',
lt105:  'Budapesten kisütött a nap!',
lt106:  '64 комментария',
lt107:  'Ki jön velünk a tengerre?) lehet-e napozni a gyerekekkel',
lt108:  '33 hozzászólás',
lt109:  'A férjem macskát akar, mit tegyek?',
lt110:  '98 hozzászólás',
lt111:  'Sziasztok. Most jöttem meg Balassagyarmatról',
lt112:  '51 hozzászólás',
lt113:  'Hogyan tanultam meg olaszul?',
lt114:  '17 комментариев',
lt115:  'Balla Amalia blogja',
};

function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};