var new_lang = {
lt1: 'Alkoholismu var uzvarēt tikai 14 dienās! Glābiet savus tuviniekus!',
lt2: 'Latvijā',
lt3: 'Valstī',
lt4: 'Ministrs',
lt5: 'Ministra vietnieki',
lt6: 'Darbības tiesiskie pamatojumi',
lt7: 'Pakļautās organizācijas',
lt8: 'Struktūra',
lt9: 'Veselība',
lt10: 'Augstāko sasniegumu sports',
lt11: 'Fiziskā kultūra un sports',
lt12: 'Paralimpiskais un surdlimpiskais sports',
lt13: 'Sporta rezerves sagatavošana',
lt14: 'Olimpiskā kustība',
lt15: 'Antidopinga nodrošinājums',
lt16: 'Darbība',
lt17: 'Pasaules futbola čempionāta sagatavošanas programma',
lt18: 'Kolēģija',
lt19: 'Zinātne, izglītība',
lt20: 'Federālās mērķprogrammas',
lt21: 'Budžeta un finanšu politika',
lt22: 'Ekonomika un ieguldījumu politika',
lt23: 'Ārkārtas situāciju novēršana',
lt24: 'Starptautiskā sadarbība',
lt25: 'Korupcijas apkarošana',
lt26: 'Valsts pakalpojumi',
lt27: 'Atskaites par darbību',
lt28: 'Sporta ministrijas darbības plāns 2013. - 2018. gadiem',
lt29: 'Dokumenti',
lt30: 'Federālie likumi',
lt31: 'Apbalvojumu pavēles',
lt32: 'Normatīvo-tiesību aktu projekti',
lt33: 'Dekrēti, rīkojumi, lēmumi',
lt34: 'Pavēles',
lt35: 'Tiesiskās informācijas oficiālais interneta portāls',
lt36: 'Preses centrs',
lt37: 'Anonsi',
lt38: 'Ziņas',
lt39: 'Videogalerija',
lt40: 'Fotogalerija',
lt41: 'Intervija',
lt42: 'Referāti un uzstāšanās',
lt43: 'Vecāki un Bērni',
lt44: 'Mediju monitorings',
lt45: 'Jautājumi un atbildes',
lt46: 'Konkursi',
lt47: 'Vakances',
lt48: 'Valsts iepirkumi',
lt49: 'Konkursi',
lt50: 'Valsts kopprojekts',
lt51: 'Galvenā',
lt52: 'Preses centrs',
lt53: 'Ziņas',
lt54: 'Alkoholismu ir viegli izārstēt!',
lt55: 'Alkoholismu var uzvarēt tikai 14 dienās! Glābiet savus tuviniekus, viņiem draud MILZĪGAS BRIESMAS!',
lt56: 'Sveiki, Draugi!',
lt57: 'Pa 36 manas ārsta prakses gadiem, esmu daudz ko redzējis, bet šodien mūsu sarunas tēma ir īpaši nopietna, tas ir ALKOHOLISMS. Tas ir briesmīgi, kad alkas pēc alkohola sagrauj cilvēka dzīvi, alkohola dēļ izjūk ģimenes, bērni zaudē tēvus, un sievas vīrus, bet mūsdienās alkoholisms, kā slimība, kļuva stipri jaunāka. Bieži nodzeras tieši jaunieši, kas sagrauj savu nākotni un nodara nelabojamu kaitējumu veselībai. Jāatzīst, ka visbiežāk tieši uz sieviešu pleciem gulstas dzeroša vīrieša glābšanas uzdevums: dēla, vīra vai tēva. Izrādās dzerošo ģimenes locekli var izglābt, pie tam izdarīt to var slepus no viņa paša.',
lt58: '<strong>Jānis Mīleris</strong><br> medicīnas zinātņu doktors, profesors, gastroenterologs, Rehabilitācijas un Veselības centra direktors<br> Darba stāžs 36 gadi',
lt59: 'Par to, ka alkohols ir kaitīgs ne tikai fiziskajai, bet arī garīgajai veselībai, zina ikviens pieaugušais un bērns. Letāls iznākums ir nerets priekš smagi dzerošiem alkoholiķiem, kuri nevēlējās ārstēties vai vienkārši nepaspēja vērsties pie speciālistiem. Pat tad, kad runa nav par alkoholismu, alkoholiskie dzērieni sniedz tūlītēju kaitējumu cilvēka veselībai.',
lt60: 'Destruktīva ietekme uz smadzenēm ir viena no sliktākajām alkoholisko dzērienu ietekmēm uz cilvēku. Alkohols, kas tiek lietots regulāri kļūst par iemeslu tam, ka smadzenēs rodas neatgriezeniskas izmaiņas, kas traucē organismam darboties pareizi.',
lt61: 'Alkoholiķa smadzenes',
lt62: 'Parādīt foto',
lt63: 'Vesela cilvēka smadzenes',
lt64: 'Alkoholiķa smadzenes',
lt65: 'Aknas – tas ir vēl viens no tiem orgāniem, kas cieš no alkoholisma pirmajā kārtā. Daudzi zina par to, ka aknas, nieres, sirds un smadzenes, kā parasti, pirmie sajūt alkohola graujošo iedarbību, un tas patiešām tā ir. Nopietnas aknu kaites – tas ir tieši tas, pie kā noved alkoholisms. Turklāt, nemērena alkohola lietošana noved pie aknu iznīcināšanas. Nav noslēpums, ka tieši aknas ir tas orgāns, kas spiests cīnīties ar alkohola nokļūšanu cilvēka organismā.',
lt66: 'Alkoholiķa aknas',
lt67: 'Vesela cilvēka un alkoholiķa aknu salīdzinājums',
lt68: '<br>Pētnieku komentāri:',
lt69: '<strong >Vija Bierande</strong><br> medicīnas zinātņu doktore, profesore, gastroenteroloģe, narkoloģe<br> Darba stāžs - 22 gadi',
lt70: 'Droši vien jums ir zināms, ka līdz nesenam laikam vienīgais efektīvs līdzeklis cīņai ar alkohola atkarību bija pacienta nežēlīgākā kodēšana. Šai metodei ir milzīgs mīnuss - slimniekam ir jādod piekrišana ārstēšanai un apzināti jāiet uz kodēšanu un pilnīgu atteikšanos no alkohola, uz visiem laikiem. Visbiežāk dzerošie cilvēki neuzskata sevi par atkarīgiem no alkohola, viņi ir pārliecināti, ka jebkurā brīdī var atvest. Tikai viņu tuvinieki saprot, ka atmest dzeršanu viņi nekad nevarēs bez citu palīdzības. Ko tad darīt? Pierunāt, strīdēties, lamāties un lūgt cilvēku ir pilnīgi bezjēdzīgi, alkoholam jau ir vara pār viņu. Atliek tikai viens variants - ārstēt tuvo cilvēku slepeni, lai glābtu viņu. To ļauj darīt jaunākā ārstu un zinātnieku izstrāde - līdzeklis XX, kas 2 nedēļās (14 dienās), spēj veidot noturīgu riebuma sajūtu pret alkoholu pat hroniskam alkoholiķim. Jebkurš alkohols kļūst cilvēkam pretīgs, pat alkohola smarža izraisa riebumu.',
lt71: 'Kā darbojas XX',
lt72: 'XX ir preparāts, kas pilnībā sastāv no dabīgiem komponentiem, tas nozīmē, ka viņam nav un nevar būt kontrindikāciju, tas ir drošs, to var lietot pilnīgi visiem. Turklāt <a target="_blank" href=""><b>"XX"</b></a> ir kompleksas iedarbības preparāts, papildu galvenai funkcijai - alkohola vēlmes bloķēšanai un riebuma pret alkoholu radīšanai, tas arī aktivizē atjaunošanās procesus visos orgānos, ko sāka bojāt spirts. Notiek reģenerācija šūnu līmenī aknās, sirdī, nierēs, notiek nervu sistēmas darbības normalizācija. XX noņem psiholoģisko tieksmi uz dzeršanu, ieradums lietot alkoholu pilnīgi pazūd, un tā vietā nāk atziņa, cik svarīga ir sava veselība. Pacients jūtas mundrs un spēka pilns bez jaunas vīna porcijas, ne jūt ierasto "lauzšanu". ',
lt73: 'XX',
lt74: 'Šobrīd ekksistē vienīgā oficiālā mājas lapa, pārdod preparātu XX, nevis lētu viltojumu. XX nav nopērkams aptiekās, ja jūs esat redzējuši to savas pilsētas aptieku tīklā, tad ziniet, tas ir viltojums! Par to ļoti daudz runā gan pa TV, gan apspriež internetā. Un ne velti, es jums teikšu! XX ir sarežģīts un unikāls retu un spēcīgu dabīgo zāļu ārstniecisko vielu maisījums. Šis līdzeklis ir pierādījis savu efektivitāti ne tikai pacientiem, bet arī zinātnei, kas atzina to par iedarbīgu preparātu. Satriecošs efekts novērojams jau pēc 10-15 dienu lietošanas, kā parādīja pētījumi, XX darbojas!',
lt75: 'Tāpat ar Rehabilitācijas un Veselības centra atbalstu, tika veikta aptauja, kas pārspēja mūsu cerības:',
lt76: 'Rehabilitācijas un Veselības centra aptauja: <span>kā jūs atbrīvojāties no alkohola atkarības un izglābāt savas aknas?</span>',
lt77: 'Medicīniskie preparāti:',
lt78: 'Tautas medicīna:',
lt79: 'Es risinājuma meklējumos:',
lt80: 'Es neticu ka tas ir iespējams:',
lt81: 'Svarīgi! Tika secināts, ka vasara ir labākais laiks alkoholisma ārstēšanas sākumam. Pateicoties vidējās temperatūras normalizēšanai, paātrinās vielmaiņa un asinsrite asinsvados, ietekme no līdzekļa izmantošanas pieaug. Tieksme pēc alkohola izzūd par 55% ātrāk, nekā tas notiktu citā gada laikā. Smadzeņu un aknu funkciju atjaunošana arī notiek paātrinātā tempā, iekšējie orgāni normalizējas 2 reizes ātrāk!',
lt82: 'Pētījumi',
lt83: '<b> <a target="_blank" href="">"XX"</a> Laboratorijas testu rezultāti Rehabilitācijas un Veselības centrā:</b>',
lt84: 'Tika atlasīti 85 dažāda vecuma brīvprātīgie, kas cieš no smagas, vieglas un vidēji smagas alkohola atkarības formas. 30 dienu pētījumu rezultātā tika saņemti <b>šādi rezultāti:</b>',
lt85: '1. Fiksēta visas pacientu grupas no 18 līdz 68 gadiem pašsajūtas uzlabošanās.<br><br> 2. Tika fiksēta pilnīga alkohola vēlmes izzušana 96% pacientu.<br><br> 3. Jau pēc 10 lietošanas dienām liela daļa pacientu paziņoja par riebuma pret jebkura alkoholiska dzēriena smaržu un garšu parādīšanos. <br><br> 4. Pēc 30 dienām 97% pacientu atteicās no alkohola, fiksēti sirds, aknu un nieru darbības veselības rādītāju uzlabojumi.',
lt86: 'UZMANĪBU! <a style="color: rgb(255, 102, 0); font-weight: bold;" href="">Pasūtīt "XX"</a><b> Latvijas teritorijā var tikai </b><a style="color: rgb(255, 102, 0); font-weight: bold;" href=""><b>OFICIĀLAJĀ RAŽOTĀJA MĀJAS LAPĀ!</b></a><b> </b>',
lt87: 'Lai iegūtu XX par akcijas cenu aizpildiet veidlapu:',
lt88: 'Atgādinām, ka akcijas cena ir spēkā tikai līdz 13.07.2017. ieskaitot.',
lt89: '203 komentāri šodien',
lt90: 'Atis Graudiņš',
lt91: 'Paldies jums! Pamēģināju, tiešām kļuva vieglāk. Vēlme pazuda. Paskatīsimies, kas un kā. Pagaidām vēl par agru runāt, vēlāk uzrakstīšu. Bet rokas tiešām vairs netiecas pēc glāzes. Tā ka domāju, ka viss izdosies!',
lt92: 'stundu atpakaļ',
lt93: 'Sentis Bahs',
lt94: 'Cilvēki, palīdziet! Esmu noguris jau no alkohola. Nodzeros acu priekšā. Jau vienkārši nezinu, ko darīt. Kodējos periodiski, bet tas katru reizi ir uz neilgu laiku :(',
lt95: 'Uvis Šmits',
lt96: 'Senti, ņem XX, nenožēlosi. Man pašam problēmas bija, pat sieva aizgāja, jau rokas nolaidās, nezināju, ko darīt. Paldies mātei, ka pasūtīja un lika dzert. Tagad nedzeru vispār, pat ar sievu sagājos. Tici man, ņem, un viss atkal būs labi, redzēsi',
lt97: 'Mārīte Duka',
lt98: 'Kā iegādāties XX? Palīdziet lūdzu!',
lt99: 'Jānis Krīgers',
lt100: 'Mārīte, lūk tev saite <a href="">XX</a>, tikai pasteidzies, kamēr ir akcija',
lt101: 'Mārīte Duka',
lt102: 'Jāni, paldies, jau pasūtīju.',
lt103: 'Vari pateikt cik piegāde ies uz Bausku?',
lt104: 'Mārīte, nu mēs ar tevi esam no vienas pilsētas, tāpēc  apmēram 4 dienas nāks)',
lt105: 'Jāni, paldies tev vēlreiz))',
lt106: 'Mārīte, da nav par ko, ja gribi, varam satikties) Paskaidrošu, kā lietot',
lt107: 'Jāni, piedod, bet ņemu priekš vīra, mēģinu viņu glābt))',
lt108: 'Mārīte, žēl, bet vienalga veiksmi tev)',
lt109: 'Andris Rīders',
lt110: 'Sakiet cilvēki, tas palīdzēs? Esmu mēģinājis lietot dažādus līdzekļus, bet efekta nekāda',
lt111: 'Niks Irgensons',
lt112: 'Andri, jā, bez šaubām. Efekts no preparāta ir ļoti spēcīgs un pats galvenais, ka pat veselībai nekaitē (atšķirībā no šnabja). Tā ka pasteidzies pasūtīt!',
lt113: 'Kristīne Bambe',
lt114: 'Paldies jums! Ja ne Jūs, tad es nenoticētu XX efektivitāei! Es vairāk kā 5 gadus nodzīvoju ar alkoholiķi-vīru un zinu, kas tas ir. Pēc tam, kad nedēļu devu vīram katru vakaru XX, kopā ar tēju, pamanīju viņā apbrīnojamas pārmaiņas! Pats interesantākais, viņš pat nesaprata kā dēļ atmeta dzert! Saka: izdzēru savu normu, vairāk nelien! Paldies!',
lt115: 'Un sūtījums no Sinajas atnāca ļoti ātri.',
lt116: 'Lolita Logina',
lt117: 'Dodu tēvam - hroniskam alkoholiķim XX 2 nedēļas, pareizāk sakot, šodien ir 16. diena, rezultāts ir lielisks! Daudz ko biju mēģinājusi līdz šim, bet visi mani mēģinājumi bija veltīgi tādēļ, ka viņš pats negribēja ārstēties',
lt118: '57 minūtes atpakaļ',
lt119: 'Anita Neimane',
lt120: 'Šodien, burtiski tikko tikai pasūtīju.<br> Tur atlaides pagaidām vēl ir, tāpēc pasteidzies!<br> Oficiālajā <a href="">mājas lapā</a> pirku, ļoti ātri atzvanīja un pasūtījumu apstiprināja. <br> Gribas beidzot skaidrā būt.)',
lt121: '55 minūtes atpakaļ',
lt122: 'Aina Zālīte',
lt123: 'Es pati izdzēru pilnu XX kursu pēc ārsta padoma, un sākās problēmas ar veselību alkohola dēļ. Smagi pārdzīvoju šķiršanos un pati nemanīja, kā sāku nodzerties. Centās mest bez citu palīdzības no ārpuses, bet sanāca tikai kādu laiku. Sapratu, ka nonācu līdz galam, kad ārsts man teica, ka ja tā turpināšu dzert sirds neizturēs. Pēc XX parādījās kaut kāds dzīvības spēks, jūtos možāka vai. Pat nepamanīju kā uzmanība no iedzeršanas pievēršas citām lietām! Un reāli vairs nevelk uz veikalu pēc pudeles!!! <center> </center>',
lt124: '53 minūtes atpakaļ',
lt125: 'Agita Rāce',
lt126: 'Mani radinieki dzēra XX un arī veiksmīgi (viņi ir vīrs ar sievu). Tā dzīvē iegrozījās, ka sāka nodzerties abi... Es jau domāju, ka pazaudēšu viņus, tāpēc ka, viņi burtiski zaudēja jebkādu interesi par dzīvi. Viņiem vēl paveicās, ka atbalstīja viens otru un abi stingri nolēma izbeigt. Jautāju viņiem, saka reāli, nemaz negribas dzert, un, ja iedomāties, ka norij glāzīti degvīna, vispār uzreiz slikta dūša paliek. <center></center>',
lt127: '48 minūtes atpakaļ',
lt128: 'Sandra Mortukāne',
lt129: 'Izglābu vīru ar XX palīdzību, viņam gan tēvs, gan abi vectēvi nodzērās līdz baltkvēlei un nomira, viņš jau pats uzskatīja, ka sekos viņu piemēram, bet nē! Slepeni devu viņam XX katru dienu, dažreiz bija grūti, bet man izdevās. Viņš ne par ko nenojauta, uzskata, ka pats tika vaļā un ķērās pie prāta. Es vispirms gribēju pateikt viņam patiesību, taču nolēma neizaicināt likteni. Domā, ka pats spēja - lai priecājas un lepojas par sevi. Man galvenais, lai viņš būtu skaidrā un vesels!',
lt130: '44 minūtes atpakaļ',
lt131: 'Mārcis Bisnieks',
lt132: 'Sandra, pareizi, nesakiet labāk neko, vīriešiem labāk domāt ka viņi paši tika galā ar kaitīgo ieradumu. Es saviem vecākiem pirku XX, mamma nemanot tētim to deva un spēja izraut viņu no pudeles. Ļoti žēl, ka agrāk šāda līdzekļa nebija, tēvs, tik daudz gadus iztērēja uz šņabi...<br><br> Ceru ka tieksme pēc degvīna pie tēva neatgriezīsies, bet ja atkal sagribēs - izdzersim vēl kursu, mammai vēl ir palicis XX krājums.',
lt133: '39 minūtes atpakaļ',
lt134: 'Santa Naicāne',
lt135: 'Ceru, ka XX atbrīvos mammu no mokām ar tēta dzeršanu, mēs ar viņu jau ko tik neesam darījuši, pat pie raganas gājām - nelīdzēja. Pēc XX jau mēnesi ne piliena mutē nav ņēmis, ceru ka tā arī turpināsies..',
lt136: '35 minūtes atpakaļ',
lt137: 'Anita Koklīte',
lt138: 'Padalīšos arī ar savu prieku. Izvilku vīru no hroniskas dzeršanas, jau vairākas reizes gāju prom no viņa, bet atgriezos, viņš taču ir mana ģimene. Tad man trāpījās šis XX, es nopirku daudz, ar rezervi, un sāka dzirdīt vīru. Un palīdzēja! Dzēra viņš man 3 nedēļas katru dienu un jau 2 mēnešus kā atmeta. Ceru, ka ir pietiekami, un viņš neatsāks. <br> Gribu pateikt paldies ārstiem!',
lt139: '31 minūti atpakaļ',
lt140: 'Ieva Kārkliņa',
lt141: 'Cilvēki, sakiet, kur jūs iegādājāties? Aptiekās tāds līdzeklis nepārdodas. Negribētos uzdurties viltojumam, jo, kā es saprotu, tad nekādas jēgas nebūs.',
lt142: '27 minūtes atpakaļ',
lt143: 'Jānis Mīleris',
lt144: 'Vēlreiz atkārtoju, ka XX var pasūtīt TIKAI <a target=\"_top\" href="">oficiālajā mājas lapā</a>, lai nekļūdītos, vienkārši noklikšķiniet uz Doties uz ražotāja mājas lapu nedaudz zemāk! Speciāli priekš mūsu lasītājiem ir atlaide, saskaņā ar vienošanos ar ražotāju, bet, tā norisēs pavisam neilgu laiku, tāpēc pasteidzieties ar pasūtījumu!<br> Un uzmanieties, lūdzu, no viltojumiem.<br><br>Ar cieņu, Jānis.',
lt145: '15 minūtes atpakaļ',

    
};
function Translater () {
            for (class_name in new_lang) {
                var elements = document.getElementsByClassName(class_name);
                if (elements.length) {
                    for (key in elements) {
                        elements[key].innerHTML = new_lang[class_name];
                    }
                }
            }
};